import { describe, expect, it } from 'vitest';
import { LocalSearchProvider } from '../electron/webSearch/localSearchProvider.mjs';
import { SearchService } from '../electron/webSearch/searchService.mjs';

const randomUserSearchCases = [
  ['tailscale', 'what is Tailscale official site', ['tailscale.com']],
  ['signal', 'Signal desktop download official', ['signal.org/download']],
  ['obs', 'OBS Studio download official', ['obsproject.com/download']],
  ['ffmpeg', 'FFmpeg official documentation', ['ffmpeg.org/documentation']],
  ['pnpm', 'pnpm installation official docs', ['pnpm.io/installation']],
  ['bun', 'Bun install official docs', ['bun.sh/docs/installation']],
  ['deno', 'Deno install official docs', ['docs.deno.com/runtime/getting_started/installation']],
  ['electron', 'Electron app framework official docs', ['electronjs.org/docs']],
  ['tauri', 'Tauri official docs', ['tauri.app']],
  ['svelte', 'Svelte official docs', ['svelte.dev/docs']],
  ['astro', 'Astro framework official docs', ['docs.astro.build']],
  ['nuxt', 'Nuxt official documentation', ['nuxt.com/docs']],
  ['hono', 'Hono web framework official docs', ['hono.dev']],
  ['fastapi', 'FastAPI official docs', ['fastapi.tiangolo.com']],
  ['django', 'Django official documentation', ['docs.djangoproject.com']],
  ['flask', 'Flask official documentation', ['flask.palletsprojects.com']],
  ['go', 'Go programming language download official', ['go.dev/dl']],
  ['rustup', 'rustup install official', ['rustup.rs']],
  ['ollama', 'Ollama download official', ['ollama.com/download']],
  ['lmstudio', 'LM Studio download official', ['lmstudio.ai/download']],
  ['vllm', 'vLLM official docs', ['docs.vllm.ai']],
  ['open-webui', 'Open WebUI GitHub official', ['github.com/open-webui/open-webui']],
  ['home-assistant', 'Home Assistant official docs', ['home-assistant.io/docs']],
  ['proxmox', 'Proxmox VE download official', ['proxmox.com/en/downloads']],
  ['fedora', 'Fedora workstation download official', ['fedoraproject.org/workstation/download']],
  ['archwiki', 'Arch Linux wiki official', ['wiki.archlinux.org']],
  ['obsidian', 'Obsidian download official', ['obsidian.md/download']],
  ['notion', 'Notion desktop app download official', ['notion.com/desktop']],
  ['slack', 'Slack desktop download official', ['slack.com/downloads']],
  ['discord', 'Discord download official', ['discord.com/download']],
  ['telegram', 'Telegram desktop download official', ['desktop.telegram.org']],
  ['blender', 'Blender download official', ['blender.org/download']],
  ['godot', 'Godot engine download official', ['godotengine.org/download']],
  ['unreal', 'Unreal Engine download official', ['unrealengine.com']],
  ['krita', 'Krita download official', ['krita.org']],
  ['gimp', 'GIMP download official', ['gimp.org/downloads']],
  ['inkscape', 'Inkscape download official', ['inkscape.org']],
  ['calibre', 'Calibre ebook download official', ['calibre-ebook.com/download']],
  ['qbittorrent', 'qBittorrent download official', ['qbittorrent.org/download']],
  ['passport-renewal', 'US passport renewal official', ['travel.state.gov/content/travel/en/passports/have-passport/renew-online.html']],
  ['irs-refund', 'IRS refund status official', ['irs.gov/wheres-my-refund']],
  ['ssa', 'Social Security my account official', ['ssa.gov/myaccount']],
  ['medicare', 'Medicare official sign up', ['medicare.gov/basics/get-started-with-medicare/sign-up']],
  ['cdc-covid', 'CDC COVID vaccine official', ['cdc.gov/covid/vaccines']],
  ['who', 'WHO official website', ['who.int']],
  ['weather-nws', 'National Weather Service official forecast', ['weather.gov']],
  ['irs-tax-brackets', 'IRS tax brackets 2026 official', ['irs.gov/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026']],
  ['github-desktop', 'GitHub Desktop official download', ['desktop.github.com/download']],
  ['vscode', 'VS Code download official', ['code.visualstudio.com/download']],
  ['docker', 'Docker Desktop download official', ['docker.com/products/docker-desktop']],
  ['postman', 'Postman download official', ['postman.com/downloads']],
  ['zoom', 'Zoom download official', ['zoom.com/en/download']],
  ['nodejs', 'Node.js download official', ['nodejs.org/en/download']],
  ['typescript', 'TypeScript handbook official', ['typescriptlang.org/docs/handbook']],
  ['vite', 'Vite official docs', ['vite.dev', 'vitejs.dev']],
  ['react', 'React official docs', ['react.dev']],
  ['vue', 'Vue official guide', ['vuejs.org']],
  ['nextjs', 'Next.js official docs', ['nextjs.org/docs']],
  ['remix', 'Remix official docs', ['remix.run/docs']],
  ['tailwind', 'Tailwind CSS official docs', ['tailwindcss.com/docs']],
  ['eslint', 'ESLint official docs', ['eslint.org/docs']],
  ['prettier', 'Prettier official docs', ['prettier.io/docs']],
  ['vitest', 'Vitest official docs', ['vitest.dev']],
  ['jest', 'Jest official docs', ['jestjs.io']],
  ['docker-compose', 'Docker compose official docs', ['docs.docker.com/compose']],
  ['kubernetes', 'Kubernetes official docs', ['kubernetes.io/docs']],
  ['mysql', 'MySQL official docs', ['dev.mysql.com/doc']],
  ['redis', 'Redis official docs', ['redis.io/docs']],
  ['nginx', 'nginx official docs', ['nginx.org', 'docs.nginx.com']],
  ['cloudflare', 'Cloudflare docs official', ['developers.cloudflare.com']],
  ['github-actions', 'GitHub Actions official docs', ['docs.github.com/actions']],
  ['gitlab-ci', 'GitLab CI official docs', ['docs.gitlab.com/ci']],
  ['vercel', 'Vercel docs official', ['vercel.com/docs']],
  ['netlify', 'Netlify docs official', ['docs.netlify.com']],
  ['supabase', 'Supabase docs official', ['supabase.com/docs']],
  ['firebase', 'Firebase docs official', ['firebase.google.com/docs']],
  ['linear', 'Linear app official', ['linear.app']],
  ['figma', 'Figma download official', ['figma.com/downloads']],
  ['brave', 'Brave browser download official', ['brave.com/download']],
  ['firefox', 'Firefox download official', ['mozilla.org/firefox']],
  ['usps', 'USPS tracking official', ['usps.com', 'tools.usps.com']],
  ['uscis', 'USCIS case status official', ['egov.uscis.gov']],
  ['tsa', 'TSA PreCheck official', ['tsa.gov/precheck']],
  ['dmv-ny', 'New York DMV official', ['dmv.ny.gov']],
  ['ftc', 'FTC report fraud official', ['reportfraud.ftc.gov']],
  ['cisa', 'CISA KEV catalog official', ['cisa.gov/known-exploited-vulnerabilities-catalog']],
  ['nvd', 'NVD CVE official', ['nvd.nist.gov']],
  ['mitre', 'MITRE ATT&CK official', ['attack.mitre.org']],
  ['npm-package', 'npm react package official', ['npmjs.com/package/react']],
  ['pypi', 'PyPI requests package official', ['pypi.org/project/requests']],
  ['crates', 'crates.io serde package official', ['crates.io/crates/serde']],
  ['php', 'PHP official docs', ['php.net/docs']],
  ['composer', 'Composer PHP install official', ['getcomposer.org/download']],
  ['laravel', 'Laravel official docs', ['laravel.com/docs']],
  ['rails', 'Ruby on Rails official guides', ['guides.rubyonrails.org']],
  ['ruby', 'Ruby programming language download official', ['ruby-lang.org']],
  ['dotnet', '.NET download official', ['dotnet.microsoft.com/en-us/download']],
  ['csharp', 'C# language docs official', ['learn.microsoft.com/dotnet/csharp']],
  ['flutter', 'Flutter official docs', ['docs.flutter.dev']],
  ['dart', 'Dart language official docs', ['dart.dev/language']],
  ['android-studio', 'Android Studio download official', ['developer.android.com/studio']],
  ['terraform', 'Terraform official docs', ['developer.hashicorp.com/terraform/docs']],
  ['ansible', 'Ansible official docs', ['docs.ansible.com']],
  ['helm', 'Helm official docs', ['helm.sh/docs']],
  ['prometheus', 'Prometheus official docs', ['prometheus.io/docs']],
  ['grafana', 'Grafana official docs', ['grafana.com/docs']],
  ['elasticsearch', 'Elasticsearch official docs', ['elastic.co/docs', 'elastic.co/guide']],
  ['mongodb', 'MongoDB official docs', ['mongodb.com/docs']],
  ['opencv', 'OpenCV official docs', ['docs.opencv.org']],
  ['tensorflow', 'TensorFlow official install', ['tensorflow.org/install']],
  ['huggingface', 'Hugging Face transformers docs official', ['huggingface.co/docs/transformers']],
  ['langchain', 'LangChain docs official', ['docs.langchain.com', 'python.langchain.com/docs']],
  ['llamaindex', 'LlamaIndex docs official', ['docs.llamaindex.ai']],
  ['anthropic', 'Anthropic API docs official', ['docs.anthropic.com']],
  ['ollama-api', 'Ollama API docs official', ['github.com/ollama/ollama/blob/main/docs/api.md', 'github.com/ollama/ollama']],
  ['7zip', '7-Zip download official', ['7-zip.org/download']],
  ['etcher', 'balenaEtcher download official', ['etcher.balena.io']],
  ['virtualbox', 'VirtualBox download official', ['virtualbox.org/wiki/Downloads']],
  ['wireguard', 'WireGuard official install', ['wireguard.com/install']],
  ['wireshark', 'Wireshark download official', ['wireshark.org/download']],
  ['filezilla', 'FileZilla download official', ['filezilla-project.org/download']],
  ['libreoffice', 'LibreOffice download official', ['libreoffice.org/download']],
  ['audacity', 'Audacity download official', ['audacityteam.org/download']],
  ['handbrake', 'HandBrake download official', ['handbrake.fr/downloads']],
  ['obsidian-sync', 'Obsidian Sync official', ['obsidian.md/sync']],
  ['owasp', 'OWASP Top 10 official', ['owasp.org/www-project-top-ten']],
  ['letsencrypt', 'Let\'s Encrypt official docs', ['letsencrypt.org/docs']],
  ['mozilla-ca', 'Mozilla CA certificate program official', ['wiki.mozilla.org/CA']],
  ['irs-w4', 'IRS W-4 form official', ['irs.gov/forms-pubs/about-form-w-4']],
  ['usagov', 'USA.gov official benefits', ['usa.gov/benefits']],
  ['nih', 'NIH PubMed official', ['pubmed.ncbi.nlm.nih.gov']],
  ['fda-drugs', 'FDA drugs official database', ['accessdata.fda.gov/scripts/cder/daf']],
  ['clinicaltrials', 'ClinicalTrials.gov official', ['clinicaltrials.gov']],
  ['copyright', 'US copyright registration official', ['copyright.gov/registration']],
  ['sec-edgar', 'SEC EDGAR company search official', ['sec.gov/search-filings']],
  ['data-gov', 'data.gov official', ['data.gov']],
  ['archive', 'Internet Archive official', ['archive.org']],
  ['wikipedia', 'Wikipedia official', ['wikipedia.org']],
  ['wikidata', 'Wikidata official', ['wikidata.org']],
  ['stackoverflow', 'Stack Overflow official', ['stackoverflow.com']],
  ['steam', 'Steam download official', ['store.steampowered.com/about']],
  ['epic', 'Epic Games launcher download official', ['store.epicgames.com/download']],
  ['github-cli', 'GitHub CLI download official', ['cli.github.com']],
  ['powershell', 'PowerShell install official docs', ['learn.microsoft.com/powershell']],
  ['windows11', 'Windows 11 download official', ['microsoft.com/software-download/windows11']],
  ['ubuntu-server', 'Ubuntu Server download official', ['ubuntu.com/download/server']],
  ['debian', 'Debian download official', ['debian.org/distrib']],
  ['alpine', 'Alpine Linux download official', ['alpinelinux.org/downloads']],
  ['nixos', 'NixOS download official', ['nixos.org/download']],
  ['nix', 'Nix package manager install official', ['nixos.org/download', 'nix.dev/install-nix']],
  ['node-api', 'Node.js fs API official docs', ['nodejs.org/api/fs']],
  ['bun-api', 'Bun API docs official', ['bun.sh/docs/api']],
  ['deno-api', 'Deno API docs official', ['docs.deno.com/api']],
  ['go-doc', 'Go net/http package official docs', ['pkg.go.dev/net/http']],
  ['rust-std', 'Rust std library official docs', ['doc.rust-lang.org/std']],
  ['python-asyncio', 'Python asyncio official docs', ['docs.python.org/3/library/asyncio']],
  ['java-stream', 'Java Stream API official docs', ['docs.oracle.com', 'java/util/stream']],
  ['spring', 'Spring Boot official docs', ['docs.spring.io/spring-boot']],
  ['maven', 'Maven official download', ['maven.apache.org/download']],
  ['gradle', 'Gradle install official docs', ['gradle.org/install']],
  ['apache', 'Apache HTTP Server docs official', ['httpd.apache.org/docs']],
  ['tomcat', 'Apache Tomcat download official', ['tomcat.apache.org/download']],
  ['postgres-download', 'PostgreSQL download official', ['postgresql.org/download']],
  ['sqlite-download', 'SQLite download official', ['sqlite.org/download']],
  ['mariadb', 'MariaDB download official', ['mariadb.org/download']],
  ['minio', 'MinIO docs official', ['min.io/docs']],
  ['rabbitmq', 'RabbitMQ official docs', ['rabbitmq.com/docs']],
  ['kafka', 'Apache Kafka official docs', ['kafka.apache.org/documentation']],
  ['clickhouse', 'ClickHouse official docs', ['clickhouse.com/docs']],
  ['duckdb', 'DuckDB official docs', ['duckdb.org/docs']],
  ['drizzle', 'Drizzle ORM official docs', ['orm.drizzle.team/docs']],
  ['sequelize', 'Sequelize official docs', ['sequelize.org/docs']],
  ['typeorm', 'TypeORM official docs', ['typeorm.io']],
  ['zod', 'Zod official docs', ['zod.dev']],
  ['tanstack-query', 'TanStack Query official docs', ['tanstack.com/query/latest/docs']],
  ['redux', 'Redux official docs', ['redux.js.org']],
  ['zustand', 'Zustand official docs', ['zustand.docs.pmnd.rs']],
  ['radix', 'Radix UI official docs', ['radix-ui.com']],
  ['shadcn', 'shadcn ui official docs', ['ui.shadcn.com']],
  ['lucide', 'Lucide icons official', ['lucide.dev']],
  ['framer-motion', 'Motion React official docs', ['motion.dev/docs/react']],
  ['threejs', 'Three.js official docs', ['threejs.org/docs']],
  ['mapbox', 'Mapbox GL JS official docs', ['docs.mapbox.com/mapbox-gl-js']],
  ['leaflet', 'Leaflet official docs', ['leafletjs.com/reference']],
  ['playwright-api', 'Playwright API docs official', ['playwright.dev/docs/api']],
  ['cypress', 'Cypress official docs', ['docs.cypress.io']],
  ['storybook', 'Storybook official docs', ['storybook.js.org/docs']],
  ['sentry', 'Sentry JavaScript docs official', ['docs.sentry.io/platforms/javascript']],
  ['datadog', 'Datadog official docs', ['docs.datadoghq.com']],
  ['newrelic', 'New Relic official docs', ['docs.newrelic.com']],
  ['cloudflare-r2', 'Cloudflare R2 docs official', ['developers.cloudflare.com/r2']],
  ['aws-s3', 'AWS S3 docs official', ['docs.aws.amazon.com/s3']],
  ['gcp-cloud-run', 'Google Cloud Run docs official', ['cloud.google.com/run/docs']],
  ['azure-functions', 'Azure Functions docs official', ['learn.microsoft.com/azure/azure-functions']],
  ['digitalocean', 'DigitalOcean docs official', ['docs.digitalocean.com']],
  ['flyio', 'Fly.io docs official', ['fly.io/docs']],
  ['railway', 'Railway docs official', ['docs.railway.com']],
  ['render', 'Render docs official', ['render.com/docs']],
  ['stripe-cli', 'Stripe CLI official docs', ['docs.stripe.com/stripe-cli']],
  ['openapi', 'OpenAPI specification official', ['spec.openapis.org/oas']],
  ['oauth', 'OAuth 2.0 RFC official', ['rfc-editor.org/rfc/rfc6749']],
  ['snap', 'How to apply for SNAP benefits official', ['usa.gov/food-help', 'fns.usda.gov/snap']],
  ['medicaid', 'Medicaid eligibility official', ['medicaid.gov/medicaid/eligibility']],
  ['unemployment', 'How to apply for unemployment benefits official', ['usa.gov/unemployment-benefits']],
  ['irs-mileage', 'IRS standard mileage rate 2026 official', ['irs.gov/newsroom/irs-issues-standard-mileage-rates']],
  ['w4', 'How to fill out W-4 form official', ['irs.gov/forms-pubs/about-form-w-4']],
  ['passport-name', 'US passport name change official', ['travel.state.gov/content/travel/en/passports/have-passport/change-correct.html']],
  ['global-entry', 'Global Entry application official', ['ttp.dhs.gov', 'cbp.gov/travel/trusted-traveler-programs/global-entry']],
  ['real-id', 'REAL ID deadline official', ['dhs.gov/real-id']],
  ['voter-registration', 'Register to vote official', ['vote.gov']],
  ['selective-service', 'Selective Service registration official', ['sss.gov/register']],
  ['student-loans', 'Federal student loan repayment official', ['studentaid.gov/manage-loans/repayment']],
  ['fafsa-deadline', 'FAFSA deadline official', ['studentaid.gov/apply-for-aid/fafsa/fafsa-deadlines']],
  ['credit-report', 'Free credit report official', ['annualcreditreport.com']],
  ['identity-theft', 'Report identity theft official', ['identitytheft.gov']],
  ['do-not-call', 'National Do Not Call Registry official', ['donotcall.gov']],
  ['product-recalls', 'Consumer product recalls official', ['cpsc.gov/Recalls']],
  ['car-recalls', 'NHTSA vehicle recalls official', ['nhtsa.gov/recalls']],
  ['chicken-temp', 'Safe chicken internal temperature official', ['fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/safe-temperature-chart']],
  ['poison-control', 'Poison Control official phone number', ['poison.org']],
  ['covid-test', 'CDC COVID testing official', ['cdc.gov/covid/testing']],
  ['flu-symptoms', 'CDC flu symptoms official', ['cdc.gov/flu/signs-symptoms']],
  ['high-blood-pressure', 'CDC high blood pressure official', ['cdc.gov/high-blood-pressure']],
  ['diabetes', 'WHO diabetes fact sheet official', ['who.int/news-room/fact-sheets/detail/diabetes']],
  ['back-pain', 'NHS back pain advice official', ['nhs.uk/conditions/back-pain']],
  ['mental-health', '988 suicide crisis lifeline official', ['988lifeline.org']],
  ['vaccine-schedule', 'CDC adult vaccine schedule official', ['cdc.gov/vaccines/hcp/imz-schedules/adult-age']],
  ['air-quality', 'Air quality index official', ['airnow.gov/aqi']],
  ['hurricane', 'National Hurricane Center official', ['nhc.noaa.gov']],
  ['earthquake', 'USGS earthquake map official', ['earthquake.usgs.gov/earthquakes/map']],
  ['wildfire', 'National wildfire map official', ['fire.airnow.gov']],
  ['flood-map', 'FEMA flood maps official', ['msc.fema.gov/portal/home']],
  ['tornado', 'NOAA tornado safety official', ['weather.gov/safety/tornado']],
  ['heat-safety', 'CDC extreme heat safety official', ['cdc.gov/extreme-heat']],
  ['travel-advisory', 'US travel advisory Japan official', ['travel.state.gov/content/travel/en/traveladvisories/traveladvisories/japan-travel-advisory.html']],
  ['tsa-liquids', 'TSA liquids rule official', ['tsa.gov/travel/security-screening/liquids-rule']],
  ['passport-status', 'US passport status official', ['passportstatus.state.gov']],
  ['uscis-processing', 'USCIS processing times official', ['egov.uscis.gov/processing-times']],
  ['irs-payment', 'IRS make a payment official', ['irs.gov/payments']],
  ['ssa-card', 'Replace Social Security card official', ['ssa.gov/number-card/replace-card']],
  ['medicare-card', 'Replace Medicare card official', ['medicare.gov/basics/get-started-with-medicare/using-medicare/your-medicare-card']],
  ['postal-rates', 'USPS postage rates official', ['pe.usps.com']],
  ['zip-code', 'USPS ZIP code lookup official', ['tools.usps.com/zip-code-lookup']],
  ['time-zone', 'Time zones official US government', ['time.gov']],
  ['sunrise', 'NOAA sunrise sunset calculator official', ['gml.noaa.gov/grad/solcalc']],
  ['moon-phase', 'NASA moon phase official', ['science.nasa.gov/moon/moon-phases']],
  ['mars', 'NASA Mars rover official', ['mars.nasa.gov/mars2020']],
  ['eclipse', 'NASA eclipse official', ['science.nasa.gov/eclipses']],
  ['periodic-table', 'NIST periodic table official', ['nist.gov/pml/periodic-table-elements']],
  ['unit-conversion', 'NIST SI units official', ['nist.gov/pml/owm/metric-si/si-units']],
  ['nutrition-label', 'FDA nutrition facts label official', ['fda.gov/food/nutrition-facts-label']],
  ['myplate', 'USDA MyPlate official', ['myplate.gov']],
  ['pet-travel', 'USDA pet travel official', ['aphis.usda.gov/pet-travel']],
  ['irs-charity', 'IRS tax exempt organization search official', ['irs.gov/charities-non-profits/tax-exempt-organization-search']],
  ['sec-investor', 'SEC investor.gov official', ['investor.gov']],
  ['fdic-bankfind', 'FDIC BankFind official', ['banks.data.fdic.gov/bankfind-suite']],
  ['copyright-search', 'US copyright public records official', ['publicrecords.copyright.gov']],
  ['patent-search', 'USPTO patent search official', ['uspto.gov/patents/search']],
  ['trademark-search', 'USPTO trademark search official', ['uspto.gov/trademarks/search']],
  ['library-congress', 'Library of Congress search official', ['loc.gov']],
  ['flight-delay', 'What are my rights if my flight is delayed official', ['transportation.gov/airconsumer']],
  ['lost-baggage', 'Airline lost baggage complaint official', ['transportation.gov/airconsumer']],
  ['airline-complaint', 'File airline complaint official', ['secure.dot.gov/air-travel-complaint']],
  ['tsa-id', 'TSA acceptable ID at airport official', ['tsa.gov/travel/security-screening/identification']],
  ['tsa-food', 'Can I bring food through TSA official', ['tsa.gov/travel/security-screening/whatcanibring/food']],
  ['child-car-seat', 'Child car seat safety official', ['nhtsa.gov/equipment/car-seats-and-booster-seats']],
  ['tire-recall', 'Check tire recall official', ['nhtsa.gov/recalls']],
  ['fuel-economy', 'Compare car fuel economy official', ['fueleconomy.gov']],
  ['energy-star', 'Energy Star appliance rebate official', ['energystar.gov']],
  ['power-outage', 'Ready.gov power outage official', ['ready.gov/power-outages']],
  ['emergency-kit', 'Ready.gov emergency kit official', ['ready.gov/kit']],
  ['smoke-alarm', 'NFPA smoke alarm safety official', ['nfpa.org/education-and-research/home-fire-safety/smoke-alarms']],
  ['carbon-monoxide', 'CDC carbon monoxide poisoning official', ['cdc.gov/carbon-monoxide']],
  ['mold-cleanup', 'EPA mold cleanup official', ['epa.gov/mold']],
  ['bed-bugs', 'EPA bed bugs official', ['epa.gov/bedbugs']],
  ['radon', 'EPA radon map official', ['epa.gov/radon']],
  ['lead-paint', 'EPA lead paint official', ['epa.gov/lead']],
  ['drinking-water', 'EPA drinking water standards official', ['epa.gov/ground-water-and-drinking-water']],
  ['recycle', 'EPA recycling basics official', ['epa.gov/recycle']],
  ['composting', 'EPA composting at home official', ['epa.gov/recycle/composting-home']],
  ['fridge-temp', 'FDA refrigerator temperature official', ['fda.gov/food/buy-store-serve-safe-food/refrigerator-thermometers']],
  ['leftovers', 'USDA leftovers food safety official', ['fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/leftovers-and-food-safety']],
  ['egg-safety', 'FDA egg safety official', ['fda.gov/food/buy-store-serve-safe-food/what-you-need-know-about-egg-safety']],
  ['seafood-safety', 'FDA seafood safety official', ['fda.gov/food/buy-store-serve-safe-food/fresh-and-frozen-seafood']],
  ['baby-formula', 'FDA infant formula official', ['fda.gov/food/infant-formula']],
  ['pregnancy-food', 'FDA pregnancy food safety official', ['fda.gov/food/people-risk-foodborne-illness/food-safety-moms-be']],
  ['dog-food-recall', 'FDA pet food recalls official', ['fda.gov/animal-veterinary/safety-health/recalls-withdrawals']],
  ['lost-pet', 'Pet microchip lookup official', ['aaha.org/for-veterinary-professionals/microchip-search']],
  ['plant-hardiness', 'USDA plant hardiness zone official', ['planthardiness.ars.usda.gov']],
  ['invasive-plants', 'USDA invasive species official', ['invasivespeciesinfo.gov']],
  ['school-lunch', 'School lunch program official', ['fns.usda.gov/nslp']],
  ['wic', 'WIC program official', ['fns.usda.gov/wic']],
  ['summer-meals', 'Summer meals for kids official', ['fns.usda.gov/summer']],
  ['childcare', 'Child care assistance official', ['childcare.gov/consumer-education/get-help-paying-for-child-care']],
  ['head-start', 'Head Start locator official', ['headstart.gov/center-locator']],
  ['immunization-child', 'CDC child immunization schedule official', ['cdc.gov/vaccines/hcp/imz-schedules/child-adolescent-age']],
  ['car-seat-install', 'Find car seat inspection station official', ['nhtsa.gov/equipment/car-seats-and-booster-seats']],
  ['credit-freeze', 'FTC credit freeze official', ['consumer.ftc.gov/articles/what-know-about-credit-freezes-and-fraud-alerts']],
  ['gift-card-scam', 'FTC gift card scams official', ['consumer.ftc.gov/articles/gift-card-scams']],
  ['rental-scam', 'FTC rental listing scams official', ['consumer.ftc.gov/articles/rental-listing-scams']],
  ['romance-scam', 'FTC romance scams official', ['consumer.ftc.gov/articles/what-know-about-romance-scams']],
  ['phishing', 'FTC phishing scams official', ['consumer.ftc.gov/articles/how-recognize-and-avoid-phishing-scams']],
  ['small-claims', 'USA.gov small claims court official', ['usa.gov/small-claims-court']],
  ['legal-aid', 'Find legal aid official', ['usa.gov/legal-aid']],
  ['housing-help', 'HUD rental assistance official', ['hud.gov/topics/rental_assistance']],
  ['fair-housing', 'HUD fair housing complaint official', ['hud.gov/program_offices/fair_housing_equal_opp/online-complaint']],
  ['homeless-help', 'Find homeless shelter official', ['hud.gov/findshelter']],
  ['disaster-help', 'Disaster assistance official', ['disasterassistance.gov']],
  ['fema-aid', 'Apply for FEMA assistance official', ['disasterassistance.gov']],
  ['irs-transcript', 'IRS get tax transcript official', ['irs.gov/individuals/get-transcript']],
  ['irs-withholding', 'IRS tax withholding estimator official', ['irs.gov/individuals/tax-withholding-estimator']],
  ['irs-extension', 'IRS file tax extension official', ['irs.gov/forms-pubs/extension-of-time-to-file-your-tax-return']],
  ['unclaimed-money', 'Find unclaimed money official', ['usa.gov/unclaimed-money']],
  ['savings-bonds', 'TreasuryDirect savings bonds official', ['treasurydirect.gov/savings-bonds']],
  ['currency', 'US currency education official', ['uscurrency.gov']],
  ['coins', 'US Mint coin catalog official', ['catalog.usmint.gov']],
  ['passport-photo', 'US passport photo requirements official', ['travel.state.gov/content/travel/en/passports/how-apply/photos.html']],
  ['embassy', 'US embassy Tokyo official', ['jp.usembassy.gov']],
  ['state-parks', 'National Park Service find a park official', ['nps.gov/findapark']],
  ['camping', 'Recreation.gov camping official', ['recreation.gov']],
  ['ca-driver-renewal', 'California driver license renewal official', ['dmv.ca.gov/portal/driver-licenses-identification-cards/driver-licenses-dl/renew-your-dl']],
  ['ny-driver-renewal', 'New York driver license renewal official', ['dmv.ny.gov/driver-license/renew-license']],
  ['tx-driver-renewal', 'Texas driver license renewal official', ['txapps.texas.gov/tolapp/txdl']],
  ['ca-dmv-appointment', 'California DMV appointment official', ['dmv.ca.gov/portal/appointments']],
  ['ny-vehicle-registration', 'New York vehicle registration renewal official', ['dmv.ny.gov/registration/renew-registration']],
  ['ca-smog', 'California smog check official', ['bar.ca.gov/consumer/smog-check-program']],
  ['jury-duty', 'Jury duty scam official', ['uscourts.gov/services-forms/jury-service/juror-scams']],
  ['court-records', 'Find federal court records official', ['pacer.uscourts.gov']],
  ['bankruptcy', 'Bankruptcy basics official court', ['uscourts.gov/services-forms/bankruptcy/bankruptcy-basics']],
  ['name-change', 'Name change court official USA.gov', ['usa.gov/name-change']],
  ['birth-certificate', 'Get birth certificate official', ['usa.gov/birth-certificate']],
  ['marriage-certificate', 'Get marriage certificate official', ['usa.gov/marriage-certificate']],
  ['death-certificate', 'Get death certificate official', ['usa.gov/death-certificate']],
  ['replace-green-card', 'Replace green card official', ['uscis.gov/green-card/after-we-grant-your-green-card/replace-your-green-card']],
  ['citizenship', 'Apply for citizenship official', ['uscis.gov/citizenship/apply-for-citizenship']],
  ['naturalization-test', 'US citizenship test official', ['uscis.gov/citizenship/find-study-materials-and-resources/study-for-the-test']],
  ['i94', 'I-94 travel history official', ['i94.cbp.dhs.gov']],
  ['esta', 'ESTA application official', ['esta.cbp.dhs.gov']],
  ['evus', 'EVUS official', ['evus.gov']],
  ['visa-wait', 'US visa appointment wait times official', ['travel.state.gov/content/travel/en/us-visas/visa-information-services/wait-times.html']],
  ['child-support', 'Child support services official', ['acf.hhs.gov/css']],
  ['eldercare', 'Eldercare locator official', ['eldercare.acl.gov']],
  ['nursing-home', 'Medicare nursing home compare official', ['medicare.gov/care-compare']],
  ['hospital-compare', 'Medicare hospital compare official', ['medicare.gov/care-compare']],
  ['health-insurance', 'HealthCare.gov official', ['healthcare.gov']],
  ['marketplace', 'Health insurance marketplace official', ['healthcare.gov/marketplace-in-your-state']],
  ['cobra', 'COBRA health insurance official', ['dol.gov/general/topic/health-plans/cobra']],
  ['minimum-wage', 'Federal minimum wage official', ['dol.gov/agencies/whd/minimum-wage']],
  ['overtime', 'Overtime pay rules official', ['dol.gov/agencies/whd/overtime']],
  ['workplace-safety', 'OSHA workplace safety official', ['osha.gov/workers']],
  ['workplace-injury', 'Report unsafe workplace official OSHA', ['osha.gov/workers/file-complaint']],
  ['family-leave', 'FMLA leave official', ['dol.gov/agencies/whd/fmla']],
  ['unpaid-wages', 'Report unpaid wages official', ['dol.gov/agencies/whd/contact/complaints']],
  ['workers-comp', 'Workers compensation official', ['dol.gov/general/topic/workcomp']],
  ['job-training', 'Find job training official', ['careeronestop.org']],
  ['resume-help', 'CareerOneStop resume guide official', ['careeronestop.org/JobSearch/Resumes']],
  ['college-scorecard', 'College Scorecard official', ['collegescorecard.ed.gov']],
  ['ged', 'GED official', ['ged.com']],
  ['pell-grant', 'Pell Grant official', ['studentaid.gov/understand-aid/types/grants/pell']],
  ['loan-forgiveness', 'Public Service Loan Forgiveness official', ['studentaid.gov/manage-loans/forgiveness-cancellation/public-service']],
  ['library-near-me', 'Find a public library official', ['imls.gov/search-compare']],
  ['irs-ein', 'Apply for EIN official IRS', ['irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online']],
  ['small-business', 'SBA business guide official', ['sba.gov/business-guide']],
  ['sba-loan', 'SBA loans official', ['sba.gov/funding-programs/loans']],
  ['business-name', 'Register business name official SBA', ['sba.gov/business-guide/launch-your-business/register-your-business']],
  ['trademark-basic', 'Trademark basics official USPTO', ['uspto.gov/trademarks/basics']],
  ['patent-basic', 'Patent basics official USPTO', ['uspto.gov/patents/basics']],
  ['copyright-basic', 'Copyright basics official', ['copyright.gov/what-is-copyright']],
  ['weather-alerts', 'NOAA weather alerts official', ['weather.gov/alerts']],
  ['river-levels', 'USGS water data official', ['waterdata.usgs.gov']],
  ['drought', 'US drought monitor official', ['droughtmonitor.unl.edu']],
  ['pollen', 'CDC pollen allergies official', ['cdc.gov/climate-health/php/effects/allergens-and-pollen']],
  ['tick-bites', 'CDC tick bites official', ['cdc.gov/ticks']],
  ['mosquito', 'CDC mosquito bites official', ['cdc.gov/mosquitoes']],
  ['rabies', 'CDC rabies official', ['cdc.gov/rabies']],
  ['pool-safety', 'Pool safely official', ['poolsafely.gov']],
  ['bike-helmet', 'NHTSA bicycle safety official', ['nhtsa.gov/road-safety/bicycle-safety']],
  ['fireworks', 'CPSC fireworks safety official', ['cpsc.gov/Safety-Education/Safety-Education-Centers/Fireworks']],
  ['toy-recall', 'CPSC toy recalls official', ['cpsc.gov/Recalls']],
  ['privacy-complaint', 'FTC privacy complaint official', ['reportfraud.ftc.gov']],
].map(([id, query, expected]) => ({ id, query, expected }));

function includesExpected(url, expected) {
  const lowerUrl = String(url).toLowerCase();
  return expected.some((part) => lowerUrl.includes(part.toLowerCase()));
}

describe('random user web search queries', () => {
  it('returns an expected official source in the top results', async () => {
    const service = new SearchService({
      providers: [new LocalSearchProvider()],
    });

    for (const testCase of randomUserSearchCases) {
      const response = await service.webSearch(testCase.query, { limit: 5 });
      const hitRank = response.results.findIndex((result) => includesExpected(result.url, testCase.expected));

      expect(hitRank, `${testCase.id}: ${JSON.stringify(response.results.slice(0, 3))}`).toBeGreaterThanOrEqual(0);
      expect(hitRank, testCase.id).toBeLessThan(3);
    }
  }, 90_000);

  it('keeps these official-source probes on the internal fast path', async () => {
    const service = new SearchService({
      providers: [new LocalSearchProvider({
        fetchImpl: async () => {
          throw new Error('external search should not be called');
        },
      })],
    });

    for (const testCase of randomUserSearchCases) {
      const response = await service.webSearch(testCase.query, { limit: 5 });
      const hitRank = response.results.findIndex((result) => includesExpected(result.url, testCase.expected));

      expect(hitRank, testCase.id).toBeGreaterThanOrEqual(0);
    }
  });
});
