import {
  FileText,
  Folder,
  Star,
  Heart,
  Bookmark,
  Target,
  Lightbulb,
  Rocket,
  Sparkles,
  Crown,
  Award,
  Trophy,
  Medal,
  Gift,
  Bell,
  Home,
  Search,
  Settings,
  User,
  Mail,
  Calendar,
  Clock,
  Lock,
  Eye,
  ThumbsUp,
  ThumbsDown,
  Check,
  CheckSquare,
  CircleCheck,
  X,
  CircleX,
  Plus,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Grid3X3,
  List,
  LayoutGrid,
  LayoutList,
  Filter,
  ArrowUpNarrowWide,
  ArrowDownAZ,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
  Link,
  Unlink,
  Share,
  Share2,
  Download,
  Upload,
  CloudDownload,
  CloudUpload,
  RefreshCw,
  RotateCcw,
  History,
  Trash2,
  Edit,
  Pencil,
  Eraser,
  Copy,
  Clipboard,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const commonIcons: IconCategory = {
  id: 'common',
  name: 'Common',
  emoji: Award,
  icons: [
    { name: 'file', icon: FileText, color: DEFAULT_ICON_COLOR },
    { name: 'folder', icon: Folder, color: DEFAULT_ICON_COLOR },
    { name: 'star', icon: Star, color: DEFAULT_ICON_COLOR },
    { name: 'starfilled', icon: Star, color: DEFAULT_ICON_COLOR },
    { name: 'heart', icon: Heart, color: DEFAULT_ICON_COLOR },
    { name: 'heartfilled', icon: Heart, color: DEFAULT_ICON_COLOR },
    { name: 'bookmark', icon: Bookmark, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarkfilled', icon: Bookmark, color: DEFAULT_ICON_COLOR },
    { name: 'target', icon: Target, color: DEFAULT_ICON_COLOR },
    { name: 'bulb', icon: Lightbulb, color: DEFAULT_ICON_COLOR },
    { name: 'rocket', icon: Rocket, color: DEFAULT_ICON_COLOR },
    { name: 'sparkles', icon: Sparkles, color: DEFAULT_ICON_COLOR },
    { name: 'crown', icon: Crown, color: DEFAULT_ICON_COLOR },
    { name: 'award', icon: Award, color: DEFAULT_ICON_COLOR },
    { name: 'trophy', icon: Trophy, color: DEFAULT_ICON_COLOR },
    { name: 'medal', icon: Medal, color: DEFAULT_ICON_COLOR },
    { name: 'gift', icon: Gift, color: DEFAULT_ICON_COLOR },
    { name: 'bell', icon: Bell, color: DEFAULT_ICON_COLOR },
    { name: 'bellfilled', icon: Bell, color: DEFAULT_ICON_COLOR },
    { name: 'home', icon: Home, color: DEFAULT_ICON_COLOR },
    { name: 'homefilled', icon: Home, color: DEFAULT_ICON_COLOR },
    { name: 'search', icon: Search, color: DEFAULT_ICON_COLOR },
    { name: 'settings', icon: Settings, color: DEFAULT_ICON_COLOR },
    { name: 'settingsfilled', icon: Settings, color: DEFAULT_ICON_COLOR },
    { name: 'user', icon: User, color: DEFAULT_ICON_COLOR },
    { name: 'userfilled', icon: User, color: DEFAULT_ICON_COLOR },
    { name: 'mail', icon: Mail, color: DEFAULT_ICON_COLOR },
    { name: 'mailfilled', icon: Mail, color: DEFAULT_ICON_COLOR },
    { name: 'calendar', icon: Calendar, color: DEFAULT_ICON_COLOR },
    { name: 'calendarfilled', icon: Calendar, color: DEFAULT_ICON_COLOR },
    { name: 'clock', icon: Clock, color: DEFAULT_ICON_COLOR },
    { name: 'clockfilled', icon: Clock, color: DEFAULT_ICON_COLOR },
    { name: 'lock', icon: Lock, color: DEFAULT_ICON_COLOR },
    { name: 'lockfilled', icon: Lock, color: DEFAULT_ICON_COLOR },
    { name: 'eye', icon: Eye, color: DEFAULT_ICON_COLOR },
    { name: 'eyefilled', icon: Eye, color: DEFAULT_ICON_COLOR },
    { name: 'thumbup', icon: ThumbsUp, color: DEFAULT_ICON_COLOR },
    { name: 'thumbupfilled', icon: ThumbsUp, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdown', icon: ThumbsDown, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdownfilled', icon: ThumbsDown, color: DEFAULT_ICON_COLOR },
    { name: 'check', icon: Check, color: DEFAULT_ICON_COLOR },
    { name: 'checkbox', icon: CheckSquare, color: DEFAULT_ICON_COLOR },
    { name: 'circlecheck', icon: CircleCheck, color: DEFAULT_ICON_COLOR },
    { name: 'circlecheckfilled', icon: CircleCheck, color: DEFAULT_ICON_COLOR },
    { name: 'x', icon: X, color: DEFAULT_ICON_COLOR },
    { name: 'circlex', icon: CircleX, color: DEFAULT_ICON_COLOR },
    { name: 'circlexfilled', icon: CircleX, color: DEFAULT_ICON_COLOR },
    { name: 'plus', icon: Plus, color: DEFAULT_ICON_COLOR },
    { name: 'minus', icon: Minus, color: DEFAULT_ICON_COLOR },
    { name: 'dots', icon: MoreHorizontal, color: DEFAULT_ICON_COLOR },
    { name: 'dotsvertical', icon: MoreVertical, color: DEFAULT_ICON_COLOR },
    { name: 'menu', icon: Menu, color: DEFAULT_ICON_COLOR },
    { name: 'griddots', icon: Grid3X3, color: DEFAULT_ICON_COLOR },
    { name: 'list', icon: List, color: DEFAULT_ICON_COLOR },
    { name: 'layoutgrid', icon: LayoutGrid, color: DEFAULT_ICON_COLOR },
    { name: 'layoutlist', icon: LayoutList, color: DEFAULT_ICON_COLOR },
    { name: 'filter', icon: Filter, color: DEFAULT_ICON_COLOR },
    { name: 'filterfilled', icon: Filter, color: DEFAULT_ICON_COLOR },
    { name: 'sort09', icon: ArrowUpNarrowWide, color: DEFAULT_ICON_COLOR },
    { name: 'sortaz', icon: ArrowDownAZ, color: DEFAULT_ICON_COLOR },
    { name: 'arrowup', icon: ArrowUp, color: DEFAULT_ICON_COLOR },
    { name: 'arrowdown', icon: ArrowDown, color: DEFAULT_ICON_COLOR },
    { name: 'arrowleft', icon: ArrowLeft, color: DEFAULT_ICON_COLOR },
    { name: 'arrowright', icon: ArrowRight, color: DEFAULT_ICON_COLOR },
    { name: 'chevronup', icon: ChevronUp, color: DEFAULT_ICON_COLOR },
    { name: 'chevrondown', icon: ChevronDown, color: DEFAULT_ICON_COLOR },
    { name: 'chevronleft', icon: ChevronLeft, color: DEFAULT_ICON_COLOR },
    { name: 'chevronright', icon: ChevronRight, color: DEFAULT_ICON_COLOR },
    { name: 'externallink', icon: ExternalLink, color: DEFAULT_ICON_COLOR },
    { name: 'link', icon: Link, color: DEFAULT_ICON_COLOR },
    { name: 'unlink', icon: Unlink, color: DEFAULT_ICON_COLOR },
    { name: 'share', icon: Share, color: DEFAULT_ICON_COLOR },
    { name: 'share2', icon: Share2, color: DEFAULT_ICON_COLOR },
    { name: 'download', icon: Download, color: DEFAULT_ICON_COLOR },
    { name: 'upload', icon: Upload, color: DEFAULT_ICON_COLOR },
    { name: 'clouddownload', icon: CloudDownload, color: DEFAULT_ICON_COLOR },
    { name: 'cloudupload', icon: CloudUpload, color: DEFAULT_ICON_COLOR },
    { name: 'refresh', icon: RefreshCw, color: DEFAULT_ICON_COLOR },
    { name: 'reload', icon: RotateCcw, color: DEFAULT_ICON_COLOR },
    { name: 'history', icon: History, color: DEFAULT_ICON_COLOR },
    { name: 'trash', icon: Trash2, color: DEFAULT_ICON_COLOR },
    { name: 'trashfilled', icon: Trash2, color: DEFAULT_ICON_COLOR },
    { name: 'edit', icon: Edit, color: DEFAULT_ICON_COLOR },
    { name: 'pencil', icon: Pencil, color: DEFAULT_ICON_COLOR },
    { name: 'eraser', icon: Eraser, color: DEFAULT_ICON_COLOR },
    { name: 'copy', icon: Copy, color: DEFAULT_ICON_COLOR },
    { name: 'clipboard', icon: Clipboard, color: DEFAULT_ICON_COLOR },
  ],
};
