import {
  IconFileText,
  IconFolder,
  IconStar,
  IconHeart,
  IconBookmark,
  IconTarget,
  IconBulb,
  IconRocket,
  IconSparkles,
  IconCrown,
  IconAward,
  IconTrophy,
  IconMedal,
  IconGift,
  IconStarFilled,
  IconHeartFilled,
  IconBookmarkFilled,
  IconBell,
  IconBellFilled,
  IconHome,
  IconHomeFilled,
  IconSearch,
  IconSettings,
  IconSettingsFilled,
  IconUser,
  IconUserFilled,
  IconMail,
  IconMailFilled,
  IconCalendar,
  IconCalendarFilled,
  IconClock,
  IconClockFilled,
  IconLock,
  IconLockFilled,
  IconEye,
  IconEyeFilled,
  IconThumbUp,
  IconThumbUpFilled,
  IconThumbDown,
  IconThumbDownFilled,
  IconCheck,
  IconCheckbox,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconX,
  IconCircleX,
  IconCircleXFilled,
  IconPlus,
  IconMinus,
  IconDots,
  IconDotsVertical,
  IconMenu2,
  IconGridDots,
  IconList,
  IconLayoutGrid,
  IconLayoutList,
  IconFilter,
  IconFilterFilled,
  IconSort09,
  IconSortAZ,
  IconArrowUp,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconChevronUp,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconExternalLink,
  IconLink,
  IconUnlink,
  IconShare,
  IconShare2,
  IconDownload,
  IconUpload,
  IconCloudDownload,
  IconCloudUpload,
  IconRefresh,
  IconReload,
  IconHistory,
  IconTrash,
  IconTrashFilled,
  IconEdit,
  IconPencil,
  IconEraser,
  IconCopy,
  IconClipboard,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const commonIcons: IconCategory = {
  id: 'common',
  name: '常用',
  emoji: '⭐',
  icons: [
    { name: 'file', icon: IconFileText, color: DEFAULT_ICON_COLOR },
    { name: 'folder', icon: IconFolder, color: DEFAULT_ICON_COLOR },
    { name: 'star', icon: IconStar, color: DEFAULT_ICON_COLOR },
    { name: 'starfilled', icon: IconStarFilled, color: DEFAULT_ICON_COLOR },
    { name: 'heart', icon: IconHeart, color: DEFAULT_ICON_COLOR },
    { name: 'heartfilled', icon: IconHeartFilled, color: DEFAULT_ICON_COLOR },
    { name: 'bookmark', icon: IconBookmark, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarkfilled', icon: IconBookmarkFilled, color: DEFAULT_ICON_COLOR },
    { name: 'target', icon: IconTarget, color: DEFAULT_ICON_COLOR },
    { name: 'bulb', icon: IconBulb, color: DEFAULT_ICON_COLOR },
    { name: 'rocket', icon: IconRocket, color: DEFAULT_ICON_COLOR },
    { name: 'sparkles', icon: IconSparkles, color: DEFAULT_ICON_COLOR },
    { name: 'crown', icon: IconCrown, color: DEFAULT_ICON_COLOR },
    { name: 'award', icon: IconAward, color: DEFAULT_ICON_COLOR },
    { name: 'trophy', icon: IconTrophy, color: DEFAULT_ICON_COLOR },
    { name: 'medal', icon: IconMedal, color: DEFAULT_ICON_COLOR },
    { name: 'gift', icon: IconGift, color: DEFAULT_ICON_COLOR },
    { name: 'bell', icon: IconBell, color: DEFAULT_ICON_COLOR },
    { name: 'bellfilled', icon: IconBellFilled, color: DEFAULT_ICON_COLOR },
    { name: 'home', icon: IconHome, color: DEFAULT_ICON_COLOR },
    { name: 'homefilled', icon: IconHomeFilled, color: DEFAULT_ICON_COLOR },
    { name: 'search', icon: IconSearch, color: DEFAULT_ICON_COLOR },
    { name: 'settings', icon: IconSettings, color: DEFAULT_ICON_COLOR },
    { name: 'settingsfilled', icon: IconSettingsFilled, color: DEFAULT_ICON_COLOR },
    { name: 'user', icon: IconUser, color: DEFAULT_ICON_COLOR },
    { name: 'userfilled', icon: IconUserFilled, color: DEFAULT_ICON_COLOR },
    { name: 'mail', icon: IconMail, color: DEFAULT_ICON_COLOR },
    { name: 'mailfilled', icon: IconMailFilled, color: DEFAULT_ICON_COLOR },
    { name: 'calendar', icon: IconCalendar, color: DEFAULT_ICON_COLOR },
    { name: 'calendarfilled', icon: IconCalendarFilled, color: DEFAULT_ICON_COLOR },
    { name: 'clock', icon: IconClock, color: DEFAULT_ICON_COLOR },
    { name: 'clockfilled', icon: IconClockFilled, color: DEFAULT_ICON_COLOR },
    { name: 'lock', icon: IconLock, color: DEFAULT_ICON_COLOR },
    { name: 'lockfilled', icon: IconLockFilled, color: DEFAULT_ICON_COLOR },
    { name: 'eye', icon: IconEye, color: DEFAULT_ICON_COLOR },
    { name: 'eyefilled', icon: IconEyeFilled, color: DEFAULT_ICON_COLOR },
    { name: 'thumbup', icon: IconThumbUp, color: DEFAULT_ICON_COLOR },
    { name: 'thumbupfilled', icon: IconThumbUpFilled, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdown', icon: IconThumbDown, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdownfilled', icon: IconThumbDownFilled, color: DEFAULT_ICON_COLOR },
    { name: 'check', icon: IconCheck, color: DEFAULT_ICON_COLOR },
    { name: 'checkbox', icon: IconCheckbox, color: DEFAULT_ICON_COLOR },
    { name: 'circlecheck', icon: IconCircleCheck, color: DEFAULT_ICON_COLOR },
    { name: 'circlecheckfilled', icon: IconCircleCheckFilled, color: DEFAULT_ICON_COLOR },
    { name: 'x', icon: IconX, color: DEFAULT_ICON_COLOR },
    { name: 'circlex', icon: IconCircleX, color: DEFAULT_ICON_COLOR },
    { name: 'circlexfilled', icon: IconCircleXFilled, color: DEFAULT_ICON_COLOR },
    { name: 'plus', icon: IconPlus, color: DEFAULT_ICON_COLOR },
    { name: 'minus', icon: IconMinus, color: DEFAULT_ICON_COLOR },
    { name: 'dots', icon: IconDots, color: DEFAULT_ICON_COLOR },
    { name: 'dotsvertical', icon: IconDotsVertical, color: DEFAULT_ICON_COLOR },
    { name: 'menu', icon: IconMenu2, color: DEFAULT_ICON_COLOR },
    { name: 'griddots', icon: IconGridDots, color: DEFAULT_ICON_COLOR },
    { name: 'list', icon: IconList, color: DEFAULT_ICON_COLOR },
    { name: 'layoutgrid', icon: IconLayoutGrid, color: DEFAULT_ICON_COLOR },
    { name: 'layoutlist', icon: IconLayoutList, color: DEFAULT_ICON_COLOR },
    { name: 'filter', icon: IconFilter, color: DEFAULT_ICON_COLOR },
    { name: 'filterfilled', icon: IconFilterFilled, color: DEFAULT_ICON_COLOR },
    { name: 'sort09', icon: IconSort09, color: DEFAULT_ICON_COLOR },
    { name: 'sortaz', icon: IconSortAZ, color: DEFAULT_ICON_COLOR },
    { name: 'arrowup', icon: IconArrowUp, color: DEFAULT_ICON_COLOR },
    { name: 'arrowdown', icon: IconArrowDown, color: DEFAULT_ICON_COLOR },
    { name: 'arrowleft', icon: IconArrowLeft, color: DEFAULT_ICON_COLOR },
    { name: 'arrowright', icon: IconArrowRight, color: DEFAULT_ICON_COLOR },
    { name: 'chevronup', icon: IconChevronUp, color: DEFAULT_ICON_COLOR },
    { name: 'chevrondown', icon: IconChevronDown, color: DEFAULT_ICON_COLOR },
    { name: 'chevronleft', icon: IconChevronLeft, color: DEFAULT_ICON_COLOR },
    { name: 'chevronright', icon: IconChevronRight, color: DEFAULT_ICON_COLOR },
    { name: 'externallink', icon: IconExternalLink, color: DEFAULT_ICON_COLOR },
    { name: 'link', icon: IconLink, color: DEFAULT_ICON_COLOR },
    { name: 'unlink', icon: IconUnlink, color: DEFAULT_ICON_COLOR },
    { name: 'share', icon: IconShare, color: DEFAULT_ICON_COLOR },
    { name: 'share2', icon: IconShare2, color: DEFAULT_ICON_COLOR },
    { name: 'download', icon: IconDownload, color: DEFAULT_ICON_COLOR },
    { name: 'upload', icon: IconUpload, color: DEFAULT_ICON_COLOR },
    { name: 'clouddownload', icon: IconCloudDownload, color: DEFAULT_ICON_COLOR },
    { name: 'cloudupload', icon: IconCloudUpload, color: DEFAULT_ICON_COLOR },
    { name: 'refresh', icon: IconRefresh, color: DEFAULT_ICON_COLOR },
    { name: 'reload', icon: IconReload, color: DEFAULT_ICON_COLOR },
    { name: 'history', icon: IconHistory, color: DEFAULT_ICON_COLOR },
    { name: 'trash', icon: IconTrash, color: DEFAULT_ICON_COLOR },
    { name: 'trashfilled', icon: IconTrashFilled, color: DEFAULT_ICON_COLOR },
    { name: 'edit', icon: IconEdit, color: DEFAULT_ICON_COLOR },
    { name: 'pencil', icon: IconPencil, color: DEFAULT_ICON_COLOR },
    { name: 'eraser', icon: IconEraser, color: DEFAULT_ICON_COLOR },
    { name: 'copy', icon: IconCopy, color: DEFAULT_ICON_COLOR },
    { name: 'clipboard', icon: IconClipboard, color: DEFAULT_ICON_COLOR },
  ],
};
