import {
  Code,
  CodeXml,
  Bug,
  BugOff,
  Database,
  DatabaseBackup,
  Cpu,
  Cloud,
  CloudOff,
  CloudUpload,
  CloudDownload,
  Wifi,
  WifiOff,
  Shield,
  ShieldCheck,
  Lock,
  LockOpen,
  Key,
  KeyRound,
  Settings,
  Terminal,
  SquareTerminal,
  Webhook,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitFork,
  Server,
  ServerOff,
  Bot,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Gamepad2,
  Watch,
  Tv,
  Disc,
  Battery,
  BatteryLow,
  BatteryMedium,
  BatteryFull,
  BatteryCharging,
  Github,
  Gitlab,
  Twitter,
  Youtube,
  Twitch,
  MessageCircle,
  Slack,
  Send,
  MessageSquare,
  Figma,
  PenTool,
  Component,
  FileCode,
  FileJson,
  Container,
  Package,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const devIcons: IconCategory = {
  id: 'dev',
  name: 'Development',
  emoji: Code,
  icons: [
    { name: 'code', icon: Code, color: DEFAULT_ICON_COLOR },
    { name: 'codedots', icon: CodeXml, color: DEFAULT_ICON_COLOR },
    { name: 'codeplus', icon: Code, color: DEFAULT_ICON_COLOR },
    { name: 'codeminus', icon: Code, color: DEFAULT_ICON_COLOR },
    { name: 'bug', icon: Bug, color: DEFAULT_ICON_COLOR },
    { name: 'bugoff', icon: BugOff, color: DEFAULT_ICON_COLOR },
    { name: 'database', icon: Database, color: DEFAULT_ICON_COLOR },
    { name: 'databaseoff', icon: DatabaseBackup, color: DEFAULT_ICON_COLOR },
    { name: 'databaseplus', icon: Database, color: DEFAULT_ICON_COLOR },
    { name: 'cpu', icon: Cpu, color: DEFAULT_ICON_COLOR },
    { name: 'cpu2', icon: Cpu, color: DEFAULT_ICON_COLOR },
    { name: 'cloud', icon: Cloud, color: DEFAULT_ICON_COLOR },
    { name: 'cloudoff', icon: CloudOff, color: DEFAULT_ICON_COLOR },
    { name: 'cloudupload', icon: CloudUpload, color: DEFAULT_ICON_COLOR },
    { name: 'clouddownload', icon: CloudDownload, color: DEFAULT_ICON_COLOR },
    { name: 'wifi', icon: Wifi, color: DEFAULT_ICON_COLOR },
    { name: 'wifioff', icon: WifiOff, color: DEFAULT_ICON_COLOR },
    { name: 'wifi0', icon: WifiOff, color: DEFAULT_ICON_COLOR },
    { name: 'wifi1', icon: Wifi, color: DEFAULT_ICON_COLOR },
    { name: 'wifi2', icon: Wifi, color: DEFAULT_ICON_COLOR },
    { name: 'shield', icon: Shield, color: DEFAULT_ICON_COLOR },
    { name: 'shieldlock', icon: Shield, color: DEFAULT_ICON_COLOR },
    { name: 'shieldcheck', icon: ShieldCheck, color: DEFAULT_ICON_COLOR },
    { name: 'lock', icon: Lock, color: DEFAULT_ICON_COLOR },
    { name: 'lockopen', icon: LockOpen, color: DEFAULT_ICON_COLOR },
    { name: 'key', icon: Key, color: DEFAULT_ICON_COLOR },
    { name: 'keyoff', icon: KeyRound, color: DEFAULT_ICON_COLOR },
    { name: 'settings', icon: Settings, color: DEFAULT_ICON_COLOR },
    { name: 'settingsautomation', icon: Settings, color: DEFAULT_ICON_COLOR },
    { name: 'terminal', icon: Terminal, color: DEFAULT_ICON_COLOR },
    { name: 'terminal2', icon: SquareTerminal, color: DEFAULT_ICON_COLOR },
    { name: 'api', icon: Webhook, color: DEFAULT_ICON_COLOR },
    { name: 'apiapp', icon: Webhook, color: DEFAULT_ICON_COLOR },
    { name: 'gitbranch', icon: GitBranch, color: DEFAULT_ICON_COLOR },
    { name: 'gitcommit', icon: GitCommit, color: DEFAULT_ICON_COLOR },
    { name: 'gitmerge', icon: GitMerge, color: DEFAULT_ICON_COLOR },
    { name: 'gitpullrequest', icon: GitPullRequest, color: DEFAULT_ICON_COLOR },
    { name: 'gitfork', icon: GitFork, color: DEFAULT_ICON_COLOR },
    { name: 'server', icon: Server, color: DEFAULT_ICON_COLOR },
    { name: 'serveroff', icon: ServerOff, color: DEFAULT_ICON_COLOR },
    { name: 'server2', icon: Server, color: DEFAULT_ICON_COLOR },
    { name: 'robot', icon: Bot, color: DEFAULT_ICON_COLOR },
    { name: 'desktop', icon: Monitor, color: DEFAULT_ICON_COLOR },
    { name: 'laptop', icon: Laptop, color: DEFAULT_ICON_COLOR },
    { name: 'mobile', icon: Smartphone, color: DEFAULT_ICON_COLOR },
    { name: 'tablet', icon: Tablet, color: DEFAULT_ICON_COLOR },
    { name: 'gamepad', icon: Gamepad2, color: DEFAULT_ICON_COLOR },
    { name: 'watch', icon: Watch, color: DEFAULT_ICON_COLOR },
    { name: 'tv', icon: Tv, color: DEFAULT_ICON_COLOR },
    { name: 'audiotape', icon: Disc, color: DEFAULT_ICON_COLOR },
    { name: 'battery', icon: Battery, color: DEFAULT_ICON_COLOR },
    { name: 'battery1', icon: BatteryLow, color: DEFAULT_ICON_COLOR },
    { name: 'battery2', icon: BatteryMedium, color: DEFAULT_ICON_COLOR },
    { name: 'battery3', icon: BatteryMedium, color: DEFAULT_ICON_COLOR },
    { name: 'battery4', icon: BatteryFull, color: DEFAULT_ICON_COLOR },
    { name: 'batterycharging', icon: BatteryCharging, color: DEFAULT_ICON_COLOR },
    { name: 'github', icon: Github, color: DEFAULT_ICON_COLOR },
    { name: 'gitlab', icon: Gitlab, color: DEFAULT_ICON_COLOR },
    { name: 'x', icon: Twitter, color: DEFAULT_ICON_COLOR },
    { name: 'youtube', icon: Youtube, color: DEFAULT_ICON_COLOR },
    { name: 'twitch', icon: Twitch, color: DEFAULT_ICON_COLOR },
    { name: 'discord', icon: MessageCircle, color: DEFAULT_ICON_COLOR },
    { name: 'slack', icon: Slack, color: DEFAULT_ICON_COLOR },
    { name: 'telegram', icon: Send, color: DEFAULT_ICON_COLOR },
    { name: 'whatsapp', icon: MessageSquare, color: DEFAULT_ICON_COLOR },
    { name: 'figma', icon: Figma, color: DEFAULT_ICON_COLOR },
    { name: 'sketch', icon: PenTool, color: DEFAULT_ICON_COLOR },
    { name: 'react', icon: Component, color: DEFAULT_ICON_COLOR },
    { name: 'vue', icon: Component, color: DEFAULT_ICON_COLOR },
    { name: 'angular', icon: Component, color: DEFAULT_ICON_COLOR },
    { name: 'svelte', icon: Component, color: DEFAULT_ICON_COLOR },
    { name: 'nextjs', icon: Component, color: DEFAULT_ICON_COLOR },
    { name: 'nodejs', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'python', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'typescript', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'javascript', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'html5', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'css3', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'docker', icon: Container, color: DEFAULT_ICON_COLOR },
    { name: 'aws', icon: Cloud, color: DEFAULT_ICON_COLOR },
    { name: 'azure', icon: Cloud, color: DEFAULT_ICON_COLOR },
    { name: 'npm', icon: Package, color: DEFAULT_ICON_COLOR },
    { name: 'yarn', icon: Package, color: DEFAULT_ICON_COLOR },
    { name: 'redux', icon: FileJson, color: DEFAULT_ICON_COLOR },
    { name: 'tailwind', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'bootstrap', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'sass', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'git', icon: GitBranch, color: DEFAULT_ICON_COLOR },
  ],
};
