import {
  IconCode,
  IconCodeDots,
  IconCodePlus,
  IconCodeMinus,
  IconBug,
  IconBugOff,
  IconDatabase,
  IconDatabaseOff,
  IconDatabasePlus,
  IconCpu,
  IconCpu2,
  IconCloud,
  IconCloudOff,
  IconCloudUpload,
  IconCloudDownload,
  IconWifi,
  IconWifiOff,
  IconWifi0,
  IconWifi1,
  IconWifi2,
  IconShield,
  IconShieldLock,
  IconShieldCheck,
  IconLock,
  IconLockOpen,
  IconKey,
  IconKeyOff,
  IconSettings,
  IconSettingsAutomation,
  IconTerminal,
  IconTerminal2,
  IconApi,
  IconApiApp,
  IconGitBranch,
  IconGitCommit,
  IconGitMerge,
  IconGitPullRequest,
  IconGitFork,
  IconServer,
  IconServerOff,
  IconServer2,
  IconRobot,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTablet,
  IconDeviceGamepad,
  IconDeviceWatch,
  IconDeviceTv,
  IconDeviceAudioTape,
  IconBattery,
  IconBattery1,
  IconBattery2,
  IconBattery3,
  IconBattery4,
  IconBatteryCharging,
  IconBrandGithub,
  IconBrandGitlab,
  IconBrandX,
  IconBrandYoutube,
  IconBrandTwitch,
  IconBrandDiscord,
  IconBrandSlack,
  IconBrandTelegram,
  IconBrandWhatsapp,
  IconBrandFigma,
  IconBrandSketch,
  IconBrandReact,
  IconBrandVue,
  IconBrandAngular,
  IconBrandSvelte,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandPython,
  IconBrandTypescript,
  IconBrandJavascript,
  IconBrandHtml5,
  IconBrandCss3,
  IconBrandDocker,
  IconBrandAws,
  IconBrandAzure,
  IconBrandNpm,
  IconBrandYarn,
  IconBrandRedux,
  IconBrandTailwind,
  IconBrandBootstrap,
  IconBrandSass,
  IconBrandGit,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const devIcons: IconCategory = {
  id: 'dev',
  name: '开发',
  emoji: IconCode,
  icons: [
    { name: 'code', icon: IconCode, color: DEFAULT_ICON_COLOR },
    { name: 'codedots', icon: IconCodeDots, color: DEFAULT_ICON_COLOR },
    { name: 'codeplus', icon: IconCodePlus, color: DEFAULT_ICON_COLOR },
    { name: 'codeminus', icon: IconCodeMinus, color: DEFAULT_ICON_COLOR },
    { name: 'bug', icon: IconBug, color: DEFAULT_ICON_COLOR },
    { name: 'bugoff', icon: IconBugOff, color: DEFAULT_ICON_COLOR },
    { name: 'database', icon: IconDatabase, color: DEFAULT_ICON_COLOR },
    { name: 'databaseoff', icon: IconDatabaseOff, color: DEFAULT_ICON_COLOR },
    { name: 'databaseplus', icon: IconDatabasePlus, color: DEFAULT_ICON_COLOR },
    { name: 'cpu', icon: IconCpu, color: DEFAULT_ICON_COLOR },
    { name: 'cpu2', icon: IconCpu2, color: DEFAULT_ICON_COLOR },
    { name: 'cloud', icon: IconCloud, color: DEFAULT_ICON_COLOR },
    { name: 'cloudoff', icon: IconCloudOff, color: DEFAULT_ICON_COLOR },
    { name: 'cloudupload', icon: IconCloudUpload, color: DEFAULT_ICON_COLOR },
    { name: 'clouddownload', icon: IconCloudDownload, color: DEFAULT_ICON_COLOR },
    { name: 'wifi', icon: IconWifi, color: DEFAULT_ICON_COLOR },
    { name: 'wifioff', icon: IconWifiOff, color: DEFAULT_ICON_COLOR },
    { name: 'wifi0', icon: IconWifi0, color: DEFAULT_ICON_COLOR },
    { name: 'wifi1', icon: IconWifi1, color: DEFAULT_ICON_COLOR },
    { name: 'wifi2', icon: IconWifi2, color: DEFAULT_ICON_COLOR },
    { name: 'shield', icon: IconShield, color: DEFAULT_ICON_COLOR },
    { name: 'shieldlock', icon: IconShieldLock, color: DEFAULT_ICON_COLOR },
    { name: 'shieldcheck', icon: IconShieldCheck, color: DEFAULT_ICON_COLOR },
    { name: 'lock', icon: IconLock, color: DEFAULT_ICON_COLOR },
    { name: 'lockopen', icon: IconLockOpen, color: DEFAULT_ICON_COLOR },
    { name: 'key', icon: IconKey, color: DEFAULT_ICON_COLOR },
    { name: 'keyoff', icon: IconKeyOff, color: DEFAULT_ICON_COLOR },
    { name: 'settings', icon: IconSettings, color: DEFAULT_ICON_COLOR },
    { name: 'settingsautomation', icon: IconSettingsAutomation, color: DEFAULT_ICON_COLOR },
    { name: 'terminal', icon: IconTerminal, color: DEFAULT_ICON_COLOR },
    { name: 'terminal2', icon: IconTerminal2, color: DEFAULT_ICON_COLOR },
    { name: 'api', icon: IconApi, color: DEFAULT_ICON_COLOR },
    { name: 'apiapp', icon: IconApiApp, color: DEFAULT_ICON_COLOR },
    { name: 'gitbranch', icon: IconGitBranch, color: DEFAULT_ICON_COLOR },
    { name: 'gitcommit', icon: IconGitCommit, color: DEFAULT_ICON_COLOR },
    { name: 'gitmerge', icon: IconGitMerge, color: DEFAULT_ICON_COLOR },
    { name: 'gitpullrequest', icon: IconGitPullRequest, color: DEFAULT_ICON_COLOR },
    { name: 'gitfork', icon: IconGitFork, color: DEFAULT_ICON_COLOR },
    { name: 'server', icon: IconServer, color: DEFAULT_ICON_COLOR },
    { name: 'serveroff', icon: IconServerOff, color: DEFAULT_ICON_COLOR },
    { name: 'server2', icon: IconServer2, color: DEFAULT_ICON_COLOR },
    { name: 'robot', icon: IconRobot, color: DEFAULT_ICON_COLOR },
    { name: 'desktop', icon: IconDeviceDesktop, color: DEFAULT_ICON_COLOR },
    { name: 'laptop', icon: IconDeviceLaptop, color: DEFAULT_ICON_COLOR },
    { name: 'mobile', icon: IconDeviceMobile, color: DEFAULT_ICON_COLOR },
    { name: 'tablet', icon: IconDeviceTablet, color: DEFAULT_ICON_COLOR },
    { name: 'gamepad', icon: IconDeviceGamepad, color: DEFAULT_ICON_COLOR },
    { name: 'watch', icon: IconDeviceWatch, color: DEFAULT_ICON_COLOR },
    { name: 'tv', icon: IconDeviceTv, color: DEFAULT_ICON_COLOR },
    { name: 'audiotape', icon: IconDeviceAudioTape, color: DEFAULT_ICON_COLOR },
    { name: 'battery', icon: IconBattery, color: DEFAULT_ICON_COLOR },
    { name: 'battery1', icon: IconBattery1, color: DEFAULT_ICON_COLOR },
    { name: 'battery2', icon: IconBattery2, color: DEFAULT_ICON_COLOR },
    { name: 'battery3', icon: IconBattery3, color: DEFAULT_ICON_COLOR },
    { name: 'battery4', icon: IconBattery4, color: DEFAULT_ICON_COLOR },
    { name: 'batterycharging', icon: IconBatteryCharging, color: DEFAULT_ICON_COLOR },
    { name: 'github', icon: IconBrandGithub, color: DEFAULT_ICON_COLOR },
    { name: 'gitlab', icon: IconBrandGitlab, color: DEFAULT_ICON_COLOR },
    { name: 'x', icon: IconBrandX, color: DEFAULT_ICON_COLOR },
    { name: 'youtube', icon: IconBrandYoutube, color: DEFAULT_ICON_COLOR },
    { name: 'twitch', icon: IconBrandTwitch, color: DEFAULT_ICON_COLOR },
    { name: 'discord', icon: IconBrandDiscord, color: DEFAULT_ICON_COLOR },
    { name: 'slack', icon: IconBrandSlack, color: DEFAULT_ICON_COLOR },
    { name: 'telegram', icon: IconBrandTelegram, color: DEFAULT_ICON_COLOR },
    { name: 'whatsapp', icon: IconBrandWhatsapp, color: DEFAULT_ICON_COLOR },
    { name: 'figma', icon: IconBrandFigma, color: DEFAULT_ICON_COLOR },
    { name: 'sketch', icon: IconBrandSketch, color: DEFAULT_ICON_COLOR },
    { name: 'react', icon: IconBrandReact, color: DEFAULT_ICON_COLOR },
    { name: 'vue', icon: IconBrandVue, color: DEFAULT_ICON_COLOR },
    { name: 'angular', icon: IconBrandAngular, color: DEFAULT_ICON_COLOR },
    { name: 'svelte', icon: IconBrandSvelte, color: DEFAULT_ICON_COLOR },
    { name: 'nextjs', icon: IconBrandNextjs, color: DEFAULT_ICON_COLOR },
    { name: 'nodejs', icon: IconBrandNodejs, color: DEFAULT_ICON_COLOR },
    { name: 'python', icon: IconBrandPython, color: DEFAULT_ICON_COLOR },
    { name: 'typescript', icon: IconBrandTypescript, color: DEFAULT_ICON_COLOR },
    { name: 'javascript', icon: IconBrandJavascript, color: DEFAULT_ICON_COLOR },
    { name: 'html5', icon: IconBrandHtml5, color: DEFAULT_ICON_COLOR },
    { name: 'css3', icon: IconBrandCss3, color: DEFAULT_ICON_COLOR },
    { name: 'docker', icon: IconBrandDocker, color: DEFAULT_ICON_COLOR },
    { name: 'aws', icon: IconBrandAws, color: DEFAULT_ICON_COLOR },
    { name: 'azure', icon: IconBrandAzure, color: DEFAULT_ICON_COLOR },
    { name: 'npm', icon: IconBrandNpm, color: DEFAULT_ICON_COLOR },
    { name: 'yarn', icon: IconBrandYarn, color: DEFAULT_ICON_COLOR },
    { name: 'redux', icon: IconBrandRedux, color: DEFAULT_ICON_COLOR },
    { name: 'tailwind', icon: IconBrandTailwind, color: DEFAULT_ICON_COLOR },
    { name: 'bootstrap', icon: IconBrandBootstrap, color: DEFAULT_ICON_COLOR },
    { name: 'sass', icon: IconBrandSass, color: DEFAULT_ICON_COLOR },
    { name: 'git', icon: IconBrandGit, color: DEFAULT_ICON_COLOR },
  ],
};
