import {
  IconNote,
  IconNoteOff,
  IconNotes,
  IconNotebook,
  IconAddressBook,
  IconBook,
  IconBook2,
  IconBookOff,
  IconBookmark,
  IconBookmarkOff,
  IconBookmarkFilled,
  IconBookmarks,
  IconClipboard,
  IconClipboardCheck,
  IconClipboardList,
  IconClipboardText,
  IconClipboardOff,
  IconPencil,
  IconPencilOff,
  IconPencilPlus,
  IconPencilMinus,
  IconArchive,
  IconArchiveOff,
  IconArchiveFilled,
  IconTrash,
  IconTrashOff,
  IconTrashFilled,
  IconTrashX,
  IconDownload,
  IconDownloadOff,
  IconUpload,
  IconPrinter,
  IconPrinterOff,
  IconFileText,
  IconFile,
  IconFileFilled,
  IconFileOff,
  IconFilePlus,
  IconFileMinus,
  IconFileCheck,
  IconFileX,
  IconFileCode,
  IconFileCode2,
  IconFileZip,
  IconFileCertificate,
  IconFileAnalytics,
  IconFileReport,
  IconFileInvoice,
  IconFileSpreadsheet,
  IconFiles,
  IconFilesOff,
  IconFolder,
  IconFolderFilled,
  IconFolderOff,
  IconFolderOpen,
  IconFolderPlus,
  IconFolderMinus,
  IconFolderCheck,
  IconFolderX,
  IconFolders,
  IconBriefcase,
  IconBriefcaseOff,
  IconBriefcase2,
  IconSchool,
  IconSchoolOff,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconChartDots,
  IconChartArea,
  IconChartArrows,
  IconWallet,
  IconWalletOff,
  IconShoppingCart,
  IconShoppingCartOff,
  IconCreditCard,
  IconCreditCardOff,
  IconCalculator,
  IconCalculatorOff,
  IconPresentation,
  IconPresentationOff,
  IconPresentationAnalytics,
  IconPackage,
  IconPackageOff,
  IconBox,
  IconBoxOff,
  IconCube,
  IconCubeOff,
  IconTable,
  IconTableOff,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const docIcons: IconCategory = {
  id: 'doc',
  name: '文档',
  emoji: IconNotebook,
  icons: [
    { name: 'note', icon: IconNote, color: DEFAULT_ICON_COLOR },
    { name: 'noteoff', icon: IconNoteOff, color: DEFAULT_ICON_COLOR },
    { name: 'notes', icon: IconNotes, color: DEFAULT_ICON_COLOR },
    { name: 'notebook', icon: IconNotebook, color: DEFAULT_ICON_COLOR },
    { name: 'book', icon: IconBook, color: DEFAULT_ICON_COLOR },
    { name: 'book2', icon: IconBook2, color: DEFAULT_ICON_COLOR },
    { name: 'bookoff', icon: IconBookOff, color: DEFAULT_ICON_COLOR },
    { name: 'bookmark', icon: IconBookmark, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarkoff', icon: IconBookmarkOff, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarkfilled', icon: IconBookmarkFilled, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarks', icon: IconBookmarks, color: DEFAULT_ICON_COLOR },
    { name: 'clipboard', icon: IconClipboard, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardcheck', icon: IconClipboardCheck, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardlist', icon: IconClipboardList, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardtext', icon: IconClipboardText, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardoff', icon: IconClipboardOff, color: DEFAULT_ICON_COLOR },
    { name: 'pencil', icon: IconPencil, color: DEFAULT_ICON_COLOR },
    { name: 'penciloff', icon: IconPencilOff, color: DEFAULT_ICON_COLOR },
    { name: 'pencilplus', icon: IconPencilPlus, color: DEFAULT_ICON_COLOR },
    { name: 'pencilminus', icon: IconPencilMinus, color: DEFAULT_ICON_COLOR },
    { name: 'archive', icon: IconArchive, color: DEFAULT_ICON_COLOR },
    { name: 'archiveoff', icon: IconArchiveOff, color: DEFAULT_ICON_COLOR },
    { name: 'archivefilled', icon: IconArchiveFilled, color: DEFAULT_ICON_COLOR },
    { name: 'trash', icon: IconTrash, color: DEFAULT_ICON_COLOR },
    { name: 'trashoff', icon: IconTrashOff, color: DEFAULT_ICON_COLOR },
    { name: 'trashfilled', icon: IconTrashFilled, color: DEFAULT_ICON_COLOR },
    { name: 'trashx', icon: IconTrashX, color: DEFAULT_ICON_COLOR },
    { name: 'download', icon: IconDownload, color: DEFAULT_ICON_COLOR },
    { name: 'downloadoff', icon: IconDownloadOff, color: DEFAULT_ICON_COLOR },
    { name: 'upload', icon: IconUpload, color: DEFAULT_ICON_COLOR },
    { name: 'printer', icon: IconPrinter, color: DEFAULT_ICON_COLOR },
    { name: 'printeroff', icon: IconPrinterOff, color: DEFAULT_ICON_COLOR },
    { name: 'filetext', icon: IconFileText, color: DEFAULT_ICON_COLOR },
    { name: 'file', icon: IconFile, color: DEFAULT_ICON_COLOR },
    { name: 'filefilled', icon: IconFileFilled, color: DEFAULT_ICON_COLOR },
    { name: 'fileoff', icon: IconFileOff, color: DEFAULT_ICON_COLOR },
    { name: 'fileplus', icon: IconFilePlus, color: DEFAULT_ICON_COLOR },
    { name: 'fileminus', icon: IconFileMinus, color: DEFAULT_ICON_COLOR },
    { name: 'filecheck', icon: IconFileCheck, color: DEFAULT_ICON_COLOR },
    { name: 'filex', icon: IconFileX, color: DEFAULT_ICON_COLOR },
    { name: 'filecode', icon: IconFileCode, color: DEFAULT_ICON_COLOR },
    { name: 'filecode2', icon: IconFileCode2, color: DEFAULT_ICON_COLOR },
    { name: 'filezip', icon: IconFileZip, color: DEFAULT_ICON_COLOR },
    { name: 'filecertificate', icon: IconFileCertificate, color: DEFAULT_ICON_COLOR },
    { name: 'fileanalytics', icon: IconFileAnalytics, color: DEFAULT_ICON_COLOR },
    { name: 'filereport', icon: IconFileReport, color: DEFAULT_ICON_COLOR },
    { name: 'fileinvoice', icon: IconFileInvoice, color: DEFAULT_ICON_COLOR },
    { name: 'filespreadsheet', icon: IconFileSpreadsheet, color: DEFAULT_ICON_COLOR },
    { name: 'files', icon: IconFiles, color: DEFAULT_ICON_COLOR },
    { name: 'filesoff', icon: IconFilesOff, color: DEFAULT_ICON_COLOR },
    { name: 'folder', icon: IconFolder, color: DEFAULT_ICON_COLOR },
    { name: 'folderfilled', icon: IconFolderFilled, color: DEFAULT_ICON_COLOR },
    { name: 'folderoff', icon: IconFolderOff, color: DEFAULT_ICON_COLOR },
    { name: 'folderopen', icon: IconFolderOpen, color: DEFAULT_ICON_COLOR },
    { name: 'folderplus', icon: IconFolderPlus, color: DEFAULT_ICON_COLOR },
    { name: 'folderminus', icon: IconFolderMinus, color: DEFAULT_ICON_COLOR },
    { name: 'foldercheck', icon: IconFolderCheck, color: DEFAULT_ICON_COLOR },
    { name: 'folderx', icon: IconFolderX, color: DEFAULT_ICON_COLOR },
    { name: 'folders', icon: IconFolders, color: DEFAULT_ICON_COLOR },
    { name: 'briefcase', icon: IconBriefcase, color: DEFAULT_ICON_COLOR },
    { name: 'briefcaseoff', icon: IconBriefcaseOff, color: DEFAULT_ICON_COLOR },
    { name: 'briefcase2', icon: IconBriefcase2, color: DEFAULT_ICON_COLOR },
    { name: 'school', icon: IconSchool, color: DEFAULT_ICON_COLOR },
    { name: 'schooloff', icon: IconSchoolOff, color: DEFAULT_ICON_COLOR },
    { name: 'chartbar', icon: IconChartBar, color: DEFAULT_ICON_COLOR },
    { name: 'chartline', icon: IconChartLine, color: DEFAULT_ICON_COLOR },
    { name: 'chartpie', icon: IconChartPie, color: DEFAULT_ICON_COLOR },
    { name: 'chartdots', icon: IconChartDots, color: DEFAULT_ICON_COLOR },
    { name: 'chartarea', icon: IconChartArea, color: DEFAULT_ICON_COLOR },
    { name: 'chartarrows', icon: IconChartArrows, color: DEFAULT_ICON_COLOR },
    { name: 'wallet', icon: IconWallet, color: DEFAULT_ICON_COLOR },
    { name: 'walletoff', icon: IconWalletOff, color: DEFAULT_ICON_COLOR },
    { name: 'shoppingcart', icon: IconShoppingCart, color: DEFAULT_ICON_COLOR },
    { name: 'shoppingcartoff', icon: IconShoppingCartOff, color: DEFAULT_ICON_COLOR },
    { name: 'creditcard', icon: IconCreditCard, color: DEFAULT_ICON_COLOR },
    { name: 'creditcardoff', icon: IconCreditCardOff, color: DEFAULT_ICON_COLOR },
    { name: 'calculator', icon: IconCalculator, color: DEFAULT_ICON_COLOR },
    { name: 'calculatoroff', icon: IconCalculatorOff, color: DEFAULT_ICON_COLOR },
    { name: 'presentation', icon: IconPresentation, color: DEFAULT_ICON_COLOR },
    { name: 'presentationoff', icon: IconPresentationOff, color: DEFAULT_ICON_COLOR },
    { name: 'presentationanalytics', icon: IconPresentationAnalytics, color: DEFAULT_ICON_COLOR },
    { name: 'package', icon: IconPackage, color: DEFAULT_ICON_COLOR },
    { name: 'packageoff', icon: IconPackageOff, color: DEFAULT_ICON_COLOR },
    { name: 'box', icon: IconBox, color: DEFAULT_ICON_COLOR },
    { name: 'boxoff', icon: IconBoxOff, color: DEFAULT_ICON_COLOR },
    { name: 'cube', icon: IconCube, color: DEFAULT_ICON_COLOR },
    { name: 'cubeoff', icon: IconCubeOff, color: DEFAULT_ICON_COLOR },
    { name: 'table', icon: IconTable, color: DEFAULT_ICON_COLOR },
    { name: 'tableoff', icon: IconTableOff, color: DEFAULT_ICON_COLOR },
  ],
};
