import {
  StickyNote,
  NotebookPen,
  Notebook,
  Book,
  BookOpen,
  BookX,
  Bookmark,
  BookmarkX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  ClipboardType,
  ClipboardX,
  Pencil,
  PencilOff,
  Archive,
  ArchiveX,
  Trash2,
  TrashIcon,
  Download,
  DownloadCloud,
  Upload,
  Printer,
  PrinterCheck,
  FileText,
  File,
  FileX,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX2,
  FileCode,
  FileCode2,
  FileArchive,
  FileBadge,
  FileBarChart,
  FileSpreadsheet,
  Files,
  Folder,
  FolderOpen,
  FolderX,
  FolderPlus,
  FolderMinus,
  FolderCheck,
  Folders,
  Briefcase,
  BriefcaseBusiness,
  GraduationCap,
  BarChart,
  LineChart,
  PieChart,
  ChartScatter,
  AreaChart,
  TrendingUp,
  Wallet,
  WalletCards,
  ShoppingCart,
  CreditCard,
  Calculator,
  Presentation,
  Package,
  PackageOpen,
  Box,
  Boxes,
  Table,
  TableProperties,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const docIcons: IconCategory = {
  id: 'doc',
  name: 'Documents',
  emoji: Notebook,
  icons: [
    { name: 'note', icon: StickyNote, color: DEFAULT_ICON_COLOR },
    { name: 'noteoff', icon: StickyNote, color: DEFAULT_ICON_COLOR },
    { name: 'notes', icon: NotebookPen, color: DEFAULT_ICON_COLOR },
    { name: 'notebook', icon: Notebook, color: DEFAULT_ICON_COLOR },
    { name: 'book', icon: Book, color: DEFAULT_ICON_COLOR },
    { name: 'book2', icon: BookOpen, color: DEFAULT_ICON_COLOR },
    { name: 'bookoff', icon: BookX, color: DEFAULT_ICON_COLOR },
    { name: 'bookmark', icon: Bookmark, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarkoff', icon: BookmarkX, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarkfilled', icon: Bookmark, color: DEFAULT_ICON_COLOR },
    { name: 'bookmarks', icon: Bookmark, color: DEFAULT_ICON_COLOR },
    { name: 'clipboard', icon: Clipboard, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardcheck', icon: ClipboardCheck, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardlist', icon: ClipboardList, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardtext', icon: ClipboardType, color: DEFAULT_ICON_COLOR },
    { name: 'clipboardoff', icon: ClipboardX, color: DEFAULT_ICON_COLOR },
    { name: 'pencil', icon: Pencil, color: DEFAULT_ICON_COLOR },
    { name: 'penciloff', icon: PencilOff, color: DEFAULT_ICON_COLOR },
    { name: 'pencilplus', icon: Pencil, color: DEFAULT_ICON_COLOR },
    { name: 'pencilminus', icon: Pencil, color: DEFAULT_ICON_COLOR },
    { name: 'archive', icon: Archive, color: DEFAULT_ICON_COLOR },
    { name: 'archiveoff', icon: ArchiveX, color: DEFAULT_ICON_COLOR },
    { name: 'archivefilled', icon: Archive, color: DEFAULT_ICON_COLOR },
    { name: 'trash', icon: Trash2, color: DEFAULT_ICON_COLOR },
    { name: 'trashoff', icon: TrashIcon, color: DEFAULT_ICON_COLOR },
    { name: 'trashfilled', icon: Trash2, color: DEFAULT_ICON_COLOR },
    { name: 'trashx', icon: Trash2, color: DEFAULT_ICON_COLOR },
    { name: 'download', icon: Download, color: DEFAULT_ICON_COLOR },
    { name: 'downloadoff', icon: DownloadCloud, color: DEFAULT_ICON_COLOR },
    { name: 'upload', icon: Upload, color: DEFAULT_ICON_COLOR },
    { name: 'printer', icon: Printer, color: DEFAULT_ICON_COLOR },
    { name: 'printeroff', icon: PrinterCheck, color: DEFAULT_ICON_COLOR },
    { name: 'filetext', icon: FileText, color: DEFAULT_ICON_COLOR },
    { name: 'file', icon: File, color: DEFAULT_ICON_COLOR },
    { name: 'filefilled', icon: File, color: DEFAULT_ICON_COLOR },
    { name: 'fileoff', icon: FileX, color: DEFAULT_ICON_COLOR },
    { name: 'fileplus', icon: FilePlus, color: DEFAULT_ICON_COLOR },
    { name: 'fileminus', icon: FileMinus, color: DEFAULT_ICON_COLOR },
    { name: 'filecheck', icon: FileCheck, color: DEFAULT_ICON_COLOR },
    { name: 'filex', icon: FileX2, color: DEFAULT_ICON_COLOR },
    { name: 'filecode', icon: FileCode, color: DEFAULT_ICON_COLOR },
    { name: 'filecode2', icon: FileCode2, color: DEFAULT_ICON_COLOR },
    { name: 'filezip', icon: FileArchive, color: DEFAULT_ICON_COLOR },
    { name: 'filecertificate', icon: FileBadge, color: DEFAULT_ICON_COLOR },
    { name: 'fileanalytics', icon: FileBarChart, color: DEFAULT_ICON_COLOR },
    { name: 'filereport', icon: FileBarChart, color: DEFAULT_ICON_COLOR },
    { name: 'fileinvoice', icon: FileText, color: DEFAULT_ICON_COLOR },
    { name: 'filespreadsheet', icon: FileSpreadsheet, color: DEFAULT_ICON_COLOR },
    { name: 'files', icon: Files, color: DEFAULT_ICON_COLOR },
    { name: 'filesoff', icon: Files, color: DEFAULT_ICON_COLOR },
    { name: 'folder', icon: Folder, color: DEFAULT_ICON_COLOR },
    { name: 'folderfilled', icon: Folder, color: DEFAULT_ICON_COLOR },
    { name: 'folderoff', icon: FolderX, color: DEFAULT_ICON_COLOR },
    { name: 'folderopen', icon: FolderOpen, color: DEFAULT_ICON_COLOR },
    { name: 'folderplus', icon: FolderPlus, color: DEFAULT_ICON_COLOR },
    { name: 'folderminus', icon: FolderMinus, color: DEFAULT_ICON_COLOR },
    { name: 'foldercheck', icon: FolderCheck, color: DEFAULT_ICON_COLOR },
    { name: 'folderx', icon: FolderX, color: DEFAULT_ICON_COLOR },
    { name: 'folders', icon: Folders, color: DEFAULT_ICON_COLOR },
    { name: 'briefcase', icon: Briefcase, color: DEFAULT_ICON_COLOR },
    { name: 'briefcaseoff', icon: Briefcase, color: DEFAULT_ICON_COLOR },
    { name: 'briefcase2', icon: BriefcaseBusiness, color: DEFAULT_ICON_COLOR },
    { name: 'school', icon: GraduationCap, color: DEFAULT_ICON_COLOR },
    { name: 'schooloff', icon: GraduationCap, color: DEFAULT_ICON_COLOR },
    { name: 'chartbar', icon: BarChart, color: DEFAULT_ICON_COLOR },
    { name: 'chartline', icon: LineChart, color: DEFAULT_ICON_COLOR },
    { name: 'chartpie', icon: PieChart, color: DEFAULT_ICON_COLOR },
    { name: 'chartdots', icon: ChartScatter, color: DEFAULT_ICON_COLOR },
    { name: 'chartarea', icon: AreaChart, color: DEFAULT_ICON_COLOR },
    { name: 'chartarrows', icon: TrendingUp, color: DEFAULT_ICON_COLOR },
    { name: 'wallet', icon: Wallet, color: DEFAULT_ICON_COLOR },
    { name: 'walletoff', icon: WalletCards, color: DEFAULT_ICON_COLOR },
    { name: 'shoppingcart', icon: ShoppingCart, color: DEFAULT_ICON_COLOR },
    { name: 'shoppingcartoff', icon: ShoppingCart, color: DEFAULT_ICON_COLOR },
    { name: 'creditcard', icon: CreditCard, color: DEFAULT_ICON_COLOR },
    { name: 'creditcardoff', icon: CreditCard, color: DEFAULT_ICON_COLOR },
    { name: 'calculator', icon: Calculator, color: DEFAULT_ICON_COLOR },
    { name: 'calculatoroff', icon: Calculator, color: DEFAULT_ICON_COLOR },
    { name: 'presentation', icon: Presentation, color: DEFAULT_ICON_COLOR },
    { name: 'presentationoff', icon: Presentation, color: DEFAULT_ICON_COLOR },
    { name: 'presentationanalytics', icon: Presentation, color: DEFAULT_ICON_COLOR },
    { name: 'package', icon: Package, color: DEFAULT_ICON_COLOR },
    { name: 'packageoff', icon: PackageOpen, color: DEFAULT_ICON_COLOR },
    { name: 'box', icon: Box, color: DEFAULT_ICON_COLOR },
    { name: 'boxoff', icon: Boxes, color: DEFAULT_ICON_COLOR },
    { name: 'cube', icon: Box, color: DEFAULT_ICON_COLOR },
    { name: 'cubeoff', icon: Box, color: DEFAULT_ICON_COLOR },
    { name: 'table', icon: Table, color: DEFAULT_ICON_COLOR },
    { name: 'tableoff', icon: TableProperties, color: DEFAULT_ICON_COLOR },
  ],
};
