import {
  Camera,
  CameraOff,
  Image,
  ImagePlus,
  ImageMinus,
  ImageOff,
  Music,
  Music2,
  Video,
  VideoOff,
  Headphones,
  Mic,
  MicOff,
  Mic2,
  Play,
  Pause,
  Square,
  Circle,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Palette,
  Brush,
  Paintbrush,
  Wand2,
  Wrench,
  Flame,
  Scissors,
  Ruler,
  Pencil,
  PencilOff,
  Highlighter,
  Eraser,
  Pipette,
  SwatchBook,
  Droplet,
  Droplets,
  SprayCan,
  PaintBucket,
  Frame,
  Crop,
  Move,
  FlipHorizontal,
  FlipVertical,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  ScanSearch,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const mediaIcons: IconCategory = {
  id: 'media',
  name: 'Media',
  emoji: Camera,
  icons: [
    { name: 'camera', icon: Camera, color: DEFAULT_ICON_COLOR },
    { name: 'cameraoff', icon: CameraOff, color: DEFAULT_ICON_COLOR },
    { name: 'camerafilled', icon: Camera, color: DEFAULT_ICON_COLOR },
    { name: 'cameraplus', icon: Camera, color: DEFAULT_ICON_COLOR },
    { name: 'cameraminus', icon: Camera, color: DEFAULT_ICON_COLOR },
    { name: 'camerarotate', icon: Camera, color: DEFAULT_ICON_COLOR },
    { name: 'cameraselfie', icon: Camera, color: DEFAULT_ICON_COLOR },
    { name: 'photo', icon: Image, color: DEFAULT_ICON_COLOR },
    { name: 'photooff', icon: ImageOff, color: DEFAULT_ICON_COLOR },
    { name: 'photofilled', icon: Image, color: DEFAULT_ICON_COLOR },
    { name: 'photoplus', icon: ImagePlus, color: DEFAULT_ICON_COLOR },
    { name: 'photominus', icon: ImageMinus, color: DEFAULT_ICON_COLOR },
    { name: 'photoedit', icon: Image, color: DEFAULT_ICON_COLOR },
    { name: 'photocheck', icon: Image, color: DEFAULT_ICON_COLOR },
    { name: 'photox', icon: ImageOff, color: DEFAULT_ICON_COLOR },
    { name: 'photoscan', icon: ScanSearch, color: DEFAULT_ICON_COLOR },
    { name: 'music', icon: Music, color: DEFAULT_ICON_COLOR },
    { name: 'musicoff', icon: Music2, color: DEFAULT_ICON_COLOR },
    { name: 'video', icon: Video, color: DEFAULT_ICON_COLOR },
    { name: 'videooff', icon: VideoOff, color: DEFAULT_ICON_COLOR },
    { name: 'videoplus', icon: Video, color: DEFAULT_ICON_COLOR },
    { name: 'videominus', icon: Video, color: DEFAULT_ICON_COLOR },
    { name: 'headphones', icon: Headphones, color: DEFAULT_ICON_COLOR },
    { name: 'headphonesoff', icon: Headphones, color: DEFAULT_ICON_COLOR },
    { name: 'headphonesfilled', icon: Headphones, color: DEFAULT_ICON_COLOR },
    { name: 'microphone', icon: Mic, color: DEFAULT_ICON_COLOR },
    { name: 'microphoneoff', icon: MicOff, color: DEFAULT_ICON_COLOR },
    { name: 'microphone2', icon: Mic2, color: DEFAULT_ICON_COLOR },
    { name: 'microphone2off', icon: MicOff, color: DEFAULT_ICON_COLOR },
    { name: 'playerplay', icon: Play, color: DEFAULT_ICON_COLOR },
    { name: 'playerplayfilled', icon: Play, color: DEFAULT_ICON_COLOR },
    { name: 'playerpause', icon: Pause, color: DEFAULT_ICON_COLOR },
    { name: 'playerpausefilled', icon: Pause, color: DEFAULT_ICON_COLOR },
    { name: 'playerstop', icon: Square, color: DEFAULT_ICON_COLOR },
    { name: 'playerstopfilled', icon: Square, color: DEFAULT_ICON_COLOR },
    { name: 'playerrecord', icon: Circle, color: DEFAULT_ICON_COLOR },
    { name: 'playerrecordfilled', icon: Circle, color: DEFAULT_ICON_COLOR },
    { name: 'playerskipback', icon: SkipBack, color: DEFAULT_ICON_COLOR },
    { name: 'playerskipforward', icon: SkipForward, color: DEFAULT_ICON_COLOR },
    { name: 'playertracknext', icon: FastForward, color: DEFAULT_ICON_COLOR },
    { name: 'playertrackprev', icon: Rewind, color: DEFAULT_ICON_COLOR },
    { name: 'volume', icon: Volume, color: DEFAULT_ICON_COLOR },
    { name: 'volume2', icon: Volume1, color: DEFAULT_ICON_COLOR },
    { name: 'volume3', icon: Volume2, color: DEFAULT_ICON_COLOR },
    { name: 'volumeoff', icon: VolumeX, color: DEFAULT_ICON_COLOR },
    { name: 'palette', icon: Palette, color: DEFAULT_ICON_COLOR },
    { name: 'paletteoff', icon: Palette, color: DEFAULT_ICON_COLOR },
    { name: 'brush', icon: Brush, color: DEFAULT_ICON_COLOR },
    { name: 'brushoff', icon: Brush, color: DEFAULT_ICON_COLOR },
    { name: 'paint', icon: Paintbrush, color: DEFAULT_ICON_COLOR },
    { name: 'paintoff', icon: Paintbrush, color: DEFAULT_ICON_COLOR },
    { name: 'paintfilled', icon: Paintbrush, color: DEFAULT_ICON_COLOR },
    { name: 'wand', icon: Wand2, color: DEFAULT_ICON_COLOR },
    { name: 'wandoff', icon: Wand2, color: DEFAULT_ICON_COLOR },
    { name: 'tools', icon: Wrench, color: DEFAULT_ICON_COLOR },
    { name: 'toolsoff', icon: Wrench, color: DEFAULT_ICON_COLOR },
    { name: 'lighter', icon: Flame, color: DEFAULT_ICON_COLOR },
    { name: 'scissors', icon: Scissors, color: DEFAULT_ICON_COLOR },
    { name: 'scissorsoff', icon: Scissors, color: DEFAULT_ICON_COLOR },
    { name: 'ruler', icon: Ruler, color: DEFAULT_ICON_COLOR },
    { name: 'ruler2', icon: Ruler, color: DEFAULT_ICON_COLOR },
    { name: 'ruler3', icon: Ruler, color: DEFAULT_ICON_COLOR },
    { name: 'ruleroff', icon: Ruler, color: DEFAULT_ICON_COLOR },
    { name: 'pencil', icon: Pencil, color: DEFAULT_ICON_COLOR },
    { name: 'penciloff', icon: PencilOff, color: DEFAULT_ICON_COLOR },
    { name: 'highlight', icon: Highlighter, color: DEFAULT_ICON_COLOR },
    { name: 'highlightoff', icon: Highlighter, color: DEFAULT_ICON_COLOR },
    { name: 'eraser', icon: Eraser, color: DEFAULT_ICON_COLOR },
    { name: 'eraseroff', icon: Eraser, color: DEFAULT_ICON_COLOR },
    { name: 'colorpicker', icon: Pipette, color: DEFAULT_ICON_COLOR },
    { name: 'colorswatch', icon: SwatchBook, color: DEFAULT_ICON_COLOR },
    { name: 'droplet', icon: Droplet, color: DEFAULT_ICON_COLOR },
    { name: 'dropletoff', icon: Droplets, color: DEFAULT_ICON_COLOR },
    { name: 'dropletfilled', icon: Droplet, color: DEFAULT_ICON_COLOR },
    { name: 'spray', icon: SprayCan, color: DEFAULT_ICON_COLOR },
    { name: 'bucket', icon: PaintBucket, color: DEFAULT_ICON_COLOR },
    { name: 'bucketoff', icon: PaintBucket, color: DEFAULT_ICON_COLOR },
    { name: 'artboard', icon: Frame, color: DEFAULT_ICON_COLOR },
    { name: 'artboardoff', icon: Frame, color: DEFAULT_ICON_COLOR },
    { name: 'crop', icon: Crop, color: DEFAULT_ICON_COLOR },
    { name: 'resize', icon: Move, color: DEFAULT_ICON_COLOR },
    { name: 'fliphorizontal', icon: FlipHorizontal, color: DEFAULT_ICON_COLOR },
    { name: 'flipvertical', icon: FlipVertical, color: DEFAULT_ICON_COLOR },
    { name: 'rotate', icon: RotateCw, color: DEFAULT_ICON_COLOR },
    { name: 'rotateclockwise', icon: RotateCw, color: DEFAULT_ICON_COLOR },
    { name: 'rotate2', icon: RotateCcw, color: DEFAULT_ICON_COLOR },
    { name: 'zoomin', icon: ZoomIn, color: DEFAULT_ICON_COLOR },
    { name: 'zoomout', icon: ZoomOut, color: DEFAULT_ICON_COLOR },
    { name: 'zoomreset', icon: ScanSearch, color: DEFAULT_ICON_COLOR },
  ],
};
