import {
  IconCamera,
  IconCameraOff,
  IconCameraFilled,
  IconCameraPlus,
  IconCameraMinus,
  IconCameraRotate,
  IconCameraSelfie,
  IconPhoto,
  IconPhotoOff,
  IconPhotoFilled,
  IconPhotoPlus,
  IconPhotoMinus,
  IconPhotoEdit,
  IconPhotoCheck,
  IconPhotoX,
  IconPhotoScan,
  IconMusic,
  IconMusicOff,
  IconVideo,
  IconVideoOff,
  IconVideoPlus,
  IconVideoMinus,
  IconHeadphones,
  IconHeadphonesOff,
  IconHeadphonesFilled,
  IconMicrophone,
  IconMicrophoneOff,
  IconMicrophone2,
  IconMicrophone2Off,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconPlayerPause,
  IconPlayerPauseFilled,
  IconPlayerStop,
  IconPlayerStopFilled,
  IconPlayerRecord,
  IconPlayerRecordFilled,
  IconPlayerSkipBack,
  IconPlayerSkipForward,
  IconPlayerTrackNext,
  IconPlayerTrackPrev,
  IconVolume,
  IconVolume2,
  IconVolume3,
  IconVolumeOff,
  IconPalette,
  IconPaletteOff,
  IconBrush,
  IconBrushOff,
  IconPaint,
  IconPaintOff,
  IconPaintFilled,
  IconWand,
  IconWandOff,
  IconTools,
  IconToolsOff,
  IconLighter,
  IconScissors,
  IconScissorsOff,
  IconRuler,
  IconRuler2,
  IconRuler3,
  IconRulerOff,
  IconPencil,
  IconPencilOff,
  IconHighlight,
  IconHighlightOff,
  IconEraser,
  IconEraserOff,
  IconColorPicker,
  IconColorSwatch,
  IconDroplet,
  IconDropletOff,
  IconDropletFilled,
  IconSpray,
  IconBucket,
  IconBucketOff,
  IconArtboard,
  IconArtboardOff,
  IconCrop,
  IconResize,
  IconFlipHorizontal,
  IconFlipVertical,
  IconRotate,
  IconRotateClockwise,
  IconRotate2,
  IconZoomIn,
  IconZoomOut,
  IconZoomReset,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const mediaIcons: IconCategory = {
  id: 'media',
  name: '媒体',
  emoji: '🎬',
  icons: [
    { name: 'camera', icon: IconCamera, color: DEFAULT_ICON_COLOR },
    { name: 'cameraoff', icon: IconCameraOff, color: DEFAULT_ICON_COLOR },
    { name: 'camerafilled', icon: IconCameraFilled, color: DEFAULT_ICON_COLOR },
    { name: 'cameraplus', icon: IconCameraPlus, color: DEFAULT_ICON_COLOR },
    { name: 'cameraminus', icon: IconCameraMinus, color: DEFAULT_ICON_COLOR },
    { name: 'camerarotate', icon: IconCameraRotate, color: DEFAULT_ICON_COLOR },
    { name: 'cameraselfie', icon: IconCameraSelfie, color: DEFAULT_ICON_COLOR },
    { name: 'photo', icon: IconPhoto, color: DEFAULT_ICON_COLOR },
    { name: 'photooff', icon: IconPhotoOff, color: DEFAULT_ICON_COLOR },
    { name: 'photofilled', icon: IconPhotoFilled, color: DEFAULT_ICON_COLOR },
    { name: 'photoplus', icon: IconPhotoPlus, color: DEFAULT_ICON_COLOR },
    { name: 'photominus', icon: IconPhotoMinus, color: DEFAULT_ICON_COLOR },
    { name: 'photoedit', icon: IconPhotoEdit, color: DEFAULT_ICON_COLOR },
    { name: 'photocheck', icon: IconPhotoCheck, color: DEFAULT_ICON_COLOR },
    { name: 'photox', icon: IconPhotoX, color: DEFAULT_ICON_COLOR },
    { name: 'photoscan', icon: IconPhotoScan, color: DEFAULT_ICON_COLOR },
    { name: 'music', icon: IconMusic, color: DEFAULT_ICON_COLOR },
    { name: 'musicoff', icon: IconMusicOff, color: DEFAULT_ICON_COLOR },
    { name: 'video', icon: IconVideo, color: DEFAULT_ICON_COLOR },
    { name: 'videooff', icon: IconVideoOff, color: DEFAULT_ICON_COLOR },
    { name: 'videoplus', icon: IconVideoPlus, color: DEFAULT_ICON_COLOR },
    { name: 'videominus', icon: IconVideoMinus, color: DEFAULT_ICON_COLOR },
    { name: 'headphones', icon: IconHeadphones, color: DEFAULT_ICON_COLOR },
    { name: 'headphonesoff', icon: IconHeadphonesOff, color: DEFAULT_ICON_COLOR },
    { name: 'headphonesfilled', icon: IconHeadphonesFilled, color: DEFAULT_ICON_COLOR },
    { name: 'microphone', icon: IconMicrophone, color: DEFAULT_ICON_COLOR },
    { name: 'microphoneoff', icon: IconMicrophoneOff, color: DEFAULT_ICON_COLOR },
    { name: 'microphone2', icon: IconMicrophone2, color: DEFAULT_ICON_COLOR },
    { name: 'microphone2off', icon: IconMicrophone2Off, color: DEFAULT_ICON_COLOR },
    { name: 'playerplay', icon: IconPlayerPlay, color: DEFAULT_ICON_COLOR },
    { name: 'playerplayfilled', icon: IconPlayerPlayFilled, color: DEFAULT_ICON_COLOR },
    { name: 'playerpause', icon: IconPlayerPause, color: DEFAULT_ICON_COLOR },
    { name: 'playerpausefilled', icon: IconPlayerPauseFilled, color: DEFAULT_ICON_COLOR },
    { name: 'playerstop', icon: IconPlayerStop, color: DEFAULT_ICON_COLOR },
    { name: 'playerstopfilled', icon: IconPlayerStopFilled, color: DEFAULT_ICON_COLOR },
    { name: 'playerrecord', icon: IconPlayerRecord, color: DEFAULT_ICON_COLOR },
    { name: 'playerrecordfilled', icon: IconPlayerRecordFilled, color: DEFAULT_ICON_COLOR },
    { name: 'playerskipback', icon: IconPlayerSkipBack, color: DEFAULT_ICON_COLOR },
    { name: 'playerskipforward', icon: IconPlayerSkipForward, color: DEFAULT_ICON_COLOR },
    { name: 'playertracknext', icon: IconPlayerTrackNext, color: DEFAULT_ICON_COLOR },
    { name: 'playertrackprev', icon: IconPlayerTrackPrev, color: DEFAULT_ICON_COLOR },
    { name: 'volume', icon: IconVolume, color: DEFAULT_ICON_COLOR },
    { name: 'volume2', icon: IconVolume2, color: DEFAULT_ICON_COLOR },
    { name: 'volume3', icon: IconVolume3, color: DEFAULT_ICON_COLOR },
    { name: 'volumeoff', icon: IconVolumeOff, color: DEFAULT_ICON_COLOR },
    { name: 'palette', icon: IconPalette, color: DEFAULT_ICON_COLOR },
    { name: 'paletteoff', icon: IconPaletteOff, color: DEFAULT_ICON_COLOR },
    { name: 'brush', icon: IconBrush, color: DEFAULT_ICON_COLOR },
    { name: 'brushoff', icon: IconBrushOff, color: DEFAULT_ICON_COLOR },
    { name: 'paint', icon: IconPaint, color: DEFAULT_ICON_COLOR },
    { name: 'paintoff', icon: IconPaintOff, color: DEFAULT_ICON_COLOR },
    { name: 'paintfilled', icon: IconPaintFilled, color: DEFAULT_ICON_COLOR },
    { name: 'wand', icon: IconWand, color: DEFAULT_ICON_COLOR },
    { name: 'wandoff', icon: IconWandOff, color: DEFAULT_ICON_COLOR },
    { name: 'tools', icon: IconTools, color: DEFAULT_ICON_COLOR },
    { name: 'toolsoff', icon: IconToolsOff, color: DEFAULT_ICON_COLOR },
    { name: 'lighter', icon: IconLighter, color: DEFAULT_ICON_COLOR },
    { name: 'scissors', icon: IconScissors, color: DEFAULT_ICON_COLOR },
    { name: 'scissorsoff', icon: IconScissorsOff, color: DEFAULT_ICON_COLOR },
    { name: 'ruler', icon: IconRuler, color: DEFAULT_ICON_COLOR },
    { name: 'ruler2', icon: IconRuler2, color: DEFAULT_ICON_COLOR },
    { name: 'ruler3', icon: IconRuler3, color: DEFAULT_ICON_COLOR },
    { name: 'ruleroff', icon: IconRulerOff, color: DEFAULT_ICON_COLOR },
    { name: 'pencil', icon: IconPencil, color: DEFAULT_ICON_COLOR },
    { name: 'penciloff', icon: IconPencilOff, color: DEFAULT_ICON_COLOR },
    { name: 'highlight', icon: IconHighlight, color: DEFAULT_ICON_COLOR },
    { name: 'highlightoff', icon: IconHighlightOff, color: DEFAULT_ICON_COLOR },
    { name: 'eraser', icon: IconEraser, color: DEFAULT_ICON_COLOR },
    { name: 'eraseroff', icon: IconEraserOff, color: DEFAULT_ICON_COLOR },
    { name: 'colorpicker', icon: IconColorPicker, color: DEFAULT_ICON_COLOR },
    { name: 'colorswatch', icon: IconColorSwatch, color: DEFAULT_ICON_COLOR },
    { name: 'droplet', icon: IconDroplet, color: DEFAULT_ICON_COLOR },
    { name: 'dropletoff', icon: IconDropletOff, color: DEFAULT_ICON_COLOR },
    { name: 'dropletfilled', icon: IconDropletFilled, color: DEFAULT_ICON_COLOR },
    { name: 'spray', icon: IconSpray, color: DEFAULT_ICON_COLOR },
    { name: 'bucket', icon: IconBucket, color: DEFAULT_ICON_COLOR },
    { name: 'bucketoff', icon: IconBucketOff, color: DEFAULT_ICON_COLOR },
    { name: 'artboard', icon: IconArtboard, color: DEFAULT_ICON_COLOR },
    { name: 'artboardoff', icon: IconArtboardOff, color: DEFAULT_ICON_COLOR },
    { name: 'crop', icon: IconCrop, color: DEFAULT_ICON_COLOR },
    { name: 'resize', icon: IconResize, color: DEFAULT_ICON_COLOR },
    { name: 'fliphorizontal', icon: IconFlipHorizontal, color: DEFAULT_ICON_COLOR },
    { name: 'flipvertical', icon: IconFlipVertical, color: DEFAULT_ICON_COLOR },
    { name: 'rotate', icon: IconRotate, color: DEFAULT_ICON_COLOR },
    { name: 'rotateclockwise', icon: IconRotateClockwise, color: DEFAULT_ICON_COLOR },
    { name: 'rotate2', icon: IconRotate2, color: DEFAULT_ICON_COLOR },
    { name: 'zoomin', icon: IconZoomIn, color: DEFAULT_ICON_COLOR },
    { name: 'zoomout', icon: IconZoomOut, color: DEFAULT_ICON_COLOR },
    { name: 'zoomreset', icon: IconZoomReset, color: DEFAULT_ICON_COLOR },
  ],
};
