import {
  Sprout,
  Leaf,
  TreePine,
  Trees,
  Flower,
  Flower2,
  Droplet,
  Droplets,
  Snowflake,
  Zap,
  ZapOff,
  Flame,
  Sun,
  SunDim,
  Moon,
  MoonStar,
  Sunrise,
  Sunset,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  Cloud,
  CloudOff,
  Wind,
  Umbrella,
  Rainbow,
  Cat,
  Dog,
  Rabbit,
  Bird,
  Fish,
  Bug,
  BugOff,
  Feather,
  Bone,
  PawPrint,
  Coffee,
  Pizza,
  Cake,
  Apple,
  Cookie,
  IceCreamCone,
  Beer,
  Wine,
  GlassWater,
  Sandwich,
  Beef,
  Egg,
  Milk,
  Croissant,
  Soup,
  Salad,
  Candy,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const natureIcons: IconCategory = {
  id: 'nature',
  name: 'Nature',
  emoji: Rabbit,
  icons: [
    { name: 'plant', icon: Sprout, color: DEFAULT_ICON_COLOR },
    { name: 'plant2', icon: Sprout, color: DEFAULT_ICON_COLOR },
    { name: 'plantoff', icon: Sprout, color: DEFAULT_ICON_COLOR },
    { name: 'leaf', icon: Leaf, color: DEFAULT_ICON_COLOR },
    { name: 'leafoff', icon: Leaf, color: DEFAULT_ICON_COLOR },
    { name: 'tree', icon: TreePine, color: DEFAULT_ICON_COLOR },
    { name: 'trees', icon: Trees, color: DEFAULT_ICON_COLOR },
    { name: 'flower', icon: Flower, color: DEFAULT_ICON_COLOR },
    { name: 'floweroff', icon: Flower2, color: DEFAULT_ICON_COLOR },
    { name: 'droplet', icon: Droplet, color: DEFAULT_ICON_COLOR },
    { name: 'dropletoff', icon: Droplets, color: DEFAULT_ICON_COLOR },
    { name: 'dropletfilled', icon: Droplet, color: DEFAULT_ICON_COLOR },
    { name: 'snowflake', icon: Snowflake, color: DEFAULT_ICON_COLOR },
    { name: 'snowflakeoff', icon: Snowflake, color: DEFAULT_ICON_COLOR },
    { name: 'bolt', icon: Zap, color: DEFAULT_ICON_COLOR },
    { name: 'boltoff', icon: ZapOff, color: DEFAULT_ICON_COLOR },
    { name: 'flame', icon: Flame, color: DEFAULT_ICON_COLOR },
    { name: 'flameoff', icon: Flame, color: DEFAULT_ICON_COLOR },
    { name: 'sun', icon: Sun, color: DEFAULT_ICON_COLOR },
    { name: 'sunoff', icon: SunDim, color: DEFAULT_ICON_COLOR },
    { name: 'sunfilled', icon: Sun, color: DEFAULT_ICON_COLOR },
    { name: 'sunhigh', icon: Sun, color: DEFAULT_ICON_COLOR },
    { name: 'sunlow', icon: SunDim, color: DEFAULT_ICON_COLOR },
    { name: 'moon', icon: Moon, color: DEFAULT_ICON_COLOR },
    { name: 'moonoff', icon: Moon, color: DEFAULT_ICON_COLOR },
    { name: 'moonfilled', icon: Moon, color: DEFAULT_ICON_COLOR },
    { name: 'moonstars', icon: MoonStar, color: DEFAULT_ICON_COLOR },
    { name: 'sunrise', icon: Sunrise, color: DEFAULT_ICON_COLOR },
    { name: 'sunset', icon: Sunset, color: DEFAULT_ICON_COLOR },
    { name: 'cloudrain', icon: CloudRain, color: DEFAULT_ICON_COLOR },
    { name: 'cloudsnow', icon: CloudSnow, color: DEFAULT_ICON_COLOR },
    { name: 'cloudstorm', icon: CloudLightning, color: DEFAULT_ICON_COLOR },
    { name: 'cloudfog', icon: CloudFog, color: DEFAULT_ICON_COLOR },
    { name: 'cloud', icon: Cloud, color: DEFAULT_ICON_COLOR },
    { name: 'cloudoff', icon: CloudOff, color: DEFAULT_ICON_COLOR },
    { name: 'wind', icon: Wind, color: DEFAULT_ICON_COLOR },
    { name: 'windoff', icon: Wind, color: DEFAULT_ICON_COLOR },
    { name: 'umbrella', icon: Umbrella, color: DEFAULT_ICON_COLOR },
    { name: 'umbrellaoff', icon: Umbrella, color: DEFAULT_ICON_COLOR },
    { name: 'rainbow', icon: Rainbow, color: DEFAULT_ICON_COLOR },
    { name: 'cat', icon: Cat, color: DEFAULT_ICON_COLOR },
    { name: 'dog', icon: Dog, color: DEFAULT_ICON_COLOR },
    { name: 'deer', icon: Rabbit, color: DEFAULT_ICON_COLOR },
    { name: 'horse', icon: Bird, color: DEFAULT_ICON_COLOR },
    { name: 'pig', icon: Bird, color: DEFAULT_ICON_COLOR },
    { name: 'feather', icon: Feather, color: DEFAULT_ICON_COLOR },
    { name: 'featheroff', icon: Feather, color: DEFAULT_ICON_COLOR },
    { name: 'butterfly', icon: Bug, color: DEFAULT_ICON_COLOR },
    { name: 'fish', icon: Fish, color: DEFAULT_ICON_COLOR },
    { name: 'fishoff', icon: Fish, color: DEFAULT_ICON_COLOR },
    { name: 'bug', icon: Bug, color: DEFAULT_ICON_COLOR },
    { name: 'bugoff', icon: BugOff, color: DEFAULT_ICON_COLOR },
    { name: 'spider', icon: Bug, color: DEFAULT_ICON_COLOR },
    { name: 'bat', icon: Bird, color: DEFAULT_ICON_COLOR },
    { name: 'bone', icon: Bone, color: DEFAULT_ICON_COLOR },
    { name: 'boneoff', icon: Bone, color: DEFAULT_ICON_COLOR },
    { name: 'paw', icon: PawPrint, color: DEFAULT_ICON_COLOR },
    { name: 'pawoff', icon: PawPrint, color: DEFAULT_ICON_COLOR },
    { name: 'pawfilled', icon: PawPrint, color: DEFAULT_ICON_COLOR },
    { name: 'coffee', icon: Coffee, color: DEFAULT_ICON_COLOR },
    { name: 'coffeeoff', icon: Coffee, color: DEFAULT_ICON_COLOR },
    { name: 'pizza', icon: Pizza, color: DEFAULT_ICON_COLOR },
    { name: 'cake', icon: Cake, color: DEFAULT_ICON_COLOR },
    { name: 'apple', icon: Apple, color: DEFAULT_ICON_COLOR },
    { name: 'cookie', icon: Cookie, color: DEFAULT_ICON_COLOR },
    { name: 'icecream', icon: IceCreamCone, color: DEFAULT_ICON_COLOR },
    { name: 'icecream2', icon: IceCreamCone, color: DEFAULT_ICON_COLOR },
    { name: 'beer', icon: Beer, color: DEFAULT_ICON_COLOR },
    { name: 'beeroff', icon: Beer, color: DEFAULT_ICON_COLOR },
    { name: 'beerfilled', icon: Beer, color: DEFAULT_ICON_COLOR },
    { name: 'bottle', icon: Wine, color: DEFAULT_ICON_COLOR },
    { name: 'bottleoff', icon: Wine, color: DEFAULT_ICON_COLOR },
    { name: 'glass', icon: GlassWater, color: DEFAULT_ICON_COLOR },
    { name: 'glassoff', icon: GlassWater, color: DEFAULT_ICON_COLOR },
    { name: 'glassfull', icon: GlassWater, color: DEFAULT_ICON_COLOR },
    { name: 'burger', icon: Sandwich, color: DEFAULT_ICON_COLOR },
    { name: 'meat', icon: Beef, color: DEFAULT_ICON_COLOR },
    { name: 'meatoff', icon: Beef, color: DEFAULT_ICON_COLOR },
    { name: 'egg', icon: Egg, color: DEFAULT_ICON_COLOR },
    { name: 'eggoff', icon: Egg, color: DEFAULT_ICON_COLOR },
    { name: 'milk', icon: Milk, color: DEFAULT_ICON_COLOR },
    { name: 'milkoff', icon: Milk, color: DEFAULT_ICON_COLOR },
    { name: 'bread', icon: Croissant, color: DEFAULT_ICON_COLOR },
    { name: 'soup', icon: Soup, color: DEFAULT_ICON_COLOR },
    { name: 'soupoff', icon: Soup, color: DEFAULT_ICON_COLOR },
    { name: 'salad', icon: Salad, color: DEFAULT_ICON_COLOR },
    { name: 'candy', icon: Candy, color: DEFAULT_ICON_COLOR },
    { name: 'candyoff', icon: Candy, color: DEFAULT_ICON_COLOR },
  ],
};
