import {
  IconPlant,
  IconPlant2,
  IconPlantOff,
  IconLeaf,
  IconLeafOff,
  IconTree,
  IconTrees,
  IconFlower,
  IconFlowerOff,
  IconDroplet,
  IconDropletOff,
  IconDropletFilled,
  IconSnowflake,
  IconSnowflakeOff,
  IconBolt,
  IconBoltOff,
  IconFlame,
  IconFlameOff,
  IconSun,
  IconSunOff,
  IconSunFilled,
  IconSunHigh,
  IconSunLow,
  IconMoon,
  IconMoonOff,
  IconMoonFilled,
  IconMoonStars,
  IconSunrise,
  IconSunset,
  IconCloudRain,
  IconCloudSnow,
  IconCloudStorm,
  IconCloudFog,
  IconCloud,
  IconCloudOff,
  IconWind,
  IconWindOff,
  IconUmbrella,
  IconUmbrellaOff,
  IconRainbow,
  IconCat,
  IconDog,
  IconDeer,
  IconHorse,
  IconPig,
  IconFeather,
  IconFeatherOff,
  IconButterfly,
  IconFish,
  IconFishOff,
  IconBug,
  IconBugOff,
  IconSpider,
  IconBat,
  IconBone,
  IconBoneOff,
  IconPaw,
  IconPawOff,
  IconPawFilled,
  IconCoffee,
  IconCoffeeOff,
  IconPizza,
  IconCake,
  IconApple,
  IconCookie,
  IconIceCream,
  IconIceCream2,
  IconBeer,
  IconBeerOff,
  IconBeerFilled,
  IconBottle,
  IconBottleOff,
  IconGlass,
  IconGlassOff,
  IconGlassFull,
  IconBurger,
  IconMeat,
  IconMeatOff,
  IconEgg,
  IconEggOff,
  IconMilk,
  IconMilkOff,
  IconBread,
  IconSoup,
  IconSoupOff,
  IconSalad,
  IconCandy,
  IconCandyOff,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const natureIcons: IconCategory = {
  id: 'nature',
  name: '自然',
  emoji: IconDeer,
  icons: [
    { name: 'plant', icon: IconPlant, color: DEFAULT_ICON_COLOR },
    { name: 'plant2', icon: IconPlant2, color: DEFAULT_ICON_COLOR },
    { name: 'plantoff', icon: IconPlantOff, color: DEFAULT_ICON_COLOR },
    { name: 'leaf', icon: IconLeaf, color: DEFAULT_ICON_COLOR },
    { name: 'leafoff', icon: IconLeafOff, color: DEFAULT_ICON_COLOR },
    { name: 'tree', icon: IconTree, color: DEFAULT_ICON_COLOR },
    { name: 'trees', icon: IconTrees, color: DEFAULT_ICON_COLOR },
    { name: 'flower', icon: IconFlower, color: DEFAULT_ICON_COLOR },
    { name: 'floweroff', icon: IconFlowerOff, color: DEFAULT_ICON_COLOR },
    { name: 'droplet', icon: IconDroplet, color: DEFAULT_ICON_COLOR },
    { name: 'dropletoff', icon: IconDropletOff, color: DEFAULT_ICON_COLOR },
    { name: 'dropletfilled', icon: IconDropletFilled, color: DEFAULT_ICON_COLOR },
    { name: 'snowflake', icon: IconSnowflake, color: DEFAULT_ICON_COLOR },
    { name: 'snowflakeoff', icon: IconSnowflakeOff, color: DEFAULT_ICON_COLOR },
    { name: 'bolt', icon: IconBolt, color: DEFAULT_ICON_COLOR },
    { name: 'boltoff', icon: IconBoltOff, color: DEFAULT_ICON_COLOR },
    { name: 'flame', icon: IconFlame, color: DEFAULT_ICON_COLOR },
    { name: 'flameoff', icon: IconFlameOff, color: DEFAULT_ICON_COLOR },
    { name: 'sun', icon: IconSun, color: DEFAULT_ICON_COLOR },
    { name: 'sunoff', icon: IconSunOff, color: DEFAULT_ICON_COLOR },
    { name: 'sunfilled', icon: IconSunFilled, color: DEFAULT_ICON_COLOR },
    { name: 'sunhigh', icon: IconSunHigh, color: DEFAULT_ICON_COLOR },
    { name: 'sunlow', icon: IconSunLow, color: DEFAULT_ICON_COLOR },
    { name: 'moon', icon: IconMoon, color: DEFAULT_ICON_COLOR },
    { name: 'moonoff', icon: IconMoonOff, color: DEFAULT_ICON_COLOR },
    { name: 'moonfilled', icon: IconMoonFilled, color: DEFAULT_ICON_COLOR },
    { name: 'moonstars', icon: IconMoonStars, color: DEFAULT_ICON_COLOR },
    { name: 'sunrise', icon: IconSunrise, color: DEFAULT_ICON_COLOR },
    { name: 'sunset', icon: IconSunset, color: DEFAULT_ICON_COLOR },
    { name: 'cloudrain', icon: IconCloudRain, color: DEFAULT_ICON_COLOR },
    { name: 'cloudsnow', icon: IconCloudSnow, color: DEFAULT_ICON_COLOR },
    { name: 'cloudstorm', icon: IconCloudStorm, color: DEFAULT_ICON_COLOR },
    { name: 'cloudfog', icon: IconCloudFog, color: DEFAULT_ICON_COLOR },
    { name: 'cloud', icon: IconCloud, color: DEFAULT_ICON_COLOR },
    { name: 'cloudoff', icon: IconCloudOff, color: DEFAULT_ICON_COLOR },
    { name: 'wind', icon: IconWind, color: DEFAULT_ICON_COLOR },
    { name: 'windoff', icon: IconWindOff, color: DEFAULT_ICON_COLOR },
    { name: 'umbrella', icon: IconUmbrella, color: DEFAULT_ICON_COLOR },
    { name: 'umbrellaoff', icon: IconUmbrellaOff, color: DEFAULT_ICON_COLOR },
    { name: 'rainbow', icon: IconRainbow, color: DEFAULT_ICON_COLOR },
    { name: 'cat', icon: IconCat, color: DEFAULT_ICON_COLOR },
    { name: 'dog', icon: IconDog, color: DEFAULT_ICON_COLOR },
    { name: 'deer', icon: IconDeer, color: DEFAULT_ICON_COLOR },
    { name: 'horse', icon: IconHorse, color: DEFAULT_ICON_COLOR },
    { name: 'pig', icon: IconPig, color: DEFAULT_ICON_COLOR },
    { name: 'feather', icon: IconFeather, color: DEFAULT_ICON_COLOR },
    { name: 'featheroff', icon: IconFeatherOff, color: DEFAULT_ICON_COLOR },
    { name: 'butterfly', icon: IconButterfly, color: DEFAULT_ICON_COLOR },
    { name: 'fish', icon: IconFish, color: DEFAULT_ICON_COLOR },
    { name: 'fishoff', icon: IconFishOff, color: DEFAULT_ICON_COLOR },
    { name: 'bug', icon: IconBug, color: DEFAULT_ICON_COLOR },
    { name: 'bugoff', icon: IconBugOff, color: DEFAULT_ICON_COLOR },
    { name: 'spider', icon: IconSpider, color: DEFAULT_ICON_COLOR },
    { name: 'bat', icon: IconBat, color: DEFAULT_ICON_COLOR },
    { name: 'bone', icon: IconBone, color: DEFAULT_ICON_COLOR },
    { name: 'boneoff', icon: IconBoneOff, color: DEFAULT_ICON_COLOR },
    { name: 'paw', icon: IconPaw, color: DEFAULT_ICON_COLOR },
    { name: 'pawoff', icon: IconPawOff, color: DEFAULT_ICON_COLOR },
    { name: 'pawfilled', icon: IconPawFilled, color: DEFAULT_ICON_COLOR },
    { name: 'coffee', icon: IconCoffee, color: DEFAULT_ICON_COLOR },
    { name: 'coffeeoff', icon: IconCoffeeOff, color: DEFAULT_ICON_COLOR },
    { name: 'pizza', icon: IconPizza, color: DEFAULT_ICON_COLOR },
    { name: 'cake', icon: IconCake, color: DEFAULT_ICON_COLOR },
    { name: 'apple', icon: IconApple, color: DEFAULT_ICON_COLOR },
    { name: 'cookie', icon: IconCookie, color: DEFAULT_ICON_COLOR },
    { name: 'icecream', icon: IconIceCream, color: DEFAULT_ICON_COLOR },
    { name: 'icecream2', icon: IconIceCream2, color: DEFAULT_ICON_COLOR },
    { name: 'beer', icon: IconBeer, color: DEFAULT_ICON_COLOR },
    { name: 'beeroff', icon: IconBeerOff, color: DEFAULT_ICON_COLOR },
    { name: 'beerfilled', icon: IconBeerFilled, color: DEFAULT_ICON_COLOR },
    { name: 'bottle', icon: IconBottle, color: DEFAULT_ICON_COLOR },
    { name: 'bottleoff', icon: IconBottleOff, color: DEFAULT_ICON_COLOR },
    { name: 'glass', icon: IconGlass, color: DEFAULT_ICON_COLOR },
    { name: 'glassoff', icon: IconGlassOff, color: DEFAULT_ICON_COLOR },
    { name: 'glassfull', icon: IconGlassFull, color: DEFAULT_ICON_COLOR },
    { name: 'burger', icon: IconBurger, color: DEFAULT_ICON_COLOR },
    { name: 'meat', icon: IconMeat, color: DEFAULT_ICON_COLOR },
    { name: 'meatoff', icon: IconMeatOff, color: DEFAULT_ICON_COLOR },
    { name: 'egg', icon: IconEgg, color: DEFAULT_ICON_COLOR },
    { name: 'eggoff', icon: IconEggOff, color: DEFAULT_ICON_COLOR },
    { name: 'milk', icon: IconMilk, color: DEFAULT_ICON_COLOR },
    { name: 'milkoff', icon: IconMilkOff, color: DEFAULT_ICON_COLOR },
    { name: 'bread', icon: IconBread, color: DEFAULT_ICON_COLOR },
    { name: 'soup', icon: IconSoup, color: DEFAULT_ICON_COLOR },
    { name: 'soupoff', icon: IconSoupOff, color: DEFAULT_ICON_COLOR },
    { name: 'salad', icon: IconSalad, color: DEFAULT_ICON_COLOR },
    { name: 'candy', icon: IconCandy, color: DEFAULT_ICON_COLOR },
    { name: 'candyoff', icon: IconCandyOff, color: DEFAULT_ICON_COLOR },
  ],
};
