import {
  IconHome,
  IconHomeFilled,
  IconHomeOff,
  IconHome2,
  IconComet,
  IconBuilding,
  IconBuildingSkyscraper,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconBuildingFactory,
  IconBuildingHospital,
  IconBuildingBank,
  IconBuildingChurch,
  IconWorld,
  IconWorldOff,
  IconMap,
  IconMapOff,
  IconMap2,
  IconMapPin,
  IconMapPinOff,
  IconMapPinFilled,
  IconMapPins,
  IconCompass,
  IconCompassOff,
  IconMountain,
  IconMountainOff,
  IconTent,
  IconTentOff,
  IconCampfire,
  IconBeach,
  IconPool,
  IconPlane,
  IconPlaneOff,
  IconPlaneDeparture,
  IconPlaneArrival,
  IconCar,
  IconCarOff,
  IconCarCrash,
  IconTrain,
  IconBus,
  IconBusOff,
  IconTruck,
  IconTruckOff,
  IconBike,
  IconBikeOff,
  IconMotorbike,
  IconShip,
  IconShipOff,
  IconHelicopter,
  IconAnchor,
  IconAnchorOff,
  IconUfo,
  IconUfoOff,
  IconCalendar,
  IconCalendarOff,
  IconCalendarEvent,
  IconCalendarPlus,
  IconCalendarMinus,
  IconClock,
  IconClockOff,
  IconClock2,
  IconAlarm,
  IconAlarmOff,
  IconHourglass,
  IconHourglassOff,
  IconTimeline,
  IconFlask,
  IconFlaskOff,
  IconFlask2,
  IconAtom,
  IconAtomOff,
  IconAtom2,
  IconMicroscope,
  IconMicroscopeOff,
  IconDna,
  IconDnaOff,
  IconDna2,
  IconBrain,
  IconPlanet,
  IconPlanetOff,
  IconMeteor,
  IconMeteorOff,
  IconBalloon,
  IconBalloonOff,
  IconBalloonFilled,
  IconConfetti,
  IconConfettiOff,
  IconGhost,
  IconGhost2,
  IconSkull,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const placeIcons: IconCategory = {
  id: 'place',
  name: 'Places',
  emoji: IconComet,
  icons: [
    { name: 'home', icon: IconHome, color: DEFAULT_ICON_COLOR },
    { name: 'homefilled', icon: IconHomeFilled, color: DEFAULT_ICON_COLOR },
    { name: 'homeoff', icon: IconHomeOff, color: DEFAULT_ICON_COLOR },
    { name: 'home2', icon: IconHome2, color: DEFAULT_ICON_COLOR },
    { name: 'building', icon: IconBuilding, color: DEFAULT_ICON_COLOR },
    { name: 'buildingskyscraper', icon: IconBuildingSkyscraper, color: DEFAULT_ICON_COLOR },
    { name: 'buildingstore', icon: IconBuildingStore, color: DEFAULT_ICON_COLOR },
    { name: 'buildingwarehouse', icon: IconBuildingWarehouse, color: DEFAULT_ICON_COLOR },
    { name: 'buildingfactory', icon: IconBuildingFactory, color: DEFAULT_ICON_COLOR },
    { name: 'buildinghospital', icon: IconBuildingHospital, color: DEFAULT_ICON_COLOR },
    { name: 'buildingbank', icon: IconBuildingBank, color: DEFAULT_ICON_COLOR },
    { name: 'buildingchurch', icon: IconBuildingChurch, color: DEFAULT_ICON_COLOR },
    { name: 'world', icon: IconWorld, color: DEFAULT_ICON_COLOR },
    { name: 'worldoff', icon: IconWorldOff, color: DEFAULT_ICON_COLOR },
    { name: 'map', icon: IconMap, color: DEFAULT_ICON_COLOR },
    { name: 'mapoff', icon: IconMapOff, color: DEFAULT_ICON_COLOR },
    { name: 'map2', icon: IconMap2, color: DEFAULT_ICON_COLOR },
    { name: 'mappin', icon: IconMapPin, color: DEFAULT_ICON_COLOR },
    { name: 'mappinoff', icon: IconMapPinOff, color: DEFAULT_ICON_COLOR },
    { name: 'mappinfilled', icon: IconMapPinFilled, color: DEFAULT_ICON_COLOR },
    { name: 'mappins', icon: IconMapPins, color: DEFAULT_ICON_COLOR },
    { name: 'compass', icon: IconCompass, color: DEFAULT_ICON_COLOR },
    { name: 'compassoff', icon: IconCompassOff, color: DEFAULT_ICON_COLOR },
    { name: 'mountain', icon: IconMountain, color: DEFAULT_ICON_COLOR },
    { name: 'mountainoff', icon: IconMountainOff, color: DEFAULT_ICON_COLOR },
    { name: 'tent', icon: IconTent, color: DEFAULT_ICON_COLOR },
    { name: 'tentoff', icon: IconTentOff, color: DEFAULT_ICON_COLOR },
    { name: 'campfire', icon: IconCampfire, color: DEFAULT_ICON_COLOR },
    { name: 'beach', icon: IconBeach, color: DEFAULT_ICON_COLOR },
    { name: 'pool', icon: IconPool, color: DEFAULT_ICON_COLOR },
    { name: 'plane', icon: IconPlane, color: DEFAULT_ICON_COLOR },
    { name: 'planeoff', icon: IconPlaneOff, color: DEFAULT_ICON_COLOR },
    { name: 'planedeparture', icon: IconPlaneDeparture, color: DEFAULT_ICON_COLOR },
    { name: 'planearrival', icon: IconPlaneArrival, color: DEFAULT_ICON_COLOR },
    { name: 'car', icon: IconCar, color: DEFAULT_ICON_COLOR },
    { name: 'caroff', icon: IconCarOff, color: DEFAULT_ICON_COLOR },
    { name: 'carcrash', icon: IconCarCrash, color: DEFAULT_ICON_COLOR },
    { name: 'train', icon: IconTrain, color: DEFAULT_ICON_COLOR },
    { name: 'bus', icon: IconBus, color: DEFAULT_ICON_COLOR },
    { name: 'busoff', icon: IconBusOff, color: DEFAULT_ICON_COLOR },
    { name: 'truck', icon: IconTruck, color: DEFAULT_ICON_COLOR },
    { name: 'truckoff', icon: IconTruckOff, color: DEFAULT_ICON_COLOR },
    { name: 'bike', icon: IconBike, color: DEFAULT_ICON_COLOR },
    { name: 'bikeoff', icon: IconBikeOff, color: DEFAULT_ICON_COLOR },
    { name: 'motorbike', icon: IconMotorbike, color: DEFAULT_ICON_COLOR },
    { name: 'ship', icon: IconShip, color: DEFAULT_ICON_COLOR },
    { name: 'shipoff', icon: IconShipOff, color: DEFAULT_ICON_COLOR },
    { name: 'helicopter', icon: IconHelicopter, color: DEFAULT_ICON_COLOR },
    { name: 'anchor', icon: IconAnchor, color: DEFAULT_ICON_COLOR },
    { name: 'anchoroff', icon: IconAnchorOff, color: DEFAULT_ICON_COLOR },
    { name: 'ufo', icon: IconUfo, color: DEFAULT_ICON_COLOR },
    { name: 'ufooff', icon: IconUfoOff, color: DEFAULT_ICON_COLOR },
    { name: 'calendar', icon: IconCalendar, color: DEFAULT_ICON_COLOR },
    { name: 'calendaroff', icon: IconCalendarOff, color: DEFAULT_ICON_COLOR },
    { name: 'calendarevent', icon: IconCalendarEvent, color: DEFAULT_ICON_COLOR },
    { name: 'calendarplus', icon: IconCalendarPlus, color: DEFAULT_ICON_COLOR },
    { name: 'calendarminus', icon: IconCalendarMinus, color: DEFAULT_ICON_COLOR },
    { name: 'clock', icon: IconClock, color: DEFAULT_ICON_COLOR },
    { name: 'clockoff', icon: IconClockOff, color: DEFAULT_ICON_COLOR },
    { name: 'clock2', icon: IconClock2, color: DEFAULT_ICON_COLOR },
    { name: 'alarm', icon: IconAlarm, color: DEFAULT_ICON_COLOR },
    { name: 'alarmoff', icon: IconAlarmOff, color: DEFAULT_ICON_COLOR },
    { name: 'hourglass', icon: IconHourglass, color: DEFAULT_ICON_COLOR },
    { name: 'hourglassoff', icon: IconHourglassOff, color: DEFAULT_ICON_COLOR },
    { name: 'timeline', icon: IconTimeline, color: DEFAULT_ICON_COLOR },
    { name: 'flask', icon: IconFlask, color: DEFAULT_ICON_COLOR },
    { name: 'flaskoff', icon: IconFlaskOff, color: DEFAULT_ICON_COLOR },
    { name: 'flask2', icon: IconFlask2, color: DEFAULT_ICON_COLOR },
    { name: 'atom', icon: IconAtom, color: DEFAULT_ICON_COLOR },
    { name: 'atomoff', icon: IconAtomOff, color: DEFAULT_ICON_COLOR },
    { name: 'atom2', icon: IconAtom2, color: DEFAULT_ICON_COLOR },
    { name: 'microscope', icon: IconMicroscope, color: DEFAULT_ICON_COLOR },
    { name: 'microscopeoff', icon: IconMicroscopeOff, color: DEFAULT_ICON_COLOR },
    { name: 'dna', icon: IconDna, color: DEFAULT_ICON_COLOR },
    { name: 'dnaoff', icon: IconDnaOff, color: DEFAULT_ICON_COLOR },
    { name: 'dna2', icon: IconDna2, color: DEFAULT_ICON_COLOR },
    { name: 'brain', icon: IconBrain, color: DEFAULT_ICON_COLOR },
    { name: 'planet', icon: IconPlanet, color: DEFAULT_ICON_COLOR },
    { name: 'planetoff', icon: IconPlanetOff, color: DEFAULT_ICON_COLOR },
    { name: 'meteor', icon: IconMeteor, color: DEFAULT_ICON_COLOR },
    { name: 'meteoroff', icon: IconMeteorOff, color: DEFAULT_ICON_COLOR },
    { name: 'balloon', icon: IconBalloon, color: DEFAULT_ICON_COLOR },
    { name: 'balloonoff', icon: IconBalloonOff, color: DEFAULT_ICON_COLOR },
    { name: 'balloonfilled', icon: IconBalloonFilled, color: DEFAULT_ICON_COLOR },
    { name: 'confetti', icon: IconConfetti, color: DEFAULT_ICON_COLOR },
    { name: 'confettioff', icon: IconConfettiOff, color: DEFAULT_ICON_COLOR },
    { name: 'ghost', icon: IconGhost, color: DEFAULT_ICON_COLOR },
    { name: 'ghost2', icon: IconGhost2, color: DEFAULT_ICON_COLOR },
    { name: 'skull', icon: IconSkull, color: DEFAULT_ICON_COLOR },
  ],
};
