import {
  Home,
  Building,
  Building2,
  Store,
  Warehouse,
  Factory,
  Hospital,
  Landmark,
  Church,
  Globe,
  Globe2,
  Map,
  MapPin,
  MapPinOff,
  Navigation,
  Compass,
  Mountain,
  MountainSnow,
  Tent,
  Flame,
  Umbrella,
  Waves,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Car,
  CarFront,
  Train,
  Bus,
  Truck,
  Bike,
  Ship,
  Anchor,
  Rocket,
  Calendar,
  CalendarDays,
  CalendarPlus,
  CalendarMinus,
  Clock,
  Clock2,
  AlarmClock,
  AlarmClockOff,
  Hourglass,
  Timer,
  FlaskConical,
  FlaskRound,
  Atom,
  Microscope,
  Dna,
  Brain,
  Orbit,
  Sparkles,
  PartyPopper,
  Ghost,
  Skull,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const placeIcons: IconCategory = {
  id: 'place',
  name: 'Places',
  emoji: Sparkles,
  icons: [
    { name: 'home', icon: Home, color: DEFAULT_ICON_COLOR },
    { name: 'homefilled', icon: Home, color: DEFAULT_ICON_COLOR },
    { name: 'homeoff', icon: Home, color: DEFAULT_ICON_COLOR },
    { name: 'home2', icon: Home, color: DEFAULT_ICON_COLOR },
    { name: 'building', icon: Building, color: DEFAULT_ICON_COLOR },
    { name: 'buildingskyscraper', icon: Building2, color: DEFAULT_ICON_COLOR },
    { name: 'buildingstore', icon: Store, color: DEFAULT_ICON_COLOR },
    { name: 'buildingwarehouse', icon: Warehouse, color: DEFAULT_ICON_COLOR },
    { name: 'buildingfactory', icon: Factory, color: DEFAULT_ICON_COLOR },
    { name: 'buildinghospital', icon: Hospital, color: DEFAULT_ICON_COLOR },
    { name: 'buildingbank', icon: Landmark, color: DEFAULT_ICON_COLOR },
    { name: 'buildingchurch', icon: Church, color: DEFAULT_ICON_COLOR },
    { name: 'world', icon: Globe, color: DEFAULT_ICON_COLOR },
    { name: 'worldoff', icon: Globe2, color: DEFAULT_ICON_COLOR },
    { name: 'map', icon: Map, color: DEFAULT_ICON_COLOR },
    { name: 'mapoff', icon: Map, color: DEFAULT_ICON_COLOR },
    { name: 'map2', icon: Map, color: DEFAULT_ICON_COLOR },
    { name: 'mappin', icon: MapPin, color: DEFAULT_ICON_COLOR },
    { name: 'mappinoff', icon: MapPinOff, color: DEFAULT_ICON_COLOR },
    { name: 'mappinfilled', icon: MapPin, color: DEFAULT_ICON_COLOR },
    { name: 'mappins', icon: Navigation, color: DEFAULT_ICON_COLOR },
    { name: 'compass', icon: Compass, color: DEFAULT_ICON_COLOR },
    { name: 'compassoff', icon: Compass, color: DEFAULT_ICON_COLOR },
    { name: 'mountain', icon: Mountain, color: DEFAULT_ICON_COLOR },
    { name: 'mountainoff', icon: MountainSnow, color: DEFAULT_ICON_COLOR },
    { name: 'tent', icon: Tent, color: DEFAULT_ICON_COLOR },
    { name: 'tentoff', icon: Tent, color: DEFAULT_ICON_COLOR },
    { name: 'campfire', icon: Flame, color: DEFAULT_ICON_COLOR },
    { name: 'beach', icon: Umbrella, color: DEFAULT_ICON_COLOR },
    { name: 'pool', icon: Waves, color: DEFAULT_ICON_COLOR },
    { name: 'plane', icon: Plane, color: DEFAULT_ICON_COLOR },
    { name: 'planeoff', icon: Plane, color: DEFAULT_ICON_COLOR },
    { name: 'planedeparture', icon: PlaneTakeoff, color: DEFAULT_ICON_COLOR },
    { name: 'planearrival', icon: PlaneLanding, color: DEFAULT_ICON_COLOR },
    { name: 'car', icon: Car, color: DEFAULT_ICON_COLOR },
    { name: 'caroff', icon: Car, color: DEFAULT_ICON_COLOR },
    { name: 'carcrash', icon: CarFront, color: DEFAULT_ICON_COLOR },
    { name: 'train', icon: Train, color: DEFAULT_ICON_COLOR },
    { name: 'bus', icon: Bus, color: DEFAULT_ICON_COLOR },
    { name: 'busoff', icon: Bus, color: DEFAULT_ICON_COLOR },
    { name: 'truck', icon: Truck, color: DEFAULT_ICON_COLOR },
    { name: 'truckoff', icon: Truck, color: DEFAULT_ICON_COLOR },
    { name: 'bike', icon: Bike, color: DEFAULT_ICON_COLOR },
    { name: 'bikeoff', icon: Bike, color: DEFAULT_ICON_COLOR },
    { name: 'motorbike', icon: Bike, color: DEFAULT_ICON_COLOR },
    { name: 'ship', icon: Ship, color: DEFAULT_ICON_COLOR },
    { name: 'shipoff', icon: Ship, color: DEFAULT_ICON_COLOR },
    { name: 'helicopter', icon: Plane, color: DEFAULT_ICON_COLOR },
    { name: 'anchor', icon: Anchor, color: DEFAULT_ICON_COLOR },
    { name: 'anchoroff', icon: Anchor, color: DEFAULT_ICON_COLOR },
    { name: 'ufo', icon: Rocket, color: DEFAULT_ICON_COLOR },
    { name: 'ufooff', icon: Rocket, color: DEFAULT_ICON_COLOR },
    { name: 'calendar', icon: Calendar, color: DEFAULT_ICON_COLOR },
    { name: 'calendaroff', icon: Calendar, color: DEFAULT_ICON_COLOR },
    { name: 'calendarevent', icon: CalendarDays, color: DEFAULT_ICON_COLOR },
    { name: 'calendarplus', icon: CalendarPlus, color: DEFAULT_ICON_COLOR },
    { name: 'calendarminus', icon: CalendarMinus, color: DEFAULT_ICON_COLOR },
    { name: 'clock', icon: Clock, color: DEFAULT_ICON_COLOR },
    { name: 'clockoff', icon: Clock, color: DEFAULT_ICON_COLOR },
    { name: 'clock2', icon: Clock2, color: DEFAULT_ICON_COLOR },
    { name: 'alarm', icon: AlarmClock, color: DEFAULT_ICON_COLOR },
    { name: 'alarmoff', icon: AlarmClockOff, color: DEFAULT_ICON_COLOR },
    { name: 'hourglass', icon: Hourglass, color: DEFAULT_ICON_COLOR },
    { name: 'hourglassoff', icon: Hourglass, color: DEFAULT_ICON_COLOR },
    { name: 'timeline', icon: Timer, color: DEFAULT_ICON_COLOR },
    { name: 'flask', icon: FlaskConical, color: DEFAULT_ICON_COLOR },
    { name: 'flaskoff', icon: FlaskConical, color: DEFAULT_ICON_COLOR },
    { name: 'flask2', icon: FlaskRound, color: DEFAULT_ICON_COLOR },
    { name: 'atom', icon: Atom, color: DEFAULT_ICON_COLOR },
    { name: 'atomoff', icon: Atom, color: DEFAULT_ICON_COLOR },
    { name: 'atom2', icon: Atom, color: DEFAULT_ICON_COLOR },
    { name: 'microscope', icon: Microscope, color: DEFAULT_ICON_COLOR },
    { name: 'microscopeoff', icon: Microscope, color: DEFAULT_ICON_COLOR },
    { name: 'dna', icon: Dna, color: DEFAULT_ICON_COLOR },
    { name: 'dnaoff', icon: Dna, color: DEFAULT_ICON_COLOR },
    { name: 'dna2', icon: Dna, color: DEFAULT_ICON_COLOR },
    { name: 'brain', icon: Brain, color: DEFAULT_ICON_COLOR },
    { name: 'planet', icon: Orbit, color: DEFAULT_ICON_COLOR },
    { name: 'planetoff', icon: Orbit, color: DEFAULT_ICON_COLOR },
    { name: 'meteor', icon: Sparkles, color: DEFAULT_ICON_COLOR },
    { name: 'meteoroff', icon: Sparkles, color: DEFAULT_ICON_COLOR },
    { name: 'balloon', icon: PartyPopper, color: DEFAULT_ICON_COLOR },
    { name: 'balloonoff', icon: PartyPopper, color: DEFAULT_ICON_COLOR },
    { name: 'balloonfilled', icon: PartyPopper, color: DEFAULT_ICON_COLOR },
    { name: 'confetti', icon: PartyPopper, color: DEFAULT_ICON_COLOR },
    { name: 'confettioff', icon: PartyPopper, color: DEFAULT_ICON_COLOR },
    { name: 'ghost', icon: Ghost, color: DEFAULT_ICON_COLOR },
    { name: 'ghost2', icon: Ghost, color: DEFAULT_ICON_COLOR },
    { name: 'skull', icon: Skull, color: DEFAULT_ICON_COLOR },
  ],
};
