import {
  Check,
  X,
  CircleAlert,
  TriangleAlert,
  OctagonAlert,
  Info,
  CircleHelp,
  HelpCircle,
  Bell,
  BellOff,
  BellRing,
  Pin,
  PinOff,
  Flag,
  FlagTriangleRight,
  Filter,
  FilterX,
  RefreshCw,
  RefreshCcw,
  RotateCw,
  RotateCcw,
  Copy,
  CopyX,
  Share,
  Share2,
  Edit,
  Edit3,
  Power,
  PowerOff,
  LogOut,
  LogIn,
  ZoomIn,
  ZoomOut,
  ScanSearch,
  Maximize,
  Minimize,
  SlidersHorizontal,
  SlidersVertical,
  ListChecks,
  ClipboardCheck,
  Loader,
  Loader2,
  Hourglass,
  CircleDot,
  CircleDashed,
  CircleSlash,
  Circle,
  Square,
  Triangle,
  Diamond,
  Star,
  StarHalf,
  StarOff,
  Eye,
  EyeOff,
  Lock,
  LockOpen,
  Shield,
  ShieldCheck,
  ShieldOff,
  ToggleLeft,
  ToggleRight,
  Play,
  Pause,
  StopCircle,
  Activity,
  HeartPulse,
  AudioWaveform,
  ChartScatter,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const statusIcons: IconCategory = {
  id: 'status',
  name: 'Status',
  emoji: HeartPulse,
  icons: [
    { name: 'check', icon: Check, color: DEFAULT_ICON_COLOR },
    { name: 'x', icon: X, color: DEFAULT_ICON_COLOR },
    { name: 'alertcircle', icon: CircleAlert, color: DEFAULT_ICON_COLOR },
    { name: 'alerttriangle', icon: TriangleAlert, color: DEFAULT_ICON_COLOR },
    { name: 'alertoctagon', icon: OctagonAlert, color: DEFAULT_ICON_COLOR },
    { name: 'infocircle', icon: Info, color: DEFAULT_ICON_COLOR },
    { name: 'infosquare', icon: Info, color: DEFAULT_ICON_COLOR },
    { name: 'questionmark', icon: CircleHelp, color: DEFAULT_ICON_COLOR },
    { name: 'help', icon: HelpCircle, color: DEFAULT_ICON_COLOR },
    { name: 'helpcircle', icon: HelpCircle, color: DEFAULT_ICON_COLOR },
    { name: 'bell', icon: Bell, color: DEFAULT_ICON_COLOR },
    { name: 'belloff', icon: BellOff, color: DEFAULT_ICON_COLOR },
    { name: 'bellringing', icon: BellRing, color: DEFAULT_ICON_COLOR },
    { name: 'pin', icon: Pin, color: DEFAULT_ICON_COLOR },
    { name: 'pinned', icon: Pin, color: DEFAULT_ICON_COLOR },
    { name: 'pinnedoff', icon: PinOff, color: DEFAULT_ICON_COLOR },
    { name: 'flag', icon: Flag, color: DEFAULT_ICON_COLOR },
    { name: 'flagfilled', icon: Flag, color: DEFAULT_ICON_COLOR },
    { name: 'flag2', icon: FlagTriangleRight, color: DEFAULT_ICON_COLOR },
    { name: 'flag3', icon: Flag, color: DEFAULT_ICON_COLOR },
    { name: 'filter', icon: Filter, color: DEFAULT_ICON_COLOR },
    { name: 'filteroff', icon: FilterX, color: DEFAULT_ICON_COLOR },
    { name: 'refresh', icon: RefreshCw, color: DEFAULT_ICON_COLOR },
    { name: 'refreshoff', icon: RefreshCcw, color: DEFAULT_ICON_COLOR },
    { name: 'rotate', icon: RotateCw, color: DEFAULT_ICON_COLOR },
    { name: 'rotateclockwise', icon: RotateCw, color: DEFAULT_ICON_COLOR },
    { name: 'rotate2', icon: RotateCcw, color: DEFAULT_ICON_COLOR },
    { name: 'copy', icon: Copy, color: DEFAULT_ICON_COLOR },
    { name: 'copyoff', icon: CopyX, color: DEFAULT_ICON_COLOR },
    { name: 'share', icon: Share, color: DEFAULT_ICON_COLOR },
    { name: 'shareoff', icon: Share2, color: DEFAULT_ICON_COLOR },
    { name: 'edit', icon: Edit, color: DEFAULT_ICON_COLOR },
    { name: 'editoff', icon: Edit3, color: DEFAULT_ICON_COLOR },
    { name: 'power', icon: Power, color: DEFAULT_ICON_COLOR },
    { name: 'poweroff', icon: PowerOff, color: DEFAULT_ICON_COLOR },
    { name: 'logout', icon: LogOut, color: DEFAULT_ICON_COLOR },
    { name: 'login', icon: LogIn, color: DEFAULT_ICON_COLOR },
    { name: 'zoomin', icon: ZoomIn, color: DEFAULT_ICON_COLOR },
    { name: 'zoomout', icon: ZoomOut, color: DEFAULT_ICON_COLOR },
    { name: 'zoomreset', icon: ScanSearch, color: DEFAULT_ICON_COLOR },
    { name: 'zoomcheck', icon: ZoomIn, color: DEFAULT_ICON_COLOR },
    { name: 'maximize', icon: Maximize, color: DEFAULT_ICON_COLOR },
    { name: 'minimize', icon: Minimize, color: DEFAULT_ICON_COLOR },
    { name: 'adjustments', icon: SlidersVertical, color: DEFAULT_ICON_COLOR },
    { name: 'adjustmentshorizontal', icon: SlidersHorizontal, color: DEFAULT_ICON_COLOR },
    { name: 'listcheck', icon: ListChecks, color: DEFAULT_ICON_COLOR },
    { name: 'checklist', icon: ClipboardCheck, color: DEFAULT_ICON_COLOR },
    { name: 'progress', icon: Loader, color: DEFAULT_ICON_COLOR },
    { name: 'progresscheck', icon: Loader2, color: DEFAULT_ICON_COLOR },
    { name: 'activity', icon: Activity, color: DEFAULT_ICON_COLOR },
    { name: 'pulse', icon: HeartPulse, color: DEFAULT_ICON_COLOR },
    { name: 'wavesine', icon: AudioWaveform, color: DEFAULT_ICON_COLOR },
    { name: 'chartdots', icon: ChartScatter, color: DEFAULT_ICON_COLOR },
    { name: 'loader', icon: Loader, color: DEFAULT_ICON_COLOR },
    { name: 'loader2', icon: Loader2, color: DEFAULT_ICON_COLOR },
    { name: 'hourglass', icon: Hourglass, color: DEFAULT_ICON_COLOR },
    { name: 'hourglasshigh', icon: Hourglass, color: DEFAULT_ICON_COLOR },
    { name: 'hourglasslow', icon: Hourglass, color: DEFAULT_ICON_COLOR },
    { name: 'hourglassempty', icon: Hourglass, color: DEFAULT_ICON_COLOR },
    { name: 'circledot', icon: CircleDot, color: DEFAULT_ICON_COLOR },
    { name: 'circledotted', icon: CircleDashed, color: DEFAULT_ICON_COLOR },
    { name: 'circlehalf', icon: CircleSlash, color: DEFAULT_ICON_COLOR },
    { name: 'circle', icon: Circle, color: DEFAULT_ICON_COLOR },
    { name: 'square', icon: Square, color: DEFAULT_ICON_COLOR },
    { name: 'triangle', icon: Triangle, color: DEFAULT_ICON_COLOR },
    { name: 'diamond', icon: Diamond, color: DEFAULT_ICON_COLOR },
    { name: 'star', icon: Star, color: DEFAULT_ICON_COLOR },
    { name: 'starhalf', icon: StarHalf, color: DEFAULT_ICON_COLOR },
    { name: 'staroff', icon: StarOff, color: DEFAULT_ICON_COLOR },
    { name: 'eye', icon: Eye, color: DEFAULT_ICON_COLOR },
    { name: 'eyeoff', icon: EyeOff, color: DEFAULT_ICON_COLOR },
    { name: 'eyecheck', icon: Eye, color: DEFAULT_ICON_COLOR },
    { name: 'lock', icon: Lock, color: DEFAULT_ICON_COLOR },
    { name: 'lockoff', icon: LockOpen, color: DEFAULT_ICON_COLOR },
    { name: 'lockopen', icon: LockOpen, color: DEFAULT_ICON_COLOR },
    { name: 'shield', icon: Shield, color: DEFAULT_ICON_COLOR },
    { name: 'shieldcheck', icon: ShieldCheck, color: DEFAULT_ICON_COLOR },
    { name: 'shieldoff', icon: ShieldOff, color: DEFAULT_ICON_COLOR },
    { name: 'shieldlock', icon: Shield, color: DEFAULT_ICON_COLOR },
    { name: 'toggleleft', icon: ToggleLeft, color: DEFAULT_ICON_COLOR },
    { name: 'toggleright', icon: ToggleRight, color: DEFAULT_ICON_COLOR },
    { name: 'switch', icon: ToggleLeft, color: DEFAULT_ICON_COLOR },
    { name: 'switch2', icon: ToggleRight, color: DEFAULT_ICON_COLOR },
    { name: 'switch3', icon: ToggleLeft, color: DEFAULT_ICON_COLOR },
    { name: 'playerplay', icon: Play, color: DEFAULT_ICON_COLOR },
    { name: 'playerpause', icon: Pause, color: DEFAULT_ICON_COLOR },
    { name: 'playerstop', icon: StopCircle, color: DEFAULT_ICON_COLOR },
    { name: 'playerrecord', icon: Circle, color: DEFAULT_ICON_COLOR },
  ],
};
