import {
  IconCheck,
  IconX,
  IconAlertCircle,
  IconAlertTriangle,
  IconAlertOctagon,
  IconInfoCircle,
  IconInfoSquare,
  IconQuestionMark,
  IconHelp,
  IconHelpCircle,
  IconBell,
  IconBellOff,
  IconBellRinging,
  IconPin,
  IconPinned,
  IconPinnedOff,
  IconFlag,
  IconFlagFilled,
  IconFlag2,
  IconFlag3,
  IconFilter,
  IconFilterOff,
  IconRefresh,
  IconRefreshOff,
  IconRotate,
  IconRotateClockwise,
  IconRotate2,
  IconCopy,
  IconCopyOff,
  IconShare,
  IconShareOff,
  IconEdit,
  IconEditOff,
  IconPower,
  IconPlugConnectedX,
  IconLogout,
  IconLogin,
  IconZoomIn,
  IconZoomOut,
  IconZoomReset,
  IconZoomCheck,
  IconMaximize,
  IconMinimize,
  IconAdjustments,
  IconAdjustmentsHorizontal,
  IconListCheck,
  IconChecklist,
  IconProgress,
  IconProgressCheck,
  IconActivity,
  IconHeartbeat,
  IconHeartRateMonitor,
  IconWaveSine,
  IconChartDots,
  IconLoader,
  IconLoader2,
  IconHourglass,
  IconHourglassHigh,
  IconHourglassLow,
  IconHourglassEmpty,
  IconCircleDot,
  IconCircleDotted,
  IconCircleHalf,
  IconCircle,
  IconSquare,
  IconTriangle,
  IconDiamond,
  IconStar,
  IconStarHalf,
  IconStarOff,
  IconEye,
  IconEyeOff,
  IconEyeCheck,
  IconLock,
  IconLockOff,
  IconLockOpen,
  IconShield,
  IconShieldCheck,
  IconShieldOff,
  IconShieldLock,
  IconToggleLeft,
  IconToggleRight,
  IconSwitch,
  IconSwitch2,
  IconSwitch3,
  IconPlayerPlay,
  IconPlayerPause,
  IconPlayerStop,
  IconPlayerRecord,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const statusIcons: IconCategory = {
  id: 'status',
  name: '状态',
  emoji: IconHeartbeat,
  icons: [
    { name: 'check', icon: IconCheck, color: DEFAULT_ICON_COLOR },
    { name: 'x', icon: IconX, color: DEFAULT_ICON_COLOR },
    { name: 'alertcircle', icon: IconAlertCircle, color: DEFAULT_ICON_COLOR },
    { name: 'alerttriangle', icon: IconAlertTriangle, color: DEFAULT_ICON_COLOR },
    { name: 'alertoctagon', icon: IconAlertOctagon, color: DEFAULT_ICON_COLOR },
    { name: 'infocircle', icon: IconInfoCircle, color: DEFAULT_ICON_COLOR },
    { name: 'infosquare', icon: IconInfoSquare, color: DEFAULT_ICON_COLOR },
    { name: 'questionmark', icon: IconQuestionMark, color: DEFAULT_ICON_COLOR },
    { name: 'help', icon: IconHelp, color: DEFAULT_ICON_COLOR },
    { name: 'helpcircle', icon: IconHelpCircle, color: DEFAULT_ICON_COLOR },
    { name: 'bell', icon: IconBell, color: DEFAULT_ICON_COLOR },
    { name: 'belloff', icon: IconBellOff, color: DEFAULT_ICON_COLOR },
    { name: 'bellringing', icon: IconBellRinging, color: DEFAULT_ICON_COLOR },
    { name: 'pin', icon: IconPin, color: DEFAULT_ICON_COLOR },
    { name: 'pinned', icon: IconPinned, color: DEFAULT_ICON_COLOR },
    { name: 'pinnedoff', icon: IconPinnedOff, color: DEFAULT_ICON_COLOR },
    { name: 'flag', icon: IconFlag, color: DEFAULT_ICON_COLOR },
    { name: 'flagfilled', icon: IconFlagFilled, color: DEFAULT_ICON_COLOR },
    { name: 'flag2', icon: IconFlag2, color: DEFAULT_ICON_COLOR },
    { name: 'flag3', icon: IconFlag3, color: DEFAULT_ICON_COLOR },
    { name: 'filter', icon: IconFilter, color: DEFAULT_ICON_COLOR },
    { name: 'filteroff', icon: IconFilterOff, color: DEFAULT_ICON_COLOR },
    { name: 'refresh', icon: IconRefresh, color: DEFAULT_ICON_COLOR },
    { name: 'refreshoff', icon: IconRefreshOff, color: DEFAULT_ICON_COLOR },
    { name: 'rotate', icon: IconRotate, color: DEFAULT_ICON_COLOR },
    { name: 'rotateclockwise', icon: IconRotateClockwise, color: DEFAULT_ICON_COLOR },
    { name: 'rotate2', icon: IconRotate2, color: DEFAULT_ICON_COLOR },
    { name: 'copy', icon: IconCopy, color: DEFAULT_ICON_COLOR },
    { name: 'copyoff', icon: IconCopyOff, color: DEFAULT_ICON_COLOR },
    { name: 'share', icon: IconShare, color: DEFAULT_ICON_COLOR },
    { name: 'shareoff', icon: IconShareOff, color: DEFAULT_ICON_COLOR },
    { name: 'edit', icon: IconEdit, color: DEFAULT_ICON_COLOR },
    { name: 'editoff', icon: IconEditOff, color: DEFAULT_ICON_COLOR },
    { name: 'power', icon: IconPower, color: DEFAULT_ICON_COLOR },
    { name: 'poweroff', icon: IconPlugConnectedX, color: DEFAULT_ICON_COLOR },
    { name: 'logout', icon: IconLogout, color: DEFAULT_ICON_COLOR },
    { name: 'login', icon: IconLogin, color: DEFAULT_ICON_COLOR },
    { name: 'zoomin', icon: IconZoomIn, color: DEFAULT_ICON_COLOR },
    { name: 'zoomout', icon: IconZoomOut, color: DEFAULT_ICON_COLOR },
    { name: 'zoomreset', icon: IconZoomReset, color: DEFAULT_ICON_COLOR },
    { name: 'zoomcheck', icon: IconZoomCheck, color: DEFAULT_ICON_COLOR },
    { name: 'maximize', icon: IconMaximize, color: DEFAULT_ICON_COLOR },
    { name: 'minimize', icon: IconMinimize, color: DEFAULT_ICON_COLOR },
    { name: 'adjustments', icon: IconAdjustments, color: DEFAULT_ICON_COLOR },
    { name: 'adjustmentshorizontal', icon: IconAdjustmentsHorizontal, color: DEFAULT_ICON_COLOR },
    { name: 'listcheck', icon: IconListCheck, color: DEFAULT_ICON_COLOR },
    { name: 'checklist', icon: IconChecklist, color: DEFAULT_ICON_COLOR },
    { name: 'progress', icon: IconProgress, color: DEFAULT_ICON_COLOR },
    { name: 'progresscheck', icon: IconProgressCheck, color: DEFAULT_ICON_COLOR },
    { name: 'activity', icon: IconActivity, color: DEFAULT_ICON_COLOR },
    { name: 'pulse', icon: IconHeartbeat, color: DEFAULT_ICON_COLOR },
    { name: 'wavesine', icon: IconWaveSine, color: DEFAULT_ICON_COLOR },
    { name: 'chartdots', icon: IconChartDots, color: DEFAULT_ICON_COLOR },
    { name: 'loader', icon: IconLoader, color: DEFAULT_ICON_COLOR },
    { name: 'loader2', icon: IconLoader2, color: DEFAULT_ICON_COLOR },
    { name: 'hourglass', icon: IconHourglass, color: DEFAULT_ICON_COLOR },
    { name: 'hourglasshigh', icon: IconHourglassHigh, color: DEFAULT_ICON_COLOR },
    { name: 'hourglasslow', icon: IconHourglassLow, color: DEFAULT_ICON_COLOR },
    { name: 'hourglassempty', icon: IconHourglassEmpty, color: DEFAULT_ICON_COLOR },
    { name: 'circledot', icon: IconCircleDot, color: DEFAULT_ICON_COLOR },
    { name: 'circledotted', icon: IconCircleDotted, color: DEFAULT_ICON_COLOR },
    { name: 'circlehalf', icon: IconCircleHalf, color: DEFAULT_ICON_COLOR },
    { name: 'circle', icon: IconCircle, color: DEFAULT_ICON_COLOR },
    { name: 'square', icon: IconSquare, color: DEFAULT_ICON_COLOR },
    { name: 'triangle', icon: IconTriangle, color: DEFAULT_ICON_COLOR },
    { name: 'diamond', icon: IconDiamond, color: DEFAULT_ICON_COLOR },
    { name: 'star', icon: IconStar, color: DEFAULT_ICON_COLOR },
    { name: 'starhalf', icon: IconStarHalf, color: DEFAULT_ICON_COLOR },
    { name: 'staroff', icon: IconStarOff, color: DEFAULT_ICON_COLOR },
    { name: 'eye', icon: IconEye, color: DEFAULT_ICON_COLOR },
    { name: 'eyeoff', icon: IconEyeOff, color: DEFAULT_ICON_COLOR },
    { name: 'eyecheck', icon: IconEyeCheck, color: DEFAULT_ICON_COLOR },
    { name: 'lock', icon: IconLock, color: DEFAULT_ICON_COLOR },
    { name: 'lockoff', icon: IconLockOff, color: DEFAULT_ICON_COLOR },
    { name: 'lockopen', icon: IconLockOpen, color: DEFAULT_ICON_COLOR },
    { name: 'shield', icon: IconShield, color: DEFAULT_ICON_COLOR },
    { name: 'shieldcheck', icon: IconShieldCheck, color: DEFAULT_ICON_COLOR },
    { name: 'shieldoff', icon: IconShieldOff, color: DEFAULT_ICON_COLOR },
    { name: 'shieldlock', icon: IconShieldLock, color: DEFAULT_ICON_COLOR },
    { name: 'toggleleft', icon: IconToggleLeft, color: DEFAULT_ICON_COLOR },
    { name: 'toggleright', icon: IconToggleRight, color: DEFAULT_ICON_COLOR },
    { name: 'switch', icon: IconSwitch, color: DEFAULT_ICON_COLOR },
    { name: 'switch2', icon: IconSwitch2, color: DEFAULT_ICON_COLOR },
    { name: 'switch3', icon: IconSwitch3, color: DEFAULT_ICON_COLOR },
    { name: 'playerplay', icon: IconPlayerPlay, color: DEFAULT_ICON_COLOR },
    { name: 'playerpause', icon: IconPlayerPause, color: DEFAULT_ICON_COLOR },
    { name: 'playerstop', icon: IconPlayerStop, color: DEFAULT_ICON_COLOR },
    { name: 'playerrecord', icon: IconPlayerRecord, color: DEFAULT_ICON_COLOR },
  ],
};
