import {
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UserCog,
  UserCircle,
  UserSquare,
  Users,
  UsersRound,
  Smile,
  SmilePlus,
  Laugh,
  Frown,
  Angry,
  Meh,
  ThumbsUp,
  ThumbsDown,
  Eye,
  EyeOff,
  Mail,
  MailOpen,
  MailX,
  Forward,
  MessageSquare,
  MessageCircle,
  MessagesSquare,
  Send,
  SendHorizontal,
  Inbox,
  Phone,
  PhoneCall,
  PhoneOff,
  PhoneIncoming,
  PhoneOutgoing,
  AtSign,
  Hash,
  Tag,
  Tags,
  Link,
  Link2Off,
  ExternalLink,
  Globe,
  Globe2,
  Facebook,
  Instagram,
  Linkedin,
  Twitter,
  Ghost,
  Dribbble,
  BookUser,
  IdCard,
  Heart,
  Star,
} from 'lucide-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const userIcons: IconCategory = {
  id: 'user',
  name: 'Social',
  emoji: Send,
  icons: [
    { name: 'user', icon: User, color: DEFAULT_ICON_COLOR },
    { name: 'userfilled', icon: User, color: DEFAULT_ICON_COLOR },
    { name: 'userplus', icon: UserPlus, color: DEFAULT_ICON_COLOR },
    { name: 'userminus', icon: UserMinus, color: DEFAULT_ICON_COLOR },
    { name: 'usercheck', icon: UserCheck, color: DEFAULT_ICON_COLOR },
    { name: 'userx', icon: UserX, color: DEFAULT_ICON_COLOR },
    { name: 'useroff', icon: UserCog, color: DEFAULT_ICON_COLOR },
    { name: 'usercircle', icon: UserCircle, color: DEFAULT_ICON_COLOR },
    { name: 'usersquare', icon: UserSquare, color: DEFAULT_ICON_COLOR },
    { name: 'userheart', icon: Heart, color: DEFAULT_ICON_COLOR },
    { name: 'userstar', icon: Star, color: DEFAULT_ICON_COLOR },
    { name: 'usershield', icon: User, color: DEFAULT_ICON_COLOR },
    { name: 'users', icon: Users, color: DEFAULT_ICON_COLOR },
    { name: 'usersgroup', icon: UsersRound, color: DEFAULT_ICON_COLOR },
    { name: 'usersminus', icon: Users, color: DEFAULT_ICON_COLOR },
    { name: 'usersplus', icon: Users, color: DEFAULT_ICON_COLOR },
    { name: 'friends', icon: Users, color: DEFAULT_ICON_COLOR },
    { name: 'friendsoff', icon: Users, color: DEFAULT_ICON_COLOR },
    { name: 'moodsmile', icon: Smile, color: DEFAULT_ICON_COLOR },
    { name: 'moodsmilefilled', icon: Smile, color: DEFAULT_ICON_COLOR },
    { name: 'moodhappy', icon: SmilePlus, color: DEFAULT_ICON_COLOR },
    { name: 'moodhappyfilled', icon: SmilePlus, color: DEFAULT_ICON_COLOR },
    { name: 'moodwink', icon: Laugh, color: DEFAULT_ICON_COLOR },
    { name: 'moodsad', icon: Frown, color: DEFAULT_ICON_COLOR },
    { name: 'moodcry', icon: Frown, color: DEFAULT_ICON_COLOR },
    { name: 'moodangry', icon: Angry, color: DEFAULT_ICON_COLOR },
    { name: 'moodconfuzed', icon: Meh, color: DEFAULT_ICON_COLOR },
    { name: 'moodnervous', icon: Meh, color: DEFAULT_ICON_COLOR },
    { name: 'moodsick', icon: Frown, color: DEFAULT_ICON_COLOR },
    { name: 'moodtongue', icon: Laugh, color: DEFAULT_ICON_COLOR },
    { name: 'moodxd', icon: Laugh, color: DEFAULT_ICON_COLOR },
    { name: 'thumbup', icon: ThumbsUp, color: DEFAULT_ICON_COLOR },
    { name: 'thumbupfilled', icon: ThumbsUp, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdown', icon: ThumbsDown, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdownfilled', icon: ThumbsDown, color: DEFAULT_ICON_COLOR },
    { name: 'eye', icon: Eye, color: DEFAULT_ICON_COLOR },
    { name: 'eyefilled', icon: Eye, color: DEFAULT_ICON_COLOR },
    { name: 'eyeoff', icon: EyeOff, color: DEFAULT_ICON_COLOR },
    { name: 'eyecheck', icon: Eye, color: DEFAULT_ICON_COLOR },
    { name: 'mail', icon: Mail, color: DEFAULT_ICON_COLOR },
    { name: 'mailfilled', icon: Mail, color: DEFAULT_ICON_COLOR },
    { name: 'mailopened', icon: MailOpen, color: DEFAULT_ICON_COLOR },
    { name: 'mailoff', icon: MailX, color: DEFAULT_ICON_COLOR },
    { name: 'mailforward', icon: Forward, color: DEFAULT_ICON_COLOR },
    { name: 'message', icon: MessageSquare, color: DEFAULT_ICON_COLOR },
    { name: 'messagefilled', icon: MessageSquare, color: DEFAULT_ICON_COLOR },
    { name: 'messagecircle', icon: MessageCircle, color: DEFAULT_ICON_COLOR },
    { name: 'messagedots', icon: MessageCircle, color: DEFAULT_ICON_COLOR },
    { name: 'messageoff', icon: MessageSquare, color: DEFAULT_ICON_COLOR },
    { name: 'messageplus', icon: MessageSquare, color: DEFAULT_ICON_COLOR },
    { name: 'messages', icon: MessagesSquare, color: DEFAULT_ICON_COLOR },
    { name: 'send', icon: Send, color: DEFAULT_ICON_COLOR },
    { name: 'sendoff', icon: SendHorizontal, color: DEFAULT_ICON_COLOR },
    { name: 'inbox', icon: Inbox, color: DEFAULT_ICON_COLOR },
    { name: 'inboxoff', icon: Inbox, color: DEFAULT_ICON_COLOR },
    { name: 'phone', icon: Phone, color: DEFAULT_ICON_COLOR },
    { name: 'phonefilled', icon: Phone, color: DEFAULT_ICON_COLOR },
    { name: 'phonecall', icon: PhoneCall, color: DEFAULT_ICON_COLOR },
    { name: 'phoneoff', icon: PhoneOff, color: DEFAULT_ICON_COLOR },
    { name: 'phoneincoming', icon: PhoneIncoming, color: DEFAULT_ICON_COLOR },
    { name: 'phoneoutgoing', icon: PhoneOutgoing, color: DEFAULT_ICON_COLOR },
    { name: 'at', icon: AtSign, color: DEFAULT_ICON_COLOR },
    { name: 'atoff', icon: AtSign, color: DEFAULT_ICON_COLOR },
    { name: 'hash', icon: Hash, color: DEFAULT_ICON_COLOR },
    { name: 'tag', icon: Tag, color: DEFAULT_ICON_COLOR },
    { name: 'tagfilled', icon: Tag, color: DEFAULT_ICON_COLOR },
    { name: 'tagoff', icon: Tag, color: DEFAULT_ICON_COLOR },
    { name: 'tags', icon: Tags, color: DEFAULT_ICON_COLOR },
    { name: 'tagsoff', icon: Tags, color: DEFAULT_ICON_COLOR },
    { name: 'link', icon: Link, color: DEFAULT_ICON_COLOR },
    { name: 'linkoff', icon: Link2Off, color: DEFAULT_ICON_COLOR },
    { name: 'externallink', icon: ExternalLink, color: DEFAULT_ICON_COLOR },
    { name: 'world', icon: Globe, color: DEFAULT_ICON_COLOR },
    { name: 'worldwww', icon: Globe2, color: DEFAULT_ICON_COLOR },
    { name: 'facebook', icon: Facebook, color: DEFAULT_ICON_COLOR },
    { name: 'instagram', icon: Instagram, color: DEFAULT_ICON_COLOR },
    { name: 'linkedin', icon: Linkedin, color: DEFAULT_ICON_COLOR },
    { name: 'tiktok', icon: Twitter, color: DEFAULT_ICON_COLOR },
    { name: 'snapchat', icon: Ghost, color: DEFAULT_ICON_COLOR },
    { name: 'pinterest', icon: Twitter, color: DEFAULT_ICON_COLOR },
    { name: 'reddit', icon: Twitter, color: DEFAULT_ICON_COLOR },
    { name: 'medium', icon: Twitter, color: DEFAULT_ICON_COLOR },
    { name: 'dribbble', icon: Dribbble, color: DEFAULT_ICON_COLOR },
    { name: 'behance', icon: Dribbble, color: DEFAULT_ICON_COLOR },
    { name: 'addressbook', icon: BookUser, color: DEFAULT_ICON_COLOR },
    { name: 'addressbookoff', icon: BookUser, color: DEFAULT_ICON_COLOR },
    { name: 'id', icon: IdCard, color: DEFAULT_ICON_COLOR },
    { name: 'idoff', icon: IdCard, color: DEFAULT_ICON_COLOR },
  ],
};
