import {
  IconUser,
  IconUserFilled,
  IconUserPlus,
  IconUserMinus,
  IconUserCheck,
  IconUserX,
  IconUserOff,
  IconUserCircle,
  IconUserSquare,
  IconUserHeart,
  IconUserStar,
  IconUserShield,
  IconUsers,
  IconUsersGroup,
  IconUsersMinus,
  IconUsersPlus,
  IconFriends,
  IconFriendsOff,
  IconMoodSmile,
  IconMoodSmileFilled,
  IconMoodHappy,
  IconMoodHappyFilled,
  IconMoodWink,
  IconMoodSad,
  IconMoodCry,
  IconMoodAngry,
  IconMoodConfuzed,
  IconMoodNervous,
  IconMoodSick,
  IconMoodTongue,
  IconMoodXd,
  IconThumbUp,
  IconThumbUpFilled,
  IconThumbDown,
  IconThumbDownFilled,
  IconEye,
  IconEyeFilled,
  IconEyeOff,
  IconEyeCheck,
  IconMail,
  IconMailFilled,
  IconMailOpened,
  IconMailOff,
  IconMailForward,
  IconMessage,
  IconMessageFilled,
  IconMessageCircle,
  IconMessageDots,
  IconMessageOff,
  IconMessagePlus,
  IconMessages,
  IconSend,
  IconSendOff,
  IconInbox,
  IconInboxOff,
  IconPhone,
  IconPhoneFilled,
  IconPhoneCall,
  IconPhoneOff,
  IconPhoneIncoming,
  IconPhoneOutgoing,
  IconAt,
  IconAtOff,
  IconHash,
  IconTag,
  IconTagFilled,
  IconTagOff,
  IconTags,
  IconTagsOff,
  IconLink,
  IconLinkOff,
  IconExternalLink,
  IconWorld,
  IconWorldWww,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandTiktok,
  IconBrandSnapchat,
  IconBrandPinterest,
  IconBrandReddit,
  IconBrandMedium,
  IconBrandDribbble,
  IconBrandBehance,
  IconAddressBook,
  IconAddressBookOff,
  IconId,
  IconIdOff,
} from '@tabler/icons-react';
import { IconCategory, DEFAULT_ICON_COLOR } from './types';

export const userIcons: IconCategory = {
  id: 'user',
  name: '用户',
  emoji: IconSend,
  icons: [
    { name: 'user', icon: IconUser, color: DEFAULT_ICON_COLOR },
    { name: 'userfilled', icon: IconUserFilled, color: DEFAULT_ICON_COLOR },
    { name: 'userplus', icon: IconUserPlus, color: DEFAULT_ICON_COLOR },
    { name: 'userminus', icon: IconUserMinus, color: DEFAULT_ICON_COLOR },
    { name: 'usercheck', icon: IconUserCheck, color: DEFAULT_ICON_COLOR },
    { name: 'userx', icon: IconUserX, color: DEFAULT_ICON_COLOR },
    { name: 'useroff', icon: IconUserOff, color: DEFAULT_ICON_COLOR },
    { name: 'usercircle', icon: IconUserCircle, color: DEFAULT_ICON_COLOR },
    { name: 'usersquare', icon: IconUserSquare, color: DEFAULT_ICON_COLOR },
    { name: 'userheart', icon: IconUserHeart, color: DEFAULT_ICON_COLOR },
    { name: 'userstar', icon: IconUserStar, color: DEFAULT_ICON_COLOR },
    { name: 'usershield', icon: IconUserShield, color: DEFAULT_ICON_COLOR },
    { name: 'users', icon: IconUsers, color: DEFAULT_ICON_COLOR },
    { name: 'usersgroup', icon: IconUsersGroup, color: DEFAULT_ICON_COLOR },
    { name: 'usersminus', icon: IconUsersMinus, color: DEFAULT_ICON_COLOR },
    { name: 'usersplus', icon: IconUsersPlus, color: DEFAULT_ICON_COLOR },
    { name: 'friends', icon: IconFriends, color: DEFAULT_ICON_COLOR },
    { name: 'friendsoff', icon: IconFriendsOff, color: DEFAULT_ICON_COLOR },
    { name: 'moodsmile', icon: IconMoodSmile, color: DEFAULT_ICON_COLOR },
    { name: 'moodsmilefilled', icon: IconMoodSmileFilled, color: DEFAULT_ICON_COLOR },
    { name: 'moodhappy', icon: IconMoodHappy, color: DEFAULT_ICON_COLOR },
    { name: 'moodhappyfilled', icon: IconMoodHappyFilled, color: DEFAULT_ICON_COLOR },
    { name: 'moodwink', icon: IconMoodWink, color: DEFAULT_ICON_COLOR },
    { name: 'moodsad', icon: IconMoodSad, color: DEFAULT_ICON_COLOR },
    { name: 'moodcry', icon: IconMoodCry, color: DEFAULT_ICON_COLOR },
    { name: 'moodangry', icon: IconMoodAngry, color: DEFAULT_ICON_COLOR },
    { name: 'moodconfuzed', icon: IconMoodConfuzed, color: DEFAULT_ICON_COLOR },
    { name: 'moodnervous', icon: IconMoodNervous, color: DEFAULT_ICON_COLOR },
    { name: 'moodsick', icon: IconMoodSick, color: DEFAULT_ICON_COLOR },
    { name: 'moodtongue', icon: IconMoodTongue, color: DEFAULT_ICON_COLOR },
    { name: 'moodxd', icon: IconMoodXd, color: DEFAULT_ICON_COLOR },
    { name: 'thumbup', icon: IconThumbUp, color: DEFAULT_ICON_COLOR },
    { name: 'thumbupfilled', icon: IconThumbUpFilled, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdown', icon: IconThumbDown, color: DEFAULT_ICON_COLOR },
    { name: 'thumbdownfilled', icon: IconThumbDownFilled, color: DEFAULT_ICON_COLOR },
    { name: 'eye', icon: IconEye, color: DEFAULT_ICON_COLOR },
    { name: 'eyefilled', icon: IconEyeFilled, color: DEFAULT_ICON_COLOR },
    { name: 'eyeoff', icon: IconEyeOff, color: DEFAULT_ICON_COLOR },
    { name: 'eyecheck', icon: IconEyeCheck, color: DEFAULT_ICON_COLOR },
    { name: 'mail', icon: IconMail, color: DEFAULT_ICON_COLOR },
    { name: 'mailfilled', icon: IconMailFilled, color: DEFAULT_ICON_COLOR },
    { name: 'mailopened', icon: IconMailOpened, color: DEFAULT_ICON_COLOR },
    { name: 'mailoff', icon: IconMailOff, color: DEFAULT_ICON_COLOR },
    { name: 'mailforward', icon: IconMailForward, color: DEFAULT_ICON_COLOR },
    { name: 'message', icon: IconMessage, color: DEFAULT_ICON_COLOR },
    { name: 'messagefilled', icon: IconMessageFilled, color: DEFAULT_ICON_COLOR },
    { name: 'messagecircle', icon: IconMessageCircle, color: DEFAULT_ICON_COLOR },
    { name: 'messagedots', icon: IconMessageDots, color: DEFAULT_ICON_COLOR },
    { name: 'messageoff', icon: IconMessageOff, color: DEFAULT_ICON_COLOR },
    { name: 'messageplus', icon: IconMessagePlus, color: DEFAULT_ICON_COLOR },
    { name: 'messages', icon: IconMessages, color: DEFAULT_ICON_COLOR },
    { name: 'send', icon: IconSend, color: DEFAULT_ICON_COLOR },
    { name: 'sendoff', icon: IconSendOff, color: DEFAULT_ICON_COLOR },
    { name: 'inbox', icon: IconInbox, color: DEFAULT_ICON_COLOR },
    { name: 'inboxoff', icon: IconInboxOff, color: DEFAULT_ICON_COLOR },
    { name: 'phone', icon: IconPhone, color: DEFAULT_ICON_COLOR },
    { name: 'phonefilled', icon: IconPhoneFilled, color: DEFAULT_ICON_COLOR },
    { name: 'phonecall', icon: IconPhoneCall, color: DEFAULT_ICON_COLOR },
    { name: 'phoneoff', icon: IconPhoneOff, color: DEFAULT_ICON_COLOR },
    { name: 'phoneincoming', icon: IconPhoneIncoming, color: DEFAULT_ICON_COLOR },
    { name: 'phoneoutgoing', icon: IconPhoneOutgoing, color: DEFAULT_ICON_COLOR },
    { name: 'at', icon: IconAt, color: DEFAULT_ICON_COLOR },
    { name: 'atoff', icon: IconAtOff, color: DEFAULT_ICON_COLOR },
    { name: 'hash', icon: IconHash, color: DEFAULT_ICON_COLOR },
    { name: 'tag', icon: IconTag, color: DEFAULT_ICON_COLOR },
    { name: 'tagfilled', icon: IconTagFilled, color: DEFAULT_ICON_COLOR },
    { name: 'tagoff', icon: IconTagOff, color: DEFAULT_ICON_COLOR },
    { name: 'tags', icon: IconTags, color: DEFAULT_ICON_COLOR },
    { name: 'tagsoff', icon: IconTagsOff, color: DEFAULT_ICON_COLOR },
    { name: 'link', icon: IconLink, color: DEFAULT_ICON_COLOR },
    { name: 'linkoff', icon: IconLinkOff, color: DEFAULT_ICON_COLOR },
    { name: 'externallink', icon: IconExternalLink, color: DEFAULT_ICON_COLOR },
    { name: 'world', icon: IconWorld, color: DEFAULT_ICON_COLOR },
    { name: 'worldwww', icon: IconWorldWww, color: DEFAULT_ICON_COLOR },
    { name: 'facebook', icon: IconBrandFacebook, color: DEFAULT_ICON_COLOR },
    { name: 'instagram', icon: IconBrandInstagram, color: DEFAULT_ICON_COLOR },
    { name: 'linkedin', icon: IconBrandLinkedin, color: DEFAULT_ICON_COLOR },
    { name: 'tiktok', icon: IconBrandTiktok, color: DEFAULT_ICON_COLOR },
    { name: 'snapchat', icon: IconBrandSnapchat, color: DEFAULT_ICON_COLOR },
    { name: 'pinterest', icon: IconBrandPinterest, color: DEFAULT_ICON_COLOR },
    { name: 'reddit', icon: IconBrandReddit, color: DEFAULT_ICON_COLOR },
    { name: 'medium', icon: IconBrandMedium, color: DEFAULT_ICON_COLOR },
    { name: 'dribbble', icon: IconBrandDribbble, color: DEFAULT_ICON_COLOR },
    { name: 'behance', icon: IconBrandBehance, color: DEFAULT_ICON_COLOR },
    { name: 'addressbook', icon: IconAddressBook, color: DEFAULT_ICON_COLOR },
    { name: 'addressbookoff', icon: IconAddressBookOff, color: DEFAULT_ICON_COLOR },
    { name: 'id', icon: IconId, color: DEFAULT_ICON_COLOR },
    { name: 'idoff', icon: IconIdOff, color: DEFAULT_ICON_COLOR },
  ],
};
