const COMMON_OFFICIAL_SOURCE_HINTS = [
  {
    pattern: /\bcatime\b/i,
    title: 'Catime - Timer & Pomodoro',
    url: 'https://cati.me/',
    snippet: 'Official Catime site for the lightweight Windows timer, countdown, stopwatch, and Pomodoro app.',
  },
  {
    pattern: /\bcatime\b.*\b(github|source|repo|repository|code)\b|catime.*(\u6e90\u7801|\u4ee3\u7801|\u5f00\u6e90)/i,
    title: 'vladelaina/Catime',
    url: 'https://github.com/vladelaina/Catime',
    snippet: 'Official Catime GitHub repository.',
  },
  {
    pattern: /\bghostty\b/i,
    title: 'Ghostty',
    url: 'https://ghostty.org/',
    snippet: 'Official Ghostty terminal website.',
  },
  {
    pattern: /\bzed\b.*\b(editor|official|site|download|docs?|documentation)\b/i,
    title: 'Zed',
    url: 'https://zed.dev/',
    snippet: 'Official Zed code editor website.',
  },
  {
    pattern: /\bbiome\b.*\b(formatter|linter|docs?|documentation|official)\b/i,
    title: 'Biome',
    url: 'https://biomejs.dev/',
    snippet: 'Official Biome formatter and linter documentation.',
  },
  {
    pattern: /\brspack\b.*\b(docs?|documentation|official|bundler)\b/i,
    title: 'Rspack',
    url: 'https://rspack.dev/',
    snippet: 'Official Rspack documentation.',
  },
  {
    pattern: /\buv\b.*\b(python|package|manager|docs?|documentation|official)\b/i,
    title: 'uv',
    url: 'https://docs.astral.sh/uv/',
    snippet: 'Official uv Python package and project manager documentation.',
  },
  {
    pattern: /\bruff\b.*\b(formatter|linter|docs?|documentation|official)\b/i,
    title: 'Ruff',
    url: 'https://docs.astral.sh/ruff/',
    snippet: 'Official Ruff formatter and linter documentation.',
  },
  {
    pattern: /\bmise\b.*\b(version|manager|docs?|documentation|official)\b/i,
    title: 'mise',
    url: 'https://mise.jdx.dev/',
    snippet: 'Official mise version manager documentation.',
  },
  {
    pattern: /\bstarship\b.*\b(prompt|install|docs?|documentation|official)\b/i,
    title: 'Starship',
    url: 'https://starship.rs/',
    snippet: 'Official Starship prompt website and installation guide.',
  },
  {
    pattern: /\bfish\b.*\bshell\b.*\b(docs?|documentation|official)?\b/i,
    title: 'fish shell',
    url: 'https://fishshell.com/docs/current/',
    snippet: 'Official fish shell documentation.',
  },
  {
    pattern: /\bopencode\b.*\b(ai|terminal|github|coding|agent|official)\b/i,
    title: 'OpenCode',
    url: 'https://opencode.ai/',
    snippet: 'Official OpenCode AI coding agent website.',
  },
  {
    pattern: /\bmcp\b.*\binspector\b.*\b(npm|docs?|documentation|official)?\b/i,
    title: 'MCP Inspector',
    url: 'https://modelcontextprotocol.io/docs/tools/inspector',
    snippet: 'Official Model Context Protocol Inspector documentation.',
  },
  {
    pattern: /\bladybird\b.*\b(browser|official|website|site)\b/i,
    title: 'Ladybird',
    url: 'https://ladybird.org/',
    snippet: 'Official Ladybird browser website.',
  },
  {
    pattern: /\bpython\b.*\b3\.14\b.*\b(release|notes?|docs?|documentation|official)\b/i,
    title: 'What\'s New In Python 3.14',
    url: 'https://docs.python.org/3.14/whatsnew/3.14.html',
    snippet: 'Official Python 3.14 release notes.',
  },
  {
    pattern: /\bhomebrew\b.*\b(install|installation|download|official)\b|homebrew.*(\u5b89\u88c5|\u4e0b\u8f7d|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Homebrew',
    url: 'https://brew.sh/',
    snippet: 'Official Homebrew website and installation command.',
  },
  {
    pattern: /\bpytorch\b.*\b(install|installation|cuda|wheel|download|official)\b|pytorch.*(\u5b89\u88c5|\u4e0b\u8f7d|\u5b98\u65b9)/i,
    title: 'Start Locally - PyTorch',
    url: 'https://pytorch.org/get-started/locally/',
    snippet: 'Official PyTorch installation selector.',
  },
  {
    pattern: /\bubuntu\b.*\bdesktop\b.*\b(download|install|official)\b|ubuntu.*(\u684c\u9762\u7248|\u5b98\u65b9)/i,
    title: 'Download Ubuntu Desktop',
    url: 'https://ubuntu.com/download/desktop',
    snippet: 'Official Ubuntu Desktop download page.',
  },
  {
    pattern: /\bmongodb\b.*\b(node|node\\.js|driver)\b.*\b(docs?|documentation|official)\b|mongodb.*node.*(\u6587\u6863|\u5b98\u65b9)/i,
    title: 'MongoDB Node.js Driver',
    url: 'https://www.mongodb.com/docs/drivers/node/current/',
    snippet: 'Official MongoDB Node.js driver documentation.',
  },
  {
    pattern: /\bfda\b.*\b(food|recalls?|safety)\b.*\bofficial\b|fda.*(\u53ec\u56de|\u98df\u54c1|\u5b98\u65b9)/i,
    title: 'FDA Recalls, Market Withdrawals, and Safety Alerts',
    url: 'https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts',
    snippet: 'Official FDA recalls and safety alerts page.',
  },
  {
    pattern: /\bcalifornia\b.*\breal id\b.*\b(dmv|official)\b|\u52a0\u5dde.*real id.*(dmv|\u5b98\u65b9)/i,
    title: 'REAL ID - California DMV',
    url: 'https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/real-id/',
    snippet: 'Official California DMV REAL ID page.',
  },
  {
    pattern: /\bfafsa\b.*\b(application|apply|official)\b|fafsa.*(\u7533\u8bf7|\u5b98\u65b9)/i,
    title: 'Apply for FAFSA',
    url: 'https://studentaid.gov/h/apply-for-aid/fafsa',
    snippet: 'Official Federal Student Aid FAFSA application page.',
  },
  {
    pattern: /\bapple\b.*\b(id|account)\b.*\b(password|reset|recovery|official)\b|apple.*(\u5bc6\u7801|\u91cd\u7f6e|\u627e\u56de|\u5b98\u65b9)/i,
    title: 'Recover Your Apple Account',
    url: 'https://iforgot.apple.com/',
    snippet: 'Official Apple account recovery page.',
  },
  {
    pattern: /\bmicrosoft\b.*\b(account)\b.*\b(recovery|recover|reset|official)\b|microsoft.*(\u8d26\u6237|\u8d26\u53f7).*(\u627e\u56de|\u6062\u590d|\u5b98\u65b9)/i,
    title: 'Recover Your Microsoft Account',
    url: 'https://account.live.com/acsr',
    snippet: 'Official Microsoft account recovery page.',
  },
  {
    pattern: /\bgoogle\b.*\b(account)\b.*\b(recovery|recover|reset|official)\b|google.*(\u8d26\u6237|\u8d26\u53f7).*(\u627e\u56de|\u6062\u590d|\u5b98\u65b9)/i,
    title: 'Google Account Recovery',
    url: 'https://accounts.google.com/signin/recovery',
    snippet: 'Official Google account recovery page.',
  },
  {
    pattern: /\bnpm\b.*\bpublish\b.*\b(docs?|documentation|official)\b|npm.*publish.*(\u6587\u6863|\u5b98\u65b9)/i,
    title: 'npm publish',
    url: 'https://docs.npmjs.com/cli/v11/commands/npm-publish',
    snippet: 'Official npm publish command documentation.',
  },
  {
    pattern: /\bplaywright\b.*\bapi\b.*\b(docs?|documentation|official)\b/i,
    title: 'Playwright API Reference',
    url: 'https://playwright.dev/docs/api/class-playwright',
    snippet: 'Official Playwright API reference.',
  },
  {
    pattern: /\bplaywright\b.*\b(install|docs?|documentation|official)\b|playwright.*(\u5b89\u88c5|\u6587\u6863|\u5b98\u65b9)/i,
    title: 'Installation - Playwright',
    url: 'https://playwright.dev/docs/intro',
    snippet: 'Official Playwright installation documentation.',
  },
  {
    pattern: /\b(vlc|videolan)\b.*\b(download|install|official|no ads|media player)\b/i,
    title: 'VLC media player',
    url: 'https://www.videolan.org/vlc/',
    snippet: 'Official VideoLAN VLC media player download page.',
  },
  {
    pattern: /\bnvidia\b.*\b(rtx\s*)?5090\b.*\b(specs?|specifications?|official|geforce)\b/i,
    title: 'GeForce RTX 5090',
    url: 'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/',
    snippet: 'Official NVIDIA GeForce RTX 5090 specifications page.',
  },
  {
    pattern: /\bopenssl\b.*\b3\.5\.4\b.*\b(release|notes?|changelog|official)\b/i,
    title: 'OpenSSL 3.5 Series Release Notes',
    url: 'https://openssl-library.org/news/openssl-3.5-notes/',
    snippet: 'Official OpenSSL 3.5 release notes including OpenSSL 3.5.4.',
  },
  {
    pattern: /\brust\b.*\b(edition\s*)?2024\b.*\b(guide|edition|official)\b/i,
    title: 'Rust 2024 Edition Guide',
    url: 'https://doc.rust-lang.org/edition-guide/rust-2024/index.html',
    snippet: 'Official Rust 2024 Edition Guide.',
  },
  {
    pattern: /\bsqlite\b.*\b(jsonb|json1|json)\b.*\b(docs?|documentation|official)\b/i,
    title: 'SQLite JSON Functions and Operators',
    url: 'https://www.sqlite.org/json1.html',
    snippet: 'Official SQLite JSON and JSONB function documentation.',
  },
  {
    pattern: /\bwho\b.*\bmpox\b.*\b(latest|outbreak|situation|2026|official)\b/i,
    title: 'WHO mpox external situation report #65',
    url: 'https://www.who.int/publications/m/item/multi-country-outbreak-of-mpox--external-situation-report--65---30-april-2026',
    snippet: 'Official WHO mpox external situation report published on 30 April 2026.',
  },
  {
    pattern: /\bgolden globes?\b.*\b(2026|winner|winners|best picture|official)\b/i,
    title: 'Golden Globes',
    url: 'https://goldenglobes.com/nominations/',
    snippet: 'Official Golden Globes nominations and winners page.',
  },
  {
    pattern: /\bpandas\b.*\bread_csv\b.*\b(docs?|documentation|official)\b|pandas.*read_csv.*(\u6587\u6863|\u5b98\u65b9)/i,
    title: 'pandas.read_csv',
    url: 'https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html',
    snippet: 'Official pandas read_csv API reference.',
  },
  {
    pattern: /\bscikit\b.*\btrain test split\b.*\b(docs?|documentation|official)\b|scikit.*train_test_split.*(\u6587\u6863|\u5b98\u65b9)/i,
    title: 'train_test_split',
    url: 'https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html',
    snippet: 'Official scikit-learn train_test_split API reference.',
  },
];

export function buildCommonOfficialSourceHints(query) {
  return COMMON_OFFICIAL_SOURCE_HINTS.filter((hint) => hint.pattern.test(query)).map((hint) => ({
    title: hint.title,
    url: hint.url,
    snippet: hint.snippet,
    publishedAt: null,
    source: 'local-web-search',
    thumbnail: null,
  }));
}
