const EVERYDAY_OFFICIAL_SOURCE_HINTS = [
  { pattern: /\birs\b.*\bfree file\b.*\bofficial\b/i, title: 'File Your Taxes for Free', url: 'https://www.irs.gov/file-your-taxes-for-free', snippet: 'Official IRS Free File options.' },
  { pattern: /\birs\b.*\b(free tax help|vita)\b.*\bofficial\b/i, title: 'Free Tax Return Preparation', url: 'https://www.irs.gov/individuals/free-tax-return-preparation-for-qualifying-taxpayers', snippet: 'Official IRS VITA and free tax help page.' },
  { pattern: /\birs\b.*\btax preparer directory\b.*\bofficial\b/i, title: 'Directory of Federal Tax Return Preparers', url: 'https://irs.treasury.gov/rpo/rpo.jsf', snippet: 'Official IRS tax preparer directory.' },
  { pattern: /\birs\b.*\bcharity search\b.*\bofficial\b/i, title: 'Tax Exempt Organization Search', url: 'https://www.irs.gov/charities-non-profits/tax-exempt-organization-search', snippet: 'Official IRS tax exempt organization search.' },
  { pattern: /\bsocial security\b.*\bretirement estimator\b.*\bofficial\b/i, title: 'Retirement Estimator', url: 'https://www.ssa.gov/benefits/retirement/estimator.html', snippet: 'Official Social Security retirement estimator.' },
  { pattern: /\bsocial security\b.*\bearnings record\b.*\bofficial\b/i, title: 'my Social Security', url: 'https://www.ssa.gov/myaccount/', snippet: 'Official Social Security account and earnings record page.' },
  { pattern: /\bmedicare\b.*\bplan compare\b.*\bofficial\b/i, title: 'Medicare Plan Compare', url: 'https://www.medicare.gov/plan-compare/', snippet: 'Official Medicare plan comparison tool.' },
  { pattern: /\bmedicare\b.*\bcosts\b.*\bofficial\b/i, title: 'Medicare Costs', url: 'https://www.medicare.gov/basics/costs/medicare-costs', snippet: 'Official Medicare costs information.' },
  { pattern: /\bhealthcare\.gov\b.*\bfind local help\b.*\bofficial\b/i, title: 'Find Local Help', url: 'https://localhelp.healthcare.gov/', snippet: 'Official HealthCare.gov local help finder.' },
  { pattern: /\bhhs\b.*\bhipaa complaint\b.*\bofficial\b/i, title: 'Filing a HIPAA Complaint', url: 'https://www.hhs.gov/hipaa/filing-a-complaint/index.html', snippet: 'Official HHS HIPAA complaint page.' },
  { pattern: /\bclinicaltrials\.gov\b.*\b(search|official)\b/i, title: 'ClinicalTrials.gov', url: 'https://clinicaltrials.gov/', snippet: 'Official ClinicalTrials.gov search portal.' },
  { pattern: /\bpubmed\b.*\bsearch\b.*\bofficial\b/i, title: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/', snippet: 'Official PubMed search portal.' },
  { pattern: /\bfoodsafety\.gov\b.*\brecalls?\b.*\bofficial\b/i, title: 'Food Recalls and Outbreaks', url: 'https://www.foodsafety.gov/recalls-and-outbreaks', snippet: 'Official FoodSafety.gov recalls and outbreaks page.' },
  { pattern: /\bfoodkeeper\b.*\bapp\b.*\bofficial\b/i, title: 'FoodKeeper App', url: 'https://www.foodsafety.gov/keep-food-safe/foodkeeper-app', snippet: 'Official FoodKeeper app page.' },
  { pattern: /\bfda\b.*\bfood recalls?\b.*\bofficial\b/i, title: 'Recalls, Market Withdrawals, and Safety Alerts', url: 'https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts', snippet: 'Official FDA recalls and safety alerts page.' },
  { pattern: /\bfda\b.*\bcosmetics\b.*\bofficial\b/i, title: 'Cosmetics', url: 'https://www.fda.gov/cosmetics', snippet: 'Official FDA cosmetics information.' },
  { pattern: /\bcdc\b.*\bgrowth charts?\b.*\bofficial\b/i, title: 'Growth Charts', url: 'https://www.cdc.gov/growthcharts/', snippet: 'Official CDC growth charts.' },
  { pattern: /\bcdc\b.*\bchild bmi calculator\b.*\bofficial\b/i, title: 'Child and Teen BMI Calculator', url: 'https://www.cdc.gov/bmi/child-teen-calculator/', snippet: 'Official CDC child and teen BMI calculator.' },
  { pattern: /\bnhtsa\b.*\bvin decoder\b.*\bofficial\b/i, title: 'VIN Decoder', url: 'https://vpic.nhtsa.dot.gov/decoder/', snippet: 'Official NHTSA VIN decoder.' },
  { pattern: /\bnhtsa\b.*\bcar seat finder\b.*\bofficial\b/i, title: 'Car Seats and Booster Seats', url: 'https://www.nhtsa.gov/equipment/car-seats-and-booster-seats', snippet: 'Official NHTSA car seat information.' },
  { pattern: /\bfaa\b.*\bdrone registration\b.*\bofficial\b/i, title: 'FAADroneZone', url: 'https://faadronezone-access.faa.gov/', snippet: 'Official FAA drone registration portal.' },
  { pattern: /\bfaa\b.*\bairport delays?\b.*\bofficial\b/i, title: 'NAS Status', url: 'https://nasstatus.faa.gov/', snippet: 'Official FAA airport delay status page.' },
  { pattern: /\bcbp\b.*\bborder wait times\b.*\bofficial\b/i, title: 'Border Wait Times', url: 'https://bwt.cbp.gov/', snippet: 'Official CBP border wait times.' },
  { pattern: /\bstate department\b.*\btravel advisories\b.*\bofficial\b/i, title: 'Travel Advisories', url: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories.html', snippet: 'Official State Department travel advisories.' },
  { pattern: /\bstep enrollment\b.*\bstate department\b/i, title: 'Smart Traveler Enrollment Program', url: 'https://step.state.gov/', snippet: 'Official STEP enrollment portal.' },
  { pattern: /\bfind\b.*\bus embassy\b.*\bofficial\b/i, title: 'U.S. Embassies', url: 'https://www.usembassy.gov/', snippet: 'Official U.S. embassy directory.' },
  { pattern: /\btsa\b.*\bmedication rules\b.*\bofficial\b/i, title: 'What Can I Bring? Medical', url: 'https://www.tsa.gov/travel/security-screening/whatcanibring/medical', snippet: 'Official TSA medical item screening rules.' },
  { pattern: /\busps\b.*\bhold mail\b.*\bofficial\b/i, title: 'Hold Mail', url: 'https://www.usps.com/manage/hold-mail.htm', snippet: 'Official USPS Hold Mail service.' },
  { pattern: /\busps\b.*\binformed delivery\b.*\bofficial\b/i, title: 'Informed Delivery', url: 'https://informeddelivery.usps.com/', snippet: 'Official USPS Informed Delivery service.' },
  { pattern: /\busps\b.*\bpo box\b.*\bofficial\b/i, title: 'PO Boxes', url: 'https://www.usps.com/manage/po-boxes.htm', snippet: 'Official USPS PO Box service.' },
  { pattern: /\busps\b.*\bpassport appointment\b.*\bofficial\b/i, title: 'Retail Customer Appointment Scheduler', url: 'https://tools.usps.com/rcas.htm', snippet: 'Official USPS passport appointment scheduler.' },
  { pattern: /\bfcc\b.*\blicense search\b.*\bofficial\b/i, title: 'ULS License Search', url: 'https://wireless2.fcc.gov/UlsApp/UlsSearch/searchLicense.jsp', snippet: 'Official FCC license search.' },
  { pattern: /\bfcc\b.*\bnetwork outage reporting\b.*\bofficial\b/i, title: 'Network Outage Reporting System', url: 'https://www.fcc.gov/network-outage-reporting-system-nors', snippet: 'Official FCC NORS page.' },
  { pattern: /\bfcc\b.*\bbroadband labels?\b.*\bofficial\b/i, title: 'Broadband Labels', url: 'https://www.fcc.gov/broadbandlabels', snippet: 'Official FCC broadband labels page.' },
  { pattern: /\bcensus\b.*\bquickfacts\b.*\bofficial\b/i, title: 'QuickFacts', url: 'https://www.census.gov/quickfacts/', snippet: 'Official Census QuickFacts.' },
  { pattern: /\bcensus\b.*\bdata\b.*\bofficial\b/i, title: 'Explore Census Data', url: 'https://data.census.gov/', snippet: 'Official Census data portal.' },
  { pattern: /\bbls\b.*\bcpi\b.*\bofficial\b/i, title: 'Consumer Price Index', url: 'https://www.bls.gov/cpi/', snippet: 'Official BLS CPI page.' },
  { pattern: /\bbls\b.*\boccupational outlook handbook\b.*\bofficial\b/i, title: 'Occupational Outlook Handbook', url: 'https://www.bls.gov/ooh/', snippet: 'Official BLS Occupational Outlook Handbook.' },
  { pattern: /\bbea\b.*\bgdp\b.*\bofficial\b/i, title: 'Gross Domestic Product', url: 'https://www.bea.gov/data/gdp', snippet: 'Official BEA GDP data.' },
  { pattern: /\btreasury\b.*\brates\b.*\bofficial\b/i, title: 'Interest Rates', url: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates', snippet: 'Official Treasury interest rates.' },
  { pattern: /\btreasurydirect\b.*\bauctions\b.*\bofficial\b/i, title: 'Treasury Auctions', url: 'https://www.treasurydirect.gov/auctions/', snippet: 'Official TreasuryDirect auctions page.' },
  { pattern: /\bsam\.gov\b.*\bentity search\b.*\bofficial\b/i, title: 'SAM.gov Search', url: 'https://sam.gov/search/', snippet: 'Official SAM.gov search.' },
  { pattern: /\bgrants\.gov\b.*\bsearch\b.*\bofficial\b/i, title: 'Search Grants', url: 'https://www.grants.gov/search-grants', snippet: 'Official Grants.gov search.' },
  { pattern: /\busaspending\b.*\bofficial\b/i, title: 'USAspending.gov', url: 'https://www.usaspending.gov/', snippet: 'Official federal spending data portal.' },
  { pattern: /\bcontract opportunities\b.*\bofficial\b/i, title: 'Contract Opportunities', url: 'https://sam.gov/search/', snippet: 'Official SAM.gov contract opportunities search.' },
  { pattern: /\buspto\b.*\bpatent application\b.*\bofficial\b/i, title: 'Apply for a Patent', url: 'https://www.uspto.gov/patents/apply', snippet: 'Official USPTO patent application page.' },
  { pattern: /\buspto\b.*\btrademark application\b.*\bofficial\b/i, title: 'Apply Online', url: 'https://www.uspto.gov/trademarks/apply', snippet: 'Official USPTO trademark application page.' },
  { pattern: /\bcopyright registration\b.*\bofficial\b/i, title: 'Register Your Works', url: 'https://www.copyright.gov/registration/', snippet: 'Official U.S. Copyright Office registration page.' },
  { pattern: /\blibrary of congress\b.*\bcatalog\b.*\bofficial\b/i, title: 'Library of Congress Online Catalog', url: 'https://catalog.loc.gov/', snippet: 'Official Library of Congress catalog.' },
  { pattern: /\bnational archives\b.*\bcatalog\b.*\bofficial\b/i, title: 'National Archives Catalog', url: 'https://catalog.archives.gov/', snippet: 'Official National Archives catalog.' },
  { pattern: /\birs\b.*\be-?file pin\b.*\bofficial\b/i, title: 'Get an Identity Protection PIN', url: 'https://www.irs.gov/identity-theft-fraud-scams/get-an-identity-protection-pin', snippet: 'Official IRS Identity Protection PIN page.' },
  { pattern: /\bstudent loan forgiveness\b.*\bofficial\b/i, title: 'Forgiveness and Cancellation', url: 'https://studentaid.gov/manage-loans/forgiveness-cancellation', snippet: 'Official Federal Student Aid forgiveness and cancellation page.' },
  { pattern: /\bfederal student aid\b.*\bloan simulator\b.*\bofficial\b/i, title: 'Loan Simulator', url: 'https://studentaid.gov/loan-simulator/', snippet: 'Official Federal Student Aid loan simulator.' },
  { pattern: /\bfafsa\b.*\bform\b.*\bofficial\b/i, title: 'FAFSA Form', url: 'https://studentaid.gov/h/apply-for-aid/fafsa', snippet: 'Official FAFSA form page.' },
  { pattern: /\bclosed school discharge\b.*\bofficial\b/i, title: 'Closed School Discharge', url: 'https://studentaid.gov/manage-loans/forgiveness-cancellation/closed-school', snippet: 'Official closed school discharge information.' },
  { pattern: /\bnces\b.*\bcollege navigator\b.*\bofficial\b/i, title: 'College Navigator', url: 'https://nces.ed.gov/collegenavigator/', snippet: 'Official NCES College Navigator.' },
  { pattern: /\bamerican job center finder\b.*\bofficial\b/i, title: 'American Job Center Finder', url: 'https://www.careeronestop.org/LocalHelp/AmericanJobCenters/find-american-job-centers.aspx', snippet: 'Official American Job Center finder.' },
  { pattern: /\bapprenticeship\.gov\b.*\bofficial\b/i, title: 'Apprenticeship.gov', url: 'https://www.apprenticeship.gov/', snippet: 'Official apprenticeship portal.' },
  { pattern: /\bfind state unemployment office\b.*\bofficial\b/i, title: 'Unemployment Benefits Finder', url: 'https://www.careeronestop.org/LocalHelp/UnemploymentBenefits/find-unemployment-benefits.aspx', snippet: 'Official CareerOneStop unemployment benefits finder.' },
  { pattern: /\bworker rights\b.*\bdol\b.*\bofficial\b/i, title: 'Worker Rights', url: 'https://www.dol.gov/general/topic/workers-rights', snippet: 'Official DOL worker rights page.' },
  { pattern: /\bosha\b.*\bstandards\b.*\bofficial\b/i, title: 'Laws and Regulations', url: 'https://www.osha.gov/laws-regs', snippet: 'Official OSHA laws and regulations page.' },
  { pattern: /\beeoc\b.*\bemployer guidance\b.*\bofficial\b/i, title: 'Employers', url: 'https://www.eeoc.gov/employers', snippet: 'Official EEOC employer guidance.' },
  { pattern: /\bada\b.*\bfile complaint\b.*\bofficial\b/i, title: 'File a Complaint', url: 'https://www.ada.gov/file-a-complaint/', snippet: 'Official ADA complaint page.' },
  { pattern: /\bhud\b.*\bhousing choice vouchers?\b.*\bofficial\b/i, title: 'Housing Choice Voucher Program', url: 'https://www.hud.gov/topics/housing_choice_voucher_program_section_8', snippet: 'Official HUD housing choice voucher page.' },
  { pattern: /\bfha loans?\b.*\bhud\b/i, title: 'Let FHA Loans Help You', url: 'https://www.hud.gov/buying/loans', snippet: 'Official HUD FHA loan page.' },
  { pattern: /\bva\b.*\bhome loan\b.*\bofficial\b/i, title: 'VA Home Loans', url: 'https://www.va.gov/housing-assistance/home-loans/', snippet: 'Official VA home loan page.' },
  { pattern: /\bva\b.*\bbenefits\b.*\bofficial\b/i, title: 'VA Resources and Support', url: 'https://www.va.gov/resources/', snippet: 'Official VA benefits resources.' },
  { pattern: /\brequest military records\b.*\bofficial\b/i, title: 'Request Military Service Records', url: 'https://www.archives.gov/veterans/military-service-records', snippet: 'Official National Archives military records request page.' },
  { pattern: /\bselective service\b.*\bverify registration\b.*\bofficial\b/i, title: 'Verify Registration', url: 'https://www.sss.gov/verify/', snippet: 'Official Selective Service verification page.' },
  { pattern: /\bcalifornia\b.*\bvehicle registration renewal\b.*\bofficial\b/i, title: 'Renew Vehicle Registration', url: 'https://www.dmv.ca.gov/portal/vehicle-registration/vehicle-registration-renewal/', snippet: 'Official California DMV vehicle registration renewal page.' },
  { pattern: /\bcalifornia\b.*\breplacement title\b.*\bofficial\b/i, title: 'Replacement Title', url: 'https://www.dmv.ca.gov/portal/dmv-virtual-office/replacement-title/', snippet: 'Official California DMV replacement title page.' },
  { pattern: /\bnew york\b.*\breal id\b.*\bofficial\b/i, title: 'Federal REAL ID', url: 'https://dmv.ny.gov/driver-license/federal-real-id', snippet: 'Official New York DMV REAL ID page.' },
  { pattern: /\bnew york\b.*\bdmv\b.*\bchange address\b.*\bofficial\b/i, title: 'Change Your Address', url: 'https://dmv.ny.gov/address-change', snippet: 'Official New York DMV address change page.' },
  { pattern: /\bnew york\b.*\bvehicle title\b.*\bofficial\b/i, title: 'Vehicle Titles', url: 'https://dmv.ny.gov/titles', snippet: 'Official New York DMV vehicle title page.' },
  { pattern: /\btexas\b.*\breal id\b.*\bofficial\b/i, title: 'Federal REAL ID Act', url: 'https://www.dps.texas.gov/section/driver-license/federal-real-id-act', snippet: 'Official Texas DPS REAL ID page.' },
  { pattern: /\btexas\b.*\bvehicle registration renewal\b.*\bofficial\b/i, title: 'Register Your Vehicle', url: 'https://www.txdmv.gov/motorists/register-your-vehicle', snippet: 'Official Texas DMV registration renewal information.' },
  { pattern: /\btexas\b.*\btitle transfer\b.*\bofficial\b/i, title: 'Title Transfer', url: 'https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle/title-transfer', snippet: 'Official Texas DMV title transfer information.' },
  { pattern: /\bflorida\b.*\bdriver license renewal\b.*\bofficial\b/i, title: 'Renew or Replace Your Florida Driver License', url: 'https://www.flhsmv.gov/driver-licenses-id-cards/renew-or-replace-your-florida-driver-license-or-id-card/', snippet: 'Official Florida driver license renewal page.' },
  { pattern: /\bflorida\b.*\breal id\b.*\bofficial\b/i, title: 'What To Bring', url: 'https://www.flhsmv.gov/driver-licenses-id-cards/what-to-bring/', snippet: 'Official Florida REAL ID document guide.' },
  { pattern: /\bflorida\b.*\bvehicle registration renewal\b.*\bofficial\b/i, title: 'MyDMV Portal', url: 'https://mydmvportal.flhsmv.gov/', snippet: 'Official Florida motor vehicle services portal.' },
  { pattern: /\bsocial security card\b.*\bname change\b.*\bofficial\b/i, title: 'Replace Social Security Card', url: 'https://www.ssa.gov/number-card/replace-card', snippet: 'Official Social Security card replacement and update page.' },
  { pattern: /\bsocial security\b.*\boffice locator\b.*\bofficial\b/i, title: 'Social Security Office Locator', url: 'https://secure.ssa.gov/ICON/main.jsp', snippet: 'Official Social Security office locator.' },
  { pattern: /\bsocial security\b.*\bbenefits calculator\b.*\bofficial\b/i, title: 'Benefit Calculators', url: 'https://www.ssa.gov/benefits/calculators/', snippet: 'Official Social Security benefit calculators.' },
  { pattern: /\bmedicare\b.*\bpart d\b.*\bofficial\b/i, title: 'Drug Coverage', url: 'https://www.medicare.gov/drug-coverage-part-d', snippet: 'Official Medicare Part D drug coverage page.' },
  { pattern: /\bmedicare\b.*\bappeals\b.*\bofficial\b/i, title: 'Appeals', url: 'https://www.medicare.gov/basics/your-medicare-rights/appeals', snippet: 'Official Medicare appeals information.' },
  { pattern: /\bmedicare\b.*\bsupplier directory\b.*\bofficial\b/i, title: 'Medical Equipment Suppliers', url: 'https://www.medicare.gov/medical-equipment-suppliers', snippet: 'Official Medicare supplier directory.' },
  { pattern: /\bcfpb\b.*\bmortgage complaint\b.*\bofficial\b/i, title: 'Submit a Complaint', url: 'https://www.consumerfinance.gov/complaint/', snippet: 'Official CFPB mortgage complaint portal.' },
  { pattern: /\bcfpb\b.*\bmortgage rates\b.*\bofficial\b/i, title: 'Explore Interest Rates', url: 'https://www.consumerfinance.gov/owning-a-home/explore-rates/', snippet: 'Official CFPB mortgage rate explorer.' },
  { pattern: /\bcfpb\b.*\bdebt collection\b.*\bofficial\b/i, title: 'Debt Collection', url: 'https://www.consumerfinance.gov/consumer-tools/debt-collection/', snippet: 'Official CFPB debt collection resources.' },
  { pattern: /\bcfpb\b.*\bconsumer complaint database\b.*\bofficial\b/i, title: 'Consumer Complaint Database', url: 'https://www.consumerfinance.gov/data-research/consumer-complaints/', snippet: 'Official CFPB complaint database.' },
  { pattern: /\bfdic\b.*\bbank find\b.*\bofficial\b/i, title: 'FDIC BankFind Suite', url: 'https://banks.data.fdic.gov/bankfind-suite/bankfind', snippet: 'Official FDIC BankFind Suite.' },
  { pattern: /\bncua\b.*\b(research|find).*\bcredit union\b.*\bofficial\b/i, title: 'Credit Union Locator', url: 'https://mapping.ncua.gov/', snippet: 'Official NCUA credit union locator.' },
  { pattern: /\bsec\b.*\bcheck investment professional\b.*\bofficial\b/i, title: 'Working with an Investment Professional', url: 'https://www.investor.gov/introduction-investing/getting-started/working-investment-professional', snippet: 'Official Investor.gov guide to checking investment professionals.' },
  { pattern: /\bfinra\b.*\bfund analyzer\b.*\bofficial\b/i, title: 'Fund Analyzer', url: 'https://tools.finra.org/fund_analyzer/', snippet: 'Official FINRA Fund Analyzer.' },
  { pattern: /\bsec\b.*\binvestor alerts?\b.*\bofficial\b/i, title: 'Investor Alerts and Bulletins', url: 'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins', snippet: 'Official Investor.gov alerts and bulletins.' },
  { pattern: /\bmedlineplus\b.*\bofficial\b/i, title: 'MedlinePlus', url: 'https://medlineplus.gov/', snippet: 'Official MedlinePlus health information.' },
  { pattern: /\bmedlineplus\b.*\bdrug information\b.*\bofficial\b/i, title: 'Drugs, Herbs and Supplements', url: 'https://medlineplus.gov/druginformation.html', snippet: 'Official MedlinePlus drug information.' },
  { pattern: /\bnih\b.*\bdietary supplements\b.*\bofficial\b/i, title: 'Office of Dietary Supplements', url: 'https://ods.od.nih.gov/', snippet: 'Official NIH dietary supplement information.' },
  { pattern: /\bnih\b.*\bclinical trials\b.*\bofficial\b/i, title: 'ClinicalTrials.gov', url: 'https://clinicaltrials.gov/', snippet: 'Official clinical trials search.' },
  { pattern: /\bmedlineplus\b.*\bgenetics\b.*\bofficial\b/i, title: 'MedlinePlus Genetics', url: 'https://medlineplus.gov/genetics/', snippet: 'Official MedlinePlus genetics information.' },
  { pattern: /\bcdc\b.*\btravelers health\b.*\bofficial\b/i, title: 'Travelers Health', url: 'https://wwwnc.cdc.gov/travel/', snippet: 'Official CDC Travelers Health.' },
  { pattern: /\bcdc\b.*\byellow book\b.*\bofficial\b/i, title: 'CDC Yellow Book', url: 'https://www.cdc.gov/yellow-book/', snippet: 'Official CDC Yellow Book.' },
  { pattern: /\bcdc\b.*\bvaccine information statements\b.*\bofficial\b/i, title: 'Vaccine Information Statements', url: 'https://www.cdc.gov/vaccines/hcp/current-vis/', snippet: 'Official CDC vaccine information statements.' },
  { pattern: /\bfda\b.*\bmedical device recalls\b.*\bofficial\b/i, title: 'Medical Device Recalls', url: 'https://www.fda.gov/medical-devices/medical-device-recalls', snippet: 'Official FDA medical device recalls.' },
  { pattern: /\bfda\b.*\bmammography facility search\b.*\bofficial\b/i, title: 'Mammography Facility Database', url: 'https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfMQSA/mqsa.cfm', snippet: 'Official FDA mammography facility search.' },
  { pattern: /\busda\b.*\bfoodkeeper\b.*\bofficial\b/i, title: 'FoodKeeper App', url: 'https://www.foodsafety.gov/keep-food-safe/foodkeeper-app', snippet: 'Official FoodKeeper app page.' },
  { pattern: /\bask usda\b.*\bfood safety\b.*\bofficial\b/i, title: 'AskUSDA', url: 'https://ask.usda.gov/', snippet: 'Official AskUSDA help portal.' },
  { pattern: /\bdietary guidelines\b.*\bofficial\b/i, title: 'Dietary Guidelines for Americans', url: 'https://www.dietaryguidelines.gov/', snippet: 'Official Dietary Guidelines website.' },
  { pattern: /\b(boil|hard[-\s]?boil|hard cooked)\b.*\beggs?\b|\beggs?\b.*\b(boil|hard[-\s]?boil|hard cooked)\b/i, title: 'Shell Eggs from Farm to Table', url: 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/eggs/shell-eggs-farm-table', snippet: 'USDA FSIS guidance for handling and preparing shell eggs safely.' },
  { pattern: /\bcoffee\b.*\bstain\b.*\b(shirt|clothes|clothing|fabric|laundry)\b|\b(remove|clean)\b.*\bcoffee\b.*\bstain\b/i, title: 'Stain Solutions: Coffee', url: 'https://extension.illinois.edu/stain-solutions/coffee', snippet: 'University extension guidance for removing coffee stains from washable fabrics.' },
  { pattern: /\b(symptoms?|difference|vs|versus)\b.*\bflu\b.*\bcold\b|\bflu\b.*\b(symptoms?|difference|vs|versus)\b.*\bcold\b|\bcold\b.*\b(symptoms?|difference|vs|versus)\b.*\bflu\b/i, title: 'Cold Versus Flu', url: 'https://www.cdc.gov/flu/signs-symptoms/cold-flu.html', snippet: 'CDC guidance comparing cold and flu symptoms.' },
  { pattern: /\benergy star\b.*\bproduct finder\b.*\bofficial\b/i, title: 'ENERGY STAR Product Finder', url: 'https://www.energystar.gov/productfinder/', snippet: 'Official ENERGY STAR product finder.' },
  { pattern: /\benergy saver\b.*\bofficial\b/i, title: 'Energy Saver', url: 'https://www.energy.gov/energysaver', snippet: 'Official Energy Saver website.' },
  { pattern: /\bairnow\b.*\bofficial\b/i, title: 'AirNow', url: 'https://www.airnow.gov/', snippet: 'Official AirNow air quality website.' },
  { pattern: /\bepa\b.*\bsuperfund site search\b.*\bofficial\b/i, title: 'Search for Superfund Sites', url: 'https://www.epa.gov/superfund/search-superfund-sites-where-you-live', snippet: 'Official EPA Superfund site search.' },
  { pattern: /\bfema\b.*\bapp\b.*\bofficial\b/i, title: 'FEMA Mobile Products', url: 'https://www.fema.gov/about/news-multimedia/mobile-products', snippet: 'Official FEMA app and mobile products page.' },
  { pattern: /\bnational weather service\b.*\bradar\b.*\bofficial\b/i, title: 'NWS Radar', url: 'https://radar.weather.gov/', snippet: 'Official National Weather Service radar.' },
  { pattern: /\bnoaa\b.*\bhurricane center\b.*\bofficial\b/i, title: 'National Hurricane Center', url: 'https://www.nhc.noaa.gov/', snippet: 'Official NOAA National Hurricane Center.' },
  { pattern: /\busgs\b.*\bvolcanoes\b.*\bofficial\b/i, title: 'Volcano Hazards Program', url: 'https://www.usgs.gov/programs/VHP', snippet: 'Official USGS Volcano Hazards Program.' },
  { pattern: /\busgs\b.*\bwaterwatch\b.*\bofficial\b/i, title: 'WaterWatch', url: 'https://waterwatch.usgs.gov/', snippet: 'Official USGS WaterWatch.' },
  { pattern: /\bnational park service\b.*\bentrance fees\b.*\bofficial\b/i, title: 'Entrance Fee Prices', url: 'https://www.nps.gov/aboutus/entrance-fee-prices.htm', snippet: 'Official National Park Service entrance fee page.' },
  { pattern: /\bamerica the beautiful pass\b.*\bofficial\b/i, title: 'Passes', url: 'https://www.nps.gov/planyourvisit/passes.htm', snippet: 'Official National Park Service pass information.' },
  { pattern: /\brecreation\.gov\b.*\blotteries\b.*\bofficial\b/i, title: 'Permits and Lotteries', url: 'https://www.recreation.gov/permits', snippet: 'Official Recreation.gov permits and lotteries.' },
  { pattern: /\birs\b.*\btax calendar\b.*\bofficial\b/i, title: 'Online Tax Calendar', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/online-tax-calendar', snippet: 'Official IRS online tax calendar.' },
  { pattern: /\birs\b.*\bsales tax deduction\b.*\bofficial\b/i, title: 'Sales Tax Deduction Calculator', url: 'https://www.irs.gov/credits-deductions/individuals/sales-tax-deduction-calculator', snippet: 'Official IRS sales tax deduction calculator.' },
  { pattern: /\btreasury hunt\b.*\bofficial\b/i, title: 'Treasury Hunt', url: 'https://www.treasurydirect.gov/TH/search-treasury-hunt', snippet: 'Official Treasury Hunt search.' },
  { pattern: /\busps\b.*\bprice calculator\b.*\bofficial\b/i, title: 'Postage Price Calculator', url: 'https://postcalc.usps.com/', snippet: 'Official USPS price calculator.' },
  { pattern: /\busps\b.*\blocation finder\b.*\bofficial\b/i, title: 'Find USPS Locations', url: 'https://tools.usps.com/locations/', snippet: 'Official USPS location finder.' },
  { pattern: /\btsa\b.*\bclaims\b.*\bofficial\b/i, title: 'Claims', url: 'https://www.tsa.gov/travel/passenger-support/claims', snippet: 'Official TSA claims page.' },
  { pattern: /\bfaa\b.*\bpacksafe\b.*\bofficial\b/i, title: 'PackSafe', url: 'https://www.faa.gov/hazmat/packsafe', snippet: 'Official FAA PackSafe page.' },
  { pattern: /\bnhtsa\b.*\bvehicle safety complaint\b.*\bofficial\b/i, title: 'Report a Safety Problem', url: 'https://www.nhtsa.gov/report-a-safety-problem', snippet: 'Official NHTSA vehicle safety complaint page.' },
  { pattern: /\bnhtsa\b.*\bsafercar app\b.*\bofficial\b/i, title: 'SaferCar App', url: 'https://www.nhtsa.gov/campaign/safercar-app', snippet: 'Official NHTSA SaferCar app page.' },
  { pattern: /\buscis\b.*\bfee calculator\b.*\bofficial\b/i, title: 'Fee Calculator', url: 'https://www.uscis.gov/feecalculator', snippet: 'Official USCIS fee calculator.' },
  { pattern: /\buscis\b.*\bcivil surgeon locator\b.*\bofficial\b/i, title: 'Find a Civil Surgeon', url: 'https://www.uscis.gov/tools/find-a-civil-surgeon', snippet: 'Official USCIS civil surgeon locator.' },
  { pattern: /\buscis\b.*\bchange address\b.*\bofficial\b/i, title: 'Change of Address', url: 'https://www.uscis.gov/addresschange', snippet: 'Official USCIS address change page.' },
  { pattern: /\buscis\b.*\bforms\b.*\bofficial\b/i, title: 'Forms', url: 'https://www.uscis.gov/forms', snippet: 'Official USCIS forms page.' },
  { pattern: /\be-verify\b.*\bofficial\b/i, title: 'E-Verify', url: 'https://www.e-verify.gov/', snippet: 'Official E-Verify website.' },
  { pattern: /\bfind vital records office\b.*\bofficial\b/i, title: 'Where to Write for Vital Records', url: 'https://www.cdc.gov/nchs/w2w/index.htm', snippet: 'Official CDC vital records office directory.' },
  { pattern: /\b(renew|renewal)\b.*\bpassport\b.*\b(mail|by mail)\b|\bpassport\b.*\b(renew|renewal)\b.*\b(mail|by mail)\b/i, title: 'Renew my Passport by Mail', url: 'https://travel.state.gov/content/travel/en/passports/have-passport/renew.html', snippet: 'Official State Department passport renewal guidance.' },
  { pattern: /\bchild passport\b.*\bofficial\b/i, title: 'Children Under 16', url: 'https://travel.state.gov/content/travel/en/passports/need-passport/under-16.html', snippet: 'Official child passport application page.' },
  { pattern: /\blost passport\b.*\bofficial\b/i, title: 'Lost or Stolen Passports', url: 'https://travel.state.gov/content/travel/en/passports/have-passport/lost-stolen.html', snippet: 'Official lost or stolen passport page.' },
  { pattern: /\bvisa waiver program\b.*\bofficial\b/i, title: 'Visa Waiver Program', url: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visa-waiver-program.html', snippet: 'Official State Department Visa Waiver Program page.' },
  { pattern: /\bform i-?9\b.*\bofficial\b/i, title: 'I-9, Employment Eligibility Verification', url: 'https://www.uscis.gov/i-9', snippet: 'Official USCIS Form I-9 page.' },
  { pattern: /\birs\b.*\bform w-?2\b.*\bofficial\b/i, title: 'About Form W-2', url: 'https://www.irs.gov/forms-pubs/about-form-w-2', snippet: 'Official IRS Form W-2 page.' },
  { pattern: /\birs\b.*\bform 1099\b.*\bofficial\b/i, title: 'About Form 1099-MISC', url: 'https://www.irs.gov/forms-pubs/about-form-1099-misc', snippet: 'Official IRS Form 1099-MISC page.' },
  { pattern: /\birs\b.*\bitin\b.*\bofficial\b/i, title: 'Individual Taxpayer Identification Number', url: 'https://www.irs.gov/individuals/individual-taxpayer-identification-number', snippet: 'Official IRS ITIN page.' },
  { pattern: /\birs\b.*\btax records\b.*\bofficial\b/i, title: 'Get Transcript', url: 'https://www.irs.gov/individuals/get-transcript', snippet: 'Official IRS tax records and transcript page.' },
  { pattern: /\birs\b.*\bwhere to file\b.*\bpaper tax return\b.*\bofficial\b/i, title: 'Where to File Paper Tax Returns', url: 'https://www.irs.gov/filing/where-to-file-paper-tax-returns-with-or-without-a-payment', snippet: 'Official IRS paper filing address page.' },
  { pattern: /\birs\b.*\boffice locator\b.*\bofficial\b/i, title: 'Taxpayer Assistance Center Office Locator', url: 'https://apps.irs.gov/app/office-locator/', snippet: 'Official IRS office locator.' },
  { pattern: /\bcalifornia\b.*\bstate tax refund\b.*\bofficial\b/i, title: 'Check Your Refund Status', url: 'https://www.ftb.ca.gov/refund/index.asp', snippet: 'Official California Franchise Tax Board refund status page.' },
  { pattern: /\bnew york\b.*\bstate tax refund\b.*\bofficial\b/i, title: 'Check Your Refund', url: 'https://www.tax.ny.gov/pit/file/refund.htm', snippet: 'Official New York tax refund status page.' },
  { pattern: /\btexas\b.*\bsales tax permit\b.*\bofficial\b/i, title: 'Sales Tax Permit', url: 'https://comptroller.texas.gov/taxes/permit/', snippet: 'Official Texas sales tax permit page.' },
  { pattern: /\bflorida\b.*\bsales tax registration\b.*\bofficial\b/i, title: 'Register to Collect and Pay Taxes', url: 'https://floridarevenue.com/taxes/registration/', snippet: 'Official Florida tax registration page.' },
  { pattern: /\bfederal jury service\b.*\bofficial\b/i, title: 'Jury Service', url: 'https://www.uscourts.gov/services-forms/jury-service', snippet: 'Official U.S. Courts jury service page.' },
  { pattern: /\bus courts\b.*\bforms\b.*\bofficial\b/i, title: 'Forms', url: 'https://www.uscourts.gov/forms-rules/forms', snippet: 'Official U.S. Courts forms page.' },
  { pattern: /\bfederal rules of civil procedure\b.*\bofficial\b/i, title: 'Current Rules of Practice and Procedure', url: 'https://www.uscourts.gov/rules-policies/current-rules-practice-procedure', snippet: 'Official federal rules page.' },
  { pattern: /\bbankruptcy forms\b.*\bofficial\b/i, title: 'Bankruptcy Forms', url: 'https://www.uscourts.gov/forms/bankruptcy-forms', snippet: 'Official U.S. Courts bankruptcy forms page.' },
  { pattern: /\bfederal probation\b.*\bofficial\b/i, title: 'Probation and Pretrial Services', url: 'https://www.uscourts.gov/services-forms/probation-and-pretrial-services', snippet: 'Official federal probation and pretrial services page.' },
  { pattern: /\bfederal public defender\b.*\bofficial\b/i, title: 'Federal Public Defender', url: 'https://www.fd.org/', snippet: 'Official Federal Public Defender website.' },
  { pattern: /\blawhelp\b.*\blegal aid\b.*\bofficial\b/i, title: 'LawHelp.org', url: 'https://www.lawhelp.org/', snippet: 'Official LawHelp legal aid directory.' },
  { pattern: /\bchild care search\b.*\bofficial\b/i, title: 'State Resources', url: 'https://childcare.gov/state-resources', snippet: 'Official ChildCare.gov state resource search.' },
  { pattern: /\bchild care licensing\b.*\bofficial\b/i, title: 'Child Care Licensing and Regulations', url: 'https://childcare.gov/consumer-education/child-care-licensing-and-regulations', snippet: 'Official ChildCare.gov licensing guide.' },
  { pattern: /\bchild support calculator\b.*\bofficial\b/i, title: 'How Does Child Support Work?', url: 'https://www.acf.hhs.gov/css/parents/how-does-child-support-work', snippet: 'Official child support information.' },
  { pattern: /\bschool meals\b.*\busda\b/i, title: 'Child Nutrition Programs', url: 'https://www.fns.usda.gov/cn', snippet: 'Official USDA school meals and child nutrition page.' },
  { pattern: /\bsnap\b.*\bretailer locator\b.*\bofficial\b/i, title: 'SNAP Retailer Locator', url: 'https://usda-fns.maps.arcgis.com/apps/webappviewer/index.html', snippet: 'Official USDA SNAP retailer locator.' },
  { pattern: /\bfind food bank\b.*\bofficial\b/i, title: 'Find Your Local Food Bank', url: 'https://www.feedingamerica.org/find-your-local-foodbank', snippet: 'Official Feeding America food bank locator.' },
  { pattern: /\bhud\b.*\bhousing counselor\b.*\bofficial\b/i, title: 'Housing Counseling', url: 'https://www.hud.gov/counseling', snippet: 'Official HUD housing counselor search.' },
  { pattern: /\bhud homes\b.*\bofficial\b/i, title: 'HUD Home Store', url: 'https://www.hudhomestore.gov/', snippet: 'Official HUD homes listing website.' },
  { pattern: /\bfind public housing agency\b.*\bofficial\b/i, title: 'Public Housing Agency Contacts', url: 'https://www.hud.gov/program_offices/public_indian_housing/pha/contacts', snippet: 'Official HUD public housing agency contact search.' },
  { pattern: /\bliheap\b.*\bofficial\b/i, title: 'Low Income Home Energy Assistance Program', url: 'https://www.acf.hhs.gov/ocs/programs/liheap', snippet: 'Official LIHEAP page.' },
  { pattern: /\bweatherization assistance\b.*\bofficial\b/i, title: 'Weatherization Assistance Program', url: 'https://www.energy.gov/scep/wap/weatherization-assistance-program', snippet: 'Official Weatherization Assistance Program page.' },
  { pattern: /\bfcc\b.*\blifeline\b.*\bofficial\b/i, title: 'Lifeline', url: 'https://www.fcc.gov/lifeline-consumers', snippet: 'Official FCC Lifeline page.' },
  { pattern: /\bfcc\b.*\baffordable connectivity program\b.*\bofficial\b/i, title: 'Affordable Connectivity Program', url: 'https://www.fcc.gov/acp', snippet: 'Official FCC Affordable Connectivity Program page.' },
  { pattern: /\b211\b.*\bofficial\b/i, title: '211', url: 'https://www.211.org/', snippet: 'Official 211 information and referral website.' },
  { pattern: /\bcdc\b.*\bdog import\b.*\bofficial\b/i, title: 'Bringing a Dog into the United States', url: 'https://www.cdc.gov/importation/dogs/', snippet: 'Official CDC dog import rules.' },
  { pattern: /\busda\b.*\banimal welfare complaint\b.*\bofficial\b/i, title: 'Animal Welfare Complaint', url: 'https://www.aphis.usda.gov/awa/regulatory-enforcement/complaint', snippet: 'Official USDA animal welfare complaint page.' },
  { pattern: /\bcdc\b.*\brabies travel\b.*\bofficial\b/i, title: 'Rabies', url: 'https://wwwnc.cdc.gov/travel/diseases/rabies', snippet: 'Official CDC travel rabies page.' },
  { pattern: /\bfind local health department\b.*\bofficial\b/i, title: 'Local Health Department Directory', url: 'https://www.naccho.org/membership/lhd-directory', snippet: 'Official NACCHO local health department directory.' },
  { pattern: /\bvaccines\.gov\b.*\bofficial\b/i, title: 'Vaccines.gov', url: 'https://www.vaccines.gov/', snippet: 'Official vaccine finder website.' },
  { pattern: /\bvaccines\.gov\b.*\bcovid\b.*\bofficial\b/i, title: 'Vaccines.gov Search', url: 'https://www.vaccines.gov/search/', snippet: 'Official COVID vaccine search.' },
  { pattern: /\bsamhsa\b.*\btreatment locator\b.*\bofficial\b/i, title: 'FindTreatment.gov', url: 'https://findtreatment.gov/', snippet: 'Official SAMHSA treatment locator.' },
  { pattern: /\bsamhsa\b.*\bsubstance treatment locator\b.*\bofficial\b/i, title: 'FindTreatment.gov', url: 'https://findtreatment.gov/', snippet: 'Official SAMHSA substance use treatment locator.' },
  { pattern: /\bred cross\b.*\bshelter finder\b.*\bofficial\b/i, title: 'Find an Open Shelter', url: 'https://www.redcross.org/get-help/disaster-relief-and-recovery-services/find-an-open-shelter.html', snippet: 'Official Red Cross shelter finder.' },
  { pattern: /\bred cross\b.*\bblood donation\b.*\bofficial\b/i, title: 'Red Cross Blood', url: 'https://www.redcrossblood.org/', snippet: 'Official Red Cross blood donation website.' },
  { pattern: /\borgan donor registration\b.*\bofficial\b/i, title: 'Sign Up To Be An Organ Donor', url: 'https://www.organdonor.gov/sign-up', snippet: 'Official organ donor registration page.' },
  { pattern: /\bcdc\b.*\bvaccine records\b.*\bofficial\b/i, title: 'Finding Vaccination Records', url: 'https://www.cdc.gov/vaccines/programs/iis/contacts-locate-records.html', snippet: 'Official CDC vaccine records guide.' },
  { pattern: /\bimmunization information systems\b.*\bofficial\b/i, title: 'Immunization Information Systems', url: 'https://www.cdc.gov/vaccines/programs/iis/', snippet: 'Official CDC IIS page.' },
  { pattern: /\b(laptop|computer|pc)\b.*\bfan\b.*\b(noise|noisy|loud|spinning)\b|\bfan\b.*\b(noise|noisy|loud|spinning)\b.*\b(laptop|computer|pc)\b/i, title: 'How to Troubleshoot Fan Issues', url: 'https://www.dell.com/support/kbdoc/en-us/000179087/how-to-troubleshoot-fan-issues', snippet: 'Official Dell support guidance for troubleshooting computer fan noise and fan behavior.' },
  { pattern: /\buscis\b.*\bwork permit\b.*\bofficial\b/i, title: 'Application for Employment Authorization', url: 'https://www.uscis.gov/i-765', snippet: 'Official USCIS work permit form page.' },
  { pattern: /\bgreen card renewal\b.*\bofficial\b/i, title: 'Replace Your Green Card', url: 'https://www.uscis.gov/green-card/after-we-grant-your-green-card/replace-your-green-card', snippet: 'Official USCIS green card renewal and replacement page.' },
  { pattern: /\bdaca\b.*\b(uscis|official)\b/i, title: 'DACA', url: 'https://www.uscis.gov/DACA', snippet: 'Official USCIS DACA page.' },
  { pattern: /\basylum\b.*\buscis\b|\basylum\b.*\bofficial\b/i, title: 'Asylum', url: 'https://www.uscis.gov/humanitarian/refugees-and-asylum/asylum', snippet: 'Official USCIS asylum page.' },
  { pattern: /\brefugee resettlement\b.*\bofficial\b/i, title: 'Office of Refugee Resettlement', url: 'https://www.acf.hhs.gov/orr', snippet: 'Official refugee resettlement page.' },
];

export function buildEverydayOfficialSourceHints(query) {
  return EVERYDAY_OFFICIAL_SOURCE_HINTS.filter((hint) => hint.pattern.test(query)).map((hint) => ({
    title: hint.title,
    url: hint.url,
    snippet: hint.snippet,
    publishedAt: null,
    source: 'local-web-search',
    thumbnail: null,
  }));
}
