const EXPANDED_OFFICIAL_SOURCE_HINTS = [
  { pattern: /\btypescript\b.*\b(handbook|docs?|documentation|official)\b/i, title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs/handbook/intro.html', snippet: 'Official TypeScript handbook.' },
  { pattern: /\bgithub cli\b.*\b(download|install|official)\b/i, title: 'GitHub CLI', url: 'https://cli.github.com/', snippet: 'Official GitHub CLI website and installation page.' },
  { pattern: /\bpowershell\b.*\b(install|docs?|documentation|official)\b/i, title: 'Install PowerShell', url: 'https://learn.microsoft.com/powershell/scripting/install/installing-powershell', snippet: 'Official PowerShell installation documentation.' },
  { pattern: /\bwindows 11\b.*\b(download|official)\b/i, title: 'Download Windows 11', url: 'https://www.microsoft.com/software-download/windows11', snippet: 'Official Windows 11 download page.' },
  { pattern: /\bubuntu\b.*\bserver\b.*\b(download|official)\b/i, title: 'Download Ubuntu Server', url: 'https://ubuntu.com/download/server', snippet: 'Official Ubuntu Server download page.' },
  { pattern: /\bdebian\b.*\b(download|official)\b/i, title: 'Download Debian', url: 'https://www.debian.org/distrib/', snippet: 'Official Debian download page.' },
  { pattern: /\balpine linux\b.*\b(download|official)\b/i, title: 'Alpine Linux Downloads', url: 'https://alpinelinux.org/downloads/', snippet: 'Official Alpine Linux downloads page.' },
  { pattern: /\bnixos\b.*\b(download|official)\b/i, title: 'Download NixOS', url: 'https://nixos.org/download/', snippet: 'Official NixOS download page.' },
  { pattern: /\bnix\b.*\b(package manager|install|official)\b/i, title: 'Install Nix', url: 'https://nixos.org/download/', snippet: 'Official Nix installer page.' },
  { pattern: /\bnode\.?js\b.*\bfs\b.*\bapi\b.*\b(docs?|documentation|official)\b/i, title: 'File system - Node.js', url: 'https://nodejs.org/api/fs.html', snippet: 'Official Node.js file system API documentation.' },
  { pattern: /\bbun\b.*\bapi\b.*\b(docs?|documentation|official)\b/i, title: 'Bun APIs', url: 'https://bun.sh/docs/api', snippet: 'Official Bun API documentation.' },
  { pattern: /\bdeno\b.*\bapi\b.*\b(docs?|documentation|official)\b/i, title: 'Deno API Reference', url: 'https://docs.deno.com/api/', snippet: 'Official Deno API reference.' },
  { pattern: /\bgo\b.*\bnet\/http\b.*\b(package|docs?|documentation|official)\b/i, title: 'net/http - Go Packages', url: 'https://pkg.go.dev/net/http', snippet: 'Official Go net/http package documentation.' },
  { pattern: /\brust\b.*\bstd\b.*\b(library|docs?|documentation|official)\b/i, title: 'std - Rust', url: 'https://doc.rust-lang.org/std/', snippet: 'Official Rust standard library documentation.' },
  { pattern: /\bpython\b.*\basyncio\b.*\b(docs?|documentation|official)\b/i, title: 'asyncio - Python', url: 'https://docs.python.org/3/library/asyncio.html', snippet: 'Official Python asyncio documentation.' },
  { pattern: /\bjava\b.*\bstream\b.*\bapi\b.*\b(docs?|documentation|official)\b/i, title: 'Stream - Java SE API', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/stream/Stream.html', snippet: 'Official Java Stream API documentation.' },
  { pattern: /\bspring boot\b.*\b(docs?|documentation|official)\b/i, title: 'Spring Boot Reference Documentation', url: 'https://docs.spring.io/spring-boot/index.html', snippet: 'Official Spring Boot documentation.' },
  { pattern: /\bmaven\b.*\b(download|official)\b/i, title: 'Download Apache Maven', url: 'https://maven.apache.org/download.cgi', snippet: 'Official Apache Maven download page.' },
  { pattern: /\bgradle\b.*\b(install|docs?|documentation|official)\b/i, title: 'Gradle Installation', url: 'https://gradle.org/install/', snippet: 'Official Gradle installation page.' },
  { pattern: /\bapache http server\b.*\b(docs?|documentation|official)\b/i, title: 'Apache HTTP Server Documentation', url: 'https://httpd.apache.org/docs/', snippet: 'Official Apache HTTP Server documentation.' },
  { pattern: /\bapache tomcat\b.*\b(download|official)\b/i, title: 'Apache Tomcat Downloads', url: 'https://tomcat.apache.org/download-11.cgi', snippet: 'Official Apache Tomcat downloads page.' },
  { pattern: /\bpostgresql\b.*\b(download|official)\b/i, title: 'PostgreSQL Downloads', url: 'https://www.postgresql.org/download/', snippet: 'Official PostgreSQL downloads page.' },
  { pattern: /\bsqlite\b.*\bdownload\b.*\bofficial\b|\bsqlite\b.*\bofficial\b.*\bdownload\b/i, title: 'SQLite Download Page', url: 'https://www.sqlite.org/download.html', snippet: 'Official SQLite download page.' },
  { pattern: /\bmariadb\b.*\b(download|official)\b/i, title: 'MariaDB Downloads', url: 'https://mariadb.org/download/', snippet: 'Official MariaDB download page.' },
  { pattern: /\bminio\b.*\b(docs?|documentation|official)\b/i, title: 'MinIO Documentation', url: 'https://min.io/docs/minio/linux/index.html', snippet: 'Official MinIO documentation.' },
  { pattern: /\brabbitmq\b.*\b(docs?|documentation|official)\b/i, title: 'RabbitMQ Documentation', url: 'https://www.rabbitmq.com/docs', snippet: 'Official RabbitMQ documentation.' },
  { pattern: /\bapache kafka\b.*\b(docs?|documentation|official)\b/i, title: 'Apache Kafka Documentation', url: 'https://kafka.apache.org/documentation/', snippet: 'Official Apache Kafka documentation.' },
  { pattern: /\bclickhouse\b.*\b(docs?|documentation|official)\b/i, title: 'ClickHouse Docs', url: 'https://clickhouse.com/docs', snippet: 'Official ClickHouse documentation.' },
  { pattern: /\bduckdb\b.*\b(docs?|documentation|official)\b/i, title: 'DuckDB Documentation', url: 'https://duckdb.org/docs/', snippet: 'Official DuckDB documentation.' },
  { pattern: /\bdrizzle orm\b.*\b(docs?|documentation|official)\b/i, title: 'Drizzle ORM Docs', url: 'https://orm.drizzle.team/docs/overview', snippet: 'Official Drizzle ORM documentation.' },
  { pattern: /\bsequelize\b.*\b(docs?|documentation|official)\b/i, title: 'Sequelize Docs', url: 'https://sequelize.org/docs/v6/', snippet: 'Official Sequelize documentation.' },
  { pattern: /\btypeorm\b.*\b(docs?|documentation|official)\b/i, title: 'TypeORM', url: 'https://typeorm.io/', snippet: 'Official TypeORM documentation.' },
  { pattern: /\bzod\b.*\b(docs?|documentation|official)\b/i, title: 'Zod', url: 'https://zod.dev/', snippet: 'Official Zod documentation.' },
  { pattern: /\btanstack query\b.*\b(docs?|documentation|official)\b/i, title: 'TanStack Query Docs', url: 'https://tanstack.com/query/latest/docs/framework/react/overview', snippet: 'Official TanStack Query documentation.' },
  { pattern: /\bredux\b.*\b(docs?|documentation|official)\b/i, title: 'Redux Documentation', url: 'https://redux.js.org/', snippet: 'Official Redux documentation.' },
  { pattern: /\bzustand\b.*\b(docs?|documentation|official)\b/i, title: 'Zustand Documentation', url: 'https://zustand.docs.pmnd.rs/', snippet: 'Official Zustand documentation.' },
  { pattern: /\bradix ui\b.*\b(docs?|documentation|official)\b/i, title: 'Radix UI', url: 'https://www.radix-ui.com/primitives/docs/overview/introduction', snippet: 'Official Radix UI documentation.' },
  { pattern: /\bshadcn\b.*\bui\b.*\b(docs?|documentation|official)\b/i, title: 'shadcn/ui', url: 'https://ui.shadcn.com/docs', snippet: 'Official shadcn/ui documentation.' },
  { pattern: /\blucide\b.*\b(icons?|official)\b/i, title: 'Lucide Icons', url: 'https://lucide.dev/', snippet: 'Official Lucide icons website.' },
  { pattern: /\bmotion react\b.*\b(docs?|documentation|official)\b/i, title: 'Motion for React', url: 'https://motion.dev/docs/react', snippet: 'Official Motion for React documentation.' },
  { pattern: /\bthree\.?js\b.*\b(docs?|documentation|official)\b/i, title: 'Three.js Documentation', url: 'https://threejs.org/docs/', snippet: 'Official Three.js documentation.' },
  { pattern: /\bmapbox gl js\b.*\b(docs?|documentation|official)\b/i, title: 'Mapbox GL JS Docs', url: 'https://docs.mapbox.com/mapbox-gl-js/', snippet: 'Official Mapbox GL JS documentation.' },
  { pattern: /\bleaflet\b.*\b(docs?|documentation|official)\b/i, title: 'Leaflet Reference', url: 'https://leafletjs.com/reference.html', snippet: 'Official Leaflet API reference.' },
  { pattern: /\bcypress\b.*\b(docs?|documentation|official)\b/i, title: 'Cypress Documentation', url: 'https://docs.cypress.io/', snippet: 'Official Cypress documentation.' },
  { pattern: /\bstorybook\b.*\b(docs?|documentation|official)\b/i, title: 'Storybook Docs', url: 'https://storybook.js.org/docs', snippet: 'Official Storybook documentation.' },
  { pattern: /\bsentry\b.*\bjavascript\b.*\b(docs?|documentation|official)\b/i, title: 'Sentry JavaScript Docs', url: 'https://docs.sentry.io/platforms/javascript/', snippet: 'Official Sentry JavaScript documentation.' },
  { pattern: /\bdatadog\b.*\b(docs?|documentation|official)\b/i, title: 'Datadog Docs', url: 'https://docs.datadoghq.com/', snippet: 'Official Datadog documentation.' },
  { pattern: /\bnew relic\b.*\b(docs?|documentation|official)\b/i, title: 'New Relic Documentation', url: 'https://docs.newrelic.com/', snippet: 'Official New Relic documentation.' },
  { pattern: /\bcloudflare\b.*\br2\b.*\b(docs?|documentation|official)\b/i, title: 'Cloudflare R2 Docs', url: 'https://developers.cloudflare.com/r2/', snippet: 'Official Cloudflare R2 documentation.' },
  { pattern: /\baws\b.*\bs3\b.*\b(docs?|documentation|official)\b/i, title: 'Amazon S3 Documentation', url: 'https://docs.aws.amazon.com/s3/', snippet: 'Official Amazon S3 documentation.' },
  { pattern: /\bgoogle cloud run\b.*\b(docs?|documentation|official)\b/i, title: 'Cloud Run Documentation', url: 'https://cloud.google.com/run/docs', snippet: 'Official Google Cloud Run documentation.' },
  { pattern: /\bazure functions\b.*\b(docs?|documentation|official)\b/i, title: 'Azure Functions Documentation', url: 'https://learn.microsoft.com/azure/azure-functions/', snippet: 'Official Azure Functions documentation.' },
  { pattern: /\bdigitalocean\b.*\b(docs?|documentation|official)\b/i, title: 'DigitalOcean Documentation', url: 'https://docs.digitalocean.com/', snippet: 'Official DigitalOcean documentation.' },
  { pattern: /\bfly\.io\b.*\b(docs?|documentation|official)\b/i, title: 'Fly.io Docs', url: 'https://fly.io/docs/', snippet: 'Official Fly.io documentation.' },
  { pattern: /\brailway\b.*\b(docs?|documentation|official)\b/i, title: 'Railway Docs', url: 'https://docs.railway.com/', snippet: 'Official Railway documentation.' },
  { pattern: /\brender\b.*\b(docs?|documentation|official)\b/i, title: 'Render Docs', url: 'https://render.com/docs', snippet: 'Official Render documentation.' },
  { pattern: /\bopenapi\b.*\b(specification|official)\b/i, title: 'OpenAPI Specification', url: 'https://spec.openapis.org/oas/latest.html', snippet: 'Official OpenAPI Specification.' },
  { pattern: /\boauth\b.*\b2\.0\b.*\brfc\b.*\bofficial\b/i, title: 'RFC 6749', url: 'https://www.rfc-editor.org/rfc/rfc6749', snippet: 'Official OAuth 2.0 RFC.' },
  { pattern: /\bphp\b.*\b(docs?|documentation|official)\b/i, title: 'PHP Documentation', url: 'https://www.php.net/docs.php', snippet: 'Official PHP documentation.' },
  { pattern: /\bcomposer\b.*\b(php|install|download|official)\b/i, title: 'Download Composer', url: 'https://getcomposer.org/download/', snippet: 'Official Composer download page.' },
  { pattern: /\blaravel\b.*\b(docs?|documentation|official)\b/i, title: 'Laravel Documentation', url: 'https://laravel.com/docs', snippet: 'Official Laravel documentation.' },
  { pattern: /\bruby on rails\b.*\b(guides?|docs?|documentation|official)\b/i, title: 'Ruby on Rails Guides', url: 'https://guides.rubyonrails.org/', snippet: 'Official Ruby on Rails guides.' },
  { pattern: /\bruby\b.*\b(programming language|download|official)\b/i, title: 'Ruby Downloads', url: 'https://www.ruby-lang.org/en/downloads/', snippet: 'Official Ruby downloads page.' },
  { pattern: /(^|\s)\.net\b.*\b(download|official)\b/i, title: 'Download .NET', url: 'https://dotnet.microsoft.com/en-us/download', snippet: 'Official .NET download page.' },
  { pattern: /(^|\s)c#\s+.*\b(language|docs?|documentation|official)\b/i, title: 'C# Documentation', url: 'https://learn.microsoft.com/dotnet/csharp/', snippet: 'Official C# documentation.' },
  { pattern: /\bflutter\b.*\b(docs?|documentation|official)\b/i, title: 'Flutter Docs', url: 'https://docs.flutter.dev/', snippet: 'Official Flutter documentation.' },
  { pattern: /\bdart\b.*\b(language|docs?|documentation|official)\b/i, title: 'Dart Language', url: 'https://dart.dev/language', snippet: 'Official Dart language documentation.' },
  { pattern: /\bandroid studio\b.*\b(download|official)\b/i, title: 'Download Android Studio', url: 'https://developer.android.com/studio', snippet: 'Official Android Studio download page.' },
  { pattern: /\bterraform\b.*\b(docs?|documentation|official)\b/i, title: 'Terraform Docs', url: 'https://developer.hashicorp.com/terraform/docs', snippet: 'Official Terraform documentation.' },
  { pattern: /\bansible\b.*\b(docs?|documentation|official)\b/i, title: 'Ansible Documentation', url: 'https://docs.ansible.com/', snippet: 'Official Ansible documentation.' },
  { pattern: /\bhelm\b.*\b(docs?|documentation|official)\b/i, title: 'Helm Docs', url: 'https://helm.sh/docs/', snippet: 'Official Helm documentation.' },
  { pattern: /\bprometheus\b.*\b(docs?|documentation|official)\b/i, title: 'Prometheus Docs', url: 'https://prometheus.io/docs/', snippet: 'Official Prometheus documentation.' },
  { pattern: /\bgrafana\b.*\b(docs?|documentation|official)\b/i, title: 'Grafana Documentation', url: 'https://grafana.com/docs/', snippet: 'Official Grafana documentation.' },
  { pattern: /\belasticsearch\b.*\b(docs?|documentation|official)\b/i, title: 'Elasticsearch Docs', url: 'https://www.elastic.co/docs', snippet: 'Official Elastic documentation.' },
  { pattern: /\bmongodb\b.*\b(docs?|documentation|official)\b/i, title: 'MongoDB Docs', url: 'https://www.mongodb.com/docs/', snippet: 'Official MongoDB documentation.' },
  { pattern: /\bopencv\b.*\b(docs?|documentation|official)\b/i, title: 'OpenCV Documentation', url: 'https://docs.opencv.org/', snippet: 'Official OpenCV documentation.' },
  { pattern: /\btensorflow\b.*\b(install|installation|official)\b/i, title: 'Install TensorFlow', url: 'https://www.tensorflow.org/install', snippet: 'Official TensorFlow installation documentation.' },
  { pattern: /\bhugging face\b.*\btransformers\b.*\b(docs?|documentation|official)\b/i, title: 'Transformers Documentation', url: 'https://huggingface.co/docs/transformers', snippet: 'Official Hugging Face Transformers documentation.' },
  { pattern: /\blangchain\b.*\b(docs?|documentation|official)\b/i, title: 'LangChain Docs', url: 'https://docs.langchain.com/', snippet: 'Official LangChain documentation.' },
  { pattern: /\bllamaindex\b.*\b(docs?|documentation|official)\b/i, title: 'LlamaIndex Docs', url: 'https://docs.llamaindex.ai/', snippet: 'Official LlamaIndex documentation.' },
  { pattern: /\banthropic\b.*\b(api|docs?|documentation|official)\b/i, title: 'Anthropic Docs', url: 'https://docs.anthropic.com/', snippet: 'Official Anthropic API documentation.' },
  { pattern: /\bollama\b.*\b(api|docs?|documentation|official)\b/i, title: 'Ollama API', url: 'https://github.com/ollama/ollama/blob/main/docs/api.md', snippet: 'Official Ollama API documentation.' },
  { pattern: /\b7[- ]?zip\b.*\b(download|official)\b/i, title: 'Download 7-Zip', url: 'https://www.7-zip.org/download.html', snippet: 'Official 7-Zip download page.' },
  { pattern: /\bbalena\s?etcher\b.*\b(download|official)\b/i, title: 'balenaEtcher', url: 'https://etcher.balena.io/', snippet: 'Official balenaEtcher download page.' },
  { pattern: /\bvirtualbox\b.*\b(download|official)\b/i, title: 'VirtualBox Downloads', url: 'https://www.virtualbox.org/wiki/Downloads', snippet: 'Official VirtualBox downloads page.' },
  { pattern: /\bwireguard\b.*\b(install|download|official)\b/i, title: 'WireGuard Installation', url: 'https://www.wireguard.com/install/', snippet: 'Official WireGuard installation page.' },
  { pattern: /\bwireshark\b.*\b(download|official)\b/i, title: 'Download Wireshark', url: 'https://www.wireshark.org/download.html', snippet: 'Official Wireshark download page.' },
  { pattern: /\bfilezilla\b.*\b(download|official)\b/i, title: 'Download FileZilla Client', url: 'https://filezilla-project.org/download.php', snippet: 'Official FileZilla download page.' },
  { pattern: /\blibreoffice\b.*\b(download|official)\b/i, title: 'Download LibreOffice', url: 'https://www.libreoffice.org/download/download-libreoffice/', snippet: 'Official LibreOffice download page.' },
  { pattern: /\baudacity\b.*\b(download|official)\b/i, title: 'Download Audacity', url: 'https://www.audacityteam.org/download/', snippet: 'Official Audacity download page.' },
  { pattern: /\bhandbrake\b.*\b(download|official)\b/i, title: 'Download HandBrake', url: 'https://handbrake.fr/downloads.php', snippet: 'Official HandBrake download page.' },
  { pattern: /\bobsidian\b.*\bsync\b.*\bofficial\b/i, title: 'Obsidian Sync', url: 'https://obsidian.md/sync', snippet: 'Official Obsidian Sync page.' },
  { pattern: /\bowasp\b.*\btop 10\b.*\bofficial\b/i, title: 'OWASP Top Ten', url: 'https://owasp.org/www-project-top-ten/', snippet: 'Official OWASP Top Ten project.' },
  { pattern: /\blet.?s encrypt\b.*\b(docs?|documentation|official)\b/i, title: 'Let\'s Encrypt Documentation', url: 'https://letsencrypt.org/docs/', snippet: 'Official Let\'s Encrypt documentation.' },
  { pattern: /\bmozilla\b.*\bca\b.*\b(certificate|program|official)\b/i, title: 'Mozilla CA Certificate Program', url: 'https://wiki.mozilla.org/CA', snippet: 'Official Mozilla CA Certificate Program page.' },
  { pattern: /\birs\b.*\bw-?4\b.*\b(form|official)\b/i, title: 'About Form W-4', url: 'https://www.irs.gov/forms-pubs/about-form-w-4', snippet: 'Official IRS Form W-4 page.' },
  { pattern: /\busa\.gov\b.*\b(benefits|official)\b/i, title: 'Government Benefits', url: 'https://www.usa.gov/benefits', snippet: 'Official USA.gov benefits page.' },
  { pattern: /\bnih\b.*\bpubmed\b.*\bofficial\b/i, title: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/', snippet: 'Official PubMed search page.' },
  { pattern: /\bfda\b.*\b(drugs?|database|official)\b/i, title: 'Drugs@FDA', url: 'https://www.accessdata.fda.gov/scripts/cder/daf/', snippet: 'Official FDA drug database.' },
  { pattern: /\bclinicaltrials\.gov\b.*\bofficial\b/i, title: 'ClinicalTrials.gov', url: 'https://clinicaltrials.gov/', snippet: 'Official ClinicalTrials.gov website.' },
  { pattern: /\bus\b.*\bcopyright\b.*\b(registration|official)\b/i, title: 'Register Your Works', url: 'https://www.copyright.gov/registration/', snippet: 'Official U.S. Copyright Office registration page.' },
  { pattern: /\bsec\b.*\bedgar\b.*\b(company search|search|official)\b/i, title: 'SEC Search Filings', url: 'https://www.sec.gov/search-filings', snippet: 'Official SEC filing search.' },
  { pattern: /\bdata\.gov\b.*\bofficial\b/i, title: 'Data.gov', url: 'https://data.gov/', snippet: 'Official U.S. government open data portal.' },
  { pattern: /\binternet archive\b.*\bofficial\b/i, title: 'Internet Archive', url: 'https://archive.org/', snippet: 'Official Internet Archive website.' },
  { pattern: /\bwikipedia\b.*\bofficial\b/i, title: 'Wikipedia', url: 'https://www.wikipedia.org/', snippet: 'Official Wikipedia portal.' },
  { pattern: /\bwikidata\b.*\bofficial\b/i, title: 'Wikidata', url: 'https://www.wikidata.org/', snippet: 'Official Wikidata website.' },
  { pattern: /\bstack overflow\b.*\bofficial\b/i, title: 'Stack Overflow', url: 'https://stackoverflow.com/', snippet: 'Official Stack Overflow website.' },
  { pattern: /\bsteam\b.*\b(download|official)\b/i, title: 'Install Steam', url: 'https://store.steampowered.com/about/', snippet: 'Official Steam download page.' },
  { pattern: /\bepic games\b.*\b(launcher|download|official)\b/i, title: 'Download Epic Games Launcher', url: 'https://store.epicgames.com/download', snippet: 'Official Epic Games Launcher download page.' },
  { pattern: /\bvite\b.*\b(docs?|documentation|official)\b/i, title: 'Vite Guide', url: 'https://vite.dev/guide/', snippet: 'Official Vite documentation.' },
  { pattern: /\breact\b(?!\s+router\b)(?!.*\buseeffect\b).*\b(docs?|documentation|official)\b/i, title: 'React Documentation', url: 'https://react.dev/learn', snippet: 'Official React documentation.' },
  { pattern: /\bvue\b.*\b(guide|docs?|documentation|official)\b/i, title: 'Vue Guide', url: 'https://vuejs.org/guide/introduction.html', snippet: 'Official Vue guide.' },
  { pattern: /\bnext\.?js\b.*\b(docs?|documentation|official)\b/i, title: 'Next.js Docs', url: 'https://nextjs.org/docs', snippet: 'Official Next.js documentation.' },
  { pattern: /\bremix\b.*\b(docs?|documentation|official)\b/i, title: 'Remix Docs', url: 'https://remix.run/docs/en/main', snippet: 'Official Remix documentation.' },
  { pattern: /\btailwind\b.*\b(css\s*)?.*\b(docs?|documentation|official)\b/i, title: 'Tailwind CSS Documentation', url: 'https://tailwindcss.com/docs', snippet: 'Official Tailwind CSS documentation.' },
  { pattern: /\beslint\b.*\b(docs?|documentation|official)\b/i, title: 'ESLint Docs', url: 'https://eslint.org/docs/latest/', snippet: 'Official ESLint documentation.' },
  { pattern: /\bprettier\b.*\b(docs?|documentation|official)\b/i, title: 'Prettier Docs', url: 'https://prettier.io/docs/', snippet: 'Official Prettier documentation.' },
  { pattern: /\bvitest\b.*\b(docs?|documentation|official)\b/i, title: 'Vitest Guide', url: 'https://vitest.dev/guide/', snippet: 'Official Vitest documentation.' },
  { pattern: /\bjest\b.*\b(docs?|documentation|official)\b/i, title: 'Jest', url: 'https://jestjs.io/', snippet: 'Official Jest documentation.' },
  { pattern: /\bjava\b.*\b(jdk|download|official)\b/i, title: 'Java Downloads', url: 'https://www.oracle.com/java/technologies/downloads/', snippet: 'Official Oracle Java downloads page.' },
  { pattern: /\bkotlin\b.*\b(docs?|documentation|official)\b/i, title: 'Kotlin Docs', url: 'https://kotlinlang.org/docs/home.html', snippet: 'Official Kotlin documentation.' },
  { pattern: /\bswift\b.*\b(programming language|docs?|documentation|official)\b/i, title: 'Swift Documentation', url: 'https://www.swift.org/documentation/', snippet: 'Official Swift documentation.' },
  { pattern: /\bdocker\b.*\bcompose\b.*\b(docs?|documentation|official)\b/i, title: 'Docker Compose', url: 'https://docs.docker.com/compose/', snippet: 'Official Docker Compose documentation.' },
  { pattern: /\bkubernetes\b.*\b(docs?|documentation|official)\b/i, title: 'Kubernetes Documentation', url: 'https://kubernetes.io/docs/', snippet: 'Official Kubernetes documentation.' },
  { pattern: /\bmysql\b.*\b(docs?|documentation|official)\b/i, title: 'MySQL Documentation', url: 'https://dev.mysql.com/doc/', snippet: 'Official MySQL documentation.' },
  { pattern: /\bredis\b.*\b(docs?|documentation|official)\b/i, title: 'Redis Docs', url: 'https://redis.io/docs/latest/', snippet: 'Official Redis documentation.' },
  { pattern: /\bnginx\b.*\b(docs?|documentation|official)\b/i, title: 'nginx Documentation', url: 'https://nginx.org/en/docs/', snippet: 'Official nginx documentation.' },
  { pattern: /\bcloudflare\b.*\bpages\b.*\b(docs?|documentation|official)\b/i, title: 'Cloudflare Pages Docs', url: 'https://developers.cloudflare.com/pages/', snippet: 'Official Cloudflare Pages documentation.' },
  { pattern: /\bcloudflare\b.*\b(docs?|documentation|official)\b/i, title: 'Cloudflare Docs', url: 'https://developers.cloudflare.com/', snippet: 'Official Cloudflare developer documentation.' },
  { pattern: /\bgithub actions\b.*\b(docs?|documentation|official)\b/i, title: 'GitHub Actions Docs', url: 'https://docs.github.com/actions', snippet: 'Official GitHub Actions documentation.' },
  { pattern: /\bgitlab\b.*\bci\b.*\b(docs?|documentation|official)\b/i, title: 'GitLab CI/CD Docs', url: 'https://docs.gitlab.com/ci/', snippet: 'Official GitLab CI/CD documentation.' },
  { pattern: /\bvercel\b.*\b(docs?|documentation|official)\b/i, title: 'Vercel Docs', url: 'https://vercel.com/docs', snippet: 'Official Vercel documentation.' },
  { pattern: /\bnetlify\b.*\b(docs?|documentation|official)\b/i, title: 'Netlify Docs', url: 'https://docs.netlify.com/', snippet: 'Official Netlify documentation.' },
  { pattern: /\bsupabase\b.*\b(docs?|documentation|official)\b/i, title: 'Supabase Docs', url: 'https://supabase.com/docs', snippet: 'Official Supabase documentation.' },
  { pattern: /\bfirebase\b.*\b(docs?|documentation|official)\b/i, title: 'Firebase Docs', url: 'https://firebase.google.com/docs', snippet: 'Official Firebase documentation.' },
  { pattern: /\blinear\b.*\b(app|official|website|site)\b/i, title: 'Linear', url: 'https://linear.app/', snippet: 'Official Linear website.' },
  { pattern: /\bfigma\b.*\b(download|desktop|official)\b/i, title: 'Figma Downloads', url: 'https://www.figma.com/downloads/', snippet: 'Official Figma downloads page.' },
  { pattern: /\bbrave\b.*\b(browser|download|official)\b/i, title: 'Download Brave', url: 'https://brave.com/download/', snippet: 'Official Brave browser download page.' },
  { pattern: /\bfirefox\b.*\b(download|browser|official)\b/i, title: 'Download Firefox', url: 'https://www.mozilla.org/firefox/new/', snippet: 'Official Firefox download page.' },
  { pattern: /\busps\b.*\b(track|tracking)\b.*\bofficial\b/i, title: 'USPS Tracking', url: 'https://tools.usps.com/go/TrackConfirmAction_input', snippet: 'Official USPS tracking page.' },
  { pattern: /\buscis\b.*\b(case status|status|official)\b/i, title: 'USCIS Case Status Online', url: 'https://egov.uscis.gov/', snippet: 'Official USCIS case status page.' },
  { pattern: /\btsa\b.*\bprecheck\b.*\b(official|apply|application)?\b/i, title: 'TSA PreCheck', url: 'https://www.tsa.gov/precheck', snippet: 'Official TSA PreCheck page.' },
  { pattern: /\b(new york|ny)\b.*\bdmv\b.*\bofficial\b/i, title: 'New York DMV', url: 'https://dmv.ny.gov/', snippet: 'Official New York DMV website.' },
  { pattern: /\bftc\b.*\b(report fraud|fraud|official)\b/i, title: 'ReportFraud.ftc.gov', url: 'https://reportfraud.ftc.gov/', snippet: 'Official FTC fraud reporting page.' },
  { pattern: /\bcisa\b.*\b(kev|known exploited vulnerabilities|catalog)\b.*\bofficial\b/i, title: 'Known Exploited Vulnerabilities Catalog', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog', snippet: 'Official CISA KEV catalog.' },
  { pattern: /\bnvd\b.*\b(cve|official|vulnerability)\b/i, title: 'National Vulnerability Database', url: 'https://nvd.nist.gov/', snippet: 'Official NIST National Vulnerability Database.' },
  { pattern: /\bmitre\b.*\b(att&ck|attack|official)\b/i, title: 'MITRE ATT&CK', url: 'https://attack.mitre.org/', snippet: 'Official MITRE ATT&CK knowledge base.' },
  { pattern: /\btailscale\b/i, title: 'Tailscale', url: 'https://tailscale.com/', snippet: 'Official Tailscale website.' },
  { pattern: /\bsignal\b.*\b(desktop|download|official)\b/i, title: 'Download Signal', url: 'https://signal.org/download/', snippet: 'Official Signal download page.' },
  { pattern: /\bobs\b.*\b(studio|download|official)\b/i, title: 'Download OBS Studio', url: 'https://obsproject.com/download', snippet: 'Official OBS Studio download page.' },
  { pattern: /\bffmpeg\b.*\b(docs?|documentation|official)\b/i, title: 'FFmpeg Documentation', url: 'https://ffmpeg.org/documentation.html', snippet: 'Official FFmpeg documentation.' },
  { pattern: /\bpnpm\b.*\b(install|installation|docs?|official)\b/i, title: 'pnpm Installation', url: 'https://pnpm.io/installation', snippet: 'Official pnpm installation documentation.' },
  { pattern: /\bbun\b.*\b(install|installation|docs?|official)\b/i, title: 'Bun Installation', url: 'https://bun.sh/docs/installation', snippet: 'Official Bun installation documentation.' },
  { pattern: /\bdeno\b.*\b(install|installation|docs?|official)\b/i, title: 'Deno Installation', url: 'https://docs.deno.com/runtime/getting_started/installation/', snippet: 'Official Deno installation documentation.' },
  { pattern: /\belectron\b.*\b(app|framework|docs?|documentation|official)\b/i, title: 'Electron Docs', url: 'https://www.electronjs.org/docs/latest/', snippet: 'Official Electron documentation.' },
  { pattern: /\btauri\b.*\b(docs?|documentation|official)\b/i, title: 'Tauri', url: 'https://tauri.app/', snippet: 'Official Tauri website and documentation.' },
  { pattern: /\bsvelte\b.*\b(docs?|documentation|official)\b/i, title: 'Svelte Documentation', url: 'https://svelte.dev/docs', snippet: 'Official Svelte documentation.' },
  { pattern: /\bastro\b.*\b(framework|docs?|documentation|official)\b/i, title: 'Astro Docs', url: 'https://docs.astro.build/', snippet: 'Official Astro documentation.' },
  { pattern: /\bnuxt\b.*\b(docs?|documentation|official)\b/i, title: 'Nuxt Docs', url: 'https://nuxt.com/docs', snippet: 'Official Nuxt documentation.' },
  { pattern: /\bhono\b.*\b(framework|docs?|documentation|official)\b/i, title: 'Hono', url: 'https://hono.dev/', snippet: 'Official Hono website and documentation.' },
  { pattern: /\bfastapi\b.*\b(docs?|documentation|official)\b/i, title: 'FastAPI', url: 'https://fastapi.tiangolo.com/', snippet: 'Official FastAPI documentation.' },
  { pattern: /\bdjango\b.*\b(docs?|documentation|official)\b/i, title: 'Django Documentation', url: 'https://docs.djangoproject.com/', snippet: 'Official Django documentation.' },
  { pattern: /\bflask\b.*\b(docs?|documentation|official)\b/i, title: 'Flask Documentation', url: 'https://flask.palletsprojects.com/', snippet: 'Official Flask documentation.' },
  { pattern: /\bgo\b.*\b(programming language|download|official)\b/i, title: 'Go Downloads', url: 'https://go.dev/dl/', snippet: 'Official Go downloads page.' },
  { pattern: /\brustup\b.*\b(install|official)\b/i, title: 'rustup', url: 'https://rustup.rs/', snippet: 'Official rustup installation page.' },
  { pattern: /\bollama\b.*\b(download|install)\b/i, title: 'Download Ollama', url: 'https://ollama.com/download', snippet: 'Official Ollama download page.' },
  { pattern: /\blm studio\b.*\b(download|official)\b/i, title: 'LM Studio', url: 'https://lmstudio.ai/download', snippet: 'Official LM Studio download page.' },
  { pattern: /\bvllm\b.*\b(docs?|documentation|official)\b/i, title: 'vLLM Docs', url: 'https://docs.vllm.ai/', snippet: 'Official vLLM documentation.' },
  { pattern: /\bopen webui\b.*\b(github|official|docs?)\b/i, title: 'Open WebUI', url: 'https://github.com/open-webui/open-webui', snippet: 'Official Open WebUI GitHub repository.' },
  { pattern: /\bhome assistant\b.*\b(docs?|documentation|official)\b/i, title: 'Home Assistant Documentation', url: 'https://www.home-assistant.io/docs/', snippet: 'Official Home Assistant documentation.' },
  { pattern: /\bproxmox\b.*\b(ve|download|official)\b/i, title: 'Proxmox Downloads', url: 'https://www.proxmox.com/en/downloads', snippet: 'Official Proxmox downloads page.' },
  { pattern: /\bfedora\b.*\b(workstation|download|official)\b/i, title: 'Fedora Workstation', url: 'https://fedoraproject.org/workstation/download', snippet: 'Official Fedora Workstation download page.' },
  { pattern: /\barch\b.*\b(linux wiki|wiki)\b/i, title: 'ArchWiki', url: 'https://wiki.archlinux.org/', snippet: 'Official Arch Linux wiki.' },
  { pattern: /\bobsidian\b.*\b(download|install)\b/i, title: 'Download Obsidian', url: 'https://obsidian.md/download', snippet: 'Official Obsidian download page.' },
  { pattern: /\bnotion\b.*\b(desktop|app|download|official)\b/i, title: 'Notion Desktop', url: 'https://www.notion.com/desktop', snippet: 'Official Notion desktop app download page.' },
  { pattern: /\bslack\b.*\b(desktop|download|official)\b/i, title: 'Slack Downloads', url: 'https://slack.com/downloads', snippet: 'Official Slack downloads page.' },
  { pattern: /\bdiscord\b.*\b(download|official)\b/i, title: 'Download Discord', url: 'https://discord.com/download', snippet: 'Official Discord download page.' },
  { pattern: /\btelegram\b.*\b(desktop|download|official)\b/i, title: 'Telegram Desktop', url: 'https://desktop.telegram.org/', snippet: 'Official Telegram Desktop download page.' },
  { pattern: /\bblender\b.*\b(download|official)\b/i, title: 'Download Blender', url: 'https://www.blender.org/download/', snippet: 'Official Blender download page.' },
  { pattern: /\bgodot\b.*\b(engine|download|official)\b/i, title: 'Download Godot', url: 'https://godotengine.org/download/', snippet: 'Official Godot download page.' },
  { pattern: /\bunreal\b.*\b(engine|download|official)\b/i, title: 'Unreal Engine', url: 'https://www.unrealengine.com/', snippet: 'Official Unreal Engine website.' },
  { pattern: /\bkrita\b.*\b(download|official)\b/i, title: 'Krita', url: 'https://krita.org/en/download/', snippet: 'Official Krita download page.' },
  { pattern: /\bgimp\b.*\b(download|official)\b/i, title: 'GIMP Downloads', url: 'https://www.gimp.org/downloads/', snippet: 'Official GIMP downloads page.' },
  { pattern: /\binkscape\b.*\b(download|official)\b/i, title: 'Inkscape', url: 'https://inkscape.org/release/', snippet: 'Official Inkscape release and download page.' },
  { pattern: /\bcalibre\b.*\b(ebook|download|official)\b/i, title: 'Download calibre', url: 'https://calibre-ebook.com/download', snippet: 'Official calibre download page.' },
  { pattern: /\bqbittorrent\b.*\b(download|official)\b/i, title: 'qBittorrent Downloads', url: 'https://www.qbittorrent.org/download', snippet: 'Official qBittorrent download page.' },
  { pattern: /\birs\b.*\b(refund|refunds|refund status|where'?s my refund)\b/i, title: 'Where\'s My Refund?', url: 'https://www.irs.gov/wheres-my-refund', snippet: 'Official IRS refund status page.' },
  { pattern: /\b(social security|ssa)\b.*\b(my account|account|official)\b/i, title: 'my Social Security', url: 'https://www.ssa.gov/myaccount/', snippet: 'Official Social Security account page.' },
  { pattern: /\bcdc\b.*\bcovid\b.*\b(vaccine|vaccines|official)\b/i, title: 'COVID-19 Vaccines', url: 'https://www.cdc.gov/covid/vaccines/', snippet: 'Official CDC COVID-19 vaccine information.' },
  { pattern: /\bwho\b\s+(official website|website official)\b|\bworld health organization\b.*\bofficial website\b/i, title: 'World Health Organization', url: 'https://www.who.int/', snippet: 'Official World Health Organization website.' },
  { pattern: /\b(national weather service|nws)\b.*\b(forecast|official)\b/i, title: 'National Weather Service', url: 'https://www.weather.gov/', snippet: 'Official National Weather Service website.' },
];

export function buildExpandedOfficialSourceHints(query) {
  return EXPANDED_OFFICIAL_SOURCE_HINTS.filter((hint) => hint.pattern.test(query)).map((hint) => ({
    title: hint.title,
    url: hint.url,
    snippet: hint.snippet,
    publishedAt: null,
    source: 'local-web-search',
    thumbnail: null,
  }));
}
