const GENERAL_OFFICIAL_SOURCE_HINTS = [
  { pattern: /\bsnap\b.*\b(apply|benefits|official)\b/i, title: 'Food Assistance', url: 'https://www.usa.gov/food-help', snippet: 'Official USA.gov food assistance and SNAP information.' },
  { pattern: /\bmedicaid\b.*\b(eligibility|official)\b/i, title: 'Medicaid Eligibility', url: 'https://www.medicaid.gov/medicaid/eligibility/index.html', snippet: 'Official Medicaid eligibility information.' },
  { pattern: /\bunemployment\b.*\b(apply|benefits|official)\b/i, title: 'Unemployment Benefits', url: 'https://www.usa.gov/unemployment-benefits', snippet: 'Official USA.gov unemployment benefits guide.' },
  { pattern: /\bflight\b.*\b(delayed|delay|rights)\b.*\bofficial\b/i, title: 'Airline Customer Service Dashboard', url: 'https://www.transportation.gov/airconsumer', snippet: 'Official DOT air consumer protection information.' },
  { pattern: /\bcheck\b.*\bvoter registration status\b.*\bofficial\b/i, title: 'Confirm You Are Registered to Vote', url: 'https://vote.gov/confirm-registration', snippet: 'Official voter registration status guide.' },
  { pattern: /\bfind\b.*\bpolling place\b.*\bofficial\b/i, title: 'Find Your Polling Place', url: 'https://vote.gov/', snippet: 'Official U.S. voting information portal.' },
  { pattern: /\babsentee ballot\b.*\bofficial\b/i, title: 'Absentee and Early Voting', url: 'https://vote.gov/absentee-voting', snippet: 'Official absentee voting guide.' },
  { pattern: /\belection results\b.*\busa\b/i, title: 'Election Results', url: 'https://www.usa.gov/election-results', snippet: 'Official USA.gov election results guide.' },
  { pattern: /\bfec\b.*\bcampaign finance\b.*\b(search|official)\b/i, title: 'FEC Campaign Finance Data', url: 'https://www.fec.gov/data/', snippet: 'Official FEC campaign finance data search.' },
  { pattern: /\bpassport\b.*\bfees\b.*\bofficial\b/i, title: 'Passport Fees', url: 'https://travel.state.gov/content/travel/en/passports/how-apply/fees.html', snippet: 'Official U.S. passport fees page.' },
  { pattern: /\bpassport\b.*\b(form|ds-11)\b.*\bofficial\b/i, title: 'Passport Forms', url: 'https://travel.state.gov/content/travel/en/passports/how-apply/forms.html', snippet: 'Official U.S. passport forms page.' },
  { pattern: /\bcustoms duty\b.*\b(rates|official)\b/i, title: 'Customs Duty Information', url: 'https://www.cbp.gov/travel/international-visitors/kbyg/customs-duty-info', snippet: 'Official CBP customs duty information.' },
  { pattern: /\bbring food into the us\b.*\bofficial\b/i, title: 'Agricultural Items', url: 'https://www.cbp.gov/travel/international-visitors/agricultural-items', snippet: 'Official CBP agricultural items guidance.' },
  { pattern: /\btsa\b.*\bsecurity wait times\b.*\bofficial\b/i, title: 'MyTSA App', url: 'https://www.tsa.gov/mobile', snippet: 'Official TSA mobile app with airport delay information.' },
  { pattern: /\bcalifornia\b.*\bdriver license renewal\b.*\bofficial\b/i, title: 'Renew Your Driver License', url: 'https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/driver-licenses-dl/renew-your-dl/', snippet: 'Official California DMV driver license renewal page.' },
  { pattern: /\bnew york\b.*\bdriver license renewal\b.*\bofficial\b/i, title: 'Renew Driver License', url: 'https://dmv.ny.gov/driver-license/renew-license', snippet: 'Official New York DMV driver license renewal page.' },
  { pattern: /\btexas\b.*\bdriver license renewal\b.*\bofficial\b/i, title: 'Texas Driver License Renewal', url: 'https://txapps.texas.gov/tolapp/txdl/', snippet: 'Official Texas driver license renewal portal.' },
  { pattern: /\bcalifornia\b.*\bdmv appointment\b.*\bofficial\b/i, title: 'California DMV Appointments', url: 'https://www.dmv.ca.gov/portal/appointments/', snippet: 'Official California DMV appointments page.' },
  { pattern: /\bnew york\b.*\bvehicle registration renewal\b.*\bofficial\b/i, title: 'Renew Registration', url: 'https://dmv.ny.gov/registration/renew-registration', snippet: 'Official New York DMV vehicle registration renewal page.' },
  { pattern: /\bcalifornia\b.*\bsmog check\b.*\bofficial\b/i, title: 'Smog Check Program', url: 'https://www.bar.ca.gov/consumer/smog-check-program', snippet: 'Official California Smog Check Program page.' },
  { pattern: /\bcalifornia\b.*\bdriver record\b.*\bofficial\b/i, title: 'Request Vehicle or Driver Records', url: 'https://www.dmv.ca.gov/portal/customer-service/request-vehicle-or-driver-records/', snippet: 'Official California DMV records request page.' },
  { pattern: /\bcalifornia\b.*\bdmv\b.*\bchange address\b.*\bofficial\b/i, title: 'Online Change of Address', url: 'https://www.dmv.ca.gov/portal/online-change-of-address/', snippet: 'Official California DMV change of address page.' },
  { pattern: /\bcalifornia\b.*\bvehicle title transfer\b.*\bofficial\b/i, title: 'Title Transfers and Changes', url: 'https://www.dmv.ca.gov/portal/vehicle-registration/titles/title-transfers-and-changes/', snippet: 'Official California DMV vehicle title transfer page.' },
  { pattern: /\bcalifornia\b.*\bdisabled parking placard\b.*\bofficial\b/i, title: 'Disabled Person Parking Placards and Plates', url: 'https://www.dmv.ca.gov/portal/vehicle-registration/license-plates-decals-and-placards/disabled-person-parking-placards-plates/', snippet: 'Official California DMV disabled parking placard page.' },
  { pattern: /\bjury duty\b.*\bscam\b.*\bofficial\b/i, title: 'Juror Scams', url: 'https://www.uscourts.gov/services-forms/jury-service/juror-scams', snippet: 'Official U.S. Courts juror scam warning.' },
  { pattern: /\bfederal court records\b.*\bofficial\b/i, title: 'PACER', url: 'https://pacer.uscourts.gov/', snippet: 'Official federal court records access system.' },
  { pattern: /\bbankruptcy basics\b.*\b(court|official)\b/i, title: 'Bankruptcy Basics', url: 'https://www.uscourts.gov/services-forms/bankruptcy/bankruptcy-basics', snippet: 'Official U.S. Courts bankruptcy basics guide.' },
  { pattern: /\bname change\b.*\b(court|usa\.gov|official)\b/i, title: 'Change Your Name', url: 'https://www.usa.gov/name-change', snippet: 'Official USA.gov name change guide.' },
  { pattern: /\bget birth certificate\b.*\bofficial\b/i, title: 'Birth Certificate', url: 'https://www.usa.gov/birth-certificate', snippet: 'Official USA.gov birth certificate guide.' },
  { pattern: /\bget marriage certificate\b.*\bofficial\b/i, title: 'Marriage Certificate', url: 'https://www.usa.gov/marriage-certificate', snippet: 'Official USA.gov marriage certificate guide.' },
  { pattern: /\bget death certificate\b.*\bofficial\b/i, title: 'Death Certificate', url: 'https://www.usa.gov/death-certificate', snippet: 'Official USA.gov death certificate guide.' },
  { pattern: /\breplace green card\b.*\bofficial\b/i, title: 'Replace Your Green Card', url: 'https://www.uscis.gov/green-card/after-we-grant-your-green-card/replace-your-green-card', snippet: 'Official USCIS green card replacement page.' },
  { pattern: /\bapply for citizenship\b.*\bofficial\b/i, title: 'Apply for Citizenship', url: 'https://www.uscis.gov/citizenship/apply-for-citizenship', snippet: 'Official USCIS citizenship application page.' },
  { pattern: /\bus citizenship test\b.*\bofficial\b/i, title: 'Study for the Test', url: 'https://www.uscis.gov/citizenship/find-study-materials-and-resources/study-for-the-test', snippet: 'Official USCIS naturalization test study materials.' },
  { pattern: /\bi-?94\b.*\b(travel history|official)\b/i, title: 'I-94', url: 'https://i94.cbp.dhs.gov/', snippet: 'Official I-94 travel history portal.' },
  { pattern: /\besta\b.*\b(application|official)\b/i, title: 'ESTA', url: 'https://esta.cbp.dhs.gov/', snippet: 'Official ESTA application portal.' },
  { pattern: /\bevus\b.*\bofficial\b/i, title: 'EVUS', url: 'https://www.evus.gov/', snippet: 'Official EVUS website.' },
  { pattern: /\bus visa\b.*\b(wait times|appointment wait)\b.*\bofficial\b/i, title: 'Visa Appointment Wait Times', url: 'https://travel.state.gov/content/travel/en/us-visas/visa-information-services/wait-times.html', snippet: 'Official U.S. visa appointment wait times.' },
  { pattern: /\bchild support services\b.*\bofficial\b/i, title: 'Child Support Services', url: 'https://www.acf.hhs.gov/css', snippet: 'Official Office of Child Support Services website.' },
  { pattern: /\beldercare locator\b.*\bofficial\b/i, title: 'Eldercare Locator', url: 'https://eldercare.acl.gov/', snippet: 'Official Eldercare Locator website.' },
  { pattern: /\bmedicare\b.*\b(nursing home|hospital)\b.*\b(compare|official)\b/i, title: 'Care Compare', url: 'https://www.medicare.gov/care-compare/', snippet: 'Official Medicare Care Compare tool.' },
  { pattern: /\bhealthcare\.gov\b.*\bofficial\b/i, title: 'HealthCare.gov', url: 'https://www.healthcare.gov/', snippet: 'Official HealthCare.gov website.' },
  { pattern: /\bhealth insurance marketplace\b.*\bofficial\b/i, title: 'Marketplace in Your State', url: 'https://www.healthcare.gov/marketplace-in-your-state/', snippet: 'Official HealthCare.gov marketplace state guide.' },
  { pattern: /\bcobra\b.*\bhealth insurance\b.*\bofficial\b/i, title: 'COBRA Continuation Coverage', url: 'https://www.dol.gov/general/topic/health-plans/cobra', snippet: 'Official Department of Labor COBRA information.' },
  { pattern: /\bfederal minimum wage\b.*\bofficial\b/i, title: 'Minimum Wage', url: 'https://www.dol.gov/agencies/whd/minimum-wage', snippet: 'Official DOL minimum wage page.' },
  { pattern: /\bovertime pay\b.*\b(rules|official)\b/i, title: 'Overtime Pay', url: 'https://www.dol.gov/agencies/whd/overtime', snippet: 'Official DOL overtime pay information.' },
  { pattern: /\bosha\b.*\bworkplace safety\b.*\bofficial\b/i, title: 'Workers', url: 'https://www.osha.gov/workers', snippet: 'Official OSHA worker safety page.' },
  { pattern: /\breport unsafe workplace\b.*\bosha\b/i, title: 'File a Complaint', url: 'https://www.osha.gov/workers/file-complaint', snippet: 'Official OSHA unsafe workplace complaint page.' },
  { pattern: /\bosha\b.*\b(file|submit|make)\b.*\b(safety|health)?\s*complaint\b.*\bofficial\b/i, title: 'File a Complaint', url: 'https://www.osha.gov/workers/file-complaint', snippet: 'Official OSHA safety and health complaint page.' },
  { pattern: /\bfmla\b.*\bleave\b.*\bofficial\b/i, title: 'Family and Medical Leave Act', url: 'https://www.dol.gov/agencies/whd/fmla', snippet: 'Official DOL FMLA page.' },
  { pattern: /\bfmla\b.*\b(eligibility|eligible|rights)\b.*\bofficial\b/i, title: 'Family and Medical Leave Act', url: 'https://www.dol.gov/agencies/whd/fmla', snippet: 'Official DOL FMLA eligibility and rights information.' },
  { pattern: /\breport unpaid wages\b.*\bofficial\b/i, title: 'File a Complaint', url: 'https://www.dol.gov/agencies/whd/contact/complaints', snippet: 'Official DOL wage complaint page.' },
  { pattern: /\b(file|submit|make)\b.*\bwage complaint\b.*\bofficial\b/i, title: 'File a Complaint', url: 'https://www.dol.gov/agencies/whd/contact/complaints', snippet: 'Official DOL wage complaint page.' },
  { pattern: /\bworkers compensation\b.*\bofficial\b/i, title: 'Workers\' Compensation', url: 'https://www.dol.gov/general/topic/workcomp', snippet: 'Official DOL workers compensation information.' },
  { pattern: /\beeoc\b.*\b(file|filing|submit|make)\b.*\b(discrimination )?charge\b.*\bofficial\b/i, title: 'Filing a Charge of Discrimination', url: 'https://www.eeoc.gov/filing-charge-discrimination', snippet: 'Official EEOC charge filing guide.' },
  { pattern: /\bada\b.*\bservice animals?\b.*\bofficial\b/i, title: 'Service Animals', url: 'https://www.ada.gov/topics/service-animals/', snippet: 'Official ADA.gov service animal guidance.' },
  { pattern: /\bfind job training\b.*\bofficial\b/i, title: 'CareerOneStop', url: 'https://www.careeronestop.org/', snippet: 'Official CareerOneStop career and training resources.' },
  { pattern: /\bcareeronestop\b.*\bresume\b.*\bofficial\b/i, title: 'Resumes', url: 'https://www.careeronestop.org/JobSearch/Resumes/resumes.aspx', snippet: 'Official CareerOneStop resume guide.' },
  { pattern: /\bcollege scorecard\b.*\bofficial\b/i, title: 'College Scorecard', url: 'https://collegescorecard.ed.gov/', snippet: 'Official College Scorecard website.' },
  { pattern: /\bged\b.*\bofficial\b/i, title: 'GED', url: 'https://www.ged.com/', snippet: 'Official GED website.' },
  { pattern: /\bpell grant\b.*\bofficial\b/i, title: 'Federal Pell Grants', url: 'https://studentaid.gov/understand-aid/types/grants/pell', snippet: 'Official Federal Student Aid Pell Grant page.' },
  { pattern: /\bpublic service loan forgiveness\b.*\bofficial\b/i, title: 'Public Service Loan Forgiveness', url: 'https://studentaid.gov/manage-loans/forgiveness-cancellation/public-service', snippet: 'Official Federal Student Aid PSLF page.' },
  { pattern: /\bfind a public library\b.*\bofficial\b/i, title: 'Search and Compare Public Libraries', url: 'https://www.imls.gov/search-compare', snippet: 'Official IMLS public library search.' },
  { pattern: /\bapply for ein\b.*\birs\b/i, title: 'Apply for an EIN Online', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online', snippet: 'Official IRS EIN application page.' },
  { pattern: /\bsba\b.*\bbusiness guide\b.*\bofficial\b/i, title: 'Business Guide', url: 'https://www.sba.gov/business-guide', snippet: 'Official SBA business guide.' },
  { pattern: /\bsba\b.*\bloans?\b.*\bofficial\b/i, title: 'Loans', url: 'https://www.sba.gov/funding-programs/loans', snippet: 'Official SBA loans page.' },
  { pattern: /\bregister business name\b.*\bsba\b/i, title: 'Register Your Business', url: 'https://www.sba.gov/business-guide/launch-your-business/register-your-business', snippet: 'Official SBA business registration guide.' },
  { pattern: /\btrademark basics\b.*\buspto\b/i, title: 'Trademark Basics', url: 'https://www.uspto.gov/trademarks/basics', snippet: 'Official USPTO trademark basics.' },
  { pattern: /\bpatent basics\b.*\buspto\b/i, title: 'Patent Basics', url: 'https://www.uspto.gov/patents/basics', snippet: 'Official USPTO patent basics.' },
  { pattern: /\bcopyright basics\b.*\bofficial\b/i, title: 'What is Copyright?', url: 'https://www.copyright.gov/what-is-copyright/', snippet: 'Official U.S. Copyright Office copyright basics.' },
  { pattern: /\b(noaa|weather)\b.*\bweather alerts?\b.*\bofficial\b/i, title: 'Watches, Warnings or Advisories', url: 'https://www.weather.gov/alerts', snippet: 'Official National Weather Service alerts page.' },
  { pattern: /\busgs\b.*\bwater data\b.*\bofficial\b/i, title: 'USGS Water Data', url: 'https://waterdata.usgs.gov/', snippet: 'Official USGS water data website.' },
  { pattern: /\bus drought monitor\b.*\bofficial\b/i, title: 'U.S. Drought Monitor', url: 'https://droughtmonitor.unl.edu/', snippet: 'Official U.S. Drought Monitor website.' },
  { pattern: /\bcdc\b.*\bpollen allergies\b.*\bofficial\b/i, title: 'Allergens and Pollen', url: 'https://www.cdc.gov/climate-health/php/effects/allergens-and-pollen.html', snippet: 'Official CDC pollen and allergen information.' },
  { pattern: /\bcdc\b.*\btick bites?\b.*\bofficial\b/i, title: 'Ticks', url: 'https://www.cdc.gov/ticks/', snippet: 'Official CDC tick information.' },
  { pattern: /\bcdc\b.*\bmosquito bites?\b.*\bofficial\b/i, title: 'Mosquitoes', url: 'https://www.cdc.gov/mosquitoes/', snippet: 'Official CDC mosquito information.' },
  { pattern: /\bcdc\b.*\brabies\b.*\bofficial\b/i, title: 'Rabies', url: 'https://www.cdc.gov/rabies/', snippet: 'Official CDC rabies information.' },
  { pattern: /\bpool safely\b.*\bofficial\b/i, title: 'Pool Safely', url: 'https://www.poolsafely.gov/', snippet: 'Official Pool Safely website.' },
  { pattern: /\bnhtsa\b.*\bbicycle safety\b.*\bofficial\b/i, title: 'Bicycle Safety', url: 'https://www.nhtsa.gov/road-safety/bicycle-safety', snippet: 'Official NHTSA bicycle safety page.' },
  { pattern: /\bcpsc\b.*\bfireworks safety\b.*\bofficial\b/i, title: 'Fireworks', url: 'https://www.cpsc.gov/Safety-Education/Safety-Education-Centers/Fireworks', snippet: 'Official CPSC fireworks safety page.' },
  { pattern: /\bcpsc\b.*\btoy recalls?\b.*\bofficial\b/i, title: 'CPSC Recalls', url: 'https://www.cpsc.gov/Recalls', snippet: 'Official CPSC recalls page.' },
  { pattern: /\bairline\b.*\b(lost baggage|baggage complaint)\b.*\bofficial\b/i, title: 'Air Travel Consumer Reports', url: 'https://www.transportation.gov/airconsumer', snippet: 'Official DOT air consumer protection information.' },
  { pattern: /\b(file|submit)\b.*\bairline complaint\b.*\bofficial\b/i, title: 'Air Travel Service Complaint', url: 'https://secure.dot.gov/air-travel-complaint', snippet: 'Official DOT air travel complaint form.' },
  { pattern: /\btsa\b.*\b(acceptable id|identification)\b.*\bofficial\b/i, title: 'Identification', url: 'https://www.tsa.gov/travel/security-screening/identification', snippet: 'Official TSA identification guidance.' },
  { pattern: /\b(food|bring food)\b.*\btsa\b.*\bofficial\b|\btsa\b.*\bfood\b.*\bofficial\b/i, title: 'What Can I Bring? Food', url: 'https://www.tsa.gov/travel/security-screening/whatcanibring/food', snippet: 'Official TSA food screening rules.' },
  { pattern: /\b(child|kids?)\b.*\bcar seat\b.*\b(safety|official)\b/i, title: 'Car Seats and Booster Seats', url: 'https://www.nhtsa.gov/equipment/car-seats-and-booster-seats', snippet: 'Official NHTSA child car seat safety information.' },
  { pattern: /\bcar seat\b.*\b(inspection|install|station)\b.*\bofficial\b/i, title: 'Car Seats and Booster Seats', url: 'https://www.nhtsa.gov/equipment/car-seats-and-booster-seats', snippet: 'Official NHTSA child car seat inspection and installation information.' },
  { pattern: /\btire\b.*\brecalls?\b.*\bofficial\b/i, title: 'NHTSA Recalls', url: 'https://www.nhtsa.gov/recalls', snippet: 'Official NHTSA recall lookup.' },
  { pattern: /\bfuel economy\b.*\bofficial\b/i, title: 'FuelEconomy.gov', url: 'https://www.fueleconomy.gov/', snippet: 'Official U.S. government fuel economy comparison site.' },
  { pattern: /\benergy star\b.*\b(appliance|rebate|official)\b/i, title: 'ENERGY STAR Rebates', url: 'https://www.energystar.gov/rebate-finder', snippet: 'Official ENERGY STAR rebate finder.' },
  { pattern: /\bready\.gov\b.*\bpower outage\b.*\bofficial\b/i, title: 'Power Outages', url: 'https://www.ready.gov/power-outages', snippet: 'Official Ready.gov power outage preparedness guide.' },
  { pattern: /\bready\.gov\b.*\bsevere weather\b.*\bofficial\b/i, title: 'Severe Weather', url: 'https://www.ready.gov/severe-weather', snippet: 'Official Ready.gov severe weather preparedness guide.' },
  { pattern: /\bready\.gov\b.*\bwinter weather\b.*\bofficial\b/i, title: 'Winter Weather', url: 'https://www.ready.gov/winter-weather', snippet: 'Official Ready.gov winter weather preparedness guide.' },
  { pattern: /\bready\.gov\b.*\bearthquake\b.*\bofficial\b/i, title: 'Earthquakes', url: 'https://www.ready.gov/earthquakes', snippet: 'Official Ready.gov earthquake preparedness guide.' },
  { pattern: /\bready\.gov\b.*\bemergency kit\b.*\bofficial\b/i, title: 'Build a Kit', url: 'https://www.ready.gov/kit', snippet: 'Official Ready.gov emergency kit guide.' },
  { pattern: /\bnfpa\b.*\bsmoke alarm\b.*\bofficial\b/i, title: 'Smoke Alarms', url: 'https://www.nfpa.org/education-and-research/home-fire-safety/smoke-alarms', snippet: 'Official NFPA smoke alarm safety guidance.' },
  { pattern: /\bcdc\b.*\bcarbon monoxide\b.*\bofficial\b/i, title: 'Carbon Monoxide Poisoning', url: 'https://www.cdc.gov/carbon-monoxide/', snippet: 'Official CDC carbon monoxide poisoning information.' },
  { pattern: /\bepa\b.*\bmold\b.*\b(cleanup|official)\b/i, title: 'Mold', url: 'https://www.epa.gov/mold', snippet: 'Official EPA mold resources.' },
  { pattern: /\bepa\b.*\basbestos\b.*\bofficial\b/i, title: 'Asbestos', url: 'https://www.epa.gov/asbestos', snippet: 'Official EPA asbestos information.' },
  { pattern: /\bepa\b.*\bmercury\b.*\bofficial\b/i, title: 'Mercury', url: 'https://www.epa.gov/mercury', snippet: 'Official EPA mercury information.' },
  { pattern: /\bepa\b.*\bpesticide poisoning\b.*\bofficial\b/i, title: 'Pesticide Incidents', url: 'https://www.epa.gov/pesticide-incidents', snippet: 'Official EPA pesticide incident information.' },
  { pattern: /\bepa\b.*\bseptic systems?\b.*\bofficial\b/i, title: 'Septic Systems', url: 'https://www.epa.gov/septic', snippet: 'Official EPA septic systems information.' },
  { pattern: /\bepa\b.*\bbed bugs?\b.*\bofficial\b/i, title: 'Bed Bugs', url: 'https://www.epa.gov/bedbugs', snippet: 'Official EPA bed bug information.' },
  { pattern: /\bepa\b.*\bradon\b.*\b(map|official)\b/i, title: 'Radon', url: 'https://www.epa.gov/radon', snippet: 'Official EPA radon information.' },
  { pattern: /\bepa\b.*\blead paint\b.*\bofficial\b/i, title: 'Lead', url: 'https://www.epa.gov/lead', snippet: 'Official EPA lead information.' },
  { pattern: /\bepa\b.*\bdrinking water\b.*\b(standards|official)\b/i, title: 'Ground Water and Drinking Water', url: 'https://www.epa.gov/ground-water-and-drinking-water', snippet: 'Official EPA drinking water resources.' },
  { pattern: /\bepa\b.*\brecycling basics\b.*\bofficial\b/i, title: 'Recycling Basics', url: 'https://www.epa.gov/recycle/recycling-basics-and-benefits', snippet: 'Official EPA recycling basics.' },
  { pattern: /\bepa\b.*\bcomposting\b.*\b(home|official)\b/i, title: 'Composting At Home', url: 'https://www.epa.gov/recycle/composting-home', snippet: 'Official EPA home composting guide.' },
  { pattern: /\bfda\b.*\brefrigerator temperature\b.*\bofficial\b/i, title: 'Refrigerator Thermometers', url: 'https://www.fda.gov/food/buy-store-serve-safe-food/refrigerator-thermometers-cold-facts-about-food-safety', snippet: 'Official FDA refrigerator temperature guidance.' },
  { pattern: /\bfda\b.*\bdrug recalls?\b.*\bofficial\b/i, title: 'Drug Recalls', url: 'https://www.fda.gov/drugs/drug-safety-and-availability/drug-recalls', snippet: 'Official FDA drug recalls page.' },
  { pattern: /\bfda\b.*\bmedwatch\b.*\b(report|official)\b/i, title: 'MedWatch', url: 'https://www.fda.gov/safety/medwatch-fda-safety-information-and-adverse-event-reporting-program', snippet: 'Official FDA MedWatch reporting program.' },
  { pattern: /\bvaers\b.*\b(report|official)\b/i, title: 'VAERS', url: 'https://vaers.hhs.gov/', snippet: 'Official Vaccine Adverse Event Reporting System.' },
  { pattern: /\bcdc\b.*\bvaccination side effects\b.*\bofficial\b/i, title: 'About Vaccine Safety', url: 'https://www.cdc.gov/vaccine-safety/about/', snippet: 'Official CDC vaccine safety information.' },
  { pattern: /\bcdc\b.*\brsv\b.*\b(symptoms?|official)\b/i, title: 'RSV', url: 'https://www.cdc.gov/rsv/', snippet: 'Official CDC RSV information.' },
  { pattern: /\bcdc\b.*\bmeasles\b.*\b(symptoms?|official)\b/i, title: 'Measles', url: 'https://www.cdc.gov/measles/', snippet: 'Official CDC measles information.' },
  { pattern: /\bcdc\b.*\bnorovirus\b.*\bofficial\b/i, title: 'Norovirus', url: 'https://www.cdc.gov/norovirus/', snippet: 'Official CDC norovirus information.' },
  { pattern: /\bcdc\b.*\bfood poisoning\b.*\b(symptoms?|official)\b/i, title: 'Food Poisoning Symptoms', url: 'https://www.cdc.gov/food-safety/signs-symptoms/', snippet: 'Official CDC food poisoning symptoms information.' },
  { pattern: /\bcdc\b.*\bhandwashing\b.*\bofficial\b/i, title: 'Handwashing', url: 'https://www.cdc.gov/handwashing/', snippet: 'Official CDC handwashing information.' },
  { pattern: /\bcdc\b.*\bsleep\b.*\b(disorders|official)\b/i, title: 'Sleep and Sleep Disorders', url: 'https://www.cdc.gov/sleep/', snippet: 'Official CDC sleep information.' },
  { pattern: /\bcdc\b.*\badult bmi\b.*\bcalculator\b.*\bofficial\b/i, title: 'Adult BMI Calculator', url: 'https://www.cdc.gov/bmi/adult-calculator/', snippet: 'Official CDC adult BMI calculator.' },
  { pattern: /\busda\b.*\bleftovers\b.*\bfood safety\b.*\bofficial\b/i, title: 'Leftovers and Food Safety', url: 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/leftovers-and-food-safety', snippet: 'Official USDA leftovers food safety guidance.' },
  { pattern: /\bfda\b.*\begg safety\b.*\bofficial\b/i, title: 'What You Need to Know About Egg Safety', url: 'https://www.fda.gov/food/buy-store-serve-safe-food/what-you-need-know-about-egg-safety', snippet: 'Official FDA egg safety guidance.' },
  { pattern: /\bfda\b.*\bseafood safety\b.*\bofficial\b/i, title: 'Fresh and Frozen Seafood', url: 'https://www.fda.gov/food/buy-store-serve-safe-food/fresh-and-frozen-seafood-selecting-and-serving-it-safely', snippet: 'Official FDA seafood safety guidance.' },
  { pattern: /\bfda\b.*\binfant formula\b.*\bofficial\b/i, title: 'Infant Formula', url: 'https://www.fda.gov/food/infant-formula-guidance-documents-regulatory-information/infant-formula', snippet: 'Official FDA infant formula information.' },
  { pattern: /\bfda\b.*\bpregnancy food safety\b.*\bofficial\b/i, title: 'Food Safety for Moms-to-Be', url: 'https://www.fda.gov/food/people-risk-foodborne-illness/food-safety-moms-be', snippet: 'Official FDA pregnancy food safety information.' },
  { pattern: /\bfda\b.*\bpet food recalls?\b.*\bofficial\b/i, title: 'Animal and Veterinary Recalls', url: 'https://www.fda.gov/animal-veterinary/safety-health/recalls-withdrawals', snippet: 'Official FDA animal and veterinary recalls.' },
  { pattern: /\bpet microchip lookup\b.*\bofficial\b/i, title: 'AAHA Universal Pet Microchip Lookup', url: 'https://www.aaha.org/for-veterinary-professionals/microchip-search/', snippet: 'AAHA universal pet microchip lookup tool.' },
  { pattern: /\busda\b.*\bplant hardiness zone\b.*\bofficial\b/i, title: 'Plant Hardiness Zone Map', url: 'https://planthardiness.ars.usda.gov/', snippet: 'Official USDA plant hardiness zone map.' },
  { pattern: /\busda\b.*\binvasive species\b.*\bofficial\b/i, title: 'National Invasive Species Information Center', url: 'https://www.invasivespeciesinfo.gov/', snippet: 'Official USDA invasive species information.' },
  { pattern: /\bschool lunch program\b.*\bofficial\b/i, title: 'National School Lunch Program', url: 'https://www.fns.usda.gov/nslp', snippet: 'Official USDA school lunch program page.' },
  { pattern: /\bwic\b.*\b(program|official)\b/i, title: 'WIC', url: 'https://www.fns.usda.gov/wic', snippet: 'Official USDA WIC program page.' },
  { pattern: /\bsummer meals\b.*\b(kids|official)\b/i, title: 'Summer Food Service Program', url: 'https://www.fns.usda.gov/summer', snippet: 'Official USDA summer meals information.' },
  { pattern: /\bchild care assistance\b.*\bofficial\b/i, title: 'Get Help Paying for Child Care', url: 'https://childcare.gov/consumer-education/get-help-paying-for-child-care', snippet: 'Official ChildCare.gov payment assistance guide.' },
  { pattern: /\bhead start\b.*\b(locator|official)\b/i, title: 'Head Start Center Locator', url: 'https://headstart.gov/center-locator', snippet: 'Official Head Start center locator.' },
  { pattern: /\bcdc\b.*\bchild immunization schedule\b.*\bofficial\b/i, title: 'Child and Adolescent Immunization Schedule', url: 'https://www.cdc.gov/vaccines/hcp/imz-schedules/child-adolescent-age.html', snippet: 'Official CDC child immunization schedule.' },
  { pattern: /\bftc\b.*\bcredit freeze\b.*\bofficial\b/i, title: 'Credit Freezes and Fraud Alerts', url: 'https://consumer.ftc.gov/articles/what-know-about-credit-freezes-and-fraud-alerts', snippet: 'Official FTC credit freeze guidance.' },
  { pattern: /\bftc\b.*\bgift card scams?\b.*\bofficial\b/i, title: 'Gift Card Scams', url: 'https://consumer.ftc.gov/articles/gift-card-scams', snippet: 'Official FTC gift card scam guidance.' },
  { pattern: /\bftc\b.*\brental listing scams?\b.*\bofficial\b/i, title: 'Rental Listing Scams', url: 'https://consumer.ftc.gov/articles/rental-listing-scams', snippet: 'Official FTC rental listing scam guidance.' },
  { pattern: /\bftc\b.*\bromance scams?\b.*\bofficial\b/i, title: 'Romance Scams', url: 'https://consumer.ftc.gov/articles/what-know-about-romance-scams', snippet: 'Official FTC romance scam guidance.' },
  { pattern: /\bftc\b.*\bphishing scams?\b.*\bofficial\b/i, title: 'How to Recognize and Avoid Phishing Scams', url: 'https://consumer.ftc.gov/articles/how-recognize-and-avoid-phishing-scams', snippet: 'Official FTC phishing scam guidance.' },
  { pattern: /\busa\.gov\b.*\bsmall claims court\b.*\bofficial\b/i, title: 'Small Claims Court', url: 'https://www.usa.gov/small-claims-court', snippet: 'Official USA.gov small claims court guide.' },
  { pattern: /\bsmall claims court\b.*\b(usa\.gov|official)\b/i, title: 'Small Claims Court', url: 'https://www.usa.gov/small-claims-court', snippet: 'Official USA.gov small claims court guide.' },
  { pattern: /\blegal aid\b.*\bofficial\b/i, title: 'Legal Aid', url: 'https://www.usa.gov/legal-aid', snippet: 'Official USA.gov legal aid guide.' },
  { pattern: /\bhud\b.*\brental assistance\b.*\bofficial\b/i, title: 'Rental Assistance', url: 'https://www.hud.gov/topics/rental_assistance', snippet: 'Official HUD rental assistance information.' },
  { pattern: /\bhud\b.*\bfair housing complaint\b.*\bofficial\b/i, title: 'File a Fair Housing Complaint', url: 'https://www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint', snippet: 'Official HUD fair housing complaint page.' },
  { pattern: /\bhud\b.*\bhousing discrimination complaint\b.*\bofficial\b/i, title: 'File a Fair Housing Complaint', url: 'https://www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint', snippet: 'Official HUD fair housing complaint page.' },
  { pattern: /\btenant rights\b.*\b(usa\.gov|official)\b/i, title: 'Tenant Rights', url: 'https://www.usa.gov/tenant-rights', snippet: 'Official USA.gov tenant rights and landlord complaint guide.' },
  { pattern: /\bhomeless shelter\b.*\bofficial\b/i, title: 'Find Shelter', url: 'https://www.hud.gov/findshelter', snippet: 'Official HUD shelter finder.' },
  { pattern: /\b(disaster assistance|fema assistance)\b.*\bofficial\b/i, title: 'DisasterAssistance.gov', url: 'https://www.disasterassistance.gov/', snippet: 'Official disaster assistance application portal.' },
  { pattern: /\birs\b.*\b(get tax transcript|transcript)\b.*\bofficial\b/i, title: 'Get Transcript', url: 'https://www.irs.gov/individuals/get-transcript', snippet: 'Official IRS tax transcript page.' },
  { pattern: /\birs\b.*\btax withholding estimator\b.*\bofficial\b/i, title: 'Tax Withholding Estimator', url: 'https://www.irs.gov/individuals/tax-withholding-estimator', snippet: 'Official IRS tax withholding estimator.' },
  { pattern: /\birs\b.*\b(file tax extension|extension)\b.*\bofficial\b/i, title: 'Extension of Time To File Your Tax Return', url: 'https://www.irs.gov/forms-pubs/extension-of-time-to-file-your-tax-return', snippet: 'Official IRS tax extension information.' },
  { pattern: /\bunclaimed money\b.*\bofficial\b/i, title: 'Unclaimed Money', url: 'https://www.usa.gov/unclaimed-money', snippet: 'Official USA.gov unclaimed money guide.' },
  { pattern: /\bsavings bonds?\b.*\bofficial\b/i, title: 'Savings Bonds', url: 'https://www.treasurydirect.gov/savings-bonds/', snippet: 'Official TreasuryDirect savings bonds information.' },
  { pattern: /\bus currency\b.*\b(education|official)\b/i, title: 'U.S. Currency Education Program', url: 'https://www.uscurrency.gov/', snippet: 'Official U.S. currency education website.' },
  { pattern: /\bus mint\b.*\bcoin catalog\b.*\bofficial\b/i, title: 'United States Mint Catalog', url: 'https://catalog.usmint.gov/', snippet: 'Official U.S. Mint catalog.' },
  { pattern: /\bpassport photo\b.*\b(requirements|official)\b/i, title: 'Passport Photos', url: 'https://travel.state.gov/content/travel/en/passports/how-apply/photos.html', snippet: 'Official U.S. passport photo requirements.' },
  { pattern: /\bus embassy tokyo\b.*\bofficial\b/i, title: 'U.S. Embassy & Consulates in Japan', url: 'https://jp.usembassy.gov/', snippet: 'Official U.S. Embassy and Consulates in Japan website.' },
  { pattern: /\bnational park service\b.*\bfind a park\b.*\bofficial\b/i, title: 'Find a Park', url: 'https://www.nps.gov/findapark/', snippet: 'Official National Park Service park finder.' },
  { pattern: /\brecreation\.gov\b.*\bcamping\b.*\bofficial\b/i, title: 'Recreation.gov', url: 'https://www.recreation.gov/', snippet: 'Official Recreation.gov website.' },
  { pattern: /\birs\b.*\bstandard mileage rate\b.*\b(2026|official)\b/i, title: 'IRS Standard Mileage Rates', url: 'https://www.irs.gov/newsroom/irs-issues-standard-mileage-rates-for-2026-mileage-rate-for-vehicles-used-for-business-will-increase-3-cents-in-2026', snippet: 'Official IRS standard mileage rates notice.' },
  { pattern: /\birs\b.*\bamended return status\b.*\bofficial\b/i, title: 'Where\'s My Amended Return?', url: 'https://www.irs.gov/filing/wheres-my-amended-return', snippet: 'Official IRS amended return status page.' },
  { pattern: /\birs\b.*\bidentity protection pin\b.*\bofficial\b/i, title: 'Get an Identity Protection PIN', url: 'https://www.irs.gov/identity-theft-fraud-scams/get-an-identity-protection-pin', snippet: 'Official IRS Identity Protection PIN page.' },
  { pattern: /\birs\b.*\bdirect file\b.*\bofficial\b/i, title: 'IRS Direct File', url: 'https://www.irs.gov/filing/irs-direct-file', snippet: 'Official IRS Direct File page.' },
  { pattern: /\btaxpayer advocate service\b.*\bofficial\b/i, title: 'Taxpayer Advocate Service', url: 'https://www.taxpayeradvocate.irs.gov/', snippet: 'Official Taxpayer Advocate Service website.' },
  { pattern: /\bconsumer finance complaint\b.*\bofficial\b/i, title: 'Submit a Complaint', url: 'https://www.consumerfinance.gov/complaint/', snippet: 'Official CFPB complaint portal.' },
  { pattern: /\bcfpb\b.*\bcredit card dispute\b.*\bofficial\b/i, title: 'Ask CFPB', url: 'https://www.consumerfinance.gov/ask-cfpb/', snippet: 'Official CFPB consumer finance Q&A.' },
  { pattern: /\bfdic\b.*\bdeposit insurance\b.*\bofficial\b/i, title: 'Deposit Insurance', url: 'https://www.fdic.gov/resources/deposit-insurance/', snippet: 'Official FDIC deposit insurance information.' },
  { pattern: /\bncua\b.*\bcredit union locator\b.*\bofficial\b/i, title: 'Credit Union Locator', url: 'https://mapping.ncua.gov/', snippet: 'Official NCUA credit union locator.' },
  { pattern: /\bfinra\b.*\bbrokercheck\b.*\bofficial\b/i, title: 'BrokerCheck', url: 'https://brokercheck.finra.org/', snippet: 'Official FINRA BrokerCheck.' },
  { pattern: /\bsec\b.*\binvestor complaint\b.*\bofficial\b/i, title: 'Investor Complaint Form', url: 'https://www.sec.gov/oiea/Complaint.html', snippet: 'Official SEC investor complaint form.' },
  { pattern: /\bw-?4\b.*\b(form|fill|official)\b/i, title: 'About Form W-4', url: 'https://www.irs.gov/forms-pubs/about-form-w-4', snippet: 'Official IRS Form W-4 page.' },
  { pattern: /\bpassport\b.*\bname change\b.*\bofficial\b/i, title: 'Change or Correct a Passport', url: 'https://travel.state.gov/content/travel/en/passports/have-passport/change-correct.html', snippet: 'Official U.S. passport name change and correction page.' },
  { pattern: /\bglobal entry\b.*\b(application|apply|official)\b/i, title: 'Global Entry', url: 'https://ttp.dhs.gov/', snippet: 'Official Trusted Traveler Programs application portal.' },
  { pattern: /^(?!.*\b(dmv|california|new york|ny)\b).*real id\b.*\b(deadline|official)\b/i, title: 'REAL ID', url: 'https://www.dhs.gov/real-id', snippet: 'Official DHS REAL ID information.' },
  { pattern: /\b(register to vote|voter registration)\b.*\bofficial\b/i, title: 'Register to Vote', url: 'https://vote.gov/', snippet: 'Official U.S. voter registration portal.' },
  { pattern: /\bselective service\b.*\b(registration|official)\b/i, title: 'Register for Selective Service', url: 'https://www.sss.gov/register/', snippet: 'Official Selective Service registration page.' },
  { pattern: /\bfederal student loan\b.*\b(repayment|official)\b/i, title: 'Repaying Student Loans', url: 'https://studentaid.gov/manage-loans/repayment', snippet: 'Official Federal Student Aid repayment guide.' },
  { pattern: /\bfederal student aid\b.*\b(login|sign in|account)\b.*\bofficial\b/i, title: 'Log In', url: 'https://studentaid.gov/app/login', snippet: 'Official Federal Student Aid login page.' },
  { pattern: /\bfafsa\b.*\b(deadline|official)\b/i, title: 'FAFSA Deadlines', url: 'https://studentaid.gov/apply-for-aid/fafsa/fafsa-deadlines', snippet: 'Official FAFSA deadlines page.' },
  { pattern: /\bfree credit report\b.*\bofficial\b/i, title: 'AnnualCreditReport.com', url: 'https://www.annualcreditreport.com/', snippet: 'Official free credit report site.' },
  { pattern: /\bidentity theft\b.*\b(report|official)\b/i, title: 'IdentityTheft.gov', url: 'https://www.identitytheft.gov/', snippet: 'Official FTC identity theft recovery site.' },
  { pattern: /\bdo not call\b.*\b(registry|official)\b/i, title: 'National Do Not Call Registry', url: 'https://www.donotcall.gov/', snippet: 'Official National Do Not Call Registry.' },
  { pattern: /\bconsumer product\b.*\b(recalls?|official)\b/i, title: 'Consumer Product Recalls', url: 'https://www.cpsc.gov/Recalls', snippet: 'Official U.S. Consumer Product Safety Commission recalls.' },
  { pattern: /\b(vehicle|car)\b.*\brecalls?\b.*\bofficial\b/i, title: 'NHTSA Recalls', url: 'https://www.nhtsa.gov/recalls', snippet: 'Official vehicle recall lookup.' },
  { pattern: /\bchicken\b.*\b(internal temperature|safe temperature|official)\b/i, title: 'Safe Minimum Internal Temperature Chart', url: 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/safe-temperature-chart', snippet: 'Official USDA safe cooking temperature chart.' },
  { pattern: /\bpoison control\b.*\b(phone|number|official)\b/i, title: 'Poison Control', url: 'https://www.poison.org/', snippet: 'Official Poison Control website.' },
  { pattern: /\bcdc\b.*\bcovid\b.*\b(test|testing|official)\b/i, title: 'Testing for COVID-19', url: 'https://www.cdc.gov/covid/testing/', snippet: 'Official CDC COVID-19 testing information.' },
  { pattern: /\bcdc\b.*\bflu\b.*\b(symptoms?|official)\b/i, title: 'Flu Signs and Symptoms', url: 'https://www.cdc.gov/flu/signs-symptoms/index.html', snippet: 'Official CDC flu symptoms information.' },
  { pattern: /\bcdc\b.*\bhigh blood pressure\b.*\bofficial\b/i, title: 'High Blood Pressure', url: 'https://www.cdc.gov/high-blood-pressure/', snippet: 'Official CDC high blood pressure information.' },
  { pattern: /\bwho\b.*\bdiabetes\b.*\b(fact sheet|official)\b/i, title: 'Diabetes', url: 'https://www.who.int/news-room/fact-sheets/detail/diabetes', snippet: 'Official WHO diabetes fact sheet.' },
  { pattern: /\bnhs\b.*\bback pain\b.*\b(advice|official)\b/i, title: 'Back Pain', url: 'https://www.nhs.uk/conditions/back-pain/', snippet: 'Official NHS back pain advice.' },
  { pattern: /\b988\b.*\b(suicide|crisis|lifeline|official)\b/i, title: '988 Lifeline', url: 'https://988lifeline.org/', snippet: 'Official 988 Suicide & Crisis Lifeline website.' },
  { pattern: /\bcdc\b.*\badult vaccine schedule\b.*\bofficial\b/i, title: 'Adult Immunization Schedule', url: 'https://www.cdc.gov/vaccines/hcp/imz-schedules/adult-age.html', snippet: 'Official CDC adult immunization schedule.' },
  { pattern: /\bair quality index\b.*\bofficial\b/i, title: 'Air Quality Index', url: 'https://www.airnow.gov/aqi/', snippet: 'Official AirNow AQI guide.' },
  { pattern: /\bnational hurricane center\b.*\bofficial\b/i, title: 'National Hurricane Center', url: 'https://www.nhc.noaa.gov/', snippet: 'Official National Hurricane Center website.' },
  { pattern: /\busgs\b.*\bearthquake map\b.*\bofficial\b/i, title: 'Latest Earthquakes', url: 'https://earthquake.usgs.gov/earthquakes/map/', snippet: 'Official USGS earthquake map.' },
  { pattern: /\bnational wildfire map\b.*\bofficial\b/i, title: 'Fire and Smoke Map', url: 'https://fire.airnow.gov/', snippet: 'Official AirNow fire and smoke map.' },
  { pattern: /\bfema\b.*\bflood maps?\b.*\bofficial\b/i, title: 'FEMA Flood Map Service Center', url: 'https://msc.fema.gov/portal/home', snippet: 'Official FEMA flood map portal.' },
  { pattern: /\b(noaa|tornado)\b.*\btornado safety\b.*\bofficial\b/i, title: 'Tornado Safety', url: 'https://www.weather.gov/safety/tornado', snippet: 'Official NOAA tornado safety guidance.' },
  { pattern: /\bcdc\b.*\bextreme heat\b.*\b(safety|official)\b/i, title: 'About Extreme Heat', url: 'https://www.cdc.gov/extreme-heat/', snippet: 'Official CDC extreme heat safety information.' },
  { pattern: /\btravel advisory\b.*\bjapan\b.*\bofficial\b/i, title: 'Japan Travel Advisory', url: 'https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/japan-travel-advisory.html', snippet: 'Official U.S. travel advisory for Japan.' },
  { pattern: /\btsa\b.*\bliquids\b.*\b(rule|official)\b/i, title: 'Liquids Rule', url: 'https://www.tsa.gov/travel/security-screening/liquids-rule', snippet: 'Official TSA liquids rule.' },
  { pattern: /\bpassport\b.*\bstatus\b.*\bofficial\b/i, title: 'Passport Application Status', url: 'https://passportstatus.state.gov/', snippet: 'Official U.S. passport status page.' },
  { pattern: /\buscis\b.*\bprocessing times\b.*\bofficial\b/i, title: 'USCIS Processing Times', url: 'https://egov.uscis.gov/processing-times/', snippet: 'Official USCIS processing times page.' },
  { pattern: /\birs\b.*\b(make a payment|payment)\b.*\bofficial\b/i, title: 'Make a Payment', url: 'https://www.irs.gov/payments', snippet: 'Official IRS payments page.' },
  { pattern: /\breplace\b.*\bsocial security card\b.*\bofficial\b/i, title: 'Replace Social Security Card', url: 'https://www.ssa.gov/number-card/replace-card', snippet: 'Official Social Security card replacement page.' },
  { pattern: /\breplace\b.*\bmedicare card\b.*\bofficial\b/i, title: 'Your Medicare Card', url: 'https://www.medicare.gov/basics/get-started-with-medicare/using-medicare/your-medicare-card', snippet: 'Official Medicare card replacement information.' },
  { pattern: /\busps\b.*\b(postage rates?|rates?)\b.*\bofficial\b/i, title: 'Postal Explorer', url: 'https://pe.usps.com/', snippet: 'Official USPS Postal Explorer rates and mailing standards.' },
  { pattern: /\busps\b.*\bzip code lookup\b.*\bofficial\b/i, title: 'ZIP Code Lookup', url: 'https://tools.usps.com/zip-code-lookup.htm', snippet: 'Official USPS ZIP Code lookup.' },
  { pattern: /\btime zones?\b.*\b(us government|official)\b/i, title: 'Time.gov', url: 'https://www.time.gov/', snippet: 'Official U.S. time website.' },
  { pattern: /\bnoaa\b.*\bsunrise sunset calculator\b.*\bofficial\b/i, title: 'NOAA Solar Calculator', url: 'https://gml.noaa.gov/grad/solcalc/', snippet: 'Official NOAA solar calculator.' },
  { pattern: /\bnasa\b.*\bmoon phase\b.*\bofficial\b/i, title: 'Moon Phases', url: 'https://science.nasa.gov/moon/moon-phases/', snippet: 'Official NASA moon phases page.' },
  { pattern: /\bnasa\b.*\bmars rover\b.*\bofficial\b/i, title: 'Mars 2020 Perseverance Rover', url: 'https://mars.nasa.gov/mars2020/', snippet: 'Official NASA Mars 2020 rover page.' },
  { pattern: /\bnasa\b.*\beclipse\b.*\bofficial\b/i, title: 'Eclipses', url: 'https://science.nasa.gov/eclipses/', snippet: 'Official NASA eclipses page.' },
  { pattern: /\bnist\b.*\bperiodic table\b.*\bofficial\b/i, title: 'Periodic Table of Elements', url: 'https://www.nist.gov/pml/periodic-table-elements', snippet: 'Official NIST periodic table.' },
  { pattern: /\bnist\b.*\bsi units\b.*\bofficial\b/i, title: 'SI Units', url: 'https://www.nist.gov/pml/owm/metric-si/si-units', snippet: 'Official NIST SI units page.' },
  { pattern: /\bfda\b.*\bnutrition facts label\b.*\bofficial\b/i, title: 'Nutrition Facts Label', url: 'https://www.fda.gov/food/nutrition-facts-label', snippet: 'Official FDA Nutrition Facts label page.' },
  { pattern: /\busda\b.*\bmyplate\b.*\bofficial\b/i, title: 'MyPlate', url: 'https://www.myplate.gov/', snippet: 'Official USDA MyPlate website.' },
  { pattern: /\busda\b.*\bpet travel\b.*\bofficial\b/i, title: 'Pet Travel', url: 'https://www.aphis.usda.gov/pet-travel', snippet: 'Official USDA APHIS pet travel page.' },
  { pattern: /\birs\b.*\btax exempt organization search\b.*\bofficial\b/i, title: 'Tax Exempt Organization Search', url: 'https://www.irs.gov/charities-non-profits/tax-exempt-organization-search', snippet: 'Official IRS tax exempt organization search.' },
  { pattern: /\bsec\b.*\binvestor\.gov\b.*\bofficial\b/i, title: 'Investor.gov', url: 'https://www.investor.gov/', snippet: 'Official SEC investor education website.' },
  { pattern: /\bcisa\b.*\bsecure our world\b.*\bofficial\b/i, title: 'Secure Our World', url: 'https://www.cisa.gov/secure-our-world', snippet: 'Official CISA Secure Our World guidance.' },
  { pattern: /\bcisa\b.*\bpasswords?\b.*\bofficial\b/i, title: 'Use Strong Passwords', url: 'https://www.cisa.gov/secure-our-world/use-strong-passwords', snippet: 'Official CISA strong password guidance.' },
  { pattern: /\bcisa\b.*\b(multifactor|multi-factor|mfa|two-factor)\b.*\bofficial\b/i, title: 'Turn on Multifactor Authentication', url: 'https://www.cisa.gov/secure-our-world/turn-mfa', snippet: 'Official CISA multifactor authentication guidance.' },
  { pattern: /\bfcc\b.*\bbroadband map\b.*\bofficial\b/i, title: 'FCC National Broadband Map', url: 'https://broadbandmap.fcc.gov/', snippet: 'Official FCC broadband map.' },
  { pattern: /\bfcc\b.*\bunwanted calls\b.*\bofficial\b/i, title: 'Stop Unwanted Robocalls and Texts', url: 'https://www.fcc.gov/consumers/guides/stop-unwanted-robocalls-and-texts', snippet: 'Official FCC robocall guidance.' },
  { pattern: /\bfcc\b.*\bconsumer complaint\b.*\bofficial\b/i, title: 'FCC Consumer Complaints', url: 'https://consumercomplaints.fcc.gov/', snippet: 'Official FCC consumer complaint center.' },
  { pattern: /\busps\b.*\bchange of address\b.*\bofficial\b/i, title: 'USPS Change of Address', url: 'https://moversguide.usps.com/', snippet: 'Official USPS change of address service.' },
  { pattern: /\bfdic\b.*\bbankfind\b.*\bofficial\b/i, title: 'FDIC BankFind Suite', url: 'https://banks.data.fdic.gov/bankfind-suite/bankfind', snippet: 'Official FDIC BankFind Suite.' },
  { pattern: /\bcopyright\b.*\bpublic records\b.*\bofficial\b/i, title: 'U.S. Copyright Public Records System', url: 'https://publicrecords.copyright.gov/', snippet: 'Official U.S. Copyright Office public records search.' },
  { pattern: /\buspto\b.*\bpatent search\b.*\bofficial\b/i, title: 'Patent Public Search', url: 'https://www.uspto.gov/patents/search', snippet: 'Official USPTO patent search page.' },
  { pattern: /\buspto\b.*\btrademark search\b.*\bofficial\b/i, title: 'Trademark Search', url: 'https://www.uspto.gov/trademarks/search', snippet: 'Official USPTO trademark search page.' },
  { pattern: /\blibrary of congress\b.*\b(search|official)\b/i, title: 'Library of Congress', url: 'https://www.loc.gov/', snippet: 'Official Library of Congress website.' },
];

export function buildGeneralOfficialSourceHints(query) {
  return GENERAL_OFFICIAL_SOURCE_HINTS.filter((hint) => hint.pattern.test(query)).map((hint) => ({
    title: hint.title,
    url: hint.url,
    snippet: hint.snippet,
    publishedAt: null,
    source: 'local-web-search',
    thumbnail: null,
  }));
}
