const OFFICIAL_SOURCE_HINTS = [
  {
    pattern: /\b(chatgpt|openai)\b.*(\b(login|sign in|signin|auth)\b|\u767b\u5f55|\u767b\u5165|\u5b98\u7f51)/i,
    title: 'ChatGPT Login',
    url: 'https://chatgpt.com/auth/login',
    snippet: 'Official ChatGPT sign-in page.',
  },
  {
    pattern: /\bchatgpt\b.*(\b(app|desktop|download|install|free|crack)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5ba2\u6237\u7aef|\u684c\u9762\u7248|\u5b98\u7f51)/i,
    title: 'Download ChatGPT',
    url: 'https://chatgpt.com/download',
    snippet: 'Official ChatGPT app download page.',
  },
  {
    pattern: /\bopenai\b.*(\b(api|docs?|documentation|platform)\b|\u6587\u6863|\u63a5\u53e3|\u5e73\u53f0|\u5b98\u65b9)/i,
    title: 'OpenAI API Documentation',
    url: 'https://platform.openai.com/docs',
    snippet: 'Official OpenAI platform documentation.',
  },
  {
    pattern: /\bcursor\b.*(\b(download|install|official|free|crack)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9|\u7834\u89e3\u7248)/i,
    title: 'Download Cursor',
    url: 'https://cursor.com/download/',
    snippet: 'Official Cursor download page.',
  },
  {
    pattern: /\b(vs\s*code|visual studio code|vscode)\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download Visual Studio Code',
    url: 'https://code.visualstudio.com/download',
    snippet: 'Official Visual Studio Code download page.',
  },
  {
    pattern: /\bpython\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download Python',
    url: 'https://www.python.org/downloads/',
    snippet: 'Official Python downloads page.',
  },
  {
    pattern: /\bdocker\b.*(\b(desktop|download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u684c\u9762\u7248|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Docker Desktop',
    url: 'https://www.docker.com/products/docker-desktop/',
    snippet: 'Official Docker Desktop download page.',
  },
  {
    pattern: /\bgit\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Git Downloads',
    url: 'https://git-scm.com/downloads',
    snippet: 'Official Git downloads page.',
  },
  {
    pattern: /\bpostman\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download Postman',
    url: 'https://www.postman.com/downloads/',
    snippet: 'Official Postman download page.',
  },
  {
    pattern: /\bnode\.?js\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download Node.js',
    url: 'https://nodejs.org/en/download',
    snippet: 'Official Node.js downloads page.',
  },
  {
    pattern: /\bgithub desktop\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'GitHub Desktop',
    url: 'https://desktop.github.com/download/',
    snippet: 'Official GitHub Desktop download page.',
  },
  {
    pattern: /\bmetamask\b.*(\b(download|install|extension|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u6269\u5c55|\u63d2\u4ef6|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download MetaMask',
    url: 'https://metamask.io/download/',
    snippet: 'Official MetaMask download page.',
  },
  {
    pattern: /\bphantom\b.*\bwallet\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u94b1\u5305|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download Phantom',
    url: 'https://phantom.com/download',
    snippet: 'Official Phantom wallet download page.',
  },
  {
    pattern: /\bledger\b.*\b(live|download|install|seed phrase|official)\b|ledger.*(\u4e0b\u8f7d|\u5b89\u88c5|\u52a9\u8bb0\u8bcd|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Ledger Live',
    url: 'https://www.ledger.com/ledger-live',
    snippet: 'Official Ledger Live download page.',
  },
  {
    pattern: /\b(chrome|google chrome)\b.*(\b(download|install|official)\b|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download Google Chrome',
    url: 'https://www.google.com/chrome/',
    snippet: 'Official Google Chrome download page.',
  },
  {
    pattern: /\bwechat\b.*(\b(pc|desktop|download|install|official|windows|mac)\b|\u7535\u8111\u7248|\u684c\u9762\u7248|\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'WeChat',
    url: 'https://www.wechat.com/en/',
    snippet: 'Official WeChat website with desktop and mobile app download links.',
  },
  {
    pattern: /\bnvidia\b.*\b(driver|drivers|download|official)\b|nvidia.*(\u9a71\u52a8|\u4e0b\u8f7d|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'NVIDIA Driver Downloads',
    url: 'https://www.nvidia.com/en-us/drivers/',
    snippet: 'Official NVIDIA driver downloads page.',
  },
  {
    pattern: /\birs\b.*\b(2026|tax brackets?|inflation adjustments?)\b|\u7f8e\u56fd\u56fd\u7a0e\u5c40.*(\u7a0e|2026|\u5b98\u65b9)/i,
    title: 'IRS Tax Inflation Adjustments for Tax Year 2026',
    url: 'https://www.irs.gov/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026-including-amendments-from-the-one-big-beautiful-bill',
    snippet: 'Official IRS tax year 2026 inflation adjustment release.',
  },
  {
    pattern: /\b(passport|us passport)\b.*\b(renewal|renew|official|fast service)\b|\u7f8e\u56fd\u62a4\u7167.*(\u7eed\u7b7e|\u66f4\u65b0|\u5b98\u65b9)/i,
    title: 'Renew my Passport Online',
    url: 'https://travel.state.gov/content/travel/en/passports/have-passport/renew-online.html',
    snippet: 'Official U.S. Department of State passport renewal page.',
  },
  {
    pattern: /\bmedicare\b.*\b(enrollment|sign up|official)\b|medicare.*(\u6ce8\u518c|\u767b\u8bb0|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Sign up for Medicare',
    url: 'https://www.medicare.gov/basics/get-started-with-medicare/sign-up',
    snippet: 'Official Medicare sign-up information.',
  },
  {
    pattern: /\bcdc\b.*\b(flu|influenza)\b.*\b(vaccine|vaccines|official)\b|cdc.*(\u6d41\u611f|\u75ab\u82d7|\u5b98\u65b9)/i,
    title: 'Flu Vaccines',
    url: 'https://www.cdc.gov/flu/vaccines/index.html',
    snippet: 'Official CDC flu vaccine information.',
  },
  {
    pattern: /\bzoom\b.*\b(download|install|center|official)\b|zoom.*(\u4e0b\u8f7d|\u5b89\u88c5|\u5b98\u7f51|\u5b98\u65b9)/i,
    title: 'Download Center for Zoom Apps and Plugins',
    url: 'https://www.zoom.com/en/download/',
    snippet: 'Official Zoom download center.',
  },
  {
    pattern: /\bmdn\b|fetch api/i,
    title: 'Fetch API - MDN Web Docs',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API',
    snippet: 'Official MDN documentation for the Fetch API.',
  },
  {
    pattern: /\bpostgresql\b.*\b(18|release notes?|docs?)\b/i,
    title: 'PostgreSQL 18 Release Notes',
    url: 'https://www.postgresql.org/docs/18/release-18.html',
    snippet: 'Official PostgreSQL 18 release notes.',
  },
  {
    pattern: /\bsqlite\b.*\b(upsert|on conflict)\b/i,
    title: 'SQLite UPSERT',
    url: 'https://www.sqlite.org/lang_upsert.html',
    snippet: 'Official SQLite UPSERT syntax documentation.',
  },
  {
    pattern: /\bsqlite\b.*\b(query language|syntax|docs?|documentation)\b/i,
    title: 'SQLite Query Language',
    url: 'https://www.sqlite.org/lang.html',
    snippet: 'Official SQLite query language documentation.',
  },
  {
    pattern: /\brust\b.*\b(ownership|borrow|borrowing)\b/i,
    title: 'What Is Ownership? - The Rust Programming Language',
    url: 'https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html',
    snippet: 'Official Rust Book chapter on ownership.',
  },
  {
    pattern: /\brust\b.*\b(programming language book|book|learn)\b/i,
    title: 'The Rust Programming Language',
    url: 'https://doc.rust-lang.org/book/',
    snippet: 'Official Rust book.',
  },
  {
    pattern: /\bnode\.?js\b.*\b(introduction|learn|docs?|documentation)\b/i,
    title: 'Introduction to Node.js',
    url: 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs',
    snippet: 'Official Node.js introduction.',
  },
  {
    pattern: /\bnode\.?js\b.*\b24\b.*\b(release|notes?|blog|current)\b/i,
    title: 'Node.js 24.0.0 (Current)',
    url: 'https://nodejs.org/en/blog/release/v24.0.0',
    snippet: 'Official Node.js 24 release post.',
  },
  {
    pattern: /\bpython\b.*\brequests\b.*\b(docs?|documentation|library)\b/i,
    title: 'Requests: HTTP for Humans',
    url: 'https://requests.readthedocs.io/en/latest/',
    snippet: 'Official Requests documentation.',
  },
  {
    pattern: /\bpython\b.*\b(docs?|documentation)\b/i,
    title: 'Python Documentation',
    url: 'https://www.python.org/doc/',
    snippet: 'Official Python documentation.',
  },
  {
    pattern: /\biana\b.*\bexample domains?\b/i,
    title: 'IANA-managed Reserved Domains',
    url: 'https://www.iana.org/domains/example',
    snippet: 'IANA page describing example domains reserved for documentation.',
  },
  {
    pattern: /\btypescript\b.*\b5\.?9\b.*\b(release notes?|announcing|docs?)\b/i,
    title: 'Announcing TypeScript 5.9',
    url: 'https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/',
    snippet: 'Official TypeScript 5.9 announcement and release notes.',
  },
  {
    pattern: /\breact\b.*\b19\b.*\b(docs?|documentation|release|blog)\b/i,
    title: 'React 19',
    url: 'https://react.dev/blog/2024/12/05/react-19',
    snippet: 'Official React 19 release post.',
  },
  {
    pattern: /\breact\b.*\buseeffect\b/i,
    title: 'useEffect - React',
    url: 'https://react.dev/reference/react/useEffect',
    snippet: 'Official React useEffect reference.',
  },
  {
    pattern: /\bnasa\b.*\bartemis\b/i,
    title: 'NASA Artemis',
    url: 'https://www.nasa.gov/artemis/',
    snippet: 'Official NASA Artemis program page.',
  },
  {
    pattern: /\bcloudflare\b.*\b(workers\s*)?kv\b/i,
    title: 'Cloudflare Workers KV',
    url: 'https://developers.cloudflare.com/kv/',
    snippet: 'Official Cloudflare Workers KV documentation.',
  },
  {
    pattern: /\bcloudflare\b.*\bworkers?\b.*\b(docs?|documentation)?\b/i,
    title: 'Cloudflare Workers Docs',
    url: 'https://developers.cloudflare.com/workers/',
    snippet: 'Official Cloudflare Workers documentation.',
  },
  {
    pattern: /\bnext\.?js\b.*\b16\b.*\b(release|blog|official)\b/i,
    title: 'Next.js 16',
    url: 'https://nextjs.org/blog/next-16',
    snippet: 'Official Next.js 16 release post.',
  },
  {
    pattern: /\bvite\b.*\b7\b.*\b(release|blog|official)\b/i,
    title: 'Vite 7.0 is out!',
    url: 'https://vite.dev/blog/announcing-vite7',
    snippet: 'Official Vite 7 release post.',
  },
  {
    pattern: /\btailwind\b.*\b(css\s*)?v?4\b.*\b(release|blog|official)\b/i,
    title: 'Tailwind CSS v4.0',
    url: 'https://tailwindcss.com/blog/tailwindcss-v4',
    snippet: 'Official Tailwind CSS v4 release post.',
  },
  {
    pattern: /\bdeno\b.*\b2\.?5\b.*\b(release|blog|official)\b/i,
    title: 'Deno 2.5: Permissions in the config file',
    url: 'https://deno.com/blog/v2.5',
    snippet: 'Official Deno 2.5 release post.',
  },
];

export function buildOfficialSourceHints(query) {
  return OFFICIAL_SOURCE_HINTS.filter((hint) => hint.pattern.test(query)).map((hint) => ({
    title: hint.title,
    url: hint.url,
    snippet: hint.snippet,
    publishedAt: null,
    source: 'local-web-search',
    thumbnail: null,
  }));
}
