import type { SlashMenuItem } from './types';

export const slashMenuItems: SlashMenuItem[] = [
  {
    id: 'text',
    name: 'Text',
    icon: '📝',
    description: 'Plain text paragraph',
    group: 'Basic',
    searchTerms: ['paragraph', 'p'],
    commandId: 'paragraph',
  },
  {
    id: 'inline-math',
    name: 'Inline Math',
    icon: 'x²',
    description: 'Inline LaTeX formula',
    group: 'Basic',
    searchTerms: ['math inline', 'latex inline', 'formula inline'],
    commandId: 'inline-math',
  },
  {
    id: 'heading-1',
    name: 'Heading 1',
    icon: 'H1',
    description: 'Large section heading',
    group: 'Basic',
    searchTerms: ['h1', 'title'],
    commandId: 'heading-1',
  },
  {
    id: 'heading-2',
    name: 'Heading 2',
    icon: 'H2',
    description: 'Medium section heading',
    group: 'Basic',
    searchTerms: ['h2'],
    commandId: 'heading-2',
  },
  {
    id: 'heading-3',
    name: 'Heading 3',
    icon: 'H3',
    description: 'Small section heading',
    group: 'Basic',
    searchTerms: ['h3'],
    commandId: 'heading-3',
  },
  {
    id: 'heading-4',
    name: 'Heading 4',
    icon: 'H4',
    description: 'Subsection heading',
    group: 'Basic',
    searchTerms: ['h4'],
    commandId: 'heading-4',
  },
  {
    id: 'heading-5',
    name: 'Heading 5',
    icon: 'H5',
    description: 'Minor heading',
    group: 'Basic',
    searchTerms: ['h5'],
    commandId: 'heading-5',
  },
  {
    id: 'heading-6',
    name: 'Heading 6',
    icon: 'H6',
    description: 'Smallest heading',
    group: 'Basic',
    searchTerms: ['h6'],
    commandId: 'heading-6',
  },
  {
    id: 'bullet-list',
    name: 'Bullet List',
    icon: '•',
    description: 'Unordered list',
    group: 'Lists',
    searchTerms: ['ul', 'unordered'],
    commandId: 'bullet-list',
  },
  {
    id: 'ordered-list',
    name: 'Numbered List',
    icon: '1.',
    description: 'Ordered list',
    group: 'Lists',
    searchTerms: ['ol', 'ordered'],
    commandId: 'ordered-list',
  },
  {
    id: 'task-list',
    name: 'Task List',
    icon: '☑',
    description: 'Checklist with checkboxes',
    group: 'Lists',
    searchTerms: ['todo', 'checkbox', 'checklist'],
    commandId: 'task-list',
  },
  {
    id: 'code-block',
    name: 'Code Block',
    icon: '</>',
    description: 'Code with syntax highlighting',
    group: 'Media',
    searchTerms: ['code', 'pre', 'snippet'],
    commandId: 'code-block',
  },
  {
    id: 'equation',
    name: 'Equation',
    icon: '∑',
    description: 'LaTeX math block',
    group: 'Media',
    searchTerms: ['math', 'latex', 'formula'],
    commandId: 'equation',
  },
  {
    id: 'image',
    name: 'Image',
    icon: '🖼',
    description: 'Insert an image',
    group: 'Media',
    searchTerms: ['img', 'picture', 'photo'],
    commandId: 'image',
  },
  {
    id: 'table',
    name: 'Table',
    icon: '▦',
    description: 'Insert a table',
    group: 'Advanced',
    searchTerms: ['grid'],
    commandId: 'table',
  },
  {
    id: 'divider',
    name: 'Divider',
    icon: '—',
    description: 'Horizontal rule',
    group: 'Advanced',
    searchTerms: ['hr', 'line', 'separator'],
    commandId: 'divider',
  },
  {
    id: 'callout',
    name: 'Callout',
    icon: '💡',
    description: 'Highlighted note block',
    group: 'Advanced',
    searchTerms: ['note', 'tip', 'warning', 'info'],
    commandId: 'callout',
  },
  {
    id: 'quote',
    name: 'Quote',
    icon: '"',
    description: 'Block quote',
    group: 'Advanced',
    searchTerms: ['blockquote', 'cite'],
    commandId: 'quote',
  },
  {
    id: 'toc',
    name: 'Table of Contents',
    icon: '📑',
    description: 'Auto-generated TOC',
    group: 'Advanced',
    searchTerms: ['toc', 'contents', 'outline'],
    commandId: 'toc',
  },
  {
    id: 'mermaid',
    name: 'Mermaid Diagram',
    icon: '📊',
    description: 'Flowchart, sequence diagram',
    group: 'Advanced',
    searchTerms: ['diagram', 'flowchart', 'chart', 'graph'],
    commandId: 'mermaid',
  },
  {
    id: 'footnote',
    name: 'Footnote',
    icon: '📝',
    description: 'Add a footnote reference',
    group: 'Advanced',
    searchTerms: ['note', 'reference', 'citation'],
    commandId: 'footnote',
  },
  {
    id: 'footnote-definition',
    name: 'Footnote Definition',
    icon: '[^:]',
    description: 'Define footnote content block',
    group: 'Advanced',
    searchTerms: ['footnote def', 'footnote definition', 'citation block'],
    commandId: 'footnote-definition',
  },
  {
    id: 'abbreviation',
    name: 'Abbreviation',
    icon: 'Ab',
    description: 'Insert abbreviation definition',
    group: 'Advanced',
    searchTerms: ['abbr', 'acronym', 'short form'],
    commandId: 'abbreviation',
  },
  {
    id: 'video',
    name: 'Video',
    icon: '🎬',
    description: 'Embed YouTube, Bilibili video',
    group: 'Media',
    searchTerms: ['youtube', 'bilibili', 'embed', 'movie'],
    commandId: 'video',
  },
];
