import type { LanguageDetector } from '../types';

export const detectGo: LanguageDetector = (ctx) => {
  const { first100Lines, sample, code, lines } = ctx;

  // Simple single-line Go patterns
  if (lines.length <= 3) {
    // Go short variable declaration: name := "Alice"
    if (/^\w+\s*:=\s*"[^"]*"$/.test(code.trim())) {
      return 'go';
    }
    
    if (/\bfmt\.(Print|Println|Printf|Sprint|Sprintf)\(/.test(code)) {
      return 'go';
    }
  }

  // Go package declaration
  if (/^package\s+\w+$/m.test(first100Lines)) {
    if (/\bfunc\s+\w+\s*\(/.test(first100Lines) ||
        /\btype\s+\w+\s+struct/.test(first100Lines) ||
        /\bimport\s+"/.test(first100Lines) ||
        /protobuf:"/.test(first100Lines) ||
        /Code generated by protoc/.test(first100Lines)) {
      return 'go';
    }
  }

  // Go struct definition
  if (/^type\s+\w+\s+struct\s*\{/m.test(code)) {
    return 'go';
  }

  if (/\b(resp|err|ctx|req|data|result|client|conn),\s*(err|_)\s*:=/.test(code)) {
    return 'go';
  }

  if (/\w+,\s*err\s*:=/.test(code) && /\bif\s+err\s*!=\s*nil\s*\{/.test(code)) {
    return 'go';
  }

  if (/\w+\s*:=\s*\[\]\w+\{\{/.test(code)) {
    return 'go';
  }

  if (/\[\]\w+\{\{[^}]+\}\}/.test(code)) {
    return 'go';
  }

  if (/\bif\s+err\s*!=\s*nil\s*\{/.test(code)) {
    if (/\breturn\b/.test(code) && /fmt\.Errorf/.test(code)) {
      return 'go';
    }
  }

  if (/\bdefer\s+\w+\.\w+\(/.test(code)) {
    return 'go';
  }

  if (/\bgo\s+func\s*\(/.test(code) || /\bgo\s+\w+\(/.test(code)) {
    return 'go';
  }

  // Go make function (chan, map, slice) - avoid Makefile confusion
  if (/\bmake\s*\(\s*chan\s+/.test(code) ||
      /\bmake\s*\(\s*map\s*\[/.test(code) ||
      /results\s*:=\s*make\s*\(/.test(code) ||
      /\w+\s*:=\s*make\s*\(/.test(code)) {
    return 'go';
  }

  // Go sync patterns - strong indicator
  if (/\bsync\.(WaitGroup|Mutex|RWMutex)/.test(code) ||
      /\bvar\s+wg\s+sync\.WaitGroup/.test(code) ||
      /wg\.(Add|Done|Wait)\(/.test(code)) {
    return 'go';
  }

  // Go goroutine patterns (very strong indicator)
  if (/\bgo\s+func\s*\([^)]*\)\s*\{/.test(code)) {
    return 'go';
  }

  // Go anonymous goroutine with closure
  if (/\bgo\s+func\s*\(\w+\s+\w+\)\s*\{/.test(code) && /\bdefer\s+/.test(code)) {
    return 'go';
  }

  // Go channel operations (very strong indicator)
  if (/<-\s*results/.test(code) && /\bfor\s+\w+\s*:=\s*range\s+/.test(code)) {
    return 'go';
  }

  // Go channel with buffered size
  if (/\bmake\s*\(\s*chan\s+\w+,\s*\w+/.test(code)) {
    return 'go';
  }

  // Go defer with method call
  if (/\bdefer\s+\w+\.(Done|Close|Unlock)\s*\(\)/.test(code)) {
    return 'go';
  }

  // Go function with multiple return values and error handling
  if (/func\s+\w+\([^)]*\)\s+\([^)]*,\s*error\)/.test(code)) {
    return 'go';
  }

  // Go channel with close
  if (/\bclose\s*\(\s*\w+\s*\)/.test(code) && /\bmake\s*\(\s*chan\s+/.test(code)) {
    return 'go';
  }

  // Go range over channel
  if (/\bfor\s+\w+\s*:=\s*range\s+\w+\s*\{/.test(code) && /<-/.test(code)) {
    return 'go';
  }

  if (/\b(fmt|http|io|os|time|context|errors)\.\w+\(/.test(code) && /:=/.test(code)) {
    return 'go';
  }

  if (!/^package\s+\w+$/m.test(first100Lines)) {
    if (lines.length <= 3 && /:=/.test(code)) {
      if (/\b(err|ctx|req|resp)\b/.test(code)) {
        return 'go';
      }
    }
    if (lines.length <= 5 && /^type\s+\w+\s+struct/.test(code)) {
      return 'go';
    }
    return null;
  }

  if (/protobuf:"/.test(first100Lines) ||
      /Code generated by protoc/.test(first100Lines) ||
      /github\.com\/gogo\/protobuf/.test(first100Lines)) {
    return 'go';
  }

  if (/\b(func\s+\w+|type\s+\w+\s+struct|type\s+\w+\s+interface)\b/.test(first100Lines)) {
    if (/\b(chan|go\s+func|defer|interface\s*\{|make\(|range\s+)\b/.test(first100Lines) ||
        sample.includes(':=') ||
        /`json:"/.test(first100Lines) ||
        /\bfunc\s+init\s*\(\)/.test(first100Lines)) {
      return 'go';
    }
  }

  if (/\bfunc\s+\(/.test(first100Lines) && /\btype\s+\w+\s+struct/.test(first100Lines)) {
    return 'go';
  }

  if (sample.includes(':=') ||
      /`\w+:"/.test(first100Lines) ||
      /\b(chan|defer|goroutine)\b/.test(first100Lines)) {
    return 'go';
  }

  return null;
};
