import type { LanguageDetector } from '../types';

export const detectGo: LanguageDetector = (ctx) => {
  const { first100Lines, sample } = ctx;

  if (!/^package\s+\w+$/m.test(first100Lines)) {
    return null;
  }

  if (/protobuf:"/.test(first100Lines) ||
      /Code generated by protoc/.test(first100Lines) ||
      /github\.com\/gogo\/protobuf/.test(first100Lines)) {
    return 'go';
  }

  if (/\b(func\s+\w+|type\s+\w+\s+struct|type\s+\w+\s+interface)\b/.test(first100Lines)) {
    if (/\b(chan|go\s+func|defer|interface\s*\{|make\(|range\s+)\b/.test(first100Lines) ||
        sample.includes(':=') ||
        /`json:"/.test(first100Lines) ||
        /\bfunc\s+init\s*\(\)/.test(first100Lines)) {
      return 'go';
    }
  }

  if (/\bfunc\s+\(/.test(first100Lines) && /\btype\s+\w+\s+struct/.test(first100Lines)) {
    return 'go';
  }

  if (sample.includes(':=') ||
      /`\w+:"/.test(first100Lines) ||
      /\b(chan|defer|goroutine)\b/.test(first100Lines)) {
    return 'go';
  }

  return null;
};
