import type { LanguageDetector } from '../types';

export const detectGo: LanguageDetector = (ctx) => {
  const { code, first100Lines, lines } = ctx;

  const hasPackage = /^package\s+[a-z_]\w*$/m.test(first100Lines);
  const hasImport = /^\s*import\s+(?:\(|")/m.test(code);
  const hasFunc = /\bfunc\s+(?:\([^)]*\)\s*)?\w+(?:\[[^\]]+\])?\s*\(/.test(code);
  const hasStruct = /^type\s+\w+(?:\[[^\]]+\])?\s+struct\s*\{/m.test(code);
  const hasInterface = /^type\s+\w+(?:\[[^\]]+\])?\s+interface\s*\{/m.test(code);
  const hasGenericType = /^type\s+\w+\[[^\]]+\]\s+(?:struct\s*\{|map\[)/m.test(code);
  const hasTypeAlias = /^type\s+\w+\s*=\s*[\w\[\]*]+/m.test(code);
  const hasShortDecl = /(?:^|\n)\s*\w+(?:\s*,\s*\w+)*\s*:=\s*.+/.test(code);
  const hasMapLiteral = /(?:^|\n)\s*(?:var\s+\w+\s*=\s*)?map\[[^\]]+\](?:(?:\[[^\]]*\])*\*?\w+)?\s*\{/m.test(code);
  const hasStructTag = /`(?:json|xml|protobuf):"/.test(code);
  const hasIota = /\biota\b/.test(code);
  const hasGoRoutine = /\bgo\s+(?:func\s*\(|\w+\s*\()/.test(code);
  const hasSelect = /\bselect\s*\{/.test(code);
  const hasChannel = /<-/.test(code) || /\bchan(?:<-)?\b/.test(code);
  const hasMake = /\bmake\s*\(\s*(?:chan\b|map\s*\[)/.test(code);
  const hasSync = /\bsync\.(?:WaitGroup|Mutex|RWMutex|Once|Pool|Map)\b/.test(code) || /\bwg\.(?:Add|Done|Wait)\(/.test(code);
  const hasErrorFlow = /\bif\s+err\s*!=\s*nil\s*\{/.test(code) || /fmt\.Errorf\(/.test(code);
  const hasGoStdlibCall = /\b(?:fmt|http|io|os|time|context|errors|json|url|xml|gob|hex|base64|sha256|exec|strconv|sort|regexp|template)\.\w+\(/.test(code);

  if (lines.length <= 3) {
    if (/^\w+(?:\s*,\s*\w+)*\s*:=\s*(?![:=]).+$/.test(code.trim())) {
      return 'go';
    }

    if (/\bfmt\.(?:Print|Println|Printf|Sprint|Sprintf)\(/.test(code)) {
      return 'go';
    }
  }

  if (hasStruct || hasInterface || hasGenericType) {
    return 'go';
  }

  if (hasGoRoutine || hasSync) {
    return 'go';
  }

  if (hasChannel && (hasMake || hasSelect || /\bclose\s*\(/.test(code) || /\brange\s+\w+/.test(code))) {
    return 'go';
  }

  if (hasStructTag || /Code generated by protoc/.test(code) || /github\.com\/gogo\/protobuf/.test(code)) {
    return 'go';
  }

  if (hasErrorFlow && (hasShortDecl || /\bfunc\b/.test(code))) {
    return 'go';
  }

  if (!hasPackage) {
    if (lines.length <= 5 && hasStruct) {
      return 'go';
    }

    return null;
  }

  if (hasFunc || hasImport || hasIota || hasTypeAlias || hasMapLiteral || hasMake) {
    return 'go';
  }

  if (hasShortDecl && (hasGoStdlibCall || hasChannel || hasSelect)) {
    return 'go';
  }

  if (/\bfunc\s*\([^)]*\)\s*\w+(?:\[[^\]]+\])?\s*\(/.test(code)) {
    return 'go';
  }

  return null;
};
