import type { LanguageDetector } from '../types';

export const detectHaskell: LanguageDetector = (ctx) => {
  const { code, first100Lines, firstLine, lines } = ctx;

  // Haskell function with type signature
  if (/^\w+\s*::\s*[A-Z]/.test(first100Lines)) {
    return 'haskell';
  }

  // Haskell data type definition
  if (/^data\s+[A-Z]\w+\s*=/.test(first100Lines)) {
    if (/\bderiving\s*\(/.test(code) || /^\s*\|\s+[A-Z]\w+/.test(code)) {
      return 'haskell';
    }
  }

  // Haskell import with qualified
  if (/^import\s+(qualified\s+)?[A-Z][\w.]*/.test(first100Lines)) {
    // Not Python (Python uses lowercase module names)
    if (!/^import\s+\w+\s*$/.test(first100Lines) || /^import\s+[A-Z]/.test(first100Lines)) {
      return 'haskell';
    }
  }

  // Haskell Control.Monad pattern (very strong indicator)
  if (/^import\s+Control\.(Monad|Applicative|Functor)/.test(first100Lines)) {
    return 'haskell';
  }

  // Haskell data type with deriving
  if (/^data\s+[A-Z]\w+\s*=/.test(first100Lines) && /deriving\s*\(/.test(code)) {
    return 'haskell';
  }

  // Haskell Either and Maybe patterns (strong indicator)
  if (/\b(Either|Maybe|Just|Nothing|Left|Right)\s+[A-Z]/.test(code)) {
    if (/\bdo\b/.test(code) || /->/.test(code)) {
      return 'haskell';
    }
  }

  // Haskell record syntax with type annotations
  if (/\bdata\s+\w+\s*=\s*\w+\s*\{/.test(code) && /::\s*[A-Z]/.test(code)) {
    return 'haskell';
  }

  // Haskell pattern matching with where
  if (/\|\s+\w+\s+\w+\s*=/.test(code) && /\bwhere\b/.test(code)) {
    return 'haskell';
  }

  // Haskell IO type signature
  if (/::\s*\[.*\]\s*->\s*IO\s*\(\)/.test(code)) {
    return 'haskell';
  }

  if (/^#!.*\b(runhaskell|runghc|ghc)\b/.test(firstLine)) {
    return 'haskell';
  }

  if (/^(Nonterminals|Terminals)\b/m.test(first100Lines)) {
    return null;
  }

  if (/\b(proc|iterator|template|macro)\s+\w+/.test(first100Lines)) {
    return null;
  }

  if (/import\s+.*\s+from\s+['"]/.test(first100Lines)) {
    return null;
  }

  if (/\bdef\s+\w+/.test(first100Lines) && /\bend\b/.test(code)) {
    return null;
  }

  if (/\b(param|function|cmdletbinding|process|begin|end)\s*\(/i.test(first100Lines)) {
    return null;
  }
  if (/\$\w+/.test(first100Lines) && /\b(param|function)\b/i.test(first100Lines)) {
    return null;
  }

  if (/^module\s+\w+\s+exposing\s*\(/m.test(first100Lines)) {
    return null;
  }

  if (/^data\s+[A-Z]\w+(\s+\w+)?\s*=/m.test(first100Lines) && !/^(module|import)\s+/m.test(first100Lines)) {
    return null;
  }

  if (/^#!.*\brust\b/.test(firstLine)) {
    return null;
  }
  if (/\b(use\s+\w+::|fn\s+\w+\s*\(|let\s+mut\b|impl\b|pub\s+fn\b)\b/.test(first100Lines)) {
    return null;
  }

  if (/^package\s+\w+/m.test(first100Lines)) {
    return null;
  }
  if (/^func\s+\w+\s*\(/m.test(first100Lines)) {
    return null;
  }
  if (/Code generated by protoc/.test(first100Lines)) {
    return null;
  }
  // Exclude Go struct syntax
  if (/^type\s+\w+\s+struct\s*\{/m.test(code)) {
    return null;
  }

  if (/^(interface|type)\s+\w+\s*=\s*\{/.test(firstLine)) {
    return null;
  }

  if (/:\s*(string|number|boolean|void|any|unknown|never)\b/.test(first100Lines)) {
    return null;
  }

  if (/^module\s+[A-Z][\w.]*\s+(\(.*\)\s+)?where/m.test(code)) {
    return 'haskell';
  }

  if (/^import\s+qualified\s+[A-Z][\w.]*/m.test(first100Lines)) {
    return 'haskell';
  }

  if (/^main\s*::\s*IO\s*\(\)/m.test(code)) {
    return 'haskell';
  }

  if (/\bfoldr\s+\(\\/.test(code)) {
    return 'haskell';
  }

  if (/\bdata\s+\w+\s+\w+\s*=\s*\w+/.test(code)) {
    if (/\bderiving\s*\(/.test(code)) {
      return 'haskell';
    }
  }

  if (/<\$>|<\*>/.test(code)) {
    if (/\bJust\b/.test(code)) {
      return 'haskell';
    }
  }

  // Haskell list comprehension (must be early check)
  if (/\[\s*\w+\s*\^\s*\d+\s*\|\s*\w+\s*<-\s*\[/.test(code)) {
    // Haskell list comprehension with power operator
    return 'haskell';
  }

  if (/\[\s*\w+\s*\|\s*\w+\s*<-/.test(code)) {
    // Check if it's Haskell (not Julia)
    if (!/\bfor\s+\w+\s+in\s+\d+:\d+/.test(code) && !/\bfunction\b|\bend\b/.test(code)) {
      // Simple list comprehension pattern
      if (lines.length <= 3 && /^\w+\s*=\s*\[/.test(code.trim())) {
        return 'haskell';
      }
      // With where or let...in
      if (/\bwhere\b/.test(code) || /\blet\s+\w+\s*=.*\s+in\b/.test(code)) {
        return 'haskell';
      }
      // With range syntax [1..10]
      if (/\[\d+\.\.\d+\]/.test(code)) {
        return 'haskell';
      }
    }
  }

  if (/\bfmap\s+/.test(code) && />>=/.test(code)) {
    return 'haskell';
  }

  if (/^[a-z]\w*\s+[a-z]\w*(\s+[a-z]\w*)*\s*=\s*/.test(firstLine)) {
    if (lines.length <= 3 && !/\b(var|const|let|function|def|class|local)\b/.test(code)) {
      return 'haskell';
    }
  }

  // Simple Haskell expressions
  if (lines.length <= 3) {
    if (/^(sum|product|length|head|tail|take|drop|map|filter|foldr|foldl)\s+\[/.test(code.trim())) {
      return 'haskell';
    }
  }

  if (/^import\s+[A-Z][\w.]*/m.test(first100Lines)) {
    let haskellFeatures = 0;
    if (/::\s*[A-Z]/.test(code)) haskellFeatures++;
    if (/->/.test(code)) haskellFeatures++;
    if (/\bwhere\b/.test(code)) haskellFeatures++;
    if (/\bdo\b/.test(code)) haskellFeatures++;
    if (/\blet\s+\w+\s*=/.test(code)) haskellFeatures++;

    if (haskellFeatures >= 2) {
      return 'haskell';
    }
  }

  if (/::\s*[A-Z][\w\s]*/.test(code)) {
    let haskellKeywords = 0;
    if (/\bmain\b/.test(code)) haskellKeywords++;
    if (/\bwhere\b/.test(code)) haskellKeywords++;
    if (/\blet\b/.test(code)) haskellKeywords++;
    if (/\bin\b/.test(code)) haskellKeywords++;
    if (/\bcase\b/.test(code)) haskellKeywords++;
    if (/\bof\b/.test(code)) haskellKeywords++;
    if (/\bdata\b/.test(code)) haskellKeywords++;
    if (/\btype\b/.test(code)) haskellKeywords++;
    if (/\bnewtype\b/.test(code)) haskellKeywords++;
    if (/\bclass\b/.test(code)) haskellKeywords++;
    if (/\binstance\b/.test(code)) haskellKeywords++;

    if (haskellKeywords >= 2) {
      return 'haskell';
    }
  }

  if (/^(data|type|newtype)\s+[A-Z]\w+/m.test(code)) {
    return 'haskell';
  }

  if (/\bderiving\s*\(/.test(code)) {
    return 'haskell';
  }

  return null;
};
