import type { LanguageDetector } from '../types';

export const detectHaskell: LanguageDetector = (ctx) => {
  const { code, first100Lines, firstLine } = ctx;

  if (/^#!.*\b(runhaskell|runghc|ghc)\b/.test(firstLine)) {
    return 'haskell';
  }

  if (/^(Nonterminals|Terminals)\b/m.test(first100Lines)) {
    return null;
  }

  if (/\b(proc|iterator|template|macro)\s+\w+/.test(first100Lines)) {
    return null;
  }

  if (/import\s+.*\s+from\s+['"]/.test(first100Lines)) {
    return null;
  }

  if (/\bdef\s+\w+/.test(first100Lines) && /\bend\b/.test(code)) {
    return null;
  }

  if (/\b(param|function|cmdletbinding|process|begin|end)\s*\(/i.test(first100Lines)) {
    return null;
  }
  if (/\$\w+/.test(first100Lines) && /\b(param|function)\b/i.test(first100Lines)) {
    return null;
  }

  if (/^module\s+\w+\s+exposing\s*\(/m.test(first100Lines)) {
    return null;
  }

  if (/^data\s+[A-Z]\w+(\s+\w+)?\s*=/m.test(first100Lines) && !/^(module|import)\s+/m.test(first100Lines)) {
    return null;
  }

  if (/^#!.*\brust\b/.test(firstLine)) {
    return null;
  }
  if (/\b(use\s+\w+::|fn\s+\w+\s*\(|let\s+mut\b|impl\b|pub\s+fn\b)\b/.test(first100Lines)) {
    return null;
  }

  if (/^package\s+\w+/m.test(first100Lines)) {
    return null;
  }
  if (/^func\s+\w+\s*\(/m.test(first100Lines)) {
    return null;
  }
  if (/Code generated by protoc/.test(first100Lines)) {
    return null;
  }

  if (/^module\s+[A-Z][\w.]*\s+(\(.*\)\s+)?where/m.test(code)) {
    return 'haskell';
  }

  if (/^import\s+qualified\s+[A-Z][\w.]*/m.test(first100Lines)) {
    return 'haskell';
  }

  if (/^main\s*::\s*IO\s*\(\)/m.test(code)) {
    return 'haskell';
  }

  if (/^import\s+[A-Z][\w.]*/m.test(first100Lines)) {

    let haskellFeatures = 0;
    if (/::\s*[A-Z]/.test(code)) haskellFeatures++;
    if (/->/.test(code)) haskellFeatures++;
    if (/\bwhere\b/.test(code)) haskellFeatures++;
    if (/\bdo\b/.test(code)) haskellFeatures++;
    if (/\blet\s+\w+\s*=/.test(code)) haskellFeatures++;

    if (haskellFeatures >= 2) {
      return 'haskell';
    }
  }

  if (/::\s*[A-Z][\w\s]*/.test(code)) {

    let haskellKeywords = 0;
    if (/\bmain\b/.test(code)) haskellKeywords++;
    if (/\bwhere\b/.test(code)) haskellKeywords++;
    if (/\blet\b/.test(code)) haskellKeywords++;
    if (/\bin\b/.test(code)) haskellKeywords++;
    if (/\bcase\b/.test(code)) haskellKeywords++;
    if (/\bof\b/.test(code)) haskellKeywords++;
    if (/\bdata\b/.test(code)) haskellKeywords++;
    if (/\btype\b/.test(code)) haskellKeywords++;
    if (/\bnewtype\b/.test(code)) haskellKeywords++;
    if (/\bclass\b/.test(code)) haskellKeywords++;
    if (/\binstance\b/.test(code)) haskellKeywords++;

    if (haskellKeywords >= 2) {
      return 'haskell';
    }
  }

  if (/^(data|type|newtype)\s+[A-Z]\w+/m.test(code)) {
    return 'haskell';
  }

  if (/\bderiving\s*\(/.test(code)) {
    return 'haskell';
  }

  return null;
};
