import type { LanguageDetector } from '../types';

export const detectJavaScript: LanguageDetector = (ctx) => {
  const { sample, first100Lines, firstLine, hasCurlyBraces, hasSemicolon, hasImport, hasConst, hasLet, hasFunction, code } = ctx;

  if (/^\\(name|alias|title|usage|arguments|value|description|details|docType)\{/m.test(first100Lines)) {
    return null;
  }

  if (sample.includes('<?php') ||
      sample.includes('#include <') ||
      /^package\s+\w+;/m.test(first100Lines) ||
      /\b(public\s+class|private\s+class|protected\s+class)\b/.test(first100Lines) ||
      /\b(fn\s+main|let\s+mut|impl\s+|pub\s+fn)\b/.test(first100Lines)) {
    return null;
  }

  // Exclude Objective-C files
  if (/#import\s+["<]/.test(first100Lines) &&
      (/@(interface|implementation|property|protocol)\b/.test(code) ||
       /\bNS[A-Z]\w+\s*\*/.test(first100Lines) ||
       /#import\s+<(Foundation|UIKit|CoreFoundation|CFNetwork)\//.test(first100Lines))) {
    return null;
  }

  if (/\b(proc|iterator|template|macro)\s+\w+/.test(first100Lines)) {
    return null;
  }

  if (/^class\s+\w+/m.test(code)) {

    if (/->|=>/.test(code) || /constructor:\s*\([^)]*@/.test(code) || /@\w+/.test(code)) {
      return null;
    }
  }

  if (/->|=>/.test(code) && /@\w+/.test(code) && !/\bfunction\b/.test(first100Lines)) {

    if (/\b(import|export)\s+/.test(first100Lines) ||
        /:\s*\w+\s*[=;)]/.test(first100Lines) ||
        /\b(interface|type|abstract|implements)\b/.test(first100Lines)) {

    } else {
      return null;
    }
  }

  if (/^#!.*crystal/.test(firstLine) ||
      /require\s+["'].*spec_helper["']/.test(first100Lines) ||
      (/\bdescribe\s+["']/.test(code) && /\.should\s+(eq|be_true|be_false|be_nil)/.test(code))) {
    return null;
  }

  if (/^package\s+\w+$/m.test(first100Lines)) {

    if (/\bfunc\s+\w+\s*\(/.test(first100Lines) ||
        /\btype\s+\w+\s+struct/.test(first100Lines) ||
        /protobuf:"/.test(first100Lines) ||
        /Code generated by protoc/.test(first100Lines)) {
      return null;
    }
  }

  if (/\b(CREATE\s+TABLE|INSERT\s+INTO|SELECT\s+.*\s+FROM|DROP\s+TABLE|SHOW\s+WARNINGS|GRANT\s+\w+\s+TO)\b/i.test(first100Lines)) {
    return null;
  }

  if (/<-/.test(first100Lines) && /\b(library|function|data\.frame)\b/.test(first100Lines)) {

    if (!/\/\/.*<-|\/\*.*<-/.test(first100Lines)) {
      return null;
    }
  }

  if (/^function\s+\w+\s*\(/m.test(first100Lines) && /\bend\b/.test(code)) {

    if (!/\b(var|const|let)\s+\w+\s*=/.test(first100Lines) &&
        !/\bObject\.(defineProperty|create|setPrototypeOf)/.test(first100Lines)) {
      return null;
    }
  }

  if (/^function\s+\w+\s*=\s*\w+\s*\(/m.test(first100Lines) || (/^%\s/m.test(first100Lines) && /\bfunction\b/.test(first100Lines))) {
    return null;
  }

  if (/^(import|module)\s+[A-Z][\w.]*\s+exposing/m.test(first100Lines)) {
    return null;
  }

  const capitalizedImports = (first100Lines.match(/^import\s+[A-Z][\w.]*\s*$/gm) || []).length;
  if (capitalizedImports >= 2) {
    return null;
  }

  if (/^use\s+(strict|warnings|v\d+)/.test(first100Lines) || /^package\s+[\w:]+;/.test(first100Lines)) {
    return null;
  }

  if (/\b(let\s+\w+\s*=|module\s+\w+\s*=|open\s+\w+)\b/.test(first100Lines) && /\bin\b/.test(code)) {
    return null;
  }

  if (/\b(require\s+["']|property\s+\w+|getter\s+\w+|setter\s+\w+)\b/.test(first100Lines)) {
    return null;
  }

  if (/^(set|let|function|if|endif|colorscheme)\s+/.test(first100Lines)) {
    return null;
  }

  if (/^"\s/m.test(first100Lines) &&
      (/\b(function!|endfunction|call\s+\w+|set\s+\w+|let\s+[gbslwtav]:)\b/.test(first100Lines) ||
       /UseVimball/.test(first100Lines))) {
    return null;
  }

  if (firstLine.includes('<?xml')) {
    return null;
  }

  if (firstLine.includes('<Query Kind=')) {
    return null;
  }

  if (/\bArgument<\w+>/.test(first100Lines)) {
    return null;
  }

  if (/\b(MACRO|ENDMACRO|FUNCTION|ENDFUNCTION|FOREACH|ENDFOREACH|WHILE|ENDWHILE)\s*\(/g.test(first100Lines) ||
      /CMAKE_/.test(first100Lines)) {
    return null;
  }

  if (/\blocal\s+\w+/.test(first100Lines)) {
    return null;
  }

  if (/^---\s*$/.test(firstLine) && /^#{1,6}\s+/m.test(first100Lines)) {
    return null;
  }

  const headerMatches = first100Lines.match(/^#{1,6}\s+/gm);
  if (headerMatches && headerMatches.length >= 2) {
    return null;
  }

  if (/\{%[\s\S]*?%\}/.test(first100Lines) && /\{\{[\s\S]*?\|/.test(first100Lines)) {
    return null;
  }

  if (/\bconstructor\s*\(\s*(public|private|protected)\s+\w+\s*\)/.test(first100Lines)) {
    return 'typescript';
  }

  if (/\bfunction\s+\w+\s*\([\s\S]*?:\s*(string|number|boolean|any|void|Promise|Array)/.test(first100Lines)) {
    return 'typescript';
  }

  if (/\(\s*\w+:\s*(string|number|boolean|any|void|Promise|Array)[^)]*\)\s*(:|=>)/.test(first100Lines)) {
    return 'typescript';
  }

  if (/\bexport\s+function\s+\w+\s*\([\s\S]*?:\s*\w+/.test(first100Lines)) {
    return 'typescript';
  }

  const tsIndicators = [
    /\binterface\s+\w+\s*\{/.test(first100Lines),
    /\btype\s+\w+\s*=/.test(first100Lines),
    /\bexport\s+type\s+\w+/.test(first100Lines),
    /\babstract\s+class\b/.test(first100Lines),
    /\bimplements\s+\w+/.test(first100Lines),
    /\b(public|private|protected)\s+(readonly\s+)?\w+:\s*\w+/.test(first100Lines),
    /\b(public|private|protected)\s+abstract\s+\w+/.test(first100Lines),
    /<T>|<T,|<\w+>/.test(first100Lines),
    /:\s*(Promise<|Array<)/.test(first100Lines)
  ].filter(Boolean).length;

  if (tsIndicators >= 2) {
    return 'typescript';
  }

  if ((/<[A-Z]\w+/.test(first100Lines) || /return\s*\(?\s*<[a-z]+/.test(first100Lines)) &&
      !/#import\s+</.test(first100Lines)) {
    if (tsIndicators >= 1 || sample.includes('interface ')) {
      return 'tsx';
    }
    return 'jsx';
  }

  if (/\b(console\.(log|error|warn|info)|alert|document\.|window\.|require\(|module\.exports)\b/.test(first100Lines)) {

    if (ctx.lines.length <= 3 && /^console\.log\(/.test(first100Lines.trim())) {
      return 'typescript';
    }
    return 'javascript';
  }

  if (/\b(import\.meta|await\s+Promise|await\s+\w+\()\b/.test(first100Lines)) {

    if (/\bexport\s+(function|const|class|default|type|interface)/.test(first100Lines)) {

      if (tsIndicators >= 1 || /:\s*\w+\s*[=;)]/.test(first100Lines)) {
        return 'typescript';
      }
      return 'javascript';
    }
  }

  if (!hasCurlyBraces && !hasSemicolon && !hasImport && !hasConst && !hasLet && !hasFunction) {
    return null;
  }

  const jsScore = (
    (hasImport && /^import\s+/.test(firstLine) ? 2 : 0) +
    ((hasConst || hasLet) ? 1 : 0) +
    (hasFunction || /=>\s*\{/.test(first100Lines) || /function\s+\w+\s*\(/.test(first100Lines) ? 2 : 0) +
    (/\b(console\.|document\.|window\.|require\(|module\.exports|exports\.|async\s+function|await\s+|Object\.|Array\.|alert\()\b/.test(first100Lines) ? 2 : 0) +
    (hasCurlyBraces && hasSemicolon ? 1 : 0) +
    (/\bvar\s+\w+\s*=/.test(first100Lines) ? 1 : 0) +
    (/!\s*function\s*\(/.test(first100Lines) ? 2 : 0) +
    (/\$\s*\(/.test(first100Lines) ? 1 : 0) +
    (/\bexport\s+(function|const|class|default)/.test(first100Lines) ? 2 : 0) +
    (/\bimport\.meta\b/.test(first100Lines) ? 2 : 0)
  );

  if (jsScore >= 2) {
    return 'javascript';
  }

  return null;
};
