import type { DetectionContext } from '../types';

export function shouldRejectBeforeJavaScriptSignals(ctx: DetectionContext): boolean {
  const { code, first100Lines } = ctx;

  if (/^#{1,6}\s+/m.test(first100Lines) && /```\w*/.test(code)) {
    return true;
  }

  if (/^require(?:_relative)?\s+['"]/m.test(first100Lines)) {
    return true;
  }

  if (/^import\s+(?:static\s+)?(?:java|javax|jakarta|org\.(?:springframework|junit|apache|jooq)|com\.(?:fasterxml|google|intellij)|lombok|javafx)\./m.test(first100Lines)) {
    return true;
  }

  if (/^(?:from\s+[._a-z][\w.]*\s+import\s+|import\s+(?:os|sys|re|json|datetime|pathlib|typing|collections|itertools|functools|contextlib|decimal|fractions|subprocess|tempfile|uuid|logging|pytest|unittest|django|fastapi|pydantic|sqlite3|httpx|requests|argparse|click|rich)\b)/m.test(first100Lines)) {
    return true;
  }

  if (/^\s*task\s+['"][^'"]+['"]\s*,\s*->/m.test(first100Lines) || /\bconsole\.(?:log|error|warn|info)\s+['"]/m.test(code)) {
    return true;
  }

  return false;
}

export function shouldRejectAfterJavaScriptSignals(ctx: DetectionContext): boolean {
  const { code, first100Lines, firstLine, sample } = ctx;

  if (/^\\(name|alias|title|usage|arguments|value|description|details|docType)\{/m.test(first100Lines)) {
    return true;
  }

  if (/^#include\s*[<"]/m.test(first100Lines) || /^#\s*(define|ifdef|ifndef|elif|else|endif)\b/m.test(first100Lines) || /\b(public|private|protected):\s*$/m.test(code) || /\b(enum\s+class|virtual|override|noexcept|constexpr)\b/.test(code) || /\btemplate\s*</.test(code) || /\boperator\s*(?:[+\-*/%<>=!]+|\(\)|\[\])/.test(code) || /\bstd::/.test(code) || /\b(typedef\s+struct|typedef\s+void\s*\(\*|union\s+\w+\s*\{|restrict\b|volatile\b|extern\s+\w|static\s+inline)\b/.test(code) || /^struct\s+\w+\s*\{/m.test(code) || /^enum\s+\w+\s*\{/m.test(code) || /\bconst\s+char\s*\*/.test(code) || /\bunsigned\s+long\b/.test(code) || /\b(?:int|char|float|double|short|long|unsigned|signed|void)\s+\**\w+\s*\([^)]*\)\s*\{/.test(code)) {
    return true;
  }

  if (sample.includes('<?php') ||
    sample.includes('#include <') ||
    /^package\s+\w+;/m.test(first100Lines) ||
    /\b(public\s+class|private\s+class|protected\s+class)\b/.test(first100Lines) ||
    /\b(fn\s+main|let\s+mut|impl\s+|pub\s+fn)\b/.test(first100Lines)) {
    return true;
  }

  if (/#import\s+["<]/.test(first100Lines) &&
    (/@(interface|implementation|property|protocol)\b/.test(code) ||
      /\bNS[A-Z]\w+\s*\*/.test(first100Lines) ||
      /#import\s+<(Foundation|UIKit|CoreFoundation|CFNetwork)\//.test(first100Lines))) {
    return true;
  }

  if (/\b(proc|iterator|template|macro)\s+\w+/.test(first100Lines)) {
    return true;
  }

  if (/^task\s+['"]/.test(first100Lines) && /->/.test(code)) {
    return true;
  }

  if (/\b(Get|Set|New|Remove|Add|Clear|Write|Read|Test|Start|Stop|Invoke|Import|Export)-[A-Z]\w+/.test(code)) {
    return true;
  }

  if (/^\s*param\s*\(/m.test(code) && /\$[\w]+/.test(code)) {
    return true;
  }

  if (/\bfunction\s+\w+\s*\([^)]*\$\w+/.test(first100Lines) ||
    /^namespace\s+[A-Z]\w*(\\[A-Z]\w*)*;$/m.test(first100Lines) ||
    /\breturn\s+\$\w+;/.test(code)) {
    return true;
  }

  if (/^class\s+\w+/m.test(code)) {
    if (/->|=>/.test(code) || /constructor:\s*\([^)]*@/.test(code) || /@\w+/.test(code)) {
      return true;
    }
  }

  if (/^#!.*crystal/.test(firstLine) ||
    /require\s+["'].*spec_helper["']/.test(first100Lines) ||
    (/\bdescribe\s+["']/.test(code) && /\.should\s+(eq|be_true|be_false|be_nil)/.test(code))) {
    return true;
  }

  if (/^package\s+\w+$/m.test(first100Lines)) {
    if (/\bfunc\s+\w+\s*\(/.test(first100Lines) ||
      /\btype\s+\w+\s+struct/.test(first100Lines) ||
      /protobuf:"/.test(first100Lines) ||
      /Code generated by protoc/.test(first100Lines)) {
      return true;
    }
  }

  if (/\b(CREATE\s+TABLE|INSERT\s+INTO|SELECT\s+.*\s+FROM|DROP\s+TABLE|SHOW\s+WARNINGS|GRANT\s+\w+\s+TO)\b/i.test(first100Lines)) {
    return true;
  }

  if (/<-/.test(first100Lines) && /\b(library|function|data\.frame)\b/.test(first100Lines)) {
    if (!/\/\/.*<-|\/\*.*<-/.test(first100Lines)) {
      return true;
    }
  }

  if (/^function\s+\w+\s*\(/m.test(first100Lines) && /\bend\b/.test(code)) {
    if (!/\b(var|const|let)\s+\w+\s*=/.test(first100Lines) &&
      !/\bObject\.(defineProperty|create|setPrototypeOf)/.test(first100Lines)) {
      return true;
    }
  }

  if (/^function\s+\w+\s*=\s*\w+\s*\(/m.test(first100Lines) || (/^%\s/m.test(first100Lines) && /\bfunction\b/.test(first100Lines))) {
    return true;
  }

  if (/^(import|module)\s+[A-Z][\w.]*\s+exposing/m.test(first100Lines)) {
    return true;
  }

  const capitalizedImports = (first100Lines.match(/^import\s+[A-Z][\w.]*\s*$/gm) || []).length;
  if (capitalizedImports >= 2) {
    return true;
  }

  if (/^use\s+(strict|warnings|v\d+)/.test(first100Lines) || /^package\s+[\w:]+;/.test(first100Lines)) {
    return true;
  }

  if (/\b(let\s+\w+\s*=|module\s+\w+\s*=|open\s+\w+)\b/.test(first100Lines) && /\bin\b/.test(code)) {
    return true;
  }

  if (/\b(require\s+["']|property\s+\w+|getter\s+\w+|setter\s+\w+)\b/.test(first100Lines)) {
    return true;
  }

  if (/^(set|let|if|endif|colorscheme)\s+/.test(first100Lines)) {
    return true;
  }

  if (/^function!\s+/.test(first100Lines)) {
    return true;
  }

  if (/^"\s/m.test(first100Lines) &&
    (/\b(function!|endfunction|call\s+\w+|set\s+\w+|let\s+[gbslwtav]:)\b/.test(first100Lines) ||
      /UseVimball/.test(first100Lines))) {
    return true;
  }

  if (firstLine.includes('<?xml')) {
    return true;
  }

  if (firstLine.includes('<Query Kind=')) {
    return true;
  }

  if (/\bArgument<\w+>/.test(first100Lines)) {
    return true;
  }

  if (/\b(MACRO|ENDMACRO|FUNCTION|ENDFUNCTION|FOREACH|ENDFOREACH|WHILE|ENDWHILE)\s*\(/g.test(first100Lines) ||
    /CMAKE_/.test(first100Lines)) {
    return true;
  }

  if (/\blocal\s+\w+\s*=/.test(first100Lines)) {
    return true;
  }

  if (/^---\s*$/.test(firstLine) && /^#{1,6}\s+/m.test(first100Lines)) {
    return true;
  }

  const headerMatches = first100Lines.match(/^#{1,6}\s+/gm);
  if (headerMatches && headerMatches.length >= 2) {
    return true;
  }

  if (/\{%[\s\S]*?%\}/.test(first100Lines) && /\{\{[\s\S]*?\|/.test(first100Lines)) {
    return true;
  }

  return false;
}
