import { DEFAULT_PROSE_DOC_SCAN_NODE_LIMIT } from '../shared/boundedProseNodeScan';

export const MAX_APPLIED_PREVIEW_DOM_SCAN_ELEMENTS = 20_000;
export const MAX_APPLIED_PREVIEW_MATCHED_ELEMENTS = 5_000;
export const MAX_APPLIED_PREVIEW_CODE_BLOCK_SCAN_NODES = DEFAULT_PROSE_DOC_SCAN_NODE_LIMIT;
export const MAX_APPLIED_PREVIEW_TRAILING_BREAK_NODES = DEFAULT_PROSE_DOC_SCAN_NODE_LIMIT;
export const MAX_APPLIED_PREVIEW_TRAILING_BREAK_DEPTH = 512;
