import { DEFAULT_PROSE_DOC_SCAN_NODE_LIMIT } from '../shared/boundedProseNodeScan';

export const MAX_BLOCK_COMMAND_DOM_SELECTION_CHILDREN = 5_000;
export const MAX_BLOCK_COMMAND_SELECTION_SCAN_NODES = DEFAULT_PROSE_DOC_SCAN_NODE_LIMIT;
export const MAX_BLOCK_COMMAND_NODE_UPDATES = 5_000;
export const MAX_CODE_BLOCK_CONVERSION_TEXT_CHARS = 1024 * 1024;
