import type { EditorState } from '@milkdown/kit/prose/state';
import type { EditorView } from '@milkdown/kit/prose/view';
import { themeStyleResetTokens } from '@/styles/themeTokens';
import {
  cleanupAppliedPreviewDocument,
  createAppliedPreviewState,
  renderAppliedPreviewDocument,
} from './appliedPreviewState';
import {
  MAX_APPLIED_PREVIEW_DOC_SIZE,
  MAX_APPLIED_PREVIEW_DOM_ELEMENTS,
  TOOLBAR_SELECTION_HIDDEN_PREVIEW_CLASS,
} from './previewStyleConstants';
import { clearNativeSelectionForPreview } from './previewNativeSelection';
import { capturePreviewScrollSnapshot, restorePreviewScrollSnapshot } from './previewScroll';
import { previewStyleState } from './previewStyleState';

export function hasActiveAppliedPreview(view: EditorView): boolean {
  return Boolean(
    (previewStyleState.previewOverlay && previewStyleState.previewOverlay.viewDom === view.dom) ||
    (previewStyleState.selectionColorPreview && previewStyleState.selectionColorPreview.viewDom === view.dom)
  );
}

export function hasMatchingPreview(view: EditorView, key: string): boolean {
  return Boolean(
    previewStyleState.previewOverlay &&
    previewStyleState.previewOverlay.viewDom === view.dom &&
    previewStyleState.previewOverlay.key === key &&
    view.state.doc.eq(previewStyleState.previewOverlay.originalDoc)
  );
}

function canRenderAppliedPreview(view: EditorView): boolean {
  const docSize = view.state.doc.content.size;
  if (typeof docSize !== 'number' || docSize > MAX_APPLIED_PREVIEW_DOC_SIZE) {
    return false;
  }

  if (!(view.dom instanceof HTMLElement)) {
    return true;
  }

  const walker = view.dom.ownerDocument.createTreeWalker(view.dom, 1);
  let scanned = 0;
  while (walker.nextNode()) {
    scanned += 1;
    if (scanned > MAX_APPLIED_PREVIEW_DOM_ELEMENTS) {
      return false;
    }
  }

  return true;
}

function createAppliedPreviewDom(
  view: EditorView,
  apply: (previewView: EditorView) => void
): { dom: HTMLElement; state: EditorState } | null {
  if (!(view.dom instanceof HTMLElement)) {
    return null;
  }

  const previewState = createAppliedPreviewState(view, apply);

  if (previewState.doc.eq(view.state.doc)) {
    return null;
  }

  // Toolbar previews must be generated by applying the real editor command to
  // a shadow state. Do not reintroduce hand-written DOM/CSS simulations here:
  // preview markup should match the eventual applied document, including node
  // views rehydrated by renderAppliedPreviewDocument.
  return {
    dom: renderAppliedPreviewDocument(previewState, view.dom, view.dom.ownerDocument, undefined, view),
    state: previewState,
  };
}

export function renderAppliedPreview(
  view: EditorView,
  key: string,
  apply: (previewView: EditorView) => void
): boolean {
  if (!(view.dom instanceof HTMLElement) || !(view.dom.parentElement instanceof HTMLElement)) {
    void key;
    return false;
  }

  if (!canRenderAppliedPreview(view)) {
    clearPreviewOverlay();
    return false;
  }

  if (hasMatchingPreview(view, key)) {
    return true;
  }

  clearPreviewOverlay();

  const preview = createAppliedPreviewDom(view, apply);
  if (!preview) {
    return renderSelectionHiddenPreview(view, key);
  }

  const scrollSnapshot = capturePreviewScrollSnapshot(view.dom);
  const parent = view.dom.parentElement;
  const previewDom = preview.dom;
  previewDom.classList.add('toolbar-applied-preview-overlay', TOOLBAR_SELECTION_HIDDEN_PREVIEW_CLASS);
  previewDom.style.pointerEvents = themeStyleResetTokens.pointerEventsNone;
  previewDom.style.setProperty('overflow-anchor', 'none');

  previewStyleState.previewOverlay = {
    key,
    node: previewDom,
    originalDoc: view.state.doc,
    originalViewDisplay: view.dom.style.display,
    previewState: preview.state,
    viewDom: view.dom,
  };

  parent.insertBefore(previewDom, view.dom);
  view.dom.style.display = themeStyleResetTokens.displayNone;
  view.dom.setAttribute('data-toolbar-preview-hidden', 'true');
  restorePreviewScrollSnapshot(scrollSnapshot);
  clearNativeSelectionForPreview(view);
  return true;
}

export function renderSelectionHiddenPreview(view: EditorView, key: string): boolean {
  if (!(view.dom instanceof HTMLElement) || !(view.dom.parentElement instanceof HTMLElement)) {
    void key;
    return false;
  }

  if (!canRenderAppliedPreview(view)) {
    clearPreviewOverlay();
    return false;
  }

  if (hasMatchingPreview(view, key)) {
    return true;
  }

  clearPreviewOverlay();

  const scrollSnapshot = capturePreviewScrollSnapshot(view.dom);
  const previewDom = renderAppliedPreviewDocument(view.state, view.dom, view.dom.ownerDocument);
  previewDom.classList.add('toolbar-applied-preview-overlay', TOOLBAR_SELECTION_HIDDEN_PREVIEW_CLASS);
  previewDom.style.pointerEvents = themeStyleResetTokens.pointerEventsNone;
  previewDom.style.setProperty('overflow-anchor', 'none');

  previewStyleState.previewOverlay = {
    key,
    node: previewDom,
    originalDoc: view.state.doc,
    originalViewDisplay: view.dom.style.display,
    previewState: view.state,
    viewDom: view.dom,
  };

  view.dom.parentElement.insertBefore(previewDom, view.dom);
  view.dom.style.display = themeStyleResetTokens.displayNone;
  view.dom.setAttribute('data-toolbar-preview-hidden', 'true');
  restorePreviewScrollSnapshot(scrollSnapshot);
  clearNativeSelectionForPreview(view);
  return true;
}

export function clearPreviewOverlay(): boolean {
  if (!previewStyleState.previewOverlay) {
    return false;
  }

  const { node, originalViewDisplay, viewDom } = previewStyleState.previewOverlay;
  const scrollSnapshot = capturePreviewScrollSnapshot(viewDom);
  cleanupAppliedPreviewDocument(node);
  node.remove();
  if (viewDom.isConnected) {
    viewDom.style.display = originalViewDisplay;
    viewDom.removeAttribute('data-toolbar-preview-hidden');
  }
  previewStyleState.previewOverlay = null;
  restorePreviewScrollSnapshot(scrollSnapshot);
  return true;
}
