import type { VlainaThemeMapping } from './types';
import { VLAINA_FONT_THEME_MAPPINGS } from './fontMappings';

export const VLAINA_COLOR_THEME_MAPPINGS: VlainaThemeMapping[] = [
  { target: '--vlaina-color-surface-main', sources: ['--vlaina-imported-app-background', '--db', '--bg-color', '--background-primary'] },
  { target: '--vlaina-color-surface-menu', sources: ['--pn-c', '--db-ext', '--bg-color', '--vlaina-imported-app-background', '--background-primary-alt'] },
  { target: '--vlaina-color-surface-secondary', sources: ['--pn-c', '--element-color-soo-shallow', '--code-block-bg', '--background-secondary'] },
  { target: '--vlaina-color-surface-tertiary', sources: ['--pn-c-a', '--element-color-so-shallow', '--item-hover-bg-color', '--background-modifier-hover'] },
  { target: '--vlaina-color-surface-hover', sources: ['--bq-bg-fd', '--item-hover-bg-color', '--element-color-soo-shallow', '--nav-item-background-hover', '--background-modifier-hover', '--interactive-hover'] },
  { target: '--vlaina-color-surface-active', sources: ['--v-selected-c', '--active-file-bg-color', '--select-text-bg-color', '--nav-item-background-active', '--background-modifier-active', '--background-modifier-active-hover', '--interactive-normal'] },
  { target: '--vlaina-color-surface-row-hover', sources: ['--bq-bg-fd', '--item-hover-bg-color', '--element-color-soo-shallow', '--nav-item-background-hover', '--background-modifier-hover'] },
  { target: '--vlaina-color-surface-row-active', sources: ['--v-selected-c', '--active-file-bg-color', '--select-text-bg-color', '--nav-item-background-active', '--background-modifier-active'] },
  { target: '--vlaina-color-surface-empty', sources: ['--pn-c', '--element-color-soo-shallow', '--background-secondary-alt', '--background-secondary'] },
  { target: '--vlaina-color-input-surface', sources: ['--db', '--bg-color', '--background-modifier-form-field', '--background-primary'] },
  { target: '--vlaina-color-provider-input', sources: ['--pn-c', '--background-modifier-form-field', '--background-secondary'] },
  { target: '--vlaina-color-floating-surface', sources: ['--db', '--bg-color', '--background-primary'] },
  { target: '--vlaina-color-floating-surface-translucent', sources: ['--bq-bg', '--background-secondary'] },
  { target: '--vlaina-color-panel-muted', sources: ['--bq-bg-fd', '--element-color-soo-shallow', '--item-hover-bg-color', '--background-modifier-hover', '--background-secondary-alt'] },
  { target: '--vlaina-color-row-soft', sources: ['--bq-bg-fd', '--element-color-soo-shallow', '--item-hover-bg-color', '--background-modifier-hover'] },
  { target: '--vlaina-color-text-strong', sources: ['--df', '--text-color', '--appui-color-text', '--text-normal'] },
  { target: '--vlaina-color-text-primary', sources: ['--df', '--text-color', '--appui-color-text', '--text-normal'] },
  { target: '--vlaina-color-text-sidebar', sources: ['--df', '--appui-color-text', '--text-color', '--text-normal'] },
  { target: '--vlaina-color-text-hover', sources: ['--df', '--text-color', '--appui-color-text', '--text-normal'] },
  { target: '--vlaina-color-text-secondary', sources: ['--df-a', '--text-color-secondary', '--appui-color-text', '--text-muted'] },
  { target: '--vlaina-color-text-muted', sources: ['--df-a', '--text-color-secondary', '--appui-color-text', '--text-muted'] },
  { target: '--vlaina-color-text-soft', sources: ['--df-a', '--text-color-secondary', '--text-faint'] },
  { target: '--vlaina-color-text-tertiary', sources: ['--df-a', '--text-color-secondary', '--text-faint'] },
  { target: '--vlaina-color-text-disabled', sources: ['--df-a', '--text-color-secondary', '--text-faint'] },
  { target: '--vlaina-color-sidebar-pin', sources: ['--df-a', '--text-color-secondary', '--appui-color-icon', '--text-muted'] },
  { target: '--vlaina-color-muted-icon', sources: ['--df-a', '--text-color-secondary', '--appui-color-icon', '--text-muted', '--icon-color'] },
  { target: '--vlaina-color-border', sources: ['--pn-c-a', '--border-color', '--element-color-shallow', '--background-modifier-border'] },
  { target: '--vlaina-color-border-shell', sources: ['--pn-c-a', '--border-color', '--element-color-shallow', '--background-modifier-border'] },
  { target: '--vlaina-color-menu-border', sources: ['--pn-c-a', '--border-color', '--element-color-shallow', '--background-modifier-border'] },
  { target: '--vlaina-color-subtle-border', sources: ['--pn-c-a', '--border-color', '--element-color-shallow', '--background-modifier-border'] },
  { target: '--vlaina-color-subtle-border-strong', sources: ['--pn-c-a', '--border-color', '--element-color-deep', '--background-modifier-border-hover', '--background-modifier-border'] },
  { target: '--vlaina-color-panel-border', sources: ['--pn-c-a', '--border-color', '--element-color-shallow', '--background-modifier-border'] },
  { target: '--vlaina-color-accent', sources: ['--a-c', '--primary-color', '--appui-color', '--element-color', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-color-accent-hover', sources: ['--a-o-c', '--element-color-deep', '--secondary-color', '--interactive-accent-hover', '--text-accent-hover'] },
  { target: '--vlaina-color-accent-soft', sources: ['--v-selected-c', '--select-text-bg-color', '--element-color-so-shallow', '--text-selection', '--background-modifier-active'] },
  { target: '--vlaina-color-accent-light', sources: ['--v-selected-c', '--select-text-bg-color', '--element-color-soo-shallow', '--text-selection', '--background-modifier-active'] },
  { target: '--vlaina-color-accent-muted-bg', sources: ['--v-selected-c', '--text-selection', '--background-modifier-active'] },
  { target: '--vlaina-color-accent-soft-bg', sources: ['--v-selected-c', '--text-selection', '--background-modifier-active'] },
  { target: '--vlaina-color-accent-panel-bg', sources: ['--v-selected-c', '--text-selection', '--background-modifier-active'] },
  { target: '--vlaina-color-accent-border-muted', sources: ['--a-c', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-color-accent-border-hover', sources: ['--a-o-c', '--interactive-accent-hover', '--text-accent-hover'] },
  { target: '--vlaina-color-accent-focus-ring', sources: ['--v-selected-c', '--text-selection', '--background-modifier-active'] },
  { target: '--vlaina-color-sidebar-focus-ring', sources: ['--v-selected-c', '--text-selection', '--background-modifier-active'] },
  { target: '--vlaina-color-caret', sources: ['--a-c', '--primary-color', '--appui-color', '--element-color', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-color-selection', sources: ['--v-selected-c', '--select-text-bg-color', '--text-selection', '--mark-bg'] },
  { target: '--vlaina-color-editor-block-selection-bg', sources: ['--v-selected-c', '--select-text-bg-color', '--text-selection'] },
  { target: '--vlaina-color-editor-block-selection-handle', sources: ['--df', '--text-color', '--text-normal'] },
  { target: '--vlaina-color-mark-highlight-bg', sources: ['--mark-bg', '--text-highlight-bg', '--color-yellow'] },
  { target: '--vlaina-color-mark-highlight-fg', sources: ['--df', '--text-normal'] },
  { target: '--vlaina-color-find-match-bg', sources: ['--mark-bg', '--text-highlight-bg', '--color-yellow'] },
  { target: '--vlaina-color-find-match-active-bg', sources: ['--ac-ye', '--color-yellow'] },
  { target: '--vlaina-color-scrollbar-thumb', sources: ['--pn-c-a', '--element-color', '--appui-color', '--scrollbar-thumb-bg', '--background-modifier-border'] },
  { target: '--vlaina-color-scrollbar-thumb-hover', sources: ['--a-c', '--element-color-shallow', '--appui-color', '--scrollbar-active-thumb-bg', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-color-setting-panel', sources: ['--db-ext', '--db', '--bg-color', '--background-primary'] },
  { target: '--vlaina-color-setting-content', sources: ['--bq-bg-fd', '--element-color-soo-shallow', '--code-block-bg', '--background-secondary'] },
  { target: '--vlaina-color-setting-control', sources: ['--pn-c', '--element-color-soo-shallow', '--item-hover-bg-color', '--background-secondary', '--interactive-normal'] },
  { target: '--vlaina-color-setting-control-active', sources: ['--v-selected-c', '--nav-item-background-active', '--background-modifier-active', '--db', '--background-primary', '--interactive-accent'] },
  { target: '--vlaina-color-setting-field', sources: ['--db-ext', '--db', '--bg-color', '--background-modifier-form-field', '--background-primary'] },
  { target: '--vlaina-color-pill-surface', sources: ['--db', '--bg-color', '--background-primary', '--interactive-normal'] },
  { target: '--vlaina-color-pill-surface-hover', sources: ['--pn-c', '--bq-bg-fd', '--element-color-soo-shallow', '--item-hover-bg-color', '--nav-item-background-hover', '--background-modifier-hover', '--interactive-hover'] },
  { target: '--vlaina-color-control-hover-bg', sources: ['--bq-bg-fd', '--item-hover-bg-color', '--element-color-soo-shallow', '--nav-item-background-hover', '--background-modifier-hover', '--interactive-hover'] },
  { target: '--vlaina-color-control-hover-fg', sources: ['--df', '--element-color-deep', '--appui-color', '--nav-item-color-hover', '--text-normal'] },
  { target: '--vlaina-color-control-ring', sources: ['--a-c', '--primary-color', '--appui-color', '--element-color', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-color-control-ring-offset', sources: ['--db', '--bg-color', '--background-primary'] },
  { target: '--vlaina-color-titlebar-button', sources: ['--df-a', '--titlebar-text-color', '--text-muted'] },
  { target: '--vlaina-color-titlebar-button-hover', sources: ['--df', '--titlebar-text-color-focused', '--text-normal'] },
  { target: '--vlaina-color-titlebar-button-active', sources: ['--df', '--titlebar-text-color-focused', '--text-normal'] },
  { target: '--vlaina-color-tab-active-fg', sources: ['--df', '--tab-text-color-focused-active-current', '--tab-text-color-focused-active', '--text-normal'] },
  { target: '--vlaina-color-tab-muted-fg', sources: ['--df-a', '--tab-text-color', '--tab-text-color-focused', '--text-muted'] },
  { target: '--vlaina-color-tab-muted-hover-fg', sources: ['--a-c', '--tab-text-color-focused', '--text-accent'] },
  { target: '--vlaina-color-tab-close-fg', sources: ['--df-a', '--icon-color', '--text-muted'] },
  { target: '--vlaina-color-tab-close-hover-fg', sources: ['--df', '--icon-color-hover', '--text-normal'] },
  { target: '--vlaina-color-tab-separator', sources: ['--pn-c-a', '--tab-outline-color', '--background-modifier-border'] },
  { target: '--vlaina-color-tab-overlay-bg', sources: ['--db', '--tab-container-background', '--background-primary'] },
  { target: '--vlaina-color-attachment-surface', sources: ['--pn-c', '--background-secondary'] },
  { target: '--vlaina-color-attachment-remove-bg', sources: ['--db', '--background-primary'] },
  { target: '--vlaina-color-attachment-remove-bg-hover', sources: ['--pn-c', '--background-modifier-hover'] },
  { target: '--vlaina-color-attachment-remove-fg', sources: ['--df-a', '--text-muted'] },
  { target: '--vlaina-color-attachment-remove-fg-hover', sources: ['--df', '--text-normal'] },
  { target: '--vlaina-color-editor-image-surface', sources: ['--pn-c', '--background-secondary'] },
  { target: '--vlaina-color-editor-image-border', sources: ['--pn-c-a', '--background-modifier-border'] },
  { target: '--vlaina-color-editor-image-placeholder', sources: ['--df-a', '--text-faint'] },
  { target: '--vlaina-color-image-drag-placeholder-bg', sources: ['--v-selected-c', '--text-selection'] },
  { target: '--vlaina-color-image-overlay-bg', sources: ['--background-modifier-cover', '--bq-bg'] },
  { target: '--vlaina-color-image-overlay-fg', sources: ['--text-on-accent', '--db', '--background-primary'] },
  { target: '--vlaina-color-image-overlay-muted-fg', sources: ['--df-a', '--text-muted'] },
  { target: '--vlaina-color-media-overlay-border', sources: ['--pn-c-a', '--background-modifier-border'] },
  { target: '--vlaina-color-media-overlay-bg', sources: ['--background-modifier-cover', '--bq-bg'] },
  { target: '--vlaina-color-media-overlay-bg-hover', sources: ['--background-modifier-cover', '--bq-bg'] },
  { target: '--vlaina-color-media-overlay-fg', sources: ['--df', '--text-normal'] },
  { target: '--vlaina-sidebar-surface', sources: ['--pn-c', '--glass-bg-color', '--bg-color', '--db-ext', '--background-secondary', '--background-primary'] },
  { target: '--vlaina-sidebar-row-selected-bg', sources: ['--ac-t2-fd', '--active-file-bg-color', '--element-color', '--element-color-soo-shallow', '--v-selected-c', '--nav-item-background-active', '--background-modifier-active', '--text-selection'] },
  { target: '--vlaina-sidebar-row-selected-text', sources: ['--df', '--active-file-text-color', '--head-title-h2-color', '--appui-color', '--element-color-deep', '--nav-item-color-active', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-sidebar-row-selected-text-soft', sources: ['--df', '--active-file-text-color', '--head-title-h2-color', '--appui-color', '--element-color', '--nav-item-color-active', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-sidebar-row-selected-text-muted', sources: ['--df-a', '--active-file-text-color', '--head-title-h2-color', '--text-color-secondary', '--appui-color', '--nav-item-color-active', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-sidebar-text', sources: ['--df', '--appui-color-text', '--text-color', '--nav-item-color', '--text-normal'] },
  { target: '--vlaina-sidebar-text-muted', sources: ['--df-a', '--text-color-secondary', '--appui-color-text', '--nav-item-color', '--text-muted'] },
  { target: '--vlaina-sidebar-text-soft', sources: ['--df-a', '--text-color-secondary', '--text-faint'] },
  { target: '--vlaina-sidebar-icon', sources: ['--df-a', '--appui-color-icon', '--text-color-secondary', '--nav-collapse-icon-color', '--icon-color', '--text-muted'] },
  { target: '--vlaina-sidebar-icon-hover', sources: ['--a-c', '--appui-color-icon', '--element-color-deep', '--nav-item-color-hover', '--icon-color-hover', '--text-accent'] },
  { target: '--vlaina-sidebar-fade', sources: ['--bg-color', '--db-ext', '--db', '--background-secondary'] },
  { target: '--vlaina-sidebar-row-hover', sources: ['--ac-t2-fd', '--item-hover-bg-color', '--element-color-soo-shallow', '--bq-bg-fd', '--nav-item-background-hover', '--background-modifier-hover'] },
  { target: '--vlaina-sidebar-row-active', sources: ['--ac-t2-fd', '--active-file-bg-color', '--element-color', '--element-color-soo-shallow', '--v-selected-c', '--nav-item-background-active', '--background-modifier-active'] },
  { target: '--vlaina-sidebar-notes-row-drag', sources: ['--v-selected-c', '--select-text-bg-color', '--text-selection'] },
  { target: '--vlaina-sidebar-notes-section-label', sources: ['--df', '--appui-color-text', '--text-color', '--nav-item-color', '--text-normal'] },
  { target: '--vlaina-sidebar-notes-section-label-hover', sources: ['--a-c', '--appui-color', '--element-color-deep', '--nav-item-color-hover', '--text-accent'] },
  { target: '--vlaina-sidebar-notes-outline-icon', sources: ['--a-c', '--appui-color-icon', '--element-color', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-sidebar-notes-chat-icon', sources: ['--a-c', '--appui-color-icon', '--element-color', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-sidebar-notes-file-icon', sources: ['--toc-h-num-c', '--appui-color-icon', '--a-c', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-sidebar-notes-folder-icon', sources: ['--toc-h-num-c', '--appui-color-icon', '--ac-bu', '--element-color', '--color-blue', '--text-accent'] },
  { target: '--vlaina-sidebar-notes-empty-surface', sources: ['--pn-c', '--element-color-soo-shallow', '--code-block-bg', '--background-secondary-alt', '--background-secondary'] },
  { target: '--vlaina-sidebar-notes-menu-bg', sources: ['--pn-c', '--bg-color', '--background-primary-alt', '--background-secondary'] },
  { target: '--vlaina-sidebar-notes-menu-border', sources: ['--pn-c-a', '--border-color', '--element-color-shallow', '--background-modifier-border'] },
  { target: '--vlaina-code-block-background', sources: ['--code-bg', '--code-block-bg', '--code-background'] },
  { target: '--vlaina-code-inline-background', sources: ['--code-bg', '--element-color-linecode-background', '--code-background'] },
  { target: '--vlaina-code-inline-foreground', sources: ['--code-t', '--element-color-linecode', '--code-normal'] },
  { target: '--vlaina-code-syntax-foreground', sources: ['--code-t', '--text-color', '--code-normal', '--text-normal'] },
  { target: '--vlaina-code-syntax-muted', sources: ['--df-a', '--text-color-secondary', '--code-comment', '--text-muted'] },
  { target: '--vlaina-code-block-copy-color', sources: ['--df-a', '--text-muted'] },
  { target: '--vlaina-color-info', sources: ['--ac-bu', '--color-blue'] },
  { target: '--vlaina-color-success', sources: ['--ac-gn', '--color-green'] },
  { target: '--vlaina-color-warning', sources: ['--ac-og', '--color-orange', '--color-yellow'] },
  { target: '--vlaina-color-danger', sources: ['--ac-rd', '--color-red'] },
  { target: '--vlaina-color-danger-hover', sources: ['--ac-rd', '--color-red'] },
  { target: '--vlaina-color-status-info-fg', sources: ['--ac-bu', '--color-blue'] },
  { target: '--vlaina-color-status-success-fg', sources: ['--ac-gn', '--color-green'] },
  { target: '--vlaina-color-status-warning-fg', sources: ['--ac-og', '--color-orange', '--color-yellow'] },
  { target: '--vlaina-color-status-danger-fg', sources: ['--ac-rd', '--color-red'] },
  { target: '--vlaina-color-status-info-bg', sources: ['--ac-bu-a', '--ac-bu-fd', '--background-modifier-hover'] },
  { target: '--vlaina-color-status-success-bg', sources: ['--ac-gn-a', '--ac-gn-fd', '--background-modifier-hover'] },
  { target: '--vlaina-color-status-warning-bg', sources: ['--ac-og-a', '--ac-og-fd', '--background-modifier-hover'] },
  { target: '--vlaina-color-status-danger-bg', sources: ['--ac-rd-a', '--ac-rd-fd', '--background-modifier-hover'] },
  { target: '--vlaina-color-status-info-border', sources: ['--ac-bu-fd-bd', '--color-blue'] },
  { target: '--vlaina-color-status-success-border', sources: ['--ac-gn-fd-bd', '--color-green'] },
  { target: '--vlaina-color-status-warning-border', sources: ['--ac-og-fd-bd', '--color-orange', '--color-yellow'] },
  { target: '--vlaina-color-status-danger-border', sources: ['--ac-rd-fd-bd', '--color-red'] },
  { target: '--vlaina-color-callout-gray-bg', sources: ['--bq-bg', '--blockquote-background-color', '--background-secondary'] },
  { target: '--vlaina-color-callout-icon-hover-bg', sources: ['--bq-bg-fd', '--background-modifier-hover'] },
  { target: '--vlaina-color-table-drag-control-border', sources: ['--pn-c-a', '--table-border-color', '--background-modifier-border'] },
  { target: '--vlaina-color-table-drag-control-border-hover', sources: ['--a-c', '--table-selection-border-color', '--background-modifier-border-hover', '--text-accent'] },
  { target: '--vlaina-color-table-drag-control-border-focus', sources: ['--a-c', '--table-selection-border-color', '--interactive-accent', '--text-accent'] },
  { target: '--vlaina-color-table-drag-control-bg', sources: ['--db', '--background-modifier-form-field', '--background-primary'] },
  { target: '--vlaina-color-table-drag-control-fg', sources: ['--df-a', '--text-muted'] },
  { target: '--vlaina-color-table-drag-control-fg-active', sources: ['--a-c', '--table-drag-handle-color-active', '--text-accent'] },
  { target: '--vlaina-color-table-column-source-highlight-bg', sources: ['--v-selected-c', '--table-selection', '--text-selection'] },
  { target: '--vlaina-color-frontmatter-border', sources: ['--pn-c-a', '--background-modifier-border'] },
  { target: '--vlaina-color-footnote-ref-bg', sources: ['--code-bg', '--code-background', '--background-secondary'] },
  { target: '--vlaina-color-math-editor-border', sources: ['--pn-c-a', '--background-modifier-border'] },
  { target: '--vlaina-color-math-editor-text', sources: ['--df', '--text-normal'] },
  { target: '--vlaina-color-math-editor-secondary-bg-hover', sources: ['--bq-bg-fd', '--background-modifier-hover'] },
  { target: '--vlaina-color-toolbar-border', sources: ['--pn-c-a', '--background-modifier-border'] },
  { target: '--vlaina-color-toolbar-tooltip-bg', sources: ['--db', '--background-primary'] },
  { target: '--vlaina-color-toolbar-tooltip-fg', sources: ['--df', '--text-normal'] },
  { target: '--vlaina-color-toolbar-shortcut-bg', sources: ['--bq-bg-fd', '--background-modifier-hover'] },
];

export const VLAINA_THEME_MAPPINGS: VlainaThemeMapping[] = [
  ...VLAINA_COLOR_THEME_MAPPINGS,
  ...VLAINA_FONT_THEME_MAPPINGS,
];
