import { entry, type HandcraftedLanguageCase } from './languageDetectionHandcrafted';

export const handcraftedJavaCases: readonly HandcraftedLanguageCase[] = [
  entry("hello world main", "public class Main {\n  public static void main(String[] args) {\n    System.out.println(\"hello\");\n  }\n}"),
  entry("package import list", "package com.vlaina.notes;\n\nimport java.util.List;\n\npublic class Inbox {\n  private final List<String> titles;\n\n  public Inbox(List<String> titles) {\n    this.titles = titles;\n  }\n}"),
  entry("import static math max", "import static java.lang.Math.max;\n\nclass Calc {\n  int value() {\n    return max(2, 3);\n  }\n}"),
  entry("class field constructor", "class Note {\n  private final String title;\n\n  Note(String title) {\n    this.title = title;\n  }\n}"),
  entry("public getter method", "public class User {\n  private String name;\n\n  public String getName() {\n    return name;\n  }\n}"),
  entry("boolean method branch", "class Flags {\n  boolean isReady(int count) {\n    return count > 0;\n  }\n}"),
  entry("enum sync state", "enum SyncState {\n  IDLE,\n  RUNNING,\n  FAILED\n}"),
  entry("interface repository", "public interface NoteRepository {\n  String findById(String id);\n}"),
  entry("implements runnable", "class Worker implements Runnable {\n  @Override\n  public void run() {\n    System.out.println(\"run\");\n  }\n}"),
  entry("extends exception", "class InvalidNoteException extends RuntimeException {\n  InvalidNoteException(String message) {\n    super(message);\n  }\n}"),
  entry("record point value", "record Point(int x, int y) {\n}"),
  entry("generic list field", "class Box<T> {\n  private final T value;\n\n  Box(T value) {\n    this.value = value;\n  }\n}"),
  entry("generic method identity", "class Utils {\n  static <T> T identity(T value) {\n    return value;\n  }\n}"),
  entry("optional of nullable", "import java.util.Optional;\n\nclass Mapper {\n  Optional<String> title(String value) {\n    return Optional.ofNullable(value);\n  }\n}"),
  entry("optional or else", "import java.util.Optional;\n\nclass Example {\n  String title(Optional<String> value) {\n    return value.orElse(\"draft\");\n  }\n}"),
  entry("stream of filter map", "import java.util.stream.Stream;\n\nclass Example {\n  Stream<String> titles() {\n    return Stream.of(\"a\", \"b\").filter(v -> !v.isBlank()).map(String::trim);\n  }\n}"),
  entry("collectors to list", "import java.util.List;\nimport java.util.stream.Collectors;\n\nclass Example {\n  List<String> titles(List<String> values) {\n    return values.stream().map(String::toUpperCase).collect(Collectors.toList());\n  }\n}"),
  entry("collectors grouping by", "import java.util.List;\nimport java.util.Map;\nimport java.util.stream.Collectors;\n\nclass Example {\n  Map<Integer, List<String>> grouped(List<String> values) {\n    return values.stream().collect(Collectors.groupingBy(String::length));\n  }\n}"),
  entry("arrays as list strings", "import java.util.Arrays;\nimport java.util.List;\n\nclass Example {\n  List<String> names() {\n    return Arrays.asList(\"a\", \"b\", \"c\");\n  }\n}"),
  entry("array list diamond", "import java.util.ArrayList;\nimport java.util.List;\n\nclass Example {\n  List<String> values = new ArrayList<>();\n}"),
  entry("hash map diamond", "import java.util.HashMap;\nimport java.util.Map;\n\nclass Example {\n  Map<String, Integer> counts = new HashMap<>();\n}"),
  entry("hash set diamond", "import java.util.HashSet;\nimport java.util.Set;\n\nclass Example {\n  Set<String> tags = new HashSet<>();\n}"),
  entry("map get or default", "import java.util.Map;\n\nclass Example {\n  int count(Map<String, Integer> counts) {\n    return counts.getOrDefault(\"draft\", 0);\n  }\n}"),
  entry("list for each loop", "import java.util.List;\n\nclass Example {\n  void print(List<String> values) {\n    for (String value : values) {\n      System.out.println(value);\n    }\n  }\n}"),
  entry("indexed for loop", "class Example {\n  int sum(int[] values) {\n    int total = 0;\n    for (int i = 0; i < values.length; i++) {\n      total += values[i];\n    }\n    return total;\n  }\n}"),
  entry("while loop decrement", "class Example {\n  int countdown(int value) {\n    while (value > 0) {\n      value--;\n    }\n    return value;\n  }\n}"),
  entry("switch expression arrow", "class Example {\n  String label(int value) {\n    return switch (value) {\n      case 1 -> \"one\";\n      default -> \"other\";\n    };\n  }\n}"),
  entry("classic switch statement", "class Example {\n  String label(int value) {\n    switch (value) {\n      case 1:\n        return \"one\";\n      default:\n        return \"other\";\n    }\n  }\n}"),
  entry("try catch finally", "class Example {\n  int parse(String value) {\n    try {\n      return Integer.parseInt(value);\n    } catch (NumberFormatException error) {\n      return 0;\n    } finally {\n      System.out.println(\"done\");\n    }\n  }\n}"),
  entry("try with resources reader", "import java.io.BufferedReader;\nimport java.io.IOException;\nimport java.io.Reader;\n\nclass Example {\n  String read(Reader source) throws IOException {\n    try (BufferedReader reader = new BufferedReader(source)) {\n      return reader.readLine();\n    }\n  }\n}"),
  entry("throws io exception", "import java.io.IOException;\n\nclass Example {\n  void save() throws IOException {\n    throw new IOException(\"disk\");\n  }\n}"),
  entry("static final constant", "class Example {\n  private static final String APP_NAME = \"vlaina\";\n}"),
  entry("nested static class", "class Outer {\n  static class Inner {\n    String title() {\n      return \"ok\";\n    }\n  }\n}"),
  entry("builder style return this", "class Builder {\n  private String title;\n\n  Builder title(String value) {\n    this.title = value;\n    return this;\n  }\n}"),
  entry("annotation override method", "class Example {\n  @Override\n  public String toString() {\n    return \"Example\";\n  }\n}"),
  entry("suppress warnings raw list", "import java.util.List;\n\nclass Example {\n  @SuppressWarnings(\"unchecked\")\n  List<String> cast(Object value) {\n    return (List<String>) value;\n  }\n}"),
  entry("deprecated annotation", "class Example {\n  @Deprecated\n  void oldMethod() {\n  }\n}"),
  entry("junit test annotation", "import org.junit.Test;\n\npublic class ExampleTest {\n  @Test\n  public void loadsValue() {\n    System.out.println(\"ok\");\n  }\n}"),
  entry("junit assert equals", "import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.assertEquals;\n\nclass ExampleTest {\n  @Test\n  void addsValues() {\n    assertEquals(4, 2 + 2);\n  }\n}"),
  entry("spring rest controller", "import org.springframework.web.bind.annotation.GetMapping;\nimport org.springframework.web.bind.annotation.RestController;\n\n@RestController\nclass HealthController {\n  @GetMapping(\"/health\")\n  String health() {\n    return \"ok\";\n  }\n}"),
  entry("spring service annotation", "import org.springframework.stereotype.Service;\n\n@Service\nclass NoteService {\n  String title() {\n    return \"draft\";\n  }\n}"),
  entry("spring autowired field", "import org.springframework.beans.factory.annotation.Autowired;\nimport org.springframework.stereotype.Component;\n\n@Component\nclass Handler {\n  @Autowired\n  private NoteService service;\n}"),
  entry("jpa entity table", "import jakarta.persistence.Entity;\nimport jakarta.persistence.Table;\n\n@Entity\n@Table(name = \"notes\")\nclass NoteEntity {\n}"),
  entry("jpa id column", "import jakarta.persistence.Column;\nimport jakarta.persistence.Entity;\nimport jakarta.persistence.Id;\n\n@Entity\nclass NoteEntity {\n  @Id\n  private Long id;\n\n  @Column(name = \"title\")\n  private String title;\n}"),
  entry("package private class", "package com.vlaina.editor;\n\nclass DraftFormatter {\n  String format(String title) {\n    return title.trim();\n  }\n}"),
  entry("import org apache commons", "import org.apache.commons.lang3.StringUtils;\n\nclass Example {\n  boolean blank(String value) {\n    return StringUtils.isBlank(value);\n  }\n}"),
  entry("import junit assert throws", "import static org.junit.jupiter.api.Assertions.assertThrows;\nimport org.junit.jupiter.api.Test;\n\nclass ExampleTest {\n  @Test\n  void fails() {\n    assertThrows(IllegalArgumentException.class, () -> { throw new IllegalArgumentException(); });\n  }\n}"),
  entry("lambda comparator sort", "import java.util.Comparator;\nimport java.util.List;\n\nclass Example {\n  void sort(List<String> values) {\n    values.sort(Comparator.comparing(String::length));\n  }\n}"),
  entry("method reference stream map", "import java.util.List;\n\nclass Example {\n  List<String> trim(List<String> values) {\n    return values.stream().map(String::trim).toList();\n  }\n}"),
  entry("text block query", "class Example {\n  String query() {\n    return \"\"\"\n      select id, title\n      from notes\n      \"\"\";\n  }\n}"),
  entry("var local inference", "import java.util.List;\n\nclass Example {\n  void run() {\n    var names = List.of(\"a\", \"b\");\n    System.out.println(names.size());\n  }\n}"),
  entry("sealed interface permits", "sealed interface Command permits OpenCommand, CloseCommand {\n}"),
  entry("final class service", "public final class NoteService {\n  public String status() {\n    return \"ready\";\n  }\n}"),
  entry("abstract class method", "abstract class BaseJob {\n  abstract void run();\n}"),
  entry("protected method override", "class Parent {\n  protected void save() {\n  }\n}\n\nclass Child extends Parent {\n  @Override\n  protected void save() {\n  }\n}"),
  entry("implements comparable", "class Version implements Comparable<Version> {\n  @Override\n  public int compareTo(Version other) {\n    return 0;\n  }\n}"),
  entry("public static factory", "class Example {\n  public static Example create() {\n    return new Example();\n  }\n}"),
  entry("private constructor singleton", "class Settings {\n  private static final Settings INSTANCE = new Settings();\n\n  private Settings() {\n  }\n}"),
  entry("local date now", "import java.time.LocalDate;\n\nclass Example {\n  LocalDate today() {\n    return LocalDate.now();\n  }\n}"),
  entry("instant parse call", "import java.time.Instant;\n\nclass Example {\n  Instant value() {\n    return Instant.parse(\"2026-04-06T00:00:00Z\");\n  }\n}"),
  entry("date time formatter", "import java.time.format.DateTimeFormatter;\n\nclass Example {\n  DateTimeFormatter formatter = DateTimeFormatter.ISO_LOCAL_DATE;\n}"),
  entry("uuid random uuid", "import java.util.UUID;\n\nclass Example {\n  UUID next() {\n    return UUID.randomUUID();\n  }\n}"),
  entry("big decimal add", "import java.math.BigDecimal;\n\nclass Example {\n  BigDecimal total() {\n    return new BigDecimal(\"12.50\").add(new BigDecimal(\"3.25\"));\n  }\n}"),
  entry("path of string", "import java.nio.file.Path;\n\nclass Example {\n  Path file() {\n    return Path.of(\"notes\", \"draft.md\");\n  }\n}"),
  entry("files read string", "import java.io.IOException;\nimport java.nio.file.Files;\nimport java.nio.file.Path;\n\nclass Example {\n  String load(Path path) throws IOException {\n    return Files.readString(path);\n  }\n}"),
  entry("file open read signal", "import java.io.File;\n\nclass Example {\n  boolean exists() {\n    return new File(\"notes.txt\").exists();\n  }\n}"),
  entry("thread start runnable", "class Example {\n  void start() {\n    new Thread(() -> System.out.println(\"run\")).start();\n  }\n}"),
  entry("executor service submit", "import java.util.concurrent.ExecutorService;\nimport java.util.concurrent.Executors;\n\nclass Example {\n  void run() {\n    ExecutorService pool = Executors.newSingleThreadExecutor();\n    pool.submit(() -> System.out.println(\"task\"));\n  }\n}"),
  entry("completable future supply async", "import java.util.concurrent.CompletableFuture;\n\nclass Example {\n  CompletableFuture<String> load() {\n    return CompletableFuture.supplyAsync(() -> \"ok\");\n  }\n}"),
  entry("stream iterate limit", "import java.util.stream.Stream;\n\nclass Example {\n  Stream<Integer> numbers() {\n    return Stream.iterate(1, value -> value + 1).limit(3);\n  }\n}"),
  entry("stream generate supplier", "import java.util.stream.Stream;\n\nclass Example {\n  Stream<String> values() {\n    return Stream.generate(() -> \"x\").limit(2);\n  }\n}"),
  entry("optional map flat map", "import java.util.Optional;\n\nclass Example {\n  Optional<Integer> length(Optional<String> value) {\n    return value.map(String::length).flatMap(Optional::ofNullable);\n  }\n}"),
  entry("pattern matching instance of", "class Example {\n  int length(Object value) {\n    if (value instanceof String text) {\n      return text.length();\n    }\n    return 0;\n  }\n}"),
  entry("catch multiple exceptions", "import java.io.IOException;\nimport java.sql.SQLException;\n\nclass Example {\n  void load() {\n    try {\n      throw new IOException();\n    } catch (IOException | SQLException error) {\n      System.out.println(error.getMessage());\n    }\n  }\n}"),
  entry("synchronized block monitor", "class Example {\n  private final Object monitor = new Object();\n\n  void run() {\n    synchronized (monitor) {\n      System.out.println(\"locked\");\n    }\n  }\n}"),
  entry("volatile field flag", "class Example {\n  private volatile boolean stopped;\n}"),
  entry("transient field cache", "class Example {\n  private transient String cached;\n}"),
  entry("public static nested interface", "class Example {\n  public interface Loader {\n    String load();\n  }\n}"),
  entry("annotation custom target", "import java.lang.annotation.ElementType;\nimport java.lang.annotation.Target;\n\n@Target(ElementType.METHOD)\n@interface Logged {\n}"),
  entry("generic bounds comparable", "class Example {\n  <T extends Comparable<T>> T max(T left, T right) {\n    return left.compareTo(right) >= 0 ? left : right;\n  }\n}"),
  entry("wildcard extends list", "import java.util.List;\n\nclass Example {\n  int total(List<? extends Number> values) {\n    return values.size();\n  }\n}"),
  entry("wildcard super consumer", "import java.util.List;\n\nclass Example {\n  void add(List<? super Integer> values) {\n    values.add(1);\n  }\n}"),
  entry("list string arrays as list", "import java.util.Arrays;\nimport java.util.List;\n\nclass Example {\n  List<String> names = Arrays.asList(\"alpha\", \"beta\");\n}"),
  entry("map entry loop", "import java.util.Map;\n\nclass Example {\n  void print(Map<String, Integer> counts) {\n    for (Map.Entry<String, Integer> entry : counts.entrySet()) {\n      System.out.println(entry.getKey());\n    }\n  }\n}"),
  entry("queue poll offer", "import java.util.ArrayDeque;\nimport java.util.Queue;\n\nclass Example {\n  Queue<String> values = new ArrayDeque<>();\n}"),
  entry("deque add first", "import java.util.ArrayDeque;\n\nclass Example {\n  void run() {\n    var deque = new ArrayDeque<String>();\n    deque.addFirst(\"draft\");\n  }\n}"),
  entry("list of factory", "import java.util.List;\n\nclass Example {\n  List<String> values() {\n    return List.of(\"a\", \"b\");\n  }\n}"),
  entry("map of factory", "import java.util.Map;\n\nclass Example {\n  Map<String, Integer> values() {\n    return Map.of(\"draft\", 1, \"done\", 2);\n  }\n}"),
  entry("set of factory", "import java.util.Set;\n\nclass Example {\n  Set<String> tags() {\n    return Set.of(\"java\", \"notes\");\n  }\n}"),
  entry("locale root lower case", "import java.util.Locale;\n\nclass Example {\n  String normalize(String value) {\n    return value.toLowerCase(Locale.ROOT);\n  }\n}"),
  entry("scanner next line", "import java.util.Scanner;\n\nclass Example {\n  String read(Scanner scanner) {\n    return scanner.nextLine();\n  }\n}"),
  entry("string builder append", "class Example {\n  String build() {\n    return new StringBuilder().append(\"a\").append(\"b\").toString();\n  }\n}"),
  entry("format string formatted", "class Example {\n  String label(int value) {\n    return \"count=%d\".formatted(value);\n  }\n}"),
  entry("http client request", "import java.net.URI;\nimport java.net.http.HttpClient;\nimport java.net.http.HttpRequest;\n\nclass Example {\n  HttpRequest request() {\n    return HttpRequest.newBuilder(URI.create(\"https://example.com\")).GET().build();\n  }\n}"),
  entry("json object mapper spring", "import com.fasterxml.jackson.databind.ObjectMapper;\n\nclass Example {\n  byte[] encode(ObjectMapper mapper, Object value) throws Exception {\n    return mapper.writeValueAsBytes(value);\n  }\n}"),
  entry("static import assertions", "import static org.junit.jupiter.api.Assertions.assertTrue;\nimport org.junit.jupiter.api.Test;\n\nclass ExampleTest {\n  @Test\n  void ready() {\n    assertTrue(true);\n  }\n}"),
  entry("annotation get mapping path", "import org.springframework.web.bind.annotation.GetMapping;\n\nclass Example {\n  @GetMapping(\"/notes\")\n  public String list() {\n    return \"ok\";\n  }\n}"),
  entry("repository annotation interface", "import org.springframework.stereotype.Repository;\n\n@Repository\ninterface NoteRepository {\n}"),
  entry("component constructor injection", "import org.springframework.stereotype.Component;\n\n@Component\nclass Example {\n  private final NoteService service;\n\n  Example(NoteService service) {\n    this.service = service;\n  }\n}"),
  entry("override equals hashcode", "import java.util.Objects;\n\nclass Example {\n  private final String id;\n\n  Example(String id) {\n    this.id = id;\n  }\n\n  @Override\n  public boolean equals(Object other) {\n    if (this == other) {\n      return true;\n    }\n    if (!(other instanceof Example value)) {\n      return false;\n    }\n    return Objects.equals(id, value.id);\n  }\n}"),
];
