export {
  clearCache,
  layout,
  layoutNextLine,
  layoutNextLineRange,
  layoutWithLines,
  materializeLineRange,
  measureLineStats,
  measureNaturalWidth,
  prepare,
  prepareWithSegments,
  setLocale,
  walkLineRanges,
  type LayoutCursor,
  type LayoutLine,
  type LayoutLineRange,
  type LayoutLinesResult,
  type LayoutResult,
  type LineStats,
  type PrepareOptions,
  type PreparedText,
  type PreparedTextWithSegments,
  type WordBreakMode,
} from './pretext/layout';

export {
  layoutNextRichInlineLineRange,
  materializeRichInlineLineRange,
  measureRichInlineStats,
  prepareRichInline,
  walkRichInlineLineRanges,
  type PreparedRichInline,
  type RichInlineCursor,
  type RichInlineFragment,
  type RichInlineFragmentRange,
  type RichInlineItem,
  type RichInlineLine,
  type RichInlineLineRange,
  type RichInlineStats,
} from './pretext/rich-inline';

export {
  measureTextBlockHeight,
  measureTextLineCount,
  measureTextNaturalWidth,
  measureTextWrapStats,
  measureTextareaContentHeight,
  resolveElementTextLayoutMetrics,
  type ElementTextLayoutMetrics,
  type TextBlockMeasureOptions,
  type TextLayoutMetrics,
  type TextWrapStats,
} from './textarea';
