import type { ShortcutConfig, ShortcutDefinition, ShortcutModule } from './types';
import {
  OPEN_MARKDOWN_FILE_ACTION,
  OPEN_MARKDOWN_FILE_DESCRIPTION,
} from '@/lib/notes/openMarkdownFileText';

const ALL_MODULES: ShortcutModule[] = ['notes', 'chat'];

export const SHORTCUT_DEFINITIONS: ShortcutDefinition[] = [
  {
    id: 'toggleAppViewMode',
    action: 'Toggle notes / chat',
    description: 'Toggle Notes and Chat',
    keys: ['Ctrl', "'"],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'toggleSidebar',
    action: 'Toggle sidebar',
    description: 'Toggle sidebar',
    keys: ['Ctrl', '\\'],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'sidebarSearch',
    action: 'Open sidebar search',
    description: 'Open sidebar search',
    keys: ['Ctrl', 'Shift', 'F'],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'toggleDrawer',
    action: 'Toggle drawer',
    description: 'Toggle drawer',
    keys: ['Ctrl', 'D'],
    scope: 'global',
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'open-settings',
    action: 'Open settings',
    description: 'Open settings',
    keys: ['Ctrl', ','],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'newWindow',
    action: 'New window',
    description: 'New Window',
    keys: ['Ctrl', 'N'],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'newTab',
    action: 'New note tab',
    description: 'New tab',
    keys: ['Ctrl', 'T'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'openMarkdownFile',
    action: OPEN_MARKDOWN_FILE_ACTION,
    description: OPEN_MARKDOWN_FILE_DESCRIPTION,
    keys: ['Ctrl', 'O'],
    scope: 'notes',
    isSystem: true,
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'toggleNotesSidebarView',
    action: 'Toggle files / outline',
    description: 'Toggle notes sidebar view',
    keys: ['Ctrl', 'Shift', '\\'],
    scope: 'notes',
    isSystem: true,
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'closeCurrentTab',
    action: 'Close current tab',
    description: 'Close current tab',
    keys: ['Ctrl', 'W'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'nextNoteTab',
    action: 'Next tab',
    description: 'Next note tab',
    keys: ['Ctrl', 'Tab'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'previousNoteTab',
    action: 'Previous tab',
    description: 'Previous note tab',
    keys: ['Ctrl', 'Shift', 'Tab'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'saveNote',
    action: 'Save note',
    description: 'Save note',
    keys: ['Ctrl', 'S'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'toggleEmbeddedChat',
    action: 'Toggle embedded chat',
    description: 'Toggle embedded chat',
    keys: ['Ctrl', 'L'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'editorFind',
    action: 'Find in note',
    description: 'Find in note',
    keys: ['Ctrl', 'F'],
    scope: 'notes',
    isSystem: true,
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'openNewChat',
    action: 'Open new chat',
    description: 'Open new chat',
    keys: ['Ctrl', 'Shift', 'O'],
    scope: 'chat',
    modules: ['notes', 'chat'],
    section: 'Chat',
  },
  {
    id: 'toggleTemporaryChatWelcome',
    action: 'Open temporary chat (toggle if empty)',
    description: 'Open temporary chat (toggle if empty)',
    keys: ['Ctrl', 'Shift', 'J'],
    scope: 'chat',
    isSystem: true,
    modules: ['notes', 'chat'],
    section: 'Chat',
  },
  {
    id: 'stopResponse',
    action: 'Stop response',
    description: 'Stop response',
    keys: ['Esc'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'focusChatInput',
    action: 'Focus chat input',
    description: 'Focus chat input',
    keys: ['Shift', 'Esc'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'previousChatSession',
    action: 'Previous chat',
    description: 'Previous chat',
    keys: ['Ctrl', 'Shift', 'Tab'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'nextChatSession',
    action: 'Next chat',
    description: 'Next chat',
    keys: ['Ctrl', 'Tab'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'copyLastCodeBlock',
    action: 'Copy last code block',
    description: 'Copy last code block',
    keys: ['Ctrl', 'Shift', ';'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'copyLastResponse',
    action: 'Copy last response',
    description: 'Copy last response',
    keys: ['Ctrl', 'Shift', 'C'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'previousMessage',
    action: 'Previous message',
    description: 'Previous message',
    keys: ['Shift', 'ArrowUp'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'nextMessage',
    action: 'Next message',
    description: 'Next message',
    keys: ['Shift', 'ArrowDown'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'deleteChat',
    action: 'Delete chat',
    description: 'Delete chat',
    keys: ['Ctrl', 'Shift', 'Backspace'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
];

export const DEFAULT_SHORTCUTS: ShortcutConfig[] = SHORTCUT_DEFINITIONS.map(
  ({ id, keys, description, scope, isSystem }) => ({
    id,
    keys,
    description,
    scope,
    isSystem,
  }),
);

export function getShortcutDefinitions(): ShortcutDefinition[] {
  return SHORTCUT_DEFINITIONS;
}

export function getShortcutDefinition(id: string): ShortcutDefinition | undefined {
  return SHORTCUT_DEFINITIONS.find((shortcut) => shortcut.id === id);
}

export function getShortcutDefinitionsForModule(module: ShortcutModule): ShortcutDefinition[] {
  return SHORTCUT_DEFINITIONS.filter((shortcut) => shortcut.modules.includes(module));
}
