import type { ShortcutConfig, ShortcutDefinition, ShortcutModule } from './types';
const ALL_MODULES: ShortcutModule[] = ['notes', 'chat'];

export const SHORTCUT_DEFINITIONS: ShortcutDefinition[] = [
  {
    id: 'toggleAppViewMode',
    action: 'Toggle notes / chat',
    actionKey: 'shortcut.action.toggleAppViewMode',
    description: 'Toggle Notes and Chat',
    keys: ['Ctrl', "'"],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'toggleSidebar',
    action: 'Toggle sidebar',
    actionKey: 'shortcut.action.toggleSidebar',
    description: 'Toggle sidebar',
    keys: ['Ctrl', '\\'],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'sidebarSearch',
    action: 'Open sidebar search',
    actionKey: 'shortcut.action.sidebarSearch',
    description: 'Open sidebar search',
    keys: ['Ctrl', 'Shift', 'F'],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'toggleDrawer',
    action: 'Toggle drawer',
    actionKey: 'shortcut.action.toggleDrawer',
    description: 'Toggle drawer',
    keys: ['Ctrl', 'D'],
    scope: 'global',
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'open-settings',
    action: 'Open settings',
    actionKey: 'shortcut.action.openSettings',
    description: 'Open settings',
    keys: ['Ctrl', ','],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'newWindow',
    action: 'New window',
    actionKey: 'shortcut.action.newWindow',
    description: 'New Window',
    keys: ['Ctrl', 'N'],
    scope: 'global',
    isSystem: true,
    modules: ALL_MODULES,
    section: 'General',
  },
  {
    id: 'newTab',
    action: 'New note tab',
    actionKey: 'shortcut.action.newTab',
    description: 'New tab',
    keys: ['Ctrl', 'Shift', 'T'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'openMarkdownFile',
    action: 'Open Markdown File and switch to its parent folder',
    actionKey: 'shortcut.action.openMarkdownFile',
    description: 'Open Markdown File and switch to its parent folder',
    keys: ['Ctrl', 'O'],
    scope: 'notes',
    isSystem: true,
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'toggleNotesSidebarView',
    action: 'Toggle files / outline',
    actionKey: 'shortcut.action.toggleNotesSidebarView',
    description: 'Toggle notes sidebar view',
    keys: ['Ctrl', 'Shift', '\\'],
    scope: 'notes',
    isSystem: true,
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'closeCurrentTab',
    action: 'Close current tab',
    actionKey: 'shortcut.action.closeCurrentTab',
    description: 'Close current tab',
    keys: ['Ctrl', 'W'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'reopenClosedTab',
    action: 'Reopen closed tab',
    actionKey: 'shortcut.action.reopenClosedTab',
    description: 'Reopen closed note tab',
    keys: ['Ctrl', 'Alt', 'T'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'nextNoteTab',
    action: 'Next tab',
    actionKey: 'shortcut.action.nextNoteTab',
    description: 'Next note tab',
    keys: ['Ctrl', 'Tab'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'previousNoteTab',
    action: 'Previous tab',
    actionKey: 'shortcut.action.previousNoteTab',
    description: 'Previous note tab',
    keys: ['Ctrl', 'Shift', 'Tab'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'saveNote',
    action: 'Save note',
    actionKey: 'shortcut.action.saveNote',
    description: 'Save note',
    keys: ['Ctrl', 'S'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'toggleEmbeddedChat',
    action: 'Quote selection / toggle embedded chat',
    actionKey: 'shortcut.action.toggleEmbeddedChat',
    description: 'Quote selected text to chat, or toggle embedded chat',
    keys: ['Ctrl', 'L'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'editorFind',
    action: 'Find in note',
    actionKey: 'shortcut.action.editorFind',
    description: 'Find in note',
    keys: ['Ctrl', 'F'],
    scope: 'notes',
    isSystem: true,
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'toggleNoteSourceMode',
    action: 'Toggle source / rendered mode',
    actionKey: 'shortcut.action.toggleNoteSourceMode',
    description: 'Toggle source / rendered mode',
    keys: ['Ctrl', '/'],
    scope: 'notes',
    modules: ['notes'],
    section: 'View',
  },
  {
    id: 'deleteCurrentNote',
    action: 'Delete current note',
    actionKey: 'shortcut.action.deleteCurrentNote',
    description: 'Delete current note',
    keys: ['Ctrl', 'Shift', 'Backspace'],
    scope: 'notes',
    modules: ['notes'],
    section: 'Notes',
  },
  {
    id: 'openNewChat',
    action: 'Open new chat',
    actionKey: 'shortcut.action.openNewChat',
    description: 'Open new chat',
    keys: ['Ctrl', 'Shift', 'O'],
    scope: 'chat',
    modules: ['notes', 'chat'],
    section: 'Chat',
  },
  {
    id: 'toggleTemporaryChatWelcome',
    action: 'Open temporary chat',
    actionKey: 'shortcut.action.toggleTemporaryChatWelcome',
    description: 'Open temporary chat',
    keys: ['Ctrl', 'Shift', 'J'],
    scope: 'chat',
    isSystem: true,
    modules: ['notes', 'chat'],
    section: 'Chat',
  },
  {
    id: 'stopResponse',
    action: 'Stop response',
    actionKey: 'shortcut.action.stopResponse',
    description: 'Stop response',
    keys: ['Esc'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'focusChatInput',
    action: 'Focus chat input',
    actionKey: 'shortcut.action.focusChatInput',
    description: 'Focus chat input',
    keys: ['Shift', 'Esc'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'previousChatSession',
    action: 'Previous chat',
    actionKey: 'shortcut.action.previousChatSession',
    description: 'Previous chat',
    keys: ['Ctrl', 'Shift', 'Tab'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'nextChatSession',
    action: 'Next chat',
    actionKey: 'shortcut.action.nextChatSession',
    description: 'Next chat',
    keys: ['Ctrl', 'Tab'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'copyLastCodeBlock',
    action: 'Copy last code block',
    actionKey: 'shortcut.action.copyLastCodeBlock',
    description: 'Copy last code block',
    keys: ['Ctrl', 'Shift', ';'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'copyLastResponse',
    action: 'Copy last response',
    actionKey: 'shortcut.action.copyLastResponse',
    description: 'Copy last response',
    keys: ['Ctrl', 'Shift', 'C'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'previousMessage',
    action: 'Previous message',
    actionKey: 'shortcut.action.previousMessage',
    description: 'Previous message',
    keys: ['Shift', 'ArrowUp'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'nextMessage',
    action: 'Next message',
    actionKey: 'shortcut.action.nextMessage',
    description: 'Next message',
    keys: ['Shift', 'ArrowDown'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
  {
    id: 'deleteChat',
    action: 'Delete chat',
    actionKey: 'shortcut.action.deleteChat',
    description: 'Delete chat',
    keys: ['Ctrl', 'Shift', 'Backspace'],
    scope: 'chat',
    modules: ['chat'],
    section: 'Chat',
  },
];

export const DEFAULT_SHORTCUTS: ShortcutConfig[] = SHORTCUT_DEFINITIONS.map(
  ({ id, keys, description, scope, isSystem }) => ({
    id,
    keys,
    description,
    scope,
    isSystem,
  }),
);

export function getShortcutDefinitions(): ShortcutDefinition[] {
  return SHORTCUT_DEFINITIONS;
}

export function getShortcutDefinition(id: string): ShortcutDefinition | undefined {
  return SHORTCUT_DEFINITIONS.find((shortcut) => shortcut.id === id);
}

export function getShortcutDefinitionsForModule(module: ShortcutModule): ShortcutDefinition[] {
  return SHORTCUT_DEFINITIONS.filter((shortcut) => shortcut.modules.includes(module));
}
