import { describe, it } from 'vitest';

import { expectStableMarkdownRoundTrip } from './markdownRoundTripTestUtils';

describe('real note markdown regression', () => {
  it.each([
    {
      name: 'project meeting note',
      markdown: [
        '---',
        'title: Sync Notes',
        'tags:',
        '  - project',
        '  - meeting',
        '---',
        '# Sync Notes',
        '',
        '## Decisions',
        '',
        '- Ship the editor persistence fix first.',
        '- Keep the user-visible Markdown standard.',
        '',
        '## Follow ups',
        '',
        '- [ ] Re-test renamed notes on two windows.',
        '- [x] Verify starred note metadata after reopen.',
        '',
        '> 💡 Important',
        '>',
        '> A note should look the same after saving and reopening.',
      ].join('\n'),
      expected: [
        '---',
        'title: Sync Notes',
        'tags:',
        '  - project',
        '  - meeting',
        '---',
        '# Sync Notes',
        '## Decisions',
        '',
        '- Ship the editor persistence fix first.',
        '- Keep the user-visible Markdown standard.',
        '',
        '## Follow ups',
        '',
        '- [ ] Re-test renamed notes on two windows.',
        '- [x] Verify starred note metadata after reopen.',
        '',
        '> 💡 Important',
        '>',
        '> A note should look the same after saving and reopening.',
      ].join('\n'),
    },
    {
      name: 'technical investigation note',
      markdown: [
        '# Markdown Serialization Investigation',
        '',
        'The editor must preserve `user input -> save -> reopen` semantics.',
        '',
        '```ts',
        'const persisted = serialize(doc);',
        'const reopened = parse(persisted);',
        'expect(reopened).toEqual(doc);',
        '```',
        '',
        '| Case | Expected |',
        '| --- | --- |',
        '| heading | no extra blank line |',
        '| list gap | keep list structure |',
        '',
        '$$',
        'a^2 + b^2 = c^2',
        '$$',
      ].join('\n'),
      expected: [
        '# Markdown Serialization Investigation',
        '',
        'The editor must preserve `user input -> save -> reopen` semantics.',
        '',
        '```ts',
        'const persisted = serialize(doc);',
        'const reopened = parse(persisted);',
        'expect(reopened).toEqual(doc);',
        '```',
        '',
        '| Case     | Expected            |',
        '| -------- | ------------------- |',
        '| heading  | no extra blank line |',
        '| list gap | keep list structure |',
        '',
        '$$',
        'a^2 + b^2 = c^2',
        '$$',
      ].join('\n'),
    },
    {
      name: 'research clipping note',
      markdown: [
        '# Research Clipping',
        '',
        'Read [CommonMark](https://commonmark.org/help/) and [source](<docs/research note.md> "Research Source").',
        '',
        'Use ==highlighted text==, <u>underlined text</u>, and <span style="color: #41a8ea">blue note</span>.',
        '',
        '![Diagram <Draft>](<assets/diagram one.png> "Architecture & Flow")',
      ].join('\n'),
      expected: [
        '# Research Clipping',
        '',
        'Read [CommonMark](https://commonmark.org/help/) and [source](<docs/research note.md> "Research Source").',
        '',
        'Use ==highlighted text==, ++underlined text++, and <span style="color: #41a8ea">blue note</span>.',
        '',
        '![Diagram \\<Draft>](<assets/diagram one.png> "Architecture & Flow")',
      ].join('\n'),
    },
    {
      name: 'daily note with loose lists',
      markdown: [
        '# Daily Note',
        '',
        'Morning plan.',
        '',
        '1. Review pull requests.',
        '',
        '   Leave notes on risky changes.',
        '',
        '2. Test Markdown persistence.',
        '',
        '- Personal reminder',
        '',
        '  Keep one blank line before the detail paragraph.',
      ].join('\n'),
      expected: [
        '# Daily Note',
        '',
        'Morning plan.',
        '',
        '1. Review pull requests.',
        '',
        '   Leave notes on risky changes.',
        '',
        '2. Test Markdown persistence.',
        '- Personal reminder',
        '',
        '  Keep one blank line before the detail paragraph.',
      ].join('\n'),
    },
    {
      name: 'design note with custom blocks',
      markdown: [
        '# Editor UX Notes',
        '',
        '[TOC]',
        '',
        '## Preview',
        '',
        '<!--align:center-->',
        '',
        '> 💡 Toolbar preview',
        '>',
        '> The preview should reuse the actual rendered style.',
        '',
        '```mermaid',
        'graph TD',
        '  Input --> Parse',
        '  Parse --> Persist',
        '  Persist --> Reopen',
        '```',
      ].join('\n'),
      expected: [
        '# Editor UX Notes',
        '',
        '[TOC]',
        '',
        '## Preview',
        '',
        '<!--align:center-->',
        '',
        '> 💡 Toolbar preview',
        '>',
        '> The preview should reuse the actual rendered style.',
        '',
        '```mermaid',
        'graph TD',
        '  Input --> Parse',
        '  Parse --> Persist',
        '  Persist --> Reopen',
        '```',
      ].join('\n'),
    },
  ])('keeps a realistic note stable after save and reopen: $name', async ({ markdown, expected }) => {
    await expectStableMarkdownRoundTrip(markdown, expected);
  });
});
