import { describe, it } from 'vitest';

import {
  expectConvergentPersistedMarkdownRoundTrip,
  expectStableMarkdownRoundTrip,
} from './markdownRoundTripTestUtils';

describe('real note markdown regression', () => {
  it.each([
    {
      name: 'project meeting note',
      markdown: [
        '---',
        'title: Sync Notes',
        'tags:',
        '  - project',
        '  - meeting',
        '---',
        '# Sync Notes',
        '',
        '## Decisions',
        '',
        '- Ship the editor persistence fix first.',
        '- Keep the user-visible Markdown standard.',
        '',
        '## Follow ups',
        '',
        '- [ ] Re-test renamed notes on two windows.',
        '- [x] Verify starred note metadata after reopen.',
        '',
        '> 💡 Important',
        '>',
        '> A note should look the same after saving and reopening.',
      ].join('\n'),
      expected: [
        '---',
        'title: Sync Notes',
        'tags:',
        '  - project',
        '  - meeting',
        '---',
        '# Sync Notes',
        '## Decisions',
        '',
        '- Ship the editor persistence fix first.',
        '- Keep the user-visible Markdown standard.',
        '',
        '## Follow ups',
        '',
        '- [ ] Re-test renamed notes on two windows.',
        '- [x] Verify starred note metadata after reopen.',
        '',
        '> 💡 Important',
        '>',
        '> A note should look the same after saving and reopening.',
      ].join('\n'),
    },
    {
      name: 'technical investigation note',
      markdown: [
        '# Markdown Serialization Investigation',
        '',
        'The editor must preserve `user input -> save -> reopen` semantics.',
        '',
        '```ts',
        'const persisted = serialize(doc);',
        'const reopened = parse(persisted);',
        'expect(reopened).toEqual(doc);',
        '```',
        '',
        '| Case | Expected |',
        '| --- | --- |',
        '| heading | no extra blank line |',
        '| list gap | keep list structure |',
        '',
        '$$',
        'a^2 + b^2 = c^2',
        '$$',
      ].join('\n'),
      expected: [
        '# Markdown Serialization Investigation',
        '',
        'The editor must preserve `user input -> save -> reopen` semantics.',
        '',
        '```ts',
        'const persisted = serialize(doc);',
        'const reopened = parse(persisted);',
        'expect(reopened).toEqual(doc);',
        '```',
        '',
        '| Case     | Expected            |',
        '| -------- | ------------------- |',
        '| heading  | no extra blank line |',
        '| list gap | keep list structure |',
        '',
        '$$',
        'a^2 + b^2 = c^2',
        '$$',
      ].join('\n'),
    },
    {
      name: 'research clipping note',
      markdown: [
        '# Research Clipping',
        '',
        'Read [CommonMark](https://commonmark.org/help/) and [source](<docs/research note.md> "Research Source").',
        '',
        'Use ==highlighted text==, <u>underlined text</u>, and <span style="color: #41a8ea">blue note</span>.',
        '',
        '![Diagram <Draft>](<assets/diagram one.png> "Architecture & Flow")',
      ].join('\n'),
      expected: [
        '# Research Clipping',
        '',
        'Read [CommonMark](https://commonmark.org/help/) and [source](<docs/research note.md> "Research Source").',
        '',
        'Use ==highlighted text==, ++underlined text++, and <span style="color: #41a8ea">blue note</span>.',
        '',
        '<img src="assets/diagram one.png" alt="Diagram &lt;Draft&gt;" title="Architecture &amp; Flow" />',
      ].join('\n'),
    },
    {
      name: 'daily note with loose lists',
      markdown: [
        '# Daily Note',
        '',
        'Morning plan.',
        '',
        '1. Review pull requests.',
        '',
        '   Leave notes on risky changes.',
        '',
        '2. Test Markdown persistence.',
        '',
        '- Personal reminder',
        '',
        '  Keep one blank line before the detail paragraph.',
      ].join('\n'),
      expected: [
        '# Daily Note',
        '',
        'Morning plan.',
        '',
        '1. Review pull requests.',
        '',
        '   Leave notes on risky changes.',
        '',
        '2. Test Markdown persistence.',
        '- Personal reminder',
        '',
        '  Keep one blank line before the detail paragraph.',
      ].join('\n'),
    },
    {
      name: 'design note with custom blocks',
      markdown: [
        '# Editor UX Notes',
        '',
        '[TOC]',
        '',
        '## Preview',
        '',
        '<!--align:center-->',
        '',
        '> 💡 Toolbar preview',
        '>',
        '> The preview should reuse the actual rendered style.',
        '',
        '```mermaid',
        'graph TD',
        '  Input --> Parse',
        '  Parse --> Persist',
        '  Persist --> Reopen',
        '```',
      ].join('\n'),
      expected: [
        '# Editor UX Notes',
        '',
        '[TOC]',
        '',
        '## Preview',
        '',
        '<!--align:center-->',
        '',
        '> 💡 Toolbar preview',
        '>',
        '> The preview should reuse the actual rendered style.',
        '',
        '```mermaid',
        'graph TD',
        '  Input --> Parse',
        '  Parse --> Persist',
        '  Persist --> Reopen',
        '```',
      ].join('\n'),
    },
    {
      name: 'mixed numbered Chinese task note from paste',
      convergentOnly: true,
      markdown: [
        '# Paste Regression',
        '',
        '1输入不要固定的高度，',
        '',
        ' 测试yt那些',
        '',
        '1. 输入反斜杠东西出来的有点慢',
        '',
        '1. 右键单击图表，将其另存为本地磁盘上的 SVG、PNG 或 JPG 文件。',
        '2. 不同的主题',
        '',
        '1. 表格的渲染太慢了，打开的时候可以看到loadign',
        '2. 检查对',
        '',
        '`mindmap支持是否完整`',
        '3. 表格看看是否需要调整大小',
        '4. ',
        '5. 斜杠工具栏',
        '6. 文件的拖入star',
        '7. todo之后就是会换行',
        '8. 从外部拖动文件进来，就是变成和我们一样的拖动文件的样式',
        '9. 给所有的换图标',
        '10. 这个md的解析和使用直接诶是乱套了',
        '11. 这个merger表格根本用不了',
        '    1. 在他下面弄个反斜杠直接消失了',
        '12. 自动生成的目录部分的高度需要调整',
        '13. 角注需要处理',
        '14. 链接到其他文件',
        '15. 少了直接创建mermed',
        '16. html语法的支持情况',
        '17. 那个图表的话就是记得有主题的lobchat有',
        '18. 在两个公式或图标中怎么插入空行',
        '    1. 然后箭头的移动应该选中',
      ].join('\n'),
      expected: [
        '# Paste Regression',
        '',
        '1输入不要固定的高度，',
        '',
        '测试yt那些',
        '',
        '1. 输入反斜杠东西出来的有点慢',
        '2. 右键单击图表，将其另存为本地磁盘上的 SVG、PNG 或 JPG 文件。',
        '3. 不同的主题',
        '4. 表格的渲染太慢了，打开的时候可以看到loadign',
        '5. 检查对',
        '',
        '`mindmap支持是否完整`\\',
        '3\\. 表格看看是否需要调整大小\\',
        '4\\.\\',
        '5\\. 斜杠工具栏\\',
        '6\\. 文件的拖入star\\',
        '7\\. todo之后就是会换行\\',
        '8\\. 从外部拖动文件进来，就是变成和我们一样的拖动文件的样式\\',
        '9\\. 给所有的换图标\\',
        '10\\. 这个md的解析和使用直接诶是乱套了\\',
        '11\\. 这个merger表格根本用不了\\',
        '1\\. 在他下面弄个反斜杠直接消失了\\',
        '12\\. 自动生成的目录部分的高度需要调整\\',
        '13\\. 角注需要处理\\',
        '14\\. 链接到其他文件\\',
        '15\\. 少了直接创建mermed\\',
        '16\\. html语法的支持情况\\',
        '17\\. 那个图表的话就是记得有主题的lobchat有\\',
        '18\\. 在两个公式或图标中怎么插入空行\\',
        '1\\. 然后箭头的移动应该选中',
      ].join('\n'),
    },
  ])('keeps a realistic note stable after save and reopen: $name', async ({ markdown, expected, convergentOnly }) => {
    if (convergentOnly) {
      await expectConvergentPersistedMarkdownRoundTrip(markdown, expected);
      return;
    }

    await expectStableMarkdownRoundTrip(markdown, expected);
  });

  it('keeps Chinese plain text trailing backslashes visible after opening a markdown file', async () => {
    const markdown = [
      '7）视图模式：支持大纲和文档列表视图，方便在不同段落和不同文件之间进行切换。\\',
      '8）跨平台：支持macOS、Windows和Linux系统。\\',
      '9）目前免费：这么好用的编辑器竟然是免费的。',
    ].join('\n');

    await expectConvergentPersistedMarkdownRoundTrip(
      markdown,
      [
        '7）视图模式：支持大纲和文档列表视图，方便在不同段落和不同文件之间进行切换。\\\\\\',
        '8）跨平台：支持macOS、Windows和Linux系统。\\\\\\',
        '9）目前免费：这么好用的编辑器竟然是免费的。',
      ].join('\n'),
      '切换。\\'
    );
  });
});
