export const themeColorTokens = {
  white: '#ffffff',
  transparentWhite: '#ffffff00',
  windowBackgroundLight: '#fcfcfc',
  windowBackgroundDark: '#050505',
  windowSymbolLight: '#27262b',
  windowSymbolDark: '#ededee',
  textPrimary: '#27272A',
  iconDefault: '#6b7280',
  accent: '#1E96EB',
  accentHover: '#167fd0',
  exportText: '#171717',
  exportSurface: '#ffffff',
  exportBorder: '#d4d4d4',
  exportMutedText: '#525252',
  exportCodeSurface: '#f5f5f5',
  mermaidText: '#27272A',
  mermaidBorder: '#d4d4d8',
  mermaidLine: '#71717a',
  mermaidSurface: '#FFFFFF',
  mermaidSurfaceSecondary: '#f4f4f5',
  mermaidSurfaceTertiary: '#fafafa',
  brandDiscord: '#5865F2',
  brandQq: '#12B7F5',
  brandWechat: '#07C160',
  brandGoogleBlue: '#4285F4',
  brandGoogleGreen: '#34A853',
  brandGoogleYellow: '#FBBC05',
  brandGoogleRed: '#EA4335',
  brandSlackRed: '#E01E5A',
  brandSlackBlue: '#36C5F0',
  brandSlackGreen: '#2EB67D',
  brandSlackYellow: '#ECB22E',
  qrForeground: '#97c7ecff',
  eventRed: '#FE002D',
  eventRedDarkText: '#FF6B6B',
  eventAmber: '#f59e0b',
  eventAmberDarkText: '#fbbf24',
  eventYellow: '#FEC900',
  eventYellowDarkText: '#FFE066',
  eventGreen: '#63DA38',
  eventGreenDarkText: '#8AE86B',
  eventBlue: '#008BFE',
  eventBlueDarkText: '#66B3FF',
  eventPurple: '#AD46FF',
  eventPurpleDarkText: '#C77FFF',
  eventBrown: '#B47D58',
  eventBrownDarkText: '#D4A882',
  eventDefault: '#9F9FA9',
  eventDefaultDarkText: '#B8B8C0',
  toolbarColorHexes: [
    '#f1fdf3', '#e6f4e7', '#d1e9d3', '#99cda9',
    '#e7f0d3', '#d2ea9c', '#abcb88', '#84b271',
    '#e3fdfc', '#cbf1f4', '#a6e3e8', '#71c9cd',
    '#fff9f9', '#ffdfe0', '#ffc1d0', '#fca9bd',
    '#f8ddfe', '#f2c0ff', '#c09fee', '#866ec6',
  ],
} as const;

export const themeTyporaBaseTokens = {
  background: '#ffffff',
  text: '#333333',
  selection: '#B5D6FC',
  monospace: '"Lucida Console", Consolas, "Courier", monospace',
} as const;

export const themeTyporaFixedLightAppFallbackDeclarations = [
  '--vlaina-color-soft-placeholder: #e1e1e1;',
  '--vlaina-color-editor-block-selection: var(--vlaina-color-accent);',
  '--vlaina-color-editor-block-selection-fg: #fefbf9;',
  '--vlaina-color-editor-block-selection-drag-box: rgb(190 223 254 / 0.42);',
  '--vlaina-color-brand-pink: #f08aa6;',
  '--vlaina-color-brand-pink-soft: rgb(240 138 166 / 0.12);',
  '--vlaina-color-danger-soft: #fef2f2;',
  '--vlaina-color-overlay: rgb(0 0 0 / 0.5);',
  '--vlaina-color-backdrop-soft: rgb(39 39 42 / 0.2);',
  '--vlaina-color-drop-overlay: rgb(255 255 255 / 0.2);',
  '--vlaina-color-shortcut-key-bg: #3f3f46;',
  '--vlaina-color-shortcut-key-fg: #f4f4f5;',
  '--vlaina-color-favorite-fg: #f59e0b;',
  '--vlaina-color-favorite-fg-muted: rgb(245 158 11 / 0.7);',
  '--vlaina-color-overlay-strong: rgb(0 0 0 / 0.6);',
  '--vlaina-color-overlay-weak: rgb(0 0 0 / 0.035);',
  '--vlaina-color-emoji-category-bg: var(--vlaina-color-surface-secondary);',
  '--vlaina-color-emoji-category-active-bg: #e4e4e7;',
  '--vlaina-color-unavailable-bg: #f3f4f6;',
  '--vlaina-color-unavailable-fg: #6b7280;',
  '--vlaina-color-media-surface: #000000;',
  '--vlaina-color-ai-review-added-fg: #166534;',
  '--vlaina-color-ai-review-added-bg: rgb(220 252 231 / 0.9);',
  '--vlaina-color-ai-review-removed-fg: #991b1b;',
  '--vlaina-color-ai-review-removed-bg: rgb(254 226 226 / 0.9);',
  '--vlaina-color-ai-review-removed-decoration: rgb(239 68 68 / 0.7);',
  '--vlaina-color-ai-review-panel: var(--vlaina-color-white);',
  '--vlaina-color-ai-review-panel-border: #e4e4e7;',
  '--vlaina-color-color-picker-default-bg: linear-gradient(135deg, var(--vlaina-color-white) 45%, var(--vlaina-color-danger) 45%, var(--vlaina-color-danger) 55%, var(--vlaina-color-white) 55%);',
  '--vlaina-color-panel-glass: linear-gradient(180deg, rgb(255 255 255 / 0.64), rgb(255 255 255 / 0.38));',
  '--vlaina-color-editor-frontmatter-placeholder: color-mix(in srgb, var(--vlaina-color-text-soft), transparent 18%);',
  '--vlaina-color-brand-google-gradient: linear-gradient(to right, #4285f4, #fbbc05, #34a853);',
  '--vlaina-color-quota-track: #e9e6df;',
  '--vlaina-color-quota-fill: var(--vlaina-sidebar-row-selected-text-soft);',
  '--vlaina-color-inverse-surface: #18181b;',
  '--vlaina-color-inverse-surface-hover: #27272a;',
  '--vlaina-color-inverse-text: #ffffff;',
  '--vlaina-color-membership-plus-bg: #f0f9ff;',
  '--vlaina-color-membership-plus-fg: #0284c7;',
  '--vlaina-color-membership-pro-bg: #ecfdf5;',
  '--vlaina-color-membership-pro-fg: #059669;',
  '--vlaina-color-membership-max-bg: #f5f3ff;',
  '--vlaina-color-membership-max-fg: #7c3aed;',
  '--vlaina-color-membership-ultra-bg: #18181b;',
  '--vlaina-color-membership-ultra-fg: #fbbf24;',
  '--vlaina-code-syntax-keyword: #d73a49;',
  '--vlaina-code-syntax-name: #6f42c1;',
  '--vlaina-code-syntax-function: #6f42c1;',
  '--vlaina-code-syntax-constant: #005cc5;',
  '--vlaina-code-syntax-type: #d73a49;',
  '--vlaina-code-syntax-operator: #24292e;',
  '--vlaina-code-syntax-string: #032f62;',
  '--vlaina-code-syntax-variable: #e36209;',
  '--vlaina-code-syntax-tag: #22863a;',
  '--vlaina-code-syntax-markup: #005cc5;',
  '--vlaina-code-syntax-list: #735c0f;',
  '--vlaina-code-syntax-invalid: #b31d28;',
  '--vlaina-code-syntax-addition-bg: #f0fff4;',
  '--vlaina-code-syntax-deletion-bg: #ffeef0;',
] as const;

export const themeTyporaFixedLightAppEffectDeclarations = [
  '--vlaina-shadow-find-match-active: inset 0 0 0 1px rgba(120, 53, 15, 0.2), 0 0 0 1px rgba(255, 176, 32, 0.45);',
  '--vlaina-shadow-ai-review-added: inset 0 -2px 0 rgb(34 197 94 / 0.38);',
  '--vlaina-shadow-ai-review-panel: var(--v-fl-sd, 0 20px 40px -12px rgb(0 0 0 / 0.1), 0 0 0 1px rgb(0 0 0 / 0.02));',
  '--vlaina-shadow-toolbar: var(--v-fl-sd, 0 10px 30px rgb(15 23 42 / 0.12), 0 2px 8px rgb(15 23 42 / 0.08));',
  '--vlaina-shadow-toolbar-submenu: var(--v-fl-sd, 0 16px 40px rgb(15 23 42 / 0.14), 0 4px 12px rgb(15 23 42 / 0.08));',
  '--vlaina-shadow-toolbar-dropdown: var(--v-fl-sd, 0 18px 36px rgb(15 23 42 / 0.08), 0 4px 12px rgb(15 23 42 / 0.06));',
  '--vlaina-shadow-toolbar-tooltip: 0 10px 24px rgba(0, 0, 0, 0.14);',
  '--vlaina-shadow-toolbar-error: 0 0 8px rgba(239, 68, 68, 0.4);',
  '--vlaina-shadow-menu: var(--v-fl-sd, 0 12px 36px -12px rgba(15, 23, 42, 0.24));',
  '--vlaina-shadow-xs: 0 1px 2px 0 rgb(0 0 0 / 0.05);',
  '--vlaina-shadow-sm: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);',
  '--vlaina-shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);',
  '--vlaina-shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);',
  '--vlaina-shadow-xl: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);',
  '--vlaina-shadow-2xl: 0 25px 50px -12px rgb(0 0 0 / 0.25);',
  '--vlaina-shadow-icon-hover: 0 6px 18px -10px rgb(0 0 0 / 0.35);',
  '--vlaina-filter-icon-hover: drop-shadow(0 4px 6px rgba(0, 0, 0, 0.1));',
  '--vlaina-shadow-menu-hover: 0 6px 20px rgba(0, 0, 0, 0.055), inset 0 1px 0 rgba(255, 255, 255, 0.7);',
  '--vlaina-shadow-popover: var(--v-fl-sd, 0 8px 24px rgba(15, 23, 42, 0.08), 0 2px 8px rgba(15, 23, 42, 0.04), inset 0 1px 0 rgba(255, 255, 255, 0.7));',
  '--vlaina-shadow-badge: 0 8px 18px rgba(15, 23, 42, 0.08);',
  '--vlaina-shadow-input-inset: inset 0 1px 0 rgba(255, 255, 255, 0.72);',
  '--vlaina-shadow-input-focus: inset 0 1px 0 rgba(255, 255, 255, 0.72), 0 1px 6px rgba(0, 0, 0, 0.04);',
  '--vlaina-shadow-control-active: 0 1px 2px rgba(0, 0, 0, 0.08);',
  '--vlaina-shadow-raised-soft: 0 4px 16px rgba(0, 0, 0, 0.04), inset 0 1px 0 rgba(255, 255, 255, 0.7);',
  '--vlaina-shadow-floating-panel: var(--v-fl-sd, 0 16px 40px rgba(15, 23, 42, 0.12));',
  '--vlaina-shadow-drag-preview: 0 20px 60px rgba(0, 0, 0, 0.3);',
  '--vlaina-shadow-panel-soft: 0 10px 30px rgba(0, 0, 0, 0.04);',
  '--vlaina-shadow-selection-soft: 0 2px 8px rgba(30, 150, 235, 0.06);',
  '--vlaina-shadow-accent-action: 0 0 0 3px rgba(65, 168, 234, 0.12), 0 10px 24px rgba(65, 168, 234, 0.28);',
  '--vlaina-shadow-drag-row: inset 0 1px 0 rgb(255 255 255 / 0.2), 0 10px 24px -18px rgba(30, 150, 235, 0.65);',
] as const;

export const themeEventColorTokens = {
  eventBgAlpha: 0.1,
  eventBgDarkAlpha: 0.2,
  eventBorderAlpha: 0.4,
  eventBorderDarkAlpha: 0.5,
  eventRingAlpha: 0.3,
  eventRingDarkAlpha: 0.2,
  eventFillAlpha: 0.3,
  eventFillDarkAlpha: 0.4,
  allDayBgAlpha: 0.15,
  allDayBgDarkAlpha: 0.25,
  allDayBorderAlpha: 0.5,
  allDayBorderDarkAlpha: 0.6,
  rainbowGradientAngle: '135deg',
  rainbowGradientColorCount: 6,
} as const;

export const themeRadiusTokens = {
  px4: '4px',
  px6: '6px',
  px8Var: 'var(--vlaina-radius-8px)',
} as const;

export const themeFontWeightTokens = {
  normal: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
} as const;

export const themeIconTokens = {
  fillNone: 'none',
  defaultCssSize: '1em',
  sizeXs: 12,
  sizeSm: 14,
  sizeSidebar: 15,
  sizeRow: 16,
  sizeCollapseTriangle: 16,
  sizeStarBadge: 16,
  sizeEditorDragHandle: 14,
  sizeCompact: 18,
  sizeMd: 20,
  sizeLg: 24,
  sizeTitlebarToggle: 25,
  sizeXl: 32,
  sizeQrPlaceholder: 34,
  sizeUploadPreview: 44,
  viewBoxDefault: '0 0 24 24',
  viewBoxStarBadge: '0 0 20 20',
  viewBoxPrimer: '0 0 16 16',
  viewBoxPhosphor: '0 0 256 256',
  strokeThin: 1.5,
  strokeHairline: 1,
  strokeDefault: 2,
  strokeEmphasis: 2.5,
  strokeCollapseTriangle: 2.25,
  strokeUploadSpinner: 3,
  strokeQrPlaceholder: 1.7,
} as const;

export const themeTypographyTokens = {
  exportTitleFontSize: '34px',
  exportTitleLineHeight: '1.16',
  exportBodyLineHeight: '1.72',
  exportHeadingLineHeight: '1.25',
  exportHeading1FontSize: '28px',
  exportHeading2FontSize: '23px',
  exportHeading3FontSize: '19px',
  exportCodeFontSize: '0.92em',
  iconLineHeight: 1,
  streamFallbackLineHeight: 0,
} as const;

export const themeExportLayoutTokens = {
  widthPx: 840,
  docxTitleAfterSpacing: 320,
  docxHeadingBeforeSpacing: 220,
  docxHeadingAfterSpacing: 120,
  docxCodeBeforeSpacing: 80,
  docxCodeAfterSpacing: 80,
  docxCodeFontSizeHalfPoints: 20,
  docxQuoteIndentLeft: 360,
  docxQuoteBeforeSpacing: 80,
  docxQuoteAfterSpacing: 80,
  hiddenHostLeft: '-10000px',
  hiddenHostTop: '0',
  pageMargin: '0',
  documentMargin: '0 auto',
  documentPadding: '56px 64px 72px',
  titleMargin: '0 0 28px',
  headingMargin: '1.5em 0 0.45em',
  blockMargin: '0.8em 0',
  blockquoteBorderLeft: '4px',
  blockquotePaddingLeft: '14px',
  inlineCodePadding: '0.12em 0.28em',
  prePadding: '14px 16px',
  preCodePadding: '0',
  mediaMaxWidth: '100%',
  mediaHeight: 'auto',
  tableWidth: '100%',
  tableBorderWidth: '1px',
  tableCellPadding: '7px 9px',
} as const;

export const themeMarkdownMetricTokens = {
  bodyFontSizePx: 17,
  inlineCodeFontSizePx: 17,
  inlineCodeExtraWidthPx: 8,
  bodyLineHeightExtraPx: 8,
  headingOneFontSizePx: 34,
  headingTwoFontSizePx: 29,
  headingThreeFontSizePx: 25,
  headingFourFontSizePx: 22,
  headingFiveFontSizePx: 19,
  headingSixFontSizePx: 17,
  headingOneLineHeightPx: 44,
  headingTwoLineHeightPx: 39,
  headingThreeLineHeightPx: 33,
  headingFourLineHeightPx: 30,
  headingFiveLineHeightPx: 27,
  headingSixLineHeightPx: 25,
  blockquoteContentInsetPx: 17,
  blockquotePaddingYPx: 20,
  codeBlockHeaderHeightPx: 40,
  codeBlockPaddingYPx: 16,
  ruleHeightPx: 30,
  blockGapPx: 20,
  listContentInsetPx: 32,
  listMarginYPx: 16,
  listItemMarginYPx: 12,
  tableMarginYPx: 32,
  tableCellPaddingYPx: 16,
  tableBorderYPx: 2,
  tableRowBorderYPx: 1,
} as const;

export const themeImageDragPlaceholderTokens = {
  editorPaddingPx: 80,
  containerPaddingPx: 60,
  defaultHeightPx: 100,
  marginPx: 8,
  borderWidth: '3px',
} as const;

export const themeTextAreaTokens = {
  heightAuto: 'auto',
  overflowAuto: 'auto',
  overflowHidden: 'hidden',
  minHeightPx: 0,
  collapsedMaxHeightPx: 0,
  unboundedMaxHeightPx: 100000,
  inlineRenameMaxHeightPx: 96,
  titleResizeHeightGuardPx: 2,
  titleResizeFallbackDelayMs: 120,
} as const;

export const themeAssetGridTokens = {
  gapPx: 8,
  paddingPx: 8,
  compactItemSizePx: 60,
  regularItemSizePx: 104,
  maxHeightPx: 280,
  minResolvedItemSizePx: 48,
} as const;

const whiteboardPaperDotRadiusPx = 0.65;
const whiteboardPaperLineWidthPx = 1;

export const themeWhiteboardTokens = {
  initialPanX: 0,
  initialPanY: 0,
  defaultZoom: 1,
  minZoom: 0.12,
  maxZoom: 4,
  zoomStep: 0.12,
  paperDotRadiusPx: whiteboardPaperDotRadiusPx,
  paperLineWidthPx: whiteboardPaperLineWidthPx,
  paperGridSizePx: {
    dots: 20,
    grid: 24,
    ruled: 24,
  },
  paperBackgroundImages: {
    blank: 'none',
    dots: `radial-gradient(circle, var(--vlaina-color-whiteboard-grid-dot) ${whiteboardPaperDotRadiusPx}px, transparent ${whiteboardPaperDotRadiusPx}px)`,
    grid: `linear-gradient(var(--vlaina-color-whiteboard-grid-dot) ${whiteboardPaperLineWidthPx}px, transparent ${whiteboardPaperLineWidthPx}px), linear-gradient(90deg, var(--vlaina-color-whiteboard-grid-dot) ${whiteboardPaperLineWidthPx}px, transparent ${whiteboardPaperLineWidthPx}px)`,
    ruled: `linear-gradient(transparent calc(100% - ${whiteboardPaperLineWidthPx}px), var(--vlaina-color-whiteboard-grid-dot) calc(100% - ${whiteboardPaperLineWidthPx}px))`,
  },
  wheelZoomIntensity: 0.0015,
  minElementWidthPx: 96,
  minElementHeightPx: 64,
  resizeHandlePx: 16,
  defaultPointerPressure: 0.5,
  minPointerPressure: 0.08,
  penBaseWidthPx: 1.4,
  penPressureWidthPx: 5.6,
  pencilBaseWidthPx: 0.9,
  pencilPressureWidthPx: 3.4,
  pencilOpacity: 0.74,
  markerBaseWidthPx: 8,
  markerPressureWidthPx: 14,
  markerOpacity: 0.34,
  fountainBaseWidthPx: 0.8,
  fountainPressureWidthPx: 8.8,
  watercolorBaseWidthPx: 10,
  watercolorPressureWidthPx: 18,
  watercolorOpacity: 0.22,
  crayonBaseWidthPx: 3.2,
  crayonPressureWidthPx: 8,
  crayonOpacity: 0.68,
  watercolorOuterWidthScale: 1.35,
  watercolorInnerOpacityScale: 0.7,
  watercolorWashOpacityScale: 0.36,
  watercolorWashWidthScale: 1.86,
  strokeEdgeFeatherWidthPx: 0.45,
  strokeTaperMinScale: 0.12,
  strokeTaperPointCount: 3,
  pressureDetailMediumThreshold: 0.52,
  pressureDetailHeavyThreshold: 0.76,
  pencilGrainOpacityScale: 0.34,
  pencilGrainWidthScale: 0.42,
  pencilGrainDashArray: '0.8 5.2',
  pencilGrainSecondaryOpacityScale: 0.2,
  pencilGrainSecondaryWidthScale: 0.26,
  pencilGrainSecondaryDashArray: '0.5 3.2 1.2 6.5',
  pencilGrainDashOffsetPx: 1.7,
  pencilEdgeJitter: 0.055,
  pencilPressureCoreOpacityScale: 0.24,
  pencilPressureCoreWidthScale: 0.3,
  markerCoreOpacityScale: 0.28,
  markerCoreWidthScale: 0.52,
  markerLineCap: 'butt' as const,
  markerNibAngleDeg: 90,
  markerNibMinWidthScale: 0.58,
  markerPressureCoreOpacityScale: 0.22,
  markerPressureCoreWidthScale: 0.34,
  crayonTextureOpacityScale: 0.45,
  crayonTextureWidthScale: 0.72,
  crayonTextureDashArray: '1 7',
  crayonTextureSecondaryOpacityScale: 0.3,
  crayonTextureSecondaryWidthScale: 0.54,
  crayonTextureSecondaryDashArray: '2.4 3.5 0.7 6',
  crayonTextureDashOffsetPx: 2.1,
  crayonEdgeJitter: 0.13,
  crayonPressureCoreOpacityScale: 0.3,
  crayonPressureCoreWidthScale: 0.28,
  crayonWaxOpacityScale: 0.28,
  crayonWaxWidthScale: 0.38,
  crayonWaxDashArray: '0.8 4.5',
  fountainCoreOpacityScale: 0.3,
  fountainCoreWidthScale: 0.22,
  fountainNibAngleDeg: -42,
  fountainNibMinWidthScale: 0.32,
  watercolorEdgeJitter: 0.075,
  watercolorPressureCoreOpacityScale: 0.62,
  watercolorPressureCoreWidthScale: 0.32,
  strokeSmoothing: {
    pen: 0.42,
    pencil: 0.22,
    marker: 0.5,
    fountain: 0.38,
    watercolor: 0.56,
    crayon: 0.18,
  },
  textureDashScaleExponent: 0.5,
  textureDashOffsetVariationScale: 0.42,
  strokeNoFill: 'none',
  strokeLineCap: 'round',
  strokeLineJoin: 'round',
  eraserRadiusPx: 1,
  strokeEraserRadiusPx: 10,
  minBrushSize: 0.35,
  maxBrushSize: 4,
  brushWheelStep: 0.12,
  brushWheelButtonDelta: 1,
  brushSizePresets: [0.5, 0.75, 1, 1.5, 2],
  brushSizePreviewBasePx: 6,
  strokePointMinDistancePx: 1.4,
  mousePressureSpeedPxPerMs: 1.2,
  mousePressureRange: {
    pen: { min: 0.26, max: 0.76 },
    pencil: { min: 0.2, max: 0.68 },
    marker: { min: 0.46, max: 0.62 },
    fountain: { min: 0.16, max: 0.82 },
    watercolor: { min: 0.4, max: 0.66 },
    crayon: { min: 0.32, max: 0.72 },
  },
  pointerPressureSmoothing: {
    pen: 0.46,
    pencil: 0.52,
    marker: 0.3,
    fountain: 0.42,
    watercolor: 0.26,
    crayon: 0.48,
  },
  strokeHitTolerancePx: 10,
  strokeSelectionPaddingPx: 6,
  strokeSelectionWidthPx: 1.4,
  selectionResizeEdgeHitSizePx: 14,
  selectionResizeHandleSizePx: 8,
  selectionResizeMinSizePx: 32,
  eraserSampleStepPx: 3,
  eraserTargetPreviewOpacity: 0.3,
  eraserTrailDecayFraction: 0.12,
  eraserTrailDecayIntervalMs: 34,
  eraserTrailOpacity: 0.22,
  eraserTrailTaperExponent: 1.35,
  eraserTrailWidthPx: 14,
  viewportCullingOverscanPx: 360,
  brushCursorStrokeWidthPx: 1,
  brushCursorInkOpacity: 1,
  brushCursorWashGuideOpacity: 0.2,
  brushColorSwatches: ['#27272a', '#ef4444', '#f59e0b', '#10b981', '#1e96eb', '#8b5cf6'],
  exportPaddingPx: 56,
  exportEmptyWidthPx: 1200,
  exportEmptyHeightPx: 800,
  exportElementRadiusPx: 8,
  exportFontSizePx: 15,
  exportTextLineHeightPx: 19,
  exportMaxTextLines: 6,
  imageDefaultWidthPx: 360,
  imageDefaultHeightPx: 240,
  fitViewPaddingPx: 96,
} as const;

export const themeBackdropTokens = {
  zIndex: 100,
  blurPx: 6,
  durationSeconds: 0.1,
  settingsModalBlurPx: 6,
  settingsModalDurationSeconds: 0.05,
  notesBlankWorkspaceDropZIndex: 70,
  notesBlankWorkspaceDropBlurPx: 6,
  notesBlankWorkspaceDropDurationSeconds: 0.18,
  moduleShortcutsBlurPx: 6,
  moduleShortcutsDurationSeconds: 0.05,
  accountDialogZIndex: 1000,
  accountDialogBlurPx: 8,
  accountDialogDurationSeconds: 0.05,
  createNotesRootZIndex: 9999,
  createNotesRootBlurPx: 8,
  createNotesRootDurationSeconds: 0.1,
} as const;

export const themeSidebarTokens = {
  width: 'var(--vlaina-width-sidebar-default)',
  mobileWidth: 'var(--vlaina-width-sidebar-mobile)',
  iconWidth: 'var(--vlaina-width-sidebar-icon)',
  recentNotesRootPathHintTextLeftOffsetPx: 40,
  recentNotesRootPathHintHorizontalPaddingPx: 12,
  recentNotesRootPathHintGapPx: 2,
  recentNotesRootPathHintEstimatedHeightPx: 34,
} as const;

export const themeCodeBlockEditorTokens = {
  fontSize: 'var(--vlaina-font-0875rem)',
  lineHeight: 'var(--vlaina-leading-175)',
  contentPadding: 'var(--vlaina-space-0)',
  contentMinHeight: 'var(--vlaina-size-175rem)',
  linePadding: 'var(--vlaina-padding-code-block-line)',
  gutterZIndex: 'var(--vlaina-z-10)',
  gutterPaddingLeft: 'var(--vlaina-space-05rem)',
} as const;

export const themeImageEdgeMaskTokens = {
  outerRadialInnerStop: '44%',
  outerRadialMidStop: '72%',
  outerRadialMidAlpha: 0.12,
  outerRadialEndAlpha: 0.2,
  outerVerticalStartAlpha: 0.18,
  outerVerticalEndAlpha: 0.2,
  outerVerticalInnerStart: '28%',
  outerVerticalInnerEnd: '72%',
  outerHorizontalStartAlpha: 0.16,
  outerHorizontalEndAlpha: 0.18,
  outerHorizontalInnerStart: '24%',
  outerHorizontalInnerEnd: '76%',
  outerBlur: 'var(--vlaina-size-10px)',
  outerOpacity: 'var(--vlaina-opacity-95)',
  innerBorderWidth: 'var(--vlaina-border-width-1)',
  innerBorderAlpha: 0.16,
  innerGlowSize: 'var(--vlaina-size-26px)',
  innerGlowAlpha: 0.22,
  innerVerticalStartAlpha: 0.16,
  innerVerticalEndAlpha: 0.18,
  innerVerticalInnerStart: '24%',
  innerVerticalInnerEnd: '76%',
  innerHorizontalStartAlpha: 0.14,
  innerHorizontalEndAlpha: 0.16,
  innerHorizontalInnerStart: '22%',
  innerHorizontalInnerEnd: '78%',
} as const;

export const themeMotionTokens = {
  opacityHidden: 0,
  opacityVisible: 1,
  opacityDeleting: 0.4,
  opacityPreview: 0.92,
  standardEase: [0.22, 1, 0.36, 1],
  notesRootModalEase: [0.19, 1, 0.22, 1],
  chatEmbeddedOverlayDuration: 0.1,
  chatEmbeddedSidebarHiddenX: '-100%',
  chatEmbeddedSidebarVisibleX: 0,
  chatEmbeddedSidebarSpringStiffness: 520,
  chatEmbeddedSidebarSpringDamping: 44,
  chatEmbeddedSidebarSpringMass: 0.82,
  chatUserEditInitialOpacity: 0.85,
  chatUserEditInitialX: 12,
  chatUserEditVisibleX: 0,
  chatUserEditDuration: 0.14,
  notesRootModalInitialScale: 0.96,
  notesRootModalVisibleScale: 1,
  notesRootModalY: 12,
  notesRootModalVisibleY: 0,
  notesRootModalDuration: 0.1,
  noteFindInitialScale: 0.98,
  noteFindVisibleScale: 1,
  noteFindInitialY: -10,
  noteFindVisibleY: 0,
  noteFindSpringStiffness: 500,
  noteFindSpringDamping: 35,
  noteFindShadowWithQuery: '0 8px 24px rgb(15 23 42 / 0.08), 0 1px 4px rgb(15 23 42 / 0.06)',
  noteFindShadowWithoutQuery: '0 4px 14px rgb(15 23 42 / 0.06)',
  noteFindReplaceCollapsedHeight: 0,
  noteFindReplaceExpandedHeight: 'auto',
  settingsSegmentedControlBounce: 0.15,
  settingsSegmentedControlDuration: 0.25,
  appViewSwitchCollapsedWidth: 32,
  toastInitialY: 50,
  toastVisibleY: 0,
  toastInitialScale: 0.3,
  toastVisibleScale: 1,
  toastExitScale: 0.5,
  toastExitDuration: 0.2,
  hoverPeekInitialX: -20,
  hoverPeekVisibleX: 0,
  settingsModalInitialScale: 0.96,
  settingsModalVisibleScale: 1,
  settingsModalY: 10,
  settingsModalVisibleY: 0,
  settingsModalDuration: 0.05,
  settingsModalEase: [0.16, 1, 0.3, 1],
  aiChannelPopulatedInitialY: 8,
  aiChannelPopulatedExitY: -6,
  aiChannelPopulatedDuration: 0.2,
  aiChannelEmptyInitialY: 6,
  aiChannelEmptyExitY: -4,
  aiChannelEmptyDuration: 0.18,
  linkEditorY: -4,
  linkEditorVisibleY: 0,
  linkEditorActionExitX: 4,
  linkEditorActionInitialX: -4,
  linkEditorActionVisibleX: 0,
  linkEditorInitialScale: 0.96,
  linkEditorVisibleScale: 1,
  linkEditorActionInitialScale: 0.8,
  linkEditorActionVisibleScale: 1,
  linkEditorActionTapScale: 0.9,
  scaleBreatheHidden: 0.98,
  scaleVisible: 1,
  slideY: 10,
} as const;

export const themeLinkTooltipTokens = {
  anchorOffsetPx: 8,
  viewportMarginPx: 12,
  centeredTransform: 'translateX(var(--vlaina-translate--50pct))',
  transformOrigin: 'center top',
  editorShellPaddingPx: 40,
  editorActionWidthPx: 36,
  editorAutofocusDelayMs: 50,
} as const;

export const themeImageResizeHandleTokens = {
  thickness: 'var(--vlaina-size-12px)',
  offset: 'calc(var(--vlaina-size-6px) * -1)',
  cornerSize: 'var(--vlaina-size-24px)',
  cornerZIndex: 'var(--vlaina-z-51)',
} as const;

export const themeOffscreenTokens = {
  clipboardLeft: '-9999px',
  clipboardTop: '0',
  blockDragPreviewLeft: '-10000px',
  blockDragPreviewTop: '-10000px',
} as const;

export const themeCaretOverlayTokens = {
  zIndex: 10001,
  blinkDuration: '1.05s',
  blinkHoldDelayMs: 220,
  visibleKeyframeEnd: '45%',
  hiddenKeyframeStart: '46%',
  opacityVisible: 1,
  opacityHidden: 0,
} as const;

export const themeStyleResetTokens = {
  animationNone: 'none',
  backgroundTransparent: 'transparent',
  borderNone: 'none',
  borderNoneImportant: 'none !important',
  borderRadiusNone: '0',
  boxShadowNone: 'none',
  colorTransparent: 'transparent',
  colorTransparentImportant: 'transparent !important',
  currentColor: 'currentColor',
  displayNone: 'none',
  fillNone: 'none',
  maxSizeNone: 'none',
  outlineNone: 'none',
  pointerEventsNone: 'none',
  transitionNone: 'none',
} as const;

export const themeRenderingTokens = {
  translateZ0: 'translateZ(0)',
  translate3dOffscreen: 'translate3d(-9999px, -9999px, 0)',
  translate3dZeroPx: 'translate3d(0px, 0px, 0)',
  translateCenter: 'translate(-50%, -50%)',
  translateCenterTop: 'translate(-50%, 0)',
  translateYCenter: 'translateY(-50%)',
  transformWillChange: 'transform',
  transformOpacityWillChange: 'transform, opacity',
  transformSizeWillChange: 'transform, width, height',
  backfaceHidden: 'hidden',
  visibilityHidden: 'hidden',
  userSelectNone: 'none',
  touchActionNone: 'none',
  overscrollBehaviorNone: 'none',
  overflowAnchorNone: 'none',
  transformNone: 'none',
  verticalAlignBaseline: 'baseline',
  overflowWrapAnywhere: 'anywhere',
  overflowWrapBreakWord: 'break-word',
  overflowWrapNormal: 'normal',
  whiteSpacePre: 'pre',
  whiteSpacePreWrap: 'pre-wrap',
  containStrict: 'strict',
  containLayoutPaintStyle: 'layout paint style',
  scrollPositionWillChange: 'scroll-position',
} as const;

export const themeEmojiPickerTokens = {
  maxRecentEmojis: 18,
  maxRecentIconsStorageChars: 16 * 1024,
  emojisPerRow: 9,
  emojiSizePx: 32,
  rowGapPx: 2,
  virtualTitleRowHeightPx: 28,
  virtualOverscanRows: 5,
} as const;

export const themeChatLayoutTokens = {
  embeddedSidebarWidth: 'min(clamp(16rem, 80%, 21rem), 86vw)',
} as const;

export const themeChatComposerTokens = {
  textareaMinHeightPx: 24,
  textareaMaxHeightPx: 320,
} as const;

export const themeChatImageViewerTokens = {
  minZoom: 0.2,
  maxZoom: 5,
  zoomStep: 0.12,
  fitPaddingBreakpointPx: 640,
  fitHorizontalPaddingCompactPx: 28,
  fitHorizontalPaddingWidePx: 96,
  fitVerticalPaddingCompactPx: 96,
  fitVerticalPaddingWidePx: 140,
  defaultViewportWidthPx: 1440,
  defaultViewportHeightPx: 900,
  minViewportSizePx: 1,
  previewMinZoomScale: 0.35,
  copiedResetDelayMs: 1200,
} as const;

export const themeUiFeedbackTokens = {
  defaultTooltipDelayMs: 250,
  copyFeedbackDurationMs: 1200,
  copyFeedbackClosingMs: 160,
  hoverPeekOpenDelayMs: 75,
  chatThinkingSelectionReleaseDelayMs: 250,
  chatThinkingSelectionSettleDelayMs: 120,
  editorDragHandleThrottleMs: 16,
  editorMarkdownSerializationDebounceMs: 500,
  editorThemeCompatibilityDecorationDebounceMs: 700,
  editorTextEditorLivePreviewDebounceMs: 180,
  editorPendingMarkdownCommitThrottleMs: 120,
  editorPendingMarkdownTestCommitThrottleMs: 0,
  editorCompositionSettleMs: 220,
  editorInitNoiseWindowMs: 500,
  notesSidebarSearchDebounceMs: 120,
  markdownFontSizePreviewStepPx: 32,
  imageToolbarCopyFeedbackDurationMs: 2000,
  fileTreeClickSuppressionCleanupDelayMs: 250,
  invalidFileNameToastIntervalMs: 1200,
  invalidFileNameToastDurationMs: 3500,
  errorToastDurationMs: 4500,
  providerApiKeyCopyDurationMs: 1500,
  toolbarTooltipDelayMs: 250,
  urlRailValidationErrorDurationMs: 500,
} as const;

export const themeFileTreeTokens = {
  imageThumbnailDecodeEdgePx: 64,
  imageLibraryThumbnailDecodeEdgePx: 320,
  imageHoverPreviewDelayMs: 150,
  imageLibraryRowHeightPx: 136,
  imageLibraryFallbackWidthPx: 400,
  imageLibraryFallbackHeightPx: 360,
  virtualRowHorizontalChromePx: 72,
  virtualRowDepthIndentPx: 12,
  virtualRowAverageCharacterWidthPx: 8,
  sidebarRowHorizontalChromePx: 136,
  sidebarRowDepthIndentPx: 16,
  sidebarMeasuredTextSafetyPx: 16,
} as const;

export const themeChatStreamTokens = {
  baseCharDelayMs: 20,
  minCharDelayMs: 20,
  adaptiveDelayQueueScale: 0.3,
  minAdaptiveCharDelayMs: 1,
  maxAdaptiveCharDelayMs: 18,
  minAppendWindowMs: 35,
  maxAppendWindowMs: 260,
  appendWindowRatio: 0.75,
  fallbackContentWidthPx: 640,
  minStablePrefixChars: 160,
} as const;

export const themeEditorLayoutTokens = {
  contentMaxWidthPx: 900,
  contentPaddingDesktopPx: 96,
  contentPaddingMobilePx: 48,
  contentOffsetTransition: 'margin-left 180ms cubic-bezier(0.25, 0.8, 0.25, 1)',
  findScrollPaddingPx: 96,
  findCenteredMinOffsetPx: 32,
  findBlockTopMinOffsetPx: 40,
  findBlockTopMaxOffsetPx: 160,
  findBlockTopViewportRatio: 0.26,
  defaultViewportWidthPx: 1200,
  autoCreateBlankDraftDelayMs: 0,
  autoSaveDebounceMs: 800,
  editorInitFallbackDelayMs: 30000,
  scrollRestoreTimeoutFallbackDelayMs: 160,
  restoreScrollFallbackDelayMs: 80,
} as const;

export const themeCoverLayerTokens = {
  objectFitFill: 'fill',
  sizeAuto: 'auto',
  sizeFull: '100%',
  positionCenter: '50%',
  transformOriginCenter: 'center center',
} as const;

export const themeCoverLayoutTokens = {
  minHeightPx: 120,
  maxHeightPx: 500,
  minScale: 1,
  maxScale: 10,
  defaultViewportHeightRatio: 0.236,
  fallbackViewportHeightPx: 1080,
} as const;

export const themeImageBlockStyleTokens = {
  normalTransition: 'width 0.1s ease-out, opacity 0.2s ease-out',
  displayBlock: 'block',
  maxWidthFull: '100%',
  widthFull: '100%',
  sizeFull: '100%',
  heightAuto: 'auto',
  aspectRatioAuto: 'auto',
} as const;

export const themeCropperTokens = {
  defaultCropX: 0,
  defaultCropY: 0,
  defaultCropWidth: 100,
  defaultCropHeight: 100,
  scaleBasePercent: 100,
  transformOriginTopLeft: 'top left',
} as const;

export const themeDomStyleTokens = {
  positionAbsolute: 'absolute',
  positionFixed: 'fixed',
  positionRelative: 'relative',
  cursorRowResize: 'row-resize',
  cursorColumnResize: 'col-resize',
  cursorGrabbing: 'grabbing',
  cursorPointer: 'pointer',
  cursorText: 'text',
  numericZero: 0,
  zIndexBehindString: '-1',
  sizeZero: '0',
  sizeZeroPx: '0px',
  sizeFull: '100%',
  zIndexBehind: -1,
  zIndexTextEditorPopup: '80',
  zIndexMax: '9999',
  zIndexResizeOverlay: '99999',
  zIndexForcedCaret: '2147483647',
  marginNone: '0',
  marginTopSettingsToggle: '3px',
  borderNone: '0',
  previewBorderRadius: '0.75rem',
  previewSaturateFilter: 'saturate(1.02)',
  badgeRight: '8px',
  badgeSize: '18px',
  badgeTop: '50%',
  starredPreviewPaddingRight: '30px',
  shellSidebarWidth: 'var(--vlaina-shell-sidebar-width)',
  heroIconHeaderSize: 'var(--vlaina-hero-icon-header-size)',
  localImageUnavailableSize: 'var(--vlaina-size-100px)',
  localImageLoadingSize: 'var(--vlaina-size-72px)',
  externalDragPreviewShadow: 'var(--vlaina-shadow-floating-panel)',
  fileTreePreviewSurface: 'var(--vlaina-sidebar-notes-surface)',
  fileTreePreviewBadgeColor: 'var(--vlaina-color-status-warning-fg)',
  hoverPeekDefaultWidthPx: 260,
  hoverPeekTriggerWidthPx: 48,
  toolbarTooltipOffsetPx: 8,
  editorPopupAnchorOffsetPx: 8,
  editorPopupFallbackX: 16,
  editorPopupFallbackY: 16,
  editorPopupHorizontalMarginPx: 12,
  editorDragHandleOffsetPx: 24,
  displayInlineBlock: 'inline-block',
  displayInlineFlex: 'inline-flex',
  displayFlex: 'flex',
  alignCenter: 'center',
  justifyCenter: 'center',
  iframeDefaultWidth: 560,
  iframeDefaultHeight: 315,
  iframeFrameBorder: '0',
  iframeScrollingNone: 'no',
  iframeLoadingLazy: 'lazy',
  imageDecodingAsync: 'async',
} as const;

export const themeQrTokens = {
  marginModules: 1,
  widthPx: 144,
} as const;

export const themeMermaidTokens = {
  labelSingleLineDy: '0.35em',
  labelFirstLineBaseDyEm: 0.35,
  labelLineOffsetEm: 0.6,
  labelNextLineDy: '1.2em',
  quadrantTextTopPaddingPx: 18,
} as const;

export const themeLazyLoadTokens = {
  coverPickerResetAfterCloseDelayMs: 200,
  coverPreviewDelayMs: 180,
  assetThumbnailRootMargin: '80px',
  assetThumbnailThreshold: 0.01,
  codeBlockRootMargin: '900px 0px',
  imageBlockRootMargin: '900px 0px',
  mermaidRootMargin: '900px 0px',
} as const;
