export const TYPORA_APP_CHROME_CLASSES = String.raw`typora-export-sidebar|typora-export-show-outline|typora-sourceview-on|typora-quick-open(?:-[\w-]+)?|ty-quick-open-[\w-]+|file-list-item(?:-[\w-]+)?|file-tree-node|file-library(?:-[\w-]+)?|file-library-tree|file-library-file-node|file-node(?:-[\w-]+)?|sidebar(?:-[\w-]+)?|footer-btn|ty-show-[\w-]+|typora-sidebar-resizer(?:-[\w-]+)?|outline(?:-[\w-]+)?|outline-content|popover-title|md-grid-board(?:-wrap)?|megamenu-[\w-]+|ty-menu-btn-area(?:-[\w-]+)?|ty-sidebar-search-panel|searchpanel-search-option-btn|form-control|auto-suggest-container|dropdown-menu|mac-seamless-mode`;

export const TYPORA_EDITOR_CHROME_CLASSES = String.raw`md-image-btn|md-image-input-src-btn|md-image-pick-file-btn|md-image-src-span|md-link|md-url|md-tag|md-expand|md-f-tooltip|md-notification-container|md-comment|md-meta|md-raw-inline|md-rawblock(?:-[\w-]+)?|md-htmlblock-panel|md-mathblock-panel|md-fences-adv-panel|md-fences-advanced|md-focus(?:-container)?|md-toc-tooltip|code-tooltip(?:-[\w-]+)?|ty-input|md-arrow|error-message|md-emoji-span|md-tab|ty-table-edit|md-resize-table|md-delete-table|typora-source|toggle-sourceview-btn|cm-overlay|cm-del|cm-table-row|cm-yaml|cm-block-start|cm-variable-3|cm-hr|cm-negative|cm-positive|cm-builtin`;

export const VLOOK_APP_CHROME_CLASSES = String.raw`v-mask(?:-close)?|v-welcome(?:-[\w-]+)?|v-nav-[\w-]+|v-doc(?:-[\w-]+)?|v-footnote-pn(?:-[\w-]+)?|v-link-info-list|v-link-error|v-font-style(?:-[\w-]+)?|v-fontinfo-[\w-]+|v-status-bar(?:-[\w-]+)?|v-shortcut-bar(?:-[\w-]+)?|v-toolbar(?:-[\w-]+)?|v-content(?:-[\w-]+)?|v-content-assistor|v-tool-tips|v-info-tips|v-tips|v-doc-lib-item|v-fill-width|v-search(?:-[\w-]+)?|v-link-chk-result|v-check-hash(?:-[\w-]+)?|v-audio-mini-control|v-new-version|v-para-nav-[\w-]+|v-chapter-nav(?:-[\w-]+)?|v-fig-nav(?:-[\w-]+)?|v-fullscreen-toolbar|v-print-tip|v-index-filter-result|v-pgbar|v-pic-in-pic|v-pip-btn|v-btn-done|v-fig-action|v-fig-page-num|v-toc(?:-title|-item|-folder)?|v-map-item|v-item-current|v-segment(?:-btn)?|v-spotlight(?:-in-dark)?|v-laser-cursor|v-loading|v-resume-reading|v-float-card|v-duration|v-transition-[\w-]+|v-rotate(?:45|90)|v-para-nav-mask-border|top-more|bottom-more|doc-copyright|v-copyright|laser-pointer|v-accent-btn|v-interactive|v-focus-info|v-focus-out`;

export const TYPORA_PAGE_CHROME_IDS = String.raw`vlook-toc|v-footer|v-debug|v-pdf-log|vk-footer-area|doc-lib-toc|v-para-nav-mask-border|md-notification|top-titlebar|typora-quick-open|typora-quick-open-input|typora-source|toc-dropmenu|typora-sidebar|typora-sidebar-resizer|ty-sidebar-search-back-btn|switch-file-list-btn|sidebar-new-file-btn|sidebar-search-btn|sidebar-files-menu|megamenu-back-btn|outline-content|close-outline-filter-btn|file-library(?:-[\w-]+)?|md-searchpanel|math-inline-preview|filesearch-[\w-]+`;

export const TYPORA_PAGE_CHROME_SELECTOR_PATTERNS = [
  /\[\s*class\s*\*=\s*["']?v-fontinfo-/i,
];

export const VLOOK_THEME_SETTING_OR_EXTENSION_CLASSES = String.raw`v-caption|v-cap-\d+|v-cap-cntr|v-post-card|v-badge-(?:name|value)|v-tbl-[\w-]+|v-table-[\w-]+|table-figure|v-empty-cell|v-freeze|td-span|v-long|v-column|v-tab-(?:group|box)|tab-group-wrap|tab-content-target|v-btn(?:-[\w-]+)?|btn(?:-[\w-]+)?|md-image-input-src-btn|md-expand|md-f-tooltip|v-pip-btn|mini|searchpanel-search-option-btn|ty-sidebar-search-panel|v-link-info-list-items|v-chapter-nav-[\w-]+|v-index-filter-result|v-print-tip|v-fullscreen-toolbar|v-stepwise|v-coating|v-audio-mini-control|v-page-break|v-fig(?:-[\w-]+)?|v-icon|v-svg-[\w-]+|v-img-[\w-]+|v-backdrop-blurs|html-for-mac|os-windows|os-linux|os-mac|enabled|gray|com|bk|pdfoff|first-p|wrap|unwrap|loading|pressed|selected|dark|light|current|left|right|title-[\w-]+|(?:rd|og|tu|ye|lm|gn|mn|ol|wn|aq|sk|cy|bu|se|la|vn|cf|au|pu|ro|pl|pk|gd|bn|gy|wt|bk|t[12])`;
