export const MAX_FILE_TREE_ENTRIES = 5000;
export const MAX_FILE_TREE_DIRECTORY_SCAN_ENTRIES = 10_000;
export const MAX_FILE_TREE_DEPTH = 24;
export const MAX_FILE_TREE_DERIVED_NODES = 20_000;
export const MAX_GIT_REPOSITORY_DETECTION_CONCURRENCY = 8;
