const MANAGED_FRONTMATTER_PREFIX = 'vlaina_';

export const KEY_COVER = `${MANAGED_FRONTMATTER_PREFIX}cover`;
export const KEY_ICON = `${MANAGED_FRONTMATTER_PREFIX}icon`;
export const KEY_CREATED = `${MANAGED_FRONTMATTER_PREFIX}created`;
export const KEY_UPDATED = `${MANAGED_FRONTMATTER_PREFIX}updated`;

const KEY_COVER_LAYOUT = `${MANAGED_FRONTMATTER_PREFIX}cover_layout`;
const KEY_COVER_X = `${MANAGED_FRONTMATTER_PREFIX}cover_x`;
const KEY_COVER_Y = `${MANAGED_FRONTMATTER_PREFIX}cover_y`;
const KEY_COVER_HEIGHT = `${MANAGED_FRONTMATTER_PREFIX}cover_height`;
const KEY_COVER_SCALE = `${MANAGED_FRONTMATTER_PREFIX}cover_scale`;
const KEY_ICON_SIZE = `${MANAGED_FRONTMATTER_PREFIX}icon_size`;

export { MANAGED_FRONTMATTER_PREFIX };

export const MANAGED_KEYS = new Set([
  KEY_COVER,
  KEY_COVER_LAYOUT,
  KEY_COVER_X,
  KEY_COVER_Y,
  KEY_COVER_HEIGHT,
  KEY_COVER_SCALE,
  KEY_ICON,
  KEY_ICON_SIZE,
  KEY_CREATED,
  KEY_UPDATED,
]);
