import {
    DEFAULT_PROSE_DOC_SCAN_NODE_LIMIT,
} from '../../shared/boundedProseNodeScan';

export const MAX_AUTOLINK_DECORATIONS = 1000;
export const MAX_AUTOLINK_DOC_SCAN_NODES = DEFAULT_PROSE_DOC_SCAN_NODE_LIMIT;
export const MAX_AUTOLINK_UPDATE_RANGE_SCAN_NODES = MAX_AUTOLINK_DOC_SCAN_NODES;
export const MAX_AUTOLINK_TEXT_SCAN_CHARS = 1024 * 1024;
export const MAX_AUTOLINK_TRANSACTION_STEP_TEXT_CHARS = 200_000;
export const MAX_AUTOLINK_CHANGED_CONTEXT_CHARS = 512;
export const AUTOLINK_TRIGGER_TEXT_PATTERN = /[:/.@]/;
