import { IconCategory, createIconItems, getIcon } from './types';

const ICONS = [
  'Home', 'House', 'HousePlus', 'HouseHeart', 'HousePlug', 'HouseWifi',
  'Building', 'Building2', 'Factory', 'Warehouse',
  'Hotel', 'BedDouble', 'BedSingle', 'Bed',
  'Bath', 'ShowerHead', 'Toilet',
  'Armchair', 'Sofa', 'RockingChair',
  'Lamp', 'LampDesk', 'LampFloor', 'LampCeiling', 'LampWallDown', 'LampWallUp',
  'DoorOpen', 'DoorClosed', 'DoorClosedLocked',
  'Fence', 'Mailbox', 'Blinds',
  'BrickWall', 'BrickWallFire', 'BrickWallShield',
  'Fan', 'Heater', 'AirVent',
  'Store', 'ShoppingBag', 'ShoppingCart', 'ShoppingBasket',
  'Construction', 'Landmark', 'LandPlot', 'University',
  'ConciergeBell',
  'Hospital', 'Ambulance', 'Stethoscope', 'Syringe', 'Pill', 'Tablets', 'PillBottle', 'Bandage',
  'School', 'School2', 'GraduationCap', 'Library', 'LibraryBig', 'BookOpen', 'Lectern',
  'Church', 'Cross', 'Castle',
  'Gavel', 'Scale',
  'Globe', 'Globe2', 'GlobeLock', 'Earth', 'EarthLock',
  'Map', 'MapPin', 'MapPinOff', 'MapPinned', 'MapPinPlus', 'MapPinMinus', 'MapPinCheck', 'MapPinX', 'MapPinHouse',
  'MapPinCheckInside', 'MapPinMinusInside', 'MapPinPlusInside', 'MapPinXInside', 'MapPinPen',
  'MapMinus', 'MapPlus',
  'Navigation', 'Navigation2', 'NavigationOff', 'Navigation2Off',
  'Compass', 'Locate', 'LocateFixed', 'LocateOff', 'LocationEdit',
  'Signpost', 'SignpostBig', 'Milestone',
  'Mountain', 'MountainSnow', 'Tent',
  'Trees', 'TreePine', 'TreeDeciduous', 'Palmtree',
  'Waves', 'Anchor', 'Sailboat', 'Ship',
  'Car', 'CarFront', 'CarTaxiFront', 'Caravan',
  'Truck', 'TruckElectric',
  'Bus', 'BusFront',
  'Bike', 'Motorbike',
  'Tractor',
  'Train', 'TramFront', 'TrainFront', 'TrainTrack', 'TrainFrontTunnel',
  'Plane', 'PlaneTakeoff', 'PlaneLanding',
  'Helicopter', 'TowerControl',
  'ShipWheel', 'Kayak', 'LifeBuoy',
  'Rocket', 'Satellite', 'Drone',
  'Forklift', 'CableCar',
  'Luggage', 'Backpack', 'BaggageClaim',
  'Fuel', 'EvCharger',
  'ParkingCircle', 'ParkingSquare', 'CircleParking', 'SquareParking', 'CircleParkingOff', 'SquareParkingOff',
  'ParkingCircleOff', 'ParkingSquareOff', 'ParkingMeter',
  'TrafficCone', 'Cone', 'Siren',
  'Route', 'RouteOff', 'Waypoints', 'Footprints',
  'UtilityPole', 'RailSymbol',
  'Calendar', 'Calendar1', 'CalendarDays', 'CalendarRange', 'CalendarClock',
  'CalendarPlus', 'CalendarPlus2', 'CalendarMinus', 'CalendarMinus2',
  'CalendarCheck', 'CalendarCheck2', 'CalendarX', 'CalendarX2',
  'CalendarHeart', 'CalendarSearch', 'CalendarFold', 'CalendarOff',
  'CalendarArrowUp', 'CalendarArrowDown', 'CalendarCog', 'CalendarSync',
  'Calendars',
  'Clock', 'Clock1', 'Clock2', 'Clock3', 'Clock4', 'Clock5',
  'Clock6', 'Clock7', 'Clock8', 'Clock9', 'Clock10', 'Clock11', 'Clock12',
  'ClockAlert', 'ClockArrowUp', 'ClockArrowDown', 'ClockCheck', 'ClockFading', 'ClockPlus',
  'AlarmClock', 'AlarmClockCheck', 'AlarmClockMinus', 'AlarmClockOff', 'AlarmClockPlus',
  'AlarmCheck', 'AlarmMinus', 'AlarmPlus', 'AlarmSmoke',
  'Timer', 'TimerOff', 'TimerReset',
  'Hourglass', 'Watch', 'History',
  'DollarSign', 'Euro', 'PoundSterling', 'IndianRupee', 'JapaneseYen', 'RussianRuble', 'SwissFranc',
  'GeorgianLari', 'PhilippinePeso', 'SaudiRiyal', 'TurkishLira', 'Bitcoin', 'Currency',
  'Coins', 'Banknote', 'BanknoteArrowUp', 'BanknoteArrowDown', 'BanknoteX',
  'Wallet', 'Wallet2', 'WalletCards', 'WalletMinimal',
  'CreditCard', 'CardSim', 'Receipt', 'ReceiptText',
  'ReceiptCent', 'ReceiptEuro', 'ReceiptIndianRupee', 'ReceiptJapaneseYen',
  'ReceiptPoundSterling', 'ReceiptRussianRuble', 'ReceiptSwissFranc', 'ReceiptTurkishLira',
  'PiggyBank', 'Vault',
  'CircleDollarSign', 'BadgeDollarSign', 'HandCoins',
  'Hammer', 'Wrench', 'Drill',
  'Axe', 'Shovel', 'Pickaxe', 'Anvil',
  'Scissors', 'Ruler', 'PencilRuler', 'RulerDimensionLine',
  'ToolCase',
  'HardHat', 'ShieldCheck', 'FireExtinguisher',
  'Refrigerator', 'Microwave', 'WashingMachine',
  'Tv', 'Tv2', 'TvMinimal',
  'Shredder', 'SolarPanel',
  'Table', 'Table2',
  'Sprout', 'Sprout', 'Leaf',
  'Frame', 'PictureInPicture', 'PictureInPicture2', 'Flame', 'FlameKindling',
  'FerrisWheel',
];

export const placeIcons: IconCategory = {
  id: 'place',
  name: 'Places',
  emoji: getIcon('MapPin'),
  icons: createIconItems(ICONS),
};
