import {
  floatingToolbarPlugin,
  colorMarksPlugin,
  blockAlignmentPlugin,
  headingPlugin,
  collapsePlugin,
  mathPlugin,
  mathEditorPlugin,
  slashPlugin,
  calloutPlugin,
  tablePlugin,
  selectAllPlugin,
  highlightPlugin,
  footnotePlugin,
  autolinkPlugin,
  linkTooltipPlugin,
  tocPlugin,
  mermaidPlugin,
  mermaidEditorPlugin,
  codePlugin,
  codeBlockPlugins,
  frontmatterPlugin,
  videoPlugin,
  abbrPlugin,
  taskListClickPlugin,
  listTabIndentPlugin,
  listCollapsePlugin,
  markdownLinkPlugin,
  clipboardPlugin,
  imageBlockPlugin,
  imageUploadPlugin,
  textSelectionOverlayPlugin,
  editorFindPlugin,
  blankAreaDragBoxPlugin,
  blockControlsPlugin,
  atomicBlockKeyboardNavigationPlugin,
  endBlankClickPlugin,
  nativeDragGuardPlugin,
  containerBoundaryShiftSelectionPlugin,
  hrAutoParagraphPlugin,
  autoPairPlugin,
  titleNavigationPlugin,
  typewriterModePlugin,
} from '../plugins';

export const customPluginGroups = [
  {
    name: 'floating-toolbar',
    plugins: [
      floatingToolbarPlugin,
      ...colorMarksPlugin,
      ...blockAlignmentPlugin,
    ],
  },
  {
    name: 'headings',
    plugins: [
      ...headingPlugin,
      collapsePlugin,
    ],
  },
  {
    name: 'math',
    plugins: [
      ...mathPlugin,
      mathEditorPlugin,
    ],
  },
  {
    name: 'blocks',
    plugins: [
      slashPlugin,
      ...calloutPlugin,
      ...tablePlugin,
      selectAllPlugin,
      ...highlightPlugin,
      ...footnotePlugin,
    ],
  },
  {
    name: 'links',
    plugins: [
      autolinkPlugin,
      linkTooltipPlugin,
      markdownLinkPlugin,
    ],
  },
  {
    name: 'generated-blocks',
    plugins: [
      ...tocPlugin,
      ...mermaidPlugin,
      mermaidEditorPlugin,
      ...frontmatterPlugin,
      ...codePlugin,
      ...codeBlockPlugins,
      ...videoPlugin,
      abbrPlugin,
    ],
  },
  {
    name: 'lists-clipboard-images',
    plugins: [
      taskListClickPlugin,
      listTabIndentPlugin,
      listCollapsePlugin,
      clipboardPlugin,
      imageUploadPlugin,
      ...imageBlockPlugin,
    ],
  },
  {
    name: 'interaction-overlays',
    plugins: [
      textSelectionOverlayPlugin,
      editorFindPlugin,
      nativeDragGuardPlugin,
      blockControlsPlugin,
      blankAreaDragBoxPlugin,
      atomicBlockKeyboardNavigationPlugin,
      containerBoundaryShiftSelectionPlugin,
      autoPairPlugin,
      hrAutoParagraphPlugin,
      endBlankClickPlugin,
      titleNavigationPlugin,
      typewriterModePlugin,
    ],
  },
];

export const customPlugins = customPluginGroups.flatMap((group) => group.plugins);
