import { ComponentType, SVGProps } from 'react';
import { PenLine, Pin } from 'lucide-react';
import { 
  MinusIcon,
  XMarkIcon,
  PlusIcon,
  TrashIcon,
  CogIcon,
  MagnifyingGlassIcon,
  CheckIcon,
  CheckCircleIcon,
  HomeIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  ArrowPathIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  ShareIcon,
  Bars3Icon,
  ListBulletIcon,
  FunnelIcon,
  ArrowsUpDownIcon,
  FlagIcon,
  ArrowUturnLeftIcon,
  InformationCircleIcon,
  ExclamationTriangleIcon,
  ExclamationCircleIcon,
  NoSymbolIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpRightIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  ViewColumnsIcon,
  ArrowTopRightOnSquareIcon,
  MapPinIcon,
  CalendarIcon,
  ChartPieIcon,
  UserIcon,
  ArrowLeftOnRectangleIcon,
  UsersIcon,
  SunIcon,
  MoonIcon,
  ComputerDesktopIcon,
  SwatchIcon,
  FolderIcon,
  FolderOpenIcon,
  DocumentPlusIcon,
  DocumentTextIcon,
  PhotoIcon,
  ArchiveBoxIcon,
  CloudIcon,
  LockClosedIcon,
  GlobeAltIcon,
  PaperClipIcon,
  CodeBracketIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  MicrophoneIcon,
  SpeakerWaveIcon,
  SparklesIcon,
  LanguageIcon,
  ClockIcon,
  StarIcon,
  HeartIcon,
  BeakerIcon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3Icon as AlignCenterIcon, 
  ArrowsRightLeftIcon,
  CommandLineIcon,
  ChevronUpDownIcon,
  Square2StackIcon
} from '@heroicons/react/24/outline';

// Custom Icons
import { NewChatIcon } from './custom/NewChatIcon';
import { SquareCheckBigIcon } from './custom/SquareCheckBigIcon';
import { CropIcon } from './custom/CropIcon';
import { SendIcon } from './custom/SendIcon';
import { SquareStopIcon } from './custom/SquareStopIcon';

export type IconSource = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string }>;

export const icons: Record<string, IconSource> = {
  // --- Window Controls ---
  'window.minimize': MinusIcon,
  'window.maximize': StopIcon, // Reinstated Heroicons StopIcon
  'window.close': XMarkIcon,

  // --- Common Actions ---
  'common.add': PlusIcon,
  'common.delete': TrashIcon,
  'common.remove': MinusIcon,
  'common.edit': NewChatIcon,
  'common.settings': CogIcon,
  'common.search': MagnifyingGlassIcon,
  'common.close': XMarkIcon,
  'common.check': CheckIcon,
  'common.checkCircle': CheckCircleIcon,
  'common.radio': CheckCircleIcon, 
  'common.home': HomeIcon,
  'common.more': EllipsisHorizontalIcon,
  'common.moreVert': EllipsisVerticalIcon,
  'common.refresh': ArrowPathIcon,
  'common.copy': Square2StackIcon,
  'common.download': ArrowDownTrayIcon,
  'common.upload': ArrowUpTrayIcon,
  'common.share': ShareIcon,
  'common.menu': Bars3Icon,
  'common.list': ListBulletIcon,
  'common.filter': FunnelIcon,
  'common.sort': ArrowsUpDownIcon,
  'common.flag': FlagIcon,
  'common.undo': ArrowUturnLeftIcon,
  'common.info': InformationCircleIcon,
  'common.warning': ExclamationTriangleIcon,
  'common.error': ExclamationCircleIcon,
  'common.blocked': NoSymbolIcon,
  'common.block': NoSymbolIcon,
  'common.compose': NewChatIcon,
  'common.rename': PenLine,
  'common.pin': Pin,
  'common.pinOutline': Pin,
  'common.sparkle': SparklesIcon,
  'common.send': SendIcon,
  'common.language': LanguageIcon,

  // --- Navigation ---
  'nav.chevronRight': ChevronRightIcon,
  'nav.chevronLeft': ChevronLeftIcon,
  'nav.chevronDown': ChevronDownIcon,
  'nav.chevronUp': ChevronUpIcon,
  'nav.arrowRight': ArrowRightIcon,
  'nav.arrowLeft': ArrowLeftIcon,
  'nav.arrowUpRight': ArrowUpRightIcon,
  'nav.back': ArrowLeftIcon,
  'nav.collapse': ChevronDoubleLeftIcon,
  'nav.expand': ChevronDoubleRightIcon,
  'nav.fullscreen': ArrowsPointingOutIcon,
  'nav.exitFullscreen': ArrowsPointingInIcon,
  'nav.split': ViewColumnsIcon,
  'nav.external': ArrowTopRightOnSquareIcon,
  'nav.location': MapPinIcon,
  'nav.unfold': ChevronUpDownIcon,

  // --- Sidebar/App Modules ---
  'sidebar.todo': SquareCheckBigIcon,
  'sidebar.calendar': CalendarIcon,
  'sidebar.stats': ChartPieIcon,
  'sidebar.completed': CheckCircleIcon,
  'sidebar.collapse': ChevronDoubleLeftIcon,
  'sidebar.panel': ViewColumnsIcon,
  
  // --- User/Auth ---
  'user.profile': UserIcon,
  'user.logout': ArrowLeftOnRectangleIcon,
  'user.person': UserIcon,
  'user.switch': UsersIcon,

  // --- Theme/Appearance ---
  'theme.light': SunIcon,
  'theme.dark': MoonIcon,
  'theme.system': ComputerDesktopIcon,
  'theme.palette': SwatchIcon,
  'theme.sunny': SunIcon,

  // --- Files & Folders ---
  'file.folder': FolderIcon,
  'file.folderOpen': FolderOpenIcon,
  'file.add': DocumentPlusIcon,
  'file.text': DocumentTextIcon,
  'file.image': PhotoIcon,
  'file.imagePlus': DocumentPlusIcon,
  'file.archive': ArchiveBoxIcon,
  'file.cloud': CloudIcon,
  'file.cloudOff': NoSymbolIcon,
  'file.lock': LockClosedIcon,
  'file.public': GlobeAltIcon,
  'file.attach': PaperClipIcon,
  'file.brokenImage': ExclamationCircleIcon,

  // --- Editor/Content ---
  'editor.code': CodeBracketIcon,
  'editor.list': ListBulletIcon,
  'editor.crop': CropIcon,
  'editor.alignLeft': Bars3BottomLeftIcon,
  'editor.alignCenter': AlignCenterIcon, 
  'editor.alignRight': Bars3BottomRightIcon,
  'editor.checkSquare': CheckCircleIcon,
  'editor.keyboard': CommandLineIcon,
  'editor.type': SwatchIcon,

  // --- Media ---
  'media.play': PlayIcon,
  'media.pause': PauseIcon,
  'media.stop': SquareStopIcon,
  'media.mic': MicrophoneIcon,
  'media.volume': SpeakerWaveIcon,

  // --- Misc/Specific ---
  'misc.clock': ClockIcon,
  'misc.star': StarIcon,
  'misc.heart': HeartIcon,
  'misc.shuffle': ArrowsRightLeftIcon,
  'misc.activity': ChartPieIcon, 
  'misc.lab': BeakerIcon,
  'misc.box': ArchiveBoxIcon,
  // --- Legacy / Compatibility ---
  'legacy.unfold': ChevronUpDownIcon,
};

export type IconName = keyof typeof icons;
