import { ComponentType, SVGProps } from 'react';
import { Crown, ListOrdered, PenLine, Pin, Quote } from 'lucide-react';
import { 
  MinusIcon,
  XMarkIcon,
  PlusIcon,
  TrashIcon,
  CogIcon,
  MagnifyingGlassIcon,
  CheckIcon,
  CheckCircleIcon,
  HomeIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  ArrowPathIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  ShareIcon,
  Bars3Icon,
  ListBulletIcon,
  FunnelIcon,
  ArrowsUpDownIcon,
  FlagIcon,
  ArrowUturnLeftIcon,
  InformationCircleIcon,
  ExclamationTriangleIcon,
  ExclamationCircleIcon,
  NoSymbolIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpRightIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  ViewColumnsIcon,
  ArrowTopRightOnSquareIcon,
  MapPinIcon,
  CalendarIcon,
  ChartPieIcon,
  UserIcon,
  ArrowLeftOnRectangleIcon,
  UsersIcon,
  SunIcon,
  MoonIcon,
  ComputerDesktopIcon,
  SwatchIcon,
  FolderIcon,
  FolderOpenIcon,
  DocumentPlusIcon,
  DocumentTextIcon,
  PhotoIcon,
  ArchiveBoxIcon,
  CloudIcon,
  LockClosedIcon,
  GlobeAltIcon,
  PaperClipIcon,
  TagIcon,
  CodeBracketIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  MicrophoneIcon,
  SparklesIcon,
  LanguageIcon,
  ClockIcon,
  StarIcon,
  HeartIcon,
  BeakerIcon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3Icon as AlignCenterIcon, 
  ArrowsRightLeftIcon,
  CommandLineIcon,
  ChevronUpDownIcon,
  Square2StackIcon,
  EyeIcon,
  EyeSlashIcon
} from '@heroicons/react/24/outline';

import { NewChatIcon } from './custom/mit/NewChatIcon';
import { SquareCheckBigIcon } from './custom/mit/SquareCheckBigIcon';
import { CropIcon } from './custom/mit/CropIcon';
import { SendIcon } from './custom/mit/SendIcon';
import { SquareStopIcon } from './custom/mit/SquareStopIcon';
import { TemporaryChatOffIcon } from './custom/mit/TemporaryChatOffIcon';
import { TemporaryChatOnIcon } from './custom/mit/TemporaryChatOnIcon';
import { PrimerPinIcon } from './custom/mit/PrimerPinIcon';
import { PrimerUnpinIcon } from './custom/mit/PrimerUnpinIcon';
import { ActivityIcon } from './custom/mit/ActivityIcon';
import { GoogleIcon } from './custom/mit/GoogleIcon';
import { ReviewRetryIcon } from './custom/mit/ReviewRetryIcon';
import { ReviewApplyIcon } from './custom/mit/ReviewApplyIcon';
import { ReviewCloseIcon } from './custom/mit/ReviewCloseIcon';
import { SidebarDockIcon } from './custom/mit/SidebarDockIcon';

export type IconSource = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string }>;

export const icons: Record<string, IconSource> = {
  'window.minimize': MinusIcon,
  'window.maximize': StopIcon,
  'window.close': XMarkIcon,
  'common.add': PlusIcon,
  'common.delete': TrashIcon,
  'common.remove': MinusIcon,
  'common.edit': NewChatIcon,
  'common.settings': CogIcon,
  'common.search': MagnifyingGlassIcon,
  'common.close': XMarkIcon,
  'common.reviewClose': ReviewCloseIcon,
  'common.check': CheckIcon,
  'common.reviewApply': ReviewApplyIcon,
  'common.checkCircle': CheckCircleIcon,
  'common.radio': CheckCircleIcon,
  'common.home': HomeIcon,
  'common.more': EllipsisHorizontalIcon,
  'common.moreVert': EllipsisVerticalIcon,
  'common.refresh': ArrowPathIcon,
  'common.reviewRetry': ReviewRetryIcon,
  'common.copy': Square2StackIcon,
  'common.eye': EyeIcon,
  'common.eyeOff': EyeSlashIcon,
  'common.download': ArrowDownTrayIcon,
  'common.upload': ArrowUpTrayIcon,
  'common.share': ShareIcon,
  'common.menu': Bars3Icon,
  'common.list': ListBulletIcon,
  'common.filter': FunnelIcon,
  'common.sort': ArrowsUpDownIcon,
  'common.flag': FlagIcon,
  'common.undo': ArrowUturnLeftIcon,
  'common.info': InformationCircleIcon,
  'common.warning': ExclamationTriangleIcon,
  'common.error': ExclamationCircleIcon,
  'common.blocked': NoSymbolIcon,
  'common.block': NoSymbolIcon,
  'common.compose': NewChatIcon,
  'common.quote': Quote,
  'common.tag': TagIcon,
  'common.rename': PenLine,
  'common.pin': Pin,
  'common.pinPrimer': PrimerPinIcon,
  'common.unpinPrimer': PrimerUnpinIcon,
  'common.pinOutline': Pin,
  'common.sparkle': SparklesIcon,
  'common.send': SendIcon,
  'common.language': LanguageIcon,
  'common.cloud': CloudIcon,
  'common.google': GoogleIcon,
  'chat.temporary.off': TemporaryChatOffIcon,
  'chat.temporary.on': TemporaryChatOnIcon,
  'nav.chevronRight': ChevronRightIcon,
  'nav.chevronLeft': ChevronLeftIcon,
  'nav.chevronDown': ChevronDownIcon,
  'nav.chevronUp': ChevronUpIcon,
  'nav.arrowRight': ArrowRightIcon,
  'nav.arrowLeft': ArrowLeftIcon,
  'nav.arrowUpRight': ArrowUpRightIcon,
  'nav.back': ArrowLeftIcon,
  'nav.sidebarDock': SidebarDockIcon,
  'nav.collapse': ChevronDoubleLeftIcon,
  'nav.expand': ChevronDoubleRightIcon,
  'nav.fullscreen': ArrowsPointingOutIcon,
  'nav.exitFullscreen': ArrowsPointingInIcon,
  'nav.split': ViewColumnsIcon,
  'nav.external': ArrowTopRightOnSquareIcon,
  'nav.location': MapPinIcon,
  'nav.unfold': ChevronUpDownIcon,
  'sidebar.todo': SquareCheckBigIcon,
  'sidebar.calendar': CalendarIcon,
  'sidebar.stats': ChartPieIcon,
  'sidebar.completed': CheckCircleIcon,
  'sidebar.panel': ViewColumnsIcon,
  'user.profile': UserIcon,
  'user.logout': ArrowLeftOnRectangleIcon,
  'user.person': UserIcon,
  'user.switch': UsersIcon,
  'theme.light': SunIcon,
  'theme.dark': MoonIcon,
  'theme.system': ComputerDesktopIcon,
  'theme.palette': SwatchIcon,
  'theme.sunny': SunIcon,
  'file.folder': FolderIcon,
  'file.folderOpen': FolderOpenIcon,
  'file.add': DocumentPlusIcon,
  'file.text': DocumentTextIcon,
  'file.image': PhotoIcon,
  'file.imagePlus': DocumentPlusIcon,
  'file.archive': ArchiveBoxIcon,
  'file.cloud': CloudIcon,
  'file.cloudOff': NoSymbolIcon,
  'file.lock': LockClosedIcon,
  'file.public': GlobeAltIcon,
  'file.attach': PaperClipIcon,
  'file.brokenImage': ExclamationCircleIcon,
  'editor.code': CodeBracketIcon,
  'editor.list': ListBulletIcon,
  'editor.listOrdered': ListOrdered,
  'editor.crop': CropIcon,
  'editor.alignLeft': Bars3BottomLeftIcon,
  'editor.alignCenter': AlignCenterIcon,
  'editor.alignRight': Bars3BottomRightIcon,
  'editor.checkSquare': CheckCircleIcon,
  'editor.keyboard': CommandLineIcon,
  'editor.type': SwatchIcon,
  'media.play': PlayIcon,
  'media.pause': PauseIcon,
  'media.stop': SquareStopIcon,
  'media.mic': MicrophoneIcon,
  'misc.clock': ClockIcon,
  'misc.crown': Crown,
  'misc.star': StarIcon,
  'misc.heart': HeartIcon,
  'misc.shuffle': ArrowsRightLeftIcon,
  'misc.activity': ActivityIcon,
  'misc.lab': BeakerIcon,
  'misc.box': ArchiveBoxIcon,
};

export type IconName = keyof typeof icons;
