export const INLINE_DATA_IMAGE_TARGET_HINT_PATTERN = /\bdata(?:\\*:|&|&#)/i
export const MARKDOWN_INLINE_DATA_IMAGE_HINT_PATTERN = /!\[[^\]\n]{0,512}\]\(\s*<?\s*data(?:\\*:|&|&#)/i
export const MESSAGE_IMAGE_TOKEN_HINT_PATTERN = /!\[[^\]\n]{0,512}\]\(|<img\b/i

export const MAX_INLINE_IMAGE_PERSISTENCE_PENDING_SESSIONS = 100
export const MAX_INLINE_IMAGE_PERSISTENCE_MESSAGE_NODES = 10_000
export const MAX_INLINE_IMAGE_PERSISTENCE_VERSIONS = 20
export const MAX_INLINE_IMAGE_PERSISTENCE_BRANCH_MESSAGES = 100
export const MAX_INLINE_IMAGE_PERSISTENCE_BRANCH_DEPTH = 1
export const MAX_INLINE_IMAGE_TOKENS_PER_CONTENT = 2000
export const MAX_INLINE_IMAGE_PERSISTENCE_SOURCES = 1000
export const MAX_INLINE_IMAGE_FALLBACK_TARGET_CHARS = 512 * 1024
export const MAX_INLINE_IMAGE_FALLBACK_HTML_TAG_END_SCAN_CHARS = 64 * 1024
export const MAX_INLINE_IMAGE_FALLBACK_INLINE_CODE_RANGES = 4000
export const MAX_CHAT_SESSION_DELETE_CONCURRENCY = 5
export const MAX_INLINE_IMAGE_ORPHAN_DELETE_CONCURRENCY = 4
