export function getModelLogoById(modelId: string): string | undefined {
  if (!modelId) return undefined;
  
  // Map keywords to filenames in /public/models/
  const logoMap: Record<string, string> = {
    'flux': 'flux.png',
    'midjourney': 'midjourney.png',
    'mj-': 'midjourney.png',
    'suno': 'suno.png',
    'chirp': 'suno.png',
    'luma': 'luma.png',
    'keling': 'keling.png',
    'vidu': 'vidu.png',
    'hailuo': 'hailuo.png',
    'ideogram': 'ideogram.svg',
    'codestral': 'codestral.png',
    'dbrx': 'dbrx.png',
    'upstage': 'upstage.png',
    'voyage': 'voyageai.png',
    'tele': 'tele.png',
    'bigcode': 'bigcode.webp',
    'rakuten': 'rakutenai.png',
    'adept': 'adept.png',
    'ai21': 'ai21.png',
    'mediatek': 'mediatek.png',
    'xirang': 'xirang.png',
    'mimo': 'mimo.svg',
    'aimass': 'aimass.png',
    'aisingapore': 'aisingapore.png',
    'bge-': 'bge.webp',
    'codegeex': 'codegeex.png',
    'dianxin': 'dianxin.png',
    'flashaudio': 'flashaudio.png',
    'gpt-5.1': 'gpt-5.1.png',
    'gpt-5-mini': 'gpt-5-mini.png',
    'gpt-5-nano': 'gpt-5-nano.png',
    'gpt-5': 'gpt-5.png',
    'gpt-image': 'gpt_image_1.png',
    'gryphe': 'gryphe.png',
    'mythomax': 'gryphe.png',
    'ibm': 'ibm.png',
    'granite': 'ibm.png',
    'internvl': 'internvl.png',
    'ling': 'ling.png',
    'llava': 'llava.png',
    'magic': 'magic.png',
    'minicpm': 'minicpm.webp',
    'nous': 'nousresearch.png',
    'hermes': 'nousresearch.png',
    'palm': 'palm.png',
    'bison': 'palm.png',
    'pangu': 'pangu.svg',
    'pixtral': 'pixtral.png',
    'tokenflux': 'tokenflux.png',
    'bytedance': 'byte_dance.svg',
    'embedding': 'embedding.png',
    'o1-': 'gpt_o1.png',
    'gpt-4': 'gpt_4.png',
    'gpt-3.5': 'gpt_3.5.png',
    'gpt-': 'chatgpt.jpeg',
    'claude': 'claude.png',
    'gemini': 'gemini.png',
    'deepseek': 'deepseek.png',
    'qwen': 'qwen.png',
    'qwq': 'qwen.png',
    'llama': 'llama.png',
    'mixtral': 'mixtral.png',
    'mistral': 'mixtral.png', // Using mixtral logo for mistral too? Or separate? Check file list. 'mixtral_dark.png' exists.
    'moonshot': 'moonshot.webp',
    'kimi': 'moonshot.webp',
    'baichuan': 'baichuan.png',
    'glm': 'chatglm.png',
    'zhipu': 'zhipu.png',
    'doubao': 'doubao.png',
    'minimax': 'minimax.png',
    'abab': 'minimax.png',
    'yi-': 'yi.png',
    'grok': 'grok.png',
    'hunyuan': 'hunyuan.png',
    'spark': 'sparkdesk.png',
    'internlm': 'internlm.png',
    'jina': 'jina.png',
    'cohere': 'cohere.png',
    'copilot': 'copilot.png',
    'dall-e': 'dalle.png',
    'stable-diffusion': 'stability.png',
    'sdxl': 'stability.png',
    'perplexity': 'perplexity.png',
    'sonar': 'perplexity.png',
    'step': 'step.png',
    'wenxin': 'wenxin.png',
    'ernie': 'wenxin.png',
    'google': 'google.png',
    'microsoft': 'microsoft.png',
    'nvidia': 'nvidia.png',
    'huggingface': 'huggingface.png',
    '360': '360.png'
  };

  for (const key in logoMap) {
    if (new RegExp(key, 'i').test(modelId)) {
      return `/models/${logoMap[key]}`;
    }
  }

  return undefined;
}