export const TYPORA_FIXED_LIGHT_APP_FALLBACK_DECLARATIONS = [
  '--vlaina-color-soft-placeholder: #e1e1e1;',
  '--vlaina-color-editor-block-selection: var(--vlaina-color-accent);',
  '--vlaina-color-editor-block-selection-fg: #fefbf9;',
  '--vlaina-color-editor-block-selection-drag-box: rgb(190 223 254 / 0.42);',
  '--vlaina-color-brand-pink: #f08aa6;',
  '--vlaina-color-brand-pink-soft: rgb(240 138 166 / 0.12);',
  '--vlaina-color-danger-soft: #fef2f2;',
  '--vlaina-color-overlay: rgb(0 0 0 / 0.5);',
  '--vlaina-color-backdrop-soft: rgb(39 39 42 / 0.2);',
  '--vlaina-color-drop-overlay: rgb(255 255 255 / 0.2);',
  '--vlaina-color-shortcut-key-bg: #3f3f46;',
  '--vlaina-color-shortcut-key-fg: #f4f4f5;',
  '--vlaina-color-favorite-fg: #f59e0b;',
  '--vlaina-color-favorite-fg-muted: rgb(245 158 11 / 0.7);',
  '--vlaina-color-overlay-strong: rgb(0 0 0 / 0.6);',
  '--vlaina-color-overlay-weak: rgb(0 0 0 / 0.035);',
  '--vlaina-color-emoji-category-bg: var(--vlaina-color-surface-secondary);',
  '--vlaina-color-emoji-category-active-bg: #e4e4e7;',
  '--vlaina-color-unavailable-bg: #f3f4f6;',
  '--vlaina-color-unavailable-fg: #6b7280;',
  '--vlaina-color-media-surface: #000000;',
  '--vlaina-color-ai-review-added-fg: #166534;',
  '--vlaina-color-ai-review-added-bg: rgb(220 252 231 / 0.9);',
  '--vlaina-color-ai-review-removed-fg: #991b1b;',
  '--vlaina-color-ai-review-removed-bg: rgb(254 226 226 / 0.9);',
  '--vlaina-color-ai-review-removed-decoration: rgb(239 68 68 / 0.7);',
  '--vlaina-color-ai-review-panel: var(--vlaina-color-white);',
  '--vlaina-color-ai-review-panel-border: #e4e4e7;',
  '--vlaina-color-color-picker-default-bg: linear-gradient(135deg, var(--vlaina-color-white) 45%, var(--vlaina-color-danger) 45%, var(--vlaina-color-danger) 55%, var(--vlaina-color-white) 55%);',
  '--vlaina-color-panel-glass: linear-gradient(180deg, rgb(255 255 255 / 0.64), rgb(255 255 255 / 0.38));',
  '--vlaina-color-editor-frontmatter-placeholder: color-mix(in srgb, var(--vlaina-color-text-soft), transparent 18%);',
  '--vlaina-color-brand-google-gradient: linear-gradient(to right, #4285f4, #fbbc05, #34a853);',
  '--vlaina-color-quota-track: #e9e6df;',
  '--vlaina-color-quota-fill: var(--vlaina-sidebar-row-selected-text-soft);',
  '--vlaina-color-inverse-surface: #18181b;',
  '--vlaina-color-inverse-surface-hover: #27272a;',
  '--vlaina-color-inverse-text: #ffffff;',
  '--vlaina-color-membership-plus-bg: #f0f9ff;',
  '--vlaina-color-membership-plus-fg: #0284c7;',
  '--vlaina-color-membership-pro-bg: #ecfdf5;',
  '--vlaina-color-membership-pro-fg: #059669;',
  '--vlaina-color-membership-max-bg: #f5f3ff;',
  '--vlaina-color-membership-max-fg: #7c3aed;',
  '--vlaina-color-membership-ultra-bg: #18181b;',
  '--vlaina-color-membership-ultra-fg: #fbbf24;',
  '--vlaina-code-syntax-keyword: #d73a49;',
  '--vlaina-code-syntax-name: #6f42c1;',
  '--vlaina-code-syntax-function: #6f42c1;',
  '--vlaina-code-syntax-constant: #005cc5;',
  '--vlaina-code-syntax-type: #d73a49;',
  '--vlaina-code-syntax-operator: #24292e;',
  '--vlaina-code-syntax-string: #032f62;',
  '--vlaina-code-syntax-variable: #e36209;',
  '--vlaina-code-syntax-tag: #22863a;',
  '--vlaina-code-syntax-markup: #005cc5;',
  '--vlaina-code-syntax-list: #735c0f;',
  '--vlaina-code-syntax-invalid: #b31d28;',
  '--vlaina-code-syntax-addition-bg: #f0fff4;',
  '--vlaina-code-syntax-deletion-bg: #ffeef0;',
] as const;
