import type { AiQuickActionVariant } from './aiQuickActionVariants';

export const AI_QUICK_ACTION_VARIANTS: AiQuickActionVariant[] = [
  {
    id: 'inline-command',
    name: 'Inline Command',
    description: 'Closest to a native command bar: minimal chrome and tight hierarchy.',
    layout: 'wrap',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_14px_34px_-26px_rgba(15,23,42,0.14)]',
    selectionShellClassName: 'border border-neutral-200 bg-neutral-50/70',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-neutral-200 bg-white px-3 py-1.5 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
    labelClassName: 'bg-neutral-100',
  },
  {
    id: 'apple-frost',
    name: 'Apple Frost',
    description: 'The most directly Apple-like white-glass interpretation.',
    layout: 'wrap',
    surfaceClassName: 'border border-slate-200 bg-[linear-gradient(180deg,_#ffffff,_#f8fbff)]',
    panelClassName: 'border border-white/80 bg-white/82 shadow-[0_18px_38px_-28px_rgba(148,163,184,0.22)] backdrop-blur-xl',
    selectionShellClassName: 'border border-white/80 bg-white/70',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-white/90 text-slate-600',
    inputShellClassName: 'border border-white/80 bg-white/78 text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-white/90 bg-white/82 px-3 py-1.5 text-[12px] font-medium text-slate-700',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-slate-500',
  },
  {
    id: 'selection-card',
    name: 'Selection Card',
    description: 'The selected text is elevated as the primary object, then commands follow.',
    layout: 'split',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_14px_32px_-24px_rgba(15,23,42,0.12)]',
    selectionShellClassName: 'border border-neutral-200 bg-white shadow-[0_8px_18px_-16px_rgba(15,23,42,0.12)]',
    selectionTextClassName: 'text-neutral-800',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-col gap-2',
    actionClassName: 'rounded-xl border border-neutral-200 bg-white px-3 py-2 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'rounded-2xl border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
  },
  {
    id: 'warm-note',
    name: 'Warm Note',
    description: 'Softer note-taking warmth without drifting into decoration.',
    layout: 'stack',
    surfaceClassName: 'border border-amber-100 bg-[#fffdf8]',
    panelClassName: 'border border-amber-100 bg-white shadow-[0_16px_34px_-26px_rgba(217,119,6,0.12)]',
    selectionShellClassName: 'border border-amber-100 bg-[#fffaf0]',
    selectionTextClassName: 'text-stone-700',
    scopeClassName: 'bg-amber-100 text-amber-700',
    inputShellClassName: 'border border-amber-100 bg-white text-stone-800',
    promptClassName: 'text-[13px] font-medium text-stone-500',
    actionsClassName: 'mt-3 flex flex-col gap-2',
    actionClassName: 'justify-between rounded-xl border border-amber-100 bg-white px-3 py-2 text-[12px] font-medium text-stone-700',
    featuredActionClassName: 'border-stone-900 bg-stone-900 text-white',
    sendButtonClassName: 'bg-stone-900 text-white',
    iconClassName: 'text-amber-500',
  },
  {
    id: 'calm-segment',
    name: 'Calm Segment',
    description: 'Treats preset prompts like modes, but keeps them understated.',
    layout: 'rail',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_12px_28px_-22px_rgba(15,23,42,0.12)]',
    selectionShellClassName: 'border border-neutral-200 bg-neutral-50/80',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex gap-1.5 overflow-hidden rounded-2xl bg-neutral-100 p-1',
    actionClassName: 'rounded-xl px-3 py-2 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'bg-white text-neutral-900 shadow-[0_1px_2px_rgba(0,0,0,0.06)]',
    secondaryActionClassName: 'bg-transparent',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
  },
  {
    id: 'precision-grid',
    name: 'Precision Grid',
    description: 'A tool-centric layout for users who think in explicit commands.',
    layout: 'grid',
    surfaceClassName: 'border border-slate-200 bg-white',
    panelClassName: 'border border-slate-200 bg-white shadow-[0_12px_26px_-20px_rgba(51,65,85,0.12)]',
    selectionShellClassName: 'border border-slate-200 bg-slate-50',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-slate-100 text-slate-600',
    inputShellClassName: 'border border-slate-200 bg-white text-slate-800',
    promptClassName: 'font-mono text-[12px] text-slate-500',
    actionsClassName: 'mt-3 grid grid-cols-2 gap-2',
    actionClassName: 'justify-center rounded-lg border border-slate-200 bg-white px-3 py-2 font-mono text-[11px] uppercase tracking-[0.08em] text-slate-700',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    fontClassName: 'font-mono',
    iconClassName: 'text-slate-500',
  },
  {
    id: 'executive-white',
    name: 'Executive White',
    description: 'High-restraint premium white, almost invisible until needed.',
    layout: 'wrap',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_8px_22px_-16px_rgba(15,23,42,0.12)]',
    selectionShellClassName: 'border border-neutral-200 bg-white',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-900',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-neutral-200 bg-white px-3 py-1.5 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
    labelClassName: 'bg-neutral-100',
  },
  {
    id: 'document-halo',
    name: 'Document Halo',
    description: 'Places a faint halo around the selected passage to reinforce scope.',
    layout: 'wrap',
    surfaceClassName: 'border border-slate-200 bg-[linear-gradient(180deg,_#ffffff,_#fbfcff)]',
    panelClassName: 'border border-slate-200 bg-white shadow-[0_16px_32px_-24px_rgba(99,102,241,0.12)]',
    selectionShellClassName: 'border border-indigo-100 bg-indigo-50/50 shadow-[0_0_0_3px_rgba(224,231,255,0.5)]',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-indigo-100 text-indigo-700',
    inputShellClassName: 'border border-slate-200 bg-white text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-indigo-100 bg-white px-3 py-1.5 text-[12px] font-medium text-slate-700',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-indigo-500',
  },
  {
    id: 'porcelain-panel',
    name: 'Porcelain Panel',
    description: 'Crisp, pale-blue ceramic feeling with clean professional polish.',
    layout: 'wrap',
    surfaceClassName: 'border border-sky-100 bg-[#fbfdff]',
    panelClassName: 'border border-sky-100 bg-white shadow-[0_16px_34px_-26px_rgba(14,165,233,0.12)]',
    selectionShellClassName: 'border border-sky-100 bg-[#f8fbff]',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-sky-100 text-sky-700',
    inputShellClassName: 'border border-sky-100 bg-white text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-sky-100 bg-white px-3 py-1.5 text-[12px] font-medium text-slate-700 shadow-[1px_2px_0_rgba(224,242,254,0.9)]',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-sky-500',
  },
  {
    id: 'selection-underline',
    name: 'Selection Underline',
    description: 'Editorial treatment where command text feels more textual than button-like.',
    layout: 'rail',
    surfaceClassName: 'border border-stone-200 bg-[#fffefc]',
    panelClassName: 'border border-stone-200 bg-white shadow-[0_14px_30px_-24px_rgba(120,113,108,0.12)]',
    selectionShellClassName: 'border-b border-stone-300 rounded-none bg-transparent px-0',
    selectionTextClassName: 'font-serif text-stone-700',
    scopeClassName: 'bg-stone-100 text-stone-600',
    inputShellClassName: 'border-b border-stone-300 rounded-none bg-transparent px-0 text-stone-800',
    promptClassName: 'font-serif text-[15px] text-stone-500',
    actionsClassName: 'mt-4 flex gap-4 overflow-hidden',
    actionClassName: 'rounded-none border-b border-transparent bg-transparent px-0 py-1 text-[12px] font-medium text-stone-600',
    featuredActionClassName: 'border-stone-900 text-stone-900',
    sendButtonClassName: 'bg-stone-900 text-white rounded-full',
    fontClassName: 'font-serif',
    iconClassName: 'text-stone-400',
  },
  {
    id: 'soft-command',
    name: 'Soft Command',
    description: 'Turns the whole interaction into a quieter, softer bar.',
    layout: 'wrap',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-neutral-50/70 shadow-[0_14px_30px_-24px_rgba(15,23,42,0.1)]',
    selectionShellClassName: 'border border-neutral-200 bg-white',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-white text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-neutral-200 bg-white px-3 py-1.5 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
  },
  {
    id: 'clarity-stack',
    name: 'Clarity Stack',
    description: 'Preset prompts read like concrete edit operations, one per line.',
    layout: 'stack',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_14px_28px_-22px_rgba(15,23,42,0.12)]',
    selectionShellClassName: 'border border-neutral-200 bg-neutral-50',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-col gap-2',
    actionClassName: 'justify-between rounded-xl border border-neutral-200 bg-white px-3 py-2 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
  },
  {
    id: 'titanium-light',
    name: 'Titanium Light',
    description: 'Cool premium-metal neutrality with a very polished edge.',
    layout: 'grid',
    surfaceClassName: 'border border-zinc-200 bg-[linear-gradient(180deg,_#ffffff,_#f5f5f5)]',
    panelClassName: 'border border-zinc-200 bg-white shadow-[0_16px_32px_-24px_rgba(113,113,122,0.14)]',
    selectionShellClassName: 'border border-zinc-200 bg-[#fafafa]',
    selectionTextClassName: 'text-zinc-700',
    scopeClassName: 'bg-zinc-100 text-zinc-600',
    inputShellClassName: 'border border-zinc-200 bg-white text-zinc-800',
    promptClassName: 'text-[13px] font-medium text-zinc-500',
    actionsClassName: 'mt-3 grid grid-cols-2 gap-2',
    actionClassName: 'justify-center rounded-xl border border-zinc-200 bg-white px-3 py-2 text-[12px] font-medium text-zinc-700',
    featuredActionClassName: 'border-zinc-900 bg-zinc-900 text-white',
    sendButtonClassName: 'bg-zinc-900 text-white',
    iconClassName: 'text-zinc-500',
  },
  {
    id: 'paper-command',
    name: 'Paper Command',
    description: 'A clean notebook tone for longer writing flows.',
    layout: 'split',
    surfaceClassName: 'border border-stone-200 bg-[#fffef9]',
    panelClassName: 'border border-stone-200 bg-white shadow-[0_16px_32px_-24px_rgba(120,113,108,0.12)]',
    selectionShellClassName: 'border border-stone-200 bg-[#fcfbf7]',
    selectionTextClassName: 'text-stone-700',
    scopeClassName: 'bg-stone-100 text-stone-600',
    inputShellClassName: 'border border-stone-200 bg-white text-stone-800',
    promptClassName: 'text-[13px] font-medium text-stone-500',
    actionsClassName: 'mt-3 flex flex-col gap-2',
    actionClassName: 'rounded-xl border border-stone-200 bg-white px-3 py-2 text-[12px] font-medium text-stone-700',
    featuredActionClassName: 'rounded-2xl border-stone-900 bg-stone-900 text-white',
    sendButtonClassName: 'bg-stone-900 text-white',
    iconClassName: 'text-stone-500',
  },
  {
    id: 'studio-pane',
    name: 'Studio Pane',
    description: 'Feels like a refined pro app control pane, but still lightweight.',
    layout: 'grid',
    surfaceClassName: 'border border-slate-200 bg-[#fbfcff]',
    panelClassName: 'border border-slate-200 bg-white shadow-[0_16px_30px_-24px_rgba(15,23,42,0.14)]',
    selectionShellClassName: 'border border-slate-200 bg-slate-50',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-slate-100 text-slate-600',
    inputShellClassName: 'border border-slate-200 bg-white text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 grid grid-cols-2 gap-2',
    actionClassName: 'justify-center rounded-2xl border border-slate-200 bg-white px-3 py-2 text-[12px] font-medium text-slate-700 shadow-[1px_2px_0_rgba(226,232,240,0.85)]',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-slate-500',
  },
  {
    id: 'ink-command',
    name: 'Ink Command',
    description: 'More textual and editorial, less “button UI”.',
    layout: 'stack',
    surfaceClassName: 'border border-zinc-200 bg-white',
    panelClassName: 'border border-zinc-200 bg-white shadow-[0_14px_28px_-22px_rgba(0,0,0,0.12)]',
    selectionShellClassName: 'border-b border-zinc-300 rounded-none bg-transparent px-0',
    selectionTextClassName: 'text-zinc-800',
    scopeClassName: 'bg-zinc-100 text-zinc-600',
    inputShellClassName: 'border-b border-zinc-300 rounded-none bg-transparent px-0 text-zinc-900',
    promptClassName: 'text-[14px] font-medium text-zinc-500',
    actionsClassName: 'mt-4 flex flex-col gap-2',
    actionClassName: 'justify-between rounded-none border-b border-zinc-200 bg-transparent px-0 py-2 text-[12px] font-medium text-zinc-700',
    featuredActionClassName: 'border-zinc-900 text-zinc-900',
    sendButtonClassName: 'bg-zinc-900 text-white rounded-full',
    iconClassName: 'text-zinc-500',
  },
  {
    id: 'glass-desk',
    name: 'Glass Desk',
    description: 'A brighter glass desk aesthetic grounded by a concrete selection card.',
    layout: 'wrap',
    surfaceClassName: 'border border-sky-100 bg-[radial-gradient(circle_at_top,_#ffffff,_#f5fbff)]',
    panelClassName: 'border border-white/80 bg-white/78 shadow-[0_20px_40px_-30px_rgba(14,165,233,0.18)] backdrop-blur-xl',
    selectionShellClassName: 'border border-white/90 bg-white/76',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-white/90 text-slate-600',
    inputShellClassName: 'border border-white/80 bg-white/74 text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-white/90 bg-white/82 px-3 py-1.5 text-[12px] font-medium text-slate-700',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-sky-500',
  },
  {
    id: 'command-pills',
    name: 'Command Pills',
    description: 'Turns the presets into soft verbs, almost like keyboard suggestions.',
    layout: 'wrap',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_12px_28px_-22px_rgba(15,23,42,0.12)]',
    selectionShellClassName: 'border border-neutral-200 bg-neutral-50',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2.5',
    actionClassName: 'rounded-full border border-neutral-200 bg-white px-3.5 py-2 text-[12px] font-medium text-neutral-700 shadow-[1px_2px_0_rgba(229,231,235,0.85)]',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
  },
  {
    id: 'soft-lilac',
    name: 'Soft Lilac',
    description: 'A faint intelligent-product tint without looking trendy.',
    layout: 'rail',
    surfaceClassName: 'border border-violet-100 bg-white',
    panelClassName: 'border border-violet-100 bg-white shadow-[0_16px_30px_-24px_rgba(139,92,246,0.12)]',
    selectionShellClassName: 'border border-violet-100 bg-[#fbf9ff]',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-violet-100 text-violet-700',
    inputShellClassName: 'border border-violet-100 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex gap-2 overflow-hidden',
    actionClassName: 'rounded-full border border-violet-100 bg-white px-3 py-1.5 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-violet-500',
  },
  {
    id: 'editor-tabs',
    name: 'Editor Tabs',
    description: 'Preset actions become clean little tabs below the command line.',
    layout: 'rail',
    surfaceClassName: 'border border-slate-200 bg-white',
    panelClassName: 'border border-slate-200 bg-white shadow-[0_12px_28px_-22px_rgba(15,23,42,0.12)]',
    selectionShellClassName: 'border border-slate-200 bg-slate-50',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-slate-100 text-slate-600',
    inputShellClassName: 'border border-slate-200 bg-white text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex gap-1.5 overflow-hidden rounded-2xl bg-slate-100 p-1',
    actionClassName: 'rounded-xl px-3 py-2 text-[12px] font-medium text-slate-700',
    featuredActionClassName: 'bg-white text-slate-900 shadow-[0_1px_2px_rgba(0,0,0,0.06)]',
    secondaryActionClassName: 'bg-transparent',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-slate-500',
  },
  {
    id: 'floating-pane',
    name: 'Floating Pane',
    description: 'A slightly more detached panel for a richer transient tool feel.',
    layout: 'split',
    surfaceClassName: 'border border-slate-200 bg-[#fcfcfd]',
    panelClassName: 'border border-slate-200 bg-white shadow-[0_22px_44px_-30px_rgba(15,23,42,0.18)]',
    selectionShellClassName: 'border border-slate-200 bg-white shadow-[0_8px_18px_-16px_rgba(15,23,42,0.1)]',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-slate-100 text-slate-600',
    inputShellClassName: 'border border-slate-200 bg-white text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex flex-col gap-2',
    actionClassName: 'rounded-xl border border-slate-200 bg-white px-3 py-2 text-[12px] font-medium text-slate-700',
    featuredActionClassName: 'rounded-2xl border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-slate-500',
  },
  {
    id: 'prose-pane',
    name: 'Prose Pane',
    description: 'Slightly more literary, but still rooted in editing utility.',
    layout: 'stack',
    surfaceClassName: 'border border-stone-200 bg-[#fffefb]',
    panelClassName: 'border border-stone-200 bg-white shadow-[0_16px_30px_-24px_rgba(120,113,108,0.12)]',
    selectionShellClassName: 'border-b border-stone-300 rounded-none bg-transparent px-0',
    selectionTextClassName: 'font-serif text-stone-700',
    scopeClassName: 'bg-stone-100 text-stone-600',
    inputShellClassName: 'border-b border-stone-300 rounded-none bg-transparent px-0 text-stone-800',
    promptClassName: 'font-serif text-[15px] text-stone-500',
    actionsClassName: 'mt-4 flex flex-col gap-2',
    actionClassName: 'justify-between rounded-none border-b border-stone-200 bg-transparent px-0 py-2 text-[12px] font-medium text-stone-700',
    featuredActionClassName: 'border-stone-900 text-stone-900',
    sendButtonClassName: 'bg-stone-900 text-white rounded-full',
    fontClassName: 'font-serif',
    iconClassName: 'text-stone-400',
  },
  {
    id: 'mono-tool',
    name: 'Mono Tool',
    description: 'Monospaced and exacting for users who like explicit command systems.',
    layout: 'grid',
    surfaceClassName: 'border border-zinc-200 bg-white',
    panelClassName: 'border border-zinc-200 bg-white shadow-[0_12px_26px_-20px_rgba(0,0,0,0.12)]',
    selectionShellClassName: 'border border-zinc-200 bg-zinc-50',
    selectionTextClassName: 'font-mono text-zinc-700',
    scopeClassName: 'bg-zinc-100 text-zinc-600',
    inputShellClassName: 'border border-zinc-200 bg-white text-zinc-800',
    promptClassName: 'font-mono text-[12px] text-zinc-500',
    actionsClassName: 'mt-3 grid grid-cols-2 gap-2',
    actionClassName: 'justify-center rounded-lg border border-zinc-200 bg-white px-3 py-2 font-mono text-[11px] uppercase tracking-[0.08em] text-zinc-700',
    featuredActionClassName: 'border-zinc-900 bg-zinc-900 text-white',
    sendButtonClassName: 'bg-zinc-900 text-white',
    fontClassName: 'font-mono',
    iconClassName: 'text-zinc-500',
  },
  {
    id: 'silent-chrome',
    name: 'Silent Chrome',
    description: 'Almost no visual noise, only enough chrome to orient the user.',
    layout: 'wrap',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_8px_18px_-14px_rgba(15,23,42,0.1)]',
    selectionShellClassName: 'border border-neutral-200 bg-white',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-transparent bg-neutral-100 px-3 py-1.5 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
  },
  {
    id: 'shell-blueprint',
    name: 'Shell Blueprint',
    description: 'A systematic, almost product-spec style command treatment.',
    layout: 'grid',
    surfaceClassName: 'border border-sky-100 bg-[#fbfdff]',
    panelClassName: 'border border-sky-100 bg-white shadow-[0_16px_30px_-24px_rgba(14,165,233,0.12)]',
    selectionShellClassName: 'border border-sky-100 bg-[#f7fcff]',
    selectionTextClassName: 'font-mono text-slate-700',
    scopeClassName: 'bg-sky-100 text-sky-700',
    inputShellClassName: 'border border-sky-100 bg-white text-slate-800',
    promptClassName: 'font-mono text-[12px] text-slate-500',
    actionsClassName: 'mt-3 grid grid-cols-2 gap-2',
    actionClassName: 'justify-center rounded-md border border-sky-100 bg-white px-3 py-2 font-mono text-[11px] uppercase tracking-[0.08em] text-slate-700',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    fontClassName: 'font-mono',
    iconClassName: 'text-sky-500',
  },
  {
    id: 'night-panel',
    name: 'Night Panel',
    description: 'One dark option in case the white-direction is too soft later.',
    layout: 'wrap',
    surfaceClassName: 'border border-zinc-800 bg-[#0f0f10]',
    panelClassName: 'border border-white/10 bg-white/[0.04] shadow-[0_24px_48px_-30px_rgba(0,0,0,0.55)] backdrop-blur-xl',
    selectionShellClassName: 'border border-white/10 bg-white/[0.03]',
    selectionTextClassName: 'text-zinc-300',
    scopeClassName: 'bg-white/10 text-zinc-300',
    inputShellClassName: 'border border-white/10 bg-black/20 text-zinc-200',
    promptClassName: 'text-[13px] font-medium text-zinc-400',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-[12px] font-medium text-zinc-300',
    featuredActionClassName: 'border-white bg-white text-zinc-900',
    sendButtonClassName: 'bg-white text-zinc-900',
    iconClassName: 'text-zinc-500',
  },
  {
    id: 'trim-command',
    name: 'Trim Command',
    description: 'Smaller and denser for people who want the tool to disappear fast.',
    layout: 'rail',
    surfaceClassName: 'border border-slate-200 bg-white',
    panelClassName: 'border border-slate-200 bg-white shadow-[0_10px_22px_-18px_rgba(51,65,85,0.1)]',
    selectionShellClassName: 'border border-slate-200 bg-slate-50 px-3 py-2',
    selectionTextClassName: 'text-[12px] text-slate-700',
    scopeClassName: 'bg-slate-100 text-slate-600',
    inputShellClassName: 'border border-slate-200 bg-white text-slate-800',
    promptClassName: 'text-[12px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex gap-1.5 overflow-hidden',
    actionClassName: 'rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[11px] font-medium text-slate-700',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-slate-500',
  },
  {
    id: 'focus-chip',
    name: 'Focus Chip',
    description: 'Emphasizes one default operation while keeping others secondary.',
    layout: 'wrap',
    surfaceClassName: 'border border-neutral-200 bg-white',
    panelClassName: 'border border-neutral-200 bg-white shadow-[0_14px_30px_-24px_rgba(15,23,42,0.12)]',
    selectionShellClassName: 'border border-neutral-200 bg-neutral-50',
    selectionTextClassName: 'text-neutral-700',
    scopeClassName: 'bg-neutral-100 text-neutral-600',
    inputShellClassName: 'border border-neutral-200 bg-white text-neutral-800',
    promptClassName: 'text-[13px] font-medium text-neutral-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-neutral-200 bg-neutral-50 px-3 py-1.5 text-[12px] font-medium text-neutral-700',
    featuredActionClassName: 'border-neutral-900 bg-neutral-900 text-white px-3.5 py-2',
    sendButtonClassName: 'bg-neutral-900 text-white',
    iconClassName: 'text-neutral-500',
  },
  {
    id: 'notebook-index',
    name: 'Notebook Index',
    description: 'The commands feel like orderly note labels, not pills.',
    layout: 'stack',
    surfaceClassName: 'border border-sky-100 bg-white',
    panelClassName: 'border border-sky-100 bg-white shadow-[0_16px_30px_-24px_rgba(14,165,233,0.1)]',
    selectionShellClassName: 'border border-sky-100 bg-[#f7fcff]',
    selectionTextClassName: 'text-slate-700',
    scopeClassName: 'bg-sky-100 text-sky-700',
    inputShellClassName: 'border border-sky-100 bg-white text-slate-800',
    promptClassName: 'text-[13px] font-medium text-slate-500',
    actionsClassName: 'mt-3 flex flex-col gap-2',
    actionClassName: 'justify-between rounded-xl border border-sky-100 bg-white px-3 py-2 text-[12px] font-medium text-slate-700',
    featuredActionClassName: 'border-slate-900 bg-slate-900 text-white',
    sendButtonClassName: 'bg-slate-900 text-white',
    iconClassName: 'text-sky-500',
  },
  {
    id: 'luxe-quiet',
    name: 'Luxe Quiet',
    description: 'Very restrained premium finish with almost no unnecessary motion.',
    layout: 'wrap',
    surfaceClassName: 'border border-stone-200 bg-white',
    panelClassName: 'border border-stone-200 bg-white shadow-[0_10px_24px_-18px_rgba(87,83,78,0.12)]',
    selectionShellClassName: 'border border-stone-200 bg-white',
    selectionTextClassName: 'text-stone-700',
    scopeClassName: 'bg-stone-100 text-stone-600',
    inputShellClassName: 'border border-stone-200 bg-white text-stone-800',
    promptClassName: 'text-[13px] font-medium tracking-[-0.01em] text-stone-500',
    actionsClassName: 'mt-3 flex flex-wrap gap-2',
    actionClassName: 'rounded-full border border-stone-200 bg-white px-3 py-1.5 text-[12px] font-medium text-stone-700',
    featuredActionClassName: 'border-stone-900 bg-stone-900 text-white',
    sendButtonClassName: 'bg-stone-900 text-white',
    iconClassName: 'text-stone-500',
  },
];
