export type GoogleButtonVariant = {
  id: string;
  name: string;
  category: 'Slide' | 'Glow' | 'Magnet' | 'Pulse' | 'Reveal' | 'Depth';
  surfaceClass: string;
  textClass: string;
  iconWrapClass: string;
  motionClass: string;
  accentClass?: string;
};

export const googleButtonVariants: GoogleButtonVariant[] = [
  {
    id: 'arrow-glide',
    name: 'Arrow Glide',
    category: 'Slide',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-arrow]:translate-x-1.5 hover:[&_.lab-arrow]:opacity-100',
  },
  {
    id: 'arrow-sweep',
    name: 'Arrow Sweep',
    category: 'Slide',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_30px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-50 border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-arrow]:translate-x-2 hover:[&_.lab-arrow]:scale-110 hover:[&_.lab-arrow]:opacity-100',
  },
  {
    id: 'content-drift',
    name: 'Content Drift',
    category: 'Slide',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_28px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-content]:translate-x-1',
  },
  {
    id: 'split-lane',
    name: 'Split Lane',
    category: 'Slide',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_26px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-100 text-zinc-900',
    motionClass: 'hover:[&_.lab-google]:-translate-x-0.5 hover:[&_.lab-arrow]:translate-x-1.5 hover:[&_.lab-arrow]:opacity-100',
  },
  {
    id: 'underline-run',
    name: 'Underline Run',
    category: 'Slide',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.05)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-accent]:scale-x-100',
    accentClass: 'bg-gradient-to-r from-[#4285F4] via-[#FBBC05] to-[#34A853]',
  },
  {
    id: 'halo-soft',
    name: 'Halo Soft',
    category: 'Glow',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_30px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-halo]:opacity-100 hover:[&_.lab-halo]:scale-100',
  },
  {
    id: 'halo-prism',
    name: 'Halo Prism',
    category: 'Glow',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_30px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-50 border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-halo]:opacity-100 hover:[&_.lab-halo]:scale-105',
  },
  {
    id: 'shine-scan',
    name: 'Shine Scan',
    category: 'Glow',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.05)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-shine]:translate-x-[180%]',
  },
  {
    id: 'edge-radiance',
    name: 'Edge Radiance',
    category: 'Glow',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_8px_20px_rgba(15,23,42,0.05)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:shadow-[0_0_0_1px_rgba(66,133,244,0.12),0_0_0_6px_rgba(66,133,244,0.08),0_14px_34px_rgba(15,23,42,0.08)]',
  },
  {
    id: 'logo-aura',
    name: 'Logo Aura',
    category: 'Glow',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_28px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-google]:shadow-[0_0_0_6px_rgba(66,133,244,0.08)] hover:[&_.lab-google]:scale-105',
  },
  {
    id: 'cursor-pull',
    name: 'Cursor Pull',
    category: 'Magnet',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-50 border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-content]:scale-[1.015] hover:[&_.lab-content]:translate-x-0.5',
  },
  {
    id: 'icon-orbit',
    name: 'Icon Orbit',
    category: 'Magnet',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-google]:translate-x-0.5 hover:[&_.lab-google]:-translate-y-0.5',
  },
  {
    id: 'magnetic-lane',
    name: 'Magnetic Lane',
    category: 'Magnet',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_26px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-100 text-zinc-900',
    motionClass: 'hover:[&_.lab-content]:translate-x-1 hover:[&_.lab-copy]:tracking-[0.01em]',
  },
  {
    id: 'magnetic-edge',
    name: 'Magnetic Edge',
    category: 'Magnet',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_26px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-right]:translate-x-1 hover:[&_.lab-right]:scale-105',
  },
  {
    id: 'focus-collapse',
    name: 'Focus Collapse',
    category: 'Magnet',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_26px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-content]:gap-2.5',
  },
  {
    id: 'heartbeat',
    name: 'Heartbeat',
    category: 'Pulse',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:scale-[1.01] active:scale-[0.985]',
  },
  {
    id: 'soft-breath',
    name: 'Soft Breath',
    category: 'Pulse',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-50 border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-surface]:scale-[1.008]',
  },
  {
    id: 'signal-beat',
    name: 'Signal Beat',
    category: 'Pulse',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-accent]:opacity-100 hover:[&_.lab-accent]:scale-x-100',
    accentClass: 'bg-zinc-950',
  },
  {
    id: 'icon-beat',
    name: 'Icon Beat',
    category: 'Pulse',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-google]:scale-110',
  },
  {
    id: 'text-beat',
    name: 'Text Beat',
    category: 'Pulse',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-900',
    iconWrapClass: 'bg-zinc-100 text-zinc-900',
    motionClass: 'hover:[&_.lab-copy]:opacity-100 hover:[&_.lab-copy]:tracking-[0.005em]',
  },
  {
    id: 'wipe-right',
    name: 'Wipe Right',
    category: 'Reveal',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-fill]:scale-x-100',
  },
  {
    id: 'wipe-center',
    name: 'Wipe Center',
    category: 'Reveal',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-50 border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-fill-center]:scale-x-100',
  },
  {
    id: 'mask-sheen',
    name: 'Mask Sheen',
    category: 'Reveal',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-mask]:translate-x-full',
  },
  {
    id: 'color-thread',
    name: 'Color Thread',
    category: 'Reveal',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:[&_.lab-thread]:opacity-100 hover:[&_.lab-thread]:scale-x-100',
  },
  {
    id: 'edge-peel',
    name: 'Edge Peel',
    category: 'Reveal',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-100 text-zinc-900',
    motionClass: 'hover:[&_.lab-corner]:opacity-100 hover:[&_.lab-corner]:scale-100',
  },
  {
    id: 'inner-press',
    name: 'Inner Press',
    category: 'Depth',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[inset_0_1px_0_rgba(255,255,255,0.9),0_10px_22px_rgba(15,23,42,0.05)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:shadow-[inset_0_2px_6px_rgba(15,23,42,0.08),0_8px_18px_rgba(15,23,42,0.04)]',
  },
  {
    id: 'shadow-slide',
    name: 'Shadow Slide',
    category: 'Depth',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_12px_24px_rgba(15,23,42,0.05)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:shadow-[8px_12px_26px_rgba(15,23,42,0.10)]',
  },
  {
    id: 'tilt-right',
    name: 'Tilt Right',
    category: 'Depth',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-zinc-50 border border-zinc-200 text-zinc-900',
    motionClass: 'hover:rotate-[0.35deg]',
  },
  {
    id: 'glass-tighten',
    name: 'Glass Tighten',
    category: 'Depth',
    surfaceClass: 'bg-white/90 border border-zinc-200 shadow-[0_10px_24px_rgba(15,23,42,0.06)] backdrop-blur-sm',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white/80 border border-zinc-200 text-zinc-900',
    motionClass: 'hover:bg-white hover:[&_.lab-surface]:backdrop-blur-md',
  },
  {
    id: 'plateau-shift',
    name: 'Plateau Shift',
    category: 'Depth',
    surfaceClass: 'bg-white border border-zinc-200 shadow-[0_14px_0_0_rgba(241,245,249,1),0_16px_26px_rgba(15,23,42,0.06)]',
    textClass: 'text-zinc-950',
    iconWrapClass: 'bg-white border border-zinc-200 text-zinc-900',
    motionClass: 'hover:shadow-[0_10px_0_0_rgba(241,245,249,1),0_12px_20px_rgba(15,23,42,0.05)] hover:translate-y-[1px]',
  },
];
