export type GoogleButtonVariant = {
  id: string;
  name: string;
  category?: string;
  note: string;
  containerBg: string; // The button's background
  borderClass: string;
  textClass: string;
  badgeClass: string;
  shadowClass: string;
  hoverEffect?: string;
  iconType: 'color' | 'mono' | 'outline';
};

export const googleButtonVariants: GoogleButtonVariant[] = [
  // --- 1. APPLE REFINED (Pure & Clean) ---
  {
    id: 'apple-pure-white',
    name: 'Apple Pure White',
    note: 'White on white with a hairline border. The ultimate stealth choice.',
    containerBg: 'bg-white',
    borderClass: 'border border-zinc-200',
    textClass: 'text-zinc-900',
    badgeClass: 'bg-zinc-100 text-zinc-900',
    shadowClass: 'shadow-sm',
    iconType: 'color',
  },
  {
    id: 'studio-light-grey',
    name: 'Studio Light Grey',
    note: 'Very soft grey, mimicking the finish of a Magic Keyboard.',
    containerBg: 'bg-[#f5f5f7]',
    borderClass: 'border-transparent',
    textClass: 'text-zinc-900',
    badgeClass: 'bg-white text-black shadow-sm',
    shadowClass: 'shadow-none',
    iconType: 'color',
  },
  {
    id: 'glass-frosted-button',
    name: 'Frosted Glass',
    note: 'Semi-transparent, picking up the ceramic texture behind it.',
    containerBg: 'bg-white/40 backdrop-blur-md',
    borderClass: 'border border-white/60',
    textClass: 'text-zinc-900',
    badgeClass: 'bg-white/80 text-black',
    shadowClass: 'shadow-sm',
    iconType: 'color',
  },
  {
    id: 'deep-indigo-subtle',
    name: 'Midnight Silk',
    category: 'Apple Refined',
    note: 'Not black, but a very deep indigo-grey. Much softer than pure black.',
    containerBg: 'bg-[#1c1c1e]',
    borderClass: 'border-white/5 shadow-[inset_0_1px_1px_rgba(255,255,255,0.1)]',
    textClass: 'text-zinc-100',
    badgeClass: 'bg-white text-black',
    shadowClass: 'shadow-2xl',
    iconType: 'color',
  },

  // --- 2. BRAND PURITY (Google Colors Done Right) ---
  {
    id: 'google-soft-blue',
    name: 'Google Soft Blue',
    note: 'Using Google Blue but with 5% saturation for an elegant tint.',
    containerBg: 'bg-[#f0f7ff]',
    borderClass: 'border border-blue-100',
    textClass: 'text-blue-700',
    badgeClass: 'bg-blue-600 text-white',
    shadowClass: 'shadow-sm',
    iconType: 'mono',
  },
  {
    id: 'google-rainbow-edge',
    name: 'Rainbow Edge',
    note: 'White button with a microscopic 4-color gradient border.',
    containerBg: 'bg-white',
    borderClass: 'border-none ring-[1px] ring-zinc-200 shadow-[0_0_0_1px_rgba(255,0,0,0.1),0_0_0_2px_rgba(0,255,0,0.05)]',
    textClass: 'text-zinc-900',
    badgeClass: 'bg-zinc-100 text-zinc-900',
    shadowClass: 'shadow-sm',
    iconType: 'color',
  },
  {
    id: 'minimal-brand-text',
    name: 'Brand Typography',
    note: 'Focus on the wordmark colors with a clean white base.',
    containerBg: 'bg-white',
    borderClass: 'border border-zinc-100',
    textClass: 'text-zinc-900 font-black',
    badgeClass: 'bg-white border border-zinc-100',
    shadowClass: 'shadow-xl shadow-zinc-100',
    iconType: 'color',
  },

  // --- 3. THE "GLOW" SERIES (Apple Intelligence Aesthetics) ---
  {
    id: 'siri-glow-subtle',
    name: 'Intelligence Glow',
    note: 'A soft, pulsing multi-color shadow that feels alive.',
    containerBg: 'bg-white',
    borderClass: 'border-transparent',
    textClass: 'text-zinc-900',
    badgeClass: 'bg-zinc-900 text-white',
    shadowClass: 'shadow-[0_0_20px_rgba(168,85,247,0.15),0_0_40px_rgba(59,130,246,0.1)]',
    iconType: 'color',
  },
  {
    id: 'aura-mist',
    name: 'Aura Mist',
    note: 'The button edges blend into a soft colorful mist.',
    containerBg: 'bg-white/80',
    borderClass: 'border-none',
    textClass: 'text-zinc-950',
    badgeClass: 'bg-zinc-950 text-white',
    shadowClass: 'shadow-[0_10px_30px_-5px_rgba(0,0,0,0.05)]',
    iconType: 'color',
    hoverEffect: 'hover:shadow-[0_20px_40px_rgba(168,85,247,0.2)]',
  },

  // --- 4. MATERIAL LUXURY (Industrial Finishes) ---
  {
    id: 'brushed-aluminum',
    name: 'Brushed Aluminum',
    note: 'Metallic texture with a subtle vertical grain.',
    containerBg: 'bg-[#e2e2e2] bg-[linear-gradient(180deg,#fff_0%,#e2e2e2_100%)]',
    borderClass: 'border border-zinc-300 shadow-[inset_0_1px_0_white]',
    textClass: 'text-zinc-800',
    badgeClass: 'bg-zinc-800 text-white',
    shadowClass: 'shadow-md',
    iconType: 'mono',
  },
  {
    id: 'pearl-essence',
    name: 'Pearl Essence',
    note: 'A soft pinkish-white with a pearlescent sheen.',
    containerBg: 'bg-[#fffcfc]',
    borderClass: 'border border-rose-50',
    textClass: 'text-rose-950',
    badgeClass: 'bg-rose-50 text-rose-600',
    shadowClass: 'shadow-[0_10px_20px_rgba(255,182,193,0.2)]',
    iconType: 'color',
  },
  {
    id: 'carbon-fibre-light',
    name: 'Tech Weave',
    note: 'Light grey technical pattern for a precision feel.',
    containerBg: 'bg-zinc-50 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] bg-[size:4px_4px]',
    borderClass: 'border border-zinc-200',
    textClass: 'text-zinc-900',
    badgeClass: 'bg-zinc-900 text-white',
    shadowClass: 'shadow-none',
    iconType: 'color',
  },

  // --- 5. THE "DIRECTOR" PICKS (Avant-Garde) ---
  {
    id: 'mono-outline-bold',
    name: 'Architectural Mono',
    note: 'Thick 2px outline, no background. Pure geometry.',
    containerBg: 'bg-transparent',
    borderClass: 'border-2 border-zinc-900',
    textClass: 'text-zinc-900 font-black italic',
    badgeClass: 'bg-zinc-900 text-white',
    shadowClass: 'shadow-none',
    iconType: 'mono',
  },
  {
    id: 'soft-depth-inner',
    name: 'Inner Sanctum',
    note: 'Using inner shadows to make the button look recessed into the ceramic.',
    containerBg: 'bg-zinc-50',
    borderClass: 'border-none',
    textClass: 'text-zinc-600',
    badgeClass: 'bg-white shadow-inner text-black',
    shadowClass: 'shadow-[inset_2px_2px_5px_rgba(0,0,0,0.05),inset_-2px_-2px_5px_rgba(255,255,255,1)]',
    iconType: 'color',
  },
  {
    id: 'liquid-mercury-pro',
    name: 'Liquid Mercury',
    note: 'Extreme high gloss with multi-layered specular highlights.',
    containerBg: 'bg-white bg-gradient-to-b from-white to-zinc-100',
    borderClass: 'border border-zinc-200',
    textClass: 'text-zinc-950 font-bold',
    badgeClass: 'bg-white shadow-[0_4px_10px_rgba(0,0,0,0.1)] text-black',
    shadowClass: 'shadow-[0_20px_40px_-10px_rgba(0,0,0,0.1)]',
    iconType: 'color',
  },
  {
    id: 'champagne-metal',
    name: 'Champagne Gold',
    note: 'The finish of the gold iPhone. Warm, metallic, and expensive.',
    containerBg: 'bg-[#f4e4d4]',
    borderClass: 'border border-[#d4c4b4] shadow-[inset_0_1px_0_rgba(255,255,255,0.5)]',
    textClass: 'text-[#5d4d3d]',
    badgeClass: 'bg-[#5d4d3d] text-[#f4e4d4]',
    shadowClass: 'shadow-lg shadow-[#d4c4b4]/20',
    iconType: 'mono',
  },
  {
    id: 'royal-navy-silk',
    name: 'Royal Navy',
    note: 'A very dark, high-saturation navy. Classic luxury.',
    containerBg: 'bg-[#001a33]',
    borderClass: 'border-white/10',
    textClass: 'text-white font-medium',
    badgeClass: 'bg-white text-[#001a33]',
    shadowClass: 'shadow-2xl shadow-blue-900/20',
    iconType: 'color',
  },
  {
    id: 'mint-ceramic',
    name: 'Mint Ceramic',
    note: 'A hint of green to refresh the white palette.',
    containerBg: 'bg-[#f0fcf5]',
    borderClass: 'border border-emerald-100',
    textClass: 'text-emerald-900',
    badgeClass: 'bg-emerald-500 text-white',
    shadowClass: 'shadow-sm',
    iconType: 'mono',
  },
  {
    id: 'paper-texture-pro',
    name: 'Cotton Paper',
    note: 'Subtle fiber texture, like high-quality business cards.',
    containerBg: 'bg-white bg-[url("https://www.transparenttextures.com/patterns/clean-gray-paper.png")]',
    borderClass: 'border border-zinc-200',
    textClass: 'text-zinc-800 font-serif italic',
    badgeClass: 'bg-zinc-100 text-zinc-800',
    shadowClass: 'shadow-none',
    iconType: 'color',
  },
  {
    id: 'hyper-minimal-text',
    name: 'Zero Button',
    note: 'No container at all. Just text and an icon floating perfectly.',
    containerBg: 'bg-transparent',
    borderClass: 'border-none',
    textClass: 'text-zinc-400 hover:text-zinc-950 font-black uppercase tracking-[0.2em] text-[11px]',
    badgeClass: 'bg-transparent border border-zinc-100',
    shadowClass: 'shadow-none',
    iconType: 'color',
  },
  {
    id: 'clay-white-3d',
    name: 'Clay 3D',
    note: 'Trendy 3D claymorphism with soft outer glow.',
    containerBg: 'bg-white',
    borderClass: 'border-none',
    textClass: 'text-zinc-900 font-bold',
    badgeClass: 'bg-white shadow-[2px_2px_5px_#d1d1d6,-2px_-2px_5px_#fff]',
    shadowClass: 'shadow-[8px_8px_16px_#d1d1d6,-8px_-8px_16px_#ffffff]',
    iconType: 'color',
  },
  {
    id: 'space-black-matte',
    name: 'Space Black',
    note: 'The deep, light-absorbing black of the M3 MacBook Pro.',
    containerBg: 'bg-[#0a0a0a]',
    borderClass: 'border border-white/5',
    textClass: 'text-zinc-400 font-medium',
    badgeClass: 'bg-white text-black shadow-[0_0_15px_rgba(255,255,255,0.3)]',
    shadowClass: 'shadow-2xl',
    iconType: 'mono',
  },
  {
    id: 'vibrant-magenta-glow',
    name: 'Creative Pulse',
    note: 'A sharp, creative accent for an otherwise white UI.',
    containerBg: 'bg-white',
    borderClass: 'border-2 border-rose-500',
    textClass: 'text-rose-600 font-black',
    badgeClass: 'bg-rose-600 text-white',
    shadowClass: 'shadow-xl shadow-rose-100',
    iconType: 'mono',
  },
  {
    id: 'titanium-gold',
    name: 'Titanium Gold',
    note: 'A mix of raw metal and luxury gold tint.',
    containerBg: 'bg-[#e8e0d5]',
    borderClass: 'border border-[#dcd0c0] shadow-[inset_0_1px_0_white]',
    textClass: 'text-[#7a6a5a] font-bold',
    badgeClass: 'bg-[#7a6a5a] text-white',
    shadowClass: 'shadow-md',
    iconType: 'mono',
  },
  {
    id: 'minimal-outline-dots',
    name: 'Dotted Precision',
    note: 'A dotted border for a technical, blueprint-like feel.',
    containerBg: 'bg-white',
    borderClass: 'border border-dashed border-zinc-300',
    textClass: 'text-zinc-500 hover:text-zinc-950 font-mono',
    badgeClass: 'bg-zinc-50 border border-zinc-200',
    shadowClass: 'shadow-none',
    iconType: 'color',
  },
  {
    id: 'silk-gradient',
    name: 'Silk Gradient',
    note: 'A barely-there gradient from white to very light blue.',
    containerBg: 'bg-gradient-to-b from-white to-[#f0f4ff]',
    borderClass: 'border border-blue-50/50',
    textClass: 'text-zinc-900',
    badgeClass: 'bg-white shadow-sm text-blue-600',
    shadowClass: 'shadow-lg shadow-blue-50/50',
    iconType: 'color',
  },
  {
    id: 'monolith-pro-button',
    name: 'The Monolith',
    note: 'Sharp corners, high contrast, maximum authority.',
    containerBg: 'bg-black',
    borderClass: 'border-none',
    textClass: 'text-white font-black uppercase tracking-[0.3em] text-[10px]',
    badgeClass: 'bg-white text-black',
    shadowClass: 'shadow-2xl',
    iconType: 'mono',
  },
  {
    id: 'soft-lemon-ceramic',
    name: 'Lemon Ceramic',
    note: 'Warm and sunny, like a morning in Cupertino.',
    containerBg: 'bg-[#fffdef]',
    borderClass: 'border border-yellow-100',
    textClass: 'text-yellow-900 font-bold',
    badgeClass: 'bg-yellow-400 text-yellow-900',
    shadowClass: 'shadow-sm',
    iconType: 'color',
  },
  {
    id: 'ethereal-void',
    name: 'Ethereal Void',
    note: 'A button that seems to be made of light, not matter.',
    containerBg: 'bg-white/10 backdrop-blur-3xl',
    borderClass: 'border border-white/20',
    textClass: 'text-zinc-900 font-light tracking-[0.1em]',
    badgeClass: 'bg-zinc-950 text-white shadow-2xl',
    shadowClass: 'shadow-[0_40px_100px_rgba(0,0,0,0.02)]',
    iconType: 'color',
  },
  {
    id: 'curated-standard',
    name: 'Director’s Final',
    note: 'The perfect balance of brand, Apple aesthetics, and luxury.',
    containerBg: 'bg-white shadow-[inset_0_0_15px_rgba(0,0,0,0.02)]',
    borderClass: 'border border-zinc-200/60',
    textClass: 'text-zinc-950 font-black tracking-tight',
    badgeClass: 'bg-zinc-950 text-white shadow-xl',
    shadowClass: 'shadow-[0_20px_40px_-15px_rgba(0,0,0,0.1)]',
    iconType: 'color',
  },
];
