export type MembershipBadgeTone = 'free' | 'plus' | 'pro' | 'max';

export interface MembershipBadgeVariant {
  id: string;
  name: string;
  category: string;
  stageClassName: string;
  shellClassName: string;
  headerClassName: string;
  listClassName: string;
  itemClassName: string;
  labelClassName: string;
  valueClassName: string;
  accentStyle: Record<MembershipBadgeTone, string>;
}

const tierAccentSets: Array<Record<MembershipBadgeTone, string>> = [
  {
    free: 'bg-zinc-100 text-zinc-600',
    plus: 'bg-sky-100 text-sky-700',
    pro: 'bg-emerald-100 text-emerald-700',
    max: 'bg-amber-100 text-amber-700',
  },
  {
    free: 'border border-zinc-200 bg-white text-zinc-700',
    plus: 'border border-sky-200 bg-sky-50 text-sky-700',
    pro: 'border border-emerald-200 bg-emerald-50 text-emerald-700',
    max: 'border border-orange-200 bg-orange-50 text-orange-700',
  },
  {
    free: 'bg-zinc-900 text-white',
    plus: 'bg-sky-600 text-white',
    pro: 'bg-emerald-600 text-white',
    max: 'bg-amber-500 text-zinc-950',
  },
  {
    free: 'bg-zinc-100/80 text-zinc-700 ring-1 ring-inset ring-zinc-200',
    plus: 'bg-cyan-100/80 text-cyan-800 ring-1 ring-inset ring-cyan-200',
    pro: 'bg-teal-100/80 text-teal-800 ring-1 ring-inset ring-teal-200',
    max: 'bg-fuchsia-100/80 text-fuchsia-800 ring-1 ring-inset ring-fuchsia-200',
  },
  {
    free: 'bg-[linear-gradient(135deg,#f4f4f5,#e4e4e7)] text-zinc-700',
    plus: 'bg-[linear-gradient(135deg,#dbeafe,#bfdbfe)] text-sky-800',
    pro: 'bg-[linear-gradient(135deg,#dcfce7,#bbf7d0)] text-emerald-800',
    max: 'bg-[linear-gradient(135deg,#fef3c7,#fde68a)] text-amber-900',
  },
];

export const membershipBadgeVariants: MembershipBadgeVariant[] = [
  {
    id: 'paper-pills',
    name: 'Paper Pills',
    category: 'minimal',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#f4f4f5_62%)]',
    shellClassName: 'rounded-[28px] border border-zinc-200 bg-white p-6 shadow-[0_18px_40px_rgba(15,23,42,0.06)]',
    headerClassName: 'text-zinc-400',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-zinc-200/80 bg-zinc-50 px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-black tracking-[0.12em] uppercase',
    accentStyle: tierAccentSets[0],
  },
  {
    id: 'mono-rail',
    name: 'Mono Rail',
    category: 'editorial',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#f5f5f5_60%)]',
    shellClassName: 'rounded-[30px] border border-zinc-300 bg-white p-6 shadow-[0_18px_36px_rgba(24,24,27,0.06)]',
    headerClassName: 'text-zinc-500',
    listClassName: 'gap-2.5',
    itemClassName: 'rounded-[16px] bg-white px-3 py-2.5 ring-1 ring-inset ring-zinc-200',
    labelClassName: 'text-zinc-400',
    valueClassName: 'rounded-[10px] px-2.5 py-1 text-[11px] font-bold uppercase tracking-[0.16em]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'quiet-stack',
    name: 'Quiet Stack',
    category: 'subtle',
    stageClassName: 'bg-[linear-gradient(180deg,#fbfbfc,#f1f5f9)]',
    shellClassName: 'rounded-[24px] border border-slate-200 bg-white/90 p-6 shadow-[0_16px_30px_rgba(15,23,42,0.05)] backdrop-blur',
    headerClassName: 'text-slate-400',
    listClassName: 'gap-2',
    itemClassName: 'rounded-[14px] bg-slate-50 px-3 py-2.5',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[0],
  },
  {
    id: 'badge-grid',
    name: 'Badge Grid',
    category: 'structured',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f8fafc)]',
    shellClassName: 'rounded-[26px] border border-zinc-200 bg-white p-6 shadow-[0_18px_34px_rgba(15,23,42,0.05)]',
    headerClassName: 'text-zinc-400',
    listClassName: 'grid grid-cols-2 gap-3',
    itemClassName: 'rounded-[18px] border border-zinc-200 bg-zinc-50 px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'mt-2 inline-flex rounded-[12px] px-2.5 py-1 text-[11px] font-black uppercase tracking-[0.15em]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'soft-tickets',
    name: 'Soft Tickets',
    category: 'soft',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#fffef8,#f5f5f4_60%)]',
    shellClassName: 'rounded-[30px] border border-stone-200 bg-[#fffdfa] p-6 shadow-[0_18px_40px_rgba(120,113,108,0.08)]',
    headerClassName: 'text-stone-400',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] border border-stone-200 bg-white px-4 py-3',
    labelClassName: 'text-stone-500',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-bold uppercase tracking-[0.14em]',
    accentStyle: tierAccentSets[4],
  },
  {
    id: 'dark-capsule',
    name: 'Dark Capsule',
    category: 'contrast',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#2b2b31,#0f0f12_68%)]',
    shellClassName: 'rounded-[28px] border border-white/10 bg-zinc-950 p-6 shadow-[0_24px_50px_rgba(0,0,0,0.35)]',
    headerClassName: 'text-zinc-600',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-white/10 bg-white/[0.03] px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-black uppercase tracking-[0.14em]',
    accentStyle: tierAccentSets[2],
  },
  {
    id: 'signal-bars',
    name: 'Signal Bars',
    category: 'system',
    stageClassName: 'bg-[linear-gradient(180deg,#f8fafc,#eef2ff)]',
    shellClassName: 'rounded-[26px] border border-slate-200 bg-white p-6 shadow-[0_18px_34px_rgba(15,23,42,0.06)]',
    headerClassName: 'text-slate-400',
    listClassName: 'gap-2.5',
    itemClassName: 'rounded-[16px] bg-slate-50 px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-[8px] px-2.5 py-1 text-[11px] font-black uppercase tracking-[0.14em]',
    accentStyle: tierAccentSets[3],
  },
  {
    id: 'outline-rank',
    name: 'Outline Rank',
    category: 'outline',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f3f4f6)]',
    shellClassName: 'rounded-[24px] border border-zinc-300 bg-white p-6 shadow-[0_14px_28px_rgba(15,23,42,0.04)]',
    headerClassName: 'text-zinc-400',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[14px] border border-zinc-200 bg-transparent px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'aurora-strip',
    name: 'Aurora Strip',
    category: 'atmospheric',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#eef6ff_36%,#f8fafc_72%)]',
    shellClassName: 'rounded-[30px] border border-sky-100 bg-white/95 p-6 shadow-[0_20px_42px_rgba(14,165,233,0.08)] backdrop-blur',
    headerClassName: 'text-sky-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-sky-100/80 bg-white px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-black uppercase tracking-[0.14em]',
    accentStyle: tierAccentSets[0],
  },
  {
    id: 'warm-ribbon',
    name: 'Warm Ribbon',
    category: 'warm',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#fffefb,#faf4ea_56%,#f7f7f5)]',
    shellClassName: 'rounded-[28px] border border-[#eadfce] bg-[#fffdfa] p-6 shadow-[0_18px_38px_rgba(120,113,108,0.08)]',
    headerClassName: 'text-[#c3b29b]',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] border border-[#ede4d7] bg-white px-3 py-3',
    labelClassName: 'text-[#8b7355]',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-black uppercase tracking-[0.14em]',
    accentStyle: tierAccentSets[4],
  },
  {
    id: 'index-cards',
    name: 'Index Cards',
    category: 'editorial',
    stageClassName: 'bg-[linear-gradient(180deg,#fcfcfd,#f4f4f5)]',
    shellClassName: 'rounded-[26px] border border-zinc-200 bg-white p-6 shadow-[0_18px_34px_rgba(15,23,42,0.05)]',
    headerClassName: 'text-zinc-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border-l-4 border-zinc-200 bg-zinc-50 px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-md px-2.5 py-1 text-[11px] font-black uppercase tracking-[0.14em]',
    accentStyle: tierAccentSets[0],
  },
  {
    id: 'compact-tabs',
    name: 'Compact Tabs',
    category: 'compact',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f8fafc)]',
    shellClassName: 'rounded-[24px] border border-neutral-200 bg-white p-5 shadow-[0_16px_30px_rgba(15,23,42,0.05)]',
    headerClassName: 'text-neutral-400',
    listClassName: 'gap-2',
    itemClassName: 'rounded-[14px] bg-neutral-50 px-3 py-2.5',
    labelClassName: 'text-neutral-500',
    valueClassName: 'rounded-[10px] px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.16em]',
    accentStyle: tierAccentSets[3],
  },
  {
    id: 'lucent-board',
    name: 'Lucent Board',
    category: 'glass',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#eef2ff_45%,#f8fafc_80%)]',
    shellClassName: 'rounded-[30px] border border-white/80 bg-white/70 p-6 shadow-[0_20px_40px_rgba(15,23,42,0.08)] backdrop-blur-xl',
    headerClassName: 'text-slate-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-white/80 bg-white/70 px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-bold uppercase tracking-[0.15em]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'priority-lane',
    name: 'Priority Lane',
    category: 'system',
    stageClassName: 'bg-[linear-gradient(180deg,#f8fafc,#eef2f7)]',
    shellClassName: 'rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_18px_32px_rgba(15,23,42,0.06)]',
    headerClassName: 'text-slate-400',
    listClassName: 'gap-2.5',
    itemClassName: 'rounded-[16px] border border-slate-200 bg-white px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[0],
  },
  {
    id: 'ledger-tags',
    name: 'Ledger Tags',
    category: 'structured',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f6f7f8)]',
    shellClassName: 'rounded-[24px] border border-zinc-300 bg-white p-6 shadow-[0_14px_24px_rgba(24,24,27,0.05)]',
    headerClassName: 'text-zinc-400',
    listClassName: 'gap-2',
    itemClassName: 'rounded-[14px] border-b border-zinc-200 bg-transparent px-0 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'pastel-track',
    name: 'Pastel Track',
    category: 'soft',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#f9fafb_34%,#eff6ff_78%)]',
    shellClassName: 'rounded-[30px] border border-sky-100 bg-white p-6 shadow-[0_20px_38px_rgba(59,130,246,0.06)]',
    headerClassName: 'text-sky-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] bg-sky-50/60 px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-bold uppercase tracking-[0.14em]',
    accentStyle: tierAccentSets[4],
  },
  {
    id: 'ink-panel',
    name: 'Ink Panel',
    category: 'contrast',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#2d2d30,#111113_72%)]',
    shellClassName: 'rounded-[26px] border border-white/10 bg-[#111113] p-6 shadow-[0_24px_48px_rgba(0,0,0,0.38)]',
    headerClassName: 'text-zinc-600',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] border border-white/10 bg-white/[0.02] px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-[10px] px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[2],
  },
  {
    id: 'folio-chips',
    name: 'Folio Chips',
    category: 'editorial',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#fffefc,#f7f3eb_70%)]',
    shellClassName: 'rounded-[28px] border border-stone-200 bg-[#fffdfa] p-6 shadow-[0_18px_36px_rgba(120,113,108,0.08)]',
    headerClassName: 'text-stone-400',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] border border-stone-200/80 bg-white px-3 py-3',
    labelClassName: 'text-stone-500',
    valueClassName: 'rounded-full px-3 py-1 text-[11px] font-black uppercase tracking-[0.15em]',
    accentStyle: tierAccentSets[4],
  },
  {
    id: 'plain-rank',
    name: 'Plain Rank',
    category: 'minimal',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f7f7f8)]',
    shellClassName: 'rounded-[24px] border border-zinc-200 bg-white p-6 shadow-[0_12px_24px_rgba(15,23,42,0.04)]',
    headerClassName: 'text-zinc-300',
    listClassName: 'gap-2.5',
    itemClassName: 'rounded-[12px] bg-white px-0 py-2.5',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[0],
  },
  {
    id: 'floating-pins',
    name: 'Floating Pins',
    category: 'expressive',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#f3f4f6_60%)]',
    shellClassName: 'rounded-[30px] border border-zinc-200 bg-white p-6 shadow-[0_18px_40px_rgba(15,23,42,0.06)]',
    headerClassName: 'text-zinc-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-zinc-200 bg-zinc-50 px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em] shadow-[0_6px_16px_rgba(15,23,42,0.08)]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'notebook-tabs',
    name: 'Notebook Tabs',
    category: 'structured',
    stageClassName: 'bg-[linear-gradient(180deg,#fcfcfd,#eef2f7)]',
    shellClassName: 'rounded-[26px] border border-slate-200 bg-white p-6 shadow-[0_16px_32px_rgba(15,23,42,0.06)]',
    headerClassName: 'text-slate-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] bg-slate-50 px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-[8px] px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[3],
  },
  {
    id: 'studio-cards',
    name: 'Studio Cards',
    category: 'display',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#f8fafc_55%,#eef2ff)]',
    shellClassName: 'rounded-[30px] border border-slate-200 bg-white p-6 shadow-[0_20px_42px_rgba(15,23,42,0.08)]',
    headerClassName: 'text-slate-300',
    listClassName: 'grid grid-cols-2 gap-3',
    itemClassName: 'rounded-[18px] border border-slate-200 bg-white px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'mt-2 inline-flex rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[0],
  },
  {
    id: 'frost-shell',
    name: 'Frost Shell',
    category: 'glass',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#eff6ff_40%,#eef2f7)]',
    shellClassName: 'rounded-[32px] border border-white/80 bg-white/65 p-6 shadow-[0_22px_44px_rgba(15,23,42,0.08)] backdrop-blur-xl',
    headerClassName: 'text-sky-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-white/80 bg-white/70 px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'stone-rank',
    name: 'Stone Rank',
    category: 'warm',
    stageClassName: 'bg-[linear-gradient(180deg,#fbfaf8,#f0ece6)]',
    shellClassName: 'rounded-[28px] border border-stone-200 bg-[#fcfbf8] p-6 shadow-[0_18px_36px_rgba(120,113,108,0.08)]',
    headerClassName: 'text-stone-400',
    listClassName: 'gap-2.5',
    itemClassName: 'rounded-[16px] border border-stone-200 bg-white px-3 py-3',
    labelClassName: 'text-stone-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[4],
  },
  {
    id: 'rank-lights',
    name: 'Rank Lights',
    category: 'system',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f3f4f6)]',
    shellClassName: 'rounded-[24px] border border-zinc-200 bg-white p-6 shadow-[0_14px_28px_rgba(15,23,42,0.05)]',
    headerClassName: 'text-zinc-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] border border-zinc-200 bg-zinc-50 px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[2],
  },
  {
    id: 'quiet-labels',
    name: 'Quiet Labels',
    category: 'subtle',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f8fafc)]',
    shellClassName: 'rounded-[26px] border border-zinc-200 bg-white p-6 shadow-[0_16px_30px_rgba(15,23,42,0.05)]',
    headerClassName: 'text-zinc-300',
    listClassName: 'gap-2.5',
    itemClassName: 'rounded-[15px] bg-zinc-50 px-3 py-3',
    labelClassName: 'text-zinc-400',
    valueClassName: 'rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[3],
  },
  {
    id: 'premium-lane',
    name: 'Premium Lane',
    category: 'display',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#f8fafc_44%,#eef2ff)]',
    shellClassName: 'rounded-[30px] border border-slate-200 bg-white p-6 shadow-[0_20px_40px_rgba(15,23,42,0.07)]',
    headerClassName: 'text-slate-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-slate-200 bg-white px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[2],
  },
  {
    id: 'air-tags',
    name: 'Air Tags',
    category: 'minimal',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f8fafc)]',
    shellClassName: 'rounded-[30px] border border-zinc-200/70 bg-white/80 p-6 shadow-[0_18px_36px_rgba(15,23,42,0.05)] backdrop-blur',
    headerClassName: 'text-zinc-300',
    listClassName: 'gap-2.5',
    itemClassName: 'rounded-[16px] bg-white px-3 py-3',
    labelClassName: 'text-zinc-400',
    valueClassName: 'rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[1],
  },
  {
    id: 'club-signals',
    name: 'Club Signals',
    category: 'brand',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#fffefc,#faf5ef_55%,#f4f4f5)]',
    shellClassName: 'rounded-[30px] border border-[#eadfce] bg-[#fffdfa] p-6 shadow-[0_20px_40px_rgba(120,113,108,0.1)]',
    headerClassName: 'text-[#c1b09a]',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-[#ede4d7] bg-white px-3 py-3',
    labelClassName: 'text-[#8b7355]',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[4],
  },
  {
    id: 'obsidian-slots',
    name: 'Obsidian Slots',
    category: 'contrast',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#27272a,#09090b_72%)]',
    shellClassName: 'rounded-[28px] border border-white/10 bg-zinc-950 p-6 shadow-[0_28px_56px_rgba(0,0,0,0.4)]',
    headerClassName: 'text-zinc-600',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] border border-white/10 bg-white/[0.03] px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[2],
  },
  {
    id: 'focus-notes',
    name: 'Focus Notes',
    category: 'expressive',
    stageClassName: 'bg-[linear-gradient(180deg,#ffffff,#f3f4f6)]',
    shellClassName: 'rounded-[26px] border border-zinc-200 bg-white p-6 shadow-[0_18px_36px_rgba(15,23,42,0.06)]',
    headerClassName: 'text-zinc-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[16px] border border-zinc-200 bg-zinc-50 px-3 py-3',
    labelClassName: 'text-zinc-500',
    valueClassName: 'rounded-[9px] px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[3],
  },
  {
    id: 'tier-bands',
    name: 'Tier Bands',
    category: 'display',
    stageClassName: 'bg-[radial-gradient(circle_at_top,#ffffff,#eef2ff_46%,#f8fafc)]',
    shellClassName: 'rounded-[30px] border border-slate-200 bg-white p-6 shadow-[0_20px_40px_rgba(15,23,42,0.07)]',
    headerClassName: 'text-slate-300',
    listClassName: 'gap-3',
    itemClassName: 'rounded-[18px] border border-slate-200 bg-white px-3 py-3',
    labelClassName: 'text-slate-500',
    valueClassName: 'rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em]',
    accentStyle: tierAccentSets[0],
  },
];
