export type SidebarResizeDragModel =
  | 'linear'
  | 'magnetic'
  | 'resistive'
  | 'elastic'
  | 'stepped'
  | 'glide';

export type SidebarResizeReleaseSnap = 'none' | 'proximity' | 'always';

export interface SidebarResizeVariant {
  id: string;
  name: string;
  description: string;
  category: string;
  accentClassName: string;
  surfaceClassName: string;
  canvasClassName: string;
  badgeClassName: string;
  handleStyle: 'hairline' | 'pill' | 'block';
  dragModel: SidebarResizeDragModel;
  releaseSnap: SidebarResizeReleaseSnap;
  smoothing: number;
  edgeResistance: number;
  snapStrength: number;
  stepSize?: number;
  snapPoints?: number[];
  showGhost: boolean;
  showBadge: boolean;
  showTicks: boolean;
  showScrim: boolean;
  showPreviewBar: boolean;
  recommended?: boolean;
}

export const sidebarResizeVariants: SidebarResizeVariant[] = [
  {
    id: 'quiet-rail',
    name: 'Quiet Rail',
    description: '最克制的细线拖拽，只强调稳定跟手。',
    category: 'Baseline',
    accentClassName: 'bg-neutral-900',
    surfaceClassName: 'bg-white border-neutral-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fafafa)]',
    badgeClassName: 'bg-neutral-900 text-white',
    handleStyle: 'hairline',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: false,
    showPreviewBar: false,
    recommended: true,
  },
  {
    id: 'precision-band',
    name: 'Precision Band',
    description: '拖拽时显示宽度读数，强调精确控制。',
    category: 'Precision',
    accentClassName: 'bg-sky-500',
    surfaceClassName: 'bg-white border-sky-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f6fbff)]',
    badgeClassName: 'bg-sky-100 text-sky-700',
    handleStyle: 'hairline',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'wide-hitbox',
    name: 'Wide Hitbox',
    description: '视觉仍然极细，但命中区显著扩大。',
    category: 'Hit Area',
    accentClassName: 'bg-emerald-500',
    surfaceClassName: 'bg-white border-emerald-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f6fffb)]',
    badgeClassName: 'bg-emerald-100 text-emerald-700',
    handleStyle: 'pill',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'magnetic-dock',
    name: 'Magnetic Dock',
    description: '靠近关键宽度时自动吸附，减少抖动。',
    category: 'Snap',
    accentClassName: 'bg-violet-500',
    surfaceClassName: 'bg-white border-violet-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#faf7ff)]',
    badgeClassName: 'bg-violet-100 text-violet-700',
    handleStyle: 'hairline',
    dragModel: 'magnetic',
    releaseSnap: 'proximity',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.52,
    snapPoints: [132, 168, 208, 248],
    showGhost: true,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
    recommended: true,
  },
  {
    id: 'tripoint-dock',
    name: 'Tripoint Dock',
    description: '只保留三个明确档位，降低选择成本。',
    category: 'Snap',
    accentClassName: 'bg-fuchsia-500',
    surfaceClassName: 'bg-white border-fuchsia-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fff7fd)]',
    badgeClassName: 'bg-fuchsia-100 text-fuchsia-700',
    handleStyle: 'pill',
    dragModel: 'magnetic',
    releaseSnap: 'always',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.66,
    snapPoints: [136, 188, 252],
    showGhost: true,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'elastic-edge',
    name: 'Elastic Edge',
    description: '靠近极限宽度时自动变钝，手感更软。',
    category: 'Resistance',
    accentClassName: 'bg-amber-500',
    surfaceClassName: 'bg-white border-amber-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#fffef7,#fffaf0)]',
    badgeClassName: 'bg-amber-100 text-amber-700',
    handleStyle: 'hairline',
    dragModel: 'elastic',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 0.42,
    snapStrength: 0.18,
    snapPoints: [148, 224],
    showGhost: false,
    showBadge: true,
    showTicks: false,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'soft-clamp',
    name: 'Soft Clamp',
    description: '边缘阻尼更强，防止一下撞满。',
    category: 'Resistance',
    accentClassName: 'bg-orange-500',
    surfaceClassName: 'bg-white border-orange-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#fff,#fff8f3)]',
    badgeClassName: 'bg-orange-100 text-orange-700',
    handleStyle: 'block',
    dragModel: 'resistive',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 0.3,
    snapStrength: 0,
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'glide-rail',
    name: 'Glide Rail',
    description: '宽度变化有一点惯性，更丝滑但不漂。',
    category: 'Smoothing',
    accentClassName: 'bg-cyan-500',
    surfaceClassName: 'bg-white border-cyan-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f4fdff)]',
    badgeClassName: 'bg-cyan-100 text-cyan-700',
    handleStyle: 'hairline',
    dragModel: 'glide',
    releaseSnap: 'none',
    smoothing: 0.38,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'ghost-split',
    name: 'Ghost Split',
    description: '拖拽时给出目标落点幽灵面板，方向最明确。',
    category: 'Preview',
    accentClassName: 'bg-neutral-700',
    surfaceClassName: 'bg-white border-neutral-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f8f8f9)]',
    badgeClassName: 'bg-neutral-100 text-neutral-700',
    handleStyle: 'pill',
    dragModel: 'magnetic',
    releaseSnap: 'proximity',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.42,
    snapPoints: [144, 176, 224, 260],
    showGhost: true,
    showBadge: false,
    showTicks: true,
    showScrim: true,
    showPreviewBar: false,
    recommended: true,
  },
  {
    id: 'scrim-focus',
    name: 'Scrim Focus',
    description: '拖拽时给正文轻微遮罩，让边界更明确。',
    category: 'Preview',
    accentClassName: 'bg-slate-500',
    surfaceClassName: 'bg-white border-slate-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f6f8fb)]',
    badgeClassName: 'bg-slate-100 text-slate-700',
    handleStyle: 'hairline',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: true,
    showPreviewBar: true,
  },
  {
    id: 'stage-snap',
    name: 'Stage Snap',
    description: '最适合产品化的分档手感，宽度选择很稳。',
    category: 'Recommended',
    accentClassName: 'bg-blue-600',
    surfaceClassName: 'bg-white border-blue-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f6f9ff)]',
    badgeClassName: 'bg-blue-100 text-blue-700',
    handleStyle: 'pill',
    dragModel: 'elastic',
    releaseSnap: 'always',
    smoothing: 0.74,
    edgeResistance: 0.52,
    snapStrength: 0.6,
    snapPoints: [140, 176, 224, 264],
    showGhost: true,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
    recommended: true,
  },
  {
    id: 'step-ladder',
    name: 'Step Ladder',
    description: '拖拽过程就是离散步进，像缩放等级切换。',
    category: 'Stepped',
    accentClassName: 'bg-lime-500',
    surfaceClassName: 'bg-white border-lime-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fbfff5)]',
    badgeClassName: 'bg-lime-100 text-lime-700',
    handleStyle: 'block',
    dragModel: 'stepped',
    releaseSnap: 'always',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    stepSize: 16,
    snapPoints: [128, 160, 192, 224, 256],
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'dense-editor',
    name: 'Dense Editor',
    description: '更适合重度笔记用户，倾向保留正文空间。',
    category: 'Bias',
    accentClassName: 'bg-rose-500',
    surfaceClassName: 'bg-white border-rose-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fff6f8)]',
    badgeClassName: 'bg-rose-100 text-rose-700',
    handleStyle: 'hairline',
    dragModel: 'magnetic',
    releaseSnap: 'always',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.48,
    snapPoints: [132, 156, 184],
    showGhost: true,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'wide-context',
    name: 'Wide Context',
    description: '更适合多级目录，倾向拉到更宽的状态。',
    category: 'Bias',
    accentClassName: 'bg-indigo-500',
    surfaceClassName: 'bg-white border-indigo-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f7f7ff)]',
    badgeClassName: 'bg-indigo-100 text-indigo-700',
    handleStyle: 'pill',
    dragModel: 'magnetic',
    releaseSnap: 'always',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.46,
    snapPoints: [188, 224, 264],
    showGhost: true,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'bookmark-width',
    name: 'Bookmark Width',
    description: '把常用宽度当书签，拖到附近就回到那里。',
    category: 'Memory',
    accentClassName: 'bg-teal-500',
    surfaceClassName: 'bg-white border-teal-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f4fffd)]',
    badgeClassName: 'bg-teal-100 text-teal-700',
    handleStyle: 'hairline',
    dragModel: 'magnetic',
    releaseSnap: 'proximity',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.58,
    snapPoints: [152, 208, 248],
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'commit-pulse',
    name: 'Commit Pulse',
    description: '松手后边界轻微强调，给到已生效的确认感。',
    category: 'Feedback',
    accentClassName: 'bg-red-500',
    surfaceClassName: 'bg-white border-red-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fff7f7)]',
    badgeClassName: 'bg-red-100 text-red-700',
    handleStyle: 'pill',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: true,
    showTicks: false,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'dual-rail',
    name: 'Dual Rail',
    description: '中间主线，外侧再给一个更宽的感应轨道。',
    category: 'Hit Area',
    accentClassName: 'bg-zinc-800',
    surfaceClassName: 'bg-white border-zinc-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f7f7f8)]',
    badgeClassName: 'bg-zinc-100 text-zinc-700',
    handleStyle: 'block',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: false,
    showTicks: true,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'hover-band',
    name: 'Hover Band',
    description: '平时很安静，接近可拖拽区域时才显著提醒。',
    category: 'Discovery',
    accentClassName: 'bg-purple-500',
    surfaceClassName: 'bg-white border-purple-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fbf8ff)]',
    badgeClassName: 'bg-purple-100 text-purple-700',
    handleStyle: 'pill',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'lane-guides',
    name: 'Lane Guides',
    description: '正文里额外给参考列线，拖拽时方向感更强。',
    category: 'Guides',
    accentClassName: 'bg-sky-600',
    surfaceClassName: 'bg-white border-sky-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f5fbff)]',
    badgeClassName: 'bg-sky-100 text-sky-700',
    handleStyle: 'hairline',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: true,
    showPreviewBar: false,
  },
  {
    id: 'soft-magnet',
    name: 'Soft Magnet',
    description: '只有靠得很近才吸附，避免过度抢控制权。',
    category: 'Snap',
    accentClassName: 'bg-emerald-600',
    surfaceClassName: 'bg-white border-emerald-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f6fffb)]',
    badgeClassName: 'bg-emerald-100 text-emerald-700',
    handleStyle: 'hairline',
    dragModel: 'magnetic',
    releaseSnap: 'proximity',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.32,
    snapPoints: [144, 184, 224, 256],
    showGhost: false,
    showBadge: false,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'hard-magnet',
    name: 'Hard Magnet',
    description: '更强吸附，适合明确档位的产品心智。',
    category: 'Snap',
    accentClassName: 'bg-violet-600',
    surfaceClassName: 'bg-white border-violet-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f8f6ff)]',
    badgeClassName: 'bg-violet-100 text-violet-700',
    handleStyle: 'pill',
    dragModel: 'magnetic',
    releaseSnap: 'always',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.72,
    snapPoints: [144, 188, 236],
    showGhost: true,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'reading-safe',
    name: 'Reading Safe',
    description: '正文最小阅读宽度优先，不允许过窄拖拽。',
    category: 'Constraint',
    accentClassName: 'bg-stone-500',
    surfaceClassName: 'bg-white border-stone-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fafaf9)]',
    badgeClassName: 'bg-stone-100 text-stone-700',
    handleStyle: 'block',
    dragModel: 'resistive',
    releaseSnap: 'proximity',
    smoothing: 1,
    edgeResistance: 0.36,
    snapStrength: 0.2,
    snapPoints: [160, 196, 232],
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'notion-like',
    name: 'Notion-Like',
    description: '强调轻量和低存在感，适合长期使用。',
    category: 'Productized',
    accentClassName: 'bg-neutral-800',
    surfaceClassName: 'bg-white border-neutral-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fbfbfb)]',
    badgeClassName: 'bg-neutral-100 text-neutral-700',
    handleStyle: 'hairline',
    dragModel: 'glide',
    releaseSnap: 'proximity',
    smoothing: 0.64,
    edgeResistance: 0.62,
    snapStrength: 0.24,
    snapPoints: [152, 192, 236],
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: false,
    showPreviewBar: false,
    recommended: true,
  },
  {
    id: 'figma-rail',
    name: 'Figma Rail',
    description: '更强调精度和结构感，适合专业工具范式。',
    category: 'Productized',
    accentClassName: 'bg-blue-500',
    surfaceClassName: 'bg-white border-blue-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f7fbff)]',
    badgeClassName: 'bg-blue-100 text-blue-700',
    handleStyle: 'block',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: true,
    showPreviewBar: true,
  },
  {
    id: 'paper-divider',
    name: 'Paper Divider',
    description: '视觉更柔，拖拽时像在推纸张边界。',
    category: 'Aesthetic',
    accentClassName: 'bg-amber-600',
    surfaceClassName: 'bg-[#fffdfa] border-[#ece4d6]',
    canvasClassName: 'bg-[linear-gradient(180deg,#fffdfa,#faf5ec)]',
    badgeClassName: 'bg-[#f3eadf] text-[#8a745d]',
    handleStyle: 'pill',
    dragModel: 'glide',
    releaseSnap: 'proximity',
    smoothing: 0.56,
    edgeResistance: 0.7,
    snapStrength: 0.18,
    snapPoints: [148, 200, 248],
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'dense-ticks',
    name: 'Dense Ticks',
    description: '给出更多刻度，适合频繁调宽度的用户。',
    category: 'Guides',
    accentClassName: 'bg-cyan-600',
    surfaceClassName: 'bg-white border-cyan-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f3fdff)]',
    badgeClassName: 'bg-cyan-100 text-cyan-700',
    handleStyle: 'hairline',
    dragModel: 'stepped',
    releaseSnap: 'proximity',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    stepSize: 12,
    snapPoints: [132, 156, 180, 204, 228, 252],
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'contrast-block',
    name: 'Contrast Block',
    description: '拖拽条像独立控件，发现性最强。',
    category: 'Discovery',
    accentClassName: 'bg-neutral-950',
    surfaceClassName: 'bg-white border-neutral-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f8f8f8)]',
    badgeClassName: 'bg-neutral-950 text-white',
    handleStyle: 'block',
    dragModel: 'linear',
    releaseSnap: 'none',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    showGhost: false,
    showBadge: true,
    showTicks: false,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'halo-commit',
    name: 'Halo Commit',
    description: '松手后保留一瞬间的目标宽度光晕。',
    category: 'Feedback',
    accentClassName: 'bg-pink-500',
    surfaceClassName: 'bg-white border-pink-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fff7fb)]',
    badgeClassName: 'bg-pink-100 text-pink-700',
    handleStyle: 'pill',
    dragModel: 'glide',
    releaseSnap: 'proximity',
    smoothing: 0.48,
    edgeResistance: 0.7,
    snapStrength: 0.28,
    snapPoints: [148, 196, 244],
    showGhost: true,
    showBadge: true,
    showTicks: false,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'velocity-soft',
    name: 'Velocity Soft',
    description: '拖快时更宽容，拖慢时更精确。',
    category: 'Motion',
    accentClassName: 'bg-indigo-600',
    surfaceClassName: 'bg-white border-indigo-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f7f8ff)]',
    badgeClassName: 'bg-indigo-100 text-indigo-700',
    handleStyle: 'hairline',
    dragModel: 'glide',
    releaseSnap: 'none',
    smoothing: 0.5,
    edgeResistance: 0.76,
    snapStrength: 0,
    showGhost: false,
    showBadge: true,
    showTicks: false,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'anchored-card',
    name: 'Anchored Card',
    description: '侧边栏本身像一张卡片，拖拽时层次更强。',
    category: 'Aesthetic',
    accentClassName: 'bg-slate-600',
    surfaceClassName: 'bg-white border-slate-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f4f7fa)]',
    badgeClassName: 'bg-slate-100 text-slate-700',
    handleStyle: 'pill',
    dragModel: 'elastic',
    releaseSnap: 'proximity',
    smoothing: 0.8,
    edgeResistance: 0.58,
    snapStrength: 0.24,
    snapPoints: [144, 184, 228, 260],
    showGhost: true,
    showBadge: false,
    showTicks: true,
    showScrim: true,
    showPreviewBar: false,
  },
  {
    id: 'smart-default',
    name: 'Smart Default',
    description: '偏向默认宽度，离开太多时自动回正。',
    category: 'Bias',
    accentClassName: 'bg-green-600',
    surfaceClassName: 'bg-white border-green-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f5fff7)]',
    badgeClassName: 'bg-green-100 text-green-700',
    handleStyle: 'hairline',
    dragModel: 'magnetic',
    releaseSnap: 'proximity',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0.62,
    snapPoints: [168, 224],
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: true,
  },
  {
    id: 'expansion-lane',
    name: 'Expansion Lane',
    description: '越往右拖，反馈越强，鼓励用户探索更宽布局。',
    category: 'Motion',
    accentClassName: 'bg-orange-600',
    surfaceClassName: 'bg-white border-orange-100',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fff8f1)]',
    badgeClassName: 'bg-orange-100 text-orange-700',
    handleStyle: 'block',
    dragModel: 'elastic',
    releaseSnap: 'always',
    smoothing: 0.86,
    edgeResistance: 0.48,
    snapStrength: 0.42,
    snapPoints: [156, 204, 252, 272],
    showGhost: true,
    showBadge: true,
    showTicks: true,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'reduced-noise',
    name: 'Reduced Noise',
    description: '所有辅助都压到最低，只保留手感本身。',
    category: 'Minimal',
    accentClassName: 'bg-neutral-700',
    surfaceClassName: 'bg-white border-neutral-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#fbfbfc)]',
    badgeClassName: 'bg-neutral-100 text-neutral-700',
    handleStyle: 'hairline',
    dragModel: 'glide',
    releaseSnap: 'none',
    smoothing: 0.68,
    edgeResistance: 0.78,
    snapStrength: 0,
    showGhost: false,
    showBadge: false,
    showTicks: false,
    showScrim: false,
    showPreviewBar: false,
  },
  {
    id: 'command-strip',
    name: 'Command Strip',
    description: '更像专业软件的控制条，明确、坚决、无歧义。',
    category: 'Productized',
    accentClassName: 'bg-zinc-900',
    surfaceClassName: 'bg-white border-zinc-200',
    canvasClassName: 'bg-[linear-gradient(180deg,#ffffff,#f6f6f7)]',
    badgeClassName: 'bg-zinc-900 text-white',
    handleStyle: 'block',
    dragModel: 'stepped',
    releaseSnap: 'always',
    smoothing: 1,
    edgeResistance: 1,
    snapStrength: 0,
    stepSize: 20,
    snapPoints: [140, 180, 220, 260],
    showGhost: false,
    showBadge: true,
    showTicks: true,
    showScrim: true,
    showPreviewBar: false,
  },
];
