export const OBSIDIAN_APP_CHROME_CLASSES = String.raw`app-container|workspace(?:-[\w-]+)?|nav-[\w-]+|vertical-tab-nav-item|empty-state-[\w-]+|document-search(?:-[\w-]+)?|document-replace(?:-[\w-]+)?|search-(?:highlight|results-info|input(?:-[\w-]+)?)|obsidian-search-match-highlight|spellchecker-dictionary-remove-button|u-clickable|textLayer|notice|query-toolbar-menu|combobox-button|view-action|view-actions|view-header(?:-[\w-]+)?|inline-title|full-file-names|CodeMirror-(?:foldmarker|foldgutter-[\w-]+|wrap)|mod-(?:left|right|top|root|left-split|right-split|sidedock|working|success|macos|windows|linux|publish)|labeled-nav|collapse-icon|collapse-indicator|clickable-icon|list-collapse-indicator|tooltip|gemmy-tooltip|popover|hover-popover|hider-ribbon|horizontal-main-container|colorful-active|colorful-frame|git-view-body|commit-msg|cm-heading-marker|cm-panels-bottom|cm-sizer|metadata(?:-[\w-]+)?|setting(?:-[\w-]+)?|tree-item(?:-[\w-]+)?|slider|modal(?:-[\w-]+)?|status-bar(?:-[\w-]+)?|ribbon(?:-[\w-]+)?|side-dock(?:-[\w-]+)?|sync-status-icon|prompt(?:-[\w-]+)?|suggestion(?:-[\w-]+)?|community-item|titlebar(?:-[\w-]+)?|list-item-part|menu-item|tab-stack-[\w-]+|MiniSettings-statusbar-button|themed-color-wrapper|reader-mode-content|publish(?:-[\w-]+)?|menu|button|input`;

export const OBSIDIAN_PLUGIN_CHROME_CLASSES = String.raw`search-result-file-match|search-result-file-matched-text|edit-block-button|excalibrain-[\w-]+|excalidraw-dirty|obsidian-icon-folder-icon|release-notes-view|recent-files-[\w-]+|file-embed-link|pdf-shadows-on|pdf-viewer|pdfViewer|pdf-sidebar-container|thumbnailSelectionRing|canvasWrapper|cMenuCommandItem|cMenuToolbar(?:-[\w-]+)?|cMenuToolbarCommandItem|cMenuToolbarCommandsubItem|cMenuToolbar-Divider-Line|cMenuToolbarDefaultAesthetic`;

export const OBSIDIAN_PAGE_CHROME_IDS = String.raw`cMenuModalBar|cMenuToolbarModalBar|calendar-container`;

export const OBSIDIAN_PAGE_CHROME_SELECTOR_PATTERNS = [
  /(?:#calendar-container|\.calendar\b).*\.(?:arrow|day|week-num|reset-button)(?:$|[^\w-])/i,
  /\[\s*class\s*\*=\s*["']?recent-files-/i,
  /\.markdown-rendered\s+\.mod-header\b/i,
  /\.markdown-preview-view\s+\.mod-highlighted\b/i,
  /\.markdown-preview-view\s*>\s*div(?:$|[\s.#:[>+~])/i,
  /\bdiv\.image-embed:focus-within\s+\.image-wrapper(?=$|[^\w-])/i,
];

export const OBSIDIAN_THEME_SETTING_OR_PLUGIN_CLASSES = String.raw`anp-[\w-]+|anuppuccin-[\w-]+|ctp-[\w-]+|minimal-[\w-]+|cards(?:-[\w-]+)?|list-cards|table-disable|tasks|task-metadata|task-date|task-overdue|task-calendar-icon|task-project-icon|task-labels-icon|progress-color|fancy-code|fancy-highlight|active-line|colorful-headings|full-width-media|tabular|table-tabular|row-hover|row-alt|trim-cols|row-lines(?:-off)?|col-lines|callouts-outlined|plain-external-links|mobile-black-background|image-blend-light|links-int-on|links-ext-on|heading-normal-toggle|decorations-normal-toggle|rainbow-tags|heading-underline-color|default-font-color|h[1-6]-(?:small-caps|underline|l)|h2-no-underline|checklist-plugin-[\w-]+|kanban-plugin(?:__[\w-]+)?|no-kanban-styles|dataview(?:-[\w-]+)?|block-language-dataview(?:js)?|block-language-chart|markdown-embed(?:-[\w-]+)?|internal-embed|inline-embed|embed-[\w-]+|bases-[\w-]+|mk-[\w-]+|todoist-[\w-]+|style-settings-[\w-]+|frontmatter-container|banner-image|obsidian-banner-[\w-]+|excalidraw|plugin-obsidian-discordrpc|multiselect-[\w-]+|cMenuCommandItem|cMenuToolbar(?:-[\w-]+)?|cMenuToolbarCommandItem|cMenuToolbarCommandsubItem|cMenuToolbar-Divider-Line|cMenuToolbarDefaultAesthetic|cm-embed-block|cm-callout|cm-vim-panel|cm-html-embed|cm-table-widget|cm-contentContainer|cm-formatting(?:-[\w-]+)?|cm-hmd-internal-link|cm-link-alias-pipe|cm-hmd-table-sep(?:-dummy)?|callout-fold|table-cell-wrapper|el-table|table-(?:wide|max|100|small|tiny|center|lines|nowrap(?:-first)?|numbers)|img-(?:wide|max|100|blend|grid-ratio)|iframe-(?:wide|max|100)|node-insert-event|mod-inside-iframe|canvas-[\w-]+|img-grid|is-loaded|map-(?:wide|max|100)|chart-(?:wide|max|100)|zoom-plugin-[\w-]+|checkbox-container|checkbox-square|dropdown|slider|disable-animations|fast-animations|mod-sidedock|is-translucent|is-fullscreen|is-focused|is-rtl|rtl|is-unresolved|is-collapsible|print(?:-preview)?|wide|maximize-tables(?:-auto)?|borders-none|table-view-table`;

export const OBSIDIAN_EXTENSION_SELECTOR_PATTERNS = [
  /\[\s*class\s*\*=\s*["']?mk-/i,
  /(?:#calendar-container|\.calendar\b).*\.(?:arrow|day|week-num|reset-button)(?:$|[^\w-])/i,
];
