import {
  APP_MONO_FONT_FAMILY,
  APP_SANS_FONT_FAMILY,
} from '@/lib/typography/fontFamilies';

export const MARKDOWN_BODY_FONT_SIZE = 19;
export const MARKDOWN_INLINE_CODE_FONT_SIZE = 14;

export const MARKDOWN_BODY_FONT = `normal 400 ${MARKDOWN_BODY_FONT_SIZE}px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_BODY_LINK_FONT = `normal 500 ${MARKDOWN_BODY_FONT_SIZE}px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_BODY_BOLD_FONT = `normal 600 ${MARKDOWN_BODY_FONT_SIZE}px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_BODY_ITALIC_FONT = `italic 400 ${MARKDOWN_BODY_FONT_SIZE}px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_BODY_BOLD_ITALIC_FONT = `italic 600 ${MARKDOWN_BODY_FONT_SIZE}px ${APP_SANS_FONT_FAMILY}`;

export const MARKDOWN_HEADING_ONE_FONT = `normal 700 28px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_TWO_FONT = `normal 600 26px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_THREE_FONT = `normal 600 24px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_FOUR_FONT = `normal 600 22px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_FIVE_FONT = `normal 600 20px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_SIX_FONT = `normal 600 18px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_ONE_BOLD_FONT = MARKDOWN_HEADING_ONE_FONT;
export const MARKDOWN_HEADING_ONE_ITALIC_FONT = `italic 700 28px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_ONE_BOLD_ITALIC_FONT = MARKDOWN_HEADING_ONE_ITALIC_FONT;
export const MARKDOWN_HEADING_TWO_BOLD_FONT = MARKDOWN_HEADING_TWO_FONT;
export const MARKDOWN_HEADING_TWO_ITALIC_FONT = `italic 600 26px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_TWO_BOLD_ITALIC_FONT = MARKDOWN_HEADING_TWO_ITALIC_FONT;
export const MARKDOWN_HEADING_THREE_BOLD_FONT = MARKDOWN_HEADING_THREE_FONT;
export const MARKDOWN_HEADING_THREE_ITALIC_FONT = `italic 600 24px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_THREE_BOLD_ITALIC_FONT = MARKDOWN_HEADING_THREE_ITALIC_FONT;
export const MARKDOWN_HEADING_FOUR_BOLD_FONT = MARKDOWN_HEADING_FOUR_FONT;
export const MARKDOWN_HEADING_FOUR_ITALIC_FONT = `italic 600 22px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_FOUR_BOLD_ITALIC_FONT = MARKDOWN_HEADING_FOUR_ITALIC_FONT;
export const MARKDOWN_HEADING_FIVE_BOLD_FONT = MARKDOWN_HEADING_FIVE_FONT;
export const MARKDOWN_HEADING_FIVE_ITALIC_FONT = `italic 600 20px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_FIVE_BOLD_ITALIC_FONT = MARKDOWN_HEADING_FIVE_ITALIC_FONT;
export const MARKDOWN_HEADING_SIX_BOLD_FONT = MARKDOWN_HEADING_SIX_FONT;
export const MARKDOWN_HEADING_SIX_ITALIC_FONT = `italic 600 18px ${APP_SANS_FONT_FAMILY}`;
export const MARKDOWN_HEADING_SIX_BOLD_ITALIC_FONT = MARKDOWN_HEADING_SIX_ITALIC_FONT;

export const MARKDOWN_INLINE_CODE_FONT = `500 ${MARKDOWN_INLINE_CODE_FONT_SIZE}px ${APP_MONO_FONT_FAMILY}`;
export const MARKDOWN_INLINE_CODE_EXTRA_WIDTH = 12;

export const MARKDOWN_BODY_LINE_HEIGHT = MARKDOWN_BODY_FONT_SIZE + 8;
export const MARKDOWN_HEADING_ONE_LINE_HEIGHT = 36;
export const MARKDOWN_HEADING_TWO_LINE_HEIGHT = 36;
export const MARKDOWN_HEADING_THREE_LINE_HEIGHT = 32;
export const MARKDOWN_HEADING_FOUR_LINE_HEIGHT = 30;
export const MARKDOWN_HEADING_FIVE_LINE_HEIGHT = 28;
export const MARKDOWN_HEADING_SIX_LINE_HEIGHT = 26;
export const MARKDOWN_CODE_LINE_HEIGHT = MARKDOWN_BODY_LINE_HEIGHT;
export const MARKDOWN_BLOCKQUOTE_LINE_HEIGHT = MARKDOWN_BODY_LINE_HEIGHT;
export const MARKDOWN_BLOCKQUOTE_CONTENT_INSET = 17;
export const MARKDOWN_BLOCKQUOTE_PADDING_Y = 20;
export const MARKDOWN_CODE_BLOCK_HEADER_HEIGHT = 40;
export const MARKDOWN_CODE_BLOCK_PADDING_Y = 16;
export const MARKDOWN_RULE_HEIGHT = 30;
export const MARKDOWN_BLOCK_GAP = 20;
export const MARKDOWN_LIST_CONTENT_INSET = 32;
export const MARKDOWN_LIST_MARGIN_Y = 16;
export const MARKDOWN_LIST_ITEM_MARGIN_Y = 12;
export const MARKDOWN_TABLE_MARGIN_Y = 32;
export const MARKDOWN_TABLE_LINE_HEIGHT = MARKDOWN_BODY_LINE_HEIGHT;
export const MARKDOWN_TABLE_CELL_PADDING_Y = 16;
export const MARKDOWN_TABLE_BORDER_Y = 2;
export const MARKDOWN_TABLE_ROW_BORDER_Y = 1;
