export const MAX_EXCLUDED_RANGES = 50_000;
export const MAX_MARKDOWN_LINK_PART_SCAN_CHARS = 64 * 1024;
export const MAX_FAILED_MARKDOWN_LINK_PART_SCAN_CHARS = 4 * MAX_MARKDOWN_LINK_PART_SCAN_CHARS;
export const MAX_FRONTMATTER_DELIMITER_LINE_CHARS = 1024;
export const MAX_FRONTMATTER_CHARS = 256 * 1024;
export const MAX_FRONTMATTER_LINES = 2048;
