/**
 * Config Module - Application configuration
 */

export {
  // Settings defaults
  DEFAULT_TIMEZONE,
  DEFAULT_VIEW_MODE,
  DEFAULT_DAY_COUNT,
  DEFAULT_HOUR_HEIGHT,
  DEFAULT_USE_24_HOUR,
  DEFAULT_DAY_START_TIME,

  // Group defaults
  DEFAULT_GROUP_ID,
  DEFAULT_GROUP_NAME,

  // Storage keys
  STORAGE_KEY_COLOR_FILTER,
  STORAGE_KEY_STATUS_FILTER,
  STORAGE_KEY_SHORTCUTS,
  STORAGE_KEY_PENDING_SYNC,
  STORAGE_KEY_FONT_SIZE,
  STORAGE_KEY_AUTO_UPDATE,
  STORAGE_KEY_NOTES_SIDEBAR_COLLAPSED,
  STORAGE_KEY_SHOW_SIDEBAR,

  // Aggregated
  DEFAULT_SETTINGS,
} from './defaults';
