export const MAX_DESKTOP_COMMAND_CHARS = 2048;
export const MAX_DESKTOP_COMMAND_CWD_CHARS = 4096;
export const MAX_DESKTOP_COMMAND_PURPOSE_CHARS = 500;
export const MAX_COMPUTER_COMMAND_STATUS_OUTPUT_CHARS = 64 * 1024;
export const MAX_COMPUTER_COMMAND_STATUSES = 12;
