export type BlockTextMatcher = {
  include?: string;
  exact?: string;
  exclude?: string[];
};

export type MarkdownDragSyntaxCase = {
  label: string;
  targetSelector: string;
  targetText?: string;
  match?: BlockTextMatcher;
  gap: 'standard' | 'list' | 'nested-list';
  anchorSelector?: string;
  anchorText?: string;
};

export type SyntaxHandleGeometry = {
  label: string;
  selectedCount: number;
  selectedMatchesTarget: boolean;
  targetTagName: string;
  targetClassName: string;
  targetText: string;
  controlsCenterY: number;
  targetCenterY: number;
  targetGapX: number;
  handleRightGapX: number;
  anchorGapX: number | null;
  targetIndentFromAnchorX: number | null;
};

export type DragVisualGeometry = {
  dragActive: boolean;
  controlsDragging: boolean;
  sourceCount: number;
  selectedCount: number;
  sourceClassName: string | null;
  sourceIsCodeBlock: boolean;
  sourceWidth: number | null;
  sourceHeight: number | null;
  sourceBackgroundColor: string | null;
  sourceBorderTopColor: string | null;
  sourceBoxShadow: string | null;
  sourceOutlineStyle: string | null;
  sourceOutlineWidth: string | null;
  sourceOpacity: string | null;
  sourceAfterBackgroundColor: string | null;
  sourceAfterLeft: number | null;
  sourceAfterRight: number | null;
  sourceCodeLineColor: string | null;
  sourceCodeLanguageColor: string | null;
  sourceCodeKeywordColor: string | null;
  sourceBleedStart: number | null;
  sourceBleedEnd: number | null;
  expectedBackground: string;
  expectedCodeBlockBackground: string;
  expectedCodeSyntaxForeground: string;
  expectedCodeSyntaxMuted: string;
  expectedCodeSyntaxKeyword: string;
  expectedCodeBlockSelectedBorderColor: string;
  expectedSelectionForeground: string;
  previewExists: boolean;
  previewWidth: number | null;
  previewHeight: number | null;
  previewBackgroundColor: string | null;
  previewOpacity: string | null;
  previewBoxShadow: string | null;
  previewLayerBackgroundColor: string | null;
  previewLayerOpacity: string | null;
  previewLayerBoxShadow: string | null;
  previewCodeBlockExists: boolean;
  previewCodeBlockWidth: number | null;
  previewCodeBlockHeight: number | null;
  previewCodeBlockBackgroundColor: string | null;
  previewCodeBlockBorderTopColor: string | null;
  previewCodeBlockBorderTopStyle: string | null;
  previewCodeBlockBorderTopWidth: string | null;
  previewCodeBlockBoxShadow: string | null;
  previewCodeBlockOutlineStyle: string | null;
  previewCodeBlockOutlineWidth: string | null;
  previewCodeBlockAfterBackgroundColor: string | null;
  previewCodeBlockSurfaceBackgroundColor: string | null;
  controlsBeforeBackgroundColor: string | null;
};
