export const TINY_PNG_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=';
export const REMOTE_COVER_IMAGE_URL =
  'https://raw.githubusercontent.com/521xueweihan/img_logo/master/logo/cover.jpg#w=72%25';

export type MarkdownSyntaxRoundtripCase = {
  label: string;
  markdown: string;
};

export function createMarkdownSyntaxRoundtripCases(): MarkdownSyntaxRoundtripCase[] {
  return [
    {
      label: 'frontmatter',
      markdown: [
        '---',
        'title: Roundtrip Syntax',
        'tags:',
        '  - e2e',
        '  - roundtrip',
        '---',
        '',
        '# Frontmatter Roundtrip Sentinel',
      ].join('\n'),
    },
    {
      label: 'headings-and-toc',
      markdown: [
        '# ATX Heading Sentinel',
        '',
        '[TOC]',
        '',
        '{:toc}',
        '',
        'Setext Heading Level One Sentinel',
        '=================================',
        '',
        'Setext Heading Level Two Sentinel',
        '---------------------------------',
        '',
        '## Closed Heading Sentinel ##',
        '',
        '###### Level Six Sentinel',
      ].join('\n'),
    },
    {
      label: 'inline-marks-and-links',
      markdown: [
        'Inline marks: **strong**, __strong underscore__, *emphasis*, _emphasis underscore_, ~~strike~~, ==highlight==, ++underline++, ^sup^, ~sub~, `code`, [explicit](https://example.com/docs), [ref][docs-ref], <https://example.com/autolink>, www.example.org, syntax@example.com, #syntax-tag.',
        '',
        '[docs-ref]: https://example.com/reference "Reference title"',
        '',
        'Nested inline: ***bold italic***, **bold with `code child`**, and `` npm run `build` ``.',
        '',
        '<span style="color: #2563eb">colored text sentinel</span> <mark style="background-color: #fde047">background sentinel</mark>',
        '',
        '*[API]: Application Programming Interface',
        '',
        'API abbreviation sentinel.',
      ].join('\n'),
    },
    {
      label: 'paragraphs-and-breaks',
      markdown: [
        'Soft break line one sentinel',
        'soft break line two sentinel.',
        '',
        'Hard break line one sentinel  ',
        'hard break line two sentinel.',
        '',
        'Backslash hard break line one sentinel\\',
        'backslash hard break line two sentinel.',
        '',
        'HTML break line one sentinel<br/>HTML break line two sentinel.',
        '',
        'Escaped syntax sentinel: \\# not a heading, \\[TOC\\], \\*not emphasis\\*, \\!\\[not image\\](image.png).',
      ].join('\n'),
    },
    {
      label: 'blockquotes-and-callouts',
      markdown: [
        '> Regular quote line one.',
        '> Regular quote line two.',
        '',
        '> Nested quote container sentinel.',
        '> ',
        '> - Nested quote bullet sentinel',
        '> ',
        '> ```ts',
        '> const quoteCodeSentinel = true;',
        '> ```',
        '',
        '> [!callout-icon:%F0%9F%93%8C] Callout encoded icon sentinel.',
        '> Encoded icon callout body sentinel.',
        '',
        '> <!--callout-icon:%F0%9F%94%A5-->',
        '> HTML comment icon callout body sentinel.',
      ].join('\n'),
    },
    {
      label: 'lists',
      markdown: [
        '- Bullet item alpha',
        '- Bullet item beta',
        '  - Nested bullet beta child',
        '    - Third-level bullet sentinel',
        '+ Plus bullet item sentinel',
        '* Star bullet item sentinel',
        '',
        '- Mixed list parent sentinel',
        '  1. Nested ordered child sentinel',
        '     - Third-level mixed bullet sentinel',
        '',
        '1. Ordered item alpha',
        '2. Ordered item beta',
        '',
        '- Loose bullet item alpha',
        '',
        '- Loose bullet item beta',
        '',
        '1. Loose ordered item alpha',
        '',
        '2. Loose ordered item beta',
        '',
        '1) Parenthesized ordered item alpha',
        '2) Parenthesized ordered item beta',
        '',
        '7. Ordered item custom start sentinel',
        '8. Ordered item custom continuation sentinel',
        '',
        '- [ ] Task item unchecked sentinel',
        '- [x] Task item checked sentinel',
        '  - [ ] Nested task item sentinel',
      ].join('\n'),
    },
    {
      label: 'definition-lists',
      markdown: [
        'Term sentinel',
        ': Definition description sentinel',
        '',
        'Second term sentinel',
        ': Second definition description sentinel',
        '',
        'Escaped definition term sentinel',
        '\\: Escaped definition marker sentinel',
      ].join('\n'),
    },
    {
      label: 'tables',
      markdown: [
        '| Feature | Status | Count |',
        '| :--- | :---: | ---: |',
        '| Table alpha | Stable | 1 |',
        '| Table beta | Covered | 2 |',
        '| Escaped \\| pipe | **Bold table sentinel** and [table link](https://example.com?a=1&b=2) | 3 |',
        '| `a \\| b` | \\*literal table marker\\* | 4 |',
      ].join('\n'),
    },
    {
      label: 'horizontal-rules',
      markdown: [
        'Before rule sentinel.',
        '',
        '---',
        '',
        '***',
        '',
        '___',
        '',
        'After rule sentinel.',
      ].join('\n'),
    },
    {
      label: 'code-blocks',
      markdown: [
        '```ts',
        'const syntaxSentinel: string = "code block sentinel";',
        'console.log(syntaxSentinel);',
        '```',
        '',
        '~~~js',
        'const tildeFenceSentinel = 1;',
        '~~~',
        '',
        '````md',
        '```ts',
        'const nestedFenceSentinel = 1;',
        '```',
        '````',
        '',
        '    indented code block sentinel',
        '    indented code second line sentinel',
      ].join('\n'),
    },
    {
      label: 'math',
      markdown: [
        '$$',
        'E = mc^2',
        '$$',
        '',
        '\\[',
        'f=\\mu mg',
        '\\]',
        '',
        '[',
        'a=\\frac{f}{m}=\\mu g',
        ']',
        '',
        'Advanced inline math sentinel $\\ce{H2O}$ and $\\pu{123 kJ mol-1}$ live here.',
        '',
        'Inline math sentinel $a^2 + b^2 = c^2$ lives here.',
      ].join('\n'),
    },
    {
      label: 'diagrams',
      markdown: [
        '```mermaid',
        'flowchart TD',
        '  Start[E2E Start] --> Done[E2E Done]',
        '```',
        '',
        '```sequence',
        'Alice->Bob: Diagram alias sentinel',
        '```',
        '',
        '```packet-beta',
        '0-7: "Mermaid packet alias sentinel"',
        '```',
      ].join('\n'),
    },
    {
      label: 'media',
      markdown: [
        `![Image alt sentinel](${TINY_PNG_DATA_URL} "Image title sentinel")`,
        '',
        `<img src="${TINY_PNG_DATA_URL}" alt="HTML image alt sentinel" width="40%" align="right" title="HTML image title sentinel" data-vlaina-crop="1,2,30,40,1" />`,
        '',
        `<img src="${REMOTE_COVER_IMAGE_URL}" alt="HTML crop cover sentinel" width="72%" data-vlaina-crop="0.108735,0.117569,99.891265,99.882431,2.349414" />`,
        '',
        `![Second markdown image sentinel](${TINY_PNG_DATA_URL})`,
        '',
        '![video](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video title sentinel")',
        '',
        '![Direct video sentinel](https://example.com/video.mp4)',
      ].join('\n'),
    },
    {
      label: 'footnotes',
      markdown: [
        'Footnote reference sentinel[^syntax-note].',
        '',
        '[^syntax-note]: Footnote definition sentinel.',
        '',
        'Nested footnote reference sentinel[^nested-note].',
        '',
        '[^nested-note]: Nested footnote first paragraph sentinel.',
        '',
        '    Nested footnote second paragraph sentinel.',
        '',
        '    - Nested footnote list item sentinel',
      ].join('\n'),
    },
    {
      label: 'alignment-and-html',
      markdown: [
        'Centered paragraph sentinel.',
        '<!--align:center-->',
        '',
        '### Right aligned heading sentinel',
        '<!--align:right-->',
        '',
        '<div class="raw-html-sentinel">Raw HTML block sentinel</div>',
        '',
        'Inline raw HTML sentinel: <kbd>Ctrl</kbd>+<kbd>F9</kbd> <ruby>han<rt>han sentinel</rt></ruby>.',
        '',
        '<details open><summary>Details summary sentinel</summary><p>Details body sentinel</p></details>',
        '',
        '<pre>',
        'raw pre html sentinel',
        '</pre>',
        '',
        '<?note processing sentinel?>',
        '',
        '<![CDATA[',
        'cdata raw html sentinel',
        ']]>',
        '',
        '<iframe src="https://example.com/embed"></iframe>',
        '',
        '<video src="xxx.mp4" controls />',
        '',
        '<audio src="xxx.mp3" controls />',
      ].join('\n'),
    },
  ];
}

export function createMarkdownSyntaxFixture(): string {
  return [
    '---',
    'title: E2E Markdown Syntax',
    'tags:',
    '  - e2e',
    '  - markdown',
    '---',
    '',
    '# E2E Markdown Syntax',
    '',
    '[TOC]',
    '',
    '{:toc}',
    '',
    '## Heading Coverage',
    '',
    'Setext Heading Level One Sentinel',
    '=================================',
    '',
    'Setext Heading Level Two Sentinel',
    '---------------------------------',
    '',
    '## ATX Closed Heading Sentinel ##',
    '',
    '### Heading Level Three Sentinel',
    '',
    '#### Heading Level Four Sentinel',
    '',
    '##### Heading Level Five Sentinel',
    '',
    '###### Heading Level Six Sentinel',
    '',
    '## Inline Marks And Links',
    '',
    'Inline marks paragraph: **strong text**, __strong underscore text__, *emphasis text*, _emphasis underscore text_, ~~strike text~~, ==highlighted text==, ++underlined text++, ^superscript text^, ~subscript text~, `inline code`, [explicit link](https://example.com/docs), [reference docs link][docs-ref], [internal note link](./linked-note.md#target-heading), <https://example.com/autolink-angle>, www.example.org, syntax@example.com, #syntax-tag, HTML.',
    '',
    '[docs-ref]: https://example.com/reference "Reference docs title"',
    '',
    'Reference variants: [parenthesized guide](https://example.com/docs/a_(b) "Guide title"), [angle local file](<docs/file name.md> "File Guide"), and [query link](<docs/file (draft).md?x=1&y=2>).',
    '',
    'Nested inline sentinel: ***bold italic sentinel***, **bold with `inline code child` sentinel**, `*literal* [text] &lt;tag&gt;`, and `` npm run `build` ``.',
    '',
    'Entity sentinel: AT&T, &copy;, and 3 &lt; 5.',
    '',
    '<span style="color: #2563eb">colored text sentinel</span> <mark style="background-color: #fde047">background color sentinel</mark>',
    '',
    'HTML inline marks: <mark>html mark sentinel</mark> <sup>html sup sentinel</sup> <sub>html sub sentinel</sub> <u>html underline sentinel</u>.',
    '',
    '<span style="color: rgb(37, 99, 235)">rgb colored text sentinel</span> <mark style="background-color: yellow">named background color sentinel</mark>',
    '',
    '<span class="syntax-color-extra" style="font-weight: 600; COLOR: #123456">mixed css color sentinel</span> <mark data-bg-color="#ecf6ff" style="border-radius: 2px; background-color: #ecf6ff">mixed css background sentinel</mark>',
    '',
    '<span style="color : #0f766e"><em>nested color emphasis sentinel</em></span> <mark style="background-color : #fef3c7"><strong>nested background strong sentinel</strong></mark>',
    '',
    'Escaped custom inline mark sentinels: \\==literal highlight==, X\\^literal sup^, H\\~literal sub~O, and \\++literal underline++.',
    '',
    'Escaped HTML mark text: <sup>a &lt; b &amp; c</sup> <sub>x &gt; y</sub> <mark>a = b &lt; c</mark> <u>x + y &amp; z</u>.',
    '',
    '<span data-note="keep">unsupported inline span sentinel &lt; text</span>',
    '',
    '*[HTML]: HyperText Markup Language',
    '',
    '*[API]: Application Programming Interface',
    '',
    '\\*[ESCAPED]: Escaped abbreviation definition sentinel',
    '',
    'API abbreviation sentinel.',
    '',
    '## Paragraphs And Breaks',
    '',
    'Soft break line one sentinel',
    'soft break line two sentinel.',
    '',
    'Hard break line one sentinel  ',
    'hard break line two sentinel.',
    '',
    'Backslash hard break line one sentinel\\',
    'backslash hard break line two sentinel.',
    '',
    'HTML break line one sentinel<br/>HTML break line two sentinel.',
    '',
    'Escaped syntax sentinel: \\# not a heading, \\[TOC\\], \\*not emphasis\\*, \\!\\[not image\\](image.png).',
    '',
    '## Block Quotes And Callouts',
    '',
    '> Regular quote line one.',
    '> Regular quote line two.',
    '',
    '> Nested quote container sentinel.',
    '> ',
    '> - Nested quote bullet sentinel',
    '> ',
    '> ```ts',
    '> const quoteCodeSentinel = true;',
    '> ```',
    '',
    '> 💡 Emoji callout sentinel.',
    '> ',
    '> Callout second line sentinel.',
    '',
    '> [!callout-icon:%F0%9F%93%8C] Callout encoded icon sentinel.',
    '> Encoded icon callout body sentinel.',
    '',
    '> <!--callout-icon:%F0%9F%94%A5-->',
    '> HTML comment icon callout body sentinel.',
    '',
    '## Lists',
    '',
    '- Bullet item alpha',
    '- Bullet item beta',
    '  - Nested bullet beta child',
    '    - Third-level bullet sentinel',
    '+ Plus bullet item sentinel',
    '* Star bullet item sentinel',
    '',
    '- Mixed list parent sentinel',
    '  1. Nested ordered child sentinel',
    '     - Third-level mixed bullet sentinel',
    '',
    '1. Ordered item alpha',
    '2. Ordered item beta',
    '',
    '- Loose bullet item alpha',
    '',
    '- Loose bullet item beta',
    '',
    '1. Loose ordered item alpha',
    '',
    '2. Loose ordered item beta',
    '',
    '1) Parenthesized ordered item alpha',
    '2) Parenthesized ordered item beta',
    '',
    'Ordered list separator paragraph sentinel.',
    '',
    '7. Ordered item custom start sentinel',
    '8. Ordered item custom continuation sentinel',
    '',
    '- [ ] Task item unchecked sentinel',
    '- [x] Task item checked sentinel',
    '  - [ ] Nested task item sentinel',
    '',
    '- [X] Task item uppercase checked sentinel',
    '',
    '  Loose task detail sentinel',
    '',
    '## Definition Lists',
    '',
    'Term sentinel',
    ': Definition description sentinel',
    '',
    'Second term sentinel',
    ': Second definition description sentinel',
    '',
    'Combined term sentinel',
    ': Combined definition description sentinel',
    '',
    'Escaped definition term sentinel',
    '\\: Escaped definition marker sentinel',
    '',
    '## Tables',
    '',
    '| Feature | Status | Count |',
    '| :--- | :---: | ---: |',
    '| Table alpha | Stable | 1 |',
    '| Table beta | Covered | 2 |',
    '| Escaped \\| pipe | **Bold table sentinel** and [table link](https://example.com?a=1&b=2) | 3 |',
    '| `a \\| b` | \\*literal table marker\\* | 4 |',
    '',
    '## Horizontal Rules',
    '',
    '---',
    '',
    '***',
    '',
    '___',
    '',
    '## Code',
    '',
    '```ts',
    'const syntaxSentinel: string = "code block sentinel";',
    'console.log(syntaxSentinel);',
    '```',
    '',
    '```JS',
    'const languageAliasSentinel = 1;',
    '```',
    '',
    '~~~js',
    'const tildeFenceSentinel = 1;',
    '~~~',
    '',
    '````md',
    '```ts',
    'const nestedFenceSentinel = 1;',
    '```',
    '````',
    '',
    '```',
    'plain code block sentinel',
    '```',
    '',
    '    indented code block sentinel',
    '    indented code second line sentinel',
    '',
    '## Math',
    '',
    '$$',
    'E = mc^2',
    '$$',
    '',
    '\\[',
    'f=\\mu mg',
    '\\]',
    '',
    '[',
    'a=\\frac{f}{m}=\\mu g',
    ']',
    '',
    '$$',
    '\\begin{align}a&=b\\\\c&=d\\end{align}',
    '$$',
    '',
    'Advanced inline math sentinels $\\ce{H2O}$ and $\\pu{123 kJ mol-1}$ live here.',
    '',
    'Inline math sentinel $a^2 + b^2 = c^2$ lives in this sentence.',
    '',
    '## Diagrams',
    '',
    '```mermaid',
    'flowchart TD',
    '  Start[E2E Start] --> Done[E2E Done]',
    '```',
    '',
    '```sequence',
    'Alice->Bob: Diagram alias sentinel',
    '```',
    '',
    '```flow',
    'FlowAliasStart[Flow alias sentinel] --> FlowAliasDone[Done]',
    '```',
    '',
    '```flowchart-v2',
    'FlowchartAliasStart[Flowchart alias sentinel] --> FlowchartAliasDone[Done]',
    '```',
    '',
    '```mermaid',
    '%% keep this comment',
    'flow LR',
    'FlowDirectionStart[Flow direction alias sentinel] --> FlowDirectionDone[Done]',
    '```',
    '',
    '```zenuml',
    'title Mermaid zenuml alias sentinel',
    'Bob',
    'Alice',
    'Alice->Bob: Hi Bob',
    '```',
    '',
    '```packet-beta',
    '0-7: "Mermaid packet alias sentinel"',
    '```',
    '',
    '## Media',
    '',
    `![Image alt sentinel](${TINY_PNG_DATA_URL} "Image title sentinel")`,
    '',
    `<img src="${TINY_PNG_DATA_URL}" alt="HTML image alt sentinel" width="40%" align="right" title="HTML image title sentinel" data-vlaina-crop="1,2,30,40,1" />`,
    '',
    `<img src="${REMOTE_COVER_IMAGE_URL}" alt="HTML crop cover sentinel" width="72%" data-vlaina-crop="0.108735,0.117569,99.891265,99.882431,2.349414" />`,
    '',
    `<img src='${TINY_PNG_DATA_URL}' alt='HTML single quote image sentinel' width='50%' align='left' title='HTML single quote title sentinel' />`,
    '',
    `![Second markdown image sentinel](${TINY_PNG_DATA_URL})`,
    '',
    `![Markdown image escaped < sentinel](${TINY_PNG_DATA_URL} "Markdown image title & sentinel")`,
    '',
    '![video](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video title sentinel")',
    '',
    '![YouTube short video sentinel](https://youtu.be/dQw4w9WgXcQ)',
    '',
    '![Bilibili video sentinel](https://www.bilibili.com/video/BV1xx411c7mD/)',
    '',
    '![Direct video sentinel](https://example.com/video.mp4)',
    '',
    '## Footnotes',
    '',
    'Footnote reference sentinel[^syntax-note].',
    '',
    '[^syntax-note]: Footnote definition sentinel.',
    '',
    'Nested footnote reference sentinel[^nested-note].',
    '',
    '[^nested-note]: Nested footnote first paragraph sentinel.',
    '',
    '    Nested footnote second paragraph sentinel.',
    '',
    '    - Nested footnote list item sentinel',
    '',
    '## Alignment',
    '',
    'Centered paragraph sentinel.',
    '<!--align:center-->',
    '',
    '### Right aligned heading sentinel',
    '<!--align:right-->',
    '',
    '## Raw HTML',
    '',
    '<div class="raw-html-sentinel">Raw HTML block sentinel</div>',
    '',
    'Inline raw HTML sentinel: <kbd>Ctrl</kbd>+<kbd>F9</kbd> <ruby>漢<rt>han sentinel</rt></ruby>.',
    '',
    '<details open><summary>Details summary sentinel</summary><p>Details body sentinel</p></details>',
    '',
    '<pre>',
    'raw pre html sentinel',
    '</pre>',
    '',
    '<?note processing sentinel?>',
    '',
    '<![CDATA[',
    'cdata raw html sentinel',
    ']]>',
    '',
    '<iframe src="https://example.com/embed"></iframe>',
    '',
    '<video src="xxx.mp4" controls />',
    '',
    '<audio src="xxx.mp3" controls />',
    '',
    'Final paragraph sentinel for block selection.',
    '',
  ].join('\n');
}
