export const TINY_PNG_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=';

export function createMarkdownSyntaxFixture(): string {
  return [
    '---',
    'title: E2E Markdown Syntax',
    'tags:',
    '  - e2e',
    '  - markdown',
    '---',
    '',
    '# E2E Markdown Syntax',
    '',
    '[TOC]',
    '',
    '{:toc}',
    '',
    '## Heading Coverage',
    '',
    'Setext Heading Level One Sentinel',
    '=================================',
    '',
    'Setext Heading Level Two Sentinel',
    '---------------------------------',
    '',
    '## ATX Closed Heading Sentinel ##',
    '',
    '### Heading Level Three Sentinel',
    '',
    '#### Heading Level Four Sentinel',
    '',
    '##### Heading Level Five Sentinel',
    '',
    '###### Heading Level Six Sentinel',
    '',
    '## Inline Marks And Links',
    '',
    'Inline marks paragraph: **strong text**, __strong underscore text__, *emphasis text*, _emphasis underscore text_, ~~strike text~~, ==highlighted text==, ++underlined text++, ^superscript text^, ~subscript text~, `inline code`, [explicit link](https://example.com/docs), [reference docs link][docs-ref], [internal note link](./linked-note.md#target-heading), <https://example.com/autolink-angle>, www.example.org, syntax@example.com, #syntax-tag, HTML.',
    '',
    '[docs-ref]: https://example.com/reference "Reference docs title"',
    '',
    '<span style="color: #2563eb">colored text sentinel</span> <mark style="background-color: #fde047">background color sentinel</mark>',
    '',
    'HTML inline marks: <mark>html mark sentinel</mark> <sup>html sup sentinel</sup> <sub>html sub sentinel</sub> <u>html underline sentinel</u>.',
    '',
    '<span style="color: rgb(37, 99, 235)">rgb colored text sentinel</span> <mark style="background-color: yellow">named background color sentinel</mark>',
    '',
    '*[HTML]: HyperText Markup Language',
    '',
    '*[API]: Application Programming Interface',
    '',
    'API abbreviation sentinel.',
    '',
    '## Paragraphs And Breaks',
    '',
    'Soft break line one sentinel',
    'soft break line two sentinel.',
    '',
    'Hard break line one sentinel  ',
    'hard break line two sentinel.',
    '',
    'Backslash hard break line one sentinel\\',
    'backslash hard break line two sentinel.',
    '',
    'HTML break line one sentinel<br/>HTML break line two sentinel.',
    '',
    'Escaped syntax sentinel: \\# not a heading, \\[TOC\\], \\*not emphasis\\*, \\!\\[not image\\](image.png).',
    '',
    '## Block Quotes And Callouts',
    '',
    '> Regular quote line one.',
    '> Regular quote line two.',
    '',
    '> Nested quote container sentinel.',
    '> ',
    '> - Nested quote bullet sentinel',
    '> ',
    '> ```ts',
    '> const quoteCodeSentinel = true;',
    '> ```',
    '',
    '> 💡 Emoji callout sentinel.',
    '> ',
    '> Callout second line sentinel.',
    '',
    '> [!callout-icon:%F0%9F%93%8C] Callout encoded icon sentinel.',
    '> Encoded icon callout body sentinel.',
    '',
    '> <!--callout-icon:%F0%9F%94%A5-->',
    '> HTML comment icon callout body sentinel.',
    '',
    '## Lists',
    '',
    '- Bullet item alpha',
    '- Bullet item beta',
    '  - Nested bullet beta child',
    '    - Third-level bullet sentinel',
    '+ Plus bullet item sentinel',
    '* Star bullet item sentinel',
    '',
    '- Mixed list parent sentinel',
    '  1. Nested ordered child sentinel',
    '     - Third-level mixed bullet sentinel',
    '',
    '1. Ordered item alpha',
    '2. Ordered item beta',
    '',
    'Ordered list separator paragraph sentinel.',
    '',
    '7. Ordered item custom start sentinel',
    '8. Ordered item custom continuation sentinel',
    '',
    '- [ ] Task item unchecked sentinel',
    '- [x] Task item checked sentinel',
    '  - [ ] Nested task item sentinel',
    '',
    '## Definition Lists',
    '',
    'Term sentinel',
    ': Definition description sentinel',
    '',
    'Second term sentinel',
    ': Second definition description sentinel',
    '',
    'Combined term sentinel',
    ': Combined definition description sentinel',
    '',
    '## Tables',
    '',
    '| Feature | Status | Count |',
    '| :--- | :---: | ---: |',
    '| Table alpha | Stable | 1 |',
    '| Table beta | Covered | 2 |',
    '',
    '## Horizontal Rules',
    '',
    '---',
    '',
    '***',
    '',
    '___',
    '',
    '## Code',
    '',
    '```ts',
    'const syntaxSentinel: string = "code block sentinel";',
    'console.log(syntaxSentinel);',
    '```',
    '',
    '```',
    'plain code block sentinel',
    '```',
    '',
    '    indented code block sentinel',
    '    indented code second line sentinel',
    '',
    '## Math',
    '',
    '$$',
    'E = mc^2',
    '$$',
    '',
    '\\[',
    'f=\\mu mg',
    '\\]',
    '',
    'Inline math sentinel $a^2 + b^2 = c^2$ lives in this sentence.',
    '',
    '## Diagrams',
    '',
    '```mermaid',
    'flowchart TD',
    '  Start[E2E Start] --> Done[E2E Done]',
    '```',
    '',
    '```sequence',
    'Alice->Bob: Diagram alias sentinel',
    '```',
    '',
    '```flow',
    'FlowAliasStart[Flow alias sentinel] --> FlowAliasDone[Done]',
    '```',
    '',
    '```flowchart-v2',
    'FlowchartAliasStart[Flowchart alias sentinel] --> FlowchartAliasDone[Done]',
    '```',
    '',
    '```mermaid',
    '%% keep this comment',
    'flow LR',
    'FlowDirectionStart[Flow direction alias sentinel] --> FlowDirectionDone[Done]',
    '```',
    '',
    '## Media',
    '',
    `![Image alt sentinel](${TINY_PNG_DATA_URL} "Image title sentinel")`,
    '',
    `<img src="${TINY_PNG_DATA_URL}" alt="HTML image alt sentinel" width="40%" align="right" title="HTML image title sentinel" data-vlaina-crop="1,2,30,40,1" />`,
    '',
    `<img src='${TINY_PNG_DATA_URL}' alt='HTML single quote image sentinel' width='50%' align='left' title='HTML single quote title sentinel' />`,
    '',
    `![Second markdown image sentinel](${TINY_PNG_DATA_URL})`,
    '',
    `![Markdown image escaped < sentinel](${TINY_PNG_DATA_URL} "Markdown image title & sentinel")`,
    '',
    '![video](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video title sentinel")',
    '',
    '![YouTube short video sentinel](https://youtu.be/dQw4w9WgXcQ)',
    '',
    '![Bilibili video sentinel](https://www.bilibili.com/video/BV1xx411c7mD/)',
    '',
    '![Direct video sentinel](https://example.com/video.mp4)',
    '',
    '## Footnotes',
    '',
    'Footnote reference sentinel[^syntax-note].',
    '',
    '[^syntax-note]: Footnote definition sentinel.',
    '',
    'Nested footnote reference sentinel[^nested-note].',
    '',
    '[^nested-note]: Nested footnote first paragraph sentinel.',
    '',
    '    Nested footnote second paragraph sentinel.',
    '',
    '    - Nested footnote list item sentinel',
    '',
    '## Alignment',
    '',
    'Centered paragraph sentinel.',
    '<!--align:center-->',
    '',
    '### Right aligned heading sentinel',
    '<!--align:right-->',
    '',
    '## Raw HTML',
    '',
    '<div class="raw-html-sentinel">Raw HTML block sentinel</div>',
    '',
    'Final paragraph sentinel for block selection.',
    '',
  ].join('\n');
}
