/**
 * 完整的 Phosphor Icons 图标数据
 * 
 * 自动生成，请勿手动修改
 * 生成命令: node scripts/generate-icons.mjs
 * 
 * 总计: 1512 个图标
 */

import {
  Acorn,
  AddressBook,
  AddressBookTabs,
  AirTrafficControl,
  Airplane,
  AirplaneInFlight,
  AirplaneLanding,
  AirplaneTakeoff,
  AirplaneTaxiing,
  AirplaneTilt,
  Airplay,
  Alarm,
  Alien,
  AlignBottom,
  AlignBottomSimple,
  AlignCenterHorizontal,
  AlignCenterHorizontalSimple,
  AlignCenterVertical,
  AlignCenterVerticalSimple,
  AlignLeft,
  AlignLeftSimple,
  AlignRight,
  AlignRightSimple,
  AlignTop,
  AlignTopSimple,
  AmazonLogo,
  Ambulance,
  Anchor,
  AnchorSimple,
  AndroidLogo,
  Angle,
  AngularLogo,
  Aperture,
  AppStoreLogo,
  AppWindow,
  AppleLogo,
  ApplePodcastsLogo,
  ApproximateEquals,
  Archive,
  Armchair,
  ArrowArcLeft,
  ArrowArcRight,
  ArrowBendDoubleUpLeft,
  ArrowBendDoubleUpRight,
  ArrowBendDownLeft,
  ArrowBendDownRight,
  ArrowBendLeftDown,
  ArrowBendLeftUp,
  ArrowBendRightDown,
  ArrowBendRightUp,
  ArrowBendUpLeft,
  ArrowBendUpRight,
  ArrowCircleDown,
  ArrowCircleDownLeft,
  ArrowCircleDownRight,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowCircleUp,
  ArrowCircleUpLeft,
  ArrowCircleUpRight,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowElbowDownLeft,
  ArrowElbowDownRight,
  ArrowElbowLeft,
  ArrowElbowLeftDown,
  ArrowElbowLeftUp,
  ArrowElbowRight,
  ArrowElbowRightDown,
  ArrowElbowRightUp,
  ArrowElbowUpLeft,
  ArrowElbowUpRight,
  ArrowFatDown,
  ArrowFatLeft,
  ArrowFatLineDown,
  ArrowFatLineLeft,
  ArrowFatLineRight,
  ArrowFatLineUp,
  ArrowFatLinesDown,
  ArrowFatLinesLeft,
  ArrowFatLinesRight,
  ArrowFatLinesUp,
  ArrowFatRight,
  ArrowFatUp,
  ArrowLeft,
  ArrowLineDown,
  ArrowLineDownLeft,
  ArrowLineDownRight,
  ArrowLineLeft,
  ArrowLineRight,
  ArrowLineUp,
  ArrowLineUpLeft,
  ArrowLineUpRight,
  ArrowRight,
  ArrowSquareDown,
  ArrowSquareDownLeft,
  ArrowSquareDownRight,
  ArrowSquareIn,
  ArrowSquareLeft,
  ArrowSquareOut,
  ArrowSquareRight,
  ArrowSquareUp,
  ArrowSquareUpLeft,
  ArrowSquareUpRight,
  ArrowUDownLeft,
  ArrowUDownRight,
  ArrowULeftDown,
  ArrowULeftUp,
  ArrowURightDown,
  ArrowURightUp,
  ArrowUUpLeft,
  ArrowUUpRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsCounterClockwise,
  ArrowsDownUp,
  ArrowsHorizontal,
  ArrowsIn,
  ArrowsInCardinal,
  ArrowsInLineHorizontal,
  ArrowsInLineVertical,
  ArrowsInSimple,
  ArrowsLeftRight,
  ArrowsMerge,
  ArrowsOut,
  ArrowsOutCardinal,
  ArrowsOutLineHorizontal,
  ArrowsOutLineVertical,
  ArrowsOutSimple,
  ArrowsSplit,
  ArrowsVertical,
  Article,
  ArticleMedium,
  ArticleNyTimes,
  Asclepius,
  Asterisk,
  AsteriskSimple,
  At,
  Atom,
  Avocado,
  Axe,
  Baby,
  BabyCarriage,
  Backpack,
  Backspace,
  Bag,
  BagSimple,
  Balloon,
  Bandaids,
  Bank,
  Barbell,
  Barcode,
  Barn,
  Barricade,
  Baseball,
  BaseballCap,
  BaseballHelmet,
  Basket,
  Basketball,
  Bathtub,
  BatteryCharging,
  BatteryChargingVertical,
  BatteryEmpty,
  BatteryFull,
  BatteryHigh,
  BatteryLow,
  BatteryMedium,
  BatteryPlus,
  BatteryPlusVertical,
  BatteryVerticalEmpty,
  BatteryVerticalFull,
  BatteryVerticalHigh,
  BatteryVerticalLow,
  BatteryVerticalMedium,
  BatteryWarning,
  BatteryWarningVertical,
  BeachBall,
  Beanie,
  Bed,
  BeerBottle,
  BeerStein,
  BehanceLogo,
  Bell,
  BellRinging,
  BellSimple,
  BellSimpleRinging,
  BellSimpleSlash,
  BellSimpleZ,
  BellSlash,
  BellZ,
  Belt,
  BezierCurve,
  Bicycle,
  Binary,
  Binoculars,
  Biohazard,
  Bird,
  Blueprint,
  Bluetooth,
  BluetoothConnected,
  BluetoothSlash,
  BluetoothX,
  Boat,
  Bomb,
  Bone,
  Book,
  BookBookmark,
  BookOpen,
  BookOpenText,
  BookOpenUser,
  Bookmark,
  BookmarkSimple,
  Bookmarks,
  BookmarksSimple,
  Books,
  Boot,
  Boules,
  BoundingBox,
  BowlFood,
  BowlSteam,
  BowlingBall,
  BoxArrowDown,
  BoxArrowUp,
  BoxingGlove,
  BracketsAngle,
  BracketsCurly,
  BracketsRound,
  BracketsSquare,
  Brain,
  Brandy,
  Bread,
  Bridge,
  Briefcase,
  BriefcaseMetal,
  Broadcast,
  Broom,
  Browser,
  Browsers,
  Bug,
  BugBeetle,
  BugDroid,
  Building,
  BuildingApartment,
  BuildingOffice,
  Buildings,
  Bulldozer,
  Bus,
  Butterfly,
  CableCar,
  Cactus,
  Cake,
  Calculator,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  CalendarDot,
  CalendarDots,
  CalendarHeart,
  CalendarMinus,
  CalendarPlus,
  CalendarSlash,
  CalendarStar,
  CalendarX,
  CallBell,
  Camera,
  CameraPlus,
  CameraRotate,
  CameraSlash,
  Campfire,
  Car,
  CarBattery,
  CarProfile,
  CarSimple,
  Cardholder,
  Cards,
  CardsThree,
  CaretCircleDoubleDown,
  CaretCircleDoubleLeft,
  CaretCircleDoubleRight,
  CaretCircleDoubleUp,
  CaretCircleDown,
  CaretCircleLeft,
  CaretCircleRight,
  CaretCircleUp,
  CaretCircleUpDown,
  CaretDoubleDown,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDoubleUp,
  CaretDown,
  CaretLeft,
  CaretLineDown,
  CaretLineLeft,
  CaretLineRight,
  CaretLineUp,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Carrot,
  CashRegister,
  CassetteTape,
  CastleTurret,
  Cat,
  CellSignalFull,
  CellSignalHigh,
  CellSignalLow,
  CellSignalMedium,
  CellSignalNone,
  CellSignalSlash,
  CellSignalX,
  CellTower,
  Certificate,
  Chair,
  Chalkboard,
  ChalkboardSimple,
  ChalkboardTeacher,
  Champagne,
  ChargingStation,
  ChartBar,
  ChartBarHorizontal,
  ChartDonut,
  ChartLine,
  ChartLineDown,
  ChartLineUp,
  ChartPie,
  ChartPieSlice,
  ChartPolar,
  ChartScatter,
  Chat,
  ChatCentered,
  ChatCenteredDots,
  ChatCenteredSlash,
  ChatCenteredText,
  ChatCircle,
  ChatCircleDots,
  ChatCircleSlash,
  ChatCircleText,
  ChatDots,
  ChatSlash,
  ChatTeardrop,
  ChatTeardropDots,
  ChatTeardropSlash,
  ChatTeardropText,
  ChatText,
  Chats,
  ChatsCircle,
  ChatsTeardrop,
  Check,
  CheckCircle,
  CheckFat,
  CheckSquare,
  CheckSquareOffset,
  Checkerboard,
  Checks,
  Cheers,
  Cheese,
  ChefHat,
  Cherries,
  Church,
  Cigarette,
  CigaretteSlash,
  Circle,
  CircleDashed,
  CircleHalf,
  CircleHalfTilt,
  CircleNotch,
  CirclesFour,
  CirclesThree,
  CirclesThreePlus,
  Circuitry,
  City,
  Clipboard,
  ClipboardText,
  Clock,
  ClockAfternoon,
  ClockClockwise,
  ClockCountdown,
  ClockCounterClockwise,
  ClockUser,
  ClosedCaptioning,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  CloudCheck,
  CloudFog,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSlash,
  CloudSnow,
  CloudSun,
  CloudWarning,
  CloudX,
  Clover,
  Club,
  CoatHanger,
  CodaLogo,
  Code,
  CodeBlock,
  CodeSimple,
  CodepenLogo,
  CodesandboxLogo,
  Coffee,
  CoffeeBean,
  Coin,
  CoinVertical,
  Coins,
  Columns,
  ColumnsPlusLeft,
  ColumnsPlusRight,
  Command,
  Compass,
  CompassRose,
  CompassTool,
  ComputerTower,
  Confetti,
  ContactlessPayment,
  Control,
  Cookie,
  CookingPot,
  Copy,
  CopySimple,
  Copyleft,
  Copyright,
  CornersIn,
  CornersOut,
  Couch,
  CourtBasketball,
  Cow,
  CowboyHat,
  Cpu,
  Crane,
  CraneTower,
  CreditCard,
  Cricket,
  Crop,
  Cross,
  Crosshair,
  CrosshairSimple,
  Crown,
  CrownCross,
  CrownSimple,
  Cube,
  CubeFocus,
  CubeTransparent,
  CurrencyBtc,
  CurrencyCircleDollar,
  CurrencyCny,
  CurrencyDollar,
  CurrencyDollarSimple,
  CurrencyEth,
  CurrencyEur,
  CurrencyGbp,
  CurrencyInr,
  CurrencyJpy,
  CurrencyKrw,
  CurrencyKzt,
  CurrencyNgn,
  CurrencyRub,
  Cursor,
  CursorClick,
  CursorText,
  Cylinder,
  Database,
  Desk,
  Desktop,
  DesktopTower,
  Detective,
  DevToLogo,
  DeviceMobile,
  DeviceMobileCamera,
  DeviceMobileSlash,
  DeviceMobileSpeaker,
  DeviceRotate,
  DeviceTablet,
  DeviceTabletCamera,
  DeviceTabletSpeaker,
  Devices,
  Diamond,
  DiamondsFour,
  DiceFive,
  DiceFour,
  DiceOne,
  DiceSix,
  DiceThree,
  DiceTwo,
  Disc,
  DiscoBall,
  DiscordLogo,
  Divide,
  Dna,
  Dog,
  Door,
  DoorOpen,
  Dot,
  DotOutline,
  DotsNine,
  DotsSix,
  DotsSixVertical,
  DotsThree,
  DotsThreeCircle,
  DotsThreeCircleVertical,
  DotsThreeOutline,
  DotsThreeOutlineVertical,
  DotsThreeVertical,
  Download,
  DownloadSimple,
  Dress,
  Dresser,
  DribbbleLogo,
  Drone,
  Drop,
  DropHalf,
  DropHalfBottom,
  DropSimple,
  DropSlash,
  DropboxLogo,
  Ear,
  EarSlash,
  Egg,
  EggCrack,
  Eject,
  EjectSimple,
  Elevator,
  Empty,
  Engine,
  Envelope,
  EnvelopeOpen,
  EnvelopeSimple,
  EnvelopeSimpleOpen,
  Equalizer,
  Equals,
  Eraser,
  EscalatorDown,
  EscalatorUp,
  Exam,
  ExclamationMark,
  Exclude,
  ExcludeSquare,
  Export,
  Eye,
  EyeClosed,
  EyeSlash,
  Eyedropper,
  EyedropperSample,
  Eyeglasses,
  Eyes,
  FaceMask,
  FacebookLogo,
  Factory,
  Faders,
  FadersHorizontal,
  FalloutShelter,
  Fan,
  Farm,
  FastForward,
  FastForwardCircle,
  Feather,
  FediverseLogo,
  FigmaLogo,
  File,
  FileArchive,
  FileArrowDown,
  FileArrowUp,
  FileAudio,
  FileC,
  FileCSharp,
  FileCloud,
  FileCode,
  FileCpp,
  FileCss,
  FileCsv,
  FileDashed,
  FileDoc,
  FileHtml,
  FileImage,
  FileIni,
  FileJpg,
  FileJs,
  FileJsx,
  FileLock,
  FileMagnifyingGlass,
  FileMd,
  FileMinus,
  FilePdf,
  FilePlus,
  FilePng,
  FilePpt,
  FilePy,
  FileRs,
  FileSql,
  FileSvg,
  FileText,
  FileTs,
  FileTsx,
  FileTxt,
  FileVideo,
  FileVue,
  FileX,
  FileXls,
  FileZip,
  Files,
  FilmReel,
  FilmScript,
  FilmSlate,
  FilmStrip,
  Fingerprint,
  FingerprintSimple,
  FinnTheHuman,
  Fire,
  FireExtinguisher,
  FireSimple,
  FireTruck,
  FirstAid,
  FirstAidKit,
  Fish,
  FishSimple,
  Flag,
  FlagBanner,
  FlagBannerFold,
  FlagCheckered,
  FlagPennant,
  Flame,
  Flashlight,
  Flask,
  FlipHorizontal,
  FlipVertical,
  FloppyDisk,
  FloppyDiskBack,
  FlowArrow,
  Flower,
  FlowerLotus,
  FlowerTulip,
  FlyingSaucer,
  Folder,
  FolderDashed,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FolderSimple,
  FolderSimpleDashed,
  FolderSimpleLock,
  FolderSimpleMinus,
  FolderSimplePlus,
  FolderSimpleStar,
  FolderSimpleUser,
  FolderStar,
  FolderUser,
  Folders,
  Football,
  FootballHelmet,
  Footprints,
  ForkKnife,
  FourK,
  FrameCorners,
  FramerLogo,
  Function,
  Funnel,
  FunnelSimple,
  FunnelSimpleX,
  FunnelX,
  GameController,
  Garage,
  GasCan,
  GasPump,
  Gauge,
  Gavel,
  Gear,
  GearFine,
  GearSix,
  GenderFemale,
  GenderIntersex,
  GenderMale,
  GenderNeuter,
  GenderNonbinary,
  GenderTransgender,
  Ghost,
  Gif,
  Gift,
  GitBranch,
  GitCommit,
  GitDiff,
  GitFork,
  GitMerge,
  GitPullRequest,
  GithubLogo,
  GitlabLogo,
  GitlabLogoSimple,
  Globe,
  GlobeHemisphereEast,
  GlobeHemisphereWest,
  GlobeSimple,
  GlobeSimpleX,
  GlobeStand,
  GlobeX,
  Goggles,
  Golf,
  GoodreadsLogo,
  GoogleCardboardLogo,
  GoogleChromeLogo,
  GoogleDriveLogo,
  GoogleLogo,
  GooglePhotosLogo,
  GooglePlayLogo,
  GooglePodcastsLogo,
  Gps,
  GpsFix,
  GpsSlash,
  Gradient,
  GraduationCap,
  Grains,
  GrainsSlash,
  Graph,
  GraphicsCard,
  GreaterThan,
  GreaterThanOrEqual,
  GridFour,
  GridNine,
  Guitar,
  HairDryer,
  Hamburger,
  Hammer,
  Hand,
  HandArrowDown,
  HandArrowUp,
  HandCoins,
  HandDeposit,
  HandEye,
  HandFist,
  HandGrabbing,
  HandHeart,
  HandPalm,
  HandPeace,
  HandPointing,
  HandSoap,
  HandSwipeLeft,
  HandSwipeRight,
  HandTap,
  HandWaving,
  HandWithdraw,
  Handbag,
  HandbagSimple,
  HandsClapping,
  HandsPraying,
  Handshake,
  HardDrive,
  HardDrives,
  HardHat,
  Hash,
  HashStraight,
  HeadCircuit,
  Headlights,
  Headphones,
  Headset,
  Heart,
  HeartBreak,
  HeartHalf,
  HeartStraight,
  HeartStraightBreak,
  Heartbeat,
  Hexagon,
  HighDefinition,
  HighHeel,
  Highlighter,
  HighlighterCircle,
  Hockey,
  Hoodie,
  Horse,
  Hospital,
  Hourglass,
  HourglassHigh,
  HourglassLow,
  HourglassMedium,
  HourglassSimple,
  HourglassSimpleHigh,
  HourglassSimpleLow,
  HourglassSimpleMedium,
  House,
  HouseLine,
  HouseSimple,
  Hurricane,
  IceCream,
  IdentificationBadge,
  IdentificationCard,
  Image,
  ImageBroken,
  ImageSquare,
  Images,
  ImagesSquare,
  Infinity,
  Info,
  InstagramLogo,
  Intersect,
  IntersectSquare,
  IntersectThree,
  Intersection,
  Invoice,
  Island,
  Jar,
  JarLabel,
  Jeep,
  Joystick,
  Kanban,
  Key,
  KeyReturn,
  Keyboard,
  Keyhole,
  Knife,
  Ladder,
  LadderSimple,
  Lamp,
  LampPendant,
  Laptop,
  Lasso,
  LastfmLogo,
  Layout,
  Leaf,
  Lectern,
  Lego,
  LegoSmiley,
  LessThan,
  LessThanOrEqual,
  LetterCircleH,
  LetterCircleP,
  LetterCircleV,
  Lifebuoy,
  Lightbulb,
  LightbulbFilament,
  Lighthouse,
  Lightning,
  LightningA,
  LightningSlash,
  LineSegment,
  LineSegments,
  LineVertical,
  Link,
  LinkBreak,
  LinkSimple,
  LinkSimpleBreak,
  LinkSimpleHorizontal,
  LinkSimpleHorizontalBreak,
  LinkedinLogo,
  LinktreeLogo,
  LinuxLogo,
  List,
  ListBullets,
  ListChecks,
  ListDashes,
  ListHeart,
  ListMagnifyingGlass,
  ListNumbers,
  ListPlus,
  ListStar,
  Lock,
  LockKey,
  LockKeyOpen,
  LockLaminated,
  LockLaminatedOpen,
  LockOpen,
  LockSimple,
  LockSimpleOpen,
  Lockers,
  Log,
  MagicWand,
  Magnet,
  MagnetStraight,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  Mailbox,
  MapPin,
  MapPinArea,
  MapPinLine,
  MapPinPlus,
  MapPinSimple,
  MapPinSimpleArea,
  MapPinSimpleLine,
  MapTrifold,
  MarkdownLogo,
  MarkerCircle,
  Martini,
  MaskHappy,
  MaskSad,
  MastodonLogo,
  MathOperations,
  MatrixLogo,
  Medal,
  MedalMilitary,
  MediumLogo,
  Megaphone,
  MegaphoneSimple,
  MemberOf,
  Memory,
  MessengerLogo,
  MetaLogo,
  Meteor,
  Metronome,
  Microphone,
  MicrophoneSlash,
  MicrophoneStage,
  Microscope,
  MicrosoftExcelLogo,
  MicrosoftOutlookLogo,
  MicrosoftPowerpointLogo,
  MicrosoftTeamsLogo,
  MicrosoftWordLogo,
  Minus,
  MinusCircle,
  MinusSquare,
  Money,
  MoneyWavy,
  Monitor,
  MonitorArrowUp,
  MonitorPlay,
  Moon,
  MoonStars,
  Moped,
  MopedFront,
  Mosque,
  Motorcycle,
  Mountains,
  Mouse,
  MouseLeftClick,
  MouseMiddleClick,
  MouseRightClick,
  MouseScroll,
  MouseSimple,
  MusicNote,
  MusicNoteSimple,
  MusicNotes,
  MusicNotesMinus,
  MusicNotesPlus,
  MusicNotesSimple,
  NavigationArrow,
  Needle,
  Network,
  NetworkSlash,
  NetworkX,
  Newspaper,
  NewspaperClipping,
  NotEquals,
  NotMemberOf,
  NotSubsetOf,
  NotSupersetOf,
  Notches,
  Note,
  NoteBlank,
  NotePencil,
  Notebook,
  Notepad,
  Notification,
  NotionLogo,
  NuclearPlant,
  NumberCircleEight,
  NumberCircleFive,
  NumberCircleFour,
  NumberCircleNine,
  NumberCircleOne,
  NumberCircleSeven,
  NumberCircleSix,
  NumberCircleThree,
  NumberCircleTwo,
  NumberCircleZero,
  NumberEight,
  NumberFive,
  NumberFour,
  NumberNine,
  NumberOne,
  NumberSeven,
  NumberSix,
  NumberSquareEight,
  NumberSquareFive,
  NumberSquareFour,
  NumberSquareNine,
  NumberSquareOne,
  NumberSquareSeven,
  NumberSquareSix,
  NumberSquareThree,
  NumberSquareTwo,
  NumberSquareZero,
  NumberThree,
  NumberTwo,
  NumberZero,
  Numpad,
  Nut,
  NyTimesLogo,
  Octagon,
  OfficeChair,
  Onigiri,
  OpenAiLogo,
  Option,
  Orange,
  OrangeSlice,
  Oven,
  Package,
  PaintBrush,
  PaintBrushBroad,
  PaintBrushHousehold,
  PaintBucket,
  PaintRoller,
  Palette,
  Panorama,
  Pants,
  PaperPlane,
  PaperPlaneRight,
  PaperPlaneTilt,
  Paperclip,
  PaperclipHorizontal,
  Parachute,
  Paragraph,
  Parallelogram,
  Park,
  Password,
  Path,
  PatreonLogo,
  Pause,
  PauseCircle,
  PawPrint,
  PaypalLogo,
  Peace,
  Pen,
  PenNib,
  PenNibStraight,
  Pencil,
  PencilCircle,
  PencilLine,
  PencilRuler,
  PencilSimple,
  PencilSimpleLine,
  PencilSimpleSlash,
  PencilSlash,
  Pentagon,
  Pentagram,
  Pepper,
  Percent,
  Person,
  PersonArmsSpread,
  PersonSimple,
  PersonSimpleBike,
  PersonSimpleCircle,
  PersonSimpleHike,
  PersonSimpleRun,
  PersonSimpleSki,
  PersonSimpleSnowboard,
  PersonSimpleSwim,
  PersonSimpleTaiChi,
  PersonSimpleThrow,
  PersonSimpleWalk,
  Perspective,
  Phone,
  PhoneCall,
  PhoneDisconnect,
  PhoneIncoming,
  PhoneList,
  PhoneOutgoing,
  PhonePause,
  PhonePlus,
  PhoneSlash,
  PhoneTransfer,
  PhoneX,
  PhosphorLogo,
  Pi,
  PianoKeys,
  PicnicTable,
  PictureInPicture,
  PiggyBank,
  Pill,
  PingPong,
  PintGlass,
  PinterestLogo,
  Pinwheel,
  Pipe,
  PipeWrench,
  PixLogo,
  Pizza,
  Placeholder,
  Planet,
  Plant,
  Play,
  PlayCircle,
  PlayPause,
  Playlist,
  Plug,
  PlugCharging,
  Plugs,
  PlugsConnected,
  Plus,
  PlusCircle,
  PlusMinus,
  PlusSquare,
  PokerChip,
  PoliceCar,
  Polygon,
  Popcorn,
  Popsicle,
  PottedPlant,
  Power,
  Prescription,
  Presentation,
  PresentationChart,
  Printer,
  Prohibit,
  ProhibitInset,
  ProjectorScreen,
  ProjectorScreenChart,
  Pulse,
  PushPin,
  PushPinSimple,
  PushPinSimpleSlash,
  PushPinSlash,
  PuzzlePiece,
  QrCode,
  Question,
  QuestionMark,
  Queue,
  Quotes,
  Rabbit,
  Racquet,
  Radical,
  Radio,
  RadioButton,
  Radioactive,
  Rainbow,
  RainbowCloud,
  Ranking,
  ReadCvLogo,
  Receipt,
  ReceiptX,
  Record,
  Rectangle,
  RectangleDashed,
  Recycle,
  RedditLogo,
  Repeat,
  RepeatOnce,
  ReplitLogo,
  Resize,
  Rewind,
  RewindCircle,
  RoadHorizon,
  Robot,
  Rocket,
  RocketLaunch,
  Rows,
  RowsPlusBottom,
  RowsPlusTop,
  Rss,
  RssSimple,
  Rug,
  Ruler,
  Sailboat,
  Scales,
  Scan,
  ScanSmiley,
  Scissors,
  Scooter,
  Screencast,
  Screwdriver,
  Scribble,
  ScribbleLoop,
  Scroll,
  Seal,
  SealCheck,
  SealPercent,
  SealQuestion,
  SealWarning,
  Seat,
  Seatbelt,
  SecurityCamera,
  Selection,
  SelectionAll,
  SelectionBackground,
  SelectionForeground,
  SelectionInverse,
  SelectionPlus,
  SelectionSlash,
  Shapes,
  Share,
  ShareFat,
  ShareNetwork,
  Shield,
  ShieldCheck,
  ShieldCheckered,
  ShieldChevron,
  ShieldPlus,
  ShieldSlash,
  ShieldStar,
  ShieldWarning,
  ShippingContainer,
  ShirtFolded,
  ShootingStar,
  ShoppingBag,
  ShoppingBagOpen,
  ShoppingCart,
  ShoppingCartSimple,
  Shovel,
  Shower,
  Shrimp,
  Shuffle,
  ShuffleAngular,
  ShuffleSimple,
  Sidebar,
  SidebarSimple,
  Sigma,
  SignIn,
  SignOut,
  Signature,
  Signpost,
  SimCard,
  Siren,
  SketchLogo,
  SkipBack,
  SkipBackCircle,
  SkipForward,
  SkipForwardCircle,
  Skull,
  SkypeLogo,
  SlackLogo,
  Sliders,
  SlidersHorizontal,
  Slideshow,
  Smiley,
  SmileyAngry,
  SmileyBlank,
  SmileyMeh,
  SmileyMelting,
  SmileyNervous,
  SmileySad,
  SmileySticker,
  SmileyWink,
  SmileyXEyes,
  SnapchatLogo,
  Sneaker,
  SneakerMove,
  Snowflake,
  SoccerBall,
  Sock,
  SolarPanel,
  SolarRoof,
  SortAscending,
  SortDescending,
  SoundcloudLogo,
  Spade,
  Sparkle,
  SpeakerHifi,
  SpeakerHigh,
  SpeakerLow,
  SpeakerNone,
  SpeakerSimpleHigh,
  SpeakerSimpleLow,
  SpeakerSimpleNone,
  SpeakerSimpleSlash,
  SpeakerSimpleX,
  SpeakerSlash,
  SpeakerX,
  Speedometer,
  Sphere,
  Spinner,
  SpinnerBall,
  SpinnerGap,
  Spiral,
  SplitHorizontal,
  SplitVertical,
  SpotifyLogo,
  SprayBottle,
  Square,
  SquareHalf,
  SquareHalfBottom,
  SquareLogo,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquaresFour,
  Stack,
  StackMinus,
  StackOverflowLogo,
  StackPlus,
  StackSimple,
  Stairs,
  Stamp,
  StandardDefinition,
  Star,
  StarAndCrescent,
  StarFour,
  StarHalf,
  StarOfDavid,
  SteamLogo,
  SteeringWheel,
  Steps,
  Stethoscope,
  Sticker,
  Stool,
  Stop,
  StopCircle,
  Storefront,
  Strategy,
  StripeLogo,
  Student,
  SubsetOf,
  SubsetProperOf,
  Subtitles,
  SubtitlesSlash,
  Subtract,
  SubtractSquare,
  Subway,
  Suitcase,
  SuitcaseRolling,
  SuitcaseSimple,
  Sun,
  SunDim,
  SunHorizon,
  Sunglasses,
  SupersetOf,
  SupersetProperOf,
  Swap,
  Swatches,
  SwimmingPool,
  Sword,
  Synagogue,
  Syringe,
  TShirt,
  Table,
  Tabs,
  Tag,
  TagChevron,
  TagSimple,
  Target,
  Taxi,
  TeaBag,
  TelegramLogo,
  Television,
  TelevisionSimple,
  TennisBall,
  Tent,
  Terminal,
  TerminalWindow,
  TestTube,
  TextAUnderline,
  TextAa,
  TextAlignCenter,
  TextAlignJustify,
  TextAlignLeft,
  TextAlignRight,
  TextB,
  TextColumns,
  TextH,
  TextHFive,
  TextHFour,
  TextHOne,
  TextHSix,
  TextHThree,
  TextHTwo,
  TextIndent,
  TextItalic,
  TextOutdent,
  TextStrikethrough,
  TextSubscript,
  TextSuperscript,
  TextT,
  TextTSlash,
  TextUnderline,
  Textbox,
  Thermometer,
  ThermometerCold,
  ThermometerHot,
  ThermometerSimple,
  ThreadsLogo,
  ThreeD,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TidalLogo,
  TiktokLogo,
  Tilde,
  Timer,
  TipJar,
  Tipi,
  Tire,
  ToggleLeft,
  ToggleRight,
  Toilet,
  ToiletPaper,
  Toolbox,
  Tooth,
  Tornado,
  Tote,
  ToteSimple,
  Towel,
  Tractor,
  Trademark,
  TrademarkRegistered,
  TrafficCone,
  TrafficSign,
  TrafficSignal,
  Train,
  TrainRegional,
  TrainSimple,
  Tram,
  Translate,
  Trash,
  TrashSimple,
  Tray,
  TrayArrowDown,
  TrayArrowUp,
  TreasureChest,
  Tree,
  TreeEvergreen,
  TreePalm,
  TreeStructure,
  TreeView,
  TrendDown,
  TrendUp,
  Triangle,
  TriangleDashed,
  Trolley,
  TrolleySuitcase,
  Trophy,
  Truck,
  TruckTrailer,
  TumblrLogo,
  TwitchLogo,
  TwitterLogo,
  Umbrella,
  UmbrellaSimple,
  Union,
  Unite,
  UniteSquare,
  Upload,
  UploadSimple,
  Usb,
  User,
  UserCheck,
  UserCircle,
  UserCircleCheck,
  UserCircleDashed,
  UserCircleGear,
  UserCircleMinus,
  UserCirclePlus,
  UserFocus,
  UserGear,
  UserList,
  UserMinus,
  UserPlus,
  UserRectangle,
  UserSound,
  UserSquare,
  UserSwitch,
  Users,
  UsersFour,
  UsersThree,
  Van,
  Vault,
  VectorThree,
  VectorTwo,
  Vibrate,
  Video,
  VideoCamera,
  VideoCameraSlash,
  VideoConference,
  Vignette,
  VinylRecord,
  VirtualReality,
  Virus,
  Visor,
  Voicemail,
  Volleyball,
  Wall,
  Wallet,
  Warehouse,
  Warning,
  WarningCircle,
  WarningDiamond,
  WarningOctagon,
  WashingMachine,
  Watch,
  WaveSawtooth,
  WaveSine,
  WaveSquare,
  WaveTriangle,
  Waveform,
  WaveformSlash,
  Waves,
  Webcam,
  WebcamSlash,
  WebhooksLogo,
  WechatLogo,
  WhatsappLogo,
  Wheelchair,
  WheelchairMotion,
  WifiHigh,
  WifiLow,
  WifiMedium,
  WifiNone,
  WifiSlash,
  WifiX,
  Wind,
  Windmill,
  WindowsLogo,
  Wine,
  Wrench,
  X,
  XCircle,
  XLogo,
  XSquare,
  Yarn,
  YinYang,
  YoutubeLogo,
  type Icon as PhosphorIcon,
} from '@phosphor-icons/react';

export interface IconDefinition {
  name: string;
  icon: PhosphorIcon;
}

export interface IconCategory {
  name: string;
  icons: IconDefinition[];
}

export const ICON_CATEGORIES_FULL: IconCategory[] = [
  {
    name: 'Shopping & Food',
    icons: [
      { name: 'avocado', icon: Avocado },
      { name: 'axe', icon: Axe },
      { name: 'baby-carriage', icon: BabyCarriage },
      { name: 'backpack', icon: Backpack },
      { name: 'bag', icon: Bag },
      { name: 'bag-simple', icon: BagSimple },
      { name: 'balloon', icon: Balloon },
      { name: 'barcode', icon: Barcode },
      { name: 'barn', icon: Barn },
      { name: 'baseball-cap', icon: BaseballCap },
      { name: 'basket', icon: Basket },
      { name: 'beanie', icon: Beanie },
      { name: 'beer-bottle', icon: BeerBottle },
      { name: 'beer-stein', icon: BeerStein },
      { name: 'belt', icon: Belt },
      { name: 'blueprint', icon: Blueprint },
      { name: 'boot', icon: Boot },
      { name: 'bowl-food', icon: BowlFood },
      { name: 'bowl-steam', icon: BowlSteam },
      { name: 'brandy', icon: Brandy },
      { name: 'bread', icon: Bread },
      { name: 'building', icon: Building },
      { name: 'building-apartment', icon: BuildingApartment },
      { name: 'building-office', icon: BuildingOffice },
      { name: 'buildings', icon: Buildings },
      { name: 'bulldozer', icon: Bulldozer },
      { name: 'car-battery', icon: CarBattery },
      { name: 'cardholder', icon: Cardholder },
      { name: 'carrot', icon: Carrot },
      { name: 'cash-register', icon: CashRegister },
      { name: 'cheers', icon: Cheers },
      { name: 'cheese', icon: Cheese },
      { name: 'chef-hat', icon: ChefHat },
      { name: 'cigarette', icon: Cigarette },
      { name: 'cigarette-slash', icon: CigaretteSlash },
      { name: 'coat-hanger', icon: CoatHanger },
      { name: 'coffee', icon: Coffee },
      { name: 'coffee-bean', icon: CoffeeBean },
      { name: 'coin', icon: Coin },
      { name: 'coin-vertical', icon: CoinVertical },
      { name: 'coins', icon: Coins },
      { name: 'contactless-payment', icon: ContactlessPayment },
      { name: 'copyleft', icon: Copyleft },
      { name: 'copyright', icon: Copyright },
      { name: 'cow', icon: Cow },
      { name: 'cowboy-hat', icon: CowboyHat },
      { name: 'crane', icon: Crane },
      { name: 'crane-tower', icon: CraneTower },
      { name: 'credit-card', icon: CreditCard },
      { name: 'currency-btc', icon: CurrencyBtc },
      { name: 'currency-circle-dollar', icon: CurrencyCircleDollar },
      { name: 'currency-cny', icon: CurrencyCny },
      { name: 'currency-dollar', icon: CurrencyDollar },
      { name: 'currency-dollar-simple', icon: CurrencyDollarSimple },
      { name: 'currency-eth', icon: CurrencyEth },
      { name: 'currency-eur', icon: CurrencyEur },
      { name: 'currency-gbp', icon: CurrencyGbp },
      { name: 'currency-inr', icon: CurrencyInr },
      { name: 'currency-jpy', icon: CurrencyJpy },
      { name: 'currency-krw', icon: CurrencyKrw },
      { name: 'currency-kzt', icon: CurrencyKzt },
      { name: 'currency-ngn', icon: CurrencyNgn },
      { name: 'currency-rub', icon: CurrencyRub },
      { name: 'desk', icon: Desk },
      { name: 'dress', icon: Dress },
      { name: 'dresser', icon: Dresser },
      { name: 'egg', icon: Egg },
      { name: 'egg-crack', icon: EggCrack },
      { name: 'factory', icon: Factory },
      { name: 'fan', icon: Fan },
      { name: 'farm', icon: Farm },
      { name: 'fork-knife', icon: ForkKnife },
      { name: 'garage', icon: Garage },
      { name: 'gavel', icon: Gavel },
      { name: 'gift', icon: Gift },
      { name: 'grains', icon: Grains },
      { name: 'grains-slash', icon: GrainsSlash },
      { name: 'hair-dryer', icon: HairDryer },
      { name: 'hamburger', icon: Hamburger },
      { name: 'handbag', icon: Handbag },
      { name: 'handbag-simple', icon: HandbagSimple },
      { name: 'hard-hat', icon: HardHat },
      { name: 'high-heel', icon: HighHeel },
      { name: 'hoodie', icon: Hoodie },
      { name: 'ice-cream', icon: IceCream },
      { name: 'invoice', icon: Invoice },
      { name: 'jar', icon: Jar },
      { name: 'jar-label', icon: JarLabel },
      { name: 'knife', icon: Knife },
      { name: 'lamp-pendant', icon: LampPendant },
      { name: 'martini', icon: Martini },
      { name: 'money', icon: Money },
      { name: 'nuclear-plant', icon: NuclearPlant },
      { name: 'onigiri', icon: Onigiri },
      { name: 'orange', icon: Orange },
      { name: 'oven', icon: Oven },
      { name: 'pants', icon: Pants },
      { name: 'pepper', icon: Pepper },
      { name: 'pint-glass', icon: PintGlass },
      { name: 'pipe', icon: Pipe },
      { name: 'pipe-wrench', icon: PipeWrench },
      { name: 'pix-logo', icon: PixLogo },
      { name: 'pizza', icon: Pizza },
      { name: 'plant', icon: Plant },
      { name: 'popsicle', icon: Popsicle },
      { name: 'potted-plant', icon: PottedPlant },
      { name: 'receipt', icon: Receipt },
      { name: 'receipt-x', icon: ReceiptX },
      { name: 'scales', icon: Scales },
      { name: 'screwdriver', icon: Screwdriver },
      { name: 'seatbelt', icon: Seatbelt },
      { name: 'shirt-folded', icon: ShirtFolded },
      { name: 'shopping-bag', icon: ShoppingBag },
      { name: 'shopping-bag-open', icon: ShoppingBagOpen },
      { name: 'shopping-cart', icon: ShoppingCart },
      { name: 'shopping-cart-simple', icon: ShoppingCartSimple },
      { name: 'shovel', icon: Shovel },
      { name: 'shrimp', icon: Shrimp },
      { name: 'sneaker', icon: Sneaker },
      { name: 'sneaker-move', icon: SneakerMove },
      { name: 'sock', icon: Sock },
      { name: 'solar-panel', icon: SolarPanel },
      { name: 'solar-roof', icon: SolarRoof },
      { name: 'stairs', icon: Stairs },
      { name: 'steps', icon: Steps },
      { name: 'storefront', icon: Storefront },
      { name: 'tag', icon: Tag },
      { name: 'tag-chevron', icon: TagChevron },
      { name: 'tag-simple', icon: TagSimple },
      { name: 'tea-bag', icon: TeaBag },
      { name: 'ticket', icon: Ticket },
      { name: 'tip-jar', icon: TipJar },
      { name: 'tire', icon: Tire },
      { name: 'tote', icon: Tote },
      { name: 'tote-simple', icon: ToteSimple },
      { name: 'towel', icon: Towel },
      { name: 'tractor', icon: Tractor },
      { name: 'trademark', icon: Trademark },
      { name: 'trademark-registered', icon: TrademarkRegistered },
      { name: 'truck', icon: Truck },
      { name: 'truck-trailer', icon: TruckTrailer },
      { name: 'wallet', icon: Wallet },
      { name: 'warehouse', icon: Warehouse },
      { name: 'washing-machine', icon: WashingMachine },
      { name: 'windmill', icon: Windmill },
      { name: 'wine', icon: Wine },
    ],
  },
  {
    name: 'Health & Sports',
    icons: [
      { name: 'ambulance', icon: Ambulance },
      { name: 'asclepius', icon: Asclepius },
      { name: 'bandaids', icon: Bandaids },
      { name: 'barbell', icon: Barbell },
      { name: 'bed', icon: Bed },
      { name: 'bicycle', icon: Bicycle },
      { name: 'biohazard', icon: Biohazard },
      { name: 'brain', icon: Brain },
      { name: 'dna', icon: Dna },
      { name: 'eyeglasses', icon: Eyeglasses },
      { name: 'face-mask', icon: FaceMask },
      { name: 'fallout-shelter', icon: FalloutShelter },
      { name: 'fire-truck', icon: FireTruck },
      { name: 'first-aid', icon: FirstAid },
      { name: 'first-aid-kit', icon: FirstAidKit },
      { name: 'footprints', icon: Footprints },
      { name: 'goggles', icon: Goggles },
      { name: 'hand-soap', icon: HandSoap },
      { name: 'heartbeat', icon: Heartbeat },
      { name: 'lifebuoy', icon: Lifebuoy },
      { name: 'person-arms-spread', icon: PersonArmsSpread },
      { name: 'person-simple-tai-chi', icon: PersonSimpleTaiChi },
      { name: 'pill', icon: Pill },
      { name: 'prescription', icon: Prescription },
      { name: 'pulse', icon: Pulse },
      { name: 'stethoscope', icon: Stethoscope },
      { name: 'sunglasses', icon: Sunglasses },
      { name: 'swimming-pool', icon: SwimmingPool },
      { name: 'syringe', icon: Syringe },
      { name: 'tent', icon: Tent },
      { name: 'toilet', icon: Toilet },
      { name: 'toilet-paper', icon: ToiletPaper },
      { name: 'tooth', icon: Tooth },
      { name: 'virus', icon: Virus },
      { name: 'wheelchair', icon: Wheelchair },
      { name: 'wheelchair-motion', icon: WheelchairMotion },
    ],
  },
  {
    name: 'Work & Office',
    icons: [
      { name: 'archive', icon: Archive },
      { name: 'book', icon: Book },
      { name: 'book-bookmark', icon: BookBookmark },
      { name: 'book-open', icon: BookOpen },
      { name: 'book-open-text', icon: BookOpenText },
      { name: 'book-open-user', icon: BookOpenUser },
      { name: 'bookmark', icon: Bookmark },
      { name: 'bookmark-simple', icon: BookmarkSimple },
      { name: 'bookmarks', icon: Bookmarks },
      { name: 'bookmarks-simple', icon: BookmarksSimple },
      { name: 'books', icon: Books },
      { name: 'box-arrow-down', icon: BoxArrowDown },
      { name: 'box-arrow-up', icon: BoxArrowUp },
      { name: 'briefcase', icon: Briefcase },
      { name: 'briefcase-metal', icon: BriefcaseMetal },
      { name: 'calendar', icon: Calendar },
      { name: 'calendar-blank', icon: CalendarBlank },
      { name: 'calendar-check', icon: CalendarCheck },
      { name: 'calendar-dot', icon: CalendarDot },
      { name: 'calendar-dots', icon: CalendarDots },
      { name: 'calendar-heart', icon: CalendarHeart },
      { name: 'calendar-minus', icon: CalendarMinus },
      { name: 'calendar-plus', icon: CalendarPlus },
      { name: 'calendar-slash', icon: CalendarSlash },
      { name: 'calendar-star', icon: CalendarStar },
      { name: 'calendar-x', icon: CalendarX },
      { name: 'clipboard', icon: Clipboard },
      { name: 'clipboard-text', icon: ClipboardText },
      { name: 'file', icon: File },
      { name: 'file-arrow-down', icon: FileArrowDown },
      { name: 'file-arrow-up', icon: FileArrowUp },
      { name: 'file-audio', icon: FileAudio },
      { name: 'file-c', icon: FileC },
      { name: 'file-c-sharp', icon: FileCSharp },
      { name: 'file-cloud', icon: FileCloud },
      { name: 'file-code', icon: FileCode },
      { name: 'file-cpp', icon: FileCpp },
      { name: 'file-css', icon: FileCss },
      { name: 'file-csv', icon: FileCsv },
      { name: 'file-dashed', icon: FileDashed },
      { name: 'file-doc', icon: FileDoc },
      { name: 'file-html', icon: FileHtml },
      { name: 'file-image', icon: FileImage },
      { name: 'file-ini', icon: FileIni },
      { name: 'file-jpg', icon: FileJpg },
      { name: 'file-js', icon: FileJs },
      { name: 'file-jsx', icon: FileJsx },
      { name: 'file-lock', icon: FileLock },
      { name: 'file-magnifying-glass', icon: FileMagnifyingGlass },
      { name: 'file-md', icon: FileMd },
      { name: 'file-minus', icon: FileMinus },
      { name: 'file-pdf', icon: FilePdf },
      { name: 'file-plus', icon: FilePlus },
      { name: 'file-png', icon: FilePng },
      { name: 'file-ppt', icon: FilePpt },
      { name: 'file-py', icon: FilePy },
      { name: 'file-rs', icon: FileRs },
      { name: 'file-text', icon: FileText },
      { name: 'file-ts', icon: FileTs },
      { name: 'file-tsx', icon: FileTsx },
      { name: 'file-txt', icon: FileTxt },
      { name: 'file-video', icon: FileVideo },
      { name: 'file-vue', icon: FileVue },
      { name: 'file-x', icon: FileX },
      { name: 'file-xls', icon: FileXls },
      { name: 'file-zip', icon: FileZip },
      { name: 'files', icon: Files },
      { name: 'film-script', icon: FilmScript },
      { name: 'floppy-disk', icon: FloppyDisk },
      { name: 'floppy-disk-back', icon: FloppyDiskBack },
      { name: 'folder', icon: Folder },
      { name: 'folder-dashed', icon: FolderDashed },
      { name: 'folder-lock', icon: FolderLock },
      { name: 'folder-minus', icon: FolderMinus },
      { name: 'folder-open', icon: FolderOpen },
      { name: 'folder-plus', icon: FolderPlus },
      { name: 'folder-simple', icon: FolderSimple },
      { name: 'folder-simple-dashed', icon: FolderSimpleDashed },
      { name: 'folder-simple-lock', icon: FolderSimpleLock },
      { name: 'folder-simple-minus', icon: FolderSimpleMinus },
      { name: 'folder-simple-plus', icon: FolderSimplePlus },
      { name: 'folder-simple-star', icon: FolderSimpleStar },
      { name: 'folder-simple-user', icon: FolderSimpleUser },
      { name: 'folder-star', icon: FolderStar },
      { name: 'folder-user', icon: FolderUser },
      { name: 'folders', icon: Folders },
      { name: 'graph', icon: Graph },
      { name: 'kanban', icon: Kanban },
      { name: 'list-checks', icon: ListChecks },
      { name: 'note', icon: Note },
      { name: 'note-blank', icon: NoteBlank },
      { name: 'note-pencil', icon: NotePencil },
      { name: 'notebook', icon: Notebook },
      { name: 'notepad', icon: Notepad },
      { name: 'push-pin', icon: PushPin },
      { name: 'push-pin-simple', icon: PushPinSimple },
      { name: 'push-pin-simple-slash', icon: PushPinSimpleSlash },
      { name: 'push-pin-slash', icon: PushPinSlash },
      { name: 'suitcase', icon: Suitcase },
      { name: 'suitcase-simple', icon: SuitcaseSimple },
      { name: 'trash', icon: Trash },
      { name: 'trash-simple', icon: TrashSimple },
      { name: 'tray', icon: Tray },
      { name: 'tray-arrow-down', icon: TrayArrowDown },
      { name: 'tray-arrow-up', icon: TrayArrowUp },
      { name: 'trolley', icon: Trolley },
      { name: 'trolley-suitcase', icon: TrolleySuitcase },
    ],
  },
  {
    name: 'Media & Music',
    icons: [
      { name: 'airplay', icon: Airplay },
      { name: 'article', icon: Article },
      { name: 'article-medium', icon: ArticleMedium },
      { name: 'article-ny-times', icon: ArticleNyTimes },
      { name: 'camera', icon: Camera },
      { name: 'camera-plus', icon: CameraPlus },
      { name: 'camera-rotate', icon: CameraRotate },
      { name: 'camera-slash', icon: CameraSlash },
      { name: 'cassette-tape', icon: CassetteTape },
      { name: 'closed-captioning', icon: ClosedCaptioning },
      { name: 'ear', icon: Ear },
      { name: 'ear-slash', icon: EarSlash },
      { name: 'eject', icon: Eject },
      { name: 'eject-simple', icon: EjectSimple },
      { name: 'equalizer', icon: Equalizer },
      { name: 'faders', icon: Faders },
      { name: 'faders-horizontal', icon: FadersHorizontal },
      { name: 'fast-forward', icon: FastForward },
      { name: 'fast-forward-circle', icon: FastForwardCircle },
      { name: 'film-reel', icon: FilmReel },
      { name: 'film-slate', icon: FilmSlate },
      { name: 'film-strip', icon: FilmStrip },
      { name: 'four-k', icon: FourK },
      { name: 'gif', icon: Gif },
      { name: 'guitar', icon: Guitar },
      { name: 'headphones', icon: Headphones },
      { name: 'headset', icon: Headset },
      { name: 'high-definition', icon: HighDefinition },
      { name: 'image', icon: Image },
      { name: 'image-broken', icon: ImageBroken },
      { name: 'image-square', icon: ImageSquare },
      { name: 'images', icon: Images },
      { name: 'images-square', icon: ImagesSquare },
      { name: 'music-note', icon: MusicNote },
      { name: 'music-note-simple', icon: MusicNoteSimple },
      { name: 'music-notes', icon: MusicNotes },
      { name: 'music-notes-minus', icon: MusicNotesMinus },
      { name: 'music-notes-plus', icon: MusicNotesPlus },
      { name: 'music-notes-simple', icon: MusicNotesSimple },
      { name: 'newspaper', icon: Newspaper },
      { name: 'newspaper-clipping', icon: NewspaperClipping },
      { name: 'panorama', icon: Panorama },
      { name: 'pause', icon: Pause },
      { name: 'pause-circle', icon: PauseCircle },
      { name: 'piano-keys', icon: PianoKeys },
      { name: 'picture-in-picture', icon: PictureInPicture },
      { name: 'play', icon: Play },
      { name: 'play-circle', icon: PlayCircle },
      { name: 'play-pause', icon: PlayPause },
      { name: 'playlist', icon: Playlist },
      { name: 'queue', icon: Queue },
      { name: 'record', icon: Record },
      { name: 'repeat', icon: Repeat },
      { name: 'repeat-once', icon: RepeatOnce },
      { name: 'rewind', icon: Rewind },
      { name: 'rewind-circle', icon: RewindCircle },
      { name: 'screencast', icon: Screencast },
      { name: 'shuffle', icon: Shuffle },
      { name: 'shuffle-angular', icon: ShuffleAngular },
      { name: 'shuffle-simple', icon: ShuffleSimple },
      { name: 'skip-back', icon: SkipBack },
      { name: 'skip-back-circle', icon: SkipBackCircle },
      { name: 'skip-forward', icon: SkipForward },
      { name: 'skip-forward-circle', icon: SkipForwardCircle },
      { name: 'sliders', icon: Sliders },
      { name: 'sliders-horizontal', icon: SlidersHorizontal },
      { name: 'slideshow', icon: Slideshow },
      { name: 'speaker-hifi', icon: SpeakerHifi },
      { name: 'speaker-high', icon: SpeakerHigh },
      { name: 'speaker-low', icon: SpeakerLow },
      { name: 'speaker-none', icon: SpeakerNone },
      { name: 'speaker-simple-high', icon: SpeakerSimpleHigh },
      { name: 'speaker-simple-low', icon: SpeakerSimpleLow },
      { name: 'speaker-simple-none', icon: SpeakerSimpleNone },
      { name: 'speaker-simple-slash', icon: SpeakerSimpleSlash },
      { name: 'speaker-simple-x', icon: SpeakerSimpleX },
      { name: 'speaker-slash', icon: SpeakerSlash },
      { name: 'speaker-x', icon: SpeakerX },
      { name: 'standard-definition', icon: StandardDefinition },
      { name: 'stop', icon: Stop },
      { name: 'stop-circle', icon: StopCircle },
      { name: 'subtitles', icon: Subtitles },
      { name: 'subtitles-slash', icon: SubtitlesSlash },
      { name: 'three-d', icon: ThreeD },
      { name: 'video-camera', icon: VideoCamera },
      { name: 'video-camera-slash', icon: VideoCameraSlash },
      { name: 'video-conference', icon: VideoConference },
      { name: 'vinyl-record', icon: VinylRecord },
      { name: 'wave-sawtooth', icon: WaveSawtooth },
      { name: 'wave-sine', icon: WaveSine },
      { name: 'wave-square', icon: WaveSquare },
      { name: 'wave-triangle', icon: WaveTriangle },
      { name: 'waveform', icon: Waveform },
      { name: 'waveform-slash', icon: WaveformSlash },
    ],
  },
  {
    name: 'Games & Fun',
    icons: [
      { name: 'alien', icon: Alien },
      { name: 'baseball', icon: Baseball },
      { name: 'baseball-helmet', icon: BaseballHelmet },
      { name: 'basketball', icon: Basketball },
      { name: 'beach-ball', icon: BeachBall },
      { name: 'bomb', icon: Bomb },
      { name: 'boules', icon: Boules },
      { name: 'bowling-ball', icon: BowlingBall },
      { name: 'boxing-glove', icon: BoxingGlove },
      { name: 'checkerboard', icon: Checkerboard },
      { name: 'club', icon: Club },
      { name: 'court-basketball', icon: CourtBasketball },
      { name: 'cricket', icon: Cricket },
      { name: 'crown', icon: Crown },
      { name: 'crown-cross', icon: CrownCross },
      { name: 'crown-simple', icon: CrownSimple },
      { name: 'cube-focus', icon: CubeFocus },
      { name: 'dice-five', icon: DiceFive },
      { name: 'dice-four', icon: DiceFour },
      { name: 'dice-one', icon: DiceOne },
      { name: 'dice-six', icon: DiceSix },
      { name: 'dice-three', icon: DiceThree },
      { name: 'dice-two', icon: DiceTwo },
      { name: 'disco-ball', icon: DiscoBall },
      { name: 'drone', icon: Drone },
      { name: 'finn-the-human', icon: FinnTheHuman },
      { name: 'flying-saucer', icon: FlyingSaucer },
      { name: 'football', icon: Football },
      { name: 'football-helmet', icon: FootballHelmet },
      { name: 'game-controller', icon: GameController },
      { name: 'ghost', icon: Ghost },
      { name: 'golf', icon: Golf },
      { name: 'hockey', icon: Hockey },
      { name: 'horse', icon: Horse },
      { name: 'joystick', icon: Joystick },
      { name: 'lego', icon: Lego },
      { name: 'lego-smiley', icon: LegoSmiley },
      { name: 'pentagram', icon: Pentagram },
      { name: 'person-simple-ski', icon: PersonSimpleSki },
      { name: 'person-simple-snowboard', icon: PersonSimpleSnowboard },
      { name: 'ping-pong', icon: PingPong },
      { name: 'pinwheel', icon: Pinwheel },
      { name: 'poker-chip', icon: PokerChip },
      { name: 'puzzle-piece', icon: PuzzlePiece },
      { name: 'racquet', icon: Racquet },
      { name: 'ranking', icon: Ranking },
      { name: 'scroll', icon: Scroll },
      { name: 'skull', icon: Skull },
      { name: 'soccer-ball', icon: SoccerBall },
      { name: 'spade', icon: Spade },
      { name: 'strategy', icon: Strategy },
      { name: 'sword', icon: Sword },
      { name: 'tennis-ball', icon: TennisBall },
      { name: 'treasure-chest', icon: TreasureChest },
      { name: 'trophy', icon: Trophy },
      { name: 'virtual-reality', icon: VirtualReality },
      { name: 'volleyball', icon: Volleyball },
      { name: 'yarn', icon: Yarn },
    ],
  },
  {
    name: 'Social',
    icons: [
      { name: 'address-book', icon: AddressBook },
      { name: 'address-book-tabs', icon: AddressBookTabs },
      { name: 'anchor', icon: Anchor },
      { name: 'anchor-simple', icon: AnchorSimple },
      { name: 'app-window', icon: AppWindow },
      { name: 'asterisk', icon: Asterisk },
      { name: 'asterisk-simple', icon: AsteriskSimple },
      { name: 'at', icon: At },
      { name: 'broadcast', icon: Broadcast },
      { name: 'browser', icon: Browser },
      { name: 'browsers', icon: Browsers },
      { name: 'chat', icon: Chat },
      { name: 'chat-centered', icon: ChatCentered },
      { name: 'chat-centered-dots', icon: ChatCenteredDots },
      { name: 'chat-centered-slash', icon: ChatCenteredSlash },
      { name: 'chat-centered-text', icon: ChatCenteredText },
      { name: 'chat-circle', icon: ChatCircle },
      { name: 'chat-circle-dots', icon: ChatCircleDots },
      { name: 'chat-circle-slash', icon: ChatCircleSlash },
      { name: 'chat-circle-text', icon: ChatCircleText },
      { name: 'chat-dots', icon: ChatDots },
      { name: 'chat-slash', icon: ChatSlash },
      { name: 'chat-teardrop', icon: ChatTeardrop },
      { name: 'chat-teardrop-dots', icon: ChatTeardropDots },
      { name: 'chat-teardrop-slash', icon: ChatTeardropSlash },
      { name: 'chat-teardrop-text', icon: ChatTeardropText },
      { name: 'chat-text', icon: ChatText },
      { name: 'chats', icon: Chats },
      { name: 'chats-circle', icon: ChatsCircle },
      { name: 'chats-teardrop', icon: ChatsTeardrop },
      { name: 'confetti', icon: Confetti },
      { name: 'envelope', icon: Envelope },
      { name: 'envelope-open', icon: EnvelopeOpen },
      { name: 'envelope-simple', icon: EnvelopeSimple },
      { name: 'envelope-simple-open', icon: EnvelopeSimpleOpen },
      { name: 'export', icon: Export },
      { name: 'hash', icon: Hash },
      { name: 'hash-straight', icon: HashStraight },
      { name: 'heart', icon: Heart },
      { name: 'heart-break', icon: HeartBreak },
      { name: 'heart-half', icon: HeartHalf },
      { name: 'heart-straight', icon: HeartStraight },
      { name: 'heart-straight-break', icon: HeartStraightBreak },
      { name: 'link', icon: Link },
      { name: 'link-break', icon: LinkBreak },
      { name: 'link-simple', icon: LinkSimple },
      { name: 'link-simple-break', icon: LinkSimpleBreak },
      { name: 'link-simple-horizontal', icon: LinkSimpleHorizontal },
      { name: 'link-simple-horizontal-break', icon: LinkSimpleHorizontalBreak },
      { name: 'mailbox', icon: Mailbox },
      { name: 'mask-happy', icon: MaskHappy },
      { name: 'mask-sad', icon: MaskSad },
      { name: 'megaphone', icon: Megaphone },
      { name: 'megaphone-simple', icon: MegaphoneSimple },
      { name: 'microphone', icon: Microphone },
      { name: 'microphone-slash', icon: MicrophoneSlash },
      { name: 'microphone-stage', icon: MicrophoneStage },
      { name: 'numpad', icon: Numpad },
      { name: 'paper-plane', icon: PaperPlane },
      { name: 'paper-plane-right', icon: PaperPlaneRight },
      { name: 'paper-plane-tilt', icon: PaperPlaneTilt },
      { name: 'paperclip', icon: Paperclip },
      { name: 'paperclip-horizontal', icon: PaperclipHorizontal },
      { name: 'peace', icon: Peace },
      { name: 'phone', icon: Phone },
      { name: 'phone-call', icon: PhoneCall },
      { name: 'phone-disconnect', icon: PhoneDisconnect },
      { name: 'phone-incoming', icon: PhoneIncoming },
      { name: 'phone-list', icon: PhoneList },
      { name: 'phone-outgoing', icon: PhoneOutgoing },
      { name: 'phone-pause', icon: PhonePause },
      { name: 'phone-plus', icon: PhonePlus },
      { name: 'phone-slash', icon: PhoneSlash },
      { name: 'phone-transfer', icon: PhoneTransfer },
      { name: 'phone-x', icon: PhoneX },
      { name: 'quotes', icon: Quotes },
      { name: 'radio', icon: Radio },
      { name: 'rss', icon: Rss },
      { name: 'rss-simple', icon: RssSimple },
      { name: 'share', icon: Share },
      { name: 'share-network', icon: ShareNetwork },
      { name: 'signature', icon: Signature },
      { name: 'sim-card', icon: SimCard },
      { name: 'smiley', icon: Smiley },
      { name: 'smiley-angry', icon: SmileyAngry },
      { name: 'smiley-blank', icon: SmileyBlank },
      { name: 'smiley-meh', icon: SmileyMeh },
      { name: 'smiley-melting', icon: SmileyMelting },
      { name: 'smiley-nervous', icon: SmileyNervous },
      { name: 'smiley-sad', icon: SmileySad },
      { name: 'smiley-sticker', icon: SmileySticker },
      { name: 'smiley-wink', icon: SmileyWink },
      { name: 'smiley-x-eyes', icon: SmileyXEyes },
      { name: 'sparkle', icon: Sparkle },
      { name: 'spiral', icon: Spiral },
      { name: 'star', icon: Star },
      { name: 'star-and-crescent', icon: StarAndCrescent },
      { name: 'star-four', icon: StarFour },
      { name: 'star-half', icon: StarHalf },
      { name: 'star-of-david', icon: StarOfDavid },
      { name: 'sticker', icon: Sticker },
      { name: 'thumbs-down', icon: ThumbsDown },
      { name: 'thumbs-up', icon: ThumbsUp },
      { name: 'translate', icon: Translate },
      { name: 'webcam-slash', icon: WebcamSlash },
      { name: 'yin-yang', icon: YinYang },
    ],
  },
  {
    name: 'Travel',
    icons: [
      { name: 'air-traffic-control', icon: AirTrafficControl },
      { name: 'airplane', icon: Airplane },
      { name: 'airplane-in-flight', icon: AirplaneInFlight },
      { name: 'airplane-landing', icon: AirplaneLanding },
      { name: 'airplane-takeoff', icon: AirplaneTakeoff },
      { name: 'airplane-taxiing', icon: AirplaneTaxiing },
      { name: 'airplane-tilt', icon: AirplaneTilt },
      { name: 'barricade', icon: Barricade },
      { name: 'boat', icon: Boat },
      { name: 'bridge', icon: Bridge },
      { name: 'bus', icon: Bus },
      { name: 'cable-car', icon: CableCar },
      { name: 'call-bell', icon: CallBell },
      { name: 'car', icon: Car },
      { name: 'car-profile', icon: CarProfile },
      { name: 'car-simple', icon: CarSimple },
      { name: 'castle-turret', icon: CastleTurret },
      { name: 'chalkboard', icon: Chalkboard },
      { name: 'chalkboard-simple', icon: ChalkboardSimple },
      { name: 'chalkboard-teacher', icon: ChalkboardTeacher },
      { name: 'champagne', icon: Champagne },
      { name: 'charging-station', icon: ChargingStation },
      { name: 'church', icon: Church },
      { name: 'city', icon: City },
      { name: 'compass', icon: Compass },
      { name: 'compass-rose', icon: CompassRose },
      { name: 'cookie', icon: Cookie },
      { name: 'crosshair', icon: Crosshair },
      { name: 'crosshair-simple', icon: CrosshairSimple },
      { name: 'engine', icon: Engine },
      { name: 'escalator-down', icon: EscalatorDown },
      { name: 'escalator-up', icon: EscalatorUp },
      { name: 'flag-checkered', icon: FlagCheckered },
      { name: 'gas-can', icon: GasCan },
      { name: 'gas-pump', icon: GasPump },
      { name: 'globe', icon: Globe },
      { name: 'globe-hemisphere-east', icon: GlobeHemisphereEast },
      { name: 'globe-hemisphere-west', icon: GlobeHemisphereWest },
      { name: 'globe-simple', icon: GlobeSimple },
      { name: 'globe-simple-x', icon: GlobeSimpleX },
      { name: 'globe-stand', icon: GlobeStand },
      { name: 'globe-x', icon: GlobeX },
      { name: 'gps', icon: Gps },
      { name: 'gps-fix', icon: GpsFix },
      { name: 'gps-slash', icon: GpsSlash },
      { name: 'graduation-cap', icon: GraduationCap },
      { name: 'headlights', icon: Headlights },
      { name: 'hospital', icon: Hospital },
      { name: 'house', icon: House },
      { name: 'house-line', icon: HouseLine },
      { name: 'house-simple', icon: HouseSimple },
      { name: 'island', icon: Island },
      { name: 'jeep', icon: Jeep },
      { name: 'lighthouse', icon: Lighthouse },
      { name: 'lockers', icon: Lockers },
      { name: 'map-pin', icon: MapPin },
      { name: 'map-pin-area', icon: MapPinArea },
      { name: 'map-pin-line', icon: MapPinLine },
      { name: 'map-pin-plus', icon: MapPinPlus },
      { name: 'map-pin-simple', icon: MapPinSimple },
      { name: 'map-pin-simple-area', icon: MapPinSimpleArea },
      { name: 'map-pin-simple-line', icon: MapPinSimpleLine },
      { name: 'map-trifold', icon: MapTrifold },
      { name: 'moped', icon: Moped },
      { name: 'moped-front', icon: MopedFront },
      { name: 'mosque', icon: Mosque },
      { name: 'motorcycle', icon: Motorcycle },
      { name: 'navigation-arrow', icon: NavigationArrow },
      { name: 'orange-slice', icon: OrangeSlice },
      { name: 'park', icon: Park },
      { name: 'person', icon: Person },
      { name: 'person-simple', icon: PersonSimple },
      { name: 'person-simple-bike', icon: PersonSimpleBike },
      { name: 'person-simple-run', icon: PersonSimpleRun },
      { name: 'person-simple-swim', icon: PersonSimpleSwim },
      { name: 'person-simple-throw', icon: PersonSimpleThrow },
      { name: 'person-simple-walk', icon: PersonSimpleWalk },
      { name: 'picnic-table', icon: PicnicTable },
      { name: 'police-car', icon: PoliceCar },
      { name: 'popcorn', icon: Popcorn },
      { name: 'prohibit', icon: Prohibit },
      { name: 'prohibit-inset', icon: ProhibitInset },
      { name: 'road-horizon', icon: RoadHorizon },
      { name: 'sailboat', icon: Sailboat },
      { name: 'scooter', icon: Scooter },
      { name: 'seat', icon: Seat },
      { name: 'shipping-container', icon: ShippingContainer },
      { name: 'signpost', icon: Signpost },
      { name: 'steering-wheel', icon: SteeringWheel },
      { name: 'subway', icon: Subway },
      { name: 'suitcase-rolling', icon: SuitcaseRolling },
      { name: 'synagogue', icon: Synagogue },
      { name: 'target', icon: Target },
      { name: 'taxi', icon: Taxi },
      { name: 'traffic-cone', icon: TrafficCone },
      { name: 'traffic-sign', icon: TrafficSign },
      { name: 'traffic-signal', icon: TrafficSignal },
      { name: 'train', icon: Train },
      { name: 'train-regional', icon: TrainRegional },
      { name: 'train-simple', icon: TrainSimple },
      { name: 'tram', icon: Tram },
      { name: 'van', icon: Van },
    ],
  },
  {
    name: 'Nature',
    icons: [
      { name: 'binoculars', icon: Binoculars },
      { name: 'bird', icon: Bird },
      { name: 'bone', icon: Bone },
      { name: 'butterfly', icon: Butterfly },
      { name: 'cactus', icon: Cactus },
      { name: 'campfire', icon: Campfire },
      { name: 'cat', icon: Cat },
      { name: 'cherries', icon: Cherries },
      { name: 'clover', icon: Clover },
      { name: 'dog', icon: Dog },
      { name: 'drop', icon: Drop },
      { name: 'feather', icon: Feather },
      { name: 'fire', icon: Fire },
      { name: 'fire-simple', icon: FireSimple },
      { name: 'fish', icon: Fish },
      { name: 'fish-simple', icon: FishSimple },
      { name: 'flame', icon: Flame },
      { name: 'flower', icon: Flower },
      { name: 'flower-lotus', icon: FlowerLotus },
      { name: 'flower-tulip', icon: FlowerTulip },
      { name: 'leaf', icon: Leaf },
      { name: 'log', icon: Log },
      { name: 'microscope', icon: Microscope },
      { name: 'moon', icon: Moon },
      { name: 'moon-stars', icon: MoonStars },
      { name: 'mountains', icon: Mountains },
      { name: 'paw-print', icon: PawPrint },
      { name: 'person-simple-hike', icon: PersonSimpleHike },
      { name: 'planet', icon: Planet },
      { name: 'rabbit', icon: Rabbit },
      { name: 'radioactive', icon: Radioactive },
      { name: 'shooting-star', icon: ShootingStar },
      { name: 'sun', icon: Sun },
      { name: 'sun-dim', icon: SunDim },
      { name: 'sun-horizon', icon: SunHorizon },
      { name: 'tipi', icon: Tipi },
      { name: 'tree', icon: Tree },
      { name: 'tree-evergreen', icon: TreeEvergreen },
      { name: 'tree-palm', icon: TreePalm },
      { name: 'waves', icon: Waves },
    ],
  },
  {
    name: 'Weather',
    icons: [
      { name: 'cloud-fog', icon: CloudFog },
      { name: 'cloud-lightning', icon: CloudLightning },
      { name: 'cloud-moon', icon: CloudMoon },
      { name: 'cloud-rain', icon: CloudRain },
      { name: 'cloud-snow', icon: CloudSnow },
      { name: 'cloud-sun', icon: CloudSun },
      { name: 'hurricane', icon: Hurricane },
      { name: 'lightning', icon: Lightning },
      { name: 'meteor', icon: Meteor },
      { name: 'rainbow', icon: Rainbow },
      { name: 'rainbow-cloud', icon: RainbowCloud },
      { name: 'snowflake', icon: Snowflake },
      { name: 'thermometer', icon: Thermometer },
      { name: 'thermometer-cold', icon: ThermometerCold },
      { name: 'thermometer-hot', icon: ThermometerHot },
      { name: 'thermometer-simple', icon: ThermometerSimple },
      { name: 'tornado', icon: Tornado },
      { name: 'wind', icon: Wind },
    ],
  },
  {
    name: 'People',
    icons: [
      { name: 'baby', icon: Baby },
      { name: 'detective', icon: Detective },
      { name: 'eyes', icon: Eyes },
      { name: 'gender-female', icon: GenderFemale },
      { name: 'gender-intersex', icon: GenderIntersex },
      { name: 'gender-male', icon: GenderMale },
      { name: 'gender-neuter', icon: GenderNeuter },
      { name: 'gender-nonbinary', icon: GenderNonbinary },
      { name: 'gender-transgender', icon: GenderTransgender },
      { name: 'hand-arrow-down', icon: HandArrowDown },
      { name: 'hand-arrow-up', icon: HandArrowUp },
      { name: 'hand-coins', icon: HandCoins },
      { name: 'hand-deposit', icon: HandDeposit },
      { name: 'hand-eye', icon: HandEye },
      { name: 'hand-fist', icon: HandFist },
      { name: 'hand-heart', icon: HandHeart },
      { name: 'hand-peace', icon: HandPeace },
      { name: 'hand-swipe-left', icon: HandSwipeLeft },
      { name: 'hand-swipe-right', icon: HandSwipeRight },
      { name: 'hand-tap', icon: HandTap },
      { name: 'hand-withdraw', icon: HandWithdraw },
      { name: 'hands-praying', icon: HandsPraying },
      { name: 'handshake', icon: Handshake },
      { name: 'identification-badge', icon: IdentificationBadge },
      { name: 'identification-card', icon: IdentificationCard },
      { name: 'intersect-three', icon: IntersectThree },
      { name: 'person-simple-circle', icon: PersonSimpleCircle },
      { name: 'student', icon: Student },
      { name: 'user', icon: User },
      { name: 'user-check', icon: UserCheck },
      { name: 'user-circle', icon: UserCircle },
      { name: 'user-circle-check', icon: UserCircleCheck },
      { name: 'user-circle-dashed', icon: UserCircleDashed },
      { name: 'user-circle-gear', icon: UserCircleGear },
      { name: 'user-circle-minus', icon: UserCircleMinus },
      { name: 'user-circle-plus', icon: UserCirclePlus },
      { name: 'user-focus', icon: UserFocus },
      { name: 'user-gear', icon: UserGear },
      { name: 'user-list', icon: UserList },
      { name: 'user-minus', icon: UserMinus },
      { name: 'user-plus', icon: UserPlus },
      { name: 'user-rectangle', icon: UserRectangle },
      { name: 'user-sound', icon: UserSound },
      { name: 'user-square', icon: UserSquare },
      { name: 'user-switch', icon: UserSwitch },
      { name: 'users', icon: Users },
      { name: 'users-four', icon: UsersFour },
      { name: 'users-three', icon: UsersThree },
      { name: 'video', icon: Video },
    ],
  },
  {
    name: 'Finance',
    icons: [
      { name: 'acorn', icon: Acorn },
      { name: 'approximate-equals', icon: ApproximateEquals },
      { name: 'bank', icon: Bank },
      { name: 'chart-bar', icon: ChartBar },
      { name: 'chart-bar-horizontal', icon: ChartBarHorizontal },
      { name: 'chart-donut', icon: ChartDonut },
      { name: 'chart-line', icon: ChartLine },
      { name: 'chart-line-down', icon: ChartLineDown },
      { name: 'chart-line-up', icon: ChartLineUp },
      { name: 'chart-pie', icon: ChartPie },
      { name: 'chart-pie-slice', icon: ChartPieSlice },
      { name: 'chart-polar', icon: ChartPolar },
      { name: 'chart-scatter', icon: ChartScatter },
      { name: 'empty', icon: Empty },
      { name: 'greater-than', icon: GreaterThan },
      { name: 'greater-than-or-equal', icon: GreaterThanOrEqual },
      { name: 'intersection', icon: Intersection },
      { name: 'less-than', icon: LessThan },
      { name: 'less-than-or-equal', icon: LessThanOrEqual },
      { name: 'member-of', icon: MemberOf },
      { name: 'minus-square', icon: MinusSquare },
      { name: 'money-wavy', icon: MoneyWavy },
      { name: 'not-equals', icon: NotEquals },
      { name: 'not-member-of', icon: NotMemberOf },
      { name: 'not-subset-of', icon: NotSubsetOf },
      { name: 'not-superset-of', icon: NotSupersetOf },
      { name: 'number-circle-eight', icon: NumberCircleEight },
      { name: 'number-circle-five', icon: NumberCircleFive },
      { name: 'number-circle-four', icon: NumberCircleFour },
      { name: 'number-circle-nine', icon: NumberCircleNine },
      { name: 'number-circle-one', icon: NumberCircleOne },
      { name: 'number-circle-seven', icon: NumberCircleSeven },
      { name: 'number-circle-six', icon: NumberCircleSix },
      { name: 'number-circle-three', icon: NumberCircleThree },
      { name: 'number-circle-two', icon: NumberCircleTwo },
      { name: 'number-circle-zero', icon: NumberCircleZero },
      { name: 'number-eight', icon: NumberEight },
      { name: 'number-five', icon: NumberFive },
      { name: 'number-four', icon: NumberFour },
      { name: 'number-nine', icon: NumberNine },
      { name: 'number-one', icon: NumberOne },
      { name: 'number-seven', icon: NumberSeven },
      { name: 'number-six', icon: NumberSix },
      { name: 'number-square-eight', icon: NumberSquareEight },
      { name: 'number-square-five', icon: NumberSquareFive },
      { name: 'number-square-four', icon: NumberSquareFour },
      { name: 'number-square-nine', icon: NumberSquareNine },
      { name: 'number-square-one', icon: NumberSquareOne },
      { name: 'number-square-seven', icon: NumberSquareSeven },
      { name: 'number-square-six', icon: NumberSquareSix },
      { name: 'number-square-three', icon: NumberSquareThree },
      { name: 'number-square-two', icon: NumberSquareTwo },
      { name: 'number-square-zero', icon: NumberSquareZero },
      { name: 'number-three', icon: NumberThree },
      { name: 'number-two', icon: NumberTwo },
      { name: 'number-zero', icon: NumberZero },
      { name: 'pi', icon: Pi },
      { name: 'piggy-bank', icon: PiggyBank },
      { name: 'plus-square', icon: PlusSquare },
      { name: 'presentation', icon: Presentation },
      { name: 'presentation-chart', icon: PresentationChart },
      { name: 'projector-screen', icon: ProjectorScreen },
      { name: 'projector-screen-chart', icon: ProjectorScreenChart },
      { name: 'sigma', icon: Sigma },
      { name: 'subset-of', icon: SubsetOf },
      { name: 'subset-proper-of', icon: SubsetProperOf },
      { name: 'superset-of', icon: SupersetOf },
      { name: 'superset-proper-of', icon: SupersetProperOf },
      { name: 'table', icon: Table },
      { name: 'tilde', icon: Tilde },
      { name: 'trend-down', icon: TrendDown },
      { name: 'trend-up', icon: TrendUp },
      { name: 'union', icon: Union },
    ],
  },
  {
    name: 'Objects',
    icons: [
      { name: 'armchair', icon: Armchair },
      { name: 'bathtub', icon: Bathtub },
      { name: 'broom', icon: Broom },
      { name: 'cake', icon: Cake },
      { name: 'certificate', icon: Certificate },
      { name: 'chair', icon: Chair },
      { name: 'cooking-pot', icon: CookingPot },
      { name: 'couch', icon: Couch },
      { name: 'device-mobile', icon: DeviceMobile },
      { name: 'device-mobile-camera', icon: DeviceMobileCamera },
      { name: 'device-mobile-slash', icon: DeviceMobileSlash },
      { name: 'device-mobile-speaker', icon: DeviceMobileSpeaker },
      { name: 'device-rotate', icon: DeviceRotate },
      { name: 'device-tablet', icon: DeviceTablet },
      { name: 'device-tablet-camera', icon: DeviceTabletCamera },
      { name: 'device-tablet-speaker', icon: DeviceTabletSpeaker },
      { name: 'devices', icon: Devices },
      { name: 'door', icon: Door },
      { name: 'door-open', icon: DoorOpen },
      { name: 'elevator', icon: Elevator },
      { name: 'exam', icon: Exam },
      { name: 'fire-extinguisher', icon: FireExtinguisher },
      { name: 'flag', icon: Flag },
      { name: 'flag-banner', icon: FlagBanner },
      { name: 'flag-banner-fold', icon: FlagBannerFold },
      { name: 'flag-pennant', icon: FlagPennant },
      { name: 'hammer', icon: Hammer },
      { name: 'key', icon: Key },
      { name: 'keyhole', icon: Keyhole },
      { name: 'ladder', icon: Ladder },
      { name: 'ladder-simple', icon: LadderSimple },
      { name: 'lamp', icon: Lamp },
      { name: 'lectern', icon: Lectern },
      { name: 'lock', icon: Lock },
      { name: 'lock-key', icon: LockKey },
      { name: 'lock-key-open', icon: LockKeyOpen },
      { name: 'lock-laminated', icon: LockLaminated },
      { name: 'lock-laminated-open', icon: LockLaminatedOpen },
      { name: 'lock-open', icon: LockOpen },
      { name: 'lock-simple', icon: LockSimple },
      { name: 'lock-simple-open', icon: LockSimpleOpen },
      { name: 'medal', icon: Medal },
      { name: 'medal-military', icon: MedalMilitary },
      { name: 'metronome', icon: Metronome },
      { name: 'needle', icon: Needle },
      { name: 'nut', icon: Nut },
      { name: 'office-chair', icon: OfficeChair },
      { name: 'parachute', icon: Parachute },
      { name: 'rug', icon: Rug },
      { name: 'security-camera', icon: SecurityCamera },
      { name: 'shield-star', icon: ShieldStar },
      { name: 'shower', icon: Shower },
      { name: 'siren', icon: Siren },
      { name: 'spray-bottle', icon: SprayBottle },
      { name: 'stool', icon: Stool },
      { name: 't-shirt', icon: TShirt },
      { name: 'toolbox', icon: Toolbox },
      { name: 'umbrella', icon: Umbrella },
      { name: 'umbrella-simple', icon: UmbrellaSimple },
      { name: 'usb', icon: Usb },
      { name: 'vault', icon: Vault },
      { name: 'wall', icon: Wall },
      { name: 'webcam', icon: Webcam },
    ],
  },
  {
    name: 'Tech & Dev',
    icons: [
      { name: 'atom', icon: Atom },
      { name: 'binary', icon: Binary },
      { name: 'brackets-angle', icon: BracketsAngle },
      { name: 'brackets-curly', icon: BracketsCurly },
      { name: 'brackets-round', icon: BracketsRound },
      { name: 'brackets-square', icon: BracketsSquare },
      { name: 'bug', icon: Bug },
      { name: 'bug-beetle', icon: BugBeetle },
      { name: 'bug-droid', icon: BugDroid },
      { name: 'calculator', icon: Calculator },
      { name: 'circuitry', icon: Circuitry },
      { name: 'code', icon: Code },
      { name: 'code-block', icon: CodeBlock },
      { name: 'code-simple', icon: CodeSimple },
      { name: 'computer-tower', icon: ComputerTower },
      { name: 'cpu', icon: Cpu },
      { name: 'database', icon: Database },
      { name: 'desktop', icon: Desktop },
      { name: 'desktop-tower', icon: DesktopTower },
      { name: 'disc', icon: Disc },
      { name: 'divide', icon: Divide },
      { name: 'equals', icon: Equals },
      { name: 'flask', icon: Flask },
      { name: 'function', icon: Function },
      { name: 'gauge', icon: Gauge },
      { name: 'git-branch', icon: GitBranch },
      { name: 'git-commit', icon: GitCommit },
      { name: 'git-diff', icon: GitDiff },
      { name: 'git-fork', icon: GitFork },
      { name: 'git-merge', icon: GitMerge },
      { name: 'git-pull-request', icon: GitPullRequest },
      { name: 'github-logo', icon: GithubLogo },
      { name: 'graphics-card', icon: GraphicsCard },
      { name: 'head-circuit', icon: HeadCircuit },
      { name: 'infinity', icon: Infinity },
      { name: 'laptop', icon: Laptop },
      { name: 'magnet', icon: Magnet },
      { name: 'magnet-straight', icon: MagnetStraight },
      { name: 'markdown-logo', icon: MarkdownLogo },
      { name: 'math-operations', icon: MathOperations },
      { name: 'memory', icon: Memory },
      { name: 'minus', icon: Minus },
      { name: 'minus-circle', icon: MinusCircle },
      { name: 'open-ai-logo', icon: OpenAiLogo },
      { name: 'package', icon: Package },
      { name: 'percent', icon: Percent },
      { name: 'plus', icon: Plus },
      { name: 'plus-circle', icon: PlusCircle },
      { name: 'plus-minus', icon: PlusMinus },
      { name: 'radical', icon: Radical },
      { name: 'robot', icon: Robot },
      { name: 'rocket', icon: Rocket },
      { name: 'rocket-launch', icon: RocketLaunch },
      { name: 'speedometer', icon: Speedometer },
      { name: 'terminal', icon: Terminal },
      { name: 'terminal-window', icon: TerminalWindow },
      { name: 'test-tube', icon: TestTube },
      { name: 'tree-structure', icon: TreeStructure },
      { name: 'visor', icon: Visor },
      { name: 'webhooks-logo', icon: WebhooksLogo },
      { name: 'x', icon: X },
    ],
  },
  {
    name: 'Design',
    icons: [
      { name: 'align-bottom', icon: AlignBottom },
      { name: 'align-bottom-simple', icon: AlignBottomSimple },
      { name: 'align-center-horizontal', icon: AlignCenterHorizontal },
      { name: 'align-center-horizontal-simple', icon: AlignCenterHorizontalSimple },
      { name: 'align-center-vertical', icon: AlignCenterVertical },
      { name: 'align-center-vertical-simple', icon: AlignCenterVerticalSimple },
      { name: 'align-left', icon: AlignLeft },
      { name: 'align-left-simple', icon: AlignLeftSimple },
      { name: 'align-right', icon: AlignRight },
      { name: 'align-right-simple', icon: AlignRightSimple },
      { name: 'align-top', icon: AlignTop },
      { name: 'align-top-simple', icon: AlignTopSimple },
      { name: 'angle', icon: Angle },
      { name: 'aperture', icon: Aperture },
      { name: 'bezier-curve', icon: BezierCurve },
      { name: 'bounding-box', icon: BoundingBox },
      { name: 'cards', icon: Cards },
      { name: 'cards-three', icon: CardsThree },
      { name: 'circle', icon: Circle },
      { name: 'circle-dashed', icon: CircleDashed },
      { name: 'circle-half', icon: CircleHalf },
      { name: 'circle-half-tilt', icon: CircleHalfTilt },
      { name: 'circles-four', icon: CirclesFour },
      { name: 'circles-three', icon: CirclesThree },
      { name: 'circles-three-plus', icon: CirclesThreePlus },
      { name: 'columns', icon: Columns },
      { name: 'columns-plus-left', icon: ColumnsPlusLeft },
      { name: 'columns-plus-right', icon: ColumnsPlusRight },
      { name: 'compass-tool', icon: CompassTool },
      { name: 'crop', icon: Crop },
      { name: 'cross', icon: Cross },
      { name: 'cube', icon: Cube },
      { name: 'cube-transparent', icon: CubeTransparent },
      { name: 'cursor', icon: Cursor },
      { name: 'cursor-click', icon: CursorClick },
      { name: 'cylinder', icon: Cylinder },
      { name: 'diamond', icon: Diamond },
      { name: 'diamonds-four', icon: DiamondsFour },
      { name: 'dots-nine', icon: DotsNine },
      { name: 'drop-half', icon: DropHalf },
      { name: 'drop-half-bottom', icon: DropHalfBottom },
      { name: 'drop-simple', icon: DropSimple },
      { name: 'drop-slash', icon: DropSlash },
      { name: 'eraser', icon: Eraser },
      { name: 'exclude', icon: Exclude },
      { name: 'exclude-square', icon: ExcludeSquare },
      { name: 'eye', icon: Eye },
      { name: 'eye-closed', icon: EyeClosed },
      { name: 'eye-slash', icon: EyeSlash },
      { name: 'eyedropper', icon: Eyedropper },
      { name: 'eyedropper-sample', icon: EyedropperSample },
      { name: 'flip-horizontal', icon: FlipHorizontal },
      { name: 'flip-vertical', icon: FlipVertical },
      { name: 'gradient', icon: Gradient },
      { name: 'grid-four', icon: GridFour },
      { name: 'grid-nine', icon: GridNine },
      { name: 'hexagon', icon: Hexagon },
      { name: 'highlighter', icon: Highlighter },
      { name: 'highlighter-circle', icon: HighlighterCircle },
      { name: 'intersect', icon: Intersect },
      { name: 'intersect-square', icon: IntersectSquare },
      { name: 'lasso', icon: Lasso },
      { name: 'layout', icon: Layout },
      { name: 'line-segment', icon: LineSegment },
      { name: 'line-segments', icon: LineSegments },
      { name: 'line-vertical', icon: LineVertical },
      { name: 'magic-wand', icon: MagicWand },
      { name: 'marker-circle', icon: MarkerCircle },
      { name: 'octagon', icon: Octagon },
      { name: 'paint-brush', icon: PaintBrush },
      { name: 'paint-brush-broad', icon: PaintBrushBroad },
      { name: 'paint-brush-household', icon: PaintBrushHousehold },
      { name: 'paint-bucket', icon: PaintBucket },
      { name: 'paint-roller', icon: PaintRoller },
      { name: 'palette', icon: Palette },
      { name: 'path', icon: Path },
      { name: 'pen', icon: Pen },
      { name: 'pen-nib', icon: PenNib },
      { name: 'pen-nib-straight', icon: PenNibStraight },
      { name: 'pencil', icon: Pencil },
      { name: 'pencil-circle', icon: PencilCircle },
      { name: 'pencil-line', icon: PencilLine },
      { name: 'pencil-ruler', icon: PencilRuler },
      { name: 'pencil-simple', icon: PencilSimple },
      { name: 'pencil-simple-line', icon: PencilSimpleLine },
      { name: 'pencil-simple-slash', icon: PencilSimpleSlash },
      { name: 'pencil-slash', icon: PencilSlash },
      { name: 'pentagon', icon: Pentagon },
      { name: 'perspective', icon: Perspective },
      { name: 'placeholder', icon: Placeholder },
      { name: 'polygon', icon: Polygon },
      { name: 'rectangle', icon: Rectangle },
      { name: 'rectangle-dashed', icon: RectangleDashed },
      { name: 'resize', icon: Resize },
      { name: 'rows', icon: Rows },
      { name: 'rows-plus-bottom', icon: RowsPlusBottom },
      { name: 'rows-plus-top', icon: RowsPlusTop },
      { name: 'ruler', icon: Ruler },
      { name: 'scissors', icon: Scissors },
      { name: 'scribble', icon: Scribble },
      { name: 'scribble-loop', icon: ScribbleLoop },
      { name: 'seal', icon: Seal },
      { name: 'seal-check', icon: SealCheck },
      { name: 'seal-percent', icon: SealPercent },
      { name: 'seal-question', icon: SealQuestion },
      { name: 'seal-warning', icon: SealWarning },
      { name: 'selection', icon: Selection },
      { name: 'selection-all', icon: SelectionAll },
      { name: 'selection-background', icon: SelectionBackground },
      { name: 'selection-foreground', icon: SelectionForeground },
      { name: 'selection-inverse', icon: SelectionInverse },
      { name: 'selection-plus', icon: SelectionPlus },
      { name: 'selection-slash', icon: SelectionSlash },
      { name: 'shapes', icon: Shapes },
      { name: 'sidebar', icon: Sidebar },
      { name: 'sidebar-simple', icon: SidebarSimple },
      { name: 'sketch-logo', icon: SketchLogo },
      { name: 'sphere', icon: Sphere },
      { name: 'square', icon: Square },
      { name: 'square-half', icon: SquareHalf },
      { name: 'square-half-bottom', icon: SquareHalfBottom },
      { name: 'square-split-horizontal', icon: SquareSplitHorizontal },
      { name: 'square-split-vertical', icon: SquareSplitVertical },
      { name: 'squares-four', icon: SquaresFour },
      { name: 'stack', icon: Stack },
      { name: 'stack-minus', icon: StackMinus },
      { name: 'stack-plus', icon: StackPlus },
      { name: 'stack-simple', icon: StackSimple },
      { name: 'stamp', icon: Stamp },
      { name: 'subtract', icon: Subtract },
      { name: 'subtract-square', icon: SubtractSquare },
      { name: 'swap', icon: Swap },
      { name: 'swatches', icon: Swatches },
      { name: 'text-a-underline', icon: TextAUnderline },
      { name: 'text-aa', icon: TextAa },
      { name: 'text-align-center', icon: TextAlignCenter },
      { name: 'text-align-justify', icon: TextAlignJustify },
      { name: 'text-align-left', icon: TextAlignLeft },
      { name: 'text-align-right', icon: TextAlignRight },
      { name: 'text-b', icon: TextB },
      { name: 'text-columns', icon: TextColumns },
      { name: 'text-h', icon: TextH },
      { name: 'text-h-five', icon: TextHFive },
      { name: 'text-h-four', icon: TextHFour },
      { name: 'text-h-one', icon: TextHOne },
      { name: 'text-h-six', icon: TextHSix },
      { name: 'text-h-three', icon: TextHThree },
      { name: 'text-h-two', icon: TextHTwo },
      { name: 'text-indent', icon: TextIndent },
      { name: 'text-italic', icon: TextItalic },
      { name: 'text-outdent', icon: TextOutdent },
      { name: 'text-strikethrough', icon: TextStrikethrough },
      { name: 'text-subscript', icon: TextSubscript },
      { name: 'text-superscript', icon: TextSuperscript },
      { name: 'text-t', icon: TextT },
      { name: 'text-t-slash', icon: TextTSlash },
      { name: 'text-underline', icon: TextUnderline },
      { name: 'triangle', icon: Triangle },
      { name: 'triangle-dashed', icon: TriangleDashed },
      { name: 'unite', icon: Unite },
      { name: 'unite-square', icon: UniteSquare },
      { name: 'vignette', icon: Vignette },
    ],
  },
  {
    name: 'System',
    icons: [
      { name: 'alarm', icon: Alarm },
      { name: 'backspace', icon: Backspace },
      { name: 'battery-charging', icon: BatteryCharging },
      { name: 'battery-charging-vertical', icon: BatteryChargingVertical },
      { name: 'battery-empty', icon: BatteryEmpty },
      { name: 'battery-full', icon: BatteryFull },
      { name: 'battery-high', icon: BatteryHigh },
      { name: 'battery-low', icon: BatteryLow },
      { name: 'battery-medium', icon: BatteryMedium },
      { name: 'battery-plus', icon: BatteryPlus },
      { name: 'battery-plus-vertical', icon: BatteryPlusVertical },
      { name: 'battery-vertical-empty', icon: BatteryVerticalEmpty },
      { name: 'battery-vertical-full', icon: BatteryVerticalFull },
      { name: 'battery-vertical-high', icon: BatteryVerticalHigh },
      { name: 'battery-vertical-low', icon: BatteryVerticalLow },
      { name: 'battery-vertical-medium', icon: BatteryVerticalMedium },
      { name: 'battery-warning', icon: BatteryWarning },
      { name: 'battery-warning-vertical', icon: BatteryWarningVertical },
      { name: 'bell', icon: Bell },
      { name: 'bell-ringing', icon: BellRinging },
      { name: 'bell-simple', icon: BellSimple },
      { name: 'bell-simple-ringing', icon: BellSimpleRinging },
      { name: 'bell-simple-slash', icon: BellSimpleSlash },
      { name: 'bell-simple-z', icon: BellSimpleZ },
      { name: 'bell-slash', icon: BellSlash },
      { name: 'bell-z', icon: BellZ },
      { name: 'bluetooth', icon: Bluetooth },
      { name: 'bluetooth-connected', icon: BluetoothConnected },
      { name: 'bluetooth-slash', icon: BluetoothSlash },
      { name: 'bluetooth-x', icon: BluetoothX },
      { name: 'cell-signal-full', icon: CellSignalFull },
      { name: 'cell-signal-high', icon: CellSignalHigh },
      { name: 'cell-signal-low', icon: CellSignalLow },
      { name: 'cell-signal-medium', icon: CellSignalMedium },
      { name: 'cell-signal-none', icon: CellSignalNone },
      { name: 'cell-signal-slash', icon: CellSignalSlash },
      { name: 'cell-signal-x', icon: CellSignalX },
      { name: 'cell-tower', icon: CellTower },
      { name: 'check', icon: Check },
      { name: 'check-circle', icon: CheckCircle },
      { name: 'check-fat', icon: CheckFat },
      { name: 'check-square', icon: CheckSquare },
      { name: 'check-square-offset', icon: CheckSquareOffset },
      { name: 'checks', icon: Checks },
      { name: 'circle-notch', icon: CircleNotch },
      { name: 'clock', icon: Clock },
      { name: 'clock-afternoon', icon: ClockAfternoon },
      { name: 'clock-clockwise', icon: ClockClockwise },
      { name: 'clock-countdown', icon: ClockCountdown },
      { name: 'clock-counter-clockwise', icon: ClockCounterClockwise },
      { name: 'clock-user', icon: ClockUser },
      { name: 'cloud', icon: Cloud },
      { name: 'cloud-arrow-down', icon: CloudArrowDown },
      { name: 'cloud-arrow-up', icon: CloudArrowUp },
      { name: 'cloud-check', icon: CloudCheck },
      { name: 'cloud-slash', icon: CloudSlash },
      { name: 'cloud-warning', icon: CloudWarning },
      { name: 'cloud-x', icon: CloudX },
      { name: 'control', icon: Control },
      { name: 'corners-in', icon: CornersIn },
      { name: 'corners-out', icon: CornersOut },
      { name: 'dot', icon: Dot },
      { name: 'dot-outline', icon: DotOutline },
      { name: 'dots-six', icon: DotsSix },
      { name: 'dots-six-vertical', icon: DotsSixVertical },
      { name: 'dots-three', icon: DotsThree },
      { name: 'dots-three-circle', icon: DotsThreeCircle },
      { name: 'dots-three-circle-vertical', icon: DotsThreeCircleVertical },
      { name: 'dots-three-outline', icon: DotsThreeOutline },
      { name: 'dots-three-outline-vertical', icon: DotsThreeOutlineVertical },
      { name: 'dots-three-vertical', icon: DotsThreeVertical },
      { name: 'download', icon: Download },
      { name: 'download-simple', icon: DownloadSimple },
      { name: 'exclamation-mark', icon: ExclamationMark },
      { name: 'file-archive', icon: FileArchive },
      { name: 'file-sql', icon: FileSql },
      { name: 'file-svg', icon: FileSvg },
      { name: 'fingerprint', icon: Fingerprint },
      { name: 'fingerprint-simple', icon: FingerprintSimple },
      { name: 'flashlight', icon: Flashlight },
      { name: 'frame-corners', icon: FrameCorners },
      { name: 'gear', icon: Gear },
      { name: 'gear-fine', icon: GearFine },
      { name: 'gear-six', icon: GearSix },
      { name: 'hand', icon: Hand },
      { name: 'hand-grabbing', icon: HandGrabbing },
      { name: 'hand-palm', icon: HandPalm },
      { name: 'hand-pointing', icon: HandPointing },
      { name: 'hand-waving', icon: HandWaving },
      { name: 'hands-clapping', icon: HandsClapping },
      { name: 'hard-drive', icon: HardDrive },
      { name: 'hard-drives', icon: HardDrives },
      { name: 'hourglass', icon: Hourglass },
      { name: 'hourglass-high', icon: HourglassHigh },
      { name: 'hourglass-low', icon: HourglassLow },
      { name: 'hourglass-medium', icon: HourglassMedium },
      { name: 'hourglass-simple', icon: HourglassSimple },
      { name: 'hourglass-simple-high', icon: HourglassSimpleHigh },
      { name: 'hourglass-simple-low', icon: HourglassSimpleLow },
      { name: 'hourglass-simple-medium', icon: HourglassSimpleMedium },
      { name: 'info', icon: Info },
      { name: 'key-return', icon: KeyReturn },
      { name: 'keyboard', icon: Keyboard },
      { name: 'lightbulb', icon: Lightbulb },
      { name: 'lightbulb-filament', icon: LightbulbFilament },
      { name: 'lightning-a', icon: LightningA },
      { name: 'lightning-slash', icon: LightningSlash },
      { name: 'list', icon: List },
      { name: 'monitor', icon: Monitor },
      { name: 'monitor-arrow-up', icon: MonitorArrowUp },
      { name: 'monitor-play', icon: MonitorPlay },
      { name: 'mouse', icon: Mouse },
      { name: 'mouse-left-click', icon: MouseLeftClick },
      { name: 'mouse-middle-click', icon: MouseMiddleClick },
      { name: 'mouse-right-click', icon: MouseRightClick },
      { name: 'mouse-scroll', icon: MouseScroll },
      { name: 'mouse-simple', icon: MouseSimple },
      { name: 'network', icon: Network },
      { name: 'network-slash', icon: NetworkSlash },
      { name: 'network-x', icon: NetworkX },
      { name: 'notches', icon: Notches },
      { name: 'notification', icon: Notification },
      { name: 'option', icon: Option },
      { name: 'password', icon: Password },
      { name: 'plug', icon: Plug },
      { name: 'plug-charging', icon: PlugCharging },
      { name: 'plugs', icon: Plugs },
      { name: 'plugs-connected', icon: PlugsConnected },
      { name: 'power', icon: Power },
      { name: 'qr-code', icon: QrCode },
      { name: 'question', icon: Question },
      { name: 'question-mark', icon: QuestionMark },
      { name: 'radio-button', icon: RadioButton },
      { name: 'scan', icon: Scan },
      { name: 'scan-smiley', icon: ScanSmiley },
      { name: 'shield', icon: Shield },
      { name: 'shield-check', icon: ShieldCheck },
      { name: 'shield-checkered', icon: ShieldCheckered },
      { name: 'shield-chevron', icon: ShieldChevron },
      { name: 'shield-plus', icon: ShieldPlus },
      { name: 'shield-slash', icon: ShieldSlash },
      { name: 'shield-warning', icon: ShieldWarning },
      { name: 'sign-in', icon: SignIn },
      { name: 'sign-out', icon: SignOut },
      { name: 'spinner', icon: Spinner },
      { name: 'spinner-ball', icon: SpinnerBall },
      { name: 'spinner-gap', icon: SpinnerGap },
      { name: 'tabs', icon: Tabs },
      { name: 'television', icon: Television },
      { name: 'television-simple', icon: TelevisionSimple },
      { name: 'timer', icon: Timer },
      { name: 'toggle-left', icon: ToggleLeft },
      { name: 'toggle-right', icon: ToggleRight },
      { name: 'tree-view', icon: TreeView },
      { name: 'upload', icon: Upload },
      { name: 'upload-simple', icon: UploadSimple },
      { name: 'vibrate', icon: Vibrate },
      { name: 'voicemail', icon: Voicemail },
      { name: 'warning', icon: Warning },
      { name: 'warning-circle', icon: WarningCircle },
      { name: 'warning-diamond', icon: WarningDiamond },
      { name: 'warning-octagon', icon: WarningOctagon },
      { name: 'watch', icon: Watch },
      { name: 'wifi-high', icon: WifiHigh },
      { name: 'wifi-low', icon: WifiLow },
      { name: 'wifi-medium', icon: WifiMedium },
      { name: 'wifi-none', icon: WifiNone },
      { name: 'wifi-slash', icon: WifiSlash },
      { name: 'wifi-x', icon: WifiX },
      { name: 'wrench', icon: Wrench },
      { name: 'x-circle', icon: XCircle },
      { name: 'x-square', icon: XSquare },
    ],
  },
  {
    name: 'Editor',
    icons: [
      { name: 'command', icon: Command },
      { name: 'copy', icon: Copy },
      { name: 'copy-simple', icon: CopySimple },
      { name: 'cursor-text', icon: CursorText },
      { name: 'funnel', icon: Funnel },
      { name: 'funnel-simple', icon: FunnelSimple },
      { name: 'funnel-simple-x', icon: FunnelSimpleX },
      { name: 'funnel-x', icon: FunnelX },
      { name: 'letter-circle-h', icon: LetterCircleH },
      { name: 'letter-circle-p', icon: LetterCircleP },
      { name: 'letter-circle-v', icon: LetterCircleV },
      { name: 'list-bullets', icon: ListBullets },
      { name: 'list-dashes', icon: ListDashes },
      { name: 'list-heart', icon: ListHeart },
      { name: 'list-magnifying-glass', icon: ListMagnifyingGlass },
      { name: 'list-numbers', icon: ListNumbers },
      { name: 'list-plus', icon: ListPlus },
      { name: 'list-star', icon: ListStar },
      { name: 'magnifying-glass', icon: MagnifyingGlass },
      { name: 'magnifying-glass-minus', icon: MagnifyingGlassMinus },
      { name: 'magnifying-glass-plus', icon: MagnifyingGlassPlus },
      { name: 'paragraph', icon: Paragraph },
      { name: 'printer', icon: Printer },
      { name: 'sort-ascending', icon: SortAscending },
      { name: 'sort-descending', icon: SortDescending },
      { name: 'textbox', icon: Textbox },
    ],
  },
  {
    name: 'Brands',
    icons: [
      { name: 'amazon-logo', icon: AmazonLogo },
      { name: 'android-logo', icon: AndroidLogo },
      { name: 'angular-logo', icon: AngularLogo },
      { name: 'app-store-logo', icon: AppStoreLogo },
      { name: 'apple-logo', icon: AppleLogo },
      { name: 'apple-podcasts-logo', icon: ApplePodcastsLogo },
      { name: 'behance-logo', icon: BehanceLogo },
      { name: 'coda-logo', icon: CodaLogo },
      { name: 'codepen-logo', icon: CodepenLogo },
      { name: 'codesandbox-logo', icon: CodesandboxLogo },
      { name: 'dev-to-logo', icon: DevToLogo },
      { name: 'discord-logo', icon: DiscordLogo },
      { name: 'dribbble-logo', icon: DribbbleLogo },
      { name: 'dropbox-logo', icon: DropboxLogo },
      { name: 'facebook-logo', icon: FacebookLogo },
      { name: 'fediverse-logo', icon: FediverseLogo },
      { name: 'figma-logo', icon: FigmaLogo },
      { name: 'framer-logo', icon: FramerLogo },
      { name: 'gitlab-logo', icon: GitlabLogo },
      { name: 'gitlab-logo-simple', icon: GitlabLogoSimple },
      { name: 'goodreads-logo', icon: GoodreadsLogo },
      { name: 'google-cardboard-logo', icon: GoogleCardboardLogo },
      { name: 'google-chrome-logo', icon: GoogleChromeLogo },
      { name: 'google-drive-logo', icon: GoogleDriveLogo },
      { name: 'google-logo', icon: GoogleLogo },
      { name: 'google-photos-logo', icon: GooglePhotosLogo },
      { name: 'google-play-logo', icon: GooglePlayLogo },
      { name: 'google-podcasts-logo', icon: GooglePodcastsLogo },
      { name: 'instagram-logo', icon: InstagramLogo },
      { name: 'lastfm-logo', icon: LastfmLogo },
      { name: 'linkedin-logo', icon: LinkedinLogo },
      { name: 'linktree-logo', icon: LinktreeLogo },
      { name: 'linux-logo', icon: LinuxLogo },
      { name: 'mastodon-logo', icon: MastodonLogo },
      { name: 'matrix-logo', icon: MatrixLogo },
      { name: 'medium-logo', icon: MediumLogo },
      { name: 'messenger-logo', icon: MessengerLogo },
      { name: 'meta-logo', icon: MetaLogo },
      { name: 'microsoft-excel-logo', icon: MicrosoftExcelLogo },
      { name: 'microsoft-outlook-logo', icon: MicrosoftOutlookLogo },
      { name: 'microsoft-powerpoint-logo', icon: MicrosoftPowerpointLogo },
      { name: 'microsoft-teams-logo', icon: MicrosoftTeamsLogo },
      { name: 'microsoft-word-logo', icon: MicrosoftWordLogo },
      { name: 'notion-logo', icon: NotionLogo },
      { name: 'ny-times-logo', icon: NyTimesLogo },
      { name: 'parallelogram', icon: Parallelogram },
      { name: 'patreon-logo', icon: PatreonLogo },
      { name: 'paypal-logo', icon: PaypalLogo },
      { name: 'phosphor-logo', icon: PhosphorLogo },
      { name: 'pinterest-logo', icon: PinterestLogo },
      { name: 'read-cv-logo', icon: ReadCvLogo },
      { name: 'reddit-logo', icon: RedditLogo },
      { name: 'replit-logo', icon: ReplitLogo },
      { name: 'skype-logo', icon: SkypeLogo },
      { name: 'slack-logo', icon: SlackLogo },
      { name: 'snapchat-logo', icon: SnapchatLogo },
      { name: 'soundcloud-logo', icon: SoundcloudLogo },
      { name: 'spotify-logo', icon: SpotifyLogo },
      { name: 'square-logo', icon: SquareLogo },
      { name: 'stack-overflow-logo', icon: StackOverflowLogo },
      { name: 'steam-logo', icon: SteamLogo },
      { name: 'stripe-logo', icon: StripeLogo },
      { name: 'telegram-logo', icon: TelegramLogo },
      { name: 'threads-logo', icon: ThreadsLogo },
      { name: 'tidal-logo', icon: TidalLogo },
      { name: 'tiktok-logo', icon: TiktokLogo },
      { name: 'tumblr-logo', icon: TumblrLogo },
      { name: 'twitch-logo', icon: TwitchLogo },
      { name: 'twitter-logo', icon: TwitterLogo },
      { name: 'wechat-logo', icon: WechatLogo },
      { name: 'whatsapp-logo', icon: WhatsappLogo },
      { name: 'windows-logo', icon: WindowsLogo },
      { name: 'x-logo', icon: XLogo },
      { name: 'youtube-logo', icon: YoutubeLogo },
    ],
  },
  {
    name: 'Arrows',
    icons: [
      { name: 'arrow-arc-left', icon: ArrowArcLeft },
      { name: 'arrow-arc-right', icon: ArrowArcRight },
      { name: 'arrow-bend-double-up-left', icon: ArrowBendDoubleUpLeft },
      { name: 'arrow-bend-double-up-right', icon: ArrowBendDoubleUpRight },
      { name: 'arrow-bend-down-left', icon: ArrowBendDownLeft },
      { name: 'arrow-bend-down-right', icon: ArrowBendDownRight },
      { name: 'arrow-bend-left-down', icon: ArrowBendLeftDown },
      { name: 'arrow-bend-left-up', icon: ArrowBendLeftUp },
      { name: 'arrow-bend-right-down', icon: ArrowBendRightDown },
      { name: 'arrow-bend-right-up', icon: ArrowBendRightUp },
      { name: 'arrow-bend-up-left', icon: ArrowBendUpLeft },
      { name: 'arrow-bend-up-right', icon: ArrowBendUpRight },
      { name: 'arrow-circle-down', icon: ArrowCircleDown },
      { name: 'arrow-circle-down-left', icon: ArrowCircleDownLeft },
      { name: 'arrow-circle-down-right', icon: ArrowCircleDownRight },
      { name: 'arrow-circle-left', icon: ArrowCircleLeft },
      { name: 'arrow-circle-right', icon: ArrowCircleRight },
      { name: 'arrow-circle-up', icon: ArrowCircleUp },
      { name: 'arrow-circle-up-left', icon: ArrowCircleUpLeft },
      { name: 'arrow-circle-up-right', icon: ArrowCircleUpRight },
      { name: 'arrow-clockwise', icon: ArrowClockwise },
      { name: 'arrow-counter-clockwise', icon: ArrowCounterClockwise },
      { name: 'arrow-down', icon: ArrowDown },
      { name: 'arrow-down-left', icon: ArrowDownLeft },
      { name: 'arrow-down-right', icon: ArrowDownRight },
      { name: 'arrow-elbow-down-left', icon: ArrowElbowDownLeft },
      { name: 'arrow-elbow-down-right', icon: ArrowElbowDownRight },
      { name: 'arrow-elbow-left', icon: ArrowElbowLeft },
      { name: 'arrow-elbow-left-down', icon: ArrowElbowLeftDown },
      { name: 'arrow-elbow-left-up', icon: ArrowElbowLeftUp },
      { name: 'arrow-elbow-right', icon: ArrowElbowRight },
      { name: 'arrow-elbow-right-down', icon: ArrowElbowRightDown },
      { name: 'arrow-elbow-right-up', icon: ArrowElbowRightUp },
      { name: 'arrow-elbow-up-left', icon: ArrowElbowUpLeft },
      { name: 'arrow-elbow-up-right', icon: ArrowElbowUpRight },
      { name: 'arrow-fat-down', icon: ArrowFatDown },
      { name: 'arrow-fat-left', icon: ArrowFatLeft },
      { name: 'arrow-fat-line-down', icon: ArrowFatLineDown },
      { name: 'arrow-fat-line-left', icon: ArrowFatLineLeft },
      { name: 'arrow-fat-line-right', icon: ArrowFatLineRight },
      { name: 'arrow-fat-line-up', icon: ArrowFatLineUp },
      { name: 'arrow-fat-lines-down', icon: ArrowFatLinesDown },
      { name: 'arrow-fat-lines-left', icon: ArrowFatLinesLeft },
      { name: 'arrow-fat-lines-right', icon: ArrowFatLinesRight },
      { name: 'arrow-fat-lines-up', icon: ArrowFatLinesUp },
      { name: 'arrow-fat-right', icon: ArrowFatRight },
      { name: 'arrow-fat-up', icon: ArrowFatUp },
      { name: 'arrow-left', icon: ArrowLeft },
      { name: 'arrow-line-down', icon: ArrowLineDown },
      { name: 'arrow-line-down-left', icon: ArrowLineDownLeft },
      { name: 'arrow-line-down-right', icon: ArrowLineDownRight },
      { name: 'arrow-line-left', icon: ArrowLineLeft },
      { name: 'arrow-line-right', icon: ArrowLineRight },
      { name: 'arrow-line-up', icon: ArrowLineUp },
      { name: 'arrow-line-up-left', icon: ArrowLineUpLeft },
      { name: 'arrow-line-up-right', icon: ArrowLineUpRight },
      { name: 'arrow-right', icon: ArrowRight },
      { name: 'arrow-square-down', icon: ArrowSquareDown },
      { name: 'arrow-square-down-left', icon: ArrowSquareDownLeft },
      { name: 'arrow-square-down-right', icon: ArrowSquareDownRight },
      { name: 'arrow-square-in', icon: ArrowSquareIn },
      { name: 'arrow-square-left', icon: ArrowSquareLeft },
      { name: 'arrow-square-out', icon: ArrowSquareOut },
      { name: 'arrow-square-right', icon: ArrowSquareRight },
      { name: 'arrow-square-up', icon: ArrowSquareUp },
      { name: 'arrow-square-up-left', icon: ArrowSquareUpLeft },
      { name: 'arrow-square-up-right', icon: ArrowSquareUpRight },
      { name: 'arrow-u-down-left', icon: ArrowUDownLeft },
      { name: 'arrow-u-down-right', icon: ArrowUDownRight },
      { name: 'arrow-u-left-down', icon: ArrowULeftDown },
      { name: 'arrow-u-left-up', icon: ArrowULeftUp },
      { name: 'arrow-u-right-down', icon: ArrowURightDown },
      { name: 'arrow-u-right-up', icon: ArrowURightUp },
      { name: 'arrow-u-up-left', icon: ArrowUUpLeft },
      { name: 'arrow-u-up-right', icon: ArrowUUpRight },
      { name: 'arrow-up', icon: ArrowUp },
      { name: 'arrow-up-left', icon: ArrowUpLeft },
      { name: 'arrow-up-right', icon: ArrowUpRight },
      { name: 'arrows-clockwise', icon: ArrowsClockwise },
      { name: 'arrows-counter-clockwise', icon: ArrowsCounterClockwise },
      { name: 'arrows-down-up', icon: ArrowsDownUp },
      { name: 'arrows-horizontal', icon: ArrowsHorizontal },
      { name: 'arrows-in', icon: ArrowsIn },
      { name: 'arrows-in-cardinal', icon: ArrowsInCardinal },
      { name: 'arrows-in-line-horizontal', icon: ArrowsInLineHorizontal },
      { name: 'arrows-in-line-vertical', icon: ArrowsInLineVertical },
      { name: 'arrows-in-simple', icon: ArrowsInSimple },
      { name: 'arrows-left-right', icon: ArrowsLeftRight },
      { name: 'arrows-merge', icon: ArrowsMerge },
      { name: 'arrows-out', icon: ArrowsOut },
      { name: 'arrows-out-cardinal', icon: ArrowsOutCardinal },
      { name: 'arrows-out-line-horizontal', icon: ArrowsOutLineHorizontal },
      { name: 'arrows-out-line-vertical', icon: ArrowsOutLineVertical },
      { name: 'arrows-out-simple', icon: ArrowsOutSimple },
      { name: 'arrows-split', icon: ArrowsSplit },
      { name: 'arrows-vertical', icon: ArrowsVertical },
      { name: 'caret-circle-double-down', icon: CaretCircleDoubleDown },
      { name: 'caret-circle-double-left', icon: CaretCircleDoubleLeft },
      { name: 'caret-circle-double-right', icon: CaretCircleDoubleRight },
      { name: 'caret-circle-double-up', icon: CaretCircleDoubleUp },
      { name: 'caret-circle-down', icon: CaretCircleDown },
      { name: 'caret-circle-left', icon: CaretCircleLeft },
      { name: 'caret-circle-right', icon: CaretCircleRight },
      { name: 'caret-circle-up', icon: CaretCircleUp },
      { name: 'caret-circle-up-down', icon: CaretCircleUpDown },
      { name: 'caret-double-down', icon: CaretDoubleDown },
      { name: 'caret-double-left', icon: CaretDoubleLeft },
      { name: 'caret-double-right', icon: CaretDoubleRight },
      { name: 'caret-double-up', icon: CaretDoubleUp },
      { name: 'caret-down', icon: CaretDown },
      { name: 'caret-left', icon: CaretLeft },
      { name: 'caret-line-down', icon: CaretLineDown },
      { name: 'caret-line-left', icon: CaretLineLeft },
      { name: 'caret-line-right', icon: CaretLineRight },
      { name: 'caret-line-up', icon: CaretLineUp },
      { name: 'caret-right', icon: CaretRight },
      { name: 'caret-up', icon: CaretUp },
      { name: 'caret-up-down', icon: CaretUpDown },
      { name: 'flow-arrow', icon: FlowArrow },
      { name: 'recycle', icon: Recycle },
      { name: 'share-fat', icon: ShareFat },
      { name: 'split-horizontal', icon: SplitHorizontal },
      { name: 'split-vertical', icon: SplitVertical },
      { name: 'vector-three', icon: VectorThree },
      { name: 'vector-two', icon: VectorTwo },
    ],
  },
];

// 扁平化列表用于快速查找
export const ALL_ICONS_FULL = ICON_CATEGORIES_FULL.flatMap(c => c.icons);

// 图标名称到组件的映射
export const ICON_MAP_FULL = new Map<string, PhosphorIcon>(
  ALL_ICONS_FULL.map(({ name, icon }) => [name, icon])
);

// 根据名称获取图标
export function getIconByNameFull(name: string): PhosphorIcon | undefined {
  return ICON_MAP_FULL.get(name);
}
