/**
 * Progress module icon library - based on lucide-react
 */

import type { LucideIcon } from 'lucide-react';

export interface IconDefinition {
  name: string;
  icon: LucideIcon;
}

export interface IconCategory {
  name: string;
  icons: IconDefinition[];
}

import {
  PersonStanding,
  Footprints,
  Waves,
  Bike,
  Dumbbell,
  Mountain,
  Flame,
  Tent,
  Backpack,
  Compass,
  Map,
  Trophy,
  Target,
  Gamepad2,
  Puzzle,
  Dice5,
  Spade,
  Music,
  Mic,
  Headphones,
  Guitar,
  Piano,
  Brush,
  Palette,
  Pencil,
  Camera,
  Image,
  Film,
  Book,
  Bookmark,
  NotebookPen,
  Newspaper,
  FileText,
} from 'lucide-react';

export const activityIcons: IconCategory = {
  name: 'Activity',
  icons: [
    { name: 'run', icon: PersonStanding },
    { name: 'walk', icon: Footprints },
    { name: 'swimming', icon: Waves },
    { name: 'bike', icon: Bike },
    { name: 'barbell', icon: Dumbbell },
    { name: 'mountain', icon: Mountain },
    { name: 'campfire', icon: Flame },
    { name: 'tent', icon: Tent },
    { name: 'backpack', icon: Backpack },
    { name: 'compass', icon: Compass },
    { name: 'map', icon: Map },
    { name: 'trophy', icon: Trophy },
    { name: 'target', icon: Target },
    { name: 'gamepad', icon: Gamepad2 },
    { name: 'puzzle', icon: Puzzle },
    { name: 'dice', icon: Dice5 },
    { name: 'cards', icon: Spade },
    { name: 'music', icon: Music },
    { name: 'microphone', icon: Mic },
    { name: 'headphones', icon: Headphones },
    { name: 'guitar', icon: Guitar },
    { name: 'piano', icon: Piano },
    { name: 'brush', icon: Brush },
    { name: 'palette', icon: Palette },
    { name: 'pencil', icon: Pencil },
    { name: 'camera', icon: Camera },
    { name: 'photo', icon: Image },
    { name: 'movie', icon: Film },
    { name: 'book', icon: Book },
    { name: 'bookmark', icon: Bookmark },
    { name: 'notebook', icon: NotebookPen },
    { name: 'news', icon: Newspaper },
    { name: 'article', icon: FileText },
  ],
};


import {
  Heart,
  HeartPulse,
  Pill,
  Cross,
  Stethoscope,
  Syringe,
  Eye,
  Ear,
  Brain,
  Bone,
  Droplet,
  Moon,
  Sun,
  CloudRain,
  Snowflake,
  Wind,
  Thermometer,
  Scale,
  Ruler,
  Clock,
  AlarmClock,
  Calendar,
  CalendarDays,
  CalendarClock,
  Hourglass,
  Timer,
} from 'lucide-react';

export const healthIcons: IconCategory = {
  name: 'Health',
  icons: [
    { name: 'heart', icon: Heart },
    { name: 'heartbeat', icon: HeartPulse },
    { name: 'pill', icon: Pill },
    { name: 'firstaid', icon: Cross },
    { name: 'stethoscope', icon: Stethoscope },
    { name: 'vaccine', icon: Syringe },
    { name: 'eye', icon: Eye },
    { name: 'ear', icon: Ear },
    { name: 'brain', icon: Brain },
    { name: 'bone', icon: Bone },
    { name: 'droplet', icon: Droplet },
    { name: 'flame', icon: Flame },
    { name: 'moon', icon: Moon },
    { name: 'sun', icon: Sun },
    { name: 'rain', icon: CloudRain },
    { name: 'snowflake', icon: Snowflake },
    { name: 'wind', icon: Wind },
    { name: 'thermometer', icon: Thermometer },
    { name: 'scale', icon: Scale },
    { name: 'ruler', icon: Ruler },
    { name: 'clock', icon: Clock },
    { name: 'alarm', icon: AlarmClock },
    { name: 'calendar', icon: Calendar },
    { name: 'calendarevent', icon: CalendarDays },
    { name: 'calendartime', icon: CalendarClock },
    { name: 'hourglass', icon: Hourglass },
    { name: 'timeline', icon: Timer },
  ],
};

import {
  Briefcase,
  Building,
  Building2,
  Home,
  HomeIcon,
  Armchair,
  Lamp,
  Laptop,
  Monitor,
  Smartphone,
  Tablet,
  Printer,
  Keyboard,
  Mouse,
  Server,
  Database,
  Cloud,
  Wifi,
  Router,
  Cpu,
  Code,
  Terminal,
  Bug,
  GitBranch,
  FileCode,
  Folder,
  FolderOpen,
  File,
} from 'lucide-react';

export const workIcons: IconCategory = {
  name: 'Work',
  icons: [
    { name: 'briefcase', icon: Briefcase },
    { name: 'building', icon: Building },
    { name: 'skyscraper', icon: Building2 },
    { name: 'home', icon: Home },
    { name: 'homeheart', icon: HomeIcon },
    { name: 'armchair', icon: Armchair },
    { name: 'lamp', icon: Lamp },
    { name: 'laptop', icon: Laptop },
    { name: 'desktop', icon: Monitor },
    { name: 'mobile', icon: Smartphone },
    { name: 'tablet', icon: Tablet },
    { name: 'printer', icon: Printer },
    { name: 'keyboard', icon: Keyboard },
    { name: 'mouse', icon: Mouse },
    { name: 'server', icon: Server },
    { name: 'database', icon: Database },
    { name: 'cloud', icon: Cloud },
    { name: 'wifi', icon: Wifi },
    { name: 'router', icon: Router },
    { name: 'cpu', icon: Cpu },
    { name: 'code', icon: Code },
    { name: 'terminal', icon: Terminal },
    { name: 'bug', icon: Bug },
    { name: 'gitbranch', icon: GitBranch },
    { name: 'filecode', icon: FileCode },
    { name: 'folder', icon: Folder },
    { name: 'folderopen', icon: FolderOpen },
    { name: 'file', icon: File },
    { name: 'filetext', icon: FileText },
  ],
};


import {
  Coffee,
  CupSoda,
  GlassWater,
  Wine,
  Milk,
  Beer,
  ChefHat,
  Microwave,
  Refrigerator,
  Egg,
  Beef,
  Fish,
  Apple,
  Carrot,
  Salad,
  Soup,
  Pizza,
  Sandwich,
  IceCream,
  Cake,
  Cookie,
  Candy,
} from 'lucide-react';

export const foodIcons: IconCategory = {
  name: 'Food',
  icons: [
    { name: 'coffee', icon: Coffee },
    { name: 'cup', icon: CupSoda },
    { name: 'glass', icon: GlassWater },
    { name: 'wine', icon: Wine },
    { name: 'milk', icon: Milk },
    { name: 'beer', icon: Beer },
    { name: 'chef', icon: ChefHat },
    { name: 'microwave', icon: Microwave },
    { name: 'fridge', icon: Refrigerator },
    { name: 'egg', icon: Egg },
    { name: 'meat', icon: Beef },
    { name: 'fish', icon: Fish },
    { name: 'apple', icon: Apple },
    { name: 'carrot', icon: Carrot },
    { name: 'salad', icon: Salad },
    { name: 'soup', icon: Soup },
    { name: 'pizza', icon: Pizza },
    { name: 'burger', icon: Sandwich },
    { name: 'icecream', icon: IceCream },
    { name: 'cake', icon: Cake },
    { name: 'cookie', icon: Cookie },
    { name: 'candy', icon: Candy },
  ],
};

import {
  Banknote,
  Coins,
  CircleDollarSign,
  Euro,
  JapaneseYen,
  PoundSterling,
  Bitcoin,
  Wallet,
  CreditCard,
  Receipt,
  PiggyBank,
  ChartLine,
  ChartBar,
  ChartPie,
  ChartSpline,
  TrendingUp,
  TrendingDown,
  Percent,
  Calculator,
  Plus,
  Minus,
  X,
  Divide,
  Equal,
  Infinity,
} from 'lucide-react';

export const financeIcons: IconCategory = {
  name: 'Finance',
  icons: [
    { name: 'cash', icon: Banknote },
    { name: 'coins', icon: Coins },
    { name: 'dollar', icon: CircleDollarSign },
    { name: 'euro', icon: Euro },
    { name: 'yen', icon: JapaneseYen },
    { name: 'pound', icon: PoundSterling },
    { name: 'bitcoin', icon: Bitcoin },
    { name: 'wallet', icon: Wallet },
    { name: 'creditcard', icon: CreditCard },
    { name: 'receipt', icon: Receipt },
    { name: 'piggy', icon: PiggyBank },
    { name: 'chartline', icon: ChartLine },
    { name: 'chartbar', icon: ChartBar },
    { name: 'chartpie', icon: ChartPie },
    { name: 'chartdots', icon: ChartSpline },
    { name: 'trendingup', icon: TrendingUp },
    { name: 'trendingdown', icon: TrendingDown },
    { name: 'percentage', icon: Percent },
    { name: 'calculator', icon: Calculator },
    { name: 'plus', icon: Plus },
    { name: 'minus', icon: Minus },
    { name: 'multiply', icon: X },
    { name: 'divide', icon: Divide },
    { name: 'equal', icon: Equal },
    { name: 'infinity', icon: Infinity },
  ],
};


import {
  User,
  Users,
  UsersRound,
  UserCheck,
  UserPlus,
  MessageSquare,
  MessagesSquare,
  MessageCircle,
  Mail,
  MailOpen,
  Send,
  Phone,
  PhoneCall,
  Video,
  Facebook,
  Instagram,
  Twitter,
  Youtube,
  Linkedin,
  Github,
  MessageCircleMore,
  Globe,
  Share2,
} from 'lucide-react';

export const socialIcons: IconCategory = {
  name: 'Social',
  icons: [
    { name: 'user', icon: User },
    { name: 'users', icon: Users },
    { name: 'usersgroup', icon: UsersRound },
    { name: 'usercheck', icon: UserCheck },
    { name: 'userplus', icon: UserPlus },
    { name: 'message', icon: MessageSquare },
    { name: 'messages', icon: MessagesSquare },
    { name: 'messagecircle', icon: MessageCircle },
    { name: 'mail', icon: Mail },
    { name: 'mailopened', icon: MailOpen },
    { name: 'send', icon: Send },
    { name: 'phone', icon: Phone },
    { name: 'phonecall', icon: PhoneCall },
    { name: 'video', icon: Video },
    { name: 'facebook', icon: Facebook },
    { name: 'instagram', icon: Instagram },
    { name: 'twitter', icon: Twitter },
    { name: 'youtube', icon: Youtube },
    { name: 'linkedin', icon: Linkedin },
    { name: 'github', icon: Github },
    { name: 'discord', icon: MessageCircleMore },
    { name: 'world', icon: Globe },
    { name: 'share', icon: Share2 },
  ],
};

import {
  TreePine,
  Trees,
  Sprout,
  Flower,
  Flower2,
  Leaf,
  Dog,
  Cat,
  Bird,
  Feather,
  PawPrint,
  Bug as BugNature,
  Star,
  Sparkles,
  Rocket,
  Atom,
  Recycle,
} from 'lucide-react';

export const natureIcons: IconCategory = {
  name: 'Nature',
  icons: [
    { name: 'tree', icon: TreePine },
    { name: 'trees', icon: Trees },
    { name: 'plant', icon: Sprout },
    { name: 'flower', icon: Flower },
    { name: 'flower2', icon: Flower2 },
    { name: 'leaf', icon: Leaf },
    { name: 'dog', icon: Dog },
    { name: 'cat', icon: Cat },
    { name: 'bird', icon: Bird },
    { name: 'feather', icon: Feather },
    { name: 'paw', icon: PawPrint },
    { name: 'insect', icon: BugNature },
    { name: 'star', icon: Star },
    { name: 'sparkles', icon: Sparkles },
    { name: 'rocket', icon: Rocket },
    { name: 'atom', icon: Atom },
    { name: 'recycle', icon: Recycle },
  ],
};


import {
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Sailboat,
  Bike as Motorbike,
  Truck,
  Ambulance,
  ParkingCircle,
  Fuel,
  BatteryCharging,
  TrafficCone,
  MapPin,
  MapPinned,
  Navigation,
  Flag,
  Umbrella,
  Castle,
  Church,
} from 'lucide-react';

export const travelIcons: IconCategory = {
  name: 'Travel',
  icons: [
    { name: 'car', icon: Car },
    { name: 'bus', icon: Bus },
    { name: 'train', icon: Train },
    { name: 'plane', icon: Plane },
    { name: 'ship', icon: Ship },
    { name: 'sailboat', icon: Sailboat },
    { name: 'motorbike', icon: Motorbike },
    { name: 'truck', icon: Truck },
    { name: 'ambulance', icon: Ambulance },
    { name: 'parking', icon: ParkingCircle },
    { name: 'gasstation', icon: Fuel },
    { name: 'charging', icon: BatteryCharging },
    { name: 'trafficlights', icon: TrafficCone },
    { name: 'mappin', icon: MapPin },
    { name: 'mappinfilled', icon: MapPinned },
    { name: 'navigation', icon: Navigation },
    { name: 'globe', icon: Globe },
    { name: 'flag', icon: Flag },
    { name: 'umbrella', icon: Umbrella },
    { name: 'castle', icon: Castle },
    { name: 'church', icon: Church },
  ],
};

import {
  Check,
  CircleCheck,
  CircleCheckBig,
  SquareCheck,
  ListChecks,
  CircleDot,
  Circle,
  CircleX,
  CircleAlert,
  TriangleAlert,
  Info,
  HelpCircle,
  Bell,
  BellRing,
  BellOff,
  Lock,
  LockOpen,
  Shield,
  ShieldCheck,
  EyeOff,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Laugh,
} from 'lucide-react';

export const statusIcons: IconCategory = {
  name: 'Status',
  icons: [
    { name: 'check', icon: Check },
    { name: 'circlecheck', icon: CircleCheck },
    { name: 'circlecheckfilled', icon: CircleCheckBig },
    { name: 'squarecheck', icon: SquareCheck },
    { name: 'listcheck', icon: ListChecks },
    { name: 'circledot', icon: CircleDot },
    { name: 'circle', icon: Circle },
    { name: 'circlex', icon: CircleX },
    { name: 'alertcircle', icon: CircleAlert },
    { name: 'alerttriangle', icon: TriangleAlert },
    { name: 'infocircle', icon: Info },
    { name: 'help', icon: HelpCircle },
    { name: 'bell', icon: Bell },
    { name: 'bellringing', icon: BellRing },
    { name: 'belloff', icon: BellOff },
    { name: 'lock', icon: Lock },
    { name: 'lockopen', icon: LockOpen },
    { name: 'shield', icon: Shield },
    { name: 'shieldcheck', icon: ShieldCheck },
    { name: 'eyeoff', icon: EyeOff },
    { name: 'thumbup', icon: ThumbsUp },
    { name: 'thumbdown', icon: ThumbsDown },
    { name: 'moodsmile', icon: Smile },
    { name: 'moodsad', icon: Frown },
    { name: 'moodhappy', icon: Laugh },
  ],
};


import {
  Gift,
  PartyPopper,
  Wand2,
  Crown,
  Award,
  Medal,
  Gem,
  KeyRound,
  Lightbulb,
  LightbulbOff,
  Glasses,
  Watch,
  BatteryFull,
  Plug,
  Zap,
  Anchor,
  LifeBuoy,
} from 'lucide-react';

export const objectsIcons: IconCategory = {
  name: 'Objects',
  icons: [
    { name: 'gift', icon: Gift },
    { name: 'confetti', icon: PartyPopper },
    { name: 'sparkles', icon: Sparkles },
    { name: 'wand', icon: Wand2 },
    { name: 'crown', icon: Crown },
    { name: 'award', icon: Award },
    { name: 'trophy', icon: Trophy },
    { name: 'medal', icon: Medal },
    { name: 'gem', icon: Gem },
    { name: 'key', icon: KeyRound },
    { name: 'bulb', icon: Lightbulb },
    { name: 'bulboff', icon: LightbulbOff },
    { name: 'glasses', icon: Glasses },
    { name: 'watch', icon: Watch },
    { name: 'batteryfull', icon: BatteryFull },
    { name: 'plug', icon: Plug },
    { name: 'bolt', icon: Zap },
    { name: 'zap', icon: Zap },
    { name: 'anchor', icon: Anchor },
    { name: 'lifebuoy', icon: LifeBuoy },
  ],
};

export const ICON_CATEGORIES_FULL: IconCategory[] = [
  activityIcons,
  healthIcons,
  workIcons,
  foodIcons,
  financeIcons,
  socialIcons,
  natureIcons,
  travelIcons,
  statusIcons,
  objectsIcons,
];

export const ALL_ICONS_FULL: IconDefinition[] = ICON_CATEGORIES_FULL.flatMap(cat => cat.icons);

// Build icon map using Object.fromEntries for better type inference
const iconMapObject = Object.fromEntries(
  ALL_ICONS_FULL.map(({ name, icon }) => [name, icon])
) as Record<string, LucideIcon>;

export function getIconByNameFull(name: string): LucideIcon | undefined {
  return iconMapObject[name];
}

// Export for backward compatibility
export const ICON_MAP_FULL = {
  get: (name: string) => iconMapObject[name],
  has: (name: string) => name in iconMapObject,
};
