/**
 * Progress module icon library - based on @tabler/icons-react
 */

import type { Icon as TablerIcon } from '@tabler/icons-react';

export interface IconDefinition {
  name: string;
  icon: TablerIcon;
}

export interface IconCategory {
  name: string;
  icons: IconDefinition[];
}

import {
  IconRun,
  IconWalk,
  IconSwimming,
  IconBike,
  IconYoga,
  IconStretching,
  IconBarbell,
  IconTreadmill,
  IconMountain,
  IconCampfire,
  IconTent,
  IconBackpack,
  IconCompass,
  IconMap,
  IconBallFootball,
  IconBallBasketball,
  IconBallTennis,
  IconBallVolleyball,
  IconGolf,
  IconBowling,
  IconChess,
  IconPuzzle,
  IconDice,
  IconCards,
  IconDeviceGamepad2,
  IconMusic,
  IconMicrophone,
  IconHeadphones,
  IconMusic as IconGuitar,
  IconPiano,
  IconBrush,
  IconPalette,
  IconPencil,
  IconCamera,
  IconPhoto,
  IconMovie,
  IconBook,
  IconBookmark,
  IconNotebook,
  IconNews,
  IconArticle,
} from '@tabler/icons-react';

export const activityIcons: IconCategory = {
  name: 'Activity',
  icons: [
    { name: 'run', icon: IconRun },
    { name: 'walk', icon: IconWalk },
    { name: 'swimming', icon: IconSwimming },
    { name: 'bike', icon: IconBike },
    { name: 'yoga', icon: IconYoga },
    { name: 'stretching', icon: IconStretching },
    { name: 'barbell', icon: IconBarbell },
    { name: 'treadmill', icon: IconTreadmill },
    { name: 'mountain', icon: IconMountain },
    { name: 'campfire', icon: IconCampfire },
    { name: 'tent', icon: IconTent },
    { name: 'backpack', icon: IconBackpack },
    { name: 'compass', icon: IconCompass },
    { name: 'map', icon: IconMap },
    { name: 'football', icon: IconBallFootball },
    { name: 'basketball', icon: IconBallBasketball },
    { name: 'tennis', icon: IconBallTennis },
    { name: 'volleyball', icon: IconBallVolleyball },
    { name: 'golf', icon: IconGolf },
    { name: 'bowling', icon: IconBowling },
    { name: 'chess', icon: IconChess },
    { name: 'puzzle', icon: IconPuzzle },
    { name: 'dice', icon: IconDice },
    { name: 'cards', icon: IconCards },
    { name: 'gamepad', icon: IconDeviceGamepad2 },
    { name: 'music', icon: IconMusic },
    { name: 'microphone', icon: IconMicrophone },
    { name: 'headphones', icon: IconHeadphones },
    { name: 'guitar', icon: IconGuitar },
    { name: 'piano', icon: IconPiano },
    { name: 'brush', icon: IconBrush },
    { name: 'palette', icon: IconPalette },
    { name: 'pencil', icon: IconPencil },
    { name: 'camera', icon: IconCamera },
    { name: 'photo', icon: IconPhoto },
    { name: 'movie', icon: IconMovie },
    { name: 'book', icon: IconBook },
    { name: 'bookmark', icon: IconBookmark },
    { name: 'notebook', icon: IconNotebook },
    { name: 'news', icon: IconNews },
    { name: 'article', icon: IconArticle },
  ],
};


import {
  IconHeart,
  IconHeartbeat,
  IconPill,
  IconFirstAidKit,
  IconStethoscope,
  IconVaccine,
  IconMedicineSyrup,
  IconDental,
  IconEye,
  IconEar,
  IconLungs,
  IconBrain,
  IconBone,
  IconDroplet,
  IconFlame,
  IconMoon,
  IconSun,
  IconCloudRain,
  IconSnowflake,
  IconWind,
  IconThermometer,
  IconScale,
  IconRuler,
  IconClock,
  IconAlarm,
  IconCalendar,
  IconCalendarEvent,
  IconCalendarTime,
  IconHourglass,
  IconTimeline,
} from '@tabler/icons-react';

export const healthIcons: IconCategory = {
  name: 'Health',
  icons: [
    { name: 'heart', icon: IconHeart },
    { name: 'heartbeat', icon: IconHeartbeat },
    { name: 'pill', icon: IconPill },
    { name: 'firstaid', icon: IconFirstAidKit },
    { name: 'stethoscope', icon: IconStethoscope },
    { name: 'vaccine', icon: IconVaccine },
    { name: 'medicine', icon: IconMedicineSyrup },
    { name: 'dental', icon: IconDental },
    { name: 'eye', icon: IconEye },
    { name: 'ear', icon: IconEar },
    { name: 'lungs', icon: IconLungs },
    { name: 'brain', icon: IconBrain },
    { name: 'bone', icon: IconBone },
    { name: 'droplet', icon: IconDroplet },
    { name: 'flame', icon: IconFlame },
    { name: 'moon', icon: IconMoon },
    { name: 'sun', icon: IconSun },
    { name: 'rain', icon: IconCloudRain },
    { name: 'snowflake', icon: IconSnowflake },
    { name: 'wind', icon: IconWind },
    { name: 'thermometer', icon: IconThermometer },
    { name: 'scale', icon: IconScale },
    { name: 'ruler', icon: IconRuler },
    { name: 'clock', icon: IconClock },
    { name: 'alarm', icon: IconAlarm },
    { name: 'calendar', icon: IconCalendar },
    { name: 'calendarevent', icon: IconCalendarEvent },
    { name: 'calendartime', icon: IconCalendarTime },
    { name: 'hourglass', icon: IconHourglass },
    { name: 'timeline', icon: IconTimeline },
  ],
};


import {
  IconBriefcase,
  IconBuilding,
  IconBuildingSkyscraper,
  IconHome,
  IconHomeHeart,
  IconDesk,
  IconArmchair,
  IconLamp,
  IconDeviceLaptop,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDeviceTablet,
  IconPrinter,
  IconKeyboard,
  IconMouse,
  IconServer,
  IconDatabase,
  IconCloud,
  IconWifi,
  IconRouter,
  IconCpu,
  IconCode,
  IconTerminal,
  IconBug,
  IconGitBranch,
  IconApi,
  IconFileCode,
  IconFolder,
  IconFolderOpen,
  IconFile,
  IconFileText,
} from '@tabler/icons-react';

export const workIcons: IconCategory = {
  name: 'Work',
  icons: [
    { name: 'briefcase', icon: IconBriefcase },
    { name: 'building', icon: IconBuilding },
    { name: 'skyscraper', icon: IconBuildingSkyscraper },
    { name: 'home', icon: IconHome },
    { name: 'homeheart', icon: IconHomeHeart },
    { name: 'desk', icon: IconDesk },
    { name: 'armchair', icon: IconArmchair },
    { name: 'lamp', icon: IconLamp },
    { name: 'laptop', icon: IconDeviceLaptop },
    { name: 'desktop', icon: IconDeviceDesktop },
    { name: 'mobile', icon: IconDeviceMobile },
    { name: 'tablet', icon: IconDeviceTablet },
    { name: 'printer', icon: IconPrinter },
    { name: 'keyboard', icon: IconKeyboard },
    { name: 'mouse', icon: IconMouse },
    { name: 'server', icon: IconServer },
    { name: 'database', icon: IconDatabase },
    { name: 'cloud', icon: IconCloud },
    { name: 'wifi', icon: IconWifi },
    { name: 'router', icon: IconRouter },
    { name: 'cpu', icon: IconCpu },
    { name: 'code', icon: IconCode },
    { name: 'terminal', icon: IconTerminal },
    { name: 'bug', icon: IconBug },
    { name: 'gitbranch', icon: IconGitBranch },
    { name: 'api', icon: IconApi },
    { name: 'filecode', icon: IconFileCode },
    { name: 'folder', icon: IconFolder },
    { name: 'folderopen', icon: IconFolderOpen },
    { name: 'file', icon: IconFile },
    { name: 'filetext', icon: IconFileText },
  ],
};


import {
  IconCoffee,
  IconCup,
  IconGlass,
  IconBottle,
  IconMilk,
  IconBeer,
  IconGlassFull,
  IconToolsKitchen2,
  IconChefHat,
  IconGrill,
  IconMicrowave,
  IconFridge,
  IconEgg,
  IconMeat,
  IconFish,
  IconCheese,
  IconBread,
  IconApple,
  IconCarrot,
  IconPepper,
  IconMushroom,
  IconSalad,
  IconSoup,
  IconPizza,
  IconBurger,
  IconIceCream,
  IconCake,
  IconCookie,
  IconCandy,
} from '@tabler/icons-react';

export const foodIcons: IconCategory = {
  name: 'Food',
  icons: [
    { name: 'coffee', icon: IconCoffee },
    { name: 'cup', icon: IconCup },
    { name: 'glass', icon: IconGlass },
    { name: 'bottle', icon: IconBottle },
    { name: 'milk', icon: IconMilk },
    { name: 'beer', icon: IconBeer },
    { name: 'wine', icon: IconGlassFull },
    { name: 'kitchen', icon: IconToolsKitchen2 },
    { name: 'chef', icon: IconChefHat },
    { name: 'grill', icon: IconGrill },
    { name: 'microwave', icon: IconMicrowave },
    { name: 'fridge', icon: IconFridge },
    { name: 'egg', icon: IconEgg },
    { name: 'meat', icon: IconMeat },
    { name: 'fish', icon: IconFish },
    { name: 'cheese', icon: IconCheese },
    { name: 'bread', icon: IconBread },
    { name: 'apple', icon: IconApple },
    { name: 'carrot', icon: IconCarrot },
    { name: 'pepper', icon: IconPepper },
    { name: 'mushroom', icon: IconMushroom },
    { name: 'salad', icon: IconSalad },
    { name: 'soup', icon: IconSoup },
    { name: 'pizza', icon: IconPizza },
    { name: 'burger', icon: IconBurger },
    { name: 'fries', icon: IconBurger },
    { name: 'icecream', icon: IconIceCream },
    { name: 'cake', icon: IconCake },
    { name: 'cookie', icon: IconCookie },
    { name: 'candy', icon: IconCandy },
  ],
};


import {
  IconCash,
  IconCoin,
  IconCoins,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconCurrencyYen,
  IconCurrencyPound,
  IconCurrencyBitcoin,
  IconWallet,
  IconCreditCard,
  IconReceipt,
  IconReportMoney,
  IconPigMoney,
  IconMoneybag,
  IconChartLine,
  IconChartBar,
  IconChartPie,
  IconChartDots,
  IconChartArrowsVertical,
  IconTrendingUp,
  IconTrendingDown,
  IconPercentage,
  IconCalculator,
  IconMathSymbols,
  IconPlus,
  IconMinus,
  IconX,
  IconDivide,
  IconEqual,
  IconInfinity,
} from '@tabler/icons-react';

export const financeIcons: IconCategory = {
  name: 'Finance',
  icons: [
    { name: 'cash', icon: IconCash },
    { name: 'coin', icon: IconCoin },
    { name: 'coins', icon: IconCoins },
    { name: 'dollar', icon: IconCurrencyDollar },
    { name: 'euro', icon: IconCurrencyEuro },
    { name: 'yen', icon: IconCurrencyYen },
    { name: 'pound', icon: IconCurrencyPound },
    { name: 'bitcoin', icon: IconCurrencyBitcoin },
    { name: 'wallet', icon: IconWallet },
    { name: 'creditcard', icon: IconCreditCard },
    { name: 'receipt', icon: IconReceipt },
    { name: 'report', icon: IconReportMoney },
    { name: 'piggy', icon: IconPigMoney },
    { name: 'moneybag', icon: IconMoneybag },
    { name: 'chartline', icon: IconChartLine },
    { name: 'chartbar', icon: IconChartBar },
    { name: 'chartpie', icon: IconChartPie },
    { name: 'chartdots', icon: IconChartDots },
    { name: 'chartarrows', icon: IconChartArrowsVertical },
    { name: 'trendingup', icon: IconTrendingUp },
    { name: 'trendingdown', icon: IconTrendingDown },
    { name: 'percentage', icon: IconPercentage },
    { name: 'calculator', icon: IconCalculator },
    { name: 'math', icon: IconMathSymbols },
    { name: 'plus', icon: IconPlus },
    { name: 'minus', icon: IconMinus },
    { name: 'multiply', icon: IconX },
    { name: 'divide', icon: IconDivide },
    { name: 'equal', icon: IconEqual },
    { name: 'infinity', icon: IconInfinity },
  ],
};


import {
  IconUser,
  IconUsers,
  IconUsersGroup,
  IconFriends,
  IconUserHeart,
  IconUserStar,
  IconUserCheck,
  IconUserPlus,
  IconMessage,
  IconMessages,
  IconMessageCircle,
  IconMail,
  IconMailOpened,
  IconSend,
  IconPhone,
  IconPhoneCall,
  IconVideo,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandX,
  IconBrandYoutube,
  IconBrandTiktok,
  IconBrandLinkedin,
  IconBrandGithub,
  IconBrandDiscord,
  IconBrandSlack,
  IconBrandTelegram,
  IconBrandWhatsapp,
  IconWorld,
  IconShare,
} from '@tabler/icons-react';

export const socialIcons: IconCategory = {
  name: 'Social',
  icons: [
    { name: 'user', icon: IconUser },
    { name: 'users', icon: IconUsers },
    { name: 'usersgroup', icon: IconUsersGroup },
    { name: 'friends', icon: IconFriends },
    { name: 'userheart', icon: IconUserHeart },
    { name: 'userstar', icon: IconUserStar },
    { name: 'usercheck', icon: IconUserCheck },
    { name: 'userplus', icon: IconUserPlus },
    { name: 'message', icon: IconMessage },
    { name: 'messages', icon: IconMessages },
    { name: 'messagecircle', icon: IconMessageCircle },
    { name: 'mail', icon: IconMail },
    { name: 'mailopened', icon: IconMailOpened },
    { name: 'send', icon: IconSend },
    { name: 'phone', icon: IconPhone },
    { name: 'phonecall', icon: IconPhoneCall },
    { name: 'video', icon: IconVideo },
    { name: 'facebook', icon: IconBrandFacebook },
    { name: 'instagram', icon: IconBrandInstagram },
    { name: 'twitter', icon: IconBrandX },
    { name: 'youtube', icon: IconBrandYoutube },
    { name: 'tiktok', icon: IconBrandTiktok },
    { name: 'linkedin', icon: IconBrandLinkedin },
    { name: 'github', icon: IconBrandGithub },
    { name: 'discord', icon: IconBrandDiscord },
    { name: 'slack', icon: IconBrandSlack },
    { name: 'telegram', icon: IconBrandTelegram },
    { name: 'whatsapp', icon: IconBrandWhatsapp },
    { name: 'world', icon: IconWorld },
    { name: 'share', icon: IconShare },
  ],
};


import {
  IconTree,
  IconTrees,
  IconPlant,
  IconPlant2,
  IconFlower,
  IconLeaf,
  IconSeeding,
  IconCactus,
  IconGrain,
  IconDog,
  IconCat,
  IconFishHook,
  IconFeather,
  IconPaw,
  IconBug as IconBugNature,
  IconSpider,
  IconButterfly,
  IconBat,
  IconFish as IconTurtleAlt,
  IconStar,
  IconStars,
  IconMeteor,
  IconPlanet,
  IconRocket,
  IconUfo,
  IconAlien,
  IconAtom,
  IconRadioactive,
  IconRecycle,
} from '@tabler/icons-react';

export const natureIcons: IconCategory = {
  name: 'Nature',
  icons: [
    { name: 'tree', icon: IconTree },
    { name: 'trees', icon: IconTrees },
    { name: 'plant', icon: IconPlant },
    { name: 'plant2', icon: IconPlant2 },
    { name: 'flower', icon: IconFlower },
    { name: 'leaf', icon: IconLeaf },
    { name: 'seeding', icon: IconSeeding },
    { name: 'cactus', icon: IconCactus },
    { name: 'grain', icon: IconGrain },
    { name: 'dog', icon: IconDog },
    { name: 'cat', icon: IconCat },
    { name: 'fishhook', icon: IconFishHook },
    { name: 'feather', icon: IconFeather },
    { name: 'paw', icon: IconPaw },
    { name: 'insect', icon: IconBugNature },
    { name: 'spider', icon: IconSpider },
    { name: 'butterfly', icon: IconButterfly },
    { name: 'bat', icon: IconBat },
    { name: 'snake', icon: IconBugNature },
    { name: 'turtle', icon: IconTurtleAlt },
    { name: 'star', icon: IconStar },
    { name: 'stars', icon: IconStars },
    { name: 'meteor', icon: IconMeteor },
    { name: 'planet', icon: IconPlanet },
    { name: 'rocket', icon: IconRocket },
    { name: 'ufo', icon: IconUfo },
    { name: 'alien', icon: IconAlien },
    { name: 'atom', icon: IconAtom },
    { name: 'radioactive', icon: IconRadioactive },
    { name: 'recycle', icon: IconRecycle },
  ],
};


import {
  IconCar,
  IconBus,
  IconTrain,
  IconPlane,
  IconHelicopter,
  IconShip,
  IconSailboat,
  IconMotorbike,
  IconScooter,
  IconTractor as IconTruck,
  IconAmbulance,
  IconFiretruck,
  IconCaravan,
  IconParking,
  IconGasStation,
  IconChargingPile,
  IconRoad,
  IconTrafficLights,
  IconMapPin,
  IconMapPinFilled,
  IconLocation,
  IconCurrentLocation,
  IconNavigation,
  IconGlobe,
  IconFlag,
  IconBeach,
  IconPool,
  IconParkingCircle,
  IconBuildingCastle,
  IconBuildingChurch,
} from '@tabler/icons-react';

export const travelIcons: IconCategory = {
  name: 'Travel',
  icons: [
    { name: 'car', icon: IconCar },
    { name: 'bus', icon: IconBus },
    { name: 'train', icon: IconTrain },
    { name: 'plane', icon: IconPlane },
    { name: 'helicopter', icon: IconHelicopter },
    { name: 'ship', icon: IconShip },
    { name: 'sailboat', icon: IconSailboat },
    { name: 'motorbike', icon: IconMotorbike },
    { name: 'scooter', icon: IconScooter },
    { name: 'truck', icon: IconTruck },
    { name: 'ambulance', icon: IconAmbulance },
    { name: 'firetruck', icon: IconFiretruck },
    { name: 'caravan', icon: IconCaravan },
    { name: 'parking', icon: IconParking },
    { name: 'gasstation', icon: IconGasStation },
    { name: 'charging', icon: IconChargingPile },
    { name: 'road', icon: IconRoad },
    { name: 'trafficlights', icon: IconTrafficLights },
    { name: 'mappin', icon: IconMapPin },
    { name: 'mappinfilled', icon: IconMapPinFilled },
    { name: 'location', icon: IconLocation },
    { name: 'currentlocation', icon: IconCurrentLocation },
    { name: 'navigation', icon: IconNavigation },
    { name: 'globe', icon: IconGlobe },
    { name: 'flag', icon: IconFlag },
    { name: 'beach', icon: IconBeach },
    { name: 'pool', icon: IconPool },
    { name: 'parkingcircle', icon: IconParkingCircle },
    { name: 'castle', icon: IconBuildingCastle },
    { name: 'church', icon: IconBuildingChurch },
  ],
};


import {
  IconCheck,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconSquareCheck,
  IconChecklist,
  IconListCheck,
  IconProgress,
  IconProgressCheck,
  IconCircleDot,
  IconCircle,
  IconCircleX,
  IconAlertCircle,
  IconAlertTriangle,
  IconInfoCircle,
  IconQuestionMark,
  IconHelp,
  IconBell,
  IconBellRinging,
  IconBellOff,
  IconLock,
  IconLockOpen,
  IconShield,
  IconShieldCheck,
  IconEyeCheck,
  IconEyeOff,
  IconThumbUp,
  IconThumbDown,
  IconMoodSmile,
  IconMoodSad,
  IconMoodHappy,
  IconMoodCry,
} from '@tabler/icons-react';

export const statusIcons: IconCategory = {
  name: 'Status',
  icons: [
    { name: 'check', icon: IconCheck },
    { name: 'circlecheck', icon: IconCircleCheck },
    { name: 'circlecheckfilled', icon: IconCircleCheckFilled },
    { name: 'squarecheck', icon: IconSquareCheck },
    { name: 'checklist', icon: IconChecklist },
    { name: 'listcheck', icon: IconListCheck },
    { name: 'progress', icon: IconProgress },
    { name: 'progresscheck', icon: IconProgressCheck },
    { name: 'circledot', icon: IconCircleDot },
    { name: 'circle', icon: IconCircle },
    { name: 'circlex', icon: IconCircleX },
    { name: 'alertcircle', icon: IconAlertCircle },
    { name: 'alerttriangle', icon: IconAlertTriangle },
    { name: 'infocircle', icon: IconInfoCircle },
    { name: 'questionmark', icon: IconQuestionMark },
    { name: 'help', icon: IconHelp },
    { name: 'bell', icon: IconBell },
    { name: 'bellringing', icon: IconBellRinging },
    { name: 'belloff', icon: IconBellOff },
    { name: 'lock', icon: IconLock },
    { name: 'lockopen', icon: IconLockOpen },
    { name: 'shield', icon: IconShield },
    { name: 'shieldcheck', icon: IconShieldCheck },
    { name: 'eyecheck', icon: IconEyeCheck },
    { name: 'eyeoff', icon: IconEyeOff },
    { name: 'thumbup', icon: IconThumbUp },
    { name: 'thumbdown', icon: IconThumbDown },
    { name: 'moodsmile', icon: IconMoodSmile },
    { name: 'moodsad', icon: IconMoodSad },
    { name: 'moodhappy', icon: IconMoodHappy },
    { name: 'moodcry', icon: IconMoodCry },
  ],
};


import {
  IconGift,
  IconBalloon,
  IconConfetti,
  IconSparkles,
  IconWand,
  IconCrown,
  IconAward,
  IconTrophy,
  IconMedal,
  IconRosette,
  IconDiamond,
  IconDiamondFilled,
  IconKey,
  IconLighter,
  IconBulb,
  IconBulbOff,
  IconUmbrella,
  IconSunglasses,
  IconEyeglass,
  IconClock as IconWatch,
  IconDeviceWatch,
  IconBattery as IconBatteryFull,
  IconBatteryCharging as IconBatteryCharge,
  IconPlug,
  IconBolt,
  IconAnchor,
  IconLifebuoy,
  IconCompass as IconCompassObj,
} from '@tabler/icons-react';

export const objectsIcons: IconCategory = {
  name: 'Objects',
  icons: [
    { name: 'gift', icon: IconGift },
    { name: 'balloon', icon: IconBalloon },
    { name: 'confetti', icon: IconConfetti },
    { name: 'sparkles', icon: IconSparkles },
    { name: 'wand', icon: IconWand },
    { name: 'crown', icon: IconCrown },
    { name: 'award', icon: IconAward },
    { name: 'trophy', icon: IconTrophy },
    { name: 'medal', icon: IconMedal },
    { name: 'ribbon', icon: IconRosette },
    { name: 'diamond', icon: IconDiamond },
    { name: 'gem', icon: IconDiamondFilled },
    { name: 'key', icon: IconKey },
    { name: 'lighter', icon: IconLighter },
    { name: 'flashlight', icon: IconBulb },
    { name: 'bulb', icon: IconBulb },
    { name: 'bulboff', icon: IconBulbOff },
    { name: 'umbrella', icon: IconUmbrella },
    { name: 'sunglasses', icon: IconSunglasses },
    { name: 'glasses', icon: IconEyeglass },
    { name: 'watch', icon: IconWatch },
    { name: 'smartwatch', icon: IconDeviceWatch },
    { name: 'batteryfull', icon: IconBatteryFull },
    { name: 'batterycharge', icon: IconBatteryCharge },
    { name: 'plug', icon: IconPlug },
    { name: 'bolt', icon: IconBolt },
    { name: 'zap', icon: IconBolt },
    { name: 'anchor', icon: IconAnchor },
    { name: 'lifebuoy', icon: IconLifebuoy },
    { name: 'compassobj', icon: IconCompassObj },
  ],
};


export const ICON_CATEGORIES_FULL: IconCategory[] = [
  activityIcons,
  healthIcons,
  workIcons,
  foodIcons,
  financeIcons,
  socialIcons,
  natureIcons,
  travelIcons,
  statusIcons,
  objectsIcons,
];

export const ALL_ICONS_FULL: IconDefinition[] = ICON_CATEGORIES_FULL.flatMap(cat => cat.icons);

export const ICON_MAP_FULL = new Map<string, TablerIcon>(
  ALL_ICONS_FULL.map(({ name, icon }) => [name, icon])
);

export function getIconByNameFull(name: string): TablerIcon | undefined {
  return ICON_MAP_FULL.get(name);
}
