export const MODEL_SELECTOR_LABEL_HEIGHT = 34
export const MODEL_SELECTOR_ROW_HEIGHT = 40
export const MODEL_SELECTOR_DROPDOWN_WIDTH = 432
export const MODEL_SELECTOR_DROPDOWN_FALLBACK_MAX_HEIGHT = 460
export const MODEL_SELECTOR_DROPDOWN_MAX_HEIGHT = 'min(460px, calc(100vh - 96px))'
export const MODEL_SELECTOR_LIST_HEIGHT = 'min(386px, calc(100vh - 170px))'
